### ISSUE TITLE
Add links to online exercises from online student view coach report.

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#1034]
Right now, there are no links to the topics nor exercises in online coach reports, making it more challenging to understand exactly what students are doing (or what exercises they are struggling with).

We can either:
* Get an online, demo version of KA Lite, and have any central server links to main URLs be redirected there
* Similar logic, but for actual KA exercise pages.

**Comment by aronasorman** [comment]
Not a priority; reopen if requested.
