### ISSUE TITLE
Linux: "sudo service kalite" does not validate keyword argument

### ISSUE THREAD

**Issue by gimick** [learningequality/ka-lite#1050]
this command is incorrect

pi@pi7 ~ $ sudo service kalite sto

but no error is given,

probably should list available keywords (start, stop)

**Comment by benjaoming** [comment]
Works with the debian distribution's state of the art service script.

```
➜  ka-lite git:(0.16.x) sudo service ka-lite horse
 * Usage: /etc/init.d/kalite {start|stop|restart|status}
```
