### ISSUE TITLE
Allow admins to initiate download from a missing video page

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#1054]
We can have a direct link to the video update page, with that video checked.  We could also have a link that auto-launches videodownload directly.

![screen shot 2013-11-16 at 12 07 33 pm](https://f.cloud.github.com/assets/4072455/1557041/c4ef6fda-4efa-11e3-83b6-797e0c2963db.png)

**Comment by rtibbles** [comment]
Not going to happen within the scope of KA Lite.
