### ISSUE TITLE
Improve CSV download user experience

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#1059]
Suggestion:
* A single "export" button.
* When clicked, a dialog appears in the same area of the screen.
* Dialog has four lines: start date, end date, format (radio buttons), and submit button

![image](https://f.cloud.github.com/assets/4072455/1558658/6c0519dc-4fa0-11e3-9af3-4dce6969044c.png)

**Comment by 66eli77** [comment]
fixed
