### ISSUE TITLE
Architectural & code review of current registration and syncing systems

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#1077]
Things that we want to review before releasing to the wild:

Automated registration & decentralized zones:
* Self-generated zones
* Zone Invitations
* Chain of Trust computations

Deferred signing and counting:
* Code to defer signing until sync
* Code to defer counting until sync

These items, along with the i18n, are the major incomplete items for release-0.11.  

@jamalex can we schedule specific dates for each of these?  I could be flexible with my availability to help make them happen!

Thanks!

**Comment by aronasorman** [comment]
We're practically doing this with the flexmodels syncing in the works. I'd rather we close this, since this is such a vague issue.
