### ISSUE TITLE
Explicitly show current path and don't require extra confirmation during install script

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#1096]
While running the install script (in the newest -- 999 -- branch).

**Observed:**

```
Please enter the directory where you'd like to install KA Lite (blank=.): 
.: Directory exists; install? [Y/n]
```

**Potential improvement:**

```
Please enter the directory where you'd like to install KA Lite (enter=/home/blah/curpath): 
```
(and then, it wouldn't confirm existence if it's the current path, only if it's some other path)

**Comment by 66eli77** [comment]
will be irrelevant once installer wizard done
