### ISSUE TITLE
Weird interaction between SessionStorage for messages and cached_db session engine

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#1121]
**Observed:**

Messages persisting across pages.

**Conditions to replicate:**

In local_settings.py, set:
`SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"`

Then, run `./manage.py runserver`. Visit a video page for a video that hasn't been downloaded, to get the "Video not downloaded" message to show (easiest way is via searching). Then, load a non-video page (e.g. again via searching). Most of the time, the "Video not downloaded" message will be shown again on this page.

Setting `MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage`, or leaving `SESSION_ENGINE` as the default avoids this, so it's not a high priority issue. But it was annoying to try to debug, so wanted to put it up here for historical reference.

**Comment by aronasorman** [comment]
Is this still an issue? Reopen if needed.
