### ISSUE TITLE
Revisit what we include/exclude from the topic tree

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#1132]
`kalite/khanload/management/commands/khanload.py` has a `slug_blacklist` that excludes particular topics from being included. Some of the exclusion is due to licensing issues (e.g. partner-content), some due to lack of support (e.g. cs), and some due to potential lack of relevance (e.g. the grade level topics as discussed in #1070).

I've reached out to KA to clarify the licensing of some of the content, so that we can rely more on the `ka_user_license` field returned by the API, and use this instead of some of the manual blacklisting.

It would also be great to look at what's being excluded by the "cc-third-grade-math" through "cc-eighth-grade-math" topics, and make sure all that content also exists elsewhere in the topic tree.

**Comment by aronasorman** [comment]
Stale issue.
