### ISSUE TITLE
Missing language tag => language mappings in languagelookup.json

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#1139]
WARNING:kalite:Please add the following language codes to /Users/bcipolli/FLE/central/dev1/kalite/static/data/i18n/languagelookup.json:
	['aka', 'bug', 'ceb', 'cho', 'efi', 'en-GB', 'es-AR', 'es-MX', 'es-NI', 'fr-CA', 'ful', 'fy-NL', 'hau', 'ibo', 'ilo', 'inh', 'iro', 'kar', 'kik', 'kon', 'lin', 'luo', 'meta-GEO', 'meta-TW', 'meta-WIKI', 'mlg', 'mo', 'moh', 'mos', 'nya', 'oji', 'orm', 'pan', 'pnb', 'prs', 'pt-BR', 'que', 'rup', 'ry', 'sh', 'sna', 'som', 'sot', 'sr-LATN', 'swa', 'tet', 'tir', 'tlh', 'tsn', 'umb', 'wol', 'xho', 'yor', 'zh-CN', 'zh-HK', 'zh-SG', 'zh-TW', 'zul']

@dylanjbarth could you fill these in?  Note that these should be in IETF format (as shown above), not Django/underscored.  Captialization should matter

**Comment by aronasorman** [comment]
Not a priority; let's open another issue if this comes up.
