### ISSUE TITLE
Teachers can earn points, but they only show up as a global tally temporarily

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#1171]
After a teacher watches part of a video:

![image](https://f.cloud.github.com/assets/618416/1642535/5d3e61d6-588a-11e3-9c1f-256b87abd255.png)

After refreshing the page:

![image](https://f.cloud.github.com/assets/618416/1642538/97735e42-588a-11e3-9607-5c2c87f18d2d.png)

Then, going to an exercise page and answering some questions:

![image](https://f.cloud.github.com/assets/618416/1642542/c17a1802-588a-11e3-9e62-5ad1eab0ad35.png)

**Observations:**

1. Teachers can earn points on videos and exercises, and they persist.
2. A global tally is not calculated; the top right just shows the points earned on the current page since refreshing.

**Recommendations:**

It's nice to allow teachers to earn points, so that should stay. But they should either not be shown a global tally, or (preferred) the tally should actually be global (as for students).

**Comment by 66eli77** [comment]
we don't show points earned by teacher anymore
