### ISSUE TITLE
Can KA Lite indicate a missing video codec to user?

### ISSUE THREAD

**Issue by gimick** [learningequality/ka-lite#1183]
latest 0.11.1; disconnected server, acting as wireless point.

When viewing a video, the png file is shown, but clicking the video returns 304 not mofified and nothing happens.

EDIT:
This is a missing codec issue on chromium (mp4 support not active in ubuntu and presumably debian)
Question: can ka-lite detect a failure to launch the video, or missing codec? and give the student some information?

**Comment by aronasorman** [comment]
Not a priority; reopen if needed.
