### ISSUE TITLE
Plans for P2P Replication?

### ISSUE THREAD

**Issue by rjsteinert** [learningequality/ka-lite#12]
Hi all -
I'm just starting to sink my teeth into this code and I must say awesome job!  I noticed on Jamie's blog that he mentioned ["in the current iteration, syncing is only done via the central server, but the way records are stored will support P2P syncing through the same mechanism, once a few details have been worked out."](http://jamiealexandre.com/blog/2012/12/12/ka-lite-technical-aspects/)  I'm really excited about this feature because we're using CouchDB for P2P replication at [Open Learning Exchange](https://github.com/open-learning-exchange) but I'm also interested in APIs like U1DB (http://packages.python.org/u1db/reference-implementation.html).  What direction might KA Lite take to solve P2P Replication?

Thanks!
-RJ

**Comment by MCGallaspy** [comment]
Thread is stale. Idea is in the pipeline.
