### ISSUE TITLE
Report IP address of ka-lite on GUI

### ISSUE THREAD

**Issue by jeepurs** [learningequality/ka-lite#1225]
[suggested by the Sparks]

In some deployment locations, the local network used dynamic assignments of IP addresses.  This makes it difficult for the user to sign into KA Lite.

Suggestion: To report the IP address in the GUI that has the Start Server/Stop Server buttons.

@jamalex @bcipolli @ruimalheiro @rtibbles @aronasorman @wangguan59

**Comment by jamalex** [comment]
Still needed, but added to https://github.com/learningequality/installers/issues/6#issuecomment-73297876
