### ISSUE TITLE
Allow for Tabular Coach Report to be more Top-Level

### ISSUE THREAD

**Issue by jeepurs** [learningequality/ka-lite#1226]
[suggested by the Sparks]

In some classrooms where students are choosing their own subjects to learn, teachers may want to use the Coach Reports to see how students on doing on their respective topics.  It would be useful to

1) have a "feed" like interface to see recent activity  OR

2) (more simply) have a Tabular Coach Report that allows for all the topics (not the exercises) to be on one grid.

@bcipolli @jamalex @aronasorman @rtibbles @dylanjbarth @wangguan59 @ruimalheiro

**Comment by rtibbles** [comment]
Superseded by #1871
