### ISSUE TITLE
Syncing mechanism can skip records on cancelled / resumed sync, if dependencies have higher counters than records that depend on them.

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#1257]
From #1185: 
>Device / DeviceZone / Zone objects must be synced before any others, due to dependencies. As soon as they are synced in syncmodels, they will increment counters. That is OK, since the "low watermark" counter for the device is mem-cached during the process, and so as long as the process continues, everything will be synced.
>
>However, if the syncmodels process is halted before completion, since the Device object update set the counter high, any remaining models will be skipped.
>
>Indeed, this should be a problem across all model dependencies, not just in this scenario. Really, objects should be sent over the wire in order of their counter position; however, dependencies make this not possible to do. Some mix between counter position and dependency needs to be done, such that the replication engine is fail-safe.

**Comment by aronasorman** [comment]
@jamalex is this still a problem with the current codebase? If so, please reopen.

**Comment by jamalex** [comment]
This should be resolved, as we don't increment counters for initial device/zone sync now. Thanks!
