### ISSUE TITLE
Move cronserver PID code into Python-side

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#1260]
Currently, windows and linux scripts have different ways to start/stop the cron server.  Windows launches the cron server using subprocess, and stores the PID--then used to kill.  Linux launches using the background `&` operator, and does a kill based on task name.

More consistent and clean approach would be to save the PID as a file--much like cherrypy does--from within the cron server process.  If it could launch itself in daemon mode, even better.

**Comment by aronasorman** [comment]
Fixed in latest develop.
