### ISSUE TITLE
Create backup of JSON files before writing to them

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#1301]
If, for any reason, the language pack update process is killed (for example, no memory), the JSON files can be only partially written.  If so, then they are unrecoverable, and data has to start from scratch.

In order to be more robust, we could make temp copies of all JSON files before writing.  If, on re-run of scripts the JSON files are found to be corrupted, we could look to restore them from the backup location.

I'm looking at you, `srts_remote_availability.json` :)

**Comment by aronasorman** [comment]
Not a priority; let's open another issue if this is a big problem. `update_language_packs` should only be run on the central server anyway, which should have adequate memory.
