### ISSUE TITLE
Indicate to admins on navbar when downloads are in progress

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#1309]
Admins can launch `videodownload` and `languagepackdownload`, but don't need to stay on the pages while the downloads are in progress.

It would be *slick* if we had an indicator on the navbar as to the download progress.  T

his could easily be implemeted: 
* Within the `status` method, we could query out the current progress for any open `videodownload` or `languagepackdownload` process (for non-admins, or if the processes are not active, we just return None).
* When rendering the navbar, we can have some (semi-opaque) div whose size we adjust to the % complete of the process.  I would make it as the background of the navbar items, but only because I'm like that :)

**Comment by 66eli77** [comment]
could be a nice experimental project for React.js

**Comment by benjaoming** [comment]
If people use browser tabs, this won't be a problem. Furthermore, the progress bars pick up when you close and revisit the video and content pack download pages.
