### ISSUE TITLE
Allow admins to (locally) hide unwanted groups and users

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#1342]
When syncing hasn't occurred since object creation, deletion is fine.  However in other cases, deletion is not currently possible.

In this case, we can add an option to the admin interface to hide the unwanted users, along with a link to "show hidden" (and some text somewhere indicating the # of hidden objects, in each view).

**Comment by aronasorman** [comment]
Not a priority; let's open another issue when we want to revisit this.
