### ISSUE TITLE
Downloads are not robust to unreliable connections

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#1387]
Now that language packs are large files, rather than small individual files, it is much less likely that people with unreliable connections will be able to download them.  Their connection is unlikely to ever allow downloading a 10MB file without interruption, whereas it was more likely to allow downloading of small 10-15kb files (and those that failed could be hit simply by re-running the downloads).

We absolutely need to make our system robust to unreliable connections; otherwise, we're potentially cutting people off from resources they've previously had (subtitles).

@aronasorman or @jamalex any ideas?

**Comment by aronasorman** [comment]
Closing; the workaround right now is to download videos somewhere where there's reliable internet, then transfer videos through USB. Let's open another issue if we hear that this is a problem.
