### ISSUE TITLE
Backup the database.

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#1413]
We are using SQLite. It should be awfully trivial to back this up, both for a certain time interval, and for critical periods like:
1. Database migrations
2. Code updates

... although 1. and 2. may be triggered by the same event. IN ANY CASE, WE GOTTA HAVE THIS! Even just a naive one without any rotation or online backup.

**Comment by anuragkanungo** [comment]
@aronasorman @rtibbles ,
We can use some of the feature from this package:
https://pypi.python.org/pypi/django-dbbackup/1.9.0

**Comment by aronasorman** [comment]
Oh! This looks like a great intern project.

**Comment by SG345** [comment]
I discussed about this feature with my mentor, @aronasorman. This is what we are thinking of going ahead with:

1. We can use the backup/restore features from django-dbbackup package.
2. We can implement the FIFO scheme first, by creating a Django app inside 'kalite'. Depth of the FIFO scheme could be 1, as suggested by everyone here.

**Comment by aronasorman** [comment]
First pass implemented in #4289.

**Comment by SG345** [comment]
@aronasorman: The backup as of now resides locally on the system. What if we could store all the backups online? Goal for iteration 2?
