### ISSUE TITLE
Indicate whether there are language pack updates available, with fewer clicks necessary.

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#1430]
It takes 2 clicks to check whether there are updates to language packs available.  Since this is critical to the admin workflow that we're forcing, we should expose this information more globally.

Step 1 would be to remove a click by indicating in the videos update page.  Or, we could just finish out the new admin page, which has a direct link to languages.

Step 2 would be to indicate this in the status bar.

**Comment by aronasorman** [comment]
Not necessary anymore, once we have installers with prebuilt language packs: https://github.com/learningequality/ka-lite/issues/3359
