### ISSUE TITLE
Script to launch server at startup on windows doesn't work on Windows Server 2008

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#1478]
Saw this while at Gitwe--the script doesn't work.
add_systemstart_task.bat

It adds a task, but that task fails to run, it doesn't have quite the right settings on it.

This is really important (TM)

**Comment by aronasorman** [comment]
Windows 2008 is unsupported for now. Let's open another issue if we have the bandwidth to support the Windows Server platform.
