### ISSUE TITLE
Indicate # of correct trials remaining, instead of points, on exercise progress bar

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#1548]
We've heard that loss of points can be demotivating.  Rather than specifying points as gained, perhaps indicate a "bank" of points (above the progress bar) that **would** be earned if you finish progress, along with an indicator how far along you are in progress (i.e. 2/10).

Currently, it's hard to see how far along you are, especially because of the randomness in point earning.  It's also demotivating to lose points you seemingly already had.

Should be a relatively simple fix in terms of UI and back-end logic.  @rtibbles what do you think? :D

(screen shot just as a point of reference)
![screen shot 2014-02-13 at 6 25 32 pm](https://f.cloud.github.com/assets/4072455/2200678/7ff33a30-98e5-11e3-88dc-f5d0116b319a.png)

**Comment by rtibbles** [comment]
Fixed with new attempt indication system.
