### ISSUE TITLE
Help docs on local server

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#158]
Given that we are rolling out KA Lite not just internationally, but domestically, we have no excuse left NOT to provide help documents on distributed server installs.

English only is better than nothing.

In addition, providing help docs inside our code base would help make the docs specific to the different versions of KA Lite.

Rather than implementing help docs on the Wiki, I suggest we create a Django app for getting this done, and look for help in getting docs shippable with each install.

I've assigned this to the HTH deployment.  To be honest, I'm a bit embarrassed to send KA Lite to HTH without any help documents for getting students up to speed.

**Comment by MCGallaspy** [comment]
Done.
