### ISSUE TITLE
The ergonomics of KA Lite

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#1611]
One of the somewhat concerning observations that came out of recent feedback from the Nalanda classrooms was that some students were getting _so_ engaged and focused on their learning with the KA Lite tablets that they may have neglected to move, leading to ergonomic issues.  One student “didn’t want to get up from the tablet, [...] focusing on that only”, and ended up with a crick in her neck that she noticed in the dance class that followed. Another student learned her own ergonomic lesson after spending a class period answering math exercises so intently that it took a moment to be able to extend her arm fully again afterwards, so the next class period with the tablets, she made sure to stretch her arms from time to time.

Considering these observations, it may be worth looking into including ergonomic reminders interspersed with the videos and exercises, encouraging stretching, breaks, and good posture.

**Comment by 66eli77** [comment]
really like this idea, won't close it during this issue triaging

**Comment by 66eli77** [comment]
really like this idea, won't close this during this issue triaging.

**Comment by benjaoming** [comment]
I really like this idea, too :)

**Comment by benjaoming** [comment]
This issue was moved to learningequality/kolibri#1282

**Comment by indirectlylit** [comment]
FYI, migrating to trello instead because it's not an immediately actionable issue: https://trello.com/c/WukThURt/802-ergonomic-reminders-interspersed-with-the-videos-and-exercises-encouraging-stretching-breaks-and-good-posture
