### ISSUE TITLE
Cannot download Khan Academy user data to KA Lite when distributed server is not web-accessible

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#1633]
This does not work when going through our production server, but does work when testing through the adhoc server

Production result (latest `release-0.11`):
![screen shot 2014-02-26 at 5 52 37 pm](https://f.cloud.github.com/assets/4072455/2278314/ecea237a-9f51-11e3-9158-37788536e90b.png)

Adhoc result (latest `release-0.11`):
![screen shot 2014-02-26 at 5 52 24 pm](https://f.cloud.github.com/assets/4072455/2278316/f24b39b2-9f51-11e3-8796-2f954f2e711c.png)

@jamalex I believe the above suggests that a change to the ansible scripts to make this work would be necessary, so assigning to you.  Let me know if you feel that's not appropriate!

Thanks!

**Comment by rtibbles** [comment]
Feature not currently extant.
