### ISSUE TITLE
Clicking on a video's text title in the video download topic tree causes a script error

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#1637]
Clicking should select the item.  Currently, only clicking the checkbox works.

Should be fast to fix and improve the video download UX, so targeting for 0.11.1
![screen shot 2014-02-27 at 6 24 33 am](https://f.cloud.github.com/assets/4072455/2283278/05377f7c-9fbb-11e3-92a3-a3319adbdf70.png)

**Comment by aronasorman** [comment]
Fixed in latest develop.
