### ISSUE TITLE
Allow for video management/download from  youtube for Lexlike localized videos

### ISSUE THREAD

**Issue by mjptak** [learningequality/ka-lite#1688]
Including videos in lexlike trees works great but don't seem to be found when trying
to do updates (or deletes).  
![screen shot 2014-03-07 at 10 30 06 am](https://f.cloud.github.com/assets/856425/2359302/19ade5de-a616-11e3-8aa8-9337f3583b61.png)
![screen shot 2014-03-07 at 10 30 35 am](https://f.cloud.github.com/assets/856425/2359304/2120734a-a616-11e3-930b-30ac3e0b9a61.png)

**Comment by aronasorman** [comment]
This is more appropriate as a Kolibri question, and not for KA Lite.
