### ISSUE TITLE
Embedded video playing on RPi, as a client

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#169]
Received through email:

There are three changes to the configuration that need to be done in order to get the videos to play nicely on a RPi.

1. Sound configuration.

The sound output control in /var/lib/alsa/asound.state is control 3. It takes the following values:

0 - auto - If the display is using hdmi then route the audio output to hdmi. If the display is using composite, then route the audio to the audio jack.
1 - audio jack - Force the audio to the audio jack.
2 - hdmi - Force the audio to hdmi.

This control is set to zero in the initial installation of raspbian. The documentation says to use the aset utility to set  the values of this control. DO NOT USE ASET. It will put stuff in this file that belongs in a different file. It will not have the desired effect and will set the volume to nil. Instead edit asound.state by hand:

sudo nano /var/lib/alsa/asound.state

We change the value of control 3 to 1, because we have hdmi displays that do not support sound, and use earbuds through the audio jack. This edit will not take effect until the next boot. If you shutdown or reboot by issuing commands, the edit just made will be overwritten. Instead, just pull the plug. When you plug it back in, you will have the desired result. 

2. Use omxplayer for html5 video display. (This will make the display of videos smooth if there is enough bandwidth between the server and client...which there usually is.)

Install the media-berry package as described in http://lin.jojen.de/?p=32. Prior to a week ago, this package did not work with KA-Lite. I diagnosed the problem, and told Jojen about it. (I am mannyack.) He fixed it.

I also complained to him that media-berry currently does not support subtitles. He is looking at it.

3. Take care of the black screen after omxplayer finishes playing a video.

Edit the omxplayer shell script:

sudo nano /usr/bin/omxplayer

and insert "exit 0" as in the following snippet:

…
LD_LIBRARY_PATH=$OMXPLAYER_LIBS:$LD_LIBRARY_PATH $OMXPLAYER_BIN “$@”; true
exit 0
if [ -e $FBSET ]; then
…

**Comment by rtibbles** [comment]
This should be fixed now that the Raspberry Pi browser is using GPU acceleration.
