### ISSUE TITLE
Separate specification of central server protocol by app

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#1717]
We have multiple settings that relate to the host and protocol for connecting to the central server, including `CENTRAL_SERVER_DOMAIN`, `CENTRAL_SERVER_HOST`, and `SECURESYNC_PROTOCOL`.

We have identified multiple problems with this, including (but not limited to):
1. (as per discussion on #1715) These should not be global cross-app settings. Refactored apps (i18n, video updates, etc) should default to the global host/protocol settings, but also be able to override them with their own.
2. `SECURESYNC_PROTOCOL` is not a good general-purpose name. Probably something like `CENTRAL_SERVER_DEFAULT_PROTOCOL` (and similarly, `CENTRAL_SERVER_DEFAULT_HOST`) would be better for the global default settings.
3. These settings (especially the protocol) are not being used reliably throughout the codebase; often the protocol is hard-coded as "http" (e.g. [here](https://github.com/jamalex/ka-lite/blob/06d95d7fc369871f8a398530d002a57bb9412227/kalite/templates/updates/update_languages.html#L50). Everywhere we reference the central server, the URL should be built from these settings.

**Comment by benjaoming** [comment]
Agreeing with this, but it will inevitably be picked up if a greater settings refactor occurs as of #4054
