### ISSUE TITLE
Remove inter-app dependencies on globally-defined settings

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#1733]
As we try to break inter-app dependencies and make it easier to both import external code (with their own static files, templates) and export internal code (as we try to make sensible, potentially reusable apps), it's important to write encapsulated apps.

Steps done so far:
* Break unnecessary inter-app dependencies
* Separate `settings.py` by app
* Separate `templates` by app

This step:
* Remove inter-app dependencies on globally-defined settings
    * Remove the need for `PROJECT_PATH`, `DATA_ROOT`, and other shared global settings.  Instead, define them within an app (where possible).

Future steps:
* Segregate static files by app (#1731)
* Move app-specific data to `{app}/data/` (#1732)

**Comment by aronasorman** [comment]
Fixed in latest develop. Things are pretty separate now.
