### ISSUE TITLE
Improve UX of tabular Coach Reports

### ISSUE THREAD

**Issue by dylanjbarth** [learningequality/ka-lite#1748]
@rtibbles you'll love this

Instructure (from OpenEd conf we went to back in November) is introducing mastery based __grading__ into Canvas (which is open source). 

Check out the screenshot of their new reporting tool in this article https://www.edsurge.com/n/2014-03-19-endangered-report-cards

Some simple tweaks that could make our tabular reports... dare I say.. beautiful?

**Comment by 66eli77** [comment]
it is being refactored.
