### ISSUE TITLE
"check answer" button stays the same when the answer is wrong

### ISSUE THREAD

**Issue by n-kim** [learningequality/ka-lite#1752]
![screen shot 2014-03-19 at 9 57 14 am](https://f.cloud.github.com/assets/6885676/2463051/c8b1fa5a-af87-11e3-98da-b58ea7bbddb4.png)

when you enter a wrong answer, the "Check answer" button responds by moving left and right. does not change otherwise. Hard to see if they got the answer wrong

to be clear, the button should turn red or say "Incorrect! Try again"

**Comment by rtibbles** [comment]
No longer extant.
