### ISSUE TITLE
start.sh fails silently if user encounters permissions problems

### ISSUE THREAD

**Issue by usernamenumber** [learningequality/ka-lite#1760]
I had a problem with start.sh appearing to succeed, but not resulting in a server listening on any of the given URLs (Edubuntu 12.0.4). 

It turned out that because I had done the initial git clone as via sudo (due to laziness and not having write perms to the directory where I wanted ka-lite to live), everything started out owned by (and in some cases writable only by) root. 

When I ran start.sh as non-root, it printed the expected success messages and list of URLs, but none of them worked because somewhere in there the permissions issue cases the server to fail silently. 

Using chown -R to change the ownership of everything resolved the problem. 

Adding some ownership/permissions checks  to setup_linux.sh would address this.

**Comment by 66eli77** [comment]
will not be relevant anymore once installers all implemented

**Comment by aronasorman** [comment]
`start.sh` has been replaced by `bin/kalite start`, which throws an error.
