### ISSUE TITLE
Editing details should not be separate from viewing details

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#1773]
Currently for facility management, zone management, user management, and the like, we can view summaries of details, but then need to link to a separate page to edit them. This is an unnecessary burden on the user.

I propose the following changes:
* For facility, zone, device, group, user etc. all detail views should also have the ability to edit those details built into the page.
* I think this would be best implemented using Backbone, so that data saving calls can be made via an API without having to refresh the page.

@bcipolli @aronasorman @wangguan59 @jdklein @jamalex @kennahasson 

Thoughts, ideas, worries?

**Comment by 66eli77** [comment]
not a pressing issue
