### ISSUE TITLE
Indicate to user if they may be behind a firewall.

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#1779]
If a user is behind a firewall, they'll be told they are not connected to the Internet and need to go online.  This false error message is confusing.

Better error message would be more informative ("`We couldn't connect to our server.`") and would suggest better resolution (perhaps linking to a wiki-based user's manual: "`Please `[click here](wiki url)` for information about resolving this connectivity issue.`"

**Comment by aronasorman** [comment]
not a priority; reopen if it's a big UX issue.
