### ISSUE TITLE
Indicate to users that facility metadata is incomplete

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#1808]
If we could indicate this to users, perhaps we could get better metadata.  Make sure address, latitude/longitude, and # of users are complete--otherwise indicate to users (perhaps a yellow-highlighted row, and a flashy link saying "add info about facility" for each facility)

![image](https://cloud.githubusercontent.com/assets/4072455/2564937/629c0dc8-b8ab-11e3-97cd-10d8ebb3d371.png)

**Comment by benjaoming** [comment]
Since #3908 was merged, I'm gonna go ahead and close this, please feel free to reopen. Thanks @askerry
