### ISSUE TITLE
Search Result can be made in to columns based on Topic Video Exercise 

### ISSUE THREAD

**Issue by deebee07** [learningequality/ka-lite#1825]
Branch: Develop

Current Behavior: Search Results display  as TOPIC VIDEO EXERCISE as a long vertical list with less utilization of the screen on display to the user 

![screenshot from 2014-04-01 12 54 54](https://cloud.githubusercontent.com/assets/6391037/2576437/bed419aa-b96e-11e3-80d5-5a09abb9139f.png)

Expected Behavior: Search Results can be displayed in columns Vertically with the search results, so the user can easily select the desired result and save time and that will give a better presentation of Search Results 
![screenshot from 2014-04-01 13 09 44](https://cloud.githubusercontent.com/assets/6391037/2576594/e3917b82-b970-11e3-9dbf-4284f03c0b58.png)

**Comment by aronasorman** [comment]
Closing. Reopen if it's a big UX issue.
