### ISSUE TITLE
No way to search a video to download

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#1828]
I have a video to download: "Basic set notation".  How can I most efficiently find it to download?

**Current behavior:**

I have to search the video to get the path, copy the path so it persists, then use the path to try and drill down to the actual video.  Note from #1608 I can't even depend on any clear order, and slugs and titles differ quite a bit.

**Expected behavior:**

Worst case: search the video title, browse to the video, and have a link that will bring me back to the update page with that video selected.

Best case: on-page search box that will open the video download topic tree with a searched video that I select.

**Comment by benjaoming** [comment]
For all use cases, that I can think of, this isn't very essential -- or at least won't hinder any real use of KA Lite. Closing and suggesting someone needing it to feel invited with a PR :)
