### ISSUE TITLE
Add edit link on devices from zone_management page

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#1844]
Allow editing of device info (name) from the zone_management page.  Should work just like facility (but we'll need a form for it).

![screen shot 2014-04-01 at 11 33 07 pm](https://cloud.githubusercontent.com/assets/4072455/2587997/92ce142e-ba30-11e3-8420-280a336a4f85.png)

**Comment by aronasorman** [comment]
Not a priority; let's open another issue if this is a big UX problem.
