### ISSUE TITLE
No indication that deletion of video will remove it from multiple topics.

### ISSUE THREAD

**Issue by him-28** [learningequality/ka-lite#1849]
**Current behavior:**

When a video is selected in the topic page, there is no indication that the video will be deleted from multiple topics.  This could be unexpected to users.

**Expected behavior:**

Indicate to users before deletion when deleting a video that exists in multiple topics.

==== 
Original title: Downloading/Deletion of Video with same name under different topic will lead to ambiguity for user

Original text:

Branch: Nalanda-RCT1

Expected Behavior: On selecting a specific video for downloading under some topic on completion should show completed symbol in that topic only  even the same video is present in different topic  .

Current Behavior: Selected one video for downloading .
![screenshot from 2014-04-02 17 05 28](https://cloud.githubusercontent.com/assets/6395045/2590405/01748144-ba5c-11e3-9fed-f6cedbe3d0a8.png)

During downloading other topic with same name also shows content is downloading in it.
![screenshot from 2014-04-02 17 05 49](https://cloud.githubusercontent.com/assets/6395045/2590421/2827cdd2-ba5c-11e3-846c-a81caf4473d3.png)

![screenshot from 2014-04-02 16 57 20](https://cloud.githubusercontent.com/assets/6395045/2590440/7e2378da-ba5c-11e3-8981-7bb8eb566e68.png)

Now during deletion of that video only one instance is selected.
![screenshot from 2014-04-02 16 57 55](https://cloud.githubusercontent.com/assets/6395045/2590452/c6ddd660-ba5c-11e3-8169-ea48c95ef38c.png)

Now with user point of view when we delete same name video from one topic other is also deleted this will create two problem user unknowingly deleting other topic video because only one instance is downloaded else if we download same twice space is consumed.
![screenshot from 2014-04-02 16 58 25](https://cloud.githubusercontent.com/assets/6395045/2590497/7f2d0fe2-ba5d-11e3-9a65-cd84d7f4087a.png)

Steps to reproduce:
1. Click videos option 
2. Click on Partner Content to download Introduction to light from Nasa/Measuring the universe/spectroscopy

**Comment by aronasorman** [comment]
Not a priority; let's open another if this is a big UX problem.
