### ISSUE TITLE
[Optional But Useful]  Password Checker

### ISSUE THREAD

**Issue by deebee07** [learningequality/ka-lite#1853]
Branch: nalanda-rct1

Expected Behavior: A program/script that checks whether the password is weak, medium or strong depending what the user has typed in.This will check how many uppercase, lowercase and numbers have been entered and then tell the user how strong their password is.
We can modify this to even put a password restriction when a users sets the password on the SIGN UP page 

Current Behavior: Doesn't Exist

Steps to reproduce:
1. Go to the "Users" option
2. Go to the "Coaches" option
3. Go to Add a New Teacher

![screenshot from 2014-04-02 18 07 54](https://cloud.githubusercontent.com/assets/6391037/2590855/b0cdebc4-ba63-11e3-899b-f62fb12adc6d.png)

**Comment by benjaoming** [comment]
Nobody seems to have been pitching this for a long time. Truth is that password security is very rarely an issue in offline contexts.

@deebee07 feel invited to check out the successor of KA Lite which is much more modern and will be available later in '17: http://learningequality.org/kolibri
