### ISSUE TITLE
No facility to set a new password, when old password is lost

### ISSUE THREAD

**Issue by codemania113** [learningequality/ka-lite#1858]
Branch: nalanda-rct1

Current Behavior: Once coach sets a password, he can't change his password to a new one.
The only option left is to clone again.

Expected Behavior: Coach should have the facility to set a new password
![screenshot from 2014-04-02 20 33 58](https://cloud.githubusercontent.com/assets/6392747/2592655/d424f4dc-ba77-11e3-9cb5-d06b25527442.png)

**Comment by rtibbles** [comment]
This functionality exists for non-locked down users.
