### ISSUE TITLE
Migrate control_panel to using bootstrap glyphicons

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#1861]
The pencil, trash can (not shown) and plus mark are ripped as images from bootstrap glyphicons.  Now that we're migrating to bootstrap, let's get these working as actual glyphicons.

@heidimason is this something you could take on?

![image](https://cloud.githubusercontent.com/assets/4072455/2598407/0aa14bec-bac7-11e3-8a8b-8fcc8a89abb1.png)

**Comment by rtibbles** [comment]
This is fixed.
