### ISSUE TITLE
First Name and Last Name field needs basic check 

### ISSUE THREAD

**Issue by deebee07** [learningequality/ka-lite#1863]
Branch: nalanda-rct1

Expected Behavior:First Name of a user is generally uses Alphabetical characters so we need to put a check or else users can make invalid Sign Ups

Current Behavior: Any Numerical First Name and Last Name is accepted which shouldn't be accepted

Steps to reproduce:
1. Go to the "Users"
2. Go to Coaches and Add
3. First Name and Last Name Fields

![coachname](https://cloud.githubusercontent.com/assets/6391037/2603171/1e70b1da-bb2b-11e3-8cab-0770c035d431.png)

![bug](https://cloud.githubusercontent.com/assets/6391037/2603165/fbf9030a-bb2a-11e3-8ba3-197e0d2982ef.png)

![screenshot from 2014-04-03 17 50 46](https://cloud.githubusercontent.com/assets/6391037/2603181/42e36ef4-bb2b-11e3-923f-5e2af35e2456.png)

**Comment by rtibbles** [comment]
Won't fix.
