### ISSUE TITLE
Skill mastered then too the exercise questions come up instead they should move to the next exercise

### ISSUE THREAD

**Issue by deebee07** [learningequality/ka-lite#1865]
Branch: nalanda-rct1

Expected Behavior:When a student has already mastered a skill what is the need to have more questions on the same asked again rather than moving forward to the next exercise 

Current Behavior: Logging in as a student when a student masters an exercise the same link which was already present comes up and the student has to click on the same to go to the next exercise to work upon 

Steps to reproduce:
1. Log in as a student
2. Go to Practice and select any exercise
3. Master it

![snap1](https://cloud.githubusercontent.com/assets/6391037/2603965/aed8ee68-bb35-11e3-8f77-0079b19e7bcc.png)

![snap0](https://cloud.githubusercontent.com/assets/6391037/2603896/ad983ac8-bb34-11e3-93c9-ef582d283b28.png)
![snap2](https://cloud.githubusercontent.com/assets/6391037/2603897/adc7029a-bb34-11e3-95dc-51d05bf8d550.png)
![snap3](https://cloud.githubusercontent.com/assets/6391037/2603898/adf1978a-bb34-11e3-8037-83aa6ae70765.png)

**Comment by rtibbles** [comment]
Superseded by #3368
