### ISSUE TITLE
Download Data from Khan Academy button leading to Khan Academy from a student Log in  gives Error

### ISSUE THREAD

**Issue by deebee07** [learningequality/ka-lite#1880]
Branch: nalanda-rct1

Expected Behavior: Clicking on Download Data from Khan Academy should Download Data from Khan Academy as required

Current Behavior: Below stated error pops up when we Log in with Khan Academy Log in 

Steps to reproduce:
1. Log in as a student
2. Go to Download Data from Khan Academy
3. Log in with Khan Academy credentials

![bugg](https://cloud.githubusercontent.com/assets/6391037/2614386/0ad39bb8-bbe6-11e3-9ca7-15f18074ff12.png)
![bug](https://cloud.githubusercontent.com/assets/6391037/2614387/1032afae-bbe6-11e3-94cb-030b6f81be1c.png)

**Comment by rtibbles** [comment]
Interface not extant.
