### ISSUE TITLE
Acceptable Format states it accepts only integers but it accepts any keyword

### ISSUE THREAD

**Issue by deebee07** [learningequality/ka-lite#1881]
Branch: nalanda-rct1

Expected Behavior:Answer Field should accept only ACCEPTABLE FORMATS as it is written beside the question and it should give an ERROR for an incorrectly formatted answer 

Current Behavior: Answer Field accept any Keyword of any format and has no relation with what ACCEPTABLE FORMAT states

Steps to reproduce:
1. Log in as a student
2. Go to Practice
3. Attempt a Question and check Answer Field

![hero](https://cloud.githubusercontent.com/assets/6391037/2614442/412939a6-bbe7-11e3-8063-71f699f314dd.png)

**Comment by aronasorman** [comment]
Fixed in latest khan exercises update.
