### ISSUE TITLE
Can't re-select topics after viewing scatter view

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#1900]
**Expected behavior:**

After viewing scatter points for one set of topics, can re-select topics and re-view.

**Branch:** `nalanda-rct1`

**Current behavior:**

No way to re-select topics.

**Steps to reproduction:**

1. Run `generaterealdata`
2. Log in as a coach, go to COACH => Effort vs. Mastery
3. Select topics, click "view"

Notes:

This is a regression bug.

![image](https://cloud.githubusercontent.com/assets/4072455/2631966/b4f8cbf6-be5f-11e3-892b-547a79a463b3.png)

**Comment by aronasorman** [comment]
No longer relevant in develop due to refactoring.
