### ISSUE TITLE
Facility changing  is not so flexible amongst different  users

### ISSUE THREAD

**Issue by him-28** [learningequality/ka-lite#1902]
Branch: nalanda-rct1

Expected Behaviour: Changing Facility should be allowed amongst various facilities users no priority should be given.

Current Behaviour: When you login as administrator with default  facility, in this case default facility cannot be changed .

In this case why there is a facility change option when it cannot be changed : 
![screenshot from 2014-04-07 16 35 40](https://cloud.githubusercontent.com/assets/6395045/2630705/53fadb66-be4e-11e3-82ce-4295d579ae76.png)

When login from Default facility , when click on Manage Users and View Usage; user facility could only be change to default facility but it cannot be reverted.

![screenshot from 2014-04-07 17 49 47](https://cloud.githubusercontent.com/assets/6395045/2630748/4e6a4ed8-be4f-11e3-92ff-82af14b75e57.png)

![screenshot from 2014-04-07 16 35 40](https://cloud.githubusercontent.com/assets/6395045/2630762/588d51b2-be4f-11e3-9783-eeef3ba50e6f.png)

Similarly when we login from other facility it's default facility cannot be changed
![screenshot from 2014-04-07 17 46 57](https://cloud.githubusercontent.com/assets/6395045/2630763/5ef4244a-be4f-11e3-88f2-bb18d0004a24.png)

Similarly  clicking on Manage Users and View Usage of other Facilities it could be changed to facility from which we login but cannot be reverted. 
![screenshot from 2014-04-07 18 00 30](https://cloud.githubusercontent.com/assets/6395045/2630859/e264be60-be50-11e3-94d8-79ee1bf5a29d.png)

![screenshot from 2014-04-07 18 00 45](https://cloud.githubusercontent.com/assets/6395045/2630882/382a9c84-be51-11e3-9250-8a66b62a378a.png)

Steps to reproduce:

1. Click on OverView
2. Click on Manage Users and View Usage or Click on Users tab and select users
3. Click on (Select a different facility)

**Comment by rtibbles** [comment]
Now has a dropdown.
