### ISSUE TITLE
Use sprites for images

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#196]
Using separate images requires many requests to retrieve a page.  It is more efficient to download a single "sprite" that contains all images concatenated together and do the client-side styling work to show the proper part of the sprite to simulate the image.

Given that we want to support lightweight clients, this would be a nice speedup.

**Comment by aronasorman** [comment]
Superseded by the planned asset management pipeline. Open another issue if we want to revisit this.
