### ISSUE TITLE
Migrate "validate" code to "clean"

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#1961]
According to the Django docs, `Model.clean` should be used for custom validation.  We're currently using a `validate` method on our `securesync` objects.

https://docs.djangoproject.com/en/1.4/ref/models/instances/#django.db.models.Model.clean

**Comment by aronasorman** [comment]
@benjaoming might be good to include in your refactorings.

**Comment by benjaoming** [comment]
Yes, maybe we can haz "Django 1.6 Compatibility" label? :)

**Comment by rtibbles** [comment]
Not going to happen within the scope of KA Lite.

**Comment by benjaoming** [comment]
Replaced by  #2360
