### ISSUE TITLE
No progress line is shown on mastery vs time graph with "Time session completed" on x-axis

### ISSUE THREAD

**Issue by codemania113** [learningequality/ka-lite#1972]
Branch: release-0.12.0

Current Behavior: When coach opens the mastery vs time graph to see the progress of various students, the progress is visible on the graph

Expected Behavior: Progress of all the students under a facility should be available for coach to review

Steps to reproduce:
1. Sign in as coach
2. Open the coach option
3. Select mastery over time plot
4. Select the topic for which at least one student has attempted problems

![screenshot from 2014-04-15 15 44 22](https://cloud.githubusercontent.com/assets/6392747/2705949/49045c98-c487-11e3-9373-3d6030e8306b.png)

**Comment by aronasorman** [comment]
Fixed in latest develop.
