### ISSUE TITLE
Implement UserLog triggers by extending Django signals system

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#2028]
This is a design change suggestion that I think I'd be happy to help out with.

Right now, the `UserLog` functionality is spread throughout the code, to exist wherever events happen that we want to log.  This decentralizes the logic and means that most apps have a dependency on `kalite.main`.

Another way to go would be to have apps extend the Django signaling system--to define and implement new signals.  An easy example would be for `kalite.facility` to have a `login` event (or, `pre_login` / `post_login`) and a `logout` event.

This would allow `kalite.main` to listen for all relevant signals, and simplify the relationship between the apps.

**Comment by aronasorman** [comment]
No bandwidth for nice to have; closing.
