### ISSUE TITLE
Simplified/No Login setup

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#2035]
Suggested by @grfriesen

Setting flag to:
* Hide all login features on homepage
* Don't warn students about not being logged in

Simplified login - suggested by @rtibbles
* Allow students to type in their name to login
* Create account if name not used already
* Otherwise log data to account using that name

**Comment by rtibbles** [comment]
After consultation with Nalanda teachers, a further iteration on this design has been suggested. When you select a facility, you get a drop down of all available student accounts and students select from the list. This avoids typing even the user name.

Still have other login features available, in order to allow teachers (who would not appear on the list) and admins to still login securely.

@MCGallaspy we discussed this yesterday - consider this the issue/design!

**Comment by MCGallaspy** [comment]
What if there are a very large number of accounts? Could that make for an awkwardly big dropdown list? And what if students inadvertently (or just carelessly) log in as other students? It would be very easy to do so if you are just selecting a name. Can we add an authentication step that doesn't involve typing? Perhaps a student can select one of several images as a sort of visual "password", and then when logging in the student is challenged to identify their chosen image from a set of 3 or 4.

**Comment by rtibbles** [comment]
Additional design suggestions:

* A confirmation dialogue to verify you are logging in as the correct student.
* When setting is on, a warning to admins/teachers if there are a large number of students in a facility (i.e. > 40).
* The visual password idea appeals to me, and is common in EdTech solutions for younger children - this could replace the confirmation dialogue.

**Comment by jamalex** [comment]
> What if there are a very large number of accounts?

Yeah, this could be an issue outside of Nalanda. With Nalanda, they have a separate Facility per class, so the size will be reasonable. Perhaps having them type a username, but then autocompleting, would be good for larger numbers (but not needed in the first pass).

We'll also need to make sure that the API endpoint for retrieving the list of usernames is not available when this mode isn't enabled, to avoid leaking usernames in contexts not using this feature.

**Comment by jamalex** [comment]
It would be good to implement this is as a nice, encapsulated Backbone.js widget, which could then also help be a more permanent solution for #3040.

**Comment by rtibbles** [comment]
As a first pass implementation, I am going to do this as an autocomplete similar to how our current search mechanism does it.

**Comment by MCGallaspy** [comment]
Maybe the only thing lacking on this feature now are retroactive integration tests? Just to avoid regression.

**Comment by rtibbles** [comment]
Yeah - when the BDD PR is merge, I'll make sure this feature Behaves.
