### ISSUE TITLE
Admin dashboard UX needs to be improved

### ISSUE THREAD

**Issue by dylanjbarth** [learningequality/ka-lite#2038]
Branch: release-0.12.0

Expected Behavior:

Very clear UI that helps me understand without reading any instructions or button titles, what I am able to accomplish. 

Current Behavior:

Currently, the only action available is to change students between groups, and I have an inkling that we can think of a simpler, more creative way to show the user that they can do that. 

Steps to reproduce:

1. Login as an admin / teacher w/ some data
2. Check out the user management dashboard -- "Users" on the nav bar 

Screenshot(s) of bug, if possible

![image](https://cloud.githubusercontent.com/assets/1319950/2907557/b8828fd4-d61d-11e3-81b0-a5694676070e.png)

**Comment by 66eli77** [comment]
how it looks now
![screen shot 2015-03-23 at 4 31 35 pm](https://cloud.githubusercontent.com/assets/5577205/6792853/1dd8014a-d17a-11e4-99fb-f28d74eca872.png)
