### ISSUE TITLE
Scatter coach plot does not fix axes range to 0,100 for percentage.

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#2041]
Branch: release-0.12

Expected Behavior:

* Axes fixed at 0%,100% to map onto the different quadrants

Current Behavior:

* Axes scale depending on student data

Steps to reproduce:

Generate user data. View scatter plot graph for a subtopic in which students have not achieved 100% mastery.

![image](https://cloud.githubusercontent.com/assets/1680573/2907699/806ad640-d61f-11e3-8ceb-7f269c921fd5.png)

**Comment by 66eli77** [comment]
fixed
![screen shot 2015-03-23 at 4 33 31 pm](https://cloud.githubusercontent.com/assets/5577205/6792878/60f8d382-d17a-11e4-96f4-fc0a74954e2a.png)
