### ISSUE TITLE
Frustrating coach report navigation

### ISSUE THREAD

**Issue by dylanjbarth** [learningequality/ka-lite#2044]
Branch: release-0.12.0

Expected Behavior:

Expectation is that all options available to the user are seen in the same view and are uniform in how they present themselves. So you can choose between 3 types of coach reports, you can choose between facilities, and groups of students. 

Suggestion: toolbar that can be used on all coach report screens with a group of dropdowns allowing users to navigate between coach reports (and turning the blue links to choose the facility and group into dropdowns to start with instead of needing to click on them to see that they are dropdowns)

Current Behavior:

There is a single view where you choose which report you want, and then it takes you there. 

Steps to reproduce:

1. Log in and check out the coach report workflow 

Screenshot(s) of bug, if possible

![image](https://cloud.githubusercontent.com/assets/1319950/2907661/fa1577da-d61e-11e3-8897-5bad3a885cee.png)
![image](https://cloud.githubusercontent.com/assets/1319950/2907667/0986c192-d61f-11e3-989f-02e6e6ccdebc.png)
No way to get back to selecting a different type of coach report

**Comment by rtibbles** [comment]
Implemented.
