### ISSUE TITLE
Link to practice exercises associated with videos doesn't work

### ISSUE THREAD

**Issue by aditi611** [learningequality/ka-lite#2050]
While watching certain videos, there is a link to 'Practice this concept' on the extreme right corner which on clicking says 'Page Not Found'. This link isn't present while loading some of the videos which don't have an associated exercise. For e.g. Math>Geometry>Quadrilaterals works fine whereas Math>Arithmetic and pre algebra>Ratios, proportions, units, rates>Ratios and proportions>Solving problems with table exercises does not. Ideally, this link shouldn't be present if a video has no associated exercise.

**Comment by rtibbles** [comment]
Not currently extant.
