### ISSUE TITLE
Coach Reports Mastery line issue

### ISSUE THREAD

**Issue by heidimason** [learningequality/ka-lite#2088]
In this version: #2071 

When user clicks on the "View Report" button, the Mastery line runs into the X-Axis/Y-Axis form :(
Before: 
![screen shot 2014-05-12 at 12 43 22 pm](https://cloud.githubusercontent.com/assets/4885404/2964122/bcdb605a-dae2-11e3-81c1-70297cf01775.png)
After:
![screen shot 2014-05-12 at 12 39 57 pm](https://cloud.githubusercontent.com/assets/4885404/2964129/c8e74a12-dae2-11e3-90f4-148a788e0bda.png)

**Comment by rtibbles** [comment]
No longer extant.
