### ISSUE TITLE
Knowledge map do not work on Android v2.3.7 virtualized device.

### ISSUE THREAD

**Issue by cpauya** [learningequality/ka-lite#2107]
branch: nalanda

Been doing some tests using Android devices thru [Genymotion](https://cloud.genymotion.com/)'s virtualized devices and found out that some features do not work when using Android v2.3.7 on Google Nexus v2.3.7 image (knowlegde/exercise map do not show).  Using the v4.1.1 image shows the map.  See attached images.

I haven't tested other KA-Lite features on the v2.3.7 but I think we need to set some minimum requirements/specs for Android devices to know whether we need to fix this or move on.

Since [UbiSlate 7Ci](http://www.ubislate.com/ubislate/) is on Android v4.0.3 - should we set that as our minimum requirement?  As of this writing, only v2.3.7, v4.1.1, v4.2.2, v4.3, and v4.4.2 are the Android versions available at Genymotion.

Other related tools that could be useful:
* [Google Chrome mobile emulation](https://developer.chrome.com/devtools/docs/mobile-emulation)
* [Android Virtual Devices](https://developer.android.com/tools/devices/index.html)
* [Android-x86 - VirtualBox image downloads](https://code.google.com/p/android-x86/downloads/list) - this always prompts for captcha form from my end - so we I can't download the images but could work for the others.

Related issue/s:
* [Knowledge map can't be scrolled](#2034)

Screenshots:

![screen shot 2014-05-19 at 9 37 30 am](https://cloud.githubusercontent.com/assets/175580/3009479/51f4883a-defb-11e3-979d-78bd7a25d780.png)
![screen shot 2014-05-19 at 9 36 06 am](https://cloud.githubusercontent.com/assets/175580/3009482/5bcd6df4-defb-11e3-84bc-f349895a71b2.png)

**Comment by 66eli77** [comment]
one possible solution is to install a simplified APK that embeds Crosswalk WebView(Chromium based, requires Android 4.0 and above) but does not run Django server inside the tablet.

**Comment by rtibbles** [comment]
Given that this knowledgemap no longer exists, and the new knowledgemap is hidden in 0.13 - I am not sure this is still an extant issue.
