### ISSUE TITLE
Coach Reports "suggested action" box images are low-res/too wide on larger tablets

### ISSUE THREAD

**Issue by heidimason** [learningequality/ka-lite#2143]
This is what they look like with a viewport width of 767px.  I'm not sure what people want them to look like.  This is probably low priority.
![screen shot 2014-06-04 at 5 52 43 pm 2](https://cloud.githubusercontent.com/assets/4885404/3182177/999197a6-ec4c-11e3-8e93-03920eaa34c6.png)

**Comment by rtibbles** [comment]
No longer extant.
