### ISSUE TITLE
Too much scary power for the Coaches

### ISSUE THREAD

**Issue by mikewray** [learningequality/ka-lite#2158]
I'm testing beta 0.12.0 and logged in as a coach - at first glance it looks like they have identical power to the administrator e.g. can delete a facility etc. I think this is pretty dangerous and would much prefer the coach just to have access to the coach reports and a few other limited functions. I'm pretty soon somebody, somewhere will click the wrong thing unknowingly and cause all sorts of havoc. 

Whilst I'm on the topic of the coach login but these are less critical:
Is there any need for the 'coach' button now for the coach?
It might be useful for the coach to have access to the knowledge map and videos - as is they have to have a student account to access them. I see the coach as a super user, not as a less powerful administrator
It might be an idea to associate a coach with a group?

**Comment by rtibbles** [comment]
Fixed.
