### ISSUE TITLE
In "Progress by topic," clicking back and forward buttons in browser doesn't change topic title accordingly

### ISSUE THREAD

**Issue by jtamiace** [learningequality/ka-lite#2174]
Branch: develop
Expected behavior: When navigating topics in "progress by topic" in coach reports, I expected the topic name to change along with the content when I click the back and forward button in browser to navigate.
Current behavior: The topic name doesn't change the first time that I click the back/forward button, and is confusing if there are several topics that the user has clicked through. 
Steps to reproduce:
1. Create facility, then students, then student group
2. Navigate to coach report, then progress by topic
3. Click several topics in drop down menu
4. Explore navigation through back/forward buttons in browser

Navigation to "Angles and Intersecting lines"
![bug2](https://cloud.githubusercontent.com/assets/6668144/3307519/8794b760-f66d-11e3-909d-a0b80bc35651.JPG)

Hitting back button to "Addition and subtraction"
![bug](https://cloud.githubusercontent.com/assets/6668144/3307495/4a950efa-f66d-11e3-8a68-fc951ca9cc68.JPG)

**Comment by rtibbles** [comment]
No longer extant on develop.
