### ISSUE TITLE
SESSION_ENGINE with a more sane default

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#2185]
Sitting out here in the bush with almost no internet and debugging why all session contents are lost could have been avoided :)

settings.SESSION_ENGINE should be `'django.contrib.sessions.backends.db'` because that way the sessions will persist when running KA Lite through Apache w/ mod_wsgi.

The default `'django.contrib.sessions.backends.cache'` does not persist sessions from call to call because WSGI has different processes each with their own cache.

**Comment by aronasorman** [comment]
Whoa! Didn't know you already used KA Lite last year @benjaoming!

Anyway as per https://github.com/learningequality/ka-lite/pull/4257, sessions are now stored as cookies, so they should persist across server reboots.

**Comment by benjaoming** [comment]
Hurray!! Finally!! :D

Oh I'm an old-timer :)
