### ISSUE TITLE
Videos Download Fails with Error: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by nosajesahc** [learningequality/ka-lite#2215]
Hardware: Raspberry PI
OS: Raspbian Kernel Version 3.12
Python 2.7.3 (default, Mar 18 2014, 05:13:23)

On the /update/videos/ page, I am getting the following error:

Error during update: Error: 'NoneType' object has no attribute '__getitem__'

When this happens the video download stops.  If I re-select the videos I want downloaded and resubmit the job it restarts.

I can't find a log file so I don't have any more information.  I'm guessing the video download has failed for an unrelated issue and the status update is failing because their is no information to display.

**Comment by nosajesahc** [comment]
Hello there,

I originally ran into this issue with an older release and I'm seeing it again in the latest development snapshot.

Error during update: Error: 'NoneType' object has no attribute '__getitem__'

The code I am using was clone via git yesterday from the develop branch.

**Comment by MCGallaspy** [comment]
@66eli77 once you get the pi up and running, can you try to replicate this issue?

**Comment by rtibbles** [comment]
@anuragkanungo fixed this in #3181
