### ISSUE TITLE
Port Update videos and Update Languages to backbone.js

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#2255]
So... the `update_videos.js` and `update_languages.js` is an adhoc mess of JS functions right now. We want to structure it using backbone.js.

**Comment by rtibbles** [comment]
@howdyitshelena is going to take a look at this. I assume @66eli77 has no objections.

**Comment by howdyitshelena** [comment]
Here's what I have for the features - let me know if I missed anything!
Features for the videos tab:
- downloading videos
  - download, delete, cancel, retry video downloads
  - video_start_callback
  - video_reset_callback
  - video_check_callback (checks the current progress)
  - changing the language
- topic tree
  - unselect all nodes
  - get selected, incomplete, started, videos
  - get selected, incomplete, started metadata
  - nodes for content tree
    - current, set, update

Features for the language tab:
- version comparison
- get available, installed languages
- display languages
- delete language pack
- populate installable language pack
- start language pack download
- select language pack
- start download process once #get-language-button is clicked
  - set server language

**Comment by aronasorman** [comment]
You can also upgrade installed language packs.

**Comment by howdyitshelena** [comment]
ah okay, thanks @aronasorman!

**Comment by rtibbles** [comment]
Not going to happen within the scope of KA Lite.
