### ISSUE TITLE
New content-syncing approach needed for Perseus exercises

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#2257]
With khan-exercises, we just included everything directly in the repo/installer. With Perseus, there are currently 17K+ questions, many with pre-rendered images (700+MB), which becomes unwieldy.

We might consider breaking up the Perseus content into subtopic blocks, which can be downloaded into an installation in a similar fashion as we do for videos. These content packs could include all the question data and images for a portion of the topic tree. They could also be downloaded separately on a per-language basis, as with language packs.

This doesn't need to be a blocker for merging the hackathon code into the develop-all-the-things branch, but as we've excluded the full assessmentitems.json file from the repo for now, not many exercises will work until this is fixed.

**Comment by aronasorman** [comment]
Zipping up the assessment items is almost done (with some bugs found by @jamalex). Now working on downloading the zip. After that, I'm working on splitting up the assessment item resources into their own zips by topic.

**Comment by aronasorman** [comment]
Assessment item resources is not *that* big (200 MB), so we might just bundle it as part of the installation, or allow them to download it through the UI that @MCGallaspy is building.

**Comment by aronasorman** [comment]
We decided that we're gonna bundle in the assessment resources as part of the installers. The zipped up assessment resources is around ~360 MB, and that would be the lower bound for the size of our installers.

For the git users, our migration path for them would be to run a command called `unpack_assessment_zip`, which should be given to them through an upgrade note as part of the documentation (cc @MCGallaspy).

**Comment by aronasorman** [comment]
Fixed in #2896.
