### ISSUE TITLE
Localization documentation refers to path that does not exist

### ISSUE THREAD

**Issue by louhow** [learningequality/ka-lite#2265]
Under: https://github.com/learningequality/ka-lite/blob/master/docs/LOCALIZATION-HACKING.md

Section 4.1: KA Lite loads in video content using the content/ directory and the json file **kalite/static/data/topics.json** Take a look at that json data.

However, there is no data directory:

https://github.com/learningequality/ka-lite/tree/master/kalite/static

**Comment by rtibbles** [comment]
File no longer exists.
