### ISSUE TITLE
Ads Placement Idea: hotspot connection landing/agreement page

### ISSUE THREAD

**Issue by wangguan59** [learningequality/ka-lite#2266]
Here is an idea where we could place advertising that is effective and not much issue with CC content. 

Since KA Lite running  as a server and could be set as a hotspot connection. I wonder if we could set an automatic connection landing page like I often saw an agreement at a cafe hotspot. We can put ads on that connection landing page, and has a button "Connect to KA Lite" 

Also, many hotspots will automatically load the browser on the connection page when it is connected. So a user doesn't need to open the browser and type the ip address.

@jamalex What do you think about this network technical settings.

![screen shot 2014-07-24 at 2 20 00 pm](https://cloud.githubusercontent.com/assets/1319955/3695400/f83a58e4-137d-11e4-9069-dd50868d4d75.png)

**Comment by aronasorman** [comment]
Not a priority; let's open another issue if we want to revisit this.
