### ISSUE TITLE
Revision of Exercises to Improve Learning Retention & Effectiveness

### ISSUE THREAD

**Issue by mikewray** [learningequality/ka-lite#2277]
Its well know that revising a topic a week after and then a month after dramatically increases learning retention and therefore overall effectiveness. I'm wondering if this is a basic way of capturing this functionality without the bells and whistles and going to the nth degree. 

In its simplest form, perhaps an idea is that the icons on the knowledge map change to indicate e.g. 

1. On getting 10 in a row right put a green P over the gold star i.e. proficient
2. 10 days later the greem P changes to a red R i.e. revision. When 2 in a row are completed correctly it goes to a green R
3. 20 days laters the green R turns to a red M, when two in a row are done the full star is revealed

I know KA online does a whole lot of more sophisticated stuff with this but wondering if there is a simple way in capturing the essence of this i.e. student checks out his knowledge map every now and then. I think you would find it would have a dramatic increase in learning effectiveness which is our ultimate goal. 

What your thoughts from a coding perspective?

**Comment by rtibbles** [comment]
With the introduction of content recommendation we can start to look at this in 0.15.

**Comment by rtibbles** [comment]
Not going to happen within the scope of KA Lite.
