### ISSUE TITLE
awesome keypad repeats last character if you hit return

### ISSUE THREAD

**Issue by mjptak** [learningequality/ka-lite#2288]
Branch: Nalanda-rct2 (and others)
Browser Chrome

UX Issue?:  If you use the virtual keypad and then hit the return it does not submit the answer but instead repeats the last digit you entered.

If you were just using the normal keypad and did the same thing it submits the answer.

I see that a return will select whatever number is currently selected (which is generally the last digit).

**Comment by rtibbles** [comment]
Fixed.
