### ISSUE TITLE
Log in page potential re-design 

### ISSUE THREAD

**Issue by wangguan59** [learningequality/ka-lite#231]
![image](https://f.cloud.github.com/assets/1319955/780138/5fd12e96-e9fa-11e2-83f6-e6a8d73de496.png)

User clicks the "log in" button on the top right corner to get on this page. It made me move my cursor twice to get to the log in field position, and took me a bit cognitive effort to shift my attention to the left side. 

I had few redesign ideas:
1) Center the page would make it more salient, as well as less cognitive effort to shift attention and move the cursor
2) Make it pop up for the log in page, which would make them a feel about going to the web app after they log in. (A transition between web info and web app)
3) Or a drop down section under the login button once they click it.

I would happy to show make prototypes later this week, and some development.

**Comment by 66eli77** [comment]
addressed by @rtibbles 's new PR
