### ISSUE TITLE
Cannot start server after computer restart

### ISSUE THREAD

**Issue by runfunke** [learningequality/ka-lite#2321]
Branch: Master or Develop
Expected Behavior: When I restart the computer without stopping the server, I should be able to start the server again.
Current Behavior: When the computer is restarted without stopping the KALite server, KALite will not start again without first exiting and restarting.
Steps to Reproduce:
1. Start KALite server
2. Restart computer.
3. After restart, KALite does not allow me to restart. I must Exit, then reopen KALite.

**Comment by aronasorman** [comment]
Reopen if not fixed in develop.
