### ISSUE TITLE
Starting KALite server takes a long time

### ISSUE THREAD

**Issue by runfunke** [learningequality/ka-lite#2322]
Branch: Develop or Master
Expected behavior: When clicking Start to start the server, the server should start almost immediately (as it did in previous versions 10 and prior. 11 was slow also)
Current behavior: When clicking Start to start the server, I must wait a minimum of 5 minutes (sometimes longer, up to 20 minutes) before the server starts.
Steps to reproduce: Start the server, and wait...
This is happening on Windows XP, Windows Server 2003, and Windows 7.

**Comment by aronasorman** [comment]
Hi @runfunke, I'm closing this as there's been a lot of code churn that happened in the latest develop. Hopefully that solves this issue.
