### ISSUE TITLE
Auto-start does not work for 'At system startup' or 'at user login'

### ISSUE THREAD

**Issue by runfunke** [learningequality/ka-lite#2323]
Branch: Develep or master
Expected behavior: When selected, the server should start automatically when the computer is switched on, or when a user logs-in.
Current behavior: When selected, the server will open the window, but it is not possible to click the Start server button. You must exit and restart (sometimes twice).
Steps to reproduce:
1. Select Auto-start at system startup or Auto-start at user log-in
2. Be sure the server is stopped.
3. Restart the computer and log-in to the computer user.

**Comment by aronasorman** [comment]
Fixed in develop.
