### ISSUE TITLE
Abstraction for non-Django models accessed via tastypie

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#2326]
Currently, various apps use TastyPie to expose non-Django models to the client side.

This results in a lot of repeated cruft that could be abstracted and then reused across the different apps.

Solution:
Abstract and reuse!

**Comment by rtibbles** [comment]
Punting this until the dust settles on whether we migrate from TastyPie.

**Comment by aronasorman** [comment]
Is this still on the table? I thought we named Django Rest Framework (DRF) as The Way Forward. If so we shouldn't expend to much effort putting lipstick on a pig.
