### ISSUE TITLE
Enable Byte Range requests on videos when KA Lite is behind Nginx

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#2336]
Our [demo server](http://demo.learningequality.org/) is behind an Nginx frontend proxy server. This seems to be blocking byte range requests, which prevents seeking (clicking around on the timeline) within the video playback interface.

For both the demo server and other deployments (e.g. some on the Pi) behind Nginx, we should do what is [described here](http://forum.nginx.org/read.php?11,228598,236758#msg-236758) and add the `Accept-Ranges: bytes` header via middleware within the cherrypy server bundled with KA Lite.

**Comment by benjaoming** [comment]
This works because /content /static and /media are all served by nginx and not cherrypy.

Example from Debian 8.1 running ka-lite-raspberry-pi:

![debian 8 1](https://cloud.githubusercontent.com/assets/374612/11594934/11426360-9aad-11e5-88fe-4685aa8cee02.png)
