### ISSUE TITLE
Tastypie Error Handling with JSON responses

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#2350]
Create a general wrap_view function to import into all tastypie Resources and ModelResources in order to return JSON responses that give meaningful error messages to the end user.

**Comment by aronasorman** [comment]
I know there's a lot of Tastypie hate lately in favor of django-rest-framework (DRF). Does DRF implement this already?

**Comment by aronasorman** [comment]
or rather, does DRF have the same problem?

**Comment by aronasorman** [comment]
Closing, since we're migrating to DRF soon.
