### ISSUE TITLE
Fill main content pane in "Learn" tab 

### ISSUE THREAD

**Issue by dylanjbarth** [learningequality/ka-lite#2357]
In the hackathon branch, soon to be merged into develop-all-the-things, we have an empty white content pane until the user clicks through to an exercise. 

![selection_073](https://cloud.githubusercontent.com/assets/1319950/4225937/a14fa91e-3932-11e4-968f-fd00acb60267.png)

This issue is a place where we can collaboratively brainstorm ideas for filling that space with useful content for the user

**Comment by aronasorman** [comment]
We're ignoring this for 0.13, and this will get superseded by #3368, which is what will fill this empty space.
