### ISSUE TITLE
Documentation of all local_settings.py settings

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#237]
We now have a number of features that are configurable and/or enabled via local_settings.py.  We need to have good documentation about these settings, and what effect they have, on the wiki before the planned release.

@dylanjbarth I thought us working together on this would be a nice way to discuss features of KA Lite and get them on the wiki.  I was thinking that I'd make an initial list, then discuss each with you so you could update the docs fully.

**Comment by benjaoming** [comment]
Naturally, this would be done if we fixed #4054 

local_settings is very deprecated so let's abandon this issue for good
