### ISSUE TITLE
Sign up page should not enforce facility selection

### ISSUE THREAD

**Issue by dylanjbarth** [learningequality/ka-lite#2391]
Lingering issue from merging nalanda-rct3 with develop-all-the-thing and hackathon:

Currently, facility/views reuses the facilityuser form in 5 different contexts: adding/editing teacher, adding/editing student, and user signup. In the sign up case, we don't need to enforce facility selection with the @facility_required decorator. And generally, because these 5 views are somewhat complicated, they could use a refactor toward simplification.

**Comment by jesumer** [comment]
Hi,

I hope this issue still open. I've assigned myself on this issue.
Thanks.

**Comment by jamalex** [comment]
If you can try to replicate it, that would be great. Not sure if it still exists on the develop branch.

To replicate, you'll need to create multiple facilities, but not make any of them default, then log out. When you go to the login page, if it shows [this](https://cloud.githubusercontent.com/assets/1319950/4409369/98f46a9c-44dc-11e4-80fd-0417f79ddbea.png) page first, this issue still exists.

**Comment by jesumer** [comment]
Hi @jamalex ,

I've added already some facilities and tried the things you have said and this is what the login page shows: 
![screen shot 2015-01-05 at 10 40 27 am](https://cloud.githubusercontent.com/assets/2810009/5608713/a47b7a28-94c7-11e4-9fe6-59e16ceffa25.png)

**Comment by jamalex** [comment]
Ok, great, thanks! Looks like this issue is solved, and can be closed, then.
