### ISSUE TITLE
Tests not displaying for students once they are assigned

### ISSUE THREAD

**Issue by dylanjbarth** [learningequality/ka-lite#2392]
Lingering issue from merging nalanda-rct3 with develop-all-the-thing and hackathon:

When a test is assigned, the student is redirected properly to the assigned test, but test.html is throwing all kinds of JS errors (starting with import errors and then once those were corrected, more errors within the now correctly imported files). Likely the result of merge conflict getting resolved incorrectly. 

Because tests are nalanda specific this only needs to be fixed when develop eventually gets piped to the Nalanda project.

**Comment by aronasorman** [comment]
We are not merging develop into nalanda anymore; when we do merge them, we'll have a proper student testing implementation by then. Stale issue, closing.
