### ISSUE TITLE
Create script (Bash or Python) for auto-updating version.py prior to release

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#2436]
A number of the steps of updating version.py prior to release can be nicely automated, including:

- Incrementing the version numbers; either major, minor, or patch (selected via a command line argument). If minor version is updated, patch should be reset to 0, and if major is updated, both minor and patch should be reset to 0.
- Adding an entry for the version being released to VERSION_INFO, automatically filling in the release_date, git_commit, and asking the user re: new features (or leaving them empty and we can add them in manually).
- Adding a git tag with the appropriate version.

**Comment by aronasorman** [comment]
This is slightly more involved now, given the requirements for building the deb installer on Launchpad. I also don't see this as a huge requirement since the introduction of `version.yml`.
