### ISSUE TITLE
Language change for teacher requires re-login

### ISSUE THREAD

**Issue by anuragkanungo** [learningequality/ka-lite#2445]
Branch : nalanda rct3
current behaviour : Changing Language for teacher requires re-login/  Language change button not shown site-wide
expected behavious : Language changes should reflect immediately. There should be drop-down for language change beside logout button

steps to reproduce:
1. Launch Kalite server
2. Click on Login from nav bar. Login with valid credentials for teacher
3. Goto -> Overview -> <facility for that teacher> -> edit icon for that teacher -> change language -> click update user
4. language changes do not reflect immediately

**Comment by rtibbles** [comment]
@jtamiace could you confirm if this is extant and fix?

**Comment by radinamatic** [comment]
Non extant on 0.17b4, closing!
