### ISSUE TITLE
Higher bitrate/resolution videos are choppy/cause freezes in mplayer on Pi

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#245]
Got mplayer-launching working in #139, so that the Pi can be used as a standalone client device, but the bigger (typically, newer) H.264 video files play choppily in mplayer (and froze up, eventually). When testing mplayer for vids on the Pi last summer, there were various options that helped with performance, including some options to drop frames more liberally, but have to re-experiment now to find the optimal settings. We want to be able to use the same set of MP4/H.264 videos used for playing in the browser, so re-encoding isn't an option.

**Comment by rtibbles** [comment]
I believe we have deprecated the use of mplayer.
