### ISSUE TITLE
Visits to My Progress page creates UserLog records.

### ISSUE THREAD

**Issue by cpauya** [learningequality/ka-lite#2452]
**Branch:** `release-0.12.0`

**Current behavior:**  We noticed a weird issue wherein a `UserLog` record is created whenever the student visits the My Progress page.  If `settings.USER_LOG_MAX_RECORDS_PER_USER = 3`, every visit will create a new `UserLog` up to maximum of 3 records on top of the existing records.  So if `settings.USER_LOG_MAX_RECORDS_PER_USER = None` - it will always create a new UserLog record.

This is related to the #2000 issue [findings](https://github.com/learningequality/ka-lite/issues/2000#issuecomment-58148286).

**Expected behavior:** No UserLog record must be created if a student visits the My Progress page.

**To replicate:**
1. Login as student on http://127.0.0.1:8008/ then logout after a few seconds.  This will add a record to `UserLog`.
2. Set `local_settings.USER_LOG_MAX_RECORDS_PER_USER = 3` then restart ka-lite.
3. Login as student on http://127.0.0.1:8008/
4. On another browser tab, login as admin on http://localhost:8008/ and go to http://localhost:8008/admin/main/userlog/
5. As student, visit the My Progress page, then Home, then My Progress page again.
6. Notice on the admin tab that every visit of the student on the My Progress page adds up to 3 `UserLog` records on top of the already existing record/s.

The `UserLogSummary` is also updated with the new record created, login count is incremented.

**Comment by benjaoming** [comment]
Work-around: set `settings.USER_LOG_MAX_RECORDS_PER_USER = -1` and it won't have a limit as I read the code.
