### ISSUE TITLE
Add a setting to enable or disable limit on UserLog maximum records.

### ISSUE THREAD

**Issue by cpauya** [learningequality/ka-lite#2462]
**Branch** release-0.12.0

**Milestone** 0.13.0

**Current behavior** The `settings.USER_LOG_MAX_RECORDS_PER_USER` is used to limit the number of UserLog records to be created for user stats.  To disable this it must be assigned the value `None`.  This somehow affects #2276 for counting the user login stats.

**Expected behavior** There must be a separate boolean setting to enable or disable the limit on UserLog maximum records.

**Possible solution** Add a `settings.USER_LOG_ENABLE_LIMIT = True` setting and refactor the `UserLog` codes to use this.

**Comment by benjaoming** [comment]
Setting `USER_LOG_MAX_RECORDS_PER_USER = 0` (`0` by default) will disable the `UserLog`.

While it isn't pretty, there's a signal `cull_records` in `main.models` which will remove old log entries.

**Comment by benjaoming** [comment]
Tested that it works, `UserLog` remains empty after setting `USER_LOG_MAX_RECORDS_PER_USER = 0`, and exercises keep working.
