### ISSUE TITLE
Automated option for btsync'ing contents

### ISSUE THREAD

**Issue by usernamenumber** [learningequality/ka-lite#2473]
Another quick note about using btsync to download ka-lite content. 

I was looking for a way to do this in an automated way (e.g. using Ansible), and found that you can do it by putting the following into a config file:

```
{
  "shared_folders" :
  [
    {
      "secret" : "BT7AOITNAIP3X3CSLE2EPQJFXJXMXVGQI",
      "dir" : "PATH_TO_KALITE_CONTENT_DIR",
      "use_relay_server" : true, 
      "use_tracker" : true,
      "use_dht" : false,
      "search_lan" : true,
      "use_sync_trash" : true,
      "overwrite_changes" : false
    }
  ]
}
```

...and then running `btsync --nodaemon --config CONFIG_FILENAME`

Some of the settings in there can probably be optimized or removed, but if the ability to do an unattended sync would be useful to others, it might be worth adding a mention of this to the setup guide?

**Comment by benjaoming** [comment]
We are going to freeze KA Lite at its current feature set:

1) Downloading videos individually from an HTTP source
2) Downloading full sets of downsampled videos with torrent (see: http://pantry.learningequality.org/downloads/ka-lite/ )

Thanks for reporting this back when it was relevant @usernamenumber :)

**Comment by benjaoming** [comment]
...and feel free to check out the upcoming inheritor of KA Lite: https://learningequality.org/kolibri/
