### ISSUE TITLE
Forum signup seems to be broken

### ISSUE THREAD

**Issue by usernamenumber** [learningequality/ka-lite#2476]
Apologies again if this isn't the right place to report forum bugs. If there's a better place, please let me know.

I've made two attempts to create an account at https://forums.learningequality.org/, but neither has been successful.

First I tried to sign up with my github account (usernamenumber). It seems to have created the account (subsequent attempts to login with gh say the account already exists), but even after clicking the "forgot password" link, I've gotten no confirmation email in my Inbox or Spam folder. 

Next I tried to create a new account under the name "UnN". The signup page said that the username was available, but as soon as I clicked Create, it went to an error saying that the name is taken, and subsequent attempts to create that username say the same, so it seems there's either a bug in the signup page or the subsequent account creating and notification (again, no confirmation email) that I can see.

The two accounts used different email addresses.

**Comment by tcvuongtron** [comment]
Thanks





Chuyên [URL="https://traicayvuongtron.vn/suc-khoe/trai-cay-to-huong-dan-cach-lam-don-gian-tai-nha-873.html"]hướng dẫn làm trái cây tô[/URL],[URL="https://traicayvuongtron.vn/suc-khoe/top-5-quan-trai-cay-to-giao-hang-tan-noi-o-sai-gon-941.html"]trái cây dầm ngon[/URL],[URL="https://traicayvuongtron.vn/suc-khoe/trai-cay-to-ngon-quan-tan-binh-784.html"]trái cây tô tân bình[/URL]
