### ISSUE TITLE
Teachers should be able to access the contents of a playlist by clicking on the desired playlist on the playlist tab

### ISSUE THREAD

**Issue by anuragkanungo** [learningequality/ka-lite#2478]
branch : nalanda rct3
current behaviour :Does not allow teachers/admin to view playlist contents. They need to create a dummy student to view that.
expect behaviour: Teachers should be able to access the contents of a playlist by clicking on the desired playlist on the playlist tab.

In the http://127.0.0.1:8008/playlists/assign/
![screenshot from 2014-10-14 00 08 28](https://cloud.githubusercontent.com/assets/4207886/4618260/26c6c354-5308-11e4-845d-07875bf5afa0.png)

**Comment by rtibbles** [comment]
Won't fix.
