### ISSUE TITLE
DatabaseError: attempt to write a readonly database

### ISSUE THREAD

**Issue by pr3p** [learningequality/ka-lite#2482]
hi i try to install ka-lite on new machine it seem i got this error when starting the server, please refer on the screenshot thanks and looking for your fast response.

http://prntscr.com/4vzzq0

**Comment by jcoupe** [comment]
Hi,  I am running into similar issues in installing KA-LITE on my Raspberry Pi.  I got a similar error message as the one above, and I tried first to reclone - but in accessing github, I need to use sudo to do this.  When I tried to clone from my own personal account without sudo, I get a message stating that I cannot generate the "tree."   

It appears Ka-Lite requires that a non-su user start the service.  I am running the service from a flash disk on a USB thumb, so I need sudo to mount the drive.  I am setting up the KA-LITE installation to administer it from the default Raspberry Pi login:  Pi and Raspberry - when prompted during ./setup_unix.sh .  Perhaps changing file ownership makes more sense in my case - not sure how to do the above - so many thanks for any help.

**Comment by MCGallaspy** [comment]
Hi @jcoupe, I think you can edit the `/etc/fstab` to give user in a particular group permissions to mount a usb drive. Then you will just need to add the "Pi" user to that group.

**Comment by jcoupe** [comment]
Thanks Michael - I'm a novice, and looking forward to getting this up and
running!  This looks like a good solution.  Will let you know how it
goes.

On Mon, Apr 20, 2015 at 12:32 PM, Michael Gallaspy <notifications@github.com

**Comment by jamalex** [comment]
Depending on the filesystem, you can probably also create a folder on the external USB drive and set the permissions (`sudo chmod +rw foldername`) to be readable/writable, or to belong to your regular account (`sudo chown yourusername:yourusername foldername`). You don't want to have to use `sudo` when cloning.
