### ISSUE TITLE
Extra spacing after footer on video page for student user

### ISSUE THREAD

**Issue by howdyitshelena** [learningequality/ka-lite#2512]
Branch: develop

Expected Behavior: Footer should be at the very bottom of the page

Current Behavior: There is extra spacing after the footer on pages with a learning video

![screen shot 2014-10-17 at 3 24 15 pm](https://cloud.githubusercontent.com/assets/2066060/4686952/5fc7546a-564c-11e4-8720-c377377a6a46.png)

Steps to reproduce: 
1. Log in as a student
2. Navigate to a video
    i.e. Math > Early Math > Counting > Creating a number grid
3. Scroll to the bottom of the page

**Comment by anuragkanungo** [comment]
@aronasorman 
I think it doesn't exist anymore. The spacing now is intentional.

![screen shot 2015-01-16 at 2 40 15 am](https://cloud.githubusercontent.com/assets/4207886/5766614/032a2c18-9d29-11e4-9acb-fd2e2b3c7ad5.png)
