### ISSUE TITLE
Branding of next gen platform

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#2601]
Some prankster seems to have smuggled the name "Papyrus" into develop. This is currently used for a note taking app, and appears to be hard to pronounce for an international audience. What should we call this application as it continues to morph beyond Khan Academy content?

@jamalex @aronasorman @66eli77 @jtamiace @dylanjbarth @howdyitshelena @jeepurs

**Comment by 66eli77** [comment]
skipping stone,

**Comment by sethachoi** [comment]
chameleon, kameleon, elle (LE), kay, kayle (KALE), kale, camel, and my personal favorite, kamillion$

**Comment by benjaoming** [comment]
It's odd how we ended up choosing a name other than all these great candidates :)
