### ISSUE TITLE
Protactor not visible

### ISSUE THREAD

**Issue by anuragkanungo** [learningequality/ka-lite#2616]
branch : nalanda rct3
The protractor is not visible for exercises with angles. A blank screen shows up in place of the protractor. 

Here is a link to the exercise - 
http://demo.learningequality.org/math/geometry/parallel-and-perpendicular-lines/Angle_basics/e/measuring_angles/

**Comment by aronasorman** [comment]
Solved in this commit btw: https://github.com/learningequality/ka-lite/commit/3db0fddb9512615a4a0c1d0e383e2e7f663270da
