### ISSUE TITLE
Optimize the KA Lite initial setup time

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#2619]
Initializing the required files for KA Lite on a modern computer is in the order of 50 seconds with no required input from the user. This setup script runs does the following:

1. Initializes the database with the required tables.
1. Runs migrations over those tables, changing them based on how they were changed over time during development.
1. Generates a 2048-bit RSA encryption key used for syncing.
1. Copies the assets into the Django static/ folder.

Some of these can be skipped or sped up:
1. Migrations can be disabled, which will allow Django to just initialize the database with the updated tables instead of migrating them one by one.
1. The C extension for generating encryption keys can be bundled into KA Lite, making the key generation phase much faster.
1. Assets can be placed into the static/ folder ahead of time, skipping the copying phase.

Related to #2617.

**Comment by benjaoming** [comment]
#4099 only runs migrations if database changed.

#4395 addresses to use a prebuilt database

Regarding assets, we should probably do some kind of refactor to separate userspace assets that can be updated from the ones that we might as well pre-collect.

collectstatic only runs on `manage setup`.

Key generation... hmm.. we could have a separate issue for that if anyone gets a good idea.
