### ISSUE TITLE
Integrate Khan Academy Computer Science platform into KA Lite

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#2658]
Code for live editor here:
https://github.com/Khan/live-editor

Let's do this!

**Comment by rtibbles** [comment]
Punting to 0.17.

**Comment by benjaoming** [comment]
@rtibbles thanks for making the pioneering work :)

You may want to reopen this for Kolibri, but closing for KA Lite since it wasn't done for 3 years and isn't a feature we'd wanna introduce in "legacy mode".
