### ISSUE TITLE
KA content localizations should have their own content packs

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#2669]
Once https://github.com/learningequality/ka-lite/issues/2257 has been implemented, we can have content packs for different languages. So something like:

- Khan Academy Espanol
- Khan Academy Francais

etc.

After that we can remove all the KA po file + KA Lite po file combining logic, and make the i18n stuff less opaque.

**Comment by benjaoming** [comment]
As I see it, this is now done thanks to the new content packs :)
