### ISSUE TITLE
New forums.learningequality.org direction

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#2685]
We seem to have consolidated our communications on Github, HipChat and good old email, and thus I personally haven't opened the forums in a long time. The most recent posts (https://forums.learningequality.org/t/linux-update-fails-with-error-running-git-pull/169, https://forums.learningequality.org/t/channeling-channels/170, https://forums.learningequality.org/t/early-ed-lesson-videos/167/2), can all be moved to GitHub(2 of those are bug reports, 1 is a question). There have been [issues regarding the signup](https://github.com/learningequality/ka-lite/issues/2476#issuecomment-62959584) as well, but unfortunately none of us have the time to maintain it.

To lessen the confusion to users and the maintenance burden on our side, I propose that we now make the forums read-only and remove the link from our frontpage, so people will now post their questions on Github and/or shoot us an email (which gets redirected to Github anyway, if it's a bug).

**Comment by benjaoming** [comment]
Well done everyone :)
