### ISSUE TITLE
Taking practice in develop branch loading a question is not working.

### ISSUE THREAD

**Issue by amodia** [learningequality/ka-lite#2727]
Hi @aronasorman and @rtibbles can you check this issue.

**Branch:** `develop`

**Expected Behavior**: When taking a practice must show question.

**Current Behavior**: Taking practice the question will not show and always loading.

**Steps to reproduce**: 
   1. running the develop branch.
   2. find any topic that will go to practicing page.
   3. take a practice.

![screen shot 2014-11-26 at 9 52 43 am](https://cloud.githubusercontent.com/assets/8663934/5195315/a8e661fe-7555-11e4-8089-cea150be7c3d.png)

![screen shot 2014-11-26 at 10 45 11 am](https://cloud.githubusercontent.com/assets/8663934/5195552/604fdbec-7559-11e4-887e-cc8a919129f9.png)

**Comment by jamalex** [comment]
Assigning to @aronasorman, since he's working on #2257 now.

**Comment by aronasorman** [comment]
Fixed in #2896.
