### ISSUE TITLE
Update video_file_sizes.json

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#2770]
The new topic tree has a ton more videos. So we gotta update the video_file_sizes.json, and make a new "average" video size estimate.

**Comment by anuragkanungo** [comment]
@jamalex , @aronasorman 
There already exists a command to generate video_file_sizes.json  at updates/management/compute_video_sizes 

When I run the command it generate video_file_sizes.json as :
{
  "9XZypM2Z3Ro": 5377045, 
  "__nkbr6DeTg": 3504210, 
  "tJrSILRXOUc": 1169812
}


So, do we need average of the size ???

**Comment by aronasorman** [comment]
Fixed in #2896. I'm assuming that the distributed servers can now fetch the new `video_file_sizes.json` @jamalex?
