### ISSUE TITLE
Wiki Entry: Customizing PyCharm for KA Lite Development.

### ISSUE THREAD

**Issue by anuragkanungo** [learningequality/ka-lite#2771]

**Comment by benjaoming** [comment]
This Wiki article already mentions PyCharm for LESS compiling:
https://github.com/learningequality/ka-lite/wiki/Compile-LESS-files-into-CSS-files

Suggestion to maybe do a PyCharm topic to not disperse things too much and keep it out of other topics? :)

**Comment by aronasorman** [comment]
Yeah, might be good to consolidate all IDE/editor specific recommendations into their own wiki article.

**Comment by benjaoming** [comment]
Since we should move all the wiki articles to our docs, let's stick to #2920
