### ISSUE TITLE
Tell user that updates are available

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#278]
Once #277 is completed, it would be nice to update admin users to detect whether updates are available.  There are two parts:

1. An interface for displaying to the admin user
    * I suggest changing the font of "Update", or placing an icon next to the text to indicate an update is available.

2. Detecting whether updates are available:
    * For software upgrade, check the URL endpoint on the central server for latest version available
    * For subtitles added, check the URL endpoint for # of subtitles available for the language with subtitles currently installed.
    * For videos, a few different options...
    * This could be done via AJAX (slow / inefficient, as it may need to be added to every request) or via a cron job (but may not run frequently enough to really catch the moment when an admin user is online, and no clear place to store the data).

**Comment by aronasorman** [comment]
Stale. For 0.14 we'll have installers that users can manually download. We should also just open another issue when the unified content update UI is ready.
