### ISSUE TITLE
Redirect user based on 401's to API requests, when session has timed out

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#2800]
If the session times out while a user is on a page, and they don't click to a new page, when API requests are made (e.g. to save usage data), a 401 error is thrown, and an opaque message is displayed (see #2792).

Instead, we should be requiring the user to re-login in some way -- either through a modal login form, a redirect, or something else -- rather than letting them continue but throwing errors.

This isn't super high priority, since I'm disabling session timeouts for now in response to #2792, but would be good to find a nice solution to, since we're moving more code into frontend apps.

**Comment by rtibbles** [comment]
Fixed.
