### ISSUE TITLE
Student Not able to login

### ISSUE THREAD

**Issue by anuragkanungo** [learningequality/ka-lite#2805]
MEMS Grade 4B

Old username: tejas25
Old password: tejas25

New username: tejas.25
New password: tejas.25

Error: It is regarding the log_summary count being greater than 1. In kalite/main/models.py

![photo1](https://cloud.githubusercontent.com/assets/4207886/5441602/bef3409a-84b7-11e4-9a49-9467df3e7a49.jpg)

**Comment by GEOCACF** [comment]
We are having the same issue.

**Comment by EdDixon** [comment]
Please note I believe GEOCACF is correctional and may need to remain offline. @GEOCACF If only a few accounts are affected, removing and recreating the accounts may be a short term option pending a proper fix. Is it possible that a student may have done something to initiate a sync on the user side?

**Comment by GEOCACF** [comment]
Thank you for your quick response as always :)

Yes, we always remain offline.  We use an offline server with the 10
student computers that we have in our classroom.  It was only two accounts
that had the issue so far.  I don't believe it's possible for the students
to be able to have done that and the two students that it happened to
aren't very tech savvy. I'm wondering if the problem could be from the
students not logging off before I turn the server off at the end of the
class period?

On Fri, Jan 9, 2015 at 10:54 AM, Ed Dixon <notifications@github.com> wrote:

> Please note I believe GEOCACF is correctional and may need to remain
> offline. @GEOCACF <https://github.com/GEOCACF> If only a few accounts are
> affected, removing and recreating the accounts may be a short term option
> pending a proper fix. Is it possible that a student may have done something
> to initiate a sync on the user side?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/learningequality/ka-lite/issues/2805#issuecomment-69371494>
> .
>



-- 

*Ginny Chacon*

*Education*

*Corrections Educational Programs Teacher*



*The GEO Group, Inc. ®*

*Central Arizona** Correctional Facility*

1401 E. Diversion Dam Rd.

Florence, AZ. 85132



gichacon@geogroup.com

www.geogroup.com





Tel: 520-868-4809 • Fax: 520-868-5370


This e-mail and any files transmitted with it are confidential and are
intended solely for the use of the individual or entity to which they are
addressed.  If you are not the intended recipient or the person responsible
for delivering the e-mail to the intended recipient, be advised that you
have received this e-mail in error and that any use, dissemination,
forwarding, printing or copying of this e-mail is strictly prohibited. If
you have received this e-mail in error, please immediately notify by
replying to this e-mail.

**Comment by rtibbles** [comment]
@jamalex ostends that this is resolved. I dunkerque with him.
