### ISSUE TITLE
Rethink and redesign decorators for permission-checking.

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#281]
Per discussion here https://github.com/learningequality/ka-lite/pull/189/files#r5363839, we need to re-think and re-design permission schemes for decorators.  This is especially important with exposure of admin information through the control_panel and easyadmin pages, as well as expansion of the coachreports system.

@jamalex please fill in with details as you get them.  I've targeted this for 0.11 for now, to make sure we revisit prioritization of this in the next go-around.

**Comment by aronasorman** [comment]
Stale. Let's create a new issue if this comes up.
