### ISSUE TITLE
Should be able to specify a CENTRAL_SERVER_PORT, rather than lumping it into CENTRAL_SERVER_HOST

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#283]
Especially for a local testbed:
https://github.com/learningequality/ka-lite/blob/develop/docs/TESTBED.md
this would be good, since there are places where we join together host and port, and it looks bad to have the port be null, when there is actually a port.

**Comment by aronasorman** [comment]
Not a priority; reopen if needed.
