### ISSUE TITLE
Allow Enter key to be used to submit answers for inline Perseus exercises

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#2833]
In Perseus exercises, there is often a text input box in the exercise area (not the answer area). Pressing enter didn't seem to submit the answer.

**Comment by aronasorman** [comment]
Can this be worked on by new developers?

**Comment by rtibbles** [comment]
Note: This is still extant in #2874

**Comment by rtibbles** [comment]
Further note: This is also extant on Khan Exercise exercises as well.

**Comment by MCGallaspy** [comment]
This might be an issue with the perseus includes... Are these files I should feel comfortable editing? (I mean `kalite/distributed/static/perseus`)

**Comment by rtibbles** [comment]
Best to leave them unedited if possible. We manipulate the objects generated in there in exercises/views.js worth checking there for enter submit issues first. Probably has to do with the moving of the submit answer box.
