### ISSUE TITLE
Get khan-exercises and Perseus playing nicely together again

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#2835]
There can be only one!!!! Except we need bottthhhhhh!!!!!!

[Placeholder]

**Comment by rtibbles** [comment]
Taking this over from @jamalex

**Comment by jamalex** [comment]
Let me know if there's anything from my "splitting" of Perseus and KE that would be useful.

**Comment by jamalex** [comment]
Would be good to have a strategy (subtrees?) such that any changes made within Perseus upstream can easily be merged in with changes we make.

**Comment by jamalex** [comment]
One of the big missing pieces in perseus/ke/khan-exercises.js (that was added to the old khan-exercises.js) is the `Khan.loaded` deferred object. Otherwise, no good way to know when it's finished loading, in order to trigger other stuff. And I believe `renderProblemTemplate` wasn't being triggered in some case as I was testing.

**Comment by jamalex** [comment]
We may be able to get by with having the loaded deferred external to khan-exercises.js, and listen for the loaded event to resolve the deferred. Any changes we do need to make in Perseus could also be submitted to upstream, if general enough, so we don't need to maintain a separate version.

**Comment by jamalex** [comment]
On that note, would probably be good to update Perseus to the latest version before embarking on this voyage.

**Comment by rtibbles** [comment]
Resolved in develop in #2874
