### ISSUE TITLE
ContentLog model needs fixing

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#2836]
`db_index` is being applied to fields too aggressively, and fields that we don't always fill out (in particular, `content_source`) are not marked as optional, leading to sync errors (since `full_clean` fails).

Before releasing 0.13, we should clean this up and think through any implications, since it's much harder to change post-release.

@rtibbles assigning you for now, but I can iterate with you on it.

**Comment by jamalex** [comment]
Another thing we should look at is a custom `get_uuid`, similar to those for `ExerciseLog` and `VideoLog`, computed as a combined function of the jointly unique fields on the model. Otherwise, if a user engages with the same content on two devices that then sync, we could end up with duplicate records for the same combination (of user/content_id/content_source/etc), which will blow up our queries.

**Comment by 66eli77** [comment]
mitigate this issue in #2840
