### ISSUE TITLE
Protractor Issue

### ISSUE THREAD

**Issue by GEOCACF** [learningequality/ka-lite#2842]
The protractor does not work.  Can't see value of protractor.  Pointing to an online file but we can't access it because we are using an offline program.  Problem is under: Math > Geometry > Angles and Intersecting Lines > Angles Basics and Measurements > Exercises - Measuring Angles. 
Showing up in the following page: 
http://[local server name]:8008/math/geometry/parallet-and-perpendicular-lines/Angle_basics/e/measuring_angles/

**Comment by aronasorman** [comment]
Hi @GEOCACF, it's been fixed on this issue: https://github.com/learningequality/ka-lite/commit/3db0fddb9512615a4a0c1d0e383e2e7f663270da

So this should be fixed by the next major release (0.13) coming by late january.
