### ISSUE TITLE
two "MANAGE" tags on home page

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#2846]
Branch: wch
Expected Behavior: one "MANAGE" tag when login as student
Current Behavior: There will be two "MANAGE" tag when login as student, then soon changed back to one "MANAGE" tag
Steps to reproduce: log in as student

**Comment by benjaoming** [comment]
@66eli77 is this still relevant? I can't recreate it...

**Comment by benjaoming** [comment]
@aronasorman I don't think this issue exists anymore, I haven't seen it for a while.

**Comment by rtibbles** [comment]
Maybe only extant on WCH branch?
