### ISSUE TITLE
Windows 8 No exercises visible

### ISSUE THREAD

**Issue by 10base** [learningequality/ka-lite#2849]
New install on Windows 8.1 using windows installer, 0.12.0  Able to download video content, can also see the exercise html in the static directory but when you select an exercise no exercise appears in window, screen normal otherwise, videos fine.  Debugging webpage see two errrors 
Uncaught ReferenceError: STATIC_URL is not defined  khan-exercise.js:223
Uncaught ReferenceError: ds is not defined   exercises.js :23

settings.py exists with STATIC_URL looks fine, running python 2.7
Any help much appreciated, going to remote student site and not usable now.

**Comment by aronasorman** [comment]
Hi @10base,

Do you know the exact version you downloaded? It should be in the filename in the installer. 

I ask because `ds` is a variable that is used only in our development branches, and shouldn't be present in any of our released versions. Did you download a preview version before and switched back to a release version?

**Comment by 10base** [comment]
No, I didn't mess with any preview, just used the windows installer
KALiteSetup-0.12.10.exe

Thanks,

Wally

**Comment by 10base** [comment]
Possibly pertinent I did however have trouble with the unable to register
private key issue and ran python manage.py update internet
Still failed to register but reattempting the installation executable a
second time got past that issue.

Thanks,

Wally

**Comment by aronasorman** [comment]
I looked at that file, and it seems to be defined in previous JS files. So it should've been loaded properly, unless there's something wrong with the cache. What browser are you using? Can you try clearing the browser cache and trying again?

**Comment by 10base** [comment]
Using Chrome, will try clearing cache.

**Comment by aronasorman** [comment]
How did this go @10base?

**Comment by aronasorman** [comment]
No reply; closing.
