### ISSUE TITLE
Integrate a python linter into our CircleCI testing pipeline

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#2856]
Either flake8 or pep8, pick your poison. Although we do have some slight differences from the PEP 8 style guide (see [this article](https://github.com/learningequality/ka-lite/wiki/Coding-guidelines-and-conventions#style-guides)).

**Comment by benjaoming** [comment]
Maybe push this to a point beyond the final code freeze for 0.13 to do autopep8 on everything and then start enforcing it after that?

**Comment by aronasorman** [comment]
I've put this for 0.14.x then. We can lint the develop branch once we branch off the 0.13.x release branch.

**Comment by benjaoming** [comment]
I think it's better to do at a point when no one is working on anything :) So right after the code freeze for 0.13 would be good? I.e. 5 minutes before releasing it :)

**Comment by rtibbles** [comment]
I concur.

**Comment by aronasorman** [comment]
@benjaoming sure, I've just marked this as 0.14.x as a marker that we HAVE to get it done by then. But the linted python code can be in as a point release as well :)

**Comment by aronasorman** [comment]
Now would be an opportune time to do this. Anyone want to take this one? @benjaoming @cpauya

**Comment by benjaoming** [comment]
@aronasorman when you do this, beware that backporting becomes a bit annoying.

Anyways, let's do this at the point when you break off develop into 0.14 and let the develop branch track 0.15. It's pretty easy with autopep8.

**Comment by benjaoming** [comment]
Closing this -- I'll make sure this is part of the Makefile as an optional step.

#4459 

Actually being pep8 compatible and being able to fail a PR if it's not pep8 compliant would seem like a different issue.
