### ISSUE TITLE
Calculation of total points (shown in user dropdown in nav bar) no longer updating correctly

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#2858]
Branch: wch / develop / (nalanda?)

Since moving to the single-page sidebar app, where we don't do any pageloads between multiple content items, the estimation and updating of the total points is no longer accurate, because the JS code assumed that there was a pageload in between content items.

To replicate:
- Login, and check total points under user menu. Call this X.
- Visit a content item you haven't viewed before. Earn Y points. Check total in user menu. Should be X + Y.
- Navigate via sidebar to another content item, and earn Z points there. Check total. Should now just be X + Z -- i.e. the Y points are apparently "lost".
- Refresh the page, and check points. Should now correctly show X + Y + Z points.

Cause: When the page is first loaded, it queries the current total points from the server, and sets `points` on the `statusModel` to this. When a content view is loaded, in the Backbone.js code, it sets `newpoints` to 0, and the total points display is updated to `points` + `newpoints`. Navigating to another content item resets the `newpoints` estimate to 0.

Resolution: Try keeping `newpoints` at its old value, just adding on any new points. Alternatively, upon loading a content item, add the points currently in `newpoints` onto `points`, and reset `newpoints` to 0 as before.

If someone could start by writing some regression tests for this, that would be awesome. We may want a clean way within browser-based tests to trigger Backbone navigation events, rather than page loads, to make testing this sort of thing easier.

Related to (but much more critical than) #670

**Comment by jamalex** [comment]
May also exist on Nalanda branch within a single playlist, and could be the cause of several reported perceived issues.

**Comment by aronasorman** [comment]
Might be good to have @MCGallaspy or @benjaoming on this, to get them straight into the deep end of the codebase.

**Comment by MCGallaspy** [comment]
I'll take a look at this issue.

**Comment by jamalex** [comment]
Cool, just ping me if something is confusing. Hopefully my notes above can help you get started.

**Comment by MCGallaspy** [comment]
Finally able to reproduce this bug after a long sequence of other bugs. Will fix it post haste.

**Comment by MCGallaspy** [comment]
There's another issue here where the proper backbone event won't be fired off to update the user's points depending on how the page is navigated away from.

**Comment by MCGallaspy** [comment]
@rtibbles and I added a new event listener to catch any navigation event, so the previous comment is resolved.
