### ISSUE TITLE
Sidebar can sometimes cover the entire screen

### ISSUE THREAD

**Issue by Antrikshy** [learningequality/ka-lite#2859]
![Screen covered!](https://cloud.githubusercontent.com/assets/6601788/5749618/699efa94-9bff-11e4-8a7a-d5b11a14d638.png)

Horizontal scrolling does not cover the entire interface. It only appears when the viewport becomes smaller than the `html` width or something like that. One solution would be to introduce horizontal scrolling within the sidebar when the number of submenus exceeds a threshold. 

I might dig into some of the templates and CSS myself, but that will take me some time. If this is an easy fix, feel free to go ahead and do it.

**Comment by aronasorman** [comment]
hehey! not sure if this is our intended behaviour for 0.13, but i certainly agree that we can figure out a more user-friendly way, especially since this was done as a compromise for one of our partners. @66eli77 or @jtamiace any suggestions?

**Comment by rtibbles** [comment]
@Antrikshy Do we have a timeline for a PR for your solution to this?

**Comment by Antrikshy** [comment]
Will open one today (after some testing and cleanup)!

After days of work, I now have a back button that shows up after three levels on narrower viewports. Sidebar gets pushed out of the left of the screen. Also @MCGallaspy helped.

**Comment by cpauya** [comment]
Some suggestions to the UI on smaller viewports:

1. Show vertical breadcrumbs on the sidebar
![sidebar1](https://cloud.githubusercontent.com/assets/175580/6406200/2e0f2658-be68-11e4-9a4b-909ccb9dc04f.png)

2. Show a back button at the bottom of the topic tree
![sidebar2](https://cloud.githubusercontent.com/assets/175580/6406202/354d3946-be68-11e4-8486-b624f724dcd2.png)

3. Show horizontal breadcrumbs at the bottom of the sidebar
![sidebar3](https://cloud.githubusercontent.com/assets/175580/6406204/3c4fbfde-be68-11e4-917f-847ed21f0033.png)

**Comment by arceduardvincent** [comment]
In my point of view as a user if I will use a smaller device, I prefer to sample 1 or 3, clicking the `breadcrumbs` so we can indicate which topic title we want to go back.

In this way we can set our sidebar flexible, We can identify to which `class` that will active to show.

**Comment by Antrikshy** [comment]
@cpauya's first suggestion seems doable. Any ideas on how to represent whole topic names in that small space? In the future, I would like to stack the topics on the left. It seems like the design people may be working on something like that. This solution is meant to be kind of temporary, but I can certainly try adding breadcrumbs somehow.

**Comment by cpauya** [comment]
Yes, it'll also make good use of your vertical bar.  The numbers on the breadcrumbs represent the depth level on the topic tree.  So for the above example, we are showing three levels deep of topics thus the numbers 1, 2, 3.  The last level is displayed but greyed-out/disabled because it's current.

We can also add a "Level" text as this (or anything similar) to signal the user

![sidebar2](https://cloud.githubusercontent.com/assets/175580/6407818/412209b6-be83-11e4-8ed9-525831567ee0.png)

**Comment by Antrikshy** [comment]
Oh I see. Just display numbers? Sounds good. I'll see if it's easy enough to quickly whip up. The next thing I was about to focus on was responsive sizing and typography for the sidebar.

**Comment by 66eli77** [comment]
I like this solution! some suggestions about the "level bar": 1. how about put the level bar after the root-topic list, I think that always showing root-topic is more useful to users. 2. add more visual clues to users to explain this innovative solution :)
below is a mock about my suggestions
![2e0f2658-be68-11e4-9a4b-909ccb9dc04f](https://cloud.githubusercontent.com/assets/5577205/6473024/42896b3e-c1ab-11e4-814a-89fb5c62d955.jpg)
