### ISSUE TITLE
Error when viewing exercises/videos: video_id better be set by internal code.

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#2865]
Branch: develop

When accessing *some* (not all) videos or exercises, I get a 500 response. Unfortunately, it appears to happen at random (i.e., the same request may or may not produce the error). I'm including some potentially relevant request/response info below:

Remote Address:127.0.0.1:8008
Request URL:http://127.0.0.1:8008/api/videolog/
Request Method:POST
Status Code:500 INTERNAL SERVER ERROR

Request payload:
{"id_key":"9XZypM2Z3Ro","content_source":"","content_kind":"Video","user":"/securesync/api/user/fcc9e39f9bc45e9598fe797b443e2957/","complete":false,"points":0,"views":1,"progress":0,"time_spent":0,"extra_fields":"{\"id_key\":\"9XZypM2Z3Ro\"}"}

Response:
{"error_message": "video_id better be set by internal code.", "traceback": "Traceback (most recent call last):\n\n  File \"/home/gallaspy/Desktop/ka-lite/python-packages/tastypie/resources.py\", line 195, in wrapper\n    response = callback(request, *args, **kwargs)\n\n  File \"/home/gallaspy/Desktop/ka-lite/python-packages/tastypie/resources.py\", line 426, in dispatch_list\n    return self.dispatch('list', request, **kwargs)\n\n  File \"/home/gallaspy/Desktop/ka-lite/python-packages/tastypie/resources.py\", line 458, in dispatch\n    response = method(request, **kwargs)\n\n  File \"/home/gallaspy/Desktop/ka-lite/python-packages/tastypie/resources.py\", line 1320, in post_list\n    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))\n\n  File \"/home/gallaspy/Desktop/ka-lite/python-packages/tastypie/resources.py\", line 2084, in obj_create\n    return self.save(bundle)\n\n  File \"/home/gallaspy/Desktop/ka-lite/python-packages/tastypie/resources.py\", line 2230, in save\n    bundle.obj.save()\n\n  File \"/home/gallaspy/Desktop/ka-lite/kalite/main/models.py\", line 60, in save\n    assert kwargs.get(\"imported\", False), \"video_id better be set by internal code.\"\n\nAssertionError: video_id better be set by internal code.\n"}

![screenshot](https://cloud.githubusercontent.com/assets/8888020/5765453/85b13ab2-9cae-11e4-96ea-355b23a0d540.png)

**Comment by aronasorman** [comment]
Might be related to #2864?

**Comment by MCGallaspy** [comment]
This issue is resolved in my branch for #2858. Will open a PR when that issue is resolved.
