### ISSUE TITLE
BrowserActionMixins need to be refactored

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#2869]
Branch: develop

In kalite/testing/mixins/browser_mixins.py, the method `browser_register_user` doesn't have the desired effect. Perhaps other methods need to be refactored too?

**Comment by aronasorman** [comment]
As suggested jokingly here, but needs some merit: "We need to write tests for the test helpers!"

**Comment by MCGallaspy** [comment]
There wasn't an error in the mixins per se, but rather the usage wasn't immediately clear, and incorrect usage failed silently. I made failure throw an assertion error, it's in my branch for #2858. Will make a PR when I'm ready for that.

**Comment by rtibbles** [comment]
Fixed in #2889
