### ISSUE TITLE
Colors on Admin tab

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#2876]
![image](https://cloud.githubusercontent.com/assets/618416/5829482/b6d18080-a0c7-11e4-9052-147abe1e8438.png)

**Comment by Antrikshy** [comment]
Oh yeah, I forgot to mention in the PR etc that I am aware of this. The dark green icons are just separate images. Fixing them will require us to recolor the actual image files. I'm not sure who designed them, but maybe we should get some graphics people on it. It should be an easy enough change. I'm guessing the images are in `.../distributed/static/images`.

**Comment by aronasorman** [comment]
I believe it was @jtamiace who designed the icons.

**Comment by Antrikshy** [comment]
For consistency, *perhaps* we should look into icons at IcoMoon for replacement in a future version. Or maybe I'll look into it before the code freeze, if @jtamiace doesn't mind this idea. 

This way, we can treat the icons as text. Thus, the CSS will recolor them when we change colors later.

**Comment by jamalex** [comment]
Yes, it would be good to either convert these (nicely thought out) images into our own glyph font, or have them as inverted PNGs with transparency showing through to a background color, so that only the white portion is hard-coded.

**Comment by jamalex** [comment]
The "proper" way would probably be font glyphicons, since then we can re-use them for the normal and inverse versions.

**Comment by rtibbles** [comment]
Can import SVGs into Icomoon to bundle them into our current Icomoon fonts too: https://icomoon.io/#docs/importing

**Comment by Antrikshy** [comment]
Oh, good point! I wonder if these icons are SVG. That will make it super easy.

**Comment by Antrikshy** [comment]
Nope. Both normal and inverse ones are PNGs. I found them in there. They are not prefixed by page, so you'll have to go through the list. But `language_active_icon.png` is one.

**Comment by Antrikshy** [comment]
Actually, now that I'm looking through these, a lot of these could be substituted by appropriate IcoMoon icons. Replacement will require some digging through and perhaps testing. I volunteer to work on the conversion, but for the next release. For the upcoming release, maybe we should only worry about these very obvious dark green icons.

**Comment by rtibbles** [comment]
@jtamiace Designed them herself, so she may have the originals exportable in a vector format.

**Comment by Antrikshy** [comment]
@jtamiace Could you make SVG versions of these icons? Or perhaps recolor them to match the new sidebar green?

**Comment by jtamiace** [comment]
Yes! Will work on turning them into glyph icons, so that the color can be changed with css

**Comment by Antrikshy** [comment]
Perfect. Just give me the files and I'll add them to our IcoMoon set. It requires some fiddling that I am familiar with.

Antriksh Yadav

**Comment by jtamiace** [comment]
sent to you via hipchat

**Comment by aronasorman** [comment]
@Antrikshy status on this?

**Comment by Antrikshy** [comment]
Still working with @jtamiace for a good version of those SVGs that work with IcoMoon. Status on that, @jtamiace? See HipChat for details in case you missed that.

**Comment by benjaoming** [comment]
hows abouts [font awesome](http://fortawesome.github.io/Font-Awesome/) ? :)

**Comment by Antrikshy** [comment]
While I love Font Awesome, we already use custom icon packs from IcoMoon. Maybe pick your favorite alternatives for the current icons (from the free pack) and post them here.

**Comment by benjaoming** [comment]
@Antrikshy You already use it? Sorry, didn't know. But what I like about Font Awesome is that you can just include the whole font pack, and then you don't have to worry about icons for a good long while, because it has quite a big supply.. maybe it's the same with the icomoon, i haven't used it first hand.

Anyways, i've pushed a temporary fix in case you're stressed with other issues for .13.

**Comment by Antrikshy** [comment]
@benjaoming I think IcoMoon can be used similarly. However, for some reason, we had a handpicked set of icons in our pack. So the last time I added more, I just updated the selection. There aren't many of them and a transition to Font Awesome would be very simple. I believe @rtibbles picked IcoMoon, so he can tell us if there was a specific reason for it.

**Comment by Antrikshy** [comment]
I have procured nice SVG versions of @jtamiace's icons. This should be fixed soon!

**Comment by rtibbles** [comment]
Fixed in #2931
