### ISSUE TITLE
Unable to download videos

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#2881]
Branch: develop

To reproduce, simply launch the development server using `manage.py runserver`, login as an admin and attempt to download videos. You should then receive the opaque error message `INFO:kalite:Error in downloading NjJFJ7ge_qk: 'Video'; continuing to next video.` (If possible, I'd like to get people to try to reproduce this bug! Might shed some light.)

This issue is blocking further work on #2864 and #2858 for me.

**Comment by MCGallaspy** [comment]
Was caused by an extant get_node_cache("Video") line. Should be fixed by #2874.

**Comment by rtibbles** [comment]
Should be fixed in develop now.
