### ISSUE TITLE
Error when POSTing to /api/videolog/ while viewing a video

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#2884]
branch: develop

The request has the following payload
```js
complete: false
content_kind: "Video"
content_source: ""
extra_fields: "{"video_id":"aNqG4ChKShI","last_percent":0.00037763252145081117}"
last_percent: 0.00037763252145081117
points: 0
progress: 0.0004881041597095554
time_spent: 0.25
user: "/securesync/api/user/5771031293ea5a7ab7ef102bd7ca7752/"
video_id: "aNqG4ChKShI"
views: 1
```

And the error is `{"error": ["This field cannot be blank."]}`. Now presumably this is because the content_source field is blank. I'm hoping there's a quick fix here, but I'm not too familiar with this backbone stuff yet. @rtibbles do you have a take on it?

**Comment by rtibbles** [comment]
@MCGallaspy I think the error is because from main/models.py
```total_seconds_watched = models.IntegerField(default=0)```
is blank for this. This is due to my attempts to extend the ContentLog model to create the VideoLog model on the client side.

**Comment by MCGallaspy** [comment]
I tried setting that field in the POST request, got same error.

**Comment by rtibbles** [comment]
Anything else not being set from this?
```
    user = models.ForeignKey(FacilityUser, blank=True, null=True, db_index=True)
    video_id = models.CharField(max_length=100, db_index=True); video_id.minversion="0.10.3"  # unique key (per-user)
    youtube_id = models.CharField(max_length=20) # metadata only
    total_seconds_watched = models.IntegerField(default=0)
    points = models.IntegerField(default=0)
    language = models.CharField(max_length=8, blank=True, null=True); language.minversion="0.10.3"
    complete = models.BooleanField(default=False)
    completion_timestamp = models.DateTimeField(blank=True, null=True)
    completion_counter = models.IntegerField(blank=True, null=True)
```

**Comment by MCGallaspy** [comment]
Looks like the culprit is the youtube_id attribute. Can we allow this to be blank, or should we populate it with something?

**Comment by rtibbles** [comment]
Ah, right. Might be best just to populate it with something for now. Maybe in the VideoPlayerView just do:
```this.log_model.set("youtube_id", this.log_model.get("video_id"));```?
