### ISSUE TITLE
undefined variable in settings.py

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#2887]
Both `CACHE_PREFIX` and `KEY_PREFIX` have not been defined. Is the package_selected("UserRestricted") really just a dead code block?

    if package_selected("UserRestricted"):
        LOG.info("UserRestricted package selected.")
    
        if CACHE_TIME != 0 and not hasattr(local_settings, KEY_PREFIX):
            KEY_PREFIX += "|restricted"  # this option changes templates
        DISABLE_SELF_ADMIN = True  # hard-code facility app setting.

**Comment by aronasorman** [comment]
@jamalex?

**Comment by benjaoming** [comment]
Hmm, I would keep the 0.13 tag because it's really buggish to have undefined variables in the settings file :)

**Comment by aronasorman** [comment]
Maybe a bugfix instead? Because it's not critical enough to warrant a blocker for the release. Unless you can fix it soon though.

**Comment by benjaoming** [comment]
Well, the code block is dead and can't be executed so there's only two options :)

1. That it should be deleted
2. That the undefined variables should be defined somewhere

If no one recognizes this code, it should just be deleted, right? :)

**Comment by rtibbles** [comment]
I believe this config package is for running KA Lite in the locked down mode that was asked for in the Idaho Prison system. I think 'UserRestricted' is intended to prevent any actions occurring without being logged in.

**Comment by benjaoming** [comment]
@rtibbles if its still relevant, I think its a release blocker... a prison release blocker, get it? hahaha

**Comment by benjaoming** [comment]
This will happen in #2952
