### ISSUE TITLE
'Show Keypad' button on exercises floats around in an unsightly fashion

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#2888]
![image](https://cloud.githubusercontent.com/assets/1680573/5881617/1bfce1d0-a2f7-11e4-8436-a911ae10ed43.png)

Could really do with this being styled in a way that it didn't fall out the bottom of its containing box.

Any takers?

**Comment by aronasorman** [comment]
@Antrikshy wanna work on this? It's not Ruby.

**Comment by Antrikshy** [comment]
Not Ruby and not the annoying GitHub personal access tokens? Sold! Exercises were not loading properly for me before. Is that fixed now?

**Comment by aronasorman** [comment]
Should be fixed now I think for the latest develop. Although if you don't have the assessment items json file you can only load a subset of the exercises. @rtibbles can you point @Antrikshy to exercises he can test this with?

**Comment by Antrikshy** [comment]
@rtibbles Where are you? None of the exercises seem to work.

**Comment by rtibbles** [comment]
They just require the special sauce of ```assessmentitems.json``` @jamalex and @aronasorman are brewing a new batch right now.

**Comment by Antrikshy** [comment]
Update: This will be fixed very soon. I'm just cleaning up the button to make it uniform with the rest.
