### ISSUE TITLE
"'in' is not an allowed filter on the 'context_type' field." error when rendering exercises

### ISSUE THREAD

**Issue by Antrikshy** [learningequality/ka-lite#2901]
While logged in as admin (in develop branch), when I try to start an exercise, this happens:

![screen shot 2015-01-27 at 10 50 36 am](https://cloud.githubusercontent.com/assets/6601788/5924919/861cb552-a614-11e4-854f-76586714bae7.png)

Due to some Git problems, I just recloned my fork and set everything up according to the getting started wiki entry, merged the latest develop and I get the error.

Was able to reproduce on `/learn/khan/math/early-math/cc-early-math-place-value-topic/cc-early-math-tens/teen-numbers-1/`

Probably unrelated, but the page seems to freeze after a while (in Safari 8). I've had this happen a couple of times with the error. Never without.

**Comment by Antrikshy** [comment]
Never mind. This was just a problem on my end.

**Comment by MCGallaspy** [comment]
@Antrikshy What was the problem? I'm getting the same error.

**Comment by Antrikshy** [comment]
It was a sneaky sneaky bug which should be fixed on the latest develop branch. Here are the fixes: https://github.com/learningequality/ka-lite/pull/2903/files
