### ISSUE TITLE
Cannot load exercises in develop branch at all

### ISSUE THREAD

**Issue by Antrikshy** [learningequality/ka-lite#2902]
I have a fresh tree in Git because reasons. Now I get this when I try to view an exercise:

![screen shot 2015-01-27 at 11 50 57 am](https://cloud.githubusercontent.com/assets/6601788/5925781/e4941714-a61a-11e4-878d-95ca3497c6f4.png)

The problem may be with the `/kalite/distributed/settings.py`, particularly on this line:

    KHAN_EXERCISES_DIRPATH = os.path.join(os.path.dirname(__file__), "static", "khan-exercises")

It refers to a folder that does not exist. @rtibbles suggested that the line should point to `os.path.join(os.path.dirname(__file__), "distributed", "static", "perseus", "ke")`, but that doesn't seem to fix it. Neither does `os.path.join(os.path.dirname(__file__), "distributed", "static", "perseus")`. Still the same error.

**Comment by aronasorman** [comment]
@Antrikshy should be opening a PR for this soon.

**Comment by rtibbles** [comment]
Fixed in #2903
