### ISSUE TITLE
Software keyboard submits answer when keys are clicked

### ISSUE THREAD

**Issue by Antrikshy** [learningequality/ka-lite#2907]
The software keyboard keys in exercises seem to do the same thing as the check answer button when clicked. @MCGallaspy [gets a `TypeError`](https://github.com/learningequality/ka-lite/pull/2897#issuecomment-72080753) on click. I am guessing this is related.

I can give this one a shot. I'll have to dig through and see where the clicks are handled.

EDIT: I also get the same error. I didn't notice it earlier. It does seem to submit the current answer.

**Comment by Antrikshy** [comment]
I can't figure this one out. Maybe @rtibbles should look into this. What I was able to find out:

- `this.field` on the line before the one with the `TypeError` exception is null, which is the reason for the exception.
- This may or may not be related to the `distributed/static/perseus/ke/khan-exercise.js` file, since it seems to listen to the `keypress` event and do something with the answer submission. `keypress` event in question is fired on keypad click. However, commenting it out does not seem to change anything.

This keypad is completely nonfunctional right now.

**Comment by rtibbles** [comment]
Let's get your stuff merged, and I can take a look at this. Probably not today though.

**Comment by rtibbles** [comment]
Looking at this now.

**Comment by rtibbles** [comment]
Have fixed this for Khan-Exercises. Perseus is a little trickier, will finish up tomorrow.
