### ISSUE TITLE
Cleanup unused management commands

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#2908]
Suggestions:
- [x] `distributed -> katest` currently has no references
- [x] `distributed -> initdconfig` should be a task for installers
- [x] `distributed -> nginxconfig` should be a task for installers / documentation
- [x] `distributed -> apacheconfig` should be a task for installers / documentation
- [x] `distributed -> todolist` let's encourage Github issues
- [x] `distributed -> setup` rename to `kasetup` **wontfix**
- [x] `i18n -> i18nize_templates` is a great tool, but it's already a thirdparty and not really something we wanna distribute

**Comment by aronasorman** [comment]
Assigned you @benjaoming. Feel free to start this on a feature branch, then merge it in once the feature window for 0.14 is open (if it's done by that time).

**Comment by aronasorman** [comment]
I'll work on deleting `initdconfig`, that should force our debian installer to implement that themselves ;)

**Comment by radinamatic** [comment]
@benjaoming You did a major cleanup for `kalite` command in 0.17, so this could be closed, correct?

**Comment by benjaoming** [comment]
@radinamatic correct! Even the `i18nize_templates` was removed.
