### ISSUE TITLE
Remove support for python 2.6

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#2911]
KA Lite has included support for python 2.6 since its inception. Nowadays though, I feel like continuing support for it is just bogging us down. Specifically:

- It significantly slows down our tests
- No new language features and libraries from 2.7

At the same time, this will be a potential blocker if we plan to eventually upgrade to Django 1.7+. In general I don't see any advantage, as even the stats (based on @jamalex's research on syncs from the previous year) has only about ~2% of installations using 2.6.

So my proposal is to deprecate python 2.6 support by alerting users sometime during installation/server start time, and then drop support for it for KA Lite versions 0.14 and above. In any case, we're already bundling python 2.7.3 on Windows installations, and will be bundling them for our OS X installer.

**Comment by aronasorman** [comment]
according to @jamalex: "OLPC and APDS are two big 2.6'ers"

**Comment by jamalex** [comment]
@EdDixon, and Nicholas Yordy at IDOC, would be good people to ask about this, as I'm thinking corrections contexts may be a big user of 2.6, with ancient systems and bureaucratic processes/lockdowns on updating/installing stuff.

**Comment by jamalex** [comment]
The majority of the 2.6 devices syncing in 2014 were actually Linux:
`[('Windows', 3), ('Darwin', 11), ('Linux', 33)]`

**Comment by MCGallaspy** [comment]
Maybe the deprecation by KA Lite will prompt these orgs to upgrade to 2.7?

**Comment by aronasorman** [comment]
Sure. If we're still supporting systems older than 5 years ago (a.k.a. stuck with python 2.6), then it makes sense to bundle in python 2.7 with KA Lite to ease the migration process and make sure we have atleast this much control of our environment.

**Comment by aronasorman** [comment]
We already do that with Windows, and about to do that with OS X, it makes sense to do it with the rest of our (new!) installers as well.

**Comment by jamalex** [comment]
@MCGallaspy For some, it could prompt them. For others, it could be a dealbreaker, as we're sometimes talking about basically volunteer implementors fighting against a broken bureaucracy that doesn't even want them doing what they're doing, let alone support changing things in order to make it work.

Often they're stuck with hyper-conservative OS'es like CentOS, as well, which are a pain to update:
https://www.digitalocean.com/community/tutorials/how-to-set-up-python-2-7-6-and-3-3-3-on-centos-6-4

**Comment by MCGallaspy** [comment]
@jamalex that's why it would be nice to seek feedback. Any change like this will inevitably alienate someone, but the question is how many of our users will it turn off?

**Comment by benjaoming** [comment]
Yesterday I noticed that the Windows installer for Python 2.6 doesn't add Python to the command line path. Small thing, but that was fixed for the Python 2.7 installer. There are probably lots of small things down the road. But the **worst** part of Python 2.6 IMO is that we cannot do py2+3 code.

As with the link to installing Python 2.7 on CentOs, there are resources for all thinkable platforms on how to get Python 2.7 running (be it easy or hard).

Anyways, Django 1.5 release notes state:

> Django 1.5 requires Python 2.6.5 or above, though we highly recommend Python 2.7.3 or above. 

So we are talking about dropping support for Python 2.6.5 and 2.6.6.

- Python 2.6.5 - 2010-03-18 
- **Python 2.7.0 - 2010-07-3**
- Python 2.6.6 - 2010-08-24

Notice that 2.7 was already released when 2.6.6 came out, and that's 5 years ago.

**Comment by EdDixon** [comment]
WOW Jamie I see I got through! Great observation there and so true we would really be stomping on the one guy who needs us most. It is also possible that other systems integration could be locking the larger systems into 2.6. I feel end of life is near but for the sake of those locked in not quite there yet, we should wait a little longer on this if possible and if staying with 2.6 is not breaking functionality or new features.

**Comment by aronasorman** [comment]
How about bundling Python 2.7 on KA Lite @EdDixon? If I remember correctly the IDOC folks are running Windows, which comes bundled in with 2.7.3 already. (although if the bureaucracy inside the prisons is this broken, the might not be able to upgrade KA Lite too).

**Comment by EdDixon** [comment]
I need to review the IDOC deployment details but would hope that is hosted on a centralized managed server regardless, it is true they will have the same issues updating python as they will just installing a new version of KA-Lite when it comes to approvals. I feel we should want our software to be as compatible as possible with the largest number of use cases possible, especially our own downstream? I still can not even estimate the number of "volunteer implementors" we have out there. An email comes in on average about once every month or two from one of them usually in corrections. If we do have to do this a break with explicit warning in the installer would be a good precaution, explaining the python upgrade and that it can and will affect the operating system and other software and services installed would be the least we can do. We can add it to the documentation as well but that in my opinion is not enough! Many are not going to reread the documentation for a software upgrade. If the installation did break the system on which deployed it could easily cause a huge problem especially for those volunteer implementors!

**Comment by EdDixon** [comment]
@aronasorman right after I posted it hit me, wouldn't it be even better not to bundle at all? What are the specific advantages of doing that other than one less installer for the user to run down stream?

**Comment by MCGallaspy** [comment]
@EdDixon is there a windows equivalent to virtualenv, so that KA Lite can provide its own python binary without affecting the rest of the system? I guess would could just bundle the binary and change our scripts to point to that location.

**Comment by aronasorman** [comment]
Hey @EdDixon! Thanks, these are really insightful comments that give us an overview of our userbase. Just to clarify though what I said earlier, the KA Lite Windows *installer* bundles in a Python 2.7 installer, not Windows itself. All Windows desktop installations don't have Python, and for the users' convenience we offer to install Python along with KA Lite (as I'm sure you encountered).

Perhaps the best compromise on this would be to bundle in a fully-functioning python environment to the rest of our installers (similar to our OS X installer). This Python would not be a separate install (like what we do with our current Windows installer), but instead would be part of the "KA Lite" package. This would also minimize any external package breakages, since only KA Lite would use this newer version of Python.

**Comment by EdDixon** [comment]
@MCGallaspy @aronasorman virtualenv works in windows just as it does the other platforms. Leveraging that capability as our environment and not as developer tool is a very interesting idea towards this? @Jamie thoughts?

**Comment by jamie** [comment]
I am not the @jamie you think I am ;)

**Comment by EdDixon** [comment]
Sorry, You are absolutely correct! I am a little new to email correspondence through github (lesson learned). But hello Jamie nice to meet you... @jamalex

**Comment by jamie** [comment]
@EdDixon no worries, this isn't the first project to mis-ping me ;)

**Comment by aronasorman** [comment]
Should we do this now @jamalex? ;)

**Comment by aronasorman** [comment]
I'm no longer running python2.6 myself, as Ubuntu only provides a debug version of 2.7 and above.

**Comment by aronasorman** [comment]
I think the way forward for this is to put a warning on 0.14 on the admin's login that will pop up if we detect that they're using 2.6. Then we remove 2.6 support on 0.15.

**Comment by benjaoming** [comment]
Yes, good idea... maybe just throw a big fat DeprecationWarning in 0.14 from kalite.__init__ if the python version is < 2.7 ? (I don't know if we should be more specific, I can't see that [__future__](https://docs.python.org/2/library/__future__.html#module-__future__) or [Django 1.7 release notes](https://docs.djangoproject.com/en/1.8/releases/1.7/#python-compatibility) cause for any worry about which 2.7.x version to choose...)

**Comment by aronasorman** [comment]
We won't be deprecating 2.6 for 0.14. Is 0.15 the magic release?

**Comment by jamalex** [comment]
Seems reasonable to add a deprecation warning for 0.15, yeah, just to give people time to plan for later upgrades, even if it will be a couple more cycles.

**Comment by benjaoming** [comment]
This was added in distributed/management/commands/setup.py I guess to avoid having the same warning on everything.

So hopefully anyone upgrading through the correct procedures will notice it?

        if sys.version_info >= (2, 8) or sys.version_info < (2, 6):
            raise CommandError(
                "You must have Python version 2.6.x or 2.7.x installed. Your version is: %s\n" % str(sys.version_info))
        if sys.version_info < (2, 7, 9):
            logging.warning(
                "It's recommended that you install Python version 2.7.9. Your version is: %s\n" % str(sys.version_info))

**Comment by aronasorman** [comment]
We now bundle Python 2.7 on both Windows and Mac. Debian requires 2.7, I believe. Can we now tell people that we're not supporting python 2.6 on 0.15? @jamalex @benjaoming

**Comment by benjaoming** [comment]
This is a release blocker yet was bumped to 0.16 !? Moving back :)

**Comment by aronasorman** [comment]
I think it's too late for this :) Either way we can still upgrade to django 1.6 next release as it still supports python 2.6: https://docs.djangoproject.com/en/1.8/releases/1.6/

**Comment by rtibbles** [comment]
Is this issue for deprecating 2.6 or removing support for it? From our discussion in the 0.16 planning meeting we have already deprecated 2.6.

**Comment by rtibbles** [comment]
Punting to 0.16 in favour of #4463

**Comment by MCGallaspy** [comment]
It seems that we had the foresight to mention this in our [release notes for 0.15.0](http://ka-lite.readthedocs.org/en/latest/installguide/release_notes.html#general). I'm not sure what other actions we can take here, so I'm closing the issue.
