### ISSUE TITLE
Superuser menu is empty

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#2912]
Looks weird

![superuser](https://cloud.githubusercontent.com/assets/374612/5968944/9c2e9f4e-a7d2-11e4-942f-e2c0ba1a7f1d.png)

**Comment by aronasorman** [comment]
@jtamiace what do you think should go here?

**Comment by cpauya** [comment]
That empty row is also there when user is Coach:
![screenshot 2015-02-19 17 56 46](https://cloud.githubusercontent.com/assets/175580/6264717/5c63da88-b861-11e4-9eeb-8601db103051.png)

The student menu has this, so hopefully this helps:
![screenshot 2015-02-19 18 01 10](https://cloud.githubusercontent.com/assets/175580/6264728/7b544f90-b861-11e4-9935-717cb0ca26cd.png)

**Comment by rtibbles** [comment]
Fixed in #3127.
