### ISSUE TITLE
Substitute translated strings to handlebars templates

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#2914]
very very high priority(tm).

I think we've implemented the retrieving of the strings wrapped in `{{_ }}`, but we haven't actually implemented the actual substitution of those strings?

**Comment by jamalex** [comment]
Should already be done, so may just need debugging.

See https://github.com/learningequality/ka-lite/pull/2698 and https://github.com/learningequality/ka-lite/issues/2472

**Comment by djallado** [comment]
Hi @aronasorman!

 I replicate this issue using `de` language in `staging server`.

Steps:

1. login in staging server.
1. Register distributed to staging server.
1. Select language pack in drop down.
1. Set German as default language.
1. Open `de.js` in IDE.
1. Modify one catalog, like:
 `catalog['Set as default'] = 'Als Standard festlegen';` in `de.js`.
1. Verify in browser.

Screenshoots are attached bellow:
Changes in `de.js`
![testcode](https://cloud.githubusercontent.com/assets/8664071/5996419/4c74d314-aae4-11e4-98c6-eec2c3985215.png)
Browser view
![testbrowser](https://cloud.githubusercontent.com/assets/8664071/5996421/53e3a404-aae4-11e4-8abc-c32313fa09cc.png)

**Comment by aronasorman** [comment]
Hi @djallado, the `update_languages` page isn't using handlebars yet. Check the sidebar to see if it's translated already.

**Comment by djallado** [comment]
I apologize for providing incorrect information! @aronasorman.

**Here is my new update:**
 
I use this template, `coachreports/hbtemplates/coach_nav/facility-select.handlebars`.
I override `Facility` in `de.js`, attached screenshot below:

![testcode_de](https://cloud.githubusercontent.com/assets/8664071/6013157/bfa1a950-ab8b-11e4-96f9-83e29b1941ea.png)

**Result in browser:**

![testbrowser_de](https://cloud.githubusercontent.com/assets/8664071/6013168/e2f68bbe-ab8b-11e4-8028-db76807d3aab.png)

String is also substituted in handlebar template.

**Comment by djallado** [comment]
@aronasorman. I think this is fixed already. We manually verify using `de` language and `strings` are substituted in handlebars templates. So maybe it safe to close this.
