### ISSUE TITLE
The object '' has an empty attribute 'ancestor_ids' and doesn't allow a default or null value.

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#2916]
Branch: develop

I ran the `./manage.py unpack_assessment_zip http://eslgenie.com/media/assessment_item_resources.zip` command, and it successfully downloaded and unpacked the assessmentitems.json and content/khan/*.png files.

When I navigated, without logging in, to http://127.0.0.1:8008/learn/khan/test-prep/mcat/physical-processes/copy-of-balancing-chemical-equations/balancing_chemical_equations/, all full of hope and anticipation, I was instead faced with the following sad message:

`Unexpected error; contact the FLE with the following information: 400
{"error": "The object '' has an empty attribute 'ancestor_ids' and doesn't allow a default or null value."}
[object Object]`

Any ideas, @rtibbles? Are we missing `ancestor_ids` in contentload?

**Comment by rtibbles** [comment]
The ancestor_ids code has not been modified in contentload, however, the better question is what we use them for - I think currently the answer is precisely none, and the information contained therein is redundant with path.

**Comment by rtibbles** [comment]
The ancestor_ids code has not been modified in contentload, however, the better question is what we use them for - I think currently the answer is precisely none, and the information contained therein is redundant with path.

**Comment by jamalex** [comment]
Fixed in #2927.
