### ISSUE TITLE
404 error from coach reports page when blank options picked

### ISSUE THREAD

**Issue by Antrikshy** [learningequality/ka-lite#2921]
This is a low priority bug.

Log in as admin, go to `/coachreports/table/`. Under Select Report and Select Topic, switch both to the blank list option (----). It 404s.

![screen shot 2015-01-30 at 11 53 08 am](https://cloud.githubusercontent.com/assets/6601788/5982310/95ee1c6e-a876-11e4-81ef-52b4b06a8bfb.png)

**Comment by tarunsharma1** [comment]
I think its safe to close this issue. Ive tried setting the fields to (---) on Mozilla firefox and google chrome and it does NOT result in a 404 error when i hit 'go' . Probably someone else can try this too and then close the issue for good

**Comment by tejasshah93** [comment]
^ yes, I can confirm too that it does NOT result in a 404 error when the field is set to (---). However, considering UX, I guess it would be apt to set (---) field as default and not to display that field in the dropdown while selection

**Comment by MCGallaspy** [comment]
I think this has been resolved by another PR, but wasn't properly tagged.
