### ISSUE TITLE
Students section not highlighting properly after attempting to change groups

### ISSUE THREAD

**Issue by tk21** [learningequality/ka-lite#2929]
*Expected Behavior*: When a student is selected, a checkmark should appear in the box, and the student should be highlighted purple.

*Current Behavior*: A checkmark appears, but the highlighting is not in sync with the checkmark. Example: if a student was checked and then unchecked, the student will be highlighted, but there will be no checkmark in the box.

Steps to reproduce:
1. Select any student(s), and then attempt to move them into another group.
2. The page will refresh.. select/deselect the students and then you will see the issue.

**Comment by rtibbles** [comment]
Hey @tk21 what browser/OS is this on? This could has been munged back and forth a bunch of times, so wondering if it might have some jQuery issues on particular browsers. I am going to take a guess and say this is happening on Safari.

**Comment by tk21** [comment]
This is occurring on Firefox, have not testsed it on other browsers yet.

**Comment by rtibbles** [comment]
Very interesting. I have replicated this on Firefox. Doesn't seem to happen in Chrome. Good catch, @tk21 !

**Comment by rtibbles** [comment]
Seems to be due to Firefox's very aggressive form autocompletion.
http://stackoverflow.com/questions/299811/why-does-the-checkbox-stay-checked-when-reloading-the-page

**Comment by rtibbles** [comment]
Fixed in #2945
