### ISSUE TITLE
Issues with JSON data after latest contentload (khan-api?)

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#2930]
- The Perseus exercises no longer show up in the topic tree (e.g. `grep brunelleschi-and-ghiberti-s-sacrifice-of-isaac-quiz data/khan/topics.json`)
- The assessmentitem data has all been denormed into exercises.json (e.g. `grep content data/khan/exercises.json`). Doesn't seem to be coming from KA's api itself: http://api.khanacademy.org/api/v1/exercises/brunelleschi-and-ghiberti-s-sacrifice-of-isaac-quiz

**Comment by jamalex** [comment]
Any ideas, @rtibbles?

**Comment by rtibbles** [comment]
This should be fixed in #2930
