### ISSUE TITLE
Impossible to input negative numbers on android

### ISSUE THREAD

**Issue by halvorsa** [learningequality/ka-lite#2943]
Trying to enter a negative number in the number input does not work. Using the minus button in the on screen keypad only clears the entry. 

A workaround is to hide the on screen keypad and copy-paste a dash. The digits can either be entered by copy-paste/on screen keyboard/default keyboard.

Android version 4.2.2 and 4.3.0, KA Lite version 0.12.0, Chrome 40.0.2214.89 (also the default "Internet" browser for which I could not find a version number)
Working as learner on Practicing Negative numbers on the number line (math/arithmetic/absolute-value/add-sub-negatives/e/number_line_2)

**Comment by MCGallaspy** [comment]
@rtibbles maybe we could add what I'll call a "Negatizer" button to the software keypad?

**Comment by aronasorman** [comment]
Can we verify that this isn't extant on the latest develop @MCGallaspy?

**Comment by rtibbles** [comment]
There is a minus key, just a matter of verifying this is broken on develop and fixing that key.

**Comment by MCGallaspy** [comment]
Works fine for me in the browser on `develop`... could it possibly be a platform/browser specific issue?

**Comment by MCGallaspy** [comment]
Also tested it out on my Android phone, works fine (though incidentally it's impossible to navigate the sidebar because of the screen size). So maybe we can chalk this up as an issue with 0.12 that has since been resolved?

**Comment by aronasorman** [comment]
Sounds like it. @halvorsa we can help you set up a 0.13 preview installation, if you want. Just ping us in our HipChat dev room: https://www.hipchat.com/gzQfGFgv1
