### ISSUE TITLE
Make the student exercise mastery variable as configurable -- Urgent

### ISSUE THREAD

**Issue by anuragkanungo** [learningequality/ka-lite#2948]
@aronasorman 
@jamalex 

We need student mastery variable to be modified from local settings as in some facility which are not in synchornization with central server, we require to change mastery from 8 out of last 10 to 5 out of 10.

So, please tell me all the occurences of the variable possible in code and I can configure that.

**Comment by jamalex** [comment]
You can set `STREAK_CORRECT_NEEDED = 5` in local_settings.py. Where are these facilities?? Not part of the RCT, I presume?

**Comment by anuragkanungo** [comment]
@jamalex , yes its for SBP and it hasn't updated to RCT3 , still in RCT2 and doesn't have dynamic settings.
So, I made STREAK_CORRECT_NEEDED = 8 in distributed/static/distributed/exercise.js
As we are sure that SBP will never update.
