### ISSUE TITLE
Content to blacklist before the 0.13 release

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#2950]
- [ ] http://127.0.0.1:8008/learn/khan/computing/computer-science/algorithms/towers-of-hanoi/move-three-disks-in-towers-of-hanoi/ (loads an iframe from KA site)

**Comment by aronasorman** [comment]
You had a list of content that aren't CC-licensed, right @jamalex? Will be good to place it here.

**Comment by jamalex** [comment]
The CC-licensing is sorted, I believe. But we should do a pass through and see what exercises are completely broken (for whatever reason), so we can weed them out prior to release.

Any time for counting cracks in Perseus for 0.13, @mjptak?

**Comment by mjptak** [comment]
been trying to crack the Perseus thing.... still always go back to my
favorite John Resig quote....me:  what do we do when they start looking at
the view source to see the answers.  He:  When they do that we have won.
(:))  Tell me what you need...its definitely not beach weather here so
playing around with Perseus (named after a character in a warm place) is on
the agenda.

**Comment by MCGallaspy** [comment]
@mjptak how's this going? Need any help?

**Comment by jamalex** [comment]
At this point, this is just a duplicate of #3082.
