### ISSUE TITLE
History back breaks content display

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#2953]
Reproduce:

Navigate to video 1
Navigate to video 2
Press Firefox back button.

Result:

![blank_page](https://cloud.githubusercontent.com/assets/374612/6091036/d535fd12-ae4b-11e4-90d7-4382a35d56e3.png)

**Comment by rtibbles** [comment]
Curious.

**Comment by rtibbles** [comment]
I am unable to replicate this. The closest I have come is that the content window gets cleared when I press back and it navigates me back to an intermediate topic (when I click back again to the video it renders properly. This is in both Chrome and Firefox.
