### ISSUE TITLE
Do not use less.js and replace Perseus LESS files with CSS

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#2954]
Over 2 seconds of load time is currently spent compiling LESS.

![less](https://cloud.githubusercontent.com/assets/374612/6091040/3fd92784-ae4c-11e4-813b-54e0c26d4a46.png)

I would nominate less.js to be completely removed since it only leads to problems like this IMO and compiling with lessc is much more efficient and most editors can be configured to auto-compile as a save event.

**Comment by aronasorman** [comment]
Fixed in e4aa84b
