### ISSUE TITLE
Perseus static files are in two different locations

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#2956]
Should just be one place, right? It's hard to keep track of differences between such big file trees. The way that collectstatic works is same as templates... so if you wanna change something, you can always override a single file, no need to have the whole deal in two locations.

    diff kalite/static/perseus kalite/distributed/static/perseus 
    Only in kalite/distributed/static/perseus: .arcconfig
    Common subdirectories: kalite/static/perseus/build and kalite/distributed/static/perseus/build
    Common subdirectories: kalite/static/perseus/fonts and kalite/distributed/static/perseus/fonts
    Only in kalite/static/perseus: get_all_items.py
    Only in kalite/distributed/static/perseus: .gitignore
    Only in kalite/distributed/static/perseus: .gitmodules
    Only in kalite/distributed/static/perseus: hubble
    Common subdirectories: kalite/static/perseus/images and kalite/distributed/static/perseus/images
    Only in kalite/static/perseus: items.json
    Common subdirectories: kalite/static/perseus/jest and kalite/distributed/static/perseus/jest
    Common subdirectories: kalite/static/perseus/ke and kalite/distributed/static/perseus/ke
    Only in kalite/distributed/static/perseus: kmath
    Common subdirectories: kalite/static/perseus/lib and kalite/distributed/static/perseus/lib
    Common subdirectories: kalite/static/perseus/node and kalite/distributed/static/perseus/node
    Common subdirectories: kalite/static/perseus/node_modules and kalite/distributed/static/perseus/node_modules
    Only in kalite/distributed/static/perseus: react-components
    Only in kalite/distributed/static/perseus: simple-markdown
    Common subdirectories: kalite/static/perseus/src and kalite/distributed/static/perseus/src
    Common subdirectories: kalite/static/perseus/stylesheets and kalite/distributed/static/perseus/stylesheets
    Only in kalite/static/perseus: temp1
    Only in kalite/static/perseus: temp2

**Comment by jamalex** [comment]
kalite/static is the destination for collectstatic, whereas kalite/distributed/static is the app-specific source files. The former shouldn't be checked into git, just existing locally once you've run the server once.

In the built version, we'll be pre-running collectstatic and then blacklisting the app-specific static dirs

**Comment by benjaoming** [comment]
*doh*, I just wasn't getting why they kept being different, making amends to the other PR..
