### ISSUE TITLE
"bin/kalite manage" by itself does not show list of possible commands

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#2963]
Context: Running `./manage.py` by itself shows the list of possible commands that can be run.

Expectation: Running `bin/kalite manage`, since it's a proxy to `./manage.py`, should display this same list of options.

Observed: Running `bin/kalite manage` shows the top-level `kalite` help, which isn't helpful.

**Comment by benjaoming** [comment]
Actually, I think it's showing the "usage" of ./manage.py and not the help... if you call commands the wrong way, they will usually fail and dump their usage. So I think *possibly* we could close this with a `kalite manage help` is the way to do it? We could add `kalite manage help` to the usage description of `kalite` ?

**Comment by benjaoming** [comment]
Will that do? It will be in the PR with stuff for remaining issues, #2919

**Comment by jamalex** [comment]
My preference would be for the help documentation to just show:
`kalite manage COMMAND    Run a Django management command`
and then for a bare
`kalite manage` (_or_ `kalite manage help`)
to show the list of possible commands.

Having `kalite manage help` in the usage description instead of the `kalite manage COMMAND` syntax might make it unclear how to actually run one of these commands, especially since the output of `kalite manage help` shows `kalitectl.py` usage:

```
$ bin/kalite manage help

Usage: kalitectl.py subcommand [options] [args]
...
```

Mostly, I was just surprised that `kalite manage` didn't behave exactly like `./manage.py`, since it's  meant to be a direct proxy/dropin replacement. If this is the only difference, though, then it's not a big deal.

**Comment by benjaoming** [comment]
@jamalex I have been working on making kalite output the correct command name, however there is an issue with the way that Django outputs the command name. Notice the last line conflicts with the first one.

    Usage: kalitectl.py subcommand [options] [args]

    Options:
      -v VERBOSITY, --verbosity=VERBOSITY
                            Verbosity level; 0=minimal output, 1=normal output,
                            2=verbose output, 3=very verbose output
      --settings=SETTINGS   The Python path to a settings module, e.g.
                            "myproject.settings.main". If this isn't provided, the
                            DJANGO_SETTINGS_MODULE environment variable will be
                            used.
      --pythonpath=PYTHONPATH
                            A directory to add to the Python path, e.g.
                            "/home/djangoprojects/myproject".
      --traceback           Print traceback on exception
      --auto-pdb            Break into PDB on an uncaught exception
      --version             show program's version number and exit
      -h, --help            show this help message and exit

    Type 'kalite manage help <subcommand>' for help on a specific subcommand.

I don't remember precisely, but I think the command name in the first line was hard coded and impossible to fix.... but should be investigated further.

**Comment by benjaoming** [comment]
Here is the patch that will fix our Django to output the `prog_name` in the first line.

    --- a/python-packages/django/core/management/__init__.py
    +++ b/python-packages/django/core/management/__init__.py
    @@ -357,7 +357,8 @@ class ManagementUtility(object):
             # must be processed early.
             parser = LaxOptionParser(usage="%prog subcommand [options] [args]",
                                      version=get_version(),
    -                                 option_list=BaseCommand.option_list)
    +                                 option_list=BaseCommand.option_list,
    +                                 prog=self.prog_name)
             self.autocomplete()
             try:
                 options, args = parser.parse_args(self.argv)

**Comment by benjaoming** [comment]
Seems Django 1.8dev has a different way of doing this, but still not respecting the prog_name:

https://github.com/django/django/blob/master/django/core/management/__init__.py#L278

**Comment by aronasorman** [comment]
Running `kalite manage help` does show the list of commands you can run:
```
~/src/github.com/aronasorman/ka-lite $ kalite manage help
Usage: kalitectl.py subcommand [options] [args]

Options:
  -v VERBOSITY, --verbosity=VERBOSITY
                        Verbosity level; 0=minimal output, 1=normal output, 2=verbose output, 3=very verbose output
  --settings=SETTINGS   The Python path to a settings module, e.g. "myproject.settings.main". If this isn't provided, the DJANGO_SETTINGS_MODULE environment variable will be used.
  --pythonpath=PYTHONPATH
                        A directory to add to the Python path, e.g. "/home/djangoprojects/myproject".
  --traceback           Print traceback on exception
  --auto-pdb            Break into PDB on an uncaught exception
  --version             show program's version number and exit
  -h, --help            show this help message and exit

Type 'kalite manage help <subcommand>' for help on a specific subcommand.

Available subcommands:

[ab_testing]
    read_facility_conditions

[auth]
    changepassword
    createsuperuser

[build]
    generate_blacklist

[caching]
    cache

[chronograph]
    cron
    cron_clean
    cronserver
....
[118333 refs]
[22830 refs]
~/src/github.com/aronasorman/ka-lite $ 
```

It's still printing out `kalitectl.py` as the command though. I think that should go in another issue.
