### ISSUE TITLE
Items wrapped in _() in python code do not seem to appear in translation

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#2964]
Branch: 'develop'
Expected Behavior: All text used that can be translated should be brought into translation files to upload to CrowdIn.
Current Behavior: Text that is wrapped in this way in .py files does not seem to appear on CrowdIn.
Steps to reproduce: load CrowdIn and search for any string in the codebase that has been wrapped in _().

e.g.: "This content was not found! You must login as an admin/coach to download the content."

![image](https://cloud.githubusercontent.com/assets/1680573/6116914/5ebe6fe0-b065-11e4-87a5-9a633de39372.png)

**Comment by cpauya** [comment]
Hi @rtibbles I searched: "This content was not found! You must login as an admin/coach to download the content." and found one result  --> https://crowdin.com/translate/ka-lite/28877/en-fr

**Comment by rtibbles** [comment]
Cool! Non-issue then.
