### ISSUE TITLE
Show hint button changes color when incorrect answer entered

### ISSUE THREAD

**Issue by Antrikshy** [learningequality/ka-lite#2966]
Before:
![screen shot 2015-02-09 at 2 13 14 pm](https://cloud.githubusercontent.com/assets/6601788/6116974/d462eadc-b065-11e4-9250-4301be915784.png)

After wrong answer:
![screen shot 2015-02-09 at 2 13 22 pm](https://cloud.githubusercontent.com/assets/6601788/6116978/d9f4a5da-b065-11e4-8d3a-0f79f6fcf410.png)

**Comment by rtibbles** [comment]
I believe this is intentional to give the user a hint to take the hint, so to speak.

**Comment by Antrikshy** [comment]
Hmm. When I was fixing some of the buttons, I reserved the orange ones for the "help" features (scratchpad, hint, keypad). IMO Check Answer should always be green. Here, the color is just swapping. And it's not very obvious when it happens either.

**Comment by rtibbles** [comment]
I believe this is happening internally to the Khan Academy code for the exercises.

**Comment by aronasorman** [comment]
Doesn't the "Check Answer" button shake when you have an incorrect answer? That should draw attention to that side of the screen, and hopefully to the new colors?

**Comment by rtibbles** [comment]
Won't fix.
