### ISSUE TITLE
The bottom level of the topic sidebar fades too much when the sidebar is fully extended

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#2967]
Branch: develop
Expected Behavior: Sidebar text at the lowest level should be de-emphasized but still very legible.
Current Behavior: Text is so greyed out it, it is a little hard to read.
Steps to reproduce: Navigate through topic tree to bottom level
Screenshot(s): 
![image](https://cloud.githubusercontent.com/assets/1680573/6116986/e6c9cb96-b065-11e4-9ff9-9f8eb073c1b7.png)

**Comment by Antrikshy** [comment]
Better?

![screen shot 2015-02-13 at 11 01 23 am](https://cloud.githubusercontent.com/assets/6601788/6193395/b6c2d5f2-b36f-11e4-8afe-bfad1d7bea2f.png)

Or how about we get rid of it completely?

![screen shot 2015-02-13 at 10 59 55 am](https://cloud.githubusercontent.com/assets/6601788/6193368/8233c86e-b36f-11e4-9605-5cf6720d9479.png)

Doesn't look bad.

I'm playing around with it but there isn't much wiggle room based on the algorithm we're using to calculate the opacity. It's either really transparent or barely noticeable.

**Comment by MCGallaspy** [comment]
@Antrikshy have you opened a PR for this? No fading seems fine to me, though I am relatively un-opinionated about it.

**Comment by Antrikshy** [comment]
I think it does too. Kind of forgot about it. It's an way change. I'll open a PR soon.

**Comment by Antrikshy** [comment]
Removed (commented out for now) about 5 lines and sidebar no longer fades (second screenshot above). I like the clean look of white text.

#3081
