### ISSUE TITLE
Successfully adding a coach takes you to the "Add a new coach" form

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#2970]
On `develop`, adding a new coach takes you back to the same "Add a new coach" form. Now this is up for debate, but shouldn't successfully submitting that form redirect one back to the associated facility page?

To reproduce, log in as an administrator, click on the Manage tab, choose a facility, click "Add a new coach" link at the bottom of the list of coaches, create a new coach, and then get redirected back to the same form.

**Comment by aronasorman** [comment]
I personally believe in retaining the current behavior -- this is the closest we have to bulk-adding coach accounts. Breaking that by having them click the "signup" button again would be bad UX.

**Comment by rtibbles** [comment]
It is inconsistent with both the Group and Student adding behaviour on the same page though.
