### ISSUE TITLE
Copyright notices in footer need to be updated

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#2971]
Observed:
![image](https://cloud.githubusercontent.com/assets/618416/6117002/1be74f06-b066-11e4-8e7f-3c536bd37d3a.png)

Expected:
Khan Academy's Perseus exercises are no longer CC-licensed, so we need to divide up the copyright section to indicate that while the videos are, the exercises are not.

We should also display license information on the video/exercise pages themselves.

**Comment by aronasorman** [comment]
Fixed in commit ^

**Comment by jamalex** [comment]
Err... really?

**Comment by MCGallaspy** [comment]
@jamalex So something like:
```
KA Lite version 0.13.0 © 2014
Videos © 2015 Khan Academy  (Creative Commons icon)
Exercises © 2015 Khan Academy
```
?

**Comment by jamalex** [comment]
It's a bit complicated now, since some exercises (khan-exercises) I believe are still CC? And Perseus exercises are not (yet/currently?) CC. But yeah, perhaps for now it can just be:

```
KA Lite version 0.13.0 © 2015 Foundation for Learning Equality
[Learning Equality Logo]
Videos © 2015 Khan Academy  (Creative Commons icon)
Exercises © 2015 Khan Academy
```

**Comment by rtibbles** [comment]
Closing this issue, outstanding element in new issue.
