### ISSUE TITLE
Sidebar tab expands and contracts at a different speed than the sidebar

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#2973]
Expected:
Sidebar tab should stay connected with the sidebar pane when expanding/contracting.

Observed:
![image](https://cloud.githubusercontent.com/assets/618416/6117146/775cd0e4-b067-11e4-931a-938524b17b15.png)
(tab lags behind the sidebar, due to CSS3 transition delays)

**Comment by Antrikshy** [comment]
It would be nice if we could animate the sidebar opening too. The transition for the tab was put in to make it slide out on hover.

**Comment by jamalex** [comment]
It used to slide out, but it made the load time intolerable on the cheap tablets (several seconds, and at such a low framerate that it only rendered one or two frames in the process of expanding anyway), so we would need to have this selectively turned on for certain browsers (or find a faster approach).

**Comment by djallado** [comment]
Hi!

I can't replicate this with **Genymotion emulator**, setting the **Base Memory** to 256. 
I use Genymotion emulator coz I don't have any. 
Ref: https://www.genymotion.com/#!/

What specs of tablet or computer we could replicate this?

**Comment by Antrikshy** [comment]
Looks like CSS animations were removed due to performance issues (in #3126), so this can be closed.
