### ISSUE TITLE
Video downloading invalidates content and topic tree caches at the end of every download

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#2976]
Branch: develop
Expected Behavior: hold off on invalidating content and topic_tree cache until all downloads have finished
Current Behavior: invalidates the content and topic_tree caches after every video completes
Steps to reproduce: install several language packs, download more than one video. Watch your Debug output go crazy as it continually invalidates all the languages
Screenshot(s):

![image](https://cloud.githubusercontent.com/assets/1680573/6117275/1e307eb6-b068-11e4-9ec6-c818ace591f0.png)

**Comment by rtibbles** [comment]
Fixed in #3043.

**Comment by rtibbles** [comment]
Just found this again today on develop...

**Comment by MCGallaspy** [comment]
Caches only invalidated after a whole batch has finished, not after each video.
