### ISSUE TITLE
Clicking "Show hints (1 available)" button doesn't show me a hint

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#2977]
On `develop` branch, not logged in, I navigated to `/learn/khan/math/early-math/cc-early-math-geometry-topic/cc-early-math-composing-shapes/compose-shapes/`. I immediately gave up as the exercise was far beyond me, and clicked on the "I'd like a hint" button. I expected some kind of hint, but nothing happened. After answering incorrectly, I clicked on the "Show hints (1 available)" button that replaced the "I'd like a hint" button, but again I received no hints. Please help.

**Comment by jamalex** [comment]
Yeah, that's a hard one.....

**Comment by jesumer** [comment]
Hi,

I'll try fixing this issue.

**Comment by djallado** [comment]
@jesumer.

I'll try to help you on this.

**Comment by jesumer** [comment]
@djallado,

Yes thanks.

**Comment by djallado** [comment]
Hi. my observation in this is:

1. If `"uses_assessment_items": false` 
    Hints will display if we click on it.
1. If `"uses_assessment_items": true` it return another `api: /api/assessment_item/id`, and if we click on hints nothing will happened.

**Comment by MCGallaspy** [comment]
@rtibbles could it be an issue with the API endpoint? I'll take a closer look.

**Comment by jamalex** [comment]
Fixed in #3068.
