### ISSUE TITLE
"This content was not found!" message only displayed after navigation to new page

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#2978]
Context: We still allow people to navigate to content that hasn't been downloaded, but then intend to inform them of that fact.

Expected: This message should appear when the content is opened.

Observed: No message is displayed (and the video player is still displayed) even when the content hasn't been downloaded:

![image](https://cloud.githubusercontent.com/assets/618416/6117390/0231cdcc-b069-11e4-8f59-4c787dc38506.png)

However, the message does then get displayed (seems it was buffered but never loaded) upon navigation to another page:

![image](https://cloud.githubusercontent.com/assets/618416/6117302/537e1e84-b068-11e4-867a-c4bfcc927e92.png)

**Comment by rtibbles** [comment]
Fixed in #3053.
