### ISSUE TITLE
Answer box highlighting is missing left border

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#2980]
Again on `develop`, again at `/learn/khan/math/early-math/cc-early-math-geometry-topic/cc-early-math-composing-shapes/compose-shapes/`, I clicked the check answer button without first clicking any of the radio buttons for the answer. It helpfully highlighted the answer area by creating a border, but the left side of the border was cut off. Screenshot included:

![ss](https://cloud.githubusercontent.com/assets/8888020/6117397/1b849b74-b069-11e4-9223-0f91b57748fe.png)

**Comment by rtibbles** [comment]
Fixed in #3173
