### ISSUE TITLE
"Could not connect to the server." ... proceeds to download videos just fine

### ISSUE THREAD

**Issue by Antrikshy** [learningequality/ka-lite#2983]
This red warning panel seems to show up every time I go to the video download page. But the downloads work just fine.

![screen shot 2015-02-09 at 2 44 20 pm](https://cloud.githubusercontent.com/assets/6601788/6117563/463a8422-b06a-11e4-920f-72b4a97a26ce.png)

**Comment by jesumer** [comment]
Hi, 

I can also replicate the error. It looks like that the server request was timeout and that's why it will pop up an error.  I've set my local settings and here is the error when the central doesn't running.

**Comment by jesumer** [comment]
@Antrikshy . I think this is a normal behavior of the site in a sense of having connection issue but I don't see an any issue on this. 
To reproduce this just point your local_settings to a local central server, then try not to run the central and notice the error will come out. So I conclude this was a inconsistent connection issue. Please correct me if I'm wrong. Thanks

**Comment by MCGallaspy** [comment]
Can't reproduce. Seems to have been a legitimate connection issue. Let me know if it happens again @Antrikshy.
