### ISSUE TITLE
Inconsistent placement of "No learner accounts in this group have been created." message

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#2984]
Expected: The coach reports have been unified, with switching between them done via a single dropdown. The experience should be as consistent across them as possible.

Observed:

On the tabular coach reports, empty groups are indicated in the lower area of the report:
![image](https://cloud.githubusercontent.com/assets/618416/6117550/2bdeda10-b06a-11e4-80f1-34be2a7a2387.png)

On the other reports, however, this message is displayed as a bubble error message, above everything:
![image](https://cloud.githubusercontent.com/assets/618416/6117565/49d55d8c-b06a-11e4-82d4-384958ed73d8.png)

**Comment by rtibbles** [comment]
Fixed in #3036
