### ISSUE TITLE
Device registration warning even after registering

### ISSUE THREAD

**Issue by Antrikshy** [learningequality/ka-lite#2986]
![screen shot 2015-02-09 at 2 46 08 pm](https://cloud.githubusercontent.com/assets/6601788/6117607/7e5332e6-b06a-11e4-9f32-5fc7220e3486.png)

This shows up (when logged in as admin of course) even when the device has been registered.

**Comment by cpauya** [comment]
This may be related to #3002?

**Comment by jamalex** [comment]
Yes, I think so.

**Comment by jesumer** [comment]
Yeah. I agree

**Comment by aronasorman** [comment]
Yup, possibly.

**Comment by jesumer** [comment]
I tried to reproduce this issue by changing the host in my local_settings to http://staging.learningequality.org and my loacl central server. I don't see any issue here except the button
![screen shot 2015-02-13 at 10 43 04 am](https://cloud.githubusercontent.com/assets/2810009/6181358/c872021c-b36c-11e4-950a-60a0714693e2.png)
and I did not see this warning message as what of @Antrikshy screenshot.

**Comment by jesumer** [comment]
THe button whis is assigned to @arceduardvincent  issue https://github.com/learningequality/ka-lite/issues/3002

**Comment by jesumer** [comment]
Hello @Antrikshy,

What did you do to reproduce this issue or where can we find this? as of what is in your screenshot

**Comment by Antrikshy** [comment]
When I got this error, I was logged in as admin, had registered KA Lite using whatever that one-click registration method is. And obviously, I was on the Teach tab. This was a fresh instance of the 0.13.x bug bash version.

**Comment by jesumer** [comment]
I did the same but I don't get the error.
Here's my screenshot from registration up to the teach page:
![screen shot 2015-02-13 at 12 53 32 pm](https://cloud.githubusercontent.com/assets/2810009/6182624/ad5ffc52-b382-11e4-9303-661dc929bebd.png)

![screen shot 2015-02-13 at 1 18 22 pm](https://cloud.githubusercontent.com/assets/2810009/6182627/b69cd060-b382-11e4-9b0d-4e76bf7bcca2.png)

![screen shot 2015-02-13 at 1 18 32 pm](https://cloud.githubusercontent.com/assets/2810009/6182632/ee3737f4-b382-11e4-846e-ebb8465b9abd.png)

![screen shot 2015-02-13 at 1 18 45 pm](https://cloud.githubusercontent.com/assets/2810009/6182634/02d5777a-b383-11e4-9e39-6b2aac21dcec.png)

**Comment by Antrikshy** [comment]
Interesting. Maybe it was just something on my end. I was getting a connection error too (#2983). Perhaps we should close this.

**Comment by jesumer** [comment]
Can you attached what are your screenshots on this?

**Comment by Antrikshy** [comment]
Pardon?

**Comment by MCGallaspy** [comment]
Again unable to reproduce. Let me know if you experience this again @Antrikshy. Otherwise I'm chalking this up as a legitimate warning.
