### ISSUE TITLE
Inconsistent behaviour of dropdown item selection on coach report pages

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#2987]
Expected: Unified, consistent experience.

Observed:

The top dropdowns require a button press in order to have an effect:
![image](https://cloud.githubusercontent.com/assets/618416/6117638/cdde8b4e-b06a-11e4-8c0a-4dd4b5f03d6e.png)

Whereas the bottom dropdowns trigger a reload immediately upon item selection:
![image](https://cloud.githubusercontent.com/assets/618416/6117658/f4f84170-b06a-11e4-9454-44c57cc3c8f8.png)

Recommended:
Have all dropdowns require a button before having an effect. Side effects of selecting items (especially when those side-effects may be expensive/slow) isn't ideal.

**Comment by jesumer** [comment]
Hi, 

I have already fixed this issue.
I've added a button that refreshing the browser according to to the selected item. Heres the screenshot
![screen shot 2015-02-11 at 2 57 35 pm](https://cloud.githubusercontent.com/assets/2810009/6143138/05eaf5f6-b1fe-11e4-8c9b-87feb38fa4e0.png)
