### ISSUE TITLE
Axes on scatter plot coach report are unlabeled and of arbitrary scales

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#2988]
Branch: develop
Expected Behavior: Axes on graph should be labelled to indicate what is being measured, and scales should be meaningful
Current Behavior: Axes are unlabelled, and have seemingly arbitrary maximum/minimum values
Steps to reproduce: Run 'generaterealdata' management command. Go to coach reports, scatter plot.
Screenshot(s):

![image](https://cloud.githubusercontent.com/assets/1680573/6117657/f44d1ab6-b06a-11e4-9c2f-ca9d56f4c3ef.png)

**Comment by djallado** [comment]
@rtibbles.
I defer this issue for now coz I have some issues to work on. 
I apologise for not having a progress in this.

**Comment by rtibbles** [comment]
This no longer exists on 0.14
