### ISSUE TITLE
KA-Lite MAC Installer error

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite#2991]
The current MAC Installer provides no documentation for the user upon ignoring security warnings the installer will provide a dialog for some settings crucial to those is automatically starting and stopping the server and automatically downloading resources after starting the server. Neither preferences are adjustable via the dialog during the installation.

![2015-02-09_15-41-12](https://cloud.githubusercontent.com/assets/4349806/6117577/b73c6ea8-b072-11e4-95c1-e41ad02fbdb1.png)

Choosing the Advanced Tab then setup runs something but eventually stops with no feedback. Then clicking apply runs something eventually closing the dialog. Found afterwards in the menubar is the kalite icon which allows starting the server but errors: 

![2015-02-09_15-58-15](https://cloud.githubusercontent.com/assets/4349806/6117800/9e641b86-b074-11e4-8d67-66b083d6fa1a.png)

Opening Console provides the following errors toward the bottom of the log:

![2015-02-09_16-00-53](https://cloud.githubusercontent.com/assets/4349806/6117860/0b00adcc-b075-11e4-80e8-b33077d9a534.png)

Branch: develop
Expected Behavior: Expected documentation but interfacing with dialog results in error after installation.
Current Behavior: The server does not start.
Steps to reproduce:

Steps to reproduce:
1. Rightclick open KA-Lite Monitor as user 
2. Attempt to install application

**Comment by aronasorman** [comment]
User warnings? About insecure software @EdDixon?

**Comment by cpauya** [comment]
@EdDixon Thanks for the report!  Looking into it already.

Tip: You can filter your console with "KA-Lite" so it only shows the installer/ka-lite app logs. :smiley_cat:

**Comment by EdDixon** [comment]
@Aron same certificate issue we have been dealing with I think, the KA-Lite Monitor has to be run for installation with admin right (right click open) in order to allow the user access to the application because it is from an unknown source. Subsequent runs after installation run fine with out the elevated privilege.

**Comment by EdDixon** [comment]
Also restarting the KA-Lite Monitor application after the failed installation attempt ran fine and testing on that system is now ongoing.

**Comment by EdDixon** [comment]
Important note here regarding this current MAC installer. It will create the KA-Lite Monitor.app in the Applications directory instead of a KA-Lite folder as in previous versions which breaks pathing to kalite command for example. Current work around is pull from GIT and run setup_unix.sh to revert back to the KA-Lite typical installation as a folder in the Applications menu which I am doing know to continue testing of kalite command and new exercise features.

**Comment by aronasorman** [comment]
the `KA Lite Monitor`, under the hood, is just a simple folder @EdDixon. You can `cd` to it and then run `bin/kalite` from there.

**Comment by EdDixon** [comment]
All I am seeing in that folder is contents?
![2015-02-10_12-45-58](https://cloud.githubusercontent.com/assets/4349806/6135086/e937eb70-b122-11e4-8e2a-a07d31ec56cf.png)

**Comment by aronasorman** [comment]
Sorry. You have to go inside Contents/Resources to find the kalite folder.

**Comment by EdDixon** [comment]
once in the proper path I was only able to invoke the kalite command by using "sh kalite" with the following output; 
![2015-02-10_13-02-08](https://cloud.githubusercontent.com/assets/4349806/6135402/8af71c86-b125-11e4-9722-915575a16e2b.png)

**Comment by aronasorman** [comment]
We fixed this on the dev room. @EdDixon is now testing it.

**Comment by EdDixon** [comment]
FIxed in 13.x requires the user to navigate in shell to the installation folder where bin/kalite but now works from there as designed. Closing...
