### ISSUE TITLE
Exercises incorrectly claiming mastery achieved

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#2992]
Branch: develop
Expected Behavior: Only declare 'you have mastered this exercise' when 8 out of the last ten questions are correct
Current Behavior: Students are told they have mastered an exercise after getting a question incorrect, but then correcting themselves
Steps to reproduce: Navigate to 'Count from any number' exercise. Answer it incorrectly. Then answer it correctly. It will tell you you have mastered the exercise.
Screenshot(s): 

![image](https://cloud.githubusercontent.com/assets/1680573/6117890/f63b7546-b06c-11e4-98fd-0ee6962d2a0f.png)

**Comment by jamalex** [comment]
Looks fine to me.

**Comment by rtibbles** [comment]
I can no longer replicate this. Closing for now.
