### ISSUE TITLE
Some assessment items missing, no graceful failure.

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#2994]
Branch: develop
Expected Behavior: A perseus exercise should always render a proper assessment item
Current Behavior: Some assessment items appear to be missing still, and our wrapper does not allow for graceful failure when this does happen
Steps to reproduce: Navigate to exercise 'One more, one less'. Answer questions correctly until 404 error appears.
Screenshot(s):

![image](https://cloud.githubusercontent.com/assets/1680573/6117948/8bcb6f1c-b06d-11e4-92ca-be642ab8a1ba.png)

**Comment by jamalex** [comment]
Duplicate of #2998.

**Comment by jamalex** [comment]
Copying in my notes from #2998 here, in case useful.

![image](https://cloud.githubusercontent.com/assets/618416/6118016/2f6230ac-b06e-11e4-988c-db0b7b6fd20f.png)

Possible solutions:
- Filter through the topic tree prior to release and remove any references to assessment items we don't have data for
- Gracefully skip over any assessment items that return 404's; the user doesn't care.

**Comment by rtibbles** [comment]
Fixed in #3046.
