### ISSUE TITLE
Learn tab not active when it should be

### ISSUE THREAD

**Issue by Antrikshy** [learningequality/ka-lite#2995]
![screen shot 2015-02-09 at 3 08 17 pm](https://cloud.githubusercontent.com/assets/6601788/6117946/8b434560-b06d-11e4-8ad0-c4b7cd853e66.png)

I find myself clicking it multiple times before realizing I'm already there and need to click the "Learn!" box. It's active in the actual "Learn!" area though.

**Comment by MCGallaspy** [comment]
@Antrikshy can you please provide more information about how to reproduce this error? Like what kind of user you're logged in as (learner/coach/admin) and what relative url you navigate to to get this error?

**Comment by MCGallaspy** [comment]
Okay, I think I figured this out. You're at the base url logged in as an admin? Can you reach this page as any other kind of user?

**Comment by MCGallaspy** [comment]
Doesn't look like it.

**Comment by Antrikshy** [comment]
Sorry I couldn't reply earlier. Been really busy this week. I got it logged in as admin. Base URL, yes.
