### ISSUE TITLE
"Acceptable formats" is no longer in bubble format and no longer accepts interaction

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#2996]
Expected: A nice "Acceptable formats" bubble in the exercise answer area, which displays answer input instructions when hovered/tapped.

Observed:
Ugly plaintext that accepts to interaction:
![image](https://cloud.githubusercontent.com/assets/618416/6117903/0bfd7d3e-b06d-11e4-8f27-9fd59200eda2.png)

**Comment by rtibbles** [comment]
I think this should now appear on mouseover in the input area.

**Comment by jamalex** [comment]
Hmm, I'm not seeing it there either, at least on http://127.0.0.1:8008/learn/khan/math/early-math/cc-early-math-measure-data-topic/cc-early-math-data/solving-problems-with-bar-graphs-1/ for example (where the input area is in the question area).

**Comment by rtibbles** [comment]
Hrm, this might have disappeared during the 'solutionarea' hacks.

**Comment by rtibbles** [comment]
Turns out this was a result of Khan Academy completely changing the way they do this.

**Comment by rtibbles** [comment]
Fixed, as MVP in #3046.
