### ISSUE TITLE
Missing assessment items should be handled more gracefully

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#2998]
Background: Exercises do lookups for assessment item data. Usually this data is found, as long as they've loaded the assessment item data/content pack.

Observed: We're still missing some assessment items, it seems, and when the exercise interface requests one of these and gets a 404, it explodes, and the user is stuck:

![image](https://cloud.githubusercontent.com/assets/618416/6118016/2f6230ac-b06e-11e4-988c-db0b7b6fd20f.png)

Possible solutions:
- Filter through the topic tree prior to release and remove any references to assessment items we don't have data for
- Gracefully skip over any assessment items that return 404's; the user doesn't care.

**Comment by rtibbles** [comment]
Duplicate of #2994

**Comment by jamalex** [comment]
Deduplicated!
