### ISSUE TITLE
"Content was not found" message on Manage tab

### ISSUE THREAD

**Issue by Antrikshy** [learningequality/ka-lite#2999]
Should this show up here? (The yellow panel at the top)

![screen shot 2015-02-09 at 3 19 30 pm](https://cloud.githubusercontent.com/assets/6601788/6118121/3592dc82-b06f-11e4-87c9-ba1f676bd986.png)

Never shows up on missing video pages for me.

**Comment by jamalex** [comment]
Duplicate of #2978.
