### ISSUE TITLE
Useless FAQ link on videos update UI

### ISSUE THREAD

**Issue by Antrikshy** [learningequality/ka-lite#3001]
1. Go to `/update/videos` as admin. 
2. See link "Q: How do I bulk-download videos?" under "Help for downloading videos".
3. Click it.
4. Notice that there is no such question on that page (as far as I can see).
5. ?????
6. PROFIT

**Comment by cpauya** [comment]
Let's add something like "Q: How do I bulk-download videos or download videos via Torrent?".  

I think that'll make sense than the original text.

**Comment by Antrikshy** [comment]
Or simply "Frequently Asked Questions"...

**Comment by jesumer** [comment]
Hi @aronasorman ,

Please close this issue. This issue has a PR that was merged and closed by @MCGallaspy.
