### ISSUE TITLE
Messages never go away when navigating through content in the sidebar

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3004]
Context: Navigating through content in the sidebar happens entirely in the client-side, with no page reloads.

Expected behaviour: Navigating to a new content item should clear and no longer display messages that came from interactions with other content items, or from initially logging in, e.g.:
![image](https://cloud.githubusercontent.com/assets/618416/6118514/296e5950-b073-11e4-8695-5d57054d061b.png)

Possible solution: Clear all messages prior to loading a new content item.

**Comment by rtibbles** [comment]
Fixed in #3056
