### ISSUE TITLE
No points are being earned for exercises

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3005]
Expected: Points earned for exercises

Observed: No points earned for exercises

Steps to replicate: Do exercise. No points.

**Comment by djallado** [comment]
I tried to replicate this and looks like `get_points_per_question()` is missing.

**Comment by MCGallaspy** [comment]
@djallado can you give a more detailed explanation?

**Comment by djallado** [comment]
When I tried to verify the issue, I din't found it. for now that function is in `exercise/views.js`. I see the `calculate_points_per_question` and look lite it always return a `0` value.

**Comment by jamalex** [comment]
`get_points_per_question` uses the exercise's `basepoints` in its calculation, which is derived from `seconds_per_fast_problem`, which appears to be 0 for Perseus exercises. We'll need to assume a default value for Perseus exercises (or any where `seconds_per_fast_problem` is 0).

**Comment by jamalex** [comment]
Or maybe it's time to just shift to a fixed number of points per question, across exercises. @rtibbles?

**Comment by rtibbles** [comment]
These are the only exercises I see that either have 'second_per_fast_problem' set to 0 or have the key missing:
Standard deviation of a population
Constructing a line tangent to a circle
Components of vectors
Exploring the foci of an ellipse
Comparing fractions with the same numerator
Comparing fractions with the same denominator

So I don't see that this would be causing the issue, @jamalex.

**Comment by rtibbles** [comment]
Fixed in #3046.
