### ISSUE TITLE
Viewing one (or all) of the hints for an exercise doesn't mark it as incorrect

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#3006]
On `develop`, at `/learn/khan/math/pre-algebra/fractions-pre-alg/equivalent-fractions-pre-alg/equivalent_fractions/` (but probably some other exercises as well), my progress for the exercise increases no matter how many hints I take.

**Comment by MCGallaspy** [comment]
I wonder if this is related to #2977?

**Comment by rtibbles** [comment]
Fixed in #3069.
