### ISSUE TITLE
KA-LIte on Ubuntu 14.04 failed to start.  Saved by Forum tip. Removed write protection.

### ISSUE THREAD

**Issue by edresor** [learningequality/ka-lite#3007]
When I ran the start script and an error came up that the the program could not create a "read only" database and then the server failed to start.  The start script does not accept sudo. I rebooted and tried several other things.  Nothing worked.

Then this dangerous tip in the forum written apparently for a larger issue saved me.
___
I think I got it. I had to make the installation directory writable on my ubuntu server as this
$: sudo chmod -R 777 khanAcademy/ka-lite
Otherwise nothing was orignally installed and the question of password was really not applicable without installation.
-------------

**Comment by MCGallaspy** [comment]
@edresor thanks for opening an issue, are you able to reproduce this error? And if so, can you describe how?

**Comment by aronasorman** [comment]
Hi @edresor, In the latest develop branch the recommended installation procedure would be the .deb package, or barring that, `python setup.py install`, which makes sure you have the right permissions when creating the DB.

Closing as fixed.
