### ISSUE TITLE
password validation align on top.

### ISSUE THREAD

**Issue by amodia** [learningequality/ka-lite#3008]
Branch: `develop`
Expected Behavior: password validation should align at the bottom to the password field..

Steps to reproduce: 
1. Create coach user on default facility and make password field validate.

![screen shot 2015-02-10 at 10 17 24 am](https://cloud.githubusercontent.com/assets/8663934/6120274/b216a758-b10e-11e4-9931-0a8b2fcc2666.png)

**Comment by Antrikshy** [comment]
I have been planning on redesigning the entire login/register pages to make them more Bootstrap-py and less login-form-from-2004. I might fix this if it hasn't been already.

**Comment by amodia** [comment]
@MCGallaspy This issue is already solved on [#3495](https://github.com/learningequality/ka-lite/pull/3495) I think you can close this.
