### ISSUE TITLE
Points are getting deducted for the students while doing exercises.

### ISSUE THREAD

**Issue by anuragkanungo** [learningequality/ka-lite#3013]
This is happening in KCT 4S, 4T .

**Comment by anuragkanungo** [comment]
Points are not being deducted , its just the display error. Wrong points are displayed.

**Comment by benjaoming** [comment]
@radinamatic will try to recreate this for our current 0.17 development, but most likely we need more data to recreate it.

**Comment by radinamatic** [comment]
Not having luck finding `KCT 4S, 4T` in the current KA Lite content. @anuragkanungo could you provide more details about the exercise? Which version/installer gives this error?

**Comment by radinamatic** [comment]
Thanks to info by @jamalex we can close this now!
