### ISSUE TITLE
SMPS 4B Exam Results not viewable

### ISSUE THREAD

**Issue by anuragkanungo** [learningequality/ka-lite#3014]
![screenshot from 2015-02-11 00 36 02](https://cloud.githubusercontent.com/assets/4207886/6134264/040bf05a-b186-11e4-94b0-319846973cf2.png)

**Comment by aronasorman** [comment]
what branch is this @anuragkanungo? Is this the one with the new playlists?

**Comment by anuragkanungo** [comment]
No, its separate branch.

**Comment by aronasorman** [comment]
resolution: we undelete the `407.json` file.

**Comment by anuragkanungo** [comment]
Fixed in #3016
