### ISSUE TITLE
Incorrect package prefix for middleware + more?

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#3019]
I found that I have to add `ka-lite/kalite/` to the system path to run ka-lite with mod_wsgi. This is because certain import statements are not executed from the same relative path as when running the server with a django management command.

Example in `kalite.distributed.settings`:

    MIDDLEWARE_CLASSES = (
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.common.CommonMiddleware",  # a bunch of shortcuts used by distributed
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        __package__ + ".middleware.LockdownCheck",
        "student_testing.middleware.ExamModeCheck",
    )

Here, `student_testing...` should have been `kalite.student_testing`.

Not sure how many other cases of wrong path prefixing we can come up with, but I hereby dedicate this issue to that purpose :)

**Comment by aronasorman** [comment]
And I hereby assign you to this issue :)

**Comment by benjaoming** [comment]
Fixed in #3809
