### ISSUE TITLE
Coach manage page: user tab is not aligned properly

### ISSUE THREAD

**Issue by tk21** [learningequality/ka-lite#3049]
Branch: develop
Expected behavior: User tab needs to be lined up with the rest of the tabs when logged in as coach.
Current behavior: User tab is positioned lower than the other tabs, oddly aligned....

![usertab](http://i58.tinypic.com/5dw8co.png)

**Comment by MCGallaspy** [comment]
Still extant in `develop`.

**Comment by rtibbles** [comment]
Fixed in #3071
