### ISSUE TITLE
Coach reports: Report type and date range selections operate independently

### ISSUE THREAD

**Issue by tk21** [learningequality/ka-lite#3051]
Branch: develop
Expected behavior: When moving from scatter report to timeline report or vice versa, the date range that is selected should be sent as inputs to generate the report.
Current behavior: After selecting the report type and pressing "Go", the starting-time and ending-time are defaulted back to 2015-1-13 and Ending time: <current date>, and the previous date selections before pressing "Go" are not used as the ranges. 

You have to select Report Type FIRST, press "GO", and THEN select the dates... but you can't select the dates and report type THEN press "GO" to produce the report. 

Not really a bug, but just something that may be confusing or inconvenient for users.

How to reproduce:
1. Go to coach reports
2. Select either scatter or timeline report type. 
3. Press go.
4. From that page, select the other report type from the drop down menu. 
5. Change the dates to some arbitrary range.
6. Hit go
7. See the dates get defaulted back to some default values... and not the values you inputted :( 

:disappointed_relieved:

**Comment by aronasorman** [comment]
We have rewritten the coachreports. Please open a new issue if it's still extant on the latest develop.
