### ISSUE TITLE
Page title of login page is wrong.

### ISSUE THREAD

**Issue by cpauya** [learningequality/ka-lite#3057]
Branch **develop**

Issue: When the `Login` navigation link is clicked, the page title becomes "Log inWelcome | KA Lite".

![screenshot 2015-02-17 14 08 21](https://cloud.githubusercontent.com/assets/175580/6223957/754ba378-b6ae-11e4-9655-1c6778aa6be6.png)

**Comment by MCGallaspy** [comment]
Seems like an issue of the child template not properly overriding the base template's title block.

**Comment by cpauya** [comment]
And looks like it affects other pages too:

Here's the 404 page with `DEBUG = False`
![screenshot 2015-02-18 15 02 43](https://cloud.githubusercontent.com/assets/175580/6243588/6fe75068-b77f-11e4-96c4-f789262867d4.png)

Here's the title on the `Manage -> Facilities` tab
![ka-lite-2015-02-18a](https://cloud.githubusercontent.com/assets/175580/6243661/6e7b407a-b781-11e4-885b-a4ea32fef761.png)

Will go attempt to fix some templates I find this issue.
