### ISSUE TITLE
Display license information on the content/exercise pages themselves

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#3065]
Last part of https://github.com/learningequality/ka-lite/issues/2971

We should display individual license information for all content and exercises if available.

We should also include icons for all CC licenses in order to show the range of different licenses.

**Comment by MCGallaspy** [comment]
Okay, how should it be displayed? For exercises & assessment items, is the license included in the exercise/assessment item data, or does it inherit the KA license? Same for other content items (like videos), is the license given or implied?

Where shall it be displayed? In the content area, near the bottom or top of that container?

**Comment by rtibbles** [comment]
Not going to happen within the scope of KA Lite.
