### ISSUE TITLE
Tooltip on accepted answer formats can go off bottom of screen

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3067]
This is on:
http://127.0.0.1:8008/learn/khan/math/algebra/solving-linear-equations-and-inequalities/super-yoga/equations-in-one-variable-1/

![image](https://cloud.githubusercontent.com/assets/618416/6279126/4726214e-b852-11e4-83e0-c4d8309fbc9a.png)

(note how the footer doesn't expand down to stay at the bottom)

We should also see how big tooltips like this display on small tablet screens.

**Comment by MCGallaspy** [comment]
Additional details? What browser are you using? I don't have an input box on this exercise (and hence can't even view a tooltip).

**Comment by MCGallaspy** [comment]
Nevermind, I just had to do enough exercises to pull that particular assessment item.

**Comment by mjptak** [comment]
As the number of Perseus items grows its probably a decent idea to pass the
code for the actual assessment item that an exercise is using.  Perhaps as
a debug one could expose the id of the assessment item (available in the
console).

**Comment by mjptak** [comment]
Though that looks like it might not be a perseus exercise.  Curious if ever
the two will mix (I think not).  In other words an exercises either does or
does not pull from the perseus generated assessment items.

**Comment by rtibbles** [comment]
Fixed in #3140
