### ISSUE TITLE
multiple tabs active at coach manage page.

### ISSUE THREAD

**Issue by amodia** [learningequality/ka-lite#3072]
Branch: `Develop`
Expected Behavior : Only one navigation tab must be active.
Steps to Reproduce:  Log in as coach and navigate to manage tab.

![screen shot 2015-02-20 at 3 56 18 pm](https://cloud.githubusercontent.com/assets/8663934/6283079/1db4bc44-b91a-11e4-8115-bb0d18eb6b08.png)

**Comment by rtibbles** [comment]
Fixed in #3076
