### ISSUE TITLE
language tabs will not display if not register device.

### ISSUE THREAD

**Issue by amodia** [learningequality/ka-lite#3073]
Branch: `Develop`
Expected behavior: language tab must not show if device is not register.
Steps to reproduce:  log in as coach and navigate at manage tab.
![screen shot 2015-02-20 at 4 21 16 pm](https://cloud.githubusercontent.com/assets/8663934/6283329/f391daa6-b91d-11e4-9f29-bcb087eb4a11.png)

**Comment by rtibbles** [comment]
This should be here, but we should be prompting people to register when they click into this window.
