### ISSUE TITLE
Running i18n-ize templates script translates css classes

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#3075]
Some css classes are defined in template blocks used, for example, to highlight an active tab. The i18n-ize script wraps these in translate tags. See [here](https://github.com/learningequality/ka-lite/blob/develop/kalite/control_panel/templates/control_panel/device_management.html#L8) for an example. Can we add some blocks (like `{% block users_active %}`) to a blacklist for the purposes of this script?

**Comment by jamalex** [comment]
Oooh, yeah, that will break things badly when using another language. Good catch!

Rather than making a blacklist in some third location, perhaps we could have a template tag or other marker right on a piece of text that should be ignored by i18n-ize.

Also, @aronasorman @cpauya, this seems like yet another good reason to have a dummy language pack containing reversed/accented strings, as that would allow us to catch things like this more easily. Could someone build such a language pack and share it for testing?

**Comment by jamalex** [comment]
Adding this to the 0.13.x milestone, since it will break nav for i18n users. MVP is just to manually remove the existing bad translate tags.

**Comment by arceduardvincent** [comment]
Hi @aronasorman and @cpauya 

I would like to work on this issue.

Objective:
>1 Include this blocks {% block users_active %} to the blacklist of `i18n-ize templates script`.
>2 Create a dummy language pack 
>3 Replicate the dummy language translation to our i18n-ize string.

Question:
Could we make the `make a dummy language pack ` another filed issue? 
Coz I think this one is not part of fixing the `i18n-ize templates script`

**Comment by cpauya** [comment]
Good idea, please file another issue to make a dummy language pack for testing.

**Comment by arceduardvincent** [comment]
Yeah, I will thanks .

**Comment by arceduardvincent** [comment]
Hi @MCGallaspy .

I will make a file that contains about the list `blocks` that we may set its value to be ignored or be run `i18n-ize templates script`.

Blacklisting Format 
```
('startag', 'endtag', True/False)
('{% block users_active %}', '{% endblock users_active %}', True)
```
Note:
There are some blocks that `i18n-ize templates script` must run on them like `{% block content %}` .

If you had some good idea please tell me so I could know so we could improve the script better. 
Thanks

**Comment by MCGallaspy** [comment]
@arceduardvincent, I think @jamalex has a better idea:
>Rather than making a blacklist in some third location, perhaps we could have a template tag or other marker right on a piece of text that should be ignored by i18n-ize.

That way it would be immediately clear to the reader what is getting picked up by the i18n-ize script and what isn't. What do you think?

**Comment by arceduardvincent** [comment]
@MCGallaspy yeah it is good idea that we place a marker since minority of the blocks are must be ignored by our `i18n-ize templates script `.

**Comment by MCGallaspy** [comment]
@arceduardvincent how's this coming along?

**Comment by arceduardvincent** [comment]
Hello @MCGallaspy sorry that I reply late and didn't comply this issue last week,
I am working on some `frontend issues` that I think that will affect a lot on the user or client experience that I prfioritize.

Today I work on this thanks.

**Comment by arceduardvincent** [comment]
I think we can close this issue since that the fixes are being merge.
