### ISSUE TITLE
Styling and naming issues when clicking on "My Progress"

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#3077]
![image](https://cloud.githubusercontent.com/assets/1680573/6307354/e13d63ee-b8ef-11e4-9c7f-afce79db544f.png)

**Comment by MCGallaspy** [comment]
I may have merged too soon. See:
![ss](https://cloud.githubusercontent.com/assets/8888020/6310126/83ed4ccc-b908-11e4-94b8-8fd3d0092e8a.png)

**Comment by rtibbles** [comment]
Hrm. I reduced the font size to try to prevent this. Will double check on how to de-overlap this text.

**Comment by rtibbles** [comment]
Better? 
![image](https://cloud.githubusercontent.com/assets/1680573/6310756/c9d109b2-b90e-11e4-8d2c-2a6983f141d5.png)

**Comment by MCGallaspy** [comment]
I can live with it. Can we get another set of eyes on it before I merge, as a sanity check?
