### ISSUE TITLE
UX issue on update_languages page.

### ISSUE THREAD

**Issue by djallado** [learningequality/ka-lite#3084]
Branch: `Develop`

Expected behaviour:  It should not overlap on the right side of that container.
Steps to reproduce: 

1. Login as admin
1. Go to Language tab.

screenshot is attached below:
![screen shot alignment](https://cloud.githubusercontent.com/assets/8664071/6322401/80d7e2d4-bb4e-11e4-9589-6ebb72f70fe1.png)

Task:

1. - [x] Align Get Language Pack
1. - [x] Align installed-languages table 
1. - [x] Space before footer
1. - [ ] Space in default language.

**Comment by cpauya** [comment]
@djallado Try to check if you can also fix the footer issue as reported on #3003.
