### ISSUE TITLE
Running "update_language_packs" at central server doesn't download the latest po file translated strings from crowdin.

### ISSUE THREAD

**Issue by jesumer** [learningequality/ka-lite#3087]
Branch: develop

Expected Behavior: When running the `update_language_packs` at `central server` should download the latest po files from crowdin. I manually downloaded the po files from [crowdin](https://crowdin.com/project/khanacademy/de)  and here's the screenshot:
![screen shot 2015-02-23 at 2 38 40 pm](https://cloud.githubusercontent.com/assets/2810009/6323930/14ac1a70-bb6d-11e4-97f4-860e5f67213f.png)

Current Behavior: The zip file inside `_crowdin_cache` folder with po files at the `central server` that was downloaded by running `update_languagepacks` was not updated
See the screenshot:
![screen shot 2015-02-23 at 2 38 30 pm](https://cloud.githubusercontent.com/assets/2810009/6323890/8bf506b0-bb6c-11e4-8008-62890d5d80a8.png)

Steps to reproduce:

1. Go to [crowdin](https://crowdin.com/project/khanacademy/de) and download `learn.math.algebra-basics.exercises.pot`
2. Go to your local central server and run `python manage.py update_language_packs -l de --no-srts --no-dubbed --no-kalite-trans --force-update`
3. Go to your folder at `ka-lite-central/_crowdin_cache/ka-de.zip` and unpack this zip file and open the file `learn.math.algebra-basics.exercises.po`.
4. Compare the two files.

**Comment by jesumer** [comment]
Hi @aronasorman,

cc @cpauya 
What I did was: 
1. I open up the file `update_language_packs.py` in the `ka-lite-central/centralserver/i18n/management/commands/`.
2. Get the url that is responsible of downloading a zip file from crowdin.
![screen shot 2015-02-25 at 9 27 13 am](https://cloud.githubusercontent.com/assets/2810009/6363259/5e8df95a-bcd1-11e4-981d-943bbd333f19.png)
3. Then manually download it from crowd in using the url "https://api.crowdin.com/api/project/projectID/download/de.zip?key=key123456789"
(I changed the right url for security reason)
4. Then after, This will downloaded an outdated strings from crowdin.

My point here was I guess that the url of our code has something wrong.

**Comment by cpauya** [comment]
@jesumer Can you read more details on the [CrowdIn API](https://crowdin.com/page/api) if we have an alternative API to use?

**Comment by cpauya** [comment]
Hmm... at the [Download API](https://crowdin.com/page/api/download) page, it's saying:

> Note: If you would like to download the most recent translations you may want to use export API method before downloading.

So maybe we need to Export first before downloading to make sure we get the latest translations?

**Comment by jesumer** [comment]
We already have the "export" function it is called at code line 414 at my screenshot.
