### ISSUE TITLE
Make a dummy language pack containing reversed/accented strings.

### ISSUE THREAD

**Issue by arceduardvincent** [learningequality/ka-lite#3091]
Branch: master

Expected Behaviour:
>1. The `dummy language pack` will replicate the translation string as dummy translation for test and developement.
> 2. The `.po` files were the sets of translation string that will converted to our `.mo` files.

Current Behaviour:
>1. We don't have any means to test if the translation is propagate especially when the crowdin strings are not yet approved.
>2. We  can't test if the translation works along with the designated string that intended to it.   

Steps to Replicate:

> Refer to this docs. https://github.com/learningequality/ka-lite/wiki/Internationalization:-Coding/2a94799bc579e50677492ef536ab7bedf7cf5602#steps-to-manually-verify-translations

**Comment by cpauya** [comment]
I think this must be for the [central repo](https://github.com/fle-internal/ka-lite-central)?
