### ISSUE TITLE
Exercises allow checking for hints even after the answer is verified to be correct

### ISSUE THREAD

**Issue by Antrikshy** [learningequality/ka-lite#3093]
Hints should be disabled once user has answered the question correctly.

**Comment by mjptak** [comment]
I'm not sure this is the desired functionality.  I thought that once you
got the correct answer you still should be able to check how the hints
explained it.  (especially important as alternative solution methods are
added(if ever)).

**Comment by Antrikshy** [comment]
I see. Hopefully they don't count the answer as incorrect once it has been confirmed correct.

**Comment by MCGallaspy** [comment]
@mjptak makes a good point. I'll leave this open for further comments for now.

**Comment by MCGallaspy** [comment]
> Hopefully they don't count the answer as incorrect once it has been confirmed correct.
It apparently does not.
