### ISSUE TITLE
Drawing on scratchpad sometimes selects page elements

### ISSUE THREAD

**Issue by Antrikshy** [learningequality/ka-lite#3094]
This one is a bit hard to describe. I encountered this in the radio-button style exercise as pictured.

![screen shot 2015-02-23 at 1 35 45 pm](https://cloud.githubusercontent.com/assets/6601788/6338073/ff3b03d8-bb60-11e4-9b0d-12a5582260a1.png)

It happens when the user starts dragging from within the `label` element highlighted below.

![screen shot 2015-02-23 at 1 37 14 pm](https://cloud.githubusercontent.com/assets/6601788/6338112/3ceabc32-bb61-11e4-9ebc-4532c3679333.png)

Just a minor issue caused by having the scratchpad under the exercise.

EDIT: Also that scratchpad border overlaps another element's border. Kinda unsightly.

**Comment by MCGallaspy** [comment]
I'm not sure I understand the issue, but I think the desired behavior is for e.g. radio buttons to be above the scratchpad so that you can actually select them.

**Comment by MCGallaspy** [comment]
Anyway elements that are above the scratchpad are defined in the exercise JSON blob, so it may be hard to change.

**Comment by Antrikshy** [comment]
I know it might be hard to fix, but the radio buttons stretch across the scratchpad and it's very easy to hit one of them when drawing.

**Comment by MCGallaspy** [comment]
I see... can we add a css rule to reduce the size of the radio button containers?

**Comment by Antrikshy** [comment]
Mayhaps. I tried reducing the width, but its margin still seems to cover the space. I wasn't able to fix that. It should be possible with the `box-sizing: border-box` styling so that width is calculated including the border, margin etc (if I [understand it](http://adamkaplan.me/grid/) correctly). It's common to use this styling across the website in responsive design, but I'm not sure if it will mess up hacky styling elsewhere.

Maybe assign some CSS ninja. I'm busy with other stuff right now.

**Comment by rtibbles** [comment]
Fixed in #3138
