### ISSUE TITLE
Show scratchpad button does not work sometimes

### ISSUE THREAD

**Issue by Antrikshy** [learningequality/ka-lite#3096]
1. Go to an exercise.
2. Open scratchpad to confirm it works.
3. Go to another exercise.
4. Attempt to open scratchpad and be surprised.

Reload page to make it work again.

Related: After switching exercises, the show hints button seems to misbehave (even goes to -1 hints).

**Comment by MCGallaspy** [comment]
Are you able to open the scratchpad on a different exercise after refresh? You're sure it's not an issue of the scratchpad simply not being available for that exercise?

**Comment by Antrikshy** [comment]
Yep. This seems to affect all exercises. Also, if there are exercises with no scratchpad support, it would be nice to disable the scratchpad button on them.

**Comment by MCGallaspy** [comment]
I'm labeling this as high priority since it could potentially prevent learners from completing exercises normally.

**Comment by MCGallaspy** [comment]
I think the problem is that a listener is attached to the `#scratchpad-show` button, but a new such button is created on a backbone navigation event without attaching a listener.

**Comment by MCGallaspy** [comment]
Plot twist: the listener is registered twice and thus clicking the button calls the scratchpad visibility toggling function twice.

**Comment by Antrikshy** [comment]
That is hilarious.

**Comment by rtibbles** [comment]
Fixed in #3117 .
