### ISSUE TITLE
Submitting with hidden input button breaks the exercise

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#3101]
On `develop` in 0.13.
Expected behavior: Using tab keystroke on an input should (eventually) bring me to the submit button, where I can press enter and proceed normally. (Because who needs a mouse?)
What actually happens: On `/learn/khan/math/linear-algebra/vectors_and_spaces/vectors/adding_vectors/`, for example, pressing tab when the last input box is selected focuses on a hidden "submit" button, which when submitted clears the problem from the screen, but doesn't actually check the answer or allow you to proceed to the next problem:
![ss](https://cloud.githubusercontent.com/assets/8888020/6339606/53a32576-bb6c-11e4-9912-5cb680b3a9ad.png)

To reproduce: log in as any user type and navigate to an exercise. Select the last input and press tab one time to focus on the hidden submit button, then press enter.

**Comment by MCGallaspy** [comment]
Marking as high priority since it can prevent exercises from being completed normally.

**Comment by rtibbles** [comment]
Fixed in #3101.
