### ISSUE TITLE
Clicking edit teacher button on "users" changes the second level nav tab to "facilities," should stay on "users"

### ISSUE THREAD

**Issue by jtamiace** [learningequality/ka-lite#3105]
This is probably a templating issue.
To reproduce: log in as a teacher, go to users and click the edit button (in red below)

![users](https://cloud.githubusercontent.com/assets/6668144/6340119/463e509a-bb71-11e4-8fed-21d720e86335.PNG)

Should still be on "users"
![users to facilities](https://cloud.githubusercontent.com/assets/6668144/6340131/58ee858e-bb71-11e4-9453-3facaf4f6399.PNG)

**Comment by MCGallaspy** [comment]
Since we opened up this file, let's remove these erroneous translate blocks.

**Comment by MCGallaspy** [comment]
Disregard, meant to comment on PR.
