### ISSUE TITLE
Unexpected behaviour of Navbar With a viewport size of < 768px

### ISSUE THREAD

**Issue by arceduardvincent** [learningequality/ka-lite#3112]
Hi @aronasorman and @MCGallaspy 
Branch : Develop

As you notice the image below the `Navbar` does not display the correct positioning of its tabs menu.
when the `Navbar` With a viewport size of >768 the tabs are misalign. 

![screen shot 2015-02-24 at 2 26 33 pm](https://cloud.githubusercontent.com/assets/4099119/6344296/559a9236-bc31-11e4-8578-ed0ce2ce925d.png)

Steps to replicate:
>1. Login as Admin
>2. Set viewport width to something less than 768px, or use a device that fits that criteria
>3. Open the Reports tab

**Comment by MCGallaspy** [comment]
Are you talking about the Teach/Manage/user tabs? Can you stack all the tabs underneath the container for the search bar?

**Comment by arceduardvincent** [comment]
yeah I can @MCGallaspy .

I can make it responsive to adapt the device viewport. Let me work on this issue.
Thanks

**Comment by rtibbles** [comment]
Fixed in #3132
