### ISSUE TITLE
Windows 12.10 Installer batch files LF as opposed to CRLF!

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite#3116]
All Windows Batch scripts in current 12.10 (maybe +?) are using unix LF and not windows CRLF line endings once decompressed onto the installation machine, breaking many functions. I have repaired the 9 batch files which I found affected and everything seems much improved but I can only apply the fix locally because I am not sure how these get bound to the installer which is a separate git project which I think pulls from our ka-lite repo. What makes this worse is that when viewed from github the code seems correct only by pulling and actually inspecting these on a windows system after installation do the faults appear. One fix maybe to have our windows installer implement the checkout windows style ( "core.autocrlf" set "true") git option? Attached is a screenshot from current 12.10 showing how the same file appears on github and then in windows (word wrap is on to allow the entire file to be visible). I believe this to be the cause of reported issues with several large deployments affecting both windows 7 / windows XP / and Windows Server. Please advise and if possible prioritize!
Thanks, 

![screenshot from 2015-02-24 03 17 48](https://cloud.githubusercontent.com/assets/4349806/6347271/cf85d938-bbd3-11e4-8677-e6712cd1a55c.png)

**Comment by MCGallaspy** [comment]
Which files have you found that are affected by this, @EdDixon? All `.bat` files?

**Comment by EdDixon** [comment]
/kalite 
     start.bat
     run_command.bat
     setup_windows.bat
/kalite/scripts
     cronstart.bat
     python.bat
     run_command.bat
     serverstart.bat
     start.bat
     stop.bat

I discovered these while manually applying server settings trying to get the broken install from windows installer to work properly. I do not believe you will find them any other way but to completely wipe ka-lite (and possibly python) from a windows install and then install using the installer and look at those files. Because they do not seem broken in GIT it explains why your attempts are not encountering the problem. I can only assume they are somehow not being "translated" on what ever system is compiling these into the windows installer from our source which is posix based? Assuming they are being pulled into the installer directly from source to begin with? It is the only explanation I can think of?

**Comment by EdDixon** [comment]
Closing this issue as we now have the installers repo which deprecates this one and there is more information there but for the record the LF/CRLF issues were found to not be affecting the scripts functionality although there is an open issue in installers to clean those to make them more transparent in form and function to the end user.
