### ISSUE TITLE
Hover on tabular coach report obscures user data

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#3119]
@Antrikshy this looks like it came from your addition of .table-hover class on the tabular coach report. Care to fix?

![image](https://cloud.githubusercontent.com/assets/1680573/6364902/67ecb334-bc62-11e4-8092-fdaa1e952300.png)

**Comment by Antrikshy** [comment]
I'll take a look at it as soon as possible.

**Comment by Antrikshy** [comment]
There you go: #3125.

From what I gather from the screenshot, removing .table-hover should fix it, correct?

**Comment by cpauya** [comment]
PR fix #3125, closing.
