### ISSUE TITLE
Coach report facility selection flows nicely for mobile, not for larger view ports

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#3120]
@Antrikshy your changes have made this page better for mobile, but it pushes actionable items off the bottom of the screen on wider viewports (i.e. the report type specific inputs and buttons).

Can we make this responsive for all form factors?

![image](https://cloud.githubusercontent.com/assets/1680573/6364952/36a461fe-bc63-11e4-9b8c-7c63878be8d4.png)

**Comment by Antrikshy** [comment]
I can't reproduce. You mean stretching the screen really wide makes the bottom form etc disappear? 

Fullscreen on a huge monitor doesn't do anything on my end (tested on Firefox and Safari): 
![screen shot 2015-02-25 at 2 42 43 pm](https://cloud.githubusercontent.com/assets/6601788/6382343/96f25d4c-bcfc-11e4-803c-ff375c9fa0c5.png)

What browser/device does this occur on?

**Comment by cpauya** [comment]
@Antrikshy Prior to your updates, the dropdowns are laid-out horizontally, now they are all in vertical.  The vertical layout is good for mobile devices, but we should preserve the horizontal display for desktop browsers (maybe whose width > 768px?), it makes it easy to see the other controls at the bottom.

@arceduardvincent Can you take a look on this?

**Comment by Antrikshy** [comment]
Ohhh I see. I think I know exactly how to fix this! Assign this issue to me so I can easily look it up tomorrow or later today.

**Comment by arceduardvincent** [comment]
I suggest that we consider the view port of each device and our app must have a responsive design. 
I'll attach some image that demonstrate the responsive design and it corresponds on 3 different viewport mobile and desktop view.

The mobile view with a `(320 × 480 HVGA (old iPhones, small Androids))` and `(768 × 1280 WXGA - High-end Windows Phone)`

![screen shot 2015-02-26 at 4 10 04 pm 2](https://cloud.githubusercontent.com/assets/4099119/6388248/c047d29a-bdd2-11e4-9d91-ea02feb90070.png)

The desktop View `1280 × 1024 SXGA - Small desktop`

![screen shot 2015-02-26 at 4 10 04 pm](https://cloud.githubusercontent.com/assets/4099119/6388262/daaabde6-bdd2-11e4-8849-740351a6a3ad.png)

**Comment by Antrikshy** [comment]
I have been working on this. I like the idea of a completely horizontal form on larger screens though.

**Comment by arceduardvincent** [comment]
:+1: 
thanks for the confirmation on my suggestion.

**Comment by rtibbles** [comment]
Fixed in #3141
