### ISSUE TITLE
Language pack error message should not appear at video tab.

### ISSUE THREAD

**Issue by amodia** [learningequality/ka-lite#3122]
Branch: `Develop`
Expected behavior: Language pack error message should not appear when video tab is active.
Steps to reproduce:
 1. make sure the distributed is not connected to central server. 
 2.  log in as admin.
 3. navigate to video and language tab.
 
![ka-lite-a](https://cloud.githubusercontent.com/assets/8663934/6367632/402e8652-bd10-11e4-9017-85d15d853b6c.gif)

**Comment by cpauya** [comment]
To put this in context (assuming that we didn't use the `clear_messages()` javascript function on the Videos and Languages codes:

1. If user selects the Manage menu -> Videos tab, the error message relating to languages shows.
2. If user selects the Manage menu -> Languages tab, there are no error message relating to video.

So the question is: Why does the code relating to the languages run even when I am on the Videos tab?

I think that's what @amodia need to check, perhaps the codes are not completely transitioned to `backbonejs`?

**Comment by rtibbles** [comment]
Fixed in #3123.
