### ISSUE TITLE
User popup on scatterplot coach 

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3124]
Branch: develop

Expected: Nice, colored legend on student popup on scatter report.

Observed:
![image](https://cloud.githubusercontent.com/assets/618416/6369351/5482f970-bd07-11e4-9e45-83e23fb2ed3d.png)

Steps to replicate:

- Load scatter coach report page
- Click on dot
- Observe ugly legend formatting in popup

**Comment by djallado** [comment]
@jamalex 
Agree. Maybe we put Struggling below the **name** indent it and put proper Colour.

**Comment by cpauya** [comment]
@djallado - This already has colored legends before, now they are missing or removed, perhaps cross-check on the `master` branch?

**Comment by rtibbles** [comment]
This is how it looks on master:
![image](https://cloud.githubusercontent.com/assets/1680573/6385603/0cb4285c-bd21-11e4-91cb-710d667c26cf.png)

Just a matter of making this functionality work properly again. Might just be css style names got changed in one place, but not here (for example on the Tabular Report legend styles).

**Comment by djallado** [comment]
Ok. Thanks @cpauya and @rtibbles, I'll verify it.

**Comment by rtibbles** [comment]
Fixed in #3129.
