### ISSUE TITLE
Page titles of some templates are wrong.

### ISSUE THREAD

**Issue by cpauya** [learningequality/ka-lite#3128]
Branch **develop**

To reproduce:

1. Login as admin and navigate to the `Manage` tab.
2. Click on the `Videos` tab and notice the page title is wrong "Update VideosWelcome | KA Lite"
3. Click on the `Language` tab and notice the page title is also wrong "Update LanguagesWelcome | KA Lite"

This is related to #3057 but decided to open a new issue as "catch-all" for all templates affected by this.

![screenshot 2015-02-26 11 21 00](https://cloud.githubusercontent.com/assets/175580/6385750/919bb6a6-bda9-11e4-8123-f43cfc955a98.png)

![screenshot 2015-02-26 11 22 15](https://cloud.githubusercontent.com/assets/175580/6385763/c53ff9b8-bda9-11e4-891d-df3db4d14460.png)

**Comment by rtibbles** [comment]
Fixed in #3131 .
