### ISSUE TITLE
Manage tab not working for coach user.

### ISSUE THREAD

**Issue by amodia** [learningequality/ka-lite#3133]
Branch: `develop`
Expected behavior: when clicking the manage tab it must active and show manage navigation.
Steps to reproduce:
 1. log-in as coach 
 2. navigate to manage tab.

![ka-lite-a](https://cloud.githubusercontent.com/assets/8663934/6387949/a16989bc-bdce-11e4-8543-22c49d9bfc4f.gif)

**Comment by cpauya** [comment]
We found out that for the coach user, the `Manage` tab points to the `control_panel/facility_management.html` template which does not inherit the blocks used in the `base_manage.html`.

However when the coach user clicks on the "Zone for public..." link, the user is presented with the UI for the local KA Lite installation such as this and that the `Manage` link is now active:

![screenshot 2015-02-26 17 16 50](https://cloud.githubusercontent.com/assets/175580/6389079/781fe9d6-bddb-11e4-9243-6c327e009dc1.png)

We are "lost" in trying to fix this - hopefully someone more knowledgeable on the navigation links can help?

/cc: @jamalex @jtamiace @MCGallaspy @rtibbles @aronasorman

**Comment by rtibbles** [comment]
Fixed in #3135.
