### ISSUE TITLE
Unlimited questions after streak completion.

### ISSUE THREAD

**Issue by jesumer** [learningequality/ka-lite#3134]
Branch: develop

Expected Behavior: After the streak completion should stop or proceed to the next exercise.

Current Behavior: After streak completion we now have unlimited questions.
![screen shot 2015-02-26 at 4 11 01 pm](https://cloud.githubusercontent.com/assets/2810009/6388206/1d4eb57c-bdd2-11e4-8939-a8324887cdab.png)

Steps to reproduce:

1. Logged in as a student user.
2. Do an exercise.
3. Finish the exercise and close the prompt. Notice that even after you have already finished the exercise, You have unlimited questions instead of proceeding to another exercise.

**Comment by MCGallaspy** [comment]
I think this merits discussion. Is this the intended behavior when completing exercises? Perhaps we can make it a configurable option?

**Comment by rtibbles** [comment]
I believe this is the intended behaviour. We never want to stop users from practicing more after achieving what we are currently defining as 'mastery' and until we have something akin to content recommendation, we're not really pushing them forward to anything else except by expecting them to navigate to it through the sidebar.
