### ISSUE TITLE
Tabular reports report type and topic selector reflows poorly on small screens

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#3142]
To reproduce, navigate to default coach report page with viewport <760px.

![image](https://cloud.githubusercontent.com/assets/1680573/6406079/d287b48c-be51-11e4-8233-2e54ad01f406.png)

**Comment by arceduardvincent** [comment]
Hi @rtibbles can I work on this issue?

**Comment by rtibbles** [comment]
Sounds good.

**Comment by rtibbles** [comment]
Fixed in #3147
