### ISSUE TITLE
Manage Navigation user and facilities tab have the same tooltip.

### ISSUE THREAD

**Issue by amodia** [learningequality/ka-lite#3143]
Branch: `develop` for 0.13.x
Expected behavior: user and manage tab must have different tooltip.
Actual behavior: When you hover the user and manage tab is has the same tooltip `manage user`.

![ka-lite-a](https://cloud.githubusercontent.com/assets/8663934/6406158/aa432770-be67-11e4-87f0-02f5c5d5fd21.gif)

Steps to reproduce:
 1. log in as coach.
 2. navigate to manage tab.
 3. hover to user and facilities tab.

**Comment by rtibbles** [comment]
Fixed in #3144 .
