### ISSUE TITLE
Alignment issue of subnav when resizing to < 480px.

### ISSUE THREAD

**Issue by jesumer** [learningequality/ka-lite#3145]
Branch: `develop` for `0.13.x` - February 27 2015

Expected behavior: The subnav should be aligned

Actual behavior:
This size 480px is for `Low end windows phone`.
![screen shot 2015-02-27 at 11 52 30 am](https://cloud.githubusercontent.com/assets/2810009/6407314/5cd3c858-be78-11e4-9b22-991b711f1bf7.png)

Steps to reproduce:

1. Login as teacher user.
2. Go to the manage tab.
3. Resize to 480px or less and notice.

**Comment by rtibbles** [comment]
Fixed in #3146.
