### ISSUE TITLE
Confused the difference between central server and distributed server

### ISSUE THREAD

**Issue by wangguan59** [learningequality/ka-lite#316]
One usability issue we have noticed was that some user get confused when they switch between central server and distributed sever. 
1) Similar UI style and navigation bar make user confused whether they are in central or distributed server 
2) Some users are not clear about the functionality and purpose between central and distributed server. 
3) Scenarios happen during: Device registration, Data sync (facility, zone, and user data)

I don't have a good solution for it. It's worth to discuss for during next dev meeting. 
* Quick way: Change the logo and title when the user login to the central server. We can called it KA Lite Online Management (not sure "central server" is a good word choice for non-technical people)
* Complex way: Change the navigation bar style on either sever. 

Any thoughts?

**Comment by aronasorman** [comment]
They are now different repos; difference should be clearer: https://github.com/fle-internal/ka-lite-central
