### ISSUE TITLE
Teacher (and presumably other navs) aren't properly mobile responsive

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#3168]
While use on cell phones is not our primary use case by any means, I think the second layer nav system for teachers and admins would be better if it could responsively collapse like the top level nav (maybe using a hamburger, maybe using some other format).

See here a screenshot on the Nexus 5:

![image](https://cloud.githubusercontent.com/assets/1680573/6434981/9fdc469e-c048-11e4-86bb-596c8dfd87e7.png)

@jtamiace Can you take a look at making this a more responsive design over all?

**Comment by jtamiace** [comment]
Oi. Yeah I didn't take that into account because I never expected it to be used on mobile. A hamburger icon would be best; will work on it this week.

**Comment by djallado** [comment]
@ i'll to work on this today.

**Comment by rtibbles** [comment]
@djallado No, @jtamiace is assigned and working on this.

**Comment by djallado** [comment]
Ok. Thanks. I'll look for other issue.
