### ISSUE TITLE
Cannot input into answer field using Internet Explorer

### ISSUE THREAD

**Issue by cts-prog3** [learningequality/ka-lite#3171]
When using IE I am not able to enter a value into the answer fields while doing an exercise.

**Comment by rtibbles** [comment]
Eek, that's a concern.

Which version of IE are you using? Can you provide a screenshot of the exercise you are working on too?

**Comment by aronasorman** [comment]
@MCGallaspy can you confirm this bug once we have a sample test?

**Comment by cts-prog3** [comment]
I am using IE 8 on Windows 7.  Here is a screen shot.
[cid:image001.png@01D055C6.DB18B720]

Thanks, Paul


[cid:image002.png@01CFA718.020EECE0]

Paul Dokken
Software Developer
SIL PNG Communication and Technology Services
Ukarumpa EHP 444 | Papua New Guinea
cts-prog3@sil.org.pg<mailto:cts-prog3@sil.org.pg>
+675-537-3544 x4404 {Telecom}
+675-7081-8666 {Digicel}

**Comment by cts-prog3** [comment]
I also see this error message:
Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3)
Timestamp: Tue, 3 Mar 2015 05:30:12 UTC


Message: Not implemented

Line: 57
Char: 9
Code: 0
URI: http://127.0.0.1:8008/static/js/distributed/software-keyboard.js


Thanks, Paul


[cid:image002.png@01CFA718.020EECE0]

Paul Dokken
Software Developer
SIL PNG Communication and Technology Services
Ukarumpa EHP 444 | Papua New Guinea
cts-prog3@sil.org.pg<mailto:cts-prog3@sil.org.pg>
+675-537-3544 x4404 {Telecom}
+675-7081-8666 {Digicel}

**Comment by rtibbles** [comment]
Thanks for the info. Looks like it is being caused by the software keyboard causing a compatibility issue with IE 8, we will look into it! Thanks for the report.

**Comment by MCGallaspy** [comment]
@cts-prog3 how did you install KA Lite? Through our windows installer or by pulling the source from git, and if the latter then which branch did you pull from?

**Comment by cts-prog3** [comment]
I used the installer.

Thanks, Paul


[cid:image002.png@01CFA718.020EECE0]

Paul Dokken
Software Developer
SIL PNG Communication and Technology Services
Ukarumpa EHP 444 | Papua New Guinea
cts-prog3@sil.org.pg<mailto:cts-prog3@sil.org.pg>
+675-537-3544 x4404 {Telecom}
+675-7081-8666 {Digicel}

**Comment by MCGallaspy** [comment]
@cts-prog3 by the way, your attached screenshots don't show up on when you reply through email. Can you post them directly to the thread on github?

**Comment by cts-prog3** [comment]
![kalite ie problem js error](https://cloud.githubusercontent.com/assets/7528702/6475937/d9436754-c25b-11e4-950a-07c98bdced9e.PNG)
![kalite ie problem](https://cloud.githubusercontent.com/assets/7528702/6475938/d9490dee-c25b-11e4-932b-4dde03de0da0.PNG)

**Comment by cts-prog3** [comment]
We have a server running on a linux box and when I try to access it with IE 11 it works fine.

**Comment by rtibbles** [comment]
@MCGallaspy I believe the issue is coming from this line:

```this.field.val(this.field.val().slice(0, -1));```

Googling around, it looks like there might be an issue with using .val to set values on IE7 and 8.

The right fix looks likely to be:

```this.field.prop("value", this.field.val().slice(0, -1));```

**Comment by rtibbles** [comment]
@MCGallaspy I don't have easy access to an IE8 VM in India, can you implement and test?

**Comment by MCGallaspy** [comment]
@rtibbles working on it

**Comment by MCGallaspy** [comment]
Running IE8 on Windows 7, serving `develop`, I get considerably more errors than just the software keypad...

**Comment by MCGallaspy** [comment]
When is the last time anyone checked out the app on IE8? Presumably the issue author is running 0.12 (which I'm presently testing out for this issue), but `develop` has simply an avalanche of JS errors.

**Comment by rtibbles** [comment]
Sounds like we have some compatibility fixing to do. I don't think I'll have the time next week to do a full investigation and fixing, but I have some experience with compatibility issues, so can be on hand for questions.

**Comment by MCGallaspy** [comment]
So how should we characterize this issue? Given that some compatibility issues apparently have existed since 0.12, do we consider this a blocker for 0.13? Or shall we release compatibility fixes in future 0.13 minor versions? IE8 is the last version of IE to run on XP and Server 2003, but one workaround is to use Chrome (#2925) and possibly other browsers.

**Comment by rtibbles** [comment]
I think we should aim to do the minimal compatibility fix that we can before 0.13, as it seems that even on our online site, we still have IE8 users. Goal: not pretty, but not throwing errors.

**Comment by EdDixon** [comment]
One Work around I found effective for this was to use google chrome for enterprise : https://www.google.com/work/chrome/browser/ IT departments have been able to get this approved quickly as it proided the IT department the controls they needed. While giving the classroom a responsive fast HTML 5 compatible  browser.

**Comment by MCGallaspy** [comment]
Okay, I'll try to fix compatibility issues in `develop` on IE8 in XP.

**Comment by MCGallaspy** [comment]
Browser compatibility with reactjs: http://facebook.github.io/react/docs/working-with-the-browser.html#browser-support-and-polyfills

**Comment by MCGallaspy** [comment]
pdfjs doesn't support IE8: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#what-browsers-are-supported

Is there a fallback we can use?

**Comment by MCGallaspy** [comment]
Is the KA perseus stuff supposed to be compatible with IE8? At least one of the JS errors I'm getting seems to be from those inclusions.

**Comment by MCGallaspy** [comment]
Nope, KA [doesn't support IE8](https://www.khanacademy.org/coach-res/reference-for-coaches/technology-considerations/a/supported-browsers). Given that we include the KA perseus stuff, is it still reasonable to expect that we should support IE8 too? Presumably we'll have to modify the inclusions, which isn't necessarily the best idea if we want to update them in sync with KA. Do we need to rethink how we include KA assessment items?

**Comment by rtibbles** [comment]
@mike - if Perseus is not compatible with IE8, then we should probably forget trying to make it compatible, I would say, and just direct people to using 0.12 if they are in environments where they can only use IE8.

We can perhaps, apply a hotfix for the software keyboard to prevent the issue happening on master? @aronasorman

**Comment by aronasorman** [comment]
Yeah, this seems critical enough to warrant a hotfix. I'll reopen the 0.12 bugfixes milestone and put this in there.

**Comment by aronasorman** [comment]
We'll also need to specify the software requirements in the manual, maybe somewhere in the [0.13 installation guide](http://ka-lite.readthedocs.org/en/latest/installguide/install_windows.html).
