### ISSUE TITLE
On a tablet, zooming the screen causes a change in relative size of the sidebar

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#3175]
Current behaviour:
Zooming in on a tablet causes sidebar to become hugely expanded

Expected behaviour:
Sidebar should stay the same relative size, allowing the content area that is being zoomed to take more of the focus, while the choices of content remain just as obvious (due to taking up no more screen area).

![image](https://cloud.githubusercontent.com/assets/1680573/6463607/ac5b0a38-c168-11e4-87dd-023aabadf19c.png)

**Comment by Antrikshy** [comment]
Since I'm working on making the sidebar responsive, I'll definitely look into this at some point.

**Comment by MCGallaspy** [comment]
@Antrikshy has this been resolved?

**Comment by Antrikshy** [comment]
I haven't looked at it, actually. Handling touchscreen zoom is tricky. @rtibbles, were you suggesting that we keep the sidebar the same size on the side of the screen? Any ideas on how that would work?

**Comment by rtibbles** [comment]
Not going to happen within the scope of KA Lite.
