### ISSUE TITLE
Non-semantic HTTP Response codes

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#3177]
At the moment, many of our JSON response errors are 500s - indicating that something has gone terribly wrong inside the server. This is simply not the case, as the response has been returned deliberately, and hence should almost always return an appropriate 4xx code.

**Comment by aronasorman** [comment]
OH GOD YES. So hard to tell what's actually wrong with those API calls.

@rtibbles can you document here what status codes we want to use for what? Might be good to include that eventually to our dev documentation @MCGallaspy

**Comment by aronasorman** [comment]
However, I'm torn on whether this is a blocker for 0.13. It really helps with debugging, but I don't think the user really cares what kind of error it is.

**Comment by rtibbles** [comment]
I think 0.14 is the right call for this.

**Comment by anuragkanungo** [comment]
Would like to work on it, any suggestions and pointers ?

**Comment by rtibbles** [comment]
Find any instance inside an API call where exceptions are raised, or where JsonResponseMessageError is used without a status kwarg.

These should be corrected to having a kwargs ```status=xxx```, where most of the errors should probably be of the form 4xx, because if the server is not throwing an error, but the request is not properly made, then it is a client issue. See here for appropriate codes: http://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_Error

**Comment by rtibbles** [comment]
@georgyberdyshev seems to have fixed all these in #3435
