### ISSUE TITLE
Options for answers are shown on the right pane.

### ISSUE THREAD

**Issue by cpauya** [learningequality/ka-lite#3182]
Branch: **develop**
Milestone: for **0.13.x**
Browsers: **Firefox v36.0**, **Chrome v41.x**, **Safari v8.0.3**

Expected Behavior:  The options must display at the left pane below the questions like this:
![screenshot 2015-03-05 20 52 52](https://cloud.githubusercontent.com/assets/175580/6505098/a995d2d4-c379-11e4-8aa8-321a09ff744c.png)

Current Behavior: The options for choosing the answers are shown on the right side instead of at the bottom of the question on the left pane.  ~~This usually manifests when the number of options are more than 4.~~  This is because some exercises have their answer options put in the answer area: refer to @amodia's findings below.

To reproduce:

1. Navigate to http://127.0.0.1:8008/learn/khan/computing/computer-science/algorithms/binary-search/running-time-of-binary-search/
2. See screenshot of the issue

![screenshot 2015-03-05 20 42 49](https://cloud.githubusercontent.com/assets/175580/6505034/d3a45204-c378-11e4-9fbf-c08935ddf4a0.png)

**Comment by cpauya** [comment]
It seems that even when the number of options is equal to 4, sometimes they still show on the right side.

![screenshot 2015-03-05 20 50 16](https://cloud.githubusercontent.com/assets/175580/6505077/6027dee4-c379-11e4-9ab1-b5f5450365d9.png)

**Comment by mjptak** [comment]
I figure this is a good place to chime in to wonder if there would be some
way to signal or flag khan and perseus exercises that will work well on
small screens.  Now that the video stuff works fine on smaller screen with
all the bootstrapping it might be nice to deliver a subset of exercises
that do as well.  Keep rockin' it.

**Comment by amodia** [comment]
Hi @rtibbles I found out that there are two different objects on this persus exercise: http://127.0.0.1:8008/learn/khan/computing/computer-science/algorithms/binary-search/running-time-of-binary-search/

This object is working properly.
![screen shot 2015-03-31 at 4 07 26 pm](https://cloud.githubusercontent.com/assets/8663934/6914764/af2a3b6c-d7c0-11e4-9b18-872764338fe6.png)

![screen shot 2015-03-31 at 4 06 37 pm](https://cloud.githubusercontent.com/assets/8663934/6914774/bdfcdbcc-d7c0-11e4-8321-a62217e5f08e.png)

This object is not working properly.
![screen shot 2015-03-31 at 4 08 58 pm](https://cloud.githubusercontent.com/assets/8663934/6914790/ea7d9ae2-d7c0-11e4-8cca-7d8c3c4ee7de.png)

![screen shot 2015-03-31 at 4 08 17 pm](https://cloud.githubusercontent.com/assets/8663934/6914796/f2ed43b2-d7c0-11e4-985d-9df9e70f3154.png)

**Comment by aronasorman** [comment]
Stale. Reopen if still extant.
