### ISSUE TITLE
User documentation sidebar too busy

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#3184]
On `develop` in the docs (check out http://field.learningequality.org/docs/) someone suggested in the AHM that the sidebar has too much depth. This issue is for discussion. Should the sidebar include links to locations within a page, links going up the document structure (to different pages within the docs), both, or something else entirely? @tk21 @christinepham @cs-shadow

**Comment by aronasorman** [comment]
They're OK in my view. Perhaps more padding between table-of-content entries is all that's needed to make it more visually appealing.

**Comment by aronasorman** [comment]
Nonissue for me. Reopen if anyone has strong opinions.
