### ISSUE TITLE
Correct answer is shown in the response JSON from call to the assessment item API.

### ISSUE THREAD

**Issue by cpauya** [learningequality/ka-lite#3193]
Branch **develop**

Milestone **for 0.13.x**

Browser: **Firefox v36.0.1**

**Expected Behavior:**  The response to the API call to get the details of an assessment item like http://127.0.0.1:8008/api/assessment_item/xc31e8609fc03af5a/ must NOT divulge the answer to the problem.

Since these most likely came from the `assessmentitems.json` - I have no idea how we can remove the flag to the correct answer.

**Current Behavior:**  The above API call returns this JSON response which includes the correct answer:

These examples are taken from: http://127.0.0.1:8008/learn/khan/math/early-math/cc-early-math-counting-topic/cc-early-math-counting/count-to-100/

**Example API call 1:** http://127.0.0.1:8008/api/assessment_item/xc31e8609fc03af5a/

> {"author_names": "[u'Gail Hargrave']", "id": "xc31e8609fc03af5a", "item_data": "{\"question\":{\"content\":\"Let's count by tens.\\n\\n![](/content/khan/8ee48083c68af5fd473319217c597ef07daa8088.png)\\n\\n**What number did we miss?**\\n\\n \\n\\n[[â˜ƒ radio 1]]\",\"images\":{\"/content/khan/8ee48083c68af5fd473319217c597ef07daa8088.png\":{\"width\":450,\"height\":81}},\"widgets\":{\"radio 1\":{\"type\":\"radio\",\"graded\":true,\"options\":{\"choices\":[{\"content\":\"$30$\",\"correct\":false},{\"content\":\"$60$\",\"correct\":true},{\"content\":\"$70$\",\"correct\":false}],\"randomize\":true,\"multipleSelect\":false,\"displayCount\":null,\"noneOfTheAbove\":false,\"onePerLine\":true},\"version\":{\"major\":0,\"minor\":0}}}},\"answerArea\":{\"type\":\"multiple\",\"options\":{\"content\":\"\",\"images\":{},\"widgets\":{}},\"calculator\":false},\"itemDataVersion\":{\"major\":0,\"minor\":1},\"hints\":[{\"content\":\"We missed $\\\\blue{60}$.\",\"images\":{},\"widgets\":{}}]}", "kind": "AssessmentItem", "resource_uri": "/api/assessment_item/xc31e8609fc03af5a/", "sha": "70effce750bd8343822124f612f97b1440a03b3f"}

Raw version:

```json
{"author_names": "[u'Gail Hargrave']", "id": "xc31e8609fc03af5a", "item_data": "{\"question\":{\"content\":\"Let's count by tens.\\n\\n![](/content/khan/8ee48083c68af5fd473319217c597ef07daa8088.png)\\n\\n**What number did we miss?**\\n\\n \\n\\n[[â˜ƒ radio 1]]\",\"images\":{\"/content/khan/8ee48083c68af5fd473319217c597ef07daa8088.png\":{\"width\":450,\"height\":81}},\"widgets\":{\"radio 1\":{\"type\":\"radio\",\"graded\":true,\"options\":{\"choices\":[{\"content\":\"$30$\",\"correct\":false},{\"content\":\"$60$\",\"correct\":true},{\"content\":\"$70$\",\"correct\":false}],\"randomize\":true,\"multipleSelect\":false,\"displayCount\":null,\"noneOfTheAbove\":false,\"onePerLine\":true},\"version\":{\"major\":0,\"minor\":0}}}},\"answerArea\":{\"type\":\"multiple\",\"options\":{\"content\":\"\",\"images\":{},\"widgets\":{}},\"calculator\":false},\"itemDataVersion\":{\"major\":0,\"minor\":1},\"hints\":[{\"content\":\"We missed $\\\\blue{60}$.\",\"images\":{},\"widgets\":{}}]}", "kind": "AssessmentItem", "resource_uri": "/api/assessment_item/xc31e8609fc03af5a/", "sha": "70effce750bd8343822124f612f97b1440a03b3f"}
```

The answer in this JSON is at `{\"content\":\"$60$\",\"correct\":true}`.

**Example API call 2:**  http://127.0.0.1:8008/api/assessment_item/x53f0c415af612d3f/

> {"author_names": "[u'Gail Hargrave']", "id": "x53f0c415af612d3f", "item_data": "{\"question\":{\"content\":\"**What number is missing?**  \\n[[â˜ƒ input-number 1]]\\n\\n![](/content/khan/0bca09d49f7a78a900d99955bb5252fa21c285f2.png)\",\"images\":{\"/content/khan/0bca09d49f7a78a900d99955bb5252fa21c285f2.png\":{\"width\":400,\"height\":300}},\"widgets\":{\"input-number 1\":{\"type\":\"input-number\",\"graded\":true,\"options\":{\"value\":36,\"simplify\":\"required\",\"size\":\"normal\",\"inexact\":false,\"maxError\":0.1,\"answerType\":\"number\"},\"version\":{\"major\":0,\"minor\":0}}}},\"answerArea\":{\"type\":\"multiple\",\"options\":{\"content\":\"\",\"images\":{},\"widgets\":{}},\"calculator\":false},\"itemDataVersion\":{\"major\":0,\"minor\":1},\"hints\":[{\"content\":\"$\\\\red{36}$ is missing.\",\"images\":{},\"widgets\":{}}]}", "kind": "AssessmentItem", "resource_uri": "/api/assessment_item/x53f0c415af612d3f/", "sha": "1b3d355f87896c6862337db0c072919fcae0d9b4"}

Raw version:

```json
{"author_names": "[u'Gail Hargrave']", "id": "x53f0c415af612d3f", "item_data": "{\"question\":{\"content\":\"**What number is missing?**  \\n[[â˜ƒ input-number 1]]\\n\\n![](/content/khan/0bca09d49f7a78a900d99955bb5252fa21c285f2.png)\",\"images\":{\"/content/khan/0bca09d49f7a78a900d99955bb5252fa21c285f2.png\":{\"width\":400,\"height\":300}},\"widgets\":{\"input-number 1\":{\"type\":\"input-number\",\"graded\":true,\"options\":{\"value\":36,\"simplify\":\"required\",\"size\":\"normal\",\"inexact\":false,\"maxError\":0.1,\"answerType\":\"number\"},\"version\":{\"major\":0,\"minor\":0}}}},\"answerArea\":{\"type\":\"multiple\",\"options\":{\"content\":\"\",\"images\":{},\"widgets\":{}},\"calculator\":false},\"itemDataVersion\":{\"major\":0,\"minor\":1},\"hints\":[{\"content\":\"$\\\\red{36}$ is missing.\",\"images\":{},\"widgets\":{}}]}", "kind": "AssessmentItem", "resource_uri": "/api/assessment_item/x53f0c415af612d3f/", "sha": "1b3d355f87896c6862337db0c072919fcae0d9b4"}
```

The answer in this JSON is at `"options\":{\"value\":36,...`

**To Reproduce:**

1. Navigate to http://127.0.0.1:8008/learn/khan/math/early-math/cc-early-math-counting-topic/cc-early-math-counting/count-to-100/
2. On Firefox's Web Developer Tools -> Network, click the the latest API call which is a GET to http://127.0.0.1:8008/api/assessment_item/xc31e8609fc03af5a/?_=1425697423062
3. Click on the Response tab, then the `item_data` entry.
4. See .gif screenshot.  

On the .gif screenshot, notice that for both the multiple choice or fill-in-the-blanks questions, the correct answer is included in response to the API call.

![ka-lite](https://cloud.githubusercontent.com/assets/175580/6539884/e9679ae2-c4bd-11e4-8c98-a880bba1e276.gif)

Some notes:

* Students may not be able to navigate to the Web Developer tools of their browser, so this issue becomes moot.  But still exposes the answer to the browser nonetheless.
* Perhaps this is how the exercises are programmed, I don't know much of it's code base just yet.

**Comment by jamalex** [comment]
> Perhaps this is how the exercises are programmed

Yep, the Perseus code uses this in order to determine whether the answer supplied by the user is correct. (Same thing happens [on KA's site](https://www.khanacademy.org/api/internal/user/exercises/count-from-any-number/problems/1/assessment_item?task_type=practice) as well.) So I think we can close this.

If users have figured out how to mess with Developer Tools, then, as @mjptak quoting John Resig says, "We've already won." :smile_cat:

**Comment by mjptak** [comment]
For stuff that will truly be used for summative "assessment" I am guessing
there might be a slick way to make the answer in the json files a bit less
obvious.  The positive bit is that once folk figure out the perseus format
the ability to scale from 20k assessment items to many more and better (and
dare I say locally relevant) exercises will be there.  I'm thinking the
"counting in scenes" exercise with local art.  Keep rockin' it.

**Comment by cpauya** [comment]
Ah, good feedback @jamie and @mjptak.  As we sometimes say: "It's not a bug, it's a feature!" :smiley_cat:
