### ISSUE TITLE
showing error message update command after creating superuser and starting the server

### ISSUE THREAD

**Issue by tarunsharma1** [learningequality/ka-lite#3195]
Current behavior: Giving error message.Printing out html code in the error message and asking user to run the command python manage.py update. This update command is causing things to not work by deleting some folders. It can be undone by the command git checkout develop 
Expected behavior: A nice clean error message and no link to the faulty update command

Steps to reproduce:
1.After installing, start the server, create a student account using the sign in button.
2.Then stop the server, create a superuser account using bin/kalite manage createsuperuser
3.start the server
The error message along with the update request is seen.

**Comment by MCGallaspy** [comment]
The `update` management command should have been expurgated already. Someone (probably me) should try to reproduce this nonetheless.

**Comment by aronasorman** [comment]
I think we need to purge all references to the `update` command before release.

**Comment by aronasorman** [comment]
Can't replicate with the latest develop. I also see no more mentions of `manage.py update`.
