### ISSUE TITLE
Auto - opening of sidebar after you search for a topic | Blank Space

### ISSUE THREAD

**Issue by namchester** [learningequality/ka-lite#3203]
The sidebar doesn't show up automatically after you search for something. You have to click on the arrow on the left to scroll-open the side bar.
Also, is it just me, the page looks completely empty. I mean, something should be there when you sign in. Right?

**Comment by Antrikshy** [comment]
About that sidebar... are you saying when you select a search suggestion? The sidebar does open for me then. And when I type in something vague and don't select something concrete, I am taken to a search results page.

**Comment by MCGallaspy** [comment]
@namchester can you provide detailed steps to reproduce, including a description of the expected behavior and the actual behavior?

**Comment by namchester** [comment]
Yeah, just synced my fork. It is already fixed. Sorry for the trouble.
