### ISSUE TITLE
A message showing in the Progress Report when you haven't started with any exercises yet.

### ISSUE THREAD

**Issue by namchester** [learningequality/ka-lite#3204]
I think there should be a message "Start learning to see your progress. Go to http://localhost:8008/learn/khan/ to learn!" Any suggestions?

**Comment by MCGallaspy** [comment]
@namchester this issue just came up in our chat room, and I feel it lacks important context. Please check out [our guidelines for opening issues](https://github.com/learningequality/ka-lite/blob/develop/CONTRIBUTING.md). Can you include more information for this and any future issues you open? The steps to reproduce that you include should describe how you navigated to a page (i.e. the relative url or the links you clicked).

**Comment by namchester** [comment]
Sorry!

Steps to reproduce: Going on the http://localhost:8008/management/account/ page on the student side, if a student hasn't completed/started any exercises/videos yet. 

Current Behaviour: Shows a blank page with no progress.
Expected Behaviour: Should show a message that the student hasn't started browsing any of the above stated materials yet, along with a link to start learning.

**Comment by tarunsharma1** [comment]
yep almost fixed

**Comment by namchester** [comment]
I was looking to fix it, but anyways.

**Comment by tarunsharma1** [comment]
@namchester oh sorry i didnt know :/
Anyway i already spend alot of time and fixed it..but having issues with my git...so please dont submit a patch..ill be submitting mine in sometime :)

**Comment by MCGallaspy** [comment]
Apparently resolved.
