### ISSUE TITLE
Search page title says "WelcomeSearch results for"

### ISSUE THREAD

**Issue by Antrikshy** [learningequality/ka-lite#3217]
Very minor bug.

![screen shot 2015-03-10 at 11 34 48 am](https://cloud.githubusercontent.com/assets/6601788/6582307/c5c8802a-c719-11e4-94d1-963fea67a783.png)

Just search for something that takes you to the search results page. "search" works.

**Comment by MCGallaspy** [comment]
Probably just have to change the title block in the template used for the search page.

**Comment by Antrikshy** [comment]
I took a look at it before opening the issue. I cannot find where the Welcome comes from. I guess I can check how other pages remove the Welcome before adding their own title. Someone with more knowledge of this may be able to fix it quicker.

**Comment by rtibbles** [comment]
Fixed in #3261
