### ISSUE TITLE
RuntimeError at /management/zone/None/

### ISSUE THREAD

**Issue by sharprakeshverma** [learningequality/ka-lite#3218]
"Manage" Tab Giving the Runtime error  "maximum recursion depth exceeded"
Any Solutions?

![screenshot from 2015-03-11 00 14 01](https://cloud.githubusercontent.com/assets/10394619/6582691/fe43cdea-c784-11e4-8913-3f0444d33f04.png)

**Comment by aronasorman** [comment]
Can you copy the full stack trace here @sharprakeshverma?

**Comment by aronasorman** [comment]
Also, what version of the software are you using?

**Comment by sharprakeshverma** [comment]
http://dpaste.com/0PPFG1F - Traceback

**Comment by rtibbles** [comment]
Expired. What branch was this on, master or develop?

**Comment by rtibbles** [comment]
Unable to replicate this on either master or develop, on existing and fresh installs.

More info needed.

**Comment by sharprakeshverma** [comment]
Develop branch.

**Comment by aronasorman** [comment]
Can you send us the exact git commit you're on, as well as your database?

**Comment by sharprakeshverma** [comment]
19b1a64- git commit
and branch is 0.13.0

On Thu, Mar 12, 2015 at 9:17 PM, Aron Fyodor Asor <notifications@github.com>
wrote:

> Can you send us the exact git commit you're on, as well as your database?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/learningequality/ka-lite/issues/3218#issuecomment-78507220>
> .
>

Running syncdb will create a file in this directory called "data.sqlite". This contains all the data for the local server's database, including the public and private keys, and hence must be kept secret and not shared across servers. If copying this codebase to another server, delete the 'data.sqlite' file and re-run the installation script.

**Comment by rtibbles** [comment]
Can you try to replicate on the latest develop branch? I am unable to do so.

**Comment by rtibbles** [comment]
As this is on an old branch (0.13 which was last updated in November) and I am unable to replicate it, I am going to close for now, can reopen if replication is evidenced.

**Comment by sharprakeshverma** [comment]
Should i reinstall ka-lite for development work?

**Comment by aronasorman** [comment]
Yup @sharprakeshverma, and check out the develop branch too to make sure you're working on the latest code.
