### ISSUE TITLE
Sidebar rendering bug

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3221]
Browser: Firefox 35
Branch: latest develop as of 10 Mar 2015 13:12 PST
Language: German

![screen shot 2015-03-10 at 1 11 46 pm](https://cloud.githubusercontent.com/assets/191955/6584264/398b5ac0-c727-11e4-8744-eb8ff38a2498.png)

Opening the exercise given in the url, and then opening the sidebar makes the CSS all wrong. The scrollable area only extends up to a certain point, not the entire sidebar.

**Comment by MCGallaspy** [comment]
The problem is that the height of the scrollable content in the columns is fixed (at the window height), so it doesn't change when you scroll.

**Comment by MCGallaspy** [comment]
Fixed by #3606.
