### ISSUE TITLE
Back arrow not in center

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3222]
Branch: develop
Browser: Firefox 35

![screen shot 2015-03-10 at 1 16 06 pm](https://cloud.githubusercontent.com/assets/191955/6584336/beb8f612-c727-11e4-8461-be1697828cc1.png)

**Comment by aronasorman** [comment]
Was this intentional? @Antrikshy please verify.

**Comment by Antrikshy** [comment]
Totally intentional. I thought putting it in the center would make it look weird with the sidebar tab in the center as well.

**Comment by MCGallaspy** [comment]
I'm okay with this. Perhaps someone else can weigh in, before I close this issue. @66eli77? @jtamiace?

**Comment by aronasorman** [comment]
Sounds good. Closing this now, let's reopen if @66eli77 or @jtamiace feel the need to rectify this issue.
