### ISSUE TITLE
ImportError on coachreports

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3224]
Browser: Firefox 35
Branch: develop

Giving these specific parameters for a coachreport:
![screen shot 2015-03-10 at 1 22 26 pm](https://cloud.githubusercontent.com/assets/191955/6584456/afdc0c78-c728-11e4-9741-30e578a3de2c.png)

Gives me this error:
![screen shot 2015-03-10 at 1 24 21 pm](https://cloud.githubusercontent.com/assets/191955/6584469/d212e794-c728-11e4-8287-c2b06bb82180.png)

**Comment by MCGallaspy** [comment]
Try as I might, I can't seem to reproduce this error. I'm on the same code path, but that import statement doesn't blow up my server. That said, I moved those de-inlined those imports and resolved a circular import error that resulted -- probably why someone was importing there in the first place? PR incoming.

**Comment by rtibbles** [comment]
I think if you are running the manage.py inside the kalite folder, then it will work, if you are using the manage.py in the root folder, this will not. The relative import (with no 'kalite.' in front of 'controlpanel.api_resources') I think is the cause here.
