### ISSUE TITLE
Weird spacing and whitespace in coachreport legend for German

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3225]
Branch: develop
Browser: Firefox 35

![screen shot 2015-03-10 at 1 25 46 pm](https://cloud.githubusercontent.com/assets/191955/6584492/0bee7898-c729-11e4-849a-578551b3c4fb.png)

**Comment by aronasorman** [comment]
Check to make sure that it's not something with the i18n strings.

**Comment by MCGallaspy** [comment]
Resolved.
