### ISSUE TITLE
Tabs are just a tiny bit off

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3226]
Browser: Firefox 35
branch: develop

A few pixels to the bottom of the green line:
![screen shot 2015-03-10 at 1 27 44 pm](https://cloud.githubusercontent.com/assets/191955/6584560/635fe1de-c729-11e4-849a-6dc09f782caf.png)

**Comment by tarunsharma1** [comment]
Looks fine in mine..is it language dependent or something?
![screenshot 107](https://cloud.githubusercontent.com/assets/8834964/6609970/179cab4a-c87f-11e4-8f34-5e795c701abe.png)

**Comment by aronasorman** [comment]
I'm using Firefox @tarunsharma1

**Comment by tarunsharma1** [comment]
The image at the back is firefox and the one on top is chrome..
![screenshot from 2015-03-11 18 26 33](https://cloud.githubusercontent.com/assets/8834964/6610426/4db4dd78-c81c-11e4-851b-5f7930ce2a38.png)

**Comment by aronasorman** [comment]
Oh interesting, looks like it's a language thing then? You can try downloading German as an administrator, then test it there (just make sure you have `DEBUG = True` in your `local_settings.py`).

**Comment by phiju123** [comment]
I will check it

**Comment by aronasorman** [comment]
Not a priority; reopen if replicated in another computer.
