### ISSUE TITLE
I have internet yo; why are you giving me this error?

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3228]
Branch: develop
browser: Firefox 35
language: German

I have internet, and I can visit google. But why am I getting a "No internet" error? (@jamalex said that's what it translates to)

![screen shot 2015-03-10 at 1 35 46 pm](https://cloud.githubusercontent.com/assets/191955/6584753/b9a469d8-c72a-11e4-9299-aa6d259f06a6.png)

**Comment by aronasorman** [comment]
Was running my own central server. If not reproducible, let's just close this.

**Comment by MCGallaspy** [comment]
Just to be clear, @aronasorman had an internet connection, but his `kalite/local_settings.py` file was configured to look for a local instance of the central server (something like this):
```python
CENTRAL_SERVER_HOST   = "127.0.0.1:8000"
```
Which he wasn't running; hence "no internet error". Maybe a more accurate error would be "Could not detect central server." Should we suggest the user checks their `settings.py` or `local_settings.py`?

**Comment by aronasorman** [comment]
Yeah, that's a more accurate message. 0.14.
