### ISSUE TITLE
Language pack download button floating awkwardly

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3229]
browser: Firefox 35
branch: develop

![screen shot 2015-03-10 at 1 40 55 pm](https://cloud.githubusercontent.com/assets/191955/6584824/301fb996-c72b-11e4-974a-1f0be084ec76.png)

**Comment by anuragkanungo** [comment]
Hey, @Antrikshy , can you have a look, you have better UI experience.
Thanks
