### ISSUE TITLE
"Please select topic" should not be an error message

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3230]
branch: develop
browser: Firefox 35

![screen shot 2015-03-10 at 1 42 43 pm](https://cloud.githubusercontent.com/assets/191955/6584884/8dffd802-c72b-11e4-90c7-ac494117591b.png)

I feel this should just be a normal (yellow-colored) notif

**Comment by rtibbles** [comment]
:+1: I have too, felt this was unnecessarily aggressive.
