### ISSUE TITLE
Tabs can't handle long words

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3233]
branch: develop
browser: Firefox 35

Exhibit A
![screen shot 2015-03-10 at 1 52 59 pm](https://cloud.githubusercontent.com/assets/191955/6585087/de630796-c72c-11e4-8054-ad5bfa897cb2.png)

**Comment by phiju123** [comment]
Sir I m not getting the css file
Can u pls suggest it. As im newbie in python.

**Comment by aronasorman** [comment]
I'm not aware of where the best place is to fix this as well. However @phiju123 one good place to find out is through the chrome devtools: https://developer.chrome.com/devtools/docs/elements-styles

That allows you to edit the styling in-place, and once you do fix it you can find out what file that style is placed.

**Comment by foolchan2556** [comment]
Hi, in addition to @aronasorman 's advice, I guess Inspect Element function in your right-click menu of Chrome might help, which will figure out the path of each style clause. Hope it will be helpful :)
