### ISSUE TITLE
"Learn" link in homepage no longer accurate

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3234]
branch: develop

![screen shot 2015-03-10 at 1 55 00 pm](https://cloud.githubusercontent.com/assets/191955/6585138/34b44876-c72d-11e4-801d-e74fb14f8ed8.png)

Say, we don't really have a knowledge map now do we? So this picture we have in the front page is not totally accurate then.

**Comment by Antrikshy** [comment]
Maybe we should come up with a large, clean, image-less learn button. I'll play around.

**Comment by 66eli77** [comment]
I don't see the necessity of having this page, I think the first page to land should be the learn page, and in the future, the recommend page.

**Comment by aronasorman** [comment]
I see where @66eli77 is coming from. We've unified exercises and videos into a single "Learn" page interface, and so there's no need to ask them what they want to do when they first load KA Lite -- as a guest user, really the only useful thing you can do is go straight to learning!

However, removing the front page requires significant code changes, which we should avoid now that we're so close to release.

**Comment by 66eli77** [comment]
@aronasorman  is it possible to set a redirect on this page that always point to learn? as a compromised solution for now?

**Comment by Antrikshy** [comment]
But but... pretty button design!

**Comment by Antrikshy** [comment]
Here's a draft for a simpler button that people will see when they are not logged in: http://gyazo.com/4c5f49b94bc6f8c7630c7e89545faa6a

People who are logged in will most likely not hit this page. See #3273.

**Comment by 66eli77** [comment]
fixed
