### ISSUE TITLE
Nalanda conditionals still showing up

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3235]
browser: Firefox 35
branch: develop
DB: a Nalanda DB

So even if we made a PR "stripping off" Nalanda features from develop, some of it's still showing up:
![screen shot 2015-03-10 at 2 01 38 pm](https://cloud.githubusercontent.com/assets/191955/6585315/43f1b2f0-c72e-11e4-8d62-a758401b8ef8.png)

Note the condition message and the store link.

Steps to reproduce:
1. Acquire nalanda db
2. check out develop
3. log in as a student

**Comment by aronasorman** [comment]
How's this going @anuragkanungo

**Comment by anuragkanungo** [comment]
@aronasorman
Also, if we disable CONFIG_PACKAGE="Nalanda", this conditions should not show up.
When I try with nalanda DB, I get this error:

×Unexpected error: no such table: main_contentlog

**Comment by aronasorman** [comment]
@anuragkanungo doesn't that mean that you just need to migrate your DB?

**Comment by anuragkanungo** [comment]
Yup migration helps, and the error goes but there are lot of errors with the Nalanda Db, for example :
![screenshot from 2015-03-20 22 05 39](https://cloud.githubusercontent.com/assets/4207886/6756053/5ecc8dd0-cf4d-11e4-9e3d-0d7508713257.png)

**Comment by aronasorman** [comment]
Even with an existing PR from @anuragkanungo, I can't seem to replicate this anymore. I think it's been removed through attrition.
