### ISSUE TITLE
"Inequalties"?

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3236]
branch: develop

![screen shot 2015-03-10 at 2 05 13 pm](https://cloud.githubusercontent.com/assets/191955/6585347/87e9f832-c72e-11e4-865c-2f1a8658cb21.png)

We might wanna manually correct this in the khan topic tree JSON.

**Comment by anuragkanungo** [comment]
@aronasorman , can you explain the problem, please.

**Comment by aronasorman** [comment]
Inequalties is a misspelling. It should be "Inequalities" (with an "i").

The problem is most likely in one of our Khan data jsons.

**Comment by rtibbles** [comment]
Might be good to fix this at the source, and let KA know?

**Comment by rtibbles** [comment]
Live on their site at:
https://www.khanacademy.org/math/pre-algebra/applying-math-reasoning-topic

![image](https://cloud.githubusercontent.com/assets/1680573/6602952/267264a0-c7dc-11e4-9298-8fad758f15bc.png)

**Comment by anuragkanungo** [comment]
@rtibbles , that would be the best. let them know. :-)

**Comment by rtibbles** [comment]
Fixed in #3260

**Comment by jamalex** [comment]
Reported to KA.

**Comment by jamalex** [comment]
Aaaaaand fixed on KA's side:
https://www.khanacademy.org/math/pre-algebra/applying-math-reasoning-topic/greater-than-less-than/v/greater-than-and-less-than-symbols
