### ISSUE TITLE
Strange mix of translated and not translated strings when logged in as student

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3238]
branch: develop
db: Nalanda DB (if that's relevant)
browser: Firefox 35
active language: German

When logged in as student, I get this:
![screen shot 2015-03-10 at 2 08 51 pm](https://cloud.githubusercontent.com/assets/191955/6585490/80e33886-c72f-11e4-8231-5711af5948b2.png)

Notice the German center text, but what is otherwise an English interface (navbar german strings are present in the po file). Default language is German.

Also, the topic tree isn't translated:
![screen shot 2015-03-10 at 2 13 47 pm](https://cloud.githubusercontent.com/assets/191955/6585536/b1b2ff3c-c72f-11e4-9753-1e11dbbec7a9.png)

My hunch is that the current student's default language is English (despite the system wide default being German), but somehow that center text is still getting translated to German.

**Comment by aronasorman** [comment]
@rtibbles maybe you might know what's wrong with this. Can you advise?

**Comment by cpauya** [comment]
This also happens even when I'm logged-in as an admin and have English as my language, checking it out now:

![screenshot 2015-03-11 15 37 12](https://cloud.githubusercontent.com/assets/175580/6592148/9d0a0d34-c804-11e4-872b-0e9527025ca7.png)

**Comment by cpauya** [comment]
Sorry, I had German set as my language on another browser, the above comment is wrong, will try to reproduce this issue now.
