### ISSUE TITLE
typo in the docs -- Raspberry Pi Installation Guide

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#3240]
in this page http://field.learningequality.org/docs/installguide/install_rasp_pi.html
there are couple places where "ka-lite-pi/scripts" should be "ka-lite-pi-scripts".

**Comment by MCGallaspy** [comment]
@66eli77 is this fixed by #3251?

**Comment by 66eli77** [comment]
@MCGallaspy  yes, please close this issue.
