### ISSUE TITLE
student report tooltip too tight

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3241]
branch: develop
browser: Firefox 35

![screen shot 2015-03-10 at 2 25 10 pm](https://cloud.githubusercontent.com/assets/191955/6585768/72dbd548-c731-11e4-9e86-dd31f174a08d.png)

Makes it a bit harder to read.

**Comment by tarunsharma1** [comment]
too tight as in you want the width to be increased?

**Comment by 66eli77** [comment]
progress report need a overall UI refactoring
