### ISSUE TITLE
Broken exercise

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#3242]
On `develop`, the exercise at `/learn/khan/computing/computer-programming/programming/variables/exercise-intro-to-variables/` is broken. When submitting an answer, correct or incorrect, results in the exercise question area becoming blank, and subsequent button clicks have no effect. It's also not clear what the answer format should be for many of the questions.

**Comment by aronasorman** [comment]
The exercise is working for me on the latest 0.13.x and develop branch. Closing.
