### ISSUE TITLE
No way to show all the results in the search page

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3244]
branch: develop

So we limit the number of results for each content type to 25 items, but then how do I see all the results? There's no button anywhere to expand the search to more than 25 items.

![screen shot 2015-03-10 at 2 34 21 pm](https://cloud.githubusercontent.com/assets/191955/6585937/e1f6c6a8-c732-11e4-82eb-79bef06d8c00.png)

Steps to reproduce:
1. Search "mat" in search box and press enter before autocomplete shows up.

**Comment by tarunsharma1** [comment]
@alexkchan Hey Alex, I have been looking into this issue for a couple of days now and have started working on it..I was hoping we could coordinate and discuss possible solutions :)

**Comment by alexkchan** [comment]
@tarunsharma1 Hey Tarun :) ! Awesome, I haven't had as much time to work on this as I wanted to. Aron suggested that we use Django Pagination (https://docs.djangoproject.com/en/1.5/topics/pagination/). I got as far as identifying that the search method is in views.py (def(search)) and it looks like we want to paginify the 'possible_matches' return. Right now I'm working on trying to understand how to use the 'possible_matches' return such that we can use Pagination. What kind of solutions were you exploring ?

**Comment by tarunsharma1** [comment]
Hey @alexkchan ,
So far i just identified that the value 25 for search limit is being given in views.py , I tried adding a button in search_page.html and sending a response through <form> and then change the value of max_results_per_category accordingly...this isnt a very efficient solution though as it would be difficult to identify which categories button was clicked unless we use an array of ids and also send the id...Another issue i faced in this solution was that the views.py is written such that it gives an error if there is no query specified. To overcome that, I will have to resend query in the form along with id... Didnt know about  Pagination..Ill look into that as well now :)

**Comment by tarunsharma1** [comment]
through form*

**Comment by rtibbles** [comment]
Taking this over.

**Comment by rtibbles** [comment]
Fixed in #3797
