### ISSUE TITLE
accessing exercise from progress report leads to incorrect sidebar behavior

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#3245]
![screen shot 2015-03-10 at 3 03 52 pm](https://cloud.githubusercontent.com/assets/5577205/6586444/b6058026-c736-11e4-8b10-904fc8049538.png)
reproduce:
1.login as learner;
2.go to progress report(make sure you have something to choose)
3.open any drop down list and choose an exercise from it
you will see the sidebar fade are isn't fading, and the sidebar-tab is in 'close' state even though the sidebar is open

**Comment by Antrikshy** [comment]
Something is calling the resize sidebar function, but not the main one. This is a strange issue because I have added a check to see if the sidebar is in open state before calculating its position. Assign this to me and I'll check it out.

**Comment by rtibbles** [comment]
I assume this bug will actually be more general, and will happen any time you navigate directly to the URL for an exercise.

**Comment by Antrikshy** [comment]
This is one annoying bug.

**Comment by Antrikshy** [comment]
Fixed with a `_.debounce` similar to what we use for `resize_sidebar`. I hope it doesn't cause other problems. I'll send this over in a PR with a couple other issues fixed.

**Comment by 66eli77** [comment]
we need to refactor the sidebar code in near future to take full advantage of Backbone MV's listener feature, so that we can avoid using any delay function like _.debounce(not reliable).

**Comment by Antrikshy** [comment]
@66eli77 is right. While I think we can keep this quick and dirty fix for now, the sidebar code could do with some heavy refactoring. `_.debounce` is being used in three places total. Perhaps we should look into what that function actually does. At least I *think* it adds a delay. Who knows, it might be reliable.

Anyways, I'll be very busy over the next week because of finals week. I'll work on a couple bugs and submit a PR over the weekend.

**Comment by rtibbles** [comment]
@Antrikshy for reference, this is what it does: http://underscorejs.org/#debounce

**Comment by jamalex** [comment]
@Antrikshy When you said "weekend", did you mean last weekend? Could we just get your quick and dirty fix in for now, so we can test it?

**Comment by Antrikshy** [comment]
Sorry I did mean last weekend. I'll send a PR in a couple of hours. I have two of those blockers fixed I think.

Antriksh Yadav
