### ISSUE TITLE
Remove ugly hash from beside logged-in username

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3249]
We added this 8-digit hash just for paper survey tracking purposes for Nalanda. Probably no use for it in general, and it's ugly/distracting, so let's ditch it.

![image](https://cloud.githubusercontent.com/assets/618416/6587761/b7904e30-c745-11e4-84b1-4e34c9820661.png)

**Comment by jamalex** [comment]
Could you take a look, @anuragkanungo?

**Comment by 66eli77** [comment]
@jamalex  @anuragkanungo  you can assign to me this issue, I fixed this on my personal branch yesterday.

**Comment by anuragkanungo** [comment]
@66eli77 , If you have fixed it then please go ahead take this issue and open the PR.
Thanks.

**Comment by 66eli77** [comment]
@aronasorman  this has been fixed at PR #3251, please close the issue
