### ISSUE TITLE
404 after editing and saving the Default facility properties

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#3271]
Branch: develop
Expected Behavior: After setting the location in Google map and editing the facility name, pressing the "Save facility" button should bring back to Manage tab dashboard.
Current Behavior: Pressing the "Save facility" button leads to 404 page:

>Page not found (404)
>Request Method: 	POST
>Request URL: 	http://127.0.0.1:8008/management/zone/None/facility/30c1fcf59a2e4848b7f76269dcbce002/edit

>No Zone matches the given query.

>You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.

Steps to reproduce:

1. Log in as the administrator.
2. Click the pencil icon to edit the Default facility
3. Add a Google map location
4. Edit the Name field
5. Press the "Save facility" button

**Comment by rtibbles** [comment]
Taking this over.

**Comment by rtibbles** [comment]
This bug goes deeper than I ever expected.

We actually have two entirely parallel views and templates for creating and editing facilities. Even though they look identical.

**Comment by radinamatic** [comment]
Me and my talent to step into the deep mud... ;)
