### ISSUE TITLE
Plans for new KA Lite landing page

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3273]
Current landing page doesn't serve much of a purpose.

One proposal for the behavior of the landing page:
- When not logged in: Show login form and signup form directly.
- When logged in as learner: Redirect to Learn tab (sidebar, or later, rec engine)
- When logged in as coach: Redirect to Coach tab (coach reports)
- When logged in as admin: Redirect to Manage tab

(this would mean that the KA lite logo would then auto-redirect to the pages mentioned above too -- and when logging in, it could just send to the landing page URL which would redirect appropriately, which simplifies things)

**Comment by aronasorman** [comment]
Assigned you to this @Antrikshy since you said you were meaning to make this.

**Comment by Antrikshy** [comment]
We refreshed the home page a little bit earlier this quarter, so I think this can be closed.

**Comment by aronasorman** [comment]
Homepage now has content recommendation too. :dancers:
