### ISSUE TITLE
Ask user if they have a local assessment zipfile

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3275]
To be able to handle completely offline installations, users installing through Git should be made aware through a message that:
1. There is now this big zip file they have to download
2. What the URL is to that zip file (so they can download it)
3. Whether they have a local copy of that zip file.

**Comment by MCGallaspy** [comment]
Are you suggesting this as an amendment to the docs, @aronasorman? Not sure if there's a more appropriate way to let users know.

**Comment by aronasorman** [comment]
The idea is to have a prompt in the setup command that shows a warning that we need the assessment items, and asks if they have a local copy or not.

**Comment by aronasorman** [comment]
but we also need to tell them in the release notes, and the install guide.

**Comment by aronasorman** [comment]
can put them in the same PR.
