### ISSUE TITLE
Accessibility issue colour 

### ISSUE THREAD

**Issue by Nat-Turner** [learningequality/ka-lite#3276]
for people with colour blindness it is hard to distinguish between "the blue" and "the orange" angles.

![light-bulb-clip-art](https://cloud.githubusercontent.com/assets/10179162/6629526/c39d0138-c906-11e4-90be-81c3dee55428.jpg)

just labeling the angles would fix this 
or change the colour of the text of "orange" to orange 
like in this exercise (so that people with colour blindness can match the shade of the word with the shade of the angle)
![colour3](https://cloud.githubusercontent.com/assets/10179162/6629528/d1480634-c906-11e4-9102-80a67b760ed3.jpg)

**Comment by aronasorman** [comment]
This is more of Khan Academy's issue, as we just import the exercises from them. Closing this now. But @jamalex let's inform about colorblindness issues like this one.

**Comment by jamalex** [comment]
Very important issue, but not one that we (as FLE) can address directly, as we're just pulling in KA's exercise content. A good place to report this would be at: https://code.google.com/p/khanacademy/issues/list
