### ISSUE TITLE
Score for quiz not visible.

### ISSUE THREAD

**Issue by sopu** [learningequality/ka-lite#3279]
The score display during the quiz is not completely visible due to color issues.
Need to change the color palette for progress bar.
![screenshot from 2015-03-13 18 49 50](https://cloud.githubusercontent.com/assets/6399612/6639045/1cbb3ec8-c9b2-11e4-8020-f5a040820c09.png)

As can be seen in the screenshot.

**Comment by tarunsharma1** [comment]
Or maybe change the color of the text (points) from white to black?

**Comment by sopu** [comment]
I am not quite convinced with the way the progress bar looks. The color doesn't fit with the basic color scheme of the page.

**Comment by rtibbles** [comment]
Fixed in #3294
