### ISSUE TITLE
The values of scorecard and number of "correct" icons do not match

### ISSUE THREAD

**Issue by sopu** [learningequality/ka-lite#3295]
Whenever I enter a wrong answer it gives a "cross".
Then if I enter the correct answer it still gives a "cross" but the score increases.
Screenshot
![screenshot from 2015-03-14 05 54 12](https://cloud.githubusercontent.com/assets/6399612/6649381/e1c47a0c-ca0e-11e4-849b-e38cfe24a28b.png)

In the next question if I choose the correct alternative it suddenly changes the "cross" to a "tick" and increases the score.
Screenshot
![screenshot from 2015-03-14 05 56 44](https://cloud.githubusercontent.com/assets/6399612/6649382/ec6c6c6c-ca0e-11e4-822b-09456e9ae24e.png)

**Comment by sopu** [comment]
Looks to me like some kind of bug. But if is intended to be so then please explain the logic behind it.

**Comment by rtibbles** [comment]
This appears to have been done while logged in as an admin. Admin progress data is not saved to the server, and hence the indicators are not reliable. Please confirm that this happens on a student account (I have been unable to replicate it on student accounts).

**Comment by aronasorman** [comment]
Closing.
