### ISSUE TITLE
Readability issue: The text in search auto-complete is not aligned properly

### ISSUE THREAD

**Issue by sopu** [learningequality/ka-lite#3303]
Branch: `develop`
Text in new line is not indented and thus appears below the icon which reduces readability of the topics displayed in the drop-down.

What should happen: All the line should be indented below the first line.

Screenshot
![screenshot from 2015-03-15 18 01 12](https://cloud.githubusercontent.com/assets/6399612/6656023/7b9c4642-cb3f-11e4-886c-4b3775f8881c.png)

**Comment by sopu** [comment]
@aronasorman I have given a pull request on this issue (#3304). Please see.

**Comment by MCGallaspy** [comment]
Fixed.
