### ISSUE TITLE
browser_check_django_message no longer works correctly with num_messages=0

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3307]
There are several tests on ka-lite-central that call `browser_check_django_message` with `num_messages=0`, in order to assert that no alerts were displayed.

The added line:
`WebDriverWait(self.browser, 30).until(EC.presence_of_element_located((By.CLASS_NAME, "alert")))`
is not set up to handle this case, and hence pauses 30 seconds before failing out.

It's uncertain how long should be waited in order to check for lack of alert messages, but perhaps we could get away with skipping that `WebDriverWait` line if `num_messages=0`?

**Comment by jamalex** [comment]
See https://travis-ci.org/fle-internal/ka-lite-central/builds/54519584#L439 for failures.

**Comment by MCGallaspy** [comment]
This should be a straightforward fix, but this test failure slipped under the radar because it's on the central server. Is it possible to move this test into the included submodule?
