### ISSUE TITLE
How to download only Arabic videos?

### ISSUE THREAD

**Issue by yohanboniface** [learningequality/ka-lite#3308]
Hi :)

I've installed Arabic language pack and set Arabic as default language.

Now I'm not sure if the videos from the '/update/videos/' page will all be in Arabic or not.

I've downloaded the first two, and they both are in Arabic, but before downloading all the Go, I want to be sure I'm targeting only Arabic ones :)

Also: is there a .torrent link to get them (only Arabic) in bulk?

Thanks!

Yohan

**Comment by aronasorman** [comment]
Hi Yohan, Unfortunately there's no torrent link for Arabic yet.

Returning to your original question, Yup, if it's set as the default language then it should automatically download that default language.
