### ISSUE TITLE
Details on download error?

### ISSUE THREAD

**Issue by yohanboniface** [learningequality/ka-lite#3310]
When there is an error while downloading videos, we have a gentle message that warn us about this fact, which is nice:

![screenshot from 2015-03-16 22 18 18](https://cloud.githubusercontent.com/assets/146023/6676770/b157a7f4-cc2a-11e4-9627-b9739a8eb929.png)

but having a bit more details (file unavailable? network issue? missing space on device?…) would be very useful :)

**Comment by aronasorman** [comment]
Agreed, finding the middleground between opaque stacktraces and vague errors like these is an interesting issue to tackle.

**Comment by anuragkanungo** [comment]
@aronasorman ,
This is related to extending this PR 
#3181

**Comment by rtibbles** [comment]
Should be mitigated by #4784

**Comment by benjaoming** [comment]
Closing this in favour of #4892
