### ISSUE TITLE
sidebar handle overlaps the text field when resize the window to its minimum width

### ISSUE THREAD

**Issue by shubhendras1992** [learningequality/ka-lite#3315]
Branch - develop 

1. There are possible ways to fix this. Either repositioning of sidebar handle to the top or bottom, so its     wont overlap the text field.

2.By changing its padding-left attribute. 
![screen shot 2015-03-17 at 12 48 36 pm](https://cloud.githubusercontent.com/assets/9433264/6682798/80d0eedc-cca3-11e4-87ca-26c9756e90aa.png)

**Comment by mjptak** [comment]
Awesome to see someone looking at how the exercises can become more small
screen friendly!  Moving the submit button to the bottom would in my
experience greatly increase the user experience for a large number of the
exercises...especially the "rote" ones.

**Comment by 66eli77** [comment]
my two cents
![screen shot 2015-03-17 at 9 53 43 am](https://cloud.githubusercontent.com/assets/5577205/6692717/99173f18-cc8b-11e4-9a2b-76bc9f49caee.png)
![screen shot 2015-03-17 at 9 54 01 am](https://cloud.githubusercontent.com/assets/5577205/6692720/9c1d98ba-cc8b-11e4-9d3d-0f1b505c0514.png)

**Comment by rtibbles** [comment]
I agree with @mjptak that we should look at the responsiveness of the exercise template as well. @66eli77 or @jtamiace could we think about this for 0.14?

**Comment by shubhendras1992** [comment]
Do I fix it ?

**Comment by rtibbles** [comment]
@Antrikshy could you take a look at this?

**Comment by Antrikshy** [comment]
@rtibbles Sure.

**Comment by Antrikshy** [comment]
Should I make it move out of the way only on smaller screens, @rtibbles?

**Comment by rtibbles** [comment]
Yeah, that should work, I think. What happens to it when you click on the burger to expand the collapsed top nav?

**Comment by Antrikshy** [comment]
It overlaps. :(

I'll fiddle with it.

**Comment by Antrikshy** [comment]
@rtibbles Check out #3537!

**Comment by Antrikshy** [comment]
@MCGallaspy You can close this because #3537 was merged.
