### ISSUE TITLE
Strip empty description when we run contentload

### ISSUE THREAD

**Issue by sopu** [learningequality/ka-lite#3320]
Branch: develop

The value of title attribute for "Test prep" in sidebar is a space rather than NULL. 

What to be changed: Need to change the description for test-prep in topics.json to a NULL
 
Screenshot: 
![screenshot from 2015-03-17 11 37 25](https://cloud.githubusercontent.com/assets/6399612/6687132/c1c27a8a-cccd-11e4-98f9-778747df2986.png)

**Comment by jamalex** [comment]
This needs to be added to `contentload` (or probably `khan.py`), by running `strip` on descriptions when iterating through the tree, otherwise it will be overwritten when we rerun `contentload`. Re-opening to make sure we do that.

**Comment by aronasorman** [comment]
I've updated the title and moved it to 0.14.0.

**Comment by aronasorman** [comment]
@rtibbles can you make a fix for this?

**Comment by rtibbles** [comment]
Sure.

**Comment by rtibbles** [comment]
Fixed in #3754
