### ISSUE TITLE
Opportunistically update statusModel with every API request

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#3325]
At the moment our statusModel relies on a very small amount of data, and it would add little overhead to keep this updated by injecting this data into the response from every API call.

This will allow us to keep the statusModel properly tracking the server state (particularly of is_logged_in).

**Comment by rtibbles** [comment]
Could be accomplished in TastyPie by adding the two methods here to a Base class:
http://django-tastypie.readthedocs.org/en/latest/resources.html#alter-list-data-to-serialize

**Comment by jamalex** [comment]
> Could be accomplished in TastyPie by adding the two methods here to a Base class:
> http://django-tastypie.readthedocs.org/en/latest/resources.html#alter-list-data-to-serialize

Hmm, yeah, like you mentioned, might not be the best approach. Especially since we need to add it to every Resource, or add a mixin somewhere.

**Comment by MCGallaspy** [comment]
Is there an example you're thinking of in which StatusModel doesn't properly track the state? Not clear to me what's being proposed here, and I'm thinking about punting it to 0.15 as it appears to be more substantial than a bug fix.

**Comment by rtibbles** [comment]
Fogeddaboutit.
