### ISSUE TITLE
Git install migration process

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3335]
Milestone: 0.14

The end is nigh!

Once we have installers for the 3 most common platforms, we should create a migration process for Git installations.

Idea:
- The installer should ask the user if they have a git installation somewhere. If they specify one, we copy over the DB, uninstall KA Lite through the uninstall scripts found in the Git installation, then migrate the DB we just copied.

**Comment by rtibbles** [comment]
Fixed in #3789
