### ISSUE TITLE
Coachreports scatter reports and timeline reports "No learner accounts..." alert

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#3336]
On `develop`.
Expected behavior: Scatter reports and timeline reports should show a reports
Actual behavior: I get the alert "No learner accounts in this group have been created."
Steps to reproduce (here's what I did exactly):
1. Create new coach and learner accounts with a fresh db.
2. Attempt or complete a few exercises with the student (so that presumably something will be shown on the reports).
3. As the coach, navigate to the scatter report (/coachreports/scatter/?facility_id=&group_id=) or timeline report (/coachreports/timeline/?facility_id=&group_id=) with all facilities and all groups selected.
4. Presumably this should show data for the student's attempted/completed exercises, but instead it shows the above alert.

Doesn't seem to make a difference if the learner is assigned to a group or if specific facilities/groups are chosen in the dropdown menus.

**Comment by MCGallaspy** [comment]
Actually, it seems that the date range simply needs to be set *beyond* the current day. (It's not inclusive.)

**Comment by tarunsharma1** [comment]
#3457

**Comment by aronasorman** [comment]
Coachreports have been burned down in the latest develop.
