### ISSUE TITLE
Accessibility : Empty h3 tag over video title

### ISSUE THREAD

**Issue by sopu** [learningequality/ka-lite#3337]
branch - develop

An empty heading will present no information and may introduce confusion for keyboard users and screen reader users who navigate using heading information.
Screenshot:
![screenshot from 2015-03-19 04 53 28](https://cloud.githubusercontent.com/assets/6399612/6721561/64077512-cdf4-11e4-8c1f-f86608afba14.png)

Also found using WAVE tool as shown here:
![screenshot from 2015-03-19 04 58 08](https://cloud.githubusercontent.com/assets/6399612/6721574/92b9318e-cdf4-11e4-9e0f-a309446cdf91.png)

**Comment by georgyberdyshev** [comment]
Hello,

@rtibbles 
I have added a pull request #3442 fixing this issue.

Thanks in advance, Georgy

**Comment by rtibbles** [comment]
Fixed in #3442
