### ISSUE TITLE
We don't need no stinkin' sha's

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3340]
In exercises.json, each assessment item listing contains a long sha value. We don't use this, so removing it could reduce memory usage.

```
      "{\"sha\": \"91d6237a6b766e0f753384314de80a5abc88098e\", \"live\": true, \"id\": \"x70ce5cc5da1aacd5\"}",
      "{\"sha\": \"24b04624c4b74acda8b17999c5fa65098dcc7e3b\", \"live\": true, \"id\": \"xa9e3433e96411cbe\"}",
      "{\"sha\": \"4ebfdcaa481ca85b3ad2782401810c18a70fdc4d\", \"live\": true, \"id\": \"x6b7523fe550b90f3\"}",
      "{\"sha\": \"e7beff3c214ebf32b2803619ec13a3eb949009b4\", \"live\": true, \"id\": \"xc031ddaa330ff31a\"}",
      "{\"sha\": \"f33886cf5e783e3b654be62ed863981be5df9a91\", \"live\": true, \"id\": \"xf99cbec8639f7f13\"}",
      "{\"sha\": \"0078b700d8d9b78b3056e97c8ef70033454c00f3\", \"live\": true, \"id\": \"xedf313e72a1bad64\"}",
      "{\"sha\": \"4241836fde4d74e8957e8b02a8873fdfa5ab4479\", \"live\": true, \"id\": \"x3f3228fdc1cdcaef\"}",
      "{\"sha\": \"caac19b2ca4d1cd9481d5f3c78d060bc779c2792\", \"live\": true, \"id\": \"x84f9950885b34c89\"}",
      "{\"sha\": \"83a3f987b20d8ddfdd556a703551f8acaf0d8eb0\", \"live\": true, \"id\": \"xe54cd4000d38fbea\"}",
      "{\"sha\": \"788c23a0ba1a8a67cc247b55aa98e9d7e0f4860c\", \"live\": true, \"id\": \"x622d330c5a598e7a\"}",
      "{\"sha\": \"f1c96a8b964d3eea6f602decdc938964f6f171d9\", \"live\": true, \"id\": \"xb446f3a762e8c0ed\"}",
```

**Comment by jamalex** [comment]
`live` can probably go too, since we should just filter out any that aren't live.

**Comment by aronasorman** [comment]
![image](https://cloud.githubusercontent.com/assets/191955/6722304/b30bc3c6-cd94-11e4-9203-471d6493b036.png)


If we do still read this in memory, then this certainly deserves looking at for optimizations. If we whitewash these fields, then this isn't too urgent for me.

**Comment by jamalex** [comment]
> If we whitewash these fields, then this isn't too urgent for me.

Whitewash as in "remove"? Are you saying if we solve it, then it isn't urgent? :confused:

**Comment by MCGallaspy** [comment]
#3639 removes some apparently unused fields.

**Comment by aronasorman** [comment]
Has this been resolved @MCGallaspy?

**Comment by MCGallaspy** [comment]
ORMified assessment items ditched several unused fields, so yes. Any ORMification in the future should also choose which fields to keep.
