### ISSUE TITLE
Bug: auto-suggestion search bar not working properly when using keyboard navigation keys

### ISSUE THREAD

**Issue by shubhendras1992** [learningequality/ka-lite#3349]
branch - develop 

Current behaviour - The auto-suggestion search bar not working properly, when using keyboard   navigation keys. I think it displays the name of exercise which is saved in the local directory.

Expected behaviour - It should display the name of exercise which is given on the web. And should navigate to the correct result.

As you can see in the screenshot,  name of the exercise is "Introduction: exploring college options" but It doesn't shows the same thing above.  

![screen shot 2015-03-20 at 12 28 33 am png](https://cloud.githubusercontent.com/assets/9433264/6738612/36422410-ce99-11e4-8019-c774f634251d.jpg)

Another screenshot:
![screen shot 2015-03-20 at 12 50 49 am png](https://cloud.githubusercontent.com/assets/9433264/6738727/e7b6627e-ce99-11e4-9c5e-ce65a93dd1a2.jpg)

Screenshot of buggy result:
![screen shot 2015-03-20 at 12 30 42 am](https://cloud.githubusercontent.com/assets/9433264/6738795/542bc732-ce9a-11e4-8d88-f7114e0de88f.png)

**Comment by georgyberdyshev** [comment]
@rtibbles I am working on this issue.

**Comment by georgyberdyshev** [comment]
Hello everyone,

@rtibbles 
I have added a pull request #3477 fixing this issue.

Adding screenshot of the fix, showing the updated search box text on focus.
![search input focus fixed](https://cloud.githubusercontent.com/assets/67566/6991325/a8f9e3ee-da8d-11e4-90c6-6884228084ed.png)


Thanks in advance, Georgy

**Comment by rtibbles** [comment]
Fixed in #3766
