### ISSUE TITLE
Accessibility Issue - images without alt attribute.

### ISSUE THREAD

**Issue by Roomka** [learningequality/ka-lite#3351]
<plaintext>
<img src="/static/img/ka-lite/python-powered.png" class="img-responsive community-icons">
<img src="/static/img/ka-lite/studentuser_laptop.png" class="img-responsive community-icons">
<img src="/static/img/ka-lite/cloud_server.gif" class="img-responsive community-icons">
<xmp>
<img src="/static/img/ka-lite/translate.png" class="img-responsive community-icons">
<img src="/static/img/ka-lite/facebook.png" class="img-responsive community-icons">
<img src="/static/img/ka-lite/donate.png" class="img-responsive community-icons">
<img src="/static/img/ka-lite/usage_map.png">
<img src="/static/img/ka-lite/Burma.jpg">
<img src="/static/img/ka-lite/Nalanda.jpg">
<img src="/static/img/ka-lite/Washington.jpg">
<img src="/static/img/ka-lite/faq.png">
<img src="/static/img/ka-lite/forum.png">
<img src="/static/img/ka-lite/github.png">
<img class="img-responsive" src="/static/img/ka-lite/windows.png">
<img class="img-responsive" src="/static/img/ka-lite/linux.png">
<img class="img-responsive" src="/static/img/ka-lite/apple.png">
<img class="media-link" src="/static/img/facebook.png"/>
<img class="media-link" src="/static/img/twitter.png"/>
</xmp>
Page  - https://learningequality.org/ka-lite/

**Comment by rtibbles** [comment]
For future reference: https://github.com/learningequality/ka-lite/wiki/Report-Bugs-by-Creating-Issues#issue-format

However, this repo is for the KA Lite app, not the Learning Equality homepage. See here: https://github.com/fle-internal/fle-home

**Comment by Roomka** [comment]
Thank you rtibbles, I didn't pay attention, my bad!
