### ISSUE TITLE
Accessibility Issue  - SVG Accessibility

### ISSUE THREAD

**Issue by Roomka** [learningequality/ka-lite#3355]
Branch: Master
Expected Behavior: Provide a <title> element and eventually a <desc> element with appropriate description to differentiate the different  svg elements as well as provide an alternative text description.
http://www.w3.org/TR/SVG/access.html H2.SVG
http://www.w3.org/TR/2000/NOTE-SVG-access-20000807/
Current Behavior: Provided a <desc> element used to describe the author of the svg.

**Comment by jamalex** [comment]
Is this referring to the SVGs in the exercises? If so, we don't have any control over these, and the issue will need to be opened on https://github.com/Khan/perseus (with some concrete examples).
