### ISSUE TITLE
Layout resize elements overlap

### ISSUE THREAD

**Issue by Roomka** [learningequality/ka-lite#3357]
Branch: Master
Expected behavior: during browser resize menu elements overlaps.
Correct Behavior: elements stay in the same order without overlaps.

![resize](https://cloud.githubusercontent.com/assets/4850405/6744053/6bd76856-cea3-11e4-85ac-f0599383cec4.png)

**Comment by MCGallaspy** [comment]
Looks like 0.12.x. Recommended solution is to upgrade!
