### ISSUE TITLE
Language specific installers

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#3359]
Not sure which installers Repo this should go on, but after discussion with @aronasorman and @cpauya it occurred that having installers available with a particular language pack prebundled would be advantageous for our users.

**Comment by MCGallaspy** [comment]
@aronasorman @cpauya can it be done?

**Comment by cpauya** [comment]
Yes I think this is possible because we can run the management commands on
the build server to package a specific language in the `ka--lite` folder.

**Comment by benjaoming** [comment]
This will be solvable once the import/export command is in place, which will make in possible to import preseeded folder with a languagepack #4311

**Comment by benjaoming** [comment]
Well, this is not happening in a near future, it requires lots of building resources, and we need to have a more automated release process to manage this.

If it's to happen, this issue should be opened in the installers repo anyways.
