### ISSUE TITLE
Facility and group lookups in coach report views are badly scoped and inefficient

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3360]
Expected: Time spent loading a coach report page should be proportional to number of records being matched/returned.

Observed: The tabular report (as an example; probably true of others) calls `get_accessible_objects_from_logged_in_user`, which loads all groups and facilities for which the currently logged in user has permissions, even if the user is only requesting data for a single facility. On the central server, this means 10's of thousands of records being returned, and it then takes multiple minutes to render the page with these huge dropdown lists.

Proposal: The data for the facility/group selectors should not be loaded in advance; they should be loaded on demand through a separate API endpoint, and the group list should only be populated if a facility has already been selected.

We should also have these URLs, at least on the central server (and hence probably easiest to also have the same on the distributed server) be scoped by Sharing Network, so that it will only show facilities/groups within that Sharing Network. So, for instance, the path would be:
`/zone/2847e84d8232ad0/coachreports/table/` instead of just `/coachreports/table/` (even though the `/zone/2847e84d8232ad0/` part would never change on a distributed server). Eventually, in the upcoming DB redesign, there could be multiple Sharing Networks on an installation anyway, so this scoping will definitely make sense to have by that point.

**Comment by rtibbles** [comment]
@christinepham you may want to take note of this.

**Comment by MCGallaspy** [comment]
@rtibbles this issue is now obsolete, yes?

**Comment by rtibbles** [comment]
Might still be problematic on central.

**Comment by aronasorman** [comment]
@rtibbles status of this?

**Comment by rtibbles** [comment]
This should now be scoped to what a user has permission to view. It's still a nightmare for superusers, but for ordinary users on Central, this should now be fine.

We can punt this to 0.15.x for resolving the superuser issues.

**Comment by rtibbles** [comment]
Now scoped by zone. Fixed in #4272
