### ISSUE TITLE
all quizes lead to a solution

### ISSUE THREAD

**Issue by mjptak** [learningequality/ka-lite#3362]
http://127.0.0.1:8008/learn/khan/computing/computer-science/algorithms/graph-representation/quiz-representing-graphs/

Great exercise but with no hint or solution.  From memory the default for any exercise should be that the last hint lays out the solution so you can move on and get that warm fuzzy of typing in the right answer.      Something to think about for version 0.14.......Y'all are rockin' 0.13!

**Comment by jamalex** [comment]
This may need to be something for KA's issue tracker -- not much we can do about it on our side. We're just in the scrapin' business! ;)

**Comment by MCGallaspy** [comment]
Someone can check if there's a corresponding issue on the KA site. That would let us know if there was truly a bug here or an oversight in the assessment item data -- the latter being not our fault!

**Comment by jamalex** [comment]
Looks like there were simply no hints coded up for these exercises, as it's the same on the KA side:
https://www.khanacademy.org/computing/computer-science/algorithms/graph-representation/e/quiz--representing-graphs
