### ISSUE TITLE
Inaccurate message: "This content was not found! You can download it by going to the Update page."

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3364]
When viewing an undownloaded video, you see:

![image](https://cloud.githubusercontent.com/assets/618416/6745698/33166948-ce78-11e4-8e94-bcc6a5d6c2f3.png)

However, we have no such page anymore. This should probably say "This content was not found! You can download it by going to the Manage > Videos page."

**Comment by georgyberdyshev** [comment]
Hello everyone,

@rtibbles 
I have added a pull request #3441 fixing this issue.

@jamalex This can also be merged into the 0.13.x branch

Thanks in advance, Georgy

**Comment by georgyberdyshev** [comment]
Adding screenshot of the fix, displaying the correct information

![fixed location message for missing content](https://cloud.githubusercontent.com/assets/67566/6891168/e0bbc006-d6b7-11e4-9785-1a4ae49bc0ff.png)

**Comment by aronasorman** [comment]
Fixed in the PR above. Thanks @georgyberdyshev!
