### ISSUE TITLE
Accessbility Issue: Navigation sidebar put above main content in HTML flow

### ISSUE THREAD

**Issue by sopu** [learningequality/ka-lite#3365]
Branch: develop
Current:  
One of the problems with using a screen reader to read a web page is that it sees the web page as a stream of words, appearing one at a time. As the HTML for ka-lite begins with topbar and then sidebar with all the navigation buttons, a typical screen reader will proceed to read the sidebar first, through the whole list, before it reaches the main content. 
Scrrenshot:
![screenshot from 2015-03-20 11 30 04](https://cloud.githubusercontent.com/assets/6399612/6746804/7e6ca3b8-cef4-11e4-905b-5c5acb428631.png)

Improvements suggested:
1. Put a "Skip to main content" link at the top of the page.(Used by many accessibility-aware sites.) OR
2. Put the main content before sidebar in the HTML code.

**Comment by sopu** [comment]
Please suggest the kind of improvement would be preferred.
I would like to work on it.

**Comment by MCGallaspy** [comment]
Apparently resolved.
