### ISSUE TITLE
Feature Proposal - Implement Content Recommendation Engine and Interface

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#3368]
Feature Name: Content Recommendation Engine and Interface

Team members: 
@rtibbles
@almgong
@sialan
@howdyitshelena
@66eli77 

PR reviewer: @jtamiace for Front End code, @jamalex or @aronasorman for back end code.

Description:
Implement a back end with API endpoint and front end interface for content recommendation. This content recommendation would appear immediately to the student upon logging in.

First pass content recommendation will infer recommendations from the content and structure of the content itself. Further work will then look at opportunistically using user data available on the local device to inform recommendations. Lastly, but probably outside the scope of this Feature, there can be consideration of aggregating user data centrally and adding annotation to metadata to inform future content recommendation.

For the interface, first stages will be ideation, mockups and prototyping. The first interface will be basic - with two selections presented to the user: "Next Steps", and "Try something new". The main aim of this will be to give the user simple choices to engage with content, while not always rail roading their progress.

For the backend, the first step will be cleaning up @almgong's previous work and making it into an efficient API queryable structure. This will include considering the network structure of the topic tree and different distance metrics, as well as using the metadata that is encoded in the topic tree already in different ways. Once the recommendation endpoint is in place, work can be carried out iteratively to improve the quality and efficiency of the recommendations being generated.

Milestones:
April 10 - Functional API endpoint serving basic recommendations. Mockups of interface.
April 17 - Refine mockups based on user feedback (hopefully from India and other partners). Define list of potential heuristics for using local user data.
April 24 - Enhance backend to create recommendations based on the aggregate of a range of strategies and heuristics.
May 1 - First pass implementation of interface. User testing of interface to follow.
May 8 - Addition of the simplest local user data based heuristics.
May 15 Opening PRs for final interface and latest API endpoint.
May 23 Efficiency testing of recommendation engine complete - target: Run well on a Raspberry Pi.
May 26 - PRs merged.

Reach Goals:
- More complex local user data heuristics.
- Develop initial algorithms for generating recommendations offline (as in, using data synced to the central server).

**Comment by benjaoming** [comment]
This was implemented as good as it gets in #3688 and later improvements.

For any further work on content recommendation, please refer to the successor called Kolibri, a wonderful project designed by experts such as @rtibbles :)

For further recommendations for the content recommendations, please open separate issues or even better.. PRs :)
