### ISSUE TITLE
Cannot export StoreTransactionLogs anymore 

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3370]
Branch: central-develop

Expected: We have a CSV export feature, e.g. at:
http://staging.learningequality.org/export/?zone_id=0e02138bb77d571f8de954bdc3d398ee
There is an option for exporting StoreTransactionLogs. It should work.

Observed: It does not work; it sends us to:
http://staging.learningequality.org/export/undefined?group_id=&facility_id=&zone_id=0e02138bb77d571f8de954bdc3d398ee&zone_ids=&format=csv&limit=0
which returns a 404.

Reason: We removed the tastypie API endpoints from the store app, since it's deprecated. But we still need them on the central server.

Fix: Restore those endpoints, for the central-develop branch.

**Comment by anuragkanungo** [comment]
@jamalex 
Can you point to the PR where we removed those endpoints ?

**Comment by jamalex** [comment]
Seems we didn't. We just removed part of the option from the data_export JS.

Fixed in #3372.

**Comment by anuragkanungo** [comment]
@jamalex 
Can be closed ?

**Comment by aronasorman** [comment]
Seems to be fixed in #3372.
