### ISSUE TITLE
Hidden button on sidebar can be accessed with keyboard

### ISSUE THREAD

**Issue by natnael2012** [learningequality/ka-lite#3382]
Branch - develop
Current behaviour - The hidden button on the sidebar menu can be accessed with keyboard. Keyboard only users can access it and it can create confusion for such users.

![issue](https://cloud.githubusercontent.com/assets/8178368/6769143/709dd76c-d04c-11e4-9cd0-74d9dbaf921f.png)

**Comment by MCGallaspy** [comment]
@natnael2012 can you describe how you activated the "hidden" button?

**Comment by rtibbles** [comment]
Replicated. Found it using keyboard tab.
