### ISSUE TITLE
Error: There was an error during the last sync

### ISSUE THREAD

**Issue by sharprakeshverma** [learningequality/ka-lite#3383]
Branch: Develop
Expected: Successful Sync
Actual behaviour: Getting Error "Exception happened during processing of request from ('127.0.0.1', 58384)"
Steps: "Sync Now" 
![gh](https://cloud.githubusercontent.com/assets/10394619/6771484/3f909d12-d105-11e4-834d-5e8527817e86.png)

Complete Error List at : http://pastebin.com/RQDWvN2s

![gh1](https://cloud.githubusercontent.com/assets/10394619/6771490/5f51ec14-d105-11e4-9852-6802a06a95ce.png)

**Comment by MCGallaspy** [comment]
@sharprakeshverma can you elaborate on how to reproduce this error?

**Comment by rtibbles** [comment]
Assuming this is fixed, following @jamalex's investigation of syncing issues in another issue.
