### ISSUE TITLE
404 Page not found error on reports page

### ISSUE THREAD

**Issue by sharprakeshverma** [learningequality/ka-lite#3384]
Branch: Develop
When Click on an exercise one learner has completed(Count to 100) on Reports Tab, I am getting a 404 Page not found error. 
What could be the possible reason?

At "Teach" Page:
![gh12](https://cloud.githubusercontent.com/assets/10394619/6771603/c4166dca-d108-11e4-929b-df558c4f3a4f.png)
After Clicking on "Count to 100"

![gh11](https://cloud.githubusercontent.com/assets/10394619/6771611/db94d3a6-d108-11e4-97c6-749c40a67619.png)

**Comment by rtibbles** [comment]
Good catch - the URL in the table headers seems to be incorrect. Fixing.

**Comment by sharprakeshverma** [comment]
Can a beginner help in solving this?? I am interested in solving beginner level bugs but unable to get any :(

**Comment by sharprakeshverma** [comment]
@rtibbles , saved your changes in my local installation. works fine now without errors. Can you help me with how i can get to know where the solution of this error belongs to, i mean which file.

**Comment by rtibbles** [comment]
Look at my PR on github, can look at 'files changed' to see the diff.

**Comment by rtibbles** [comment]
Fixed in #3394
