### ISSUE TITLE
Points and icons are changed during exercises.

### ISSUE THREAD

**Issue by cpauya** [learningequality/ka-lite#3386]
**Branch**: develop
**Target**: for 0.13.x
**Browser**: Firefox v36.0.1
**Current Behavior**:

1. Even if answered wrong, the points are incremented.
1. Icons are changed to correct one for previous incorrect attempts.

**Expected Behaviors**:

1. If answer is wrong, points must not be added and the "wrong" icon is shown.  The same thing for correct answers, specially for previous attempts.
1. Icons for previous attempts must stay the same, correct or incorrect.

**How to reproduce**:

1. Go to http://127.0.0.1:8008/learn/khan/math/early-math/cc-early-math-counting-topic/cc-early-math-counting/count-to-100/
1. Answer the exercises correctly and incorrectly, then move to the next questions.
1. Notice the points and icons are changed.

**See screenshot .gif**:
![ka-lite](https://cloud.githubusercontent.com/assets/175580/6773637/e3cb6760-d14e-11e4-82a4-06939566fdf6.gif)

**Comment by rtibbles** [comment]
Hrm - I can't replicate this in either Chrome or Firefox. @cpauya can you check the Javascript console to see if anything gets logged when this is happening?

**Comment by rtibbles** [comment]
@cpauya @aronasorman notes that you are logged in as either a teacher or an admin - this may explain this slightly odd behaviour.

**Comment by rtibbles** [comment]
Can't replicate this on either student or teacher accounts, so I am assuming that this is something that only happens on admin accounts.

Note: Admin accounts are different because we don't save any user progress for them, as they are not FacilityUsers.
