### ISSUE TITLE
Remove settings.CONFIG_PACKAGE

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#3388]
Ultimately this variable seems to attract platform specific-behaviour and has not been properly documented.. and possibly moreover it's just used for Raspberry Pi and Nalanda stuff.

The `package_selected()` function in kalite.settings is a utility function that looks at some weird CONFIG_PACKAGE var, which I don't understand half of, except for the following:

1. It looks in local_settings for CONFIG_PACKAGE
1. If it doesn't find it, it uses platform.uname
1. It may be [] <- but what does that mean!?
1. It can be a string or a list

So let's cut this weird behavioural CONFIG_PACKAGE thing out and just specify settings explicitly per-variable.

**Comment by rtibbles** [comment]
What are your feelings about having single settings variables that can turn on multiple settings? (Which is basically what the CONFIG_PACKAGE was doing).

**Comment by benjaoming** [comment]
That all this will be solved by managing settings properly. So you do like this (well, quite limited example):

    settings/
      __init__.py
      raspberrypi.py

Running with:

    kalite manage runserver --settings=kalite.settings.raspberrypi

or

    DJANGO_SETTINGS_MODULE=kalite.settings.raspberrypi kalite manage runserver

**Comment by rtibbles** [comment]
Sounds good to me.

**Comment by rtibbles** [comment]
Woops, wrong button.

**Comment by benjaoming** [comment]
This will happen in #2952
