### ISSUE TITLE
When zero points, ugly empty space in user drop down is displayed

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#3392]
Branch: 0.13.x

Expected Behaviour: We should either say 'Points: 0' or elide the ```<li>``` altogether.

Current Behaviour: ```<li>``` remains and nothing is injected.

![image](https://cloud.githubusercontent.com/assets/1680573/6787690/bd475baa-d151-11e4-9089-6257e96371b5.png)

**Comment by 66eli77** [comment]
cannot replicate the issue
![screen shot 2015-03-23 at 5 01 46 pm](https://cloud.githubusercontent.com/assets/5577205/6793176/52521678-d17e-11e4-9599-bfab0afcd4e7.png)
