### ISSUE TITLE
Setuptools configuration: python setup.py install / pip install ka-lite

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#3396]
In order to facilitate packaging much better, we are building a python-only installation procedure. Cross-platform.

The method you know all too well from PyPi and pip :)

This includes the following:

  * [x] A layout for all the setup meta data etc.
  * [x] GPG key signing
  * [x] New layout: Putting data files separately from the `kalite` python package, that means they will be found using `sys.prefix`, compatible with virtualenvs
  * [x] What is the future of the `kalite manage update` command? It's doing logic that should be exclusively handled by setup.py and additionally a data migration command by the `kalite` command (post-upgrade!). Discussed in #3774

End goals are:

  * [x] Installable from PyPi with `pip install ka-lite`.
  * [x] Installable from PyPi with `pip install ka-lite-static`.
  * [x] Works from a virtualenv

Deferred:

  * Moving the bundled python-packages dir... as of now, it will be installed as package data. Tracked in #3403
  * Wheel compatibility (the future package format of the Python community)... is not possible because of data files distributed outside of packages. See [this bug](https://bitbucket.org/pypa/wheel/issue/92/bdist_wheel-makes-absolute-data_files). #3951

**Comment by benjaoming** [comment]
For more, see [my branch](https://github.com/benjaoming/ka-lite/tree/setuptools-installer), moreover the [PACKAGE.md](https://github.com/benjaoming/ka-lite/blob/setuptools-installer/PACKAGING.md)

**Comment by benjaoming** [comment]
Related: #2952

**Comment by benjaoming** [comment]
@aronasorman I'm making it debatable whether this should be in 0.13 -- but it will be required to create a Debian installer.

**Comment by rtibbles** [comment]
@benjaoming I think adding the ability to build in this way is fine for 0.13.x - but we should probably not move all the python-packages out until 0.14.

Will we just be using a requirements.txt to list the packages?

**Comment by benjaoming** [comment]
@rtibbles yup, this issue is solely for packaging with nothing else changed than some paths for data files.

The python-packages thing is now covered in #3403. As for requirements.txt, yes that's a very simple and effective approach for specifying dependencies.. but actually I remember [this incident](https://github.com/django-wiki/django-wiki/commit/67f7ae9c9d6e943ecb65871e03b5f00c05da54b0) where it was ditched in favour of a more dynamic setup.py-based approach.

**Comment by rtibbles** [comment]
Righto - happy to implement however - just loath to add more bloat into python-packages with my latest PR to develop

**Comment by benjaoming** [comment]
If it's possible to freeze python-packages for 0.14, that would be helpful :) But I guess there's no alarms until the first PRs for removing them start coming in.

**Comment by aronasorman** [comment]
Merged #3519. What else needs to be done for this issue @benjaoming?

**Comment by benjaoming** [comment]
See the task list at the top ;) I'll make sure that it's moved to a new issue ASAP.

**Comment by benjaoming** [comment]
Everything resolved, closing!
