### ISSUE TITLE
Blank Page on Progress Report

### ISSUE THREAD

**Issue by sharprakeshverma** [learningequality/ka-lite#3397]
When a new user checks the progress report, It shows a complete blank page with just a "Progress Report" Heading title. I feel there should be something like "No progress" or some other message instead of a complete blank page. If this is left blank intentionally, please explain.Thanks
Branch:develop
![56](https://cloud.githubusercontent.com/assets/10394619/6800349/a3c9605e-d243-11e4-89ab-1c680fda3838.png)

**Comment by georgyberdyshev** [comment]
Hello everyone,

I have added a pull request #3439 fixing this issue.

@rtibbles Do you have any thoughts, how I can improve here by adding internationalization to the
JavaScript. Is there any backbone.js related magic?

Thanks in advance, Georgy

**Comment by georgyberdyshev** [comment]
Adding screenshot with displayed message, using pull request #3439.

![progress_error_with_message_after_fix](https://cloud.githubusercontent.com/assets/67566/6888460/ec930c0c-d67d-11e4-9952-72cab8d83cc5.png)


Thanks, Georgy

**Comment by rtibbles** [comment]
Fixed in #3277
