### ISSUE TITLE
service doesn't respond status command

### ISSUE THREAD

**Issue by yohanboniface** [learningequality/ka-lite#3398]
No way to issue "sudo service kalite status" with Linux install on master branch.

I see that the init.d is not a regular daemon script, so I guess that's why. But I think in the future (specifically now that you are reviewing the Debian install process) it could be nice to have a standard interface.

cc @benjaoming

**Comment by benjaoming** [comment]
@yohanboniface 
Thanks for the report. The `kalite` command will be a standard interface for the future to support init.d/upstart scripts etc.

I'm not quite sure why you're having problems using the `kalite status` command.. is the command itself failing or is it your path environment that doesn't contain `kalite` ?

**Comment by MCGallaspy** [comment]
@benjaoming 
Seems like @yohanboniface's issue was with setting up KA Lite to start at boot (check out the relevant [doc page](https://learningequality.org/docs/installguide/install_linux.html)), but we might have resolved this with a recent PR. Will try to dig it up. Perhaps @yohanboniface can elaborate on how to reproduce this error?

**Comment by MCGallaspy** [comment]
I think #3686 and other recent PRs have probably resolved any issues with `runatboot.sh` and the `initdconfig` management command.

**Comment by yohanboniface** [comment]
The kalite command I have on the servers doesn't answer to `status` argument. I'll update when possible and keep you updated. cc @Splite07

**Comment by MCGallaspy** [comment]
So what happens
