### ISSUE TITLE
bin/kalite does not support PyPy

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3399]
It always drops down to python2. Which is slow.

**Comment by aronasorman** [comment]
Also, KA Lite isn't working in PyPy.

**Comment by benjaoming** [comment]
It just defaults to `python2` if it's in the path. But you can override that behaviour by setting a `KALITE_PYTHON` env.

**Comment by benjaoming** [comment]
https://github.com/learningequality/ka-lite/blob/develop/bin/kalite#L72

**Comment by aronasorman** [comment]
Yeah, was hoping it would default to PyPy (since it's a "faster" python), but looks like KA Lite doesn't even work on PyPy in the first place.

**Comment by alexkchan** [comment]
Downloaded the latest version of PyPy off Brew, Ka-Lite seems to be working fine with the latest develop

**Comment by aronasorman** [comment]
Wil be fixed once https://github.com/learningequality/ka-lite/issues/4315 has been implemented.

**Comment by benjaoming** [comment]
PyPy will be dropped:
https://github.com/learningequality/installers/issues/417

But it's a duplicate of #4315 anyways

**Comment by benjaoming** [comment]
Fixed in `0.17`, releasing at the end of October. But work on installers can start now with the prerelease of 0.17b1.
