### ISSUE TITLE
Pressing the Learn tab when already under /learn/ should just expand sidebar to top-level topic

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3410]
Branch: 0.13.x

Observed:
Pressing the Learn tab when already on a sub-page of /learn/ does a full page reload. Since the Learn tab takes a long time to load, this is a bit painful. Observed a (new) user tap it repeatedly, trying to figure out where to go next (after collapsing sidebar).

Desired:
Just like we do for autocomplete results etc, we should intercept that click and route it via the Backbone router to open the sidebar and have it collapse back to the top-level of the topic tree.

Thoughts, @rtibbles / @Antrikshy?

**Comment by rtibbles** [comment]
Sounds like a reasonable fix.

**Comment by rtibbles** [comment]
I have implemented this on 0.13.x - relatively simple fix. However, it reveals two bugs:
* Javascript errors from our own sidebar code
* Perseus error when navigating away from a Perseus content node if it happens before Perseus has finished rendering.

Will fix and submit a PR.

**Comment by rtibbles** [comment]
Fixed in #3414
