### ISSUE TITLE
Can't Sync My Models, although the Sync Job has been Launched

### ISSUE THREAD

**Issue by ruancilliers** [learningequality/ka-lite#3422]
Branch: 0.12.0
Expected Behavior: When I select Sync, I expect the modules to Sync, as the messages says the Sync Job has been launched (see attached screen shot)
Current Behavior: Although the Sync Job, has been launch ( I have tried this multiple times, you can see in the screenshot that no models has been synced for more than a year ). I have also tried this manually with the syncmodules command and I get the same result.

Please let me know how I can sync my models and fix this error: Thank you... Ruan.Cilliers@gmail.com

How to Reproduce the Error: Just click on Sync Models and see that no modules has been synced...
![sync job is successfully launched message](https://cloud.githubusercontent.com/assets/11680550/6869187/dce107e4-d49a-11e4-9dc6-7ce0c249fa23.JPG)
![no models is being synced](https://cloud.githubusercontent.com/assets/11680550/6869192/e4329490-d49a-11e4-8c73-8aef71df372c.JPG)

**Comment by ruancilliers** [comment]
Hi Rakesh,

I think that is the problem. I left it for hours and no messages thay say
unsuccessful or error messages? Where would I find them? Is there a log
file somewhere so that I could send it to you?

Thank you,
Ruan

On Sunday, March 29, 2015, Rakesh Verma <notifications@github.com> wrote:

> Did the sync process completed successfully?? If not, there must be some
> errors along with a message " sync process couldnt complete successfully"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/learningequality/ka-lite/issues/3422#issuecomment-87422808>
> .
>


-- 
Sent from Gmail Mobile

**Comment by MCGallaspy** [comment]
Not really clear what the issue is. @ruancilliers did you actually create any models that could be synced, or register the device within a sharing network that had synced models? If, for example, you had created no student accounts or activity then I would fully expect no models to by synced.

**Comment by ruancilliers** [comment]
Dear Michael,

Updating to the latest version solved the problem.

Thank you for your assistance.

Enjoy your day,
Ruan

**Comment by MCGallaspy** [comment]
We'll chalk this up to user error.

**Comment by ruancilliers** [comment]
It is was definitely a bug in the previous version (012.) that I used,
which you must have fixed in the updated version (0.13). My models did not
sync in 0.12 and when I updated to 0.13 it worked... So thank you for
fixing the bug... :-)
