### ISSUE TITLE
No underlying text for password field

### ISSUE THREAD

**Issue by tarunsharma1** [learningequality/ka-lite#3430]
Current behavior: only user name field has underlying text during login
Expected behavior: password and user name fields should have underlying text like in all general forms 
, or neither of them should.
Steps to reproduce: hit the login button on the top right of the screen
![screenshot 142](https://cloud.githubusercontent.com/assets/8834964/6885246/63738792-d634-11e4-88d2-d68ac08cfe4b.png)

**Comment by tarunsharma1** [comment]
https://github.com/learningequality/ka-lite/pull/3431

**Comment by rtibbles** [comment]
Fixed in #3431
