### ISSUE TITLE
No error message when trying to login with wrong password

### ISSUE THREAD

**Issue by tarunsharma1** [learningequality/ka-lite#3432]
Expected behavior : If user enters wrong password during login, an error message saying "wrong password, please enter your correct password" should appear somewhere.
Current behavior : If user enters wrong password, nothing happens. The login dialogue box still stays the same with no error message. If dialogue box is closed and login button is hit again, the entered details stay. They are not cleared.

Steps to reproduce: Hit login and enter a wrong password. Press the login button. Nothing happens.
Close login dialogue box and hit the login button on the top right again. Data is uncleared.

![screenshot 144](https://cloud.githubusercontent.com/assets/8834964/6885313/2eb4c954-d638-11e4-9775-060ae6c38d53.png)

**Comment by tarunsharma1** [comment]
Even when a user enters a user name that has not been registered, nothing happens

**Comment by rtibbles** [comment]
Fortunately, I am blessed with precognition and already have a PR open that addresses this.

**Comment by tarunsharma1** [comment]
oh ok ...if you have already fixed this then it can be closed i suppose

**Comment by rtibbles** [comment]
Will close when the PR is merged.
