### ISSUE TITLE
select_best_available_language called 15508 times during load

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#3433]
That's the count with my assessment_zip

```
(snip too much output)

DEBUG:kalite:choosing best language among ['en'] 15496
DEBUG:kalite:Requested code es, got code en
DEBUG:kalite:choosing best language among ['en'] 15497
DEBUG:kalite:Requested code es, got code en
DEBUG:kalite:choosing best language among ['en', 'es'] 15498
DEBUG:kalite:choosing best language among ['en'] 15499
DEBUG:kalite:Requested code es, got code en
DEBUG:kalite:choosing best language among ['en', 'tr'] 15500
DEBUG:kalite:Requested code es, got code en
DEBUG:kalite:choosing best language among ['en', 'es'] 15501
DEBUG:kalite:choosing best language among ['ru', 'en', 'de', 'sw', 'it', 'ur', 'si', 'pl', 'uk', 'es'] 15502
DEBUG:kalite:choosing best language among ['ru', 'xh', 'en', 'pt', 'no', 'pt-PT', 'bn', 'de', 'tr', 'it', 'ur', 'si', 'hy', 'pl', 'uk', 'cs', 'es', 'he'] 15503
DEBUG:kalite:choosing best language among ['en'] 15504
DEBUG:kalite:Requested code es, got code en
DEBUG:kalite:choosing best language among ['bn', 'en', 'ur'] 15505
DEBUG:kalite:Requested code es, got code en
DEBUG:kalite:choosing best language among ['en'] 15506
DEBUG:kalite:Requested code es, got code en
DEBUG:kalite:choosing best language among ['ru', 'xh', 'en', 'pt-PT', 'ar', 'es', 'he'] 15507
DEBUG:kalite:choosing best language among ['en'] 15508
DEBUG:kalite:Requested code es, got code en
INFO:kalite:Preloading topic tree data for language es.
```

So I'd suggest a cache... coming right up....

**Comment by benjaoming** [comment]
Solved in https://github.com/benjaoming/ka-lite/commit/24e2373e64c50bbc439b88e59b9decaef6b11478

**Comment by jamalex** [comment]
How many times is it now called? (Just curious, as there are 7000+ videos, after all, so there may be a high floor)

**Comment by rtibbles** [comment]
The only thing that changes between calls is the 'available language' I think, @jamie - so the caching should have a decent impact.

**Comment by benjaoming** [comment]
Oh, in case the available languages are changing, too, it becomes a little harder to cache.. I'll remix the caching a bit then...

**Comment by benjaoming** [comment]
Okay, @jamalex  was quite right that of course this is also a selection based on individual video language availability... but of course not really something that we'd have to computer at load-time... could be fixed at a later occassion.

Anyways, it got cut in half now...

    DEBUG:kalite:choosing best language among set(['en']), 7768

I've also removed the log output as it was quite massive :)
