### ISSUE TITLE
Video management page does not work and returns an error

### ISSUE THREAD

**Issue by georgyberdyshev** [learningequality/ka-lite#3436]
Branch: develop
Expected behavior: Display video management page
Steps to reproduce: In the main navigation click on the manage button. After that in the sub navigation, click on the Videos button.
Actual behavior: Video management page does not work and an error message is displayed
Error
Sorry, but there was an error while trying to load the page.

(NameError: global name '_' is not defined)

![kalite_manage_video_error](https://cloud.githubusercontent.com/assets/67566/6886286/b8168e18-d637-11e4-8fa2-ac88d1962dec.png)

Thanks, Georgy

**Comment by georgyberdyshev** [comment]
Hello everyone,

I have fixed this issue and will create a PR shortly.

code:
https://github.com/learningequality/ka-lite/commit/6a7bdd4baba460f08cfe39b59ac755558c9ad2bd

Thanks, Georgy

**Comment by georgyberdyshev** [comment]
Hello everyone,

I have added a pull request #3437 fixing this issue.

@aronasorman this fixes an issue introduced in https://github.com/learningequality/ka-lite/commit/0fb6bc5782718a76d91b7ac4ce8a8514f6fcdf26

Thanks in advance, Georgy

**Comment by georgyberdyshev** [comment]
Added screenshot of the working page, after applying the code from the pull request:

![kalite_manage_video_error_fixed](https://cloud.githubusercontent.com/assets/67566/6886593/5f1814fc-d642-11e4-8b94-a7d64c6468db.png)

**Comment by rtibbles** [comment]
Fixed in #3437
