### ISSUE TITLE
Page does not scroll to the first MCQ option automatically

### ISSUE THREAD

**Issue by sopu** [learningequality/ka-lite#3444]
branch: develop
Current behavior: In firefox the auto scroll to first MCQ is not working correctly.
Screenshot
![screenshot from 2015-03-30 14 28 26](https://cloud.githubusercontent.com/assets/6399612/6893274/3742fb98-d6e9-11e4-8bdf-f0fefe8d9775.png)
![screenshot from 2015-03-30 14 30 15](https://cloud.githubusercontent.com/assets/6399612/6893279/4cb454a4-d6e9-11e4-829f-8b5a2976cf77.png)

Expected behavior: Focus should reach the first MCQ radio button

**Comment by rtibbles** [comment]
Not going to happen within the scope of KA Lite.
