### ISSUE TITLE
On some questions, pressing enter to go to next question on exercise marks next question as incorrect

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3450]
Expected: Pressing enter after completing a question should just take you to the next question.

Observed: Pressing enter takes you to the next question and marks it as incorrect (tries to answer it immediately upon showing it, with an empty answer box). Seems as if the "Enter" keypress might be getting registered twice.

Steps to replicate:

- Go to an exercise. Not sure if it applies to all, but this one shows the issue: http://127.0.0.1:8008/learn/khan/math/arithmetic/multiplication-division/mult-div-word-problems/comparing-with-multiplication/
- Type in a correct answer and hit Enter.
- It shows you answered correctly, and changes the button to "Correct! Next question...".
- Press Enter again.
- It proceeds to the next question and immediately marks it as incorrect.

**Comment by jamalex** [comment]
@rtibbles Thought you might now how the event listeners work here, and why this would be happening?

**Comment by tarunsharma1** [comment]
@jamalex this seems to happen only for this particular exercise

**Comment by jamalex** [comment]
Good call. I'll downgrade this from a release blocker to a bugfix. Thanks!

**Comment by aronasorman** [comment]
This exercise works for me on the latest 0.13.x, Firefox 37. Closing.
