### ISSUE TITLE
Inconsistent table alignments and font sizes

### ISSUE THREAD

**Issue by Joymysoy** [learningequality/ka-lite#3455]
Tables are aligned at 20px and 40px; body/paragraph font-sizes vary from 14-18px. 

![register a device welcome ka lite original](https://cloud.githubusercontent.com/assets/7270285/6909861/dec227d4-d6ff-11e4-9cb2-f5b0fa780406.png)

-------------------------------------
Fixes:
-Change 2nd table margins left and right to 40px;
-Change font size of bullet lists to 14px
-Adjust bottom margin of 1st table header to 15px

![register a device welcome ka lite mock1](https://cloud.githubusercontent.com/assets/7270285/6909864/e510346e-d6ff-11e4-9077-304358a9d672.png)

-------------------------------------
Additional Fixes:
-make bullet list stand out by changing font style to italics
-make sub headers of 2nd table stand out by increasing font-size to 20px and changing color to green

![register a device welcome ka lite mock2](https://cloud.githubusercontent.com/assets/7270285/6909865/e781048a-d6ff-11e4-8600-e8122b3d7aaa.png)

**Comment by rtibbles** [comment]
And most importantly. TABLES ARE FOR DATA!

Why, in the name of all things holy, are we using a table for layout? Burn it! Burn it with fire!

**Comment by arceduardvincent** [comment]
Hi @aronasorman and @Joymysoy my fix is merge.
Can we close this issue, I think it is done.
