### ISSUE TITLE
Redundant label/placeholder on login modal

### ISSUE THREAD

**Issue by Antrikshy** [learningequality/ka-lite#3459]
![screen shot 2015-03-31 at 12 47 16 pm](https://cloud.githubusercontent.com/assets/6601788/6927741/26edbf1a-d7a4-11e4-8bea-71ed814d5d3a.png)

>Username Username
>Password Password

ಠ_ಠ

Shouldn't we have one or the other? Maybe remove the label and make it `sr-only`? Or just get rid of the placeholder? I'm a fan of this login form: http://getbootstrap.com/examples/signin/

Assign me to this and send over your recommendations.

**Comment by rtibbles** [comment]
I couldn't give a monkeys' either way, to be honest. The problem with *just* the prefill though, is that 'Facility' is a selection drop down, so it won't be consistent.

**Comment by radinamatic** [comment]
Btw, sorry for "stealing" this one under your nose @Antrikshy , I literally just saw your last sentence about wanting to be assigned this... :(
   
The problem with Facility drop down that @rtibbles mentioned is avoided by including a "dummy" "selected disabled" option. I thought it would create problems with the screen readers, but NVDA read out everything just fine.

**Comment by Antrikshy** [comment]
Oh, that's no problem. I'll find other stuff to work on. Right now, I'm getting used to a very busy quarter schedule anyway.

I was thinking of a blank option as well. Yours looks very nice.

**Comment by MCGallaspy** [comment]
@radinamatic looks like you decided to tackle this one. Be sure to tag this issue in a PR when you're ready, so we know we can close it.

**Comment by radinamatic** [comment]
You can close it already, solved in #3647.

**Comment by radinamatic** [comment]
@MCGallaspy, this can be closed...
