### ISSUE TITLE
No module named Compressor Error

### ISSUE THREAD

**Issue by sharprakeshverma** [learningequality/ka-lite#3471]
branch: Develop
steps: update with latest develop branch
system: windows/chrome
![issue](https://cloud.githubusercontent.com/assets/10394619/6983345/41595772-da3a-11e4-89bb-0fa7cc2ceab2.png)

Updating pip used to resolve the error but this time,even that ain't working :(

**Comment by radinamatic** [comment]
Did you Install the dependencies listed in requirements.txt: 

pip install -r requirements.txt 
and 
pip install -r dev_requirements.txt

That's what solved it for me after 0.14 was released...

**Comment by aronasorman** [comment]
Follow the new instructions in the https://github.com/learningequality/ka-lite/wiki/Getting-started to install the additional dependencies.
