### ISSUE TITLE
Enforce API schemas with TastyPie (don't allow extraneous fields, at least during testing)

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3483]
Observed: Sending extra fields when POSTing to a TastyPie endpoint drops the data silently, when it's not part of the schema.

Expected: Unexpected fields in data sent to TastyPie should cause an error. Since causing unnecessary errors for offline end users isn't desirable, we should perhaps only enable this for when we're running tests.

**Comment by rtibbles** [comment]
@jamalex I think we should punt this until we make a decision on jettisoning TastyPie or not.

**Comment by jamalex** [comment]
![](http://2.bp.blogspot.com/-HPgpoqI-XuU/TaBfBITRaxI/AAAAAAAACiM/nftqWwTmm5I/s1600/jettison.gif)
