### ISSUE TITLE
Scatter Report Inconsistent behaviour when the view ports < 768px.

### ISSUE THREAD

**Issue by arceduardvincent** [learningequality/ka-lite#3499]
Branch: Develop.

Expected behaviour: When the view port < 768 the `Chart quadrant` must be responsive and bootstrap compatible.

Current behaviour: The `Chart quadrant` has a fix width  and a fix height.Whenever the viewport is change the chart over laps the header and footer.

Steps to reproduce:
1. login as admin / teacher
2. Click `TEACH` in the `navigation menu` it will navigate to the `coachreports` page.
3. Locate the `Report Type` drop down and select `Scatter Report ` then click `Go`.
4. Resize your browser view port  < 768px.
5. Notice that our `Chart quadrant` is overlapping in our header and html.

The image below show  the view port < 768px.
![screen shot 2015-04-10 at 4 48 34 pm](https://cloud.githubusercontent.com/assets/4099119/7085130/0205a802-dfa6-11e4-8f52-a803f9b5cd1a.png)

**Comment by arceduardvincent** [comment]
Hello @aronasorman I am performing some media queries in this page. 
below are some example when the view port is < 768px
![screen shot 2015-05-20 at 4 52 08 pm](https://cloud.githubusercontent.com/assets/4099119/7722283/52312f4c-ff11-11e4-9570-0a0a1f5c8c3a.png)
![screenshot 2015-05-20 16 54 33]

**Comment by MCGallaspy** [comment]
The scatter report no longer exists on develop.
