### ISSUE TITLE
French Language Pack - ? wrong video codes

### ISSUE THREAD

**Issue by tim-moody** [learningequality/ka-lite#3513]
I have managed to download all but two videos, but they repeatedly fail with Erreur pendant la mise à jour : 0 de 2 vidéos téléchargées.

Could the dubbed_video_mappings.json have the wrong youtube id.  (I am guessing about how this all works)

The 2 missing are:
 La médiane et le centre de gravité du triangle №-2.
 Exemple d'utilisation du théorème de Stokes, partie 3: Surfaces et intégrales doubles

**Comment by MCGallaspy** [comment]
Hi @tim-moody thanks for opening this issue. Could you please indicate what version of KA Lite you're using?

**Comment by tim-moody** [comment]
Not sure how to tell here is version.py
# THIS IS USED BY settings.py.  NEVER import settings.py here; hard-codes only!
# this is actually 0.12.5, but we need to update language pack version fallbacks before changing here
VERSION = "0.12.0"
VERSION_INFO = {

    "0.12.11": {
        "release_date": "2014/12/20",
        "git_commit": "b880fe4",


 kalite kalite 1034689 Apr 11 21:01 dubbed_video_mappings.json

**Comment by MCGallaspy** [comment]
@tim-moody that will do. It should also list the version in the footer of the app when you load it in the browser.

**Comment by aronasorman** [comment]
Stale. Reopen if it still persists for 0.14.
