### ISSUE TITLE
Scripts are not installed correctly for Windows

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite#3529]
The kalite command is designed to be used as system level command on windows systems however to have this functionality the git installation of 0.13.x needs to add the path " ..\kalite\bin" to the windows environment in order to provide the commands path. Because we no longer have the start and stop bat files available in this release this prevents the user from even starting the program and also may break many related commands which will also rely on this env. path being known. It is my understanding that there was a work around using a full command path but that the related functions of the command are now broke when issued that way. This should resolve that problem with modifications to those command function scripts internal pathing, and also make the kalite command available in the recommended windows installer as well. NOTE THIS DOES NOT AFFECT BEING ABLE TO USE KA-LITE WHEN INSTALLED USING THE RECOMMENDED WINDOWS INSTALLER.
![screenshot from 2015-04-16 17 48 50](https://cloud.githubusercontent.com/assets/4349806/7193743/4bc0d456-e462-11e4-9357-d05e5d03aafd.png)

**Comment by benjaoming** [comment]
Explanation of why setuptools and distutils do not correctly handle putting scripts in the path on Windows + scroll to bottom for a solution:

https://matthew-brett.github.io/pydagogue/installing_scripts.html

**Comment by benjaoming** [comment]
@EdDixon This is as close as we can get to Windows compatibility. As you may have heard about, the directory commonly found in "C:\Python27\Scripts" has to be in the Windows path for the commands to be available.

What appears to be a functional kalite.bat script is installed there. I tested that it's installed, but I couldn't test if it works.

Further work on automatically making the `kalite` work on windows has to be delegated to the installer.

**Comment by benjaoming** [comment]
@MCGallaspy what's your take on this?

The Windows installer is responsible for bin/windows/kalite.bat and then setup.py has an automaticcally generated bat script that it will put in the conventional "C:\Python27\Scripts" path.

Is there more we can do?

**Comment by MCGallaspy** [comment]
I don't consider this a release blocker. The program is usable through the task-tray icon. Should the user wish to launch the app with flags not provided through the task-tray icon (or to run management commands, which should be exceedingly rare) then they can use kalite.bat. It's true that they will have to navigate to the directory where the script is located. I don't think that's a big deal.

**Comment by EdDixon** [comment]
Considering this was expected behavior and targeted for the 0.13 release, I would think it should be a blocker on 0.14. The fact that KA-Lite will work using the windows GUI mechanisms but not work through the command line as designed has serious implications in what we provide the end user with in terms of functionality, compliance with our own documentation and goals, and redundant coding efforts to make some of the same functionality available such as the migrate function for instance, two different mechanisms to achieve the same goal. I would think the sooner we adopt the kalite command into our installers, the sooner we will start to benefit from the cross platform capabilities the command offers in simplifying and unifying a lot of this effort? Each platform does have it's specific environment needs the proposed kalite user in linux for example, plists on MAC,etc. So, why not create our own environment variables for a path for this command on windows or go ahead and create a full windows compliant binary from the kalite python script source? I feel this would really help all by eliminating any confusion of its use on specific platforms, by making the command work exactly the same way on all platforms? That was the whole idea behind developing the command as I understood it?

**Comment by benjaoming** [comment]
I feel that we need to document how to enable the command.

The issue is that it's correctly placed as a .bat script in C:\Python27\Scripts like any other Python application that's installed. However, that directory is not by default on the Windows command line path, which is a universal problem:

1. The issue is resolved since Python 3.3 for Windows: https://bugs.python.org/issue3561
1. How to add manually:
    1. Open the System Properties either via the Control Panel or pressing 
WinKey-Pause
    1. Click on the tab that says Advanced
    1. Click on Environment Variables
    1. Under System Variables, scroll down and find Path
    1. Click on Edit
    1. Add ;X:/PythonXX/Scripts where X is the appropriate drive letter and 
python version.
    1. Click OK, and OK again.

**Comment by EdDixon** [comment]
@benjaoming Awesome! So we just need to add that path during the installer process! @MCGallaspy I think for XP sp2 and above we will need to use the setx command to do so but by all means! YES Please!

**Comment by benjaoming** [comment]
@EdDixon that wasn't what I said :) I said we should put this in our docs first :)

I don't think what happens during the "manual" instructions is universal to all Windows versions as we've spend a lot of time being baffled by this mystic, magic, hocus pocus Windows path environment.

**Comment by benjaoming** [comment]
@EdDixon also, Python 3.3 is still out of reach for our codebase :(

**Comment by MCGallaspy** [comment]
@EdDixon as I mentioned above, I simply do not find the fact that "kalite" or "kalite.bat" is not in the PATH to be a release blocker for 0.14... as I said, it's quite usable still, you just have to C:\Give\the\full\path. (It's also not a barrier to using the kalite command programmatically, and is not the cause of any bugs that we have so far turned up.)

There is also one subtlety that I think bears looking in to that warrants caution when editing the PATH variable as part of the installation process, which is that PATH has a (relatively short) maximum length.

**Comment by benjaoming** [comment]
@MCGallaspy the above fix also requires the Windows installer to be running setup.py but that would be a small advantage, given that we can then delete bin/windows because setup.py generates a .bat on the fly for Windows and puts it in C:\Python27\Scripts
