### ISSUE TITLE
Getting logged out refreshes the page, but doesn't bring up the modal.

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3538]
When I restart the server, it logs me out (expected), but it simply leads me to this:
![login](https://cloud.githubusercontent.com/assets/191955/7263925/c46925f8-e83a-11e4-8010-54880e3b2446.png)

And doesn't show the modal anywhere. In develop, but maybe it's extant in 0.13.x too.

**Comment by aronasorman** [comment]
Firefox 37, btw.

**Comment by MCGallaspy** [comment]
Are you saying that you expect a redirect from an unauthorized page to display the modal?

**Comment by aronasorman** [comment]
Yes.

**Comment by rtibbles** [comment]
Yes. It is designed to do this, so if this is not happening, definitely a
bug.

**Comment by rtibbles** [comment]
Note, that as the model was not included in 0.13.x, this will not be extant there, @aronasorman.

**Comment by rtibbles** [comment]
Fixed by #3729
