### ISSUE TITLE
git submodules pointing to git url instead of https

### ISSUE THREAD

**Issue by quentusrex** [learningequality/ka-lite#3539]
kmath and simple-markdown submodules are pointing to the git url instead of the https url which causes the submodules to fail when cloned from a VM instance without an ssh key registered with github.

**Comment by rtibbles** [comment]
This comes from inclusion of the Khan Academy Perseus repo, if you would like this rectified, please open an issue there. The Perseus repo comes pre-built in KA Lite, so there is no need to clone the submodules at this time.
