### ISSUE TITLE
Video and language tabs redirect to page not found.

### ISSUE THREAD

**Issue by amodia** [learningequality/ka-lite#3545]
Branch: `Develop`
Expected behavior: Video and language tabs must not redirect to `page not found`.
Current behavior: Video and language tabs redirect to `page not found`.
Note: Make sure that your device  is not registered on central server.
Steps to reproduce: Log in as coach and navigate to manage tab and click video and language tabs.

![ka-lite-a](https://cloud.githubusercontent.com/assets/8663934/7292134/8f5430e6-e9cb-11e4-99ac-d3f7bbef5e5d.gif)

**Comment by amodia** [comment]
Hi @aronasorman I determine the problem here. Its on `user authentication`  because when the admin user login it was successfully redirect to register device page and when the facility user log in it will redirect to page not found because the facility user is not a admin user.

I think the solution is only admin user can access to register device page and when the facility user login and when they click the register device link it will redirect on another page the say `only admins can register the device`.

I have a screenshot below showing on `line 31` when the user admin click the register device link it was successfully access the `register_public_key_client` method because it was determine by `login_required` method. On `line 42`, when the facility user login it can't access the `register_public_key_client` method because of `login_required` method so what happen it will redirect to page not found page.

![screen shot 2015-05-13 at 4 41 43 pm](https://cloud.githubusercontent.com/assets/8663934/7606882/857db384-f98f-11e4-9733-a52b5ce2791e.png)

**Comment by MCGallaspy** [comment]
This will be fixed by #3729. The user is being redirected to a url that doesn't exist defined by the LOGIN_URL setting, hence the 404.

**Comment by rtibbles** [comment]
Fixed in #3729
