### ISSUE TITLE
Error while upgrading language packs: No such file or directory: '...ka-lite\\kalite\\legacy\\data\\video_file_sizes.json'

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#3548]
Branch: develop (after fetching today's upstream)

Expected Behavior: Updating language packs should not report any errors (it never did for me until now).

Current Behavior: Updating language packs starts without problems, seems to be done correctly (state is "Up to date" for the selected language), but at the end of the process there is an error message:

Error during update: Error: [Errno 2] No such file or directory: 'D:\\github15\\ka-lite\\kalite\\legacy\\data\\video_file_sizes.json'

Steps to reproduce:
1. Log in as the either administrator or coach.
2. Choose "Manage > Language".
3. Press the "Upgrade" button for the desired language.

![error_subtitle_upgrade](https://cloud.githubusercontent.com/assets/1457929/7306161/7a87a872-ea03-11e4-88c9-ab46521b9ae1.png)

**Comment by benjaoming** [comment]
@radinamatic thanks for the great and perfectly detailed report.

We have cleaned up a lot of locations of data for the project and unfortunately our test system didn't catch all mistakes.

Will fix this now...

**Comment by radinamatic** [comment]
Ohhh, the pleasures of contributing to bug-catching... :)

**Comment by aronasorman** [comment]
Managed to replicate this error on develop. Merged Ben's PR, which now fixes this.

**Comment by radinamatic** [comment]
Confirming a successful language pack upgrade with this patch! :)

![success_lang_pack_upgrade](https://cloud.githubusercontent.com/assets/1457929/7323813/acd76de0-eab1-11e4-996f-d23636c66f48.png)

**Comment by benjaoming** [comment]
Thanks for checking back in with a confirmation @radinamatic :)
