### ISSUE TITLE
Adding to INSTALLED_APPS in local_settings.py deletes all existing INSTALLED_APPS

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#3552]
Branch: develop

Expected Behaviour: Adding INSTALLED_APPS in local_settings.py should concatenate it to the tuple of INSTALLED_APPS.

Current Behaviour: Adding INSTALLED_APPS in local_settings.py overwrites the tuple of INSTALLED_APPS.

@benjaoming this seems to have changed with your latest changes in develop, but I can't for the life of me see where this might be happening. Any ideas?

**Comment by benjaoming** [comment]
First, I'll say have to things the harsh way: Of course that shouldn't concatenate anything!! That would be pure black magic!!

But I can understand that there may be project settings that would expect this. What's your take on this @rtibbles ?

**Comment by benjaoming** [comment]
I wasn't aware that this was a convention, but do we want to keep it? I don't mind breaking bad conventions at some point, but I wouldn't wanna break them without introducing a proper alternative... so since the whole project refactor is not in place yet, it might be better to keep it...

**Comment by benjaoming** [comment]
Sorry, I didn't answer the last part :) Where things are happening is in `kalite.settings.base`. At the very bottom.

**Comment by rtibbles** [comment]
@benjaoming I am quite happy for bad conventions to be broken, I assume in future the way we would add something like this would be through the plugin architecture you had previously proposed?

**Comment by benjaoming** [comment]
Not the plugin architecture per say, but the settings arch that would be
part of splitting project logic from app logic... so I'm all for keeping a
`settings.local` pattern where you can put local settings there.. it can be
quite convenient. In the longer run, it's easier though to use perhaps a
few common options for the `kalite` command or environment variables with
one's own project such as "DJANGO_SETTINGS_MODULE=my_project.settings
kalite start".

We could even create a helper function for kalite to bootstrap a custom
django project environment `kalite create_project` or something.

The difference in `settings.local` from the old local_settings.py method
will be that settings can be imported from `settings.local` without
circularity, so you could just do this in `settings.local` :

    from settings.base import INSTALLED_APPS
    INSTALLED_APPS= list(INSTALLED_APPS) + ["windows_xp"]

**Comment by benjaoming** [comment]
Not the plugin architecture per say, but the settings arch that would be
part of splitting project logic from app logic... so I'm all for keeping a
`settings.local` pattern where you can put local settings there.. it can be
quite convenient. In the longer run, it's easier though to use perhaps a
few common options for the `kalite` command or environment variables with
one's own project such as "DJANGO_SETTINGS_MODULE=my_project.settings
kalite start".

We could even create a helper function for kalite to bootstrap a custom
django project environment `kalite create_project` or something.

The difference in `settings.local` from the old local_settings.py method
will be that settings can be imported from `settings.local` without
circularity, so you could just do this in `settings.local` :

```python
from settings.base import INSTALLED_APPS
INSTALLED_APPS= list(INSTALLED_APPS) + ["windows_xp"]
```

**Comment by aronasorman** [comment]
Will be working on this.

**Comment by aronasorman** [comment]
Here's your culprit: https://github.com/aronasorman/ka-lite/blob/7a4df9a9aeab85ebd7352596f9d72733a1233e5d/kalite/settings/base.py#L331-334

I believe it's @benjaoming who added this. @benjaoming are we free to remove this?

**Comment by aronasorman** [comment]
*free to remove it for now, since we haven't ported to a more robust settings scheme.

**Comment by benjaoming** [comment]
@aronasorman the fix is given above, no you shouldn't remove it since it's importing things that can potentially be intended to overwrite other settings options.

AFAIK it's only the INSTALLED_APPS that has the weird behaviour of being supposed to be concatenated to the existing list.

**Comment by benjaoming** [comment]
Well, the fix is somewhat given above, but let me make a PR and hopefully that should be the end of this :)

**Comment by aronasorman** [comment]
@benjaoming should we then add a warning that we're moving to settings.local then, and deprecating local_settings.py?

**Comment by benjaoming** [comment]
@aronasorman 

Yes, that's a really good idea!! :+1:

**Comment by EdDixon** [comment]
I am just becoming aware of the incredible flexibility local_settings.py provides is there an alternative in the works (perhaps the kalite command?) I have read through kalite help and kalite help manage pages but I do not recall it having abilities to do things like point to the client to a different central server etc and these features have been extremely useful in testing and offers potentials for layers of future features downstream. What will the alternative be?

**Comment by benjaoming** [comment]
@EdDixon yes but it isn't done, see #3611
