### ISSUE TITLE
Empty modal dialog with simplified login 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#3553]
Branch: develop (with latest upstream)

Expected Behavior: Pressing the "Login" button should open the modal dialog (with simplified login option if you have it in local_settings.py).

Current Behavior: After fetching the latest upstream I tried to login and got an empty modal:

![empty_modal](https://cloud.githubusercontent.com/assets/1457929/7324059/5e32a1da-eab3-11e4-9e65-cd539cd9f22c.png)
 
Had a nagging suspicion it had to do with simplified login that I had activated to work on another feature, and low and behold, login modal opened correctly after I set "SIMPLIFIED_LOGIN = False" in local_settings.py.

Steps to reproduce:
1. Try to login after setting "SIMPLIFIED_LOGIN = True" in local_settings.py.

**Comment by aronasorman** [comment]
@radinamatic can you check if this is fixed with the latest develop?

**Comment by radinamatic** [comment]
Fixed, closing!
