### ISSUE TITLE
Abandon icomoon classes and use Bootstrap bundled Glyphicons instead

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#3554]
Currently we are using specially imported icomoon fonts for our topic tree icons.

As we have Bootstrap 3 embedded, it makes sense to use the glyphicons that come bundled with it, rather than adding an extra set of icons to maintain.

@jtamiace What are your thoughts on this? It would basically mean redefining our icon classes with glyphicon definitions.

**Comment by jtamiace** [comment]
![teacher](https://cloud.githubusercontent.com/assets/6668144/7357373/2c278e8a-ece3-11e4-95f4-f11ab3b2f900.PNG)
Image for reference.
 
I'd be fine with using glyphicons, but the only thing is that there is no icon available that conceptually matches the 'language' tab and you can't customize.
http://getbootstrap.com/components/#glyphicons-glyphs

Suggestions if there is a switch to glyphicons:
Users:
![user](https://cloud.githubusercontent.com/assets/6668144/7357648/06a660c6-ece5-11e4-9875-785f14690ec4.PNG)

Facilities: 
![facility](https://cloud.githubusercontent.com/assets/6668144/7357661/164c3848-ece5-11e4-8224-c3c0116ef25c.PNG)

Videos
![video](https://cloud.githubusercontent.com/assets/6668144/7357668/2f514e28-ece5-11e4-9115-ef291b5bed84.PNG)

Language??
![lang1](https://cloud.githubusercontent.com/assets/6668144/7357706/57cd665c-ece5-11e4-9fb4-88ee4f7130f0.PNG)
![lang2](https://cloud.githubusercontent.com/assets/6668144/7357731/7e5bbd50-ece5-11e4-8d59-a0b410e48ff7.PNG)
![lang3](https://cloud.githubusercontent.com/assets/6668144/7357765/b7da3408-ece5-11e4-92b5-7f99035b9168.PNG)


I could insert the images that i made in illustrator, but the issue with that would be that I would have to make style changes to the .AI file if there are changes to the color of the interface in the future. 
But its easier to make changes to an AI file than to maintain the icomoon icons?

Bootstrap's glyphicons would be most consistent for the development side, but may not have icons that make the most sense.

**Comment by Antrikshy** [comment]
How about Font Awesome? Add icon library once, use anywhere. We could fall back on it for anything missing in Glyphicons.

**Comment by radinamatic** [comment]
I like Font Awesome, but irregardless of icon set we decide to use, here is something to keep in mind to ensure their accessibility. Basically, icon element is not enough on its own, you need to wrap it into another element which will render it invisible to screen readers (with aria-hidden="true"), and then add a second span with text only for screen readers (class="sr-only"): 
```
<span aria-hidden="true">
      <i class="fa fa-home"></i>
</span>
<span class="sr-only">Home</span>
```
For detailed explanation, see the post by @hanshillen here: 
[Making font based icon sets accessible](https://github.com/FortAwesome/Font-Awesome/issues/6133) 

*Make that another item for the KA Lite A11y style guide... :)*

**Comment by rtibbles** [comment]
Punting.

**Comment by Antrikshy** [comment]
If we are migrating, I can help.

**Comment by radinamatic** [comment]
Did we decide anything regarding the icon fonts, Glyphicons or Font Awesome? @jtamiace @rtibbles 
I'm working on content rec stuff that has some `icomoon` classes, it would be a good moment to take them out of the equation...

**Comment by jtamiace** [comment]
I agree with abandoning icomoon altogether, but if we're not going to use custom fonts (which requires a third party like icomoon) and to keep the libraries used to a minimal, I think we should use both glyphicons and font awesome, relying primarily on glyphicons and resorting to font awesome when there's something that glyphicons doesn't have (Ant's earlier idea).

**Comment by jtamiace** [comment]
Actually.... taking a look at the material design for bootstrap that @rtibbles linked to earlier (http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html), there are 740 more icons that are available for use. If we do ever decide to switch to that, then we could probably scrap icomoon and font awesome.

**Comment by radinamatic** [comment]
So conclusion is to stick to glyphicons, as with material design we might not need/use Font Awesome after all?

**Comment by rtibbles** [comment]
Yep, let's go with that. Feel free to clear away icomoon, @radinamatic.

**Comment by radinamatic** [comment]
This is a version with `glyphicon-pencil` instead of `icomoon` one:

![gly-pencil](https://cloud.githubusercontent.com/assets/1457929/8656173/47547b38-2996-11e5-92b1-431d7fc3de7a.png)

Keeping this local for now, will put a PR after `browserify` stuff to avoid CSS conflicts.

**Comment by rtibbles** [comment]
Shouldn't be an issue, I've not touched css. YET!

**Comment by rtibbles** [comment]
Not going to happen within the scope of KA Lite.
