### ISSUE TITLE
Margin issue with the fields at the login modal dialog.

### ISSUE THREAD

**Issue by cpauya** [learningequality/ka-lite#3558]
**Branch** develop
**Target** 0.14.x
**Browser** Firefox v36.0.4
**Expected Behavior** The username and password fields should have left and right margins.
**Current Behavior** Not sure if this is intended behavior but currently there's no left and right margins for the fields.  Please see attached screenshot.

![screenshot 2015-04-25 14 18 12](https://cloud.githubusercontent.com/assets/175580/7331879/393a3462-eb56-11e4-860e-acce0481014b.png)

**Comment by Antrikshy** [comment]
I was thinking of taking a look at this myself, unless someone else has grabbed it.
