### ISSUE TITLE
Language pack downloading interface needs styling overhaul

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3563]
Examples of things needing improvement:
- Beta language pack checkbox/text positioning
- Position/padding on progress bar areas
- Spacing on language pack metadata in top-left panel
- Overall padding/alignment in bottom panel

![image](https://cloud.githubusercontent.com/assets/618416/7356883/0d34cd1a-ece0-11e4-9155-bb90a9d30309.png)

**Comment by Antrikshy** [comment]
Did someone say "styling overhaul"?

Assign me!

**Comment by aronasorman** [comment]
You asked for it.

**Comment by Antrikshy** [comment]
Is there a reason this space exists?

![screen shot 2015-04-27 at 4 38 18 pm](https://cloud.githubusercontent.com/assets/6601788/7360123/e52e1c88-ecfb-11e4-9cda-78631e8eb200.png)

@rtibbles?

**Comment by rtibbles** [comment]
It's where the download progress indicator goes, methinks.

**Comment by aronasorman** [comment]
It's all up for an overhaul though @antrikshy. You can change the location of the progress indicator.

**Comment by rtibbles** [comment]
Some styling fixed in #4630 we're not changing any more than that!
