### ISSUE TITLE
Language admin page cannot connect to server (develop branch)

### ISSUE THREAD

**Issue by Antrikshy** [learningequality/ka-lite#3565]
It was working at one point and now it's not. Browser cannot seem to access `http://staging.learningequality.org/api/i18n/language_packs/available/0.14?callback=jQuery1910085123504512012_1430175841598&_=1430175841599`, although I can open it directly. So language packs don't load. I have tried setting `CENTRAL_SERVER_HOST = 'hub.learningequality.org'` and tried multiple browsers. It's a server bug on this end.

It also seems to continuously ping that URL every second.

Videos tab loads properly.

**Comment by jamalex** [comment]
We're probably not building 0.14 language packs yet? @aronasorman?

**Comment by jamalex** [comment]
@aronasorman says we are. MYSTERY UNSOLVED!

**Comment by Antrikshy** [comment]
This is so strange. I deleted my database, ran `kalite start` to recreate it. Then ran `kaserve` and the languages page loaded properly. It *was* still trying to ping the server every second. The next time I visited the page, it cannot connect to server again. Also @aronasorman, it does get a status 200 every time it pings the server.

![screen shot 2015-05-15 at 2 49 32 pm](https://cloud.githubusercontent.com/assets/6601788/7662471/ae4a37b4-fb11-11e4-973f-4d8180534897.png)

**Comment by Antrikshy** [comment]
Also seems like one-click registration does not work on my installation. I have to do manual registration using an account on the central server and register KA Lite that way. Then the first time I get to the language page, it connects. Refreshing breaks it.

**Comment by jamalex** [comment]
Hmm, strange. Could you include the full contents of your local_settings.py?

It's getting a 200 when pinging the local server (that's to check the status of any possible downloads, to update the progress bar). But it might be getting something different when pinging the central server.

Can you report the specific error the browser is having when accessing `http://staging.learningequality.org/api/i18n/language_packs/available/0.14?callback=jQuery1910085123504512012_1430175841598&_=1430175841599`?

**Comment by Antrikshy** [comment]
Oh yes, it *is* pinging the local server. So *that's* how it works. I only have `DEBUG = True` in that file. @aronasorman checked that last time we tried to wrestle with this. I get no error when I access that link. I do see language packs.

![screen shot 2015-05-17 at 8 29 02 pm](https://cloud.githubusercontent.com/assets/6601788/7674034/965d47e0-fcd3-11e4-8f81-37b8a9ddf607.png)

Also, the issue persists in multiple browsers. Definitely something to do with the local server or somehow this installation. I'm running Python 2.7 (straight from python.org) on OS X Yosemite. :-/

**Comment by jamalex** [comment]
> I do see language packs.

In the dropdown list? But you said that when you refresh, then you don't see them? Is the background request to the staging server API url happening after that second refresh? Or any other JS errors suggesting why it might not be displaying the language packs in the dropdown anymore? Race condition...?

**Comment by Antrikshy** [comment]
I meant I get the response in above screenshot. I'll check later, but IIRC the console does say it could not access the language pack resource (even though I can clearly see the response when I copy paste that URL from the console).

**Comment by MCGallaspy** [comment]
Any idea on how to reproduce this @Antrikshy?

**Comment by Antrikshy** [comment]
@jamalex, @aronasorman and I tried debugging and it seems like it's a problem in my computer. It happens in all three browsers and even on the demo server. Haven't been able to isolate the problem. Tried turning off firewall. AFAIK it only happens on the language tab.

I guess you can close it and wait for any reports from other Mac users.
