### ISSUE TITLE
Ambiguous setup question

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#3567]
During `kalite manage setup` I'm asked this:

> Please enter a name for this server (or, press Enter to use 'fair-server'):

Which confuses me -- is it a hostname, a domain, a name to display for the user? It would be nice if the text stated the purpose.

Also, @aronasorman how about if we have a label called "easy-pickings" ? It would be nice to collect little things like this so that acts of procrastination can find good use :)

**Comment by MCGallaspy** [comment]
I think that's the "beginner" label.
