### ISSUE TITLE
assessment.zip 404

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#3568]
Running current develop `kalite manage setup`

```
Starting in version 0.13, you will need an assessment items package in order to access many of the available exercises.
If you have an internet connection, you can download the needed package. Warning: this may take a long time!
If you have already downloaded the assessment items package, you can specify the file in the next step.
Otherwise, we will download it from https://learningequality.org/downloads/ka-lite/0.14/content/assessment.zip.
Do you wish to download the assessment items package now? (yes or no) yes
Downloading assessment item data from a remote server. Please be patient; this file is big, so this may take some time...
Downloaded size:  Unknown
Downloading file...HTTPError: 404 Client Error: Not Found
```

**Comment by benjaoming** [comment]
@jamalex hope it's okay to assign you ;) it's just pretty critical to get the assessment.zip, and I think it's a matter of just copying the 0.13 tree for now?

**Comment by aronasorman** [comment]
Ah it's because we don't have 0.14 assessment zips for now :) I can make one now by just copying the one we have from 0.13 to 0.14. Although @rtibbles @jamalex are we planning to pull in the latest KA content? If so, we might want to generate a new assessment zip for 0.14.

**Comment by jamalex** [comment]
We'll want to pull in the latest KA content right before the code freeze, I think. In the meantime, I've copied the old assessment.zip into 0.14.

**Comment by benjaoming** [comment]
Thanks for quick processing @jamalex!!
