### ISSUE TITLE
Availability stamping needs to be enabled on all videos when there is a backup video source

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3570]
On the demo server, we include the setting:
`BACKUP_VIDEO_SOURCE = "http://s3.amazonaws.com/KA-youtube-converted/%(youtube_id)s.%(video_format)s/%(youtube_id)s.%(video_format)s"`
which enables videos to be loaded directly from Amazon. This means that all videos should be marked as available in the sidebar when this setting is on. We also need to make sure it's using that URL pattern to load the videos (right now it doesn't seem to, but that may be because of the stamping as well).

e.g. see http://demo.learningequality.org/learn/khan/test-prep/mcat/cells/cytoskeleton/

**Comment by aronasorman** [comment]
Looks like it works on 0.13.x now? Do you guys know which commit fixed this?

**Comment by aronasorman** [comment]
Looks like it's this commit: https://github.com/learningequality/ka-lite/commit/e65e31403b99fe554465b1bd90b2df836cf496a9.
