### ISSUE TITLE
Loading animation/text needed on potentially slow places in the site

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3571]
Branch: master (0.13)

Observed: A number of pages/interfaces on the site are slow to load, and just leave the user "hanging" while looking at an empty space.

Desired: We should put a loading animation or at least some "Loading . . ." text in these places, which then gets replaced when the content loads and is rendered.

Hotspots:
- The Learn tab, on first page load. The topic tree data takes a while to load in, so we stare at an empty sidebar for a bit.
- The exercises sometimes take a while to render. We used to have "Loading..." text in there.

**Comment by Antrikshy** [comment]
How about an similar to this for the Learn tab? 

![screen shot 2015-04-28 at 12 13 45 pm](https://cloud.githubusercontent.com/assets/6601788/7378122/0f2701cc-eda0-11e4-9dff-296a2771e258.png)

**Comment by rtibbles** [comment]
What would you think about having a dismissable modal overlay that we could use generically across the site to indicate loading?

**Comment by Antrikshy** [comment]
Yeah, I was thinking of that actually. How would we handle dismissing it though? I'm trying to figure out how to dismiss this overlay through Backbone when the topic tree is loaded. If there is a nice, standard way you can think of, I could easily put this in `base.html`.

**Comment by rtibbles** [comment]
http://getbootstrap.com/javascript/#modals-methods

**Comment by jamalex** [comment]
@rtibbles I like the idea of something reusable. But we wouldn't really want the user to dismiss it, would we? And rather than a modal by default, perhaps it could be applied to any DOM element, so we could have the overlay apply to only a specific part of the page?

**Comment by Antrikshy** [comment]
Wait, user-dismissable? I don't understand what @rtibbles is saying.

**Comment by jamalex** [comment]
(That way, we could, for example, add an overlay on the exercise area showing it's loading, without blocking nav away from there to another page.)

**Comment by jamalex** [comment]
I would prefer to avoid modals.

**Comment by rtibbles** [comment]
My reason for having it be user-dismissable is as a fail safe in case we fail to dismiss it properly.

But yes, having it just apply to the DOM element would work too.

**Comment by rtibbles** [comment]
In fact, we could just add it as a method to the BaseView?

**Comment by Antrikshy** [comment]
Ohh. Yes, Bootstrap modals can be dismissed programatically. I meant to ask how can we detect when the pages and modals have been initialized? Is there a nice, standard way to do that?

**Comment by jamalex** [comment]
> In fact, we could just add it as a method to the BaseView?

Nice. Then any view can just be "disabled", and the BaseView can handle adding a layer on top of its element to indicate this in a visually consistent way across the site.

**Comment by Antrikshy** [comment]
The overlay I have is nice and light. It can simply be removed from the DOM once everything has been initialized.

**Comment by jamalex** [comment]
> The overlay I have is nice and light. It can simply be removed from the DOM once everything has been initialized.

Yep, seems nice as a first pass (we may want to consider some animation in there later). The suggestion is just to do it in a reusable way.

**Comment by rtibbles** [comment]
@Antrikshy presumably it would just get overwritten when the render method is finally called?

**Comment by Antrikshy** [comment]
Ah yes, `render` is called at the very end. Adding it to BaseView to selectively highlight parts of the UI would be nice. I should look into this BaseView.

**Comment by jamalex** [comment]
Probably good to use counters, in case there are multiple things needing loading.

A method `loading_started` would add 1 to `this._loading_counter`, and show the overlay.

A method `loading_complete` would subtract 1 from `this._loading_counter`, and hide the overlay if `this._loading_counter == 0`.

**Comment by rtibbles** [comment]
Do you mean for this instance, or as part of the general pattern? I think
just having a loading method is preferable and then letting people call it
and render as needed is best. Would rather avoid too much front end magic.

**Comment by EdDixon** [comment]
In addition to the side bar some of the content within the assessments can occasionally be a little slow to render as well. I can not thing of a specific example at the moment but will try to capture a quick video of one next time it is encountered. This content is also apparently not cached because I noticed returning to it still causes the same delay. A loading notification within that space if possible would be nice. I will try to find a specific example and update here soon.

**Comment by rtibbles** [comment]
Fix in for this, but punted to 0.15.

**Comment by aronasorman** [comment]
The learn tab is snappy enough even on the RPi 2. It's nice to have this but we should open issues for specific pages.
