### ISSUE TITLE
Search autocomplete is ugly and twitchy

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#3578]
Something weird has happened to the styling of search autocomplete between 0.13 and develop.

This may have been my fault.

Any CSS wizards available to hunt down where the styling has gone?

Also, I think this has always been the case, but it is twitchy when you mouse over it.

@jtamiace @Antrikshy?

**Comment by Antrikshy** [comment]
:D

**Comment by rtibbles** [comment]
@Antrikshy It's because we lazily load the data when people focus into the search bar. This is to not load data from the server if it is not needed.

Another thing to bear in mind is that the search autocomplete dropdown list is styled much better on 0.13.x, so some of this is a regression issue. Take a look at the differences in the CSS for inspiration.

**Comment by EdDixon** [comment]
Other than different icons I did notice that the auto-complete list that is generated seemed to have different items listed? Screens show the difference between the two? 
![2015-05-01_17-40-51](https://cloud.githubusercontent.com/assets/4349806/7438909/15896f28-f02a-11e4-91fc-c505dd9f6bd3.png)
![2015-05-01_17-42-02](https://cloud.githubusercontent.com/assets/4349806/7438913/22859d96-f02a-11e4-946b-ee8d7383a488.png)

**Comment by Antrikshy** [comment]
@rtibbles Looks like the all-caps are all gone now. It *is* a little twitchy and could use a little bit of cleanup. I'll work on it.

**Comment by Antrikshy** [comment]
The twitchiness is really hard to isolate. I have no idea what's causing it.

**Comment by rtibbles** [comment]
It is either changing border sizes, padding or margins. Can't imagine
anything else that would be causing it.

**Comment by MCGallaspy** [comment]
Seems to be a few issues with the search bar. I'm stealing this to work on all three (#3349, #3345 as well) unless you already have a fix for this @Antrikshy?

**Comment by Antrikshy** [comment]
Oh yeah, that's perfect. I'm working on some stuff with content curation anyway.

**Comment by rtibbles** [comment]
Fixed in #3766
