### ISSUE TITLE
Support customizing the user's home directory

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#3599]
Fix the need to access kalite.settings from outside of the django environment in #3585

@66eli77

**Comment by benjaoming** [comment]
Adressed in PR #3591

**Comment by benjaoming** [comment]
@66eli77 are you reading this? :)

It means you should use KALITE_HOME on Android to ensure that user data is stored in a writeable place. Will you be able to work on that?

**Comment by 66eli77** [comment]
yeah, thanks for the notice : )
