### ISSUE TITLE
Download new videos in bulk

### ISSUE THREAD

**Issue by timon-langlotz** [learningequality/ka-lite#3608]
I have been trying to download the new videos, but in btsync it just says "pending approval". And even if I would get those videos, there are not the new videos in there which were added with 13.0, right?
If anybody knows where I could get them in a compressed format, I would be very happy!

By the way, nice work with the update. Looks really good!
Cheers

**Comment by EdDixon** [comment]
COnfirming these issues even with the proper key from the new docs the version of BT Sync is reporting it as an invalid key?

**Comment by aronasorman** [comment]
Hi @timon-langlotz! Update on this issue: @EdDixon and I are looking into why btsync is behaving this way. @EdDixon is also making a new set of compressed videos for the 0.13 videos.

**Comment by timon-langlotz** [comment]
Thanks! :)

**Comment by aronasorman** [comment]
Another update: We're moving to a regular torrent download for compressed videos.

**Comment by MCGallaspy** [comment]
@aronasorman @jamalex 
So apparently the state of things is that one needs the pro version of BTSync, and then after one enters the key that can be found in our docs it needs to be approved. Once we are able to offer an alternative we will also need to update the docs to reflect this situation.

**Comment by jamalex** [comment]
It's for 0.14 (so it includes some new videos not needed for 0.13), but here's a new torrent:
https://learningequality.org/downloads/ka-lite/0.14/content/ka-lite-0.14-resized-videos.torrent
(32GB total)
