### ISSUE TITLE
Write documenation on customizing kalite

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#3611]
1. We need a deprecation warning in the documentation on using local_settings.py and other deprecated ways of setting up kalite.
1. Howtos in two different chapters:
    1. Use available settings, for instance `kalite command --settings=kalite_project.settings.android`
    1. Write your own settings module and use it with `kalite command --settings=my_module` in which the first line does
```python
from kalite_project.settings.base import *
SOME_CONFIG = 123
```

For later decision: Maybe `kalite_project` is a bad name, maybe we can nest it in `kalite.project`.
Also later decision: Writing a guide on how to setup ones own project with kalite.. I don't think this will enter in 0.14.

**Comment by aronasorman** [comment]
We also need to put in a blurb about this on the release notes section of the docs.

**Comment by timon-langlotz** [comment]
How can one currently set a custom content folder?

**Comment by aronasorman** [comment]
Hi @timon-langlotz,

[Steps 2-4 on the "Download videos by bulk" section answer your question](https://learningequality.org/docs/usermanual/userman_admin.html#downloading-videos-in-bulk). Although it's embedded in another topic. Would be nice to have an entry for that in the FAQ section.

**Comment by aronasorman** [comment]
made an entry in the FAQ section: https://github.com/learningequality/ka-lite/pull/3613

**Comment by timon-langlotz** [comment]
Hi @aronasorman,

Thank you for your answer! But this was not my question. The original author of this issue mentioned that "We need a deprecation warning in the documentation on using local_settings.py ...". Therefore I was wondering how I should now set the content root folder.

Concerning the answer you gave (and another problem I am having): With the btsync version > 2.0, it just says "Pending approval" for weeks. I have managed to download the videos with an older version (~1.4) of btsync, however not with the current one. This is also why I opened Issue #3608.

**Comment by aronasorman** [comment]
If by currently you mean the "now-recommended" way of customizing KA Lite in the develop branch, then you just have to make small tweaks to your `local_settings.py`:

```python
from kalite.settings.base import *
CONTENT_ROOT = "blah"
```

If that's what you're asking. Of course, we only deprecated the old way of doing things, so it should still work (but you should definitely update your local settings!).

re: btsync -- lemme reply on that issue :)

**Comment by timon-langlotz** [comment]
Alright, thanks. I thought this was already deprecated in master branch. Sorry! Thanks anyway! :)

**Comment by benjaoming** [comment]
@aronasorman thanks for following up... just a quick note... remember that by deprecating `local_settings`, we cannot advice to continue a new pattern inside an old deprecated `local_settings` module.. people deploying kalite have to stop injecting their own modules into the kalite codebase entirely!

One of the reasons for entirely stopping to mention `local_settings` in examples: `kalite.settings.base` will still attempt to import `local_settings` so in case you import `kalite.settings.base` in `local_settings`, you get circularity.

So that's all been considered and that's why I chose the above example of how to move on with custom settings :)

**Comment by aronasorman** [comment]
I believe the next step to closing this issue is to add the deprecation warning and steps to customize KA Lite in our sphinx docs. @benjaoming would you have time to do that?

**Comment by benjaoming** [comment]
I believe that the current codebase is able to accommodate some of the right conventions, but before writing anything, I still think we should do the refactor that initiates `kalite.project` and moves anything related to our default django project in there.

**Comment by MCGallaspy** [comment]
I don't find this:
>Write your own settings module and use it with kalite command --settings=my_module

A satisfactory solution for the average user. I don't think we should officially deprecate `local_settings.py` (especially since it still works!) until we provide a viable alternative, namely a tool or an web interface which allows users to configure the settings or generate a custom settings module they can use.

**Comment by MCGallaspy** [comment]
And that said, I vote that we punt this issue to 0.15, since there's a project in the works for a web view on the settings.

**Comment by benjaoming** [comment]
@MCGallaspy - where should the average user place the local_settings.py file? ;)

We're deprecating this for good reasons, and it's been discussed, I'm happy to repeat stated points, but the broken way of using INSTALLED_APPS is a great place to start.

**Comment by MCGallaspy** [comment]
I'm aware there are issues, but what we're essentially making customization substantially more complicated for the end user without a viable alternative. Especially on windows, where the only way to launch the app with a custom settings module will be from the command line.

**Comment by benjaoming** [comment]
No it won't -- local_settings are *deprecated*, not removed! ;)

**Comment by arnoan** [comment]
If I may chime in: I think it is crucial for many implementations to define their own custom content location. (Especially if using RaspberryPi as the server it's a must.) Currently there does not seem to exist a viable alternative for defining custom folders other than creating a custom local_settings.py. So I am grateful this workaround still exists for the time being. 

On a side note: It took a long time to figure out that the new exercise material does not belong into the root level of the custom content folder but rather into a "khan" subfolder.

**Comment by benjaoming** [comment]
>  Currently there does not seem to exist a viable alternative for defining custom folders

You can create custom settings as with any other Django project and point Django to its settings env with DJANGO_SETTINGS_MODULE og --settings.

If this isn't viable, then we have a problem and share that problem with the rest of the Django world :)

**Comment by MCGallaspy** [comment]
> If this isn't viable, then we have a problem and share that problem with the rest of the Django world :)

The "problem" isn't that we can't define custom settings, it's that creating a settings module is much more complicated than overriding a few settings in `local_settings.py` from an end-user perspective. "[C]reate custom settings as with any other Django project" is emphatically not something we should expect end-users to be able to do without some help.

**Comment by benjaoming** [comment]
@MCGallaspy Is creating a local_settings.py much different from that? The Windows installer will put kalite in C:\Program Files\Some\Path, Mac installer will put it somewhere else, the PyPi on Linux might put it in /usr/local/lib/python2.7/site-packages/kalite -- already you have the task of explaining people exactly where the application package is located... and then you have the problem if they re-install and their stuff is overwritten or package managers that fail to do their job because of unclean files. Generally you wouldn't want users modifying distributed resources, and putting a file within the distributed paths kind of qualify for that.

The UIs and CLIs should provide an alternative to understanding Python and creating a settings module for limited, but common cases of customization. I can easily see a UI that solves these things automatically and a clean interface for people who want more, because they know Python anyways.

**Comment by MCGallaspy** [comment]
> Is creating a local_settings.py much different from that? 

Maybe not, but it's what people are used to. I understand it's not great, but I'm suggesting we do not change it until we have something which feels equally simple. Even deprecating it without removing it will almost certainly rustle someone's jimmies.

Now that I have a better grasp of the issue, I suppose all I'm suggesting here is that we don't deprecate local_settings.py, or that if we must then we at least mention that it still works. Plus, I suspect that for some installation methods (Windows, I'm thinking of you!) `from kalite.settings.base import *` won't _just work_ since the `kalite` module isn't on the python path. In that case, local_settings.py will indeed be the far simpler solution than creating a custom settings module and ensuring that the interpreter has the `kalite` module in its path!

**Comment by benjaoming** [comment]
> I understand it's not great, but I'm suggesting we do not change it until we have something which feels equally simple.

We're still not removing it. It's being deprecated. Jimmies may be rustled, but that will only cause for a good opportunity to explain why it's deprecated.

> Plus, I suspect that for some installation methods (Windows, I'm thinking of you!) from kalite.settings.base import * won't just work since the kalite module isn't on the python path.

It'll work provided that you are using it with the `kalite` command that's made to fix people's paths. It's actually a proxy for kalitectl. As for Windows, neither paths for Python nor commands like `kalite` will work unless the installer can fix it or the user decides to follow "usual" Windows/Python practice of manually adding it.

One more point: local_settings.py has to die because it is "magic". If you put INSTALLED_APPS there, it won't overwrite the INSTALLED_APPS of `kalite.settings`... it will be magically concatenated to it. Thus, for instance, you can never remove something from INSTALLED_APPS. But more importantly, this is unexpected silly behaviour. Other settings overwrite existing settings.

**Comment by benjaoming** [comment]
Brewing some docs over in #3925

**Comment by benjaoming** [comment]
Improved the docs for current standards, although a lot of settings miss descriptions.

For the future, our latest docs will be automatically built here:

http://ka-lite.readthedocs.org/
