### ISSUE TITLE
"Unknown command: kaserve"

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#3616]
Django 1.5 (don't know about later versions) unfortunately sets a global variable `_commands` which is causing problems when running cronograph as a thread. You can read a bit of background in the below code snippet.

I'm figuring out a solution after having disabled another piece of code that avoided the race condition in the first place.

```python
def manage(command, args=[], in_background=False):
    """
    Run a django command on the kalite project

    :param command: The django command string identifier, e.g. 'runserver'
    :param args: List of options to parse to the django management command
    :param in_background: Creates a thread for the command
    """
    # TODO(benjaoming): Why was this necessary? Had to be commented out because
    # get_commands imports django.conf.settings which should not be imported
    # outside of the command itself as DJANGO_SETTINGS_MODULE could have been
    # set from command line options.
    #
    # Follow-up May 6th: Apparently there was a kind race-condition because the
    # list of possible commands isn't thread safe... so once we have started
    # a background thread for command 1, and command 2 runs on top of that,
    # command 2 may fail saying for instance "Unknown command: 'kaserve'"
    # because the list of command was not ready-built.
    #
    # Best solution: Have this call not return until first entry thread has
    # finished building list of commands with get_commands()
    #
    # Original comment:
    # Ensure that django.core.management's global _command variable is set
    # before calling commands, especially the ones that run in the background
    #
    # get_commands()
```

@MCGallaspy I just wanted to loop you in on this, but I'll give a solution to this as soon as I'm back in the chair.

To get around it quickly, you can comment back in get_commands, but be warned that it will break when parsing a custom `--settings` option.

**Comment by MCGallaspy** [comment]
Would commenting out `get_commands()` affect use of the `manage` function?

**Comment by benjaoming** [comment]
@MCGallaspy no, it's a race condition only related to "kalite start" which starts a background thread for the chronograph and one for cherrypy (kaserve).
