### ISSUE TITLE
Huge size of KALiteSetup-0.13.1.exe [333.34 MB]

### ISSUE THREAD

**Issue by DragoonHP** [learningequality/ka-lite#3618]
What caused the sudden inflation in the setup file size? If I remember correctly, the 0.12.x series size was under 50 MB (and so was the develop branch of 0.13.x).

**Comment by aronasorman** [comment]
Hi @DragoonHP,

We now include the images and other assets needed for exercises created using Khan Academy's, Perseus framework. Without these, a majority of the new exercises won't work.

re: develop branch -- we don't include these assets as part of the repo. You have to download them manually.

I hope that answers your question,
Aron

**Comment by DragoonHP** [comment]
Thanks for the quick response. :)
