### ISSUE TITLE
Bulk-Download Videos link directs to the old FAQ

### ISSUE THREAD

**Issue by JGOODYEARUCSD** [learningequality/ka-lite#3619]
The link under "Help for downloading videos" directs to https://learningequality.org/ka-lite/faq/ while we now use https://learningequality.org/docs/faq.html 

![screen shot 2015-05-08 at 9 58 04 am](https://cloud.githubusercontent.com/assets/10428345/7541451/702abbae-f56a-11e4-817b-ac352c877b8d.png)

**Comment by aronasorman** [comment]
I think this is pretty critical, since we want to standardize on a single location for docs.

**Comment by foolchan2556** [comment]
I have created a PR https://github.com/learningequality/ka-lite/pull/3634 to fix that.
