### ISSUE TITLE
Read assessment items from zipfile

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3620]
@66eli77 mentioned that there's no noticeable performance impact, so I may take a stab at making this for 0.14.

Basically, we wanna have kalite check for `assessment.zip`. If it's there and it's for this version of KA Lite, we read from that zipfile ondemand for the needed assessment items instead of extracting them into the filesystem.

**Comment by aronasorman** [comment]
Another alternative: rather than placing assessment items in a zip file, we can also put them in an SQLite DB, where we can take advantage of its caching mechanisms.

**Comment by 66eli77** [comment]
To prevent repeating work, here's what have been done so far. A python script to create a subfolder file structure for khan folder(Perseus images); A python script to modify the assessmentitems.js making it accommodates the subfolder structure; A Django view that directly reads from the zip file and return a HttpResponse containing the image data to the requesting html

**Comment by aronasorman** [comment]
@66eli77 can you push your work to a branch in your repo? I'll just contribute in there, and we can make a PR once we're done.

**Comment by MCGallaspy** [comment]
> Another alternative: rather than placing assessment items in a zip file, we can also put them in an SQLite DB, where we can take advantage of its caching mechanisms.

Hmm, seems suspiciously like we're working on the same thing -- that is, an alternative to the current topic_tools stuff.

**Comment by jamalex** [comment]
@66eli77 is working on the static files (images), not the json/data. But
there might be some shared learning.

**Comment by 66eli77** [comment]
@aronasorman  here's the change made to read directly from zipped khan folder
https://github.com/66eli77/ka-lite/tree/read_image_from_zip

**Comment by 66eli77** [comment]
and here is the tools to modify the assessmentitems.js and rearrange the khan folder
https://github.com/66eli77/ka-lite-android-python27/tree/develop/tools

**Comment by 66eli77** [comment]
Updates for retrieving Perseus image from khan folder, the current approach does not require any change to kalite code base(potential change could be made, since it does not use Django or Cherrypy to serve the Perseus image, it might improve performance by stop using Django or Cherrypy when deal with Perseus image)
We only need to modify the assessmentitems.js file to enable it reads locally on Android.

**Comment by benjaoming** [comment]
This is part of #4311 as there are other items in the scope here. Closing this because I'm convinced we'll have this feature in the import/export commands, and the rest is up to the installers.
