### ISSUE TITLE
Caught in 'preloading loop' when accessing content from external HDD

### ISSUE THREAD

**Issue by arnoan** [learningequality/ka-lite#3621]
I came across another unintended behaviour of kalite I wanted to point out:

Branch: master (0.13.1)

When pointing kalite to search for the educational material in a custom location via creating a local_settings.py file in the 'kalite' subfolder kalite sometimes gets stuck in a 'preloading loop' upon trying to start the server. (See attached screenshot -> it keeps re-loading the content forever.)

![screenshot 2015-05-08 16 01 42](https://cloud.githubusercontent.com/assets/12040852/7544238/99f7a9e0-f5cb-11e4-80ab-b3210aa0c8cc.png)

So far this only happened to me when pointing kalite to an external USB hard drive. Never had any issues with internal memory or USB sticks. But with an old 160GB Seagate disk I can reproduce this behaviour repeatedly. 

What is more: As soon as kalite got stuck in this boot loop once, it subsequently will always get stuck even if the local_settings.py is removed or points back to the standard content folder. Reinstalling the server and keeping the database (kalite manage setup, keep database) does not fix the issue but only a clean install of the database will (kalite manage setup, delete database). 

Further it seems to make a difference whether kalite is pointed to the custom folder during the first start of a new installation already or only at a later point. When inserting the custom locale_settings.py before firing the server up on a new installation for the first time it always worked so far. When starting it once with the standard folder, then stopping the server, inserting/changing the locale_settings.py to external HDD and starting the server again it is likely to get stuck. It also indicates the successful identification of xyz new videos still (so the folder and its contents are read correctly) but then gets stuck in the loop again.

Not a big deal for me since I don't usually change the content location anymore once a setup is completed. But could create trouble for some since it seems to render the database unusable after the loop occurred once.

(Running on a MAC with Yosemite 10.3.3, Python 2.7.9 and kalite 0.13.1)

**Comment by MCGallaspy** [comment]
Very interesting, so you're saying changing the content location using `local_settings.py` after you have already started the server causes an error. What setting(s) did you change? Did you download any content after setting up the server but before changing the content location settings?

**Comment by arnoan** [comment]
The server is not running while I implement the changes. 
Rather changing (or creating local_settings.py) after the server had been started and stopped at least once after the initial installation causes the loop for me to happen (not always though, but once it happens it's permanent). 

The only change is creating a local_setting.py file pointing to a new content location. So it contains only one line e.g. CONTENT_ROOT="/Volumes/160GB/ka_content/".

One thing that comes to my mind right now: I so far did not copy the new exercise material that is located in ./content/khan to the external HDD that sometimes triggers the loop. Might be related.

**Comment by aronasorman** [comment]
@MCGallaspy @arnoan This is a known bug. It does end **eventually**, but it may take a while. The workaround for now @arnoan is to just wait, particularly if you're using an HDD :)

@MCGallaspy I think this is due to overaggressive cache clearing. Let's leave this issue open so that we can track the progress on this.

**Comment by jamalex** [comment]
I just experienced the pain of the "overaggressive cache clearing" on the demo server, after clearing the "content" folder (which had a ton of videos) and starting the server back up. By my estimate, it would have taken several human lifetimes to complete. Even though life is short, this seems unacceptably long. :) I ended up just deleting the database and starting from a fresh one; not ideal.

Is this the primary issue we're using to track this, or is there another?

**Comment by aronasorman** [comment]
@jamalex this is the primary issue now.

**Comment by MCGallaspy** [comment]
I suppose the culprit is the combination of `invalidate_on_video_delete` in `update/__init__.py`, because of the decorator `@receiver(pre_delete, sender=VideoFile)` and the fact that videoscan potentially makes a lot of deletions:
```python
        def delete_objects_for_missing_videos(youtube_ids_in_filesystem, videos_marked_at_all):
            ...
            for chunk in videos_needing_model_deletion_chunked:
                video_files_needing_model_deletion = VideoFile.objects.filter(youtube_id__in=chunk)
                video_files_needing_model_deletion.delete()
                ...
```
Perhaps the solution is to prevent execution of the listener `invalidate_on_video_delete` and then invoke it __once__ after all deletions are made.

**Comment by MCGallaspy** [comment]
Also, seems like there are two identical `invalidate_on_video_delete` functions. Is this intentional or an oversight?

**Comment by aronasorman** [comment]
Probably from a merge conflict. I think python's behaviour is to use the most recent definition.

**Comment by MCGallaspy** [comment]
What about when they're from different modules?

**Comment by MCGallaspy** [comment]
Anyway, you'll see what I mean with my incoming PR.

**Comment by MCGallaspy** [comment]
Tests were taking forever to run, until I realized that a `post_save` callback creates the same issue as a `post_delete` callback, if several saves are made in succession.

**Comment by aronasorman** [comment]
Hi @arnoan,

I've merged in some code that fixes this issue. Would you have time to test out if it fixes it on your side? You can try it out by checking out the latest code in the 0.13.x branch of KA Lite:

```
git clone https://github.com/learningequality/ka-lite --branch 0.13.x
```
and then trying to replicate this issue.

**Comment by arnoan** [comment]
@aronasorman 
Wow, now that went fast. Thank you for the heads up! 
I pulled the latest branch and attempted to replicate the former error. Happy to confirm the preloading loop does not occur anymore. Tried booting from several HDD's now and always starting up smooth.

Yet another issue solved, you guys rock!

**Comment by aronasorman** [comment]
Thanks @arnoan -- @MCGallaspy takes full credit on this one.

**Comment by aronasorman** [comment]
I'll be issuing a new version with this fix sometime by the end of this week.
