### ISSUE TITLE
Coach reports no longer work on Demo server

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3623]
Branch: 0.13.x-demo

We were getting an error on the demo server coach reports related to indexing into strings. @aronasorman put in the following as a fix:
https://github.com/learningequality/ka-lite/commit/7efaea47f72d1a4a88d0b958f9853bccd4832245

Now, however, there appears to be no way on the tabular report page to select the topics (and hence no way to review a report:

![image](https://cloud.githubusercontent.com/assets/618416/7551290/c587b0d8-f638-11e4-8280-6c358e1cda9b.png)

**Comment by EdDixon** [comment]
@jamalex just wanted to report we did test this feature on a 13.1 installation in windows and it seems to be working good via hub.

**Comment by rtibbles** [comment]
@EdDixon this was demo server specific.

This is now fixed on the demo server.
