### ISSUE TITLE
Can not uninstall.

### ISSUE THREAD

**Issue by SinghSatyam** [learningequality/ka-lite#3624]
Getting the following error.
  _   __  ___    _     _ _        
 | | / / / _ \  | |   (_) |       
 | |/ / / /_\ \ | |    _| |_ ___  
 |    \ |  _  | | |   | | __/ _ \ 
 | |\  \| | | | | |___| | ||  __/ 
 \_| \_/\_| |_/ \_____/_|\__\___| 
                                  
http://kalite.learningequality.org
                                  
./uninstall.sh: line 14: syntax error near unexpected token `;;'
./uninstall.sh: line 14: `if [ -e $SCRIPT_DIR/kalite ];; then'

**Comment by benjaoming** [comment]
@SinghSatyam thanks for reporting this!

The script you are trying to run will only remove a directory. So a quick work-around will be to remove the ka-lite directory and you're done* :)

*) Except if you have run some script to have kalite loaded when booting, in that case make sure to run `donotrunatboot.sh`.

A second point: This script and everything inside `scripts/` is being deprecated! In the future, the preferred method will be to install with pip or an installer.
