### ISSUE TITLE
bin/kalite manage shows kalitectl.py as the command name

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3638]
branch: 0.13.x (and possibly develop)

Running `kalite manage help` shows `kalitectl.py instead of `kalite` as the command name:
```
~/src/github.com/aronasorman/ka-lite $ kalite manage help
Usage: kalitectl.py subcommand [options] [args]

Options:
  -v VERBOSITY, --verbosity=VERBOSITY
                        Verbosity level; 0=minimal output, 1=normal output, 2=verbose output, 3=very verbose output
  --settings=SETTINGS   The Python path to a settings module, e.g. "myproject.settings.main". If this isn't provided, the DJANGO_SETTINGS_MODULE environment variable will be used.
  --pythonpath=PYTHONPATH
                        A directory to add to the Python path, e.g. "/home/djangoprojects/myproject".
  --traceback           Print traceback on exception
  --auto-pdb            Break into PDB on an uncaught exception
  --version             show program's version number and exit
  -h, --help            show this help message and exit

Type 'kalite manage help <subcommand>' for help on a specific subcommand.

Available subcommands:

[ab_testing]
    read_facility_conditions
```

See prior discussion on this issue: https://github.com/learningequality/ka-lite/issues/2963

**Comment by benjaoming** [comment]
Notice that the command name is written correctly below the options list.

This *might* be fixed by possibly changing `sys.argv[0]` runtime, but I think that might be a very very bad idea.

This cannot be properly fixed before we have an update of Django implemented that makes it possible.

**Comment by benjaoming** [comment]
A secondary way of fixing it would be to alleviate the need for having a proxy script `kalite` pointing at `kalitectl.py` and the very reasoning behind this behaviour was the need to be able to configure the Python environment that runs `kalitectl`.. but I don't think we should go into this now...

**Comment by rtibbles** [comment]
Punting.

**Comment by benjaoming** [comment]
This can be fixed by upgrading Django... which we're _just_ about to do :)

**Comment by benjaoming** [comment]
Closing in favour of  #2360
