### ISSUE TITLE
 computing->computer programming->advanced JS: Natural Simulation->Angular Momentum?

### ISSUE THREAD

**Issue by 3kay** [learningequality/ka-lite#3652]
In a test new installation of 0.13 i found this hierarchy which appears to be a bug.
lkk

**Comment by aronasorman** [comment]
Hi @3kay,

Thanks a lot for reporting this issue! It's the same as what Khan Academy has: https://www.khanacademy.org/computing/computer-programming/programming-natural-simulations/programming-angular-movement/a/angles-and-units

Reading through the lesson, it doesn't seem like a bug, as the lesson is a lead-up to simulation programming using Processing, which makes use of angular momentum.
