### ISSUE TITLE
Runatboot and start server issue

### ISSUE THREAD

**Issue by waltonrp** [learningequality/ka-lite#3654]
I'm following the Linux user guide
Ubuntu 15.04 64bit fresh install

I'm having issues getting the server to start. I'd started it after install and registered. I rebooted and get these errors:

aguila@XXXX-KALITE:~/ka-lite/scripts$ sudo ./runatboot.sh
INFO:kalite:UserRestricted package selected.

aguila@XXXX-KALITE:~/ka-lite/scripts$ sudo ./runatboot.sh
INFO:kalite:UserRestricted package selected.

I'm wondering if anyone can help me figure this out. Thanks,

**Comment by EdDixon** [comment]
Hi Robert,

Assuming the install went ok and you selected run at boot during the installation (which I know you want and probably did) you should find the server available already at 127.0.0.1:8008 That was tested extensivley in this release however, running that particular script post install was not so if it turns out the server is not already running let us know and I will test to confirm the problem here and get the team on it.

**Comment by waltonrp** [comment]
Server is not available.

**Comment by EdDixon** [comment]
That is a very good question running as sudo I definitely would not expect that either.. ? All I can do is try it here myself on that version of linux but just to clarify you did select run at boot during the installation? My computer is tied up compressing videos right now, can you run: "ls -l /etc/init.d/kalite" without the quotes for me as well as "env | grep KA" which may help explain what's going on?

**Comment by EdDixon** [comment]
@waltonrp just checked with latest ubuntu 15.04 all updates applied following those instructions exactly and could not replicate that error however the command itself has been moved to the scripts folder as I am sure you found out so our documentation needs to be updated and you may need to cd to the ka-lite/scripts directory. I also feel because of the nature of the "User Restricted package" error while running under sudo that you may have possibly missed the "apt-get install m2crypto" step during the pre git installation part of the setup? "apt-get install m2crypto" may resolve the error in that case but unsure if it may have affected the installation steps prior to that. If that is the case at all just a hunch on my part? We are transitioning all of this to a system level command in the future getting away from the user having to run the scripts directly as you are now, which  is why the documentation is out of sync. I hope I guessed right here and this helps!

**Comment by waltonrp** [comment]
aguila@XXXX-KALITE:~$ ls -l /etc/init.d/kalite
-rwxr-xr-x 1 root root 868 May 16 13:59 /etc/init.d/kalite

aguila@XXXX-KALITE:~$ env | grep KA
SESSION_MANAGER=local/XXXX-KALITE:@/tmp/.ICE-unix/1448,unix/XXXX-KALITE:/tmp/.ICE-unix/1448

M2Crypto was installed and I have been running the start comment from the /scripts folder

**Comment by EdDixon** [comment]
@waltonrp can you join in hipchat for further discussion on this in the dev room. I think I can walk you through it. The start on boot option is not working in linux (but was in testing just before release) and is a known issue on windows platforms as documented in the release notes. I was not aware that it is failing in linux as well until now and have found a workaround by adding the full path to the kalite command to the /etc/rc.local file (./home/(USERNAME)/ka-lite/bin/kalite start). This should make it work as you need it too however, there does seem to be something wrong with your setup there and I would prefer to troubleshoot and discuss in the dev room here on hipchat if you can join me there or email me your phone number and I can give you a call? Thanks,

**Comment by waltonrp** [comment]
Try to call me 434-223-2075 I’ll try to be by the phone for a little while.

Robert Walton
Regional Information Technology Specialist
DOC – CTSU – Field Services Unit

**Comment by EdDixon** [comment]
Thanks for the chat Robert I think we came up with some excellent ideas for VADOC and FLE! 

I have no idea what the rest of the team here may think about this work around to the start on boot issue but what is working for me right now here is after installation editing the rc.local file to use the new kalite command to start the server on boot. After a clean install of ubuntu 15.04 updated with latest patches (sudo apt-get update, sudo apt-get upgrade) and following the current instructions for KA-Lite linux installation of our current version (13.01 just in case others are reading after this issue has been resolved). Do the following:

1) sudo nano /etc/rc.local
2) between the commented out space and the exit 0 should be an empty line
3) add the following without the quotes in that empty space "./home/(USE-YOURUSERNAME-HERE)/ka-lite/bin/kalite start"
4)[Control]x to exit [shift]y to accept changes to exit the nano editor

form that point forward the machine should automatically start kalite on bootup.  Anxious to move forward with all the other things we discussed and I wil be getting with the team here first thing next week on those items!

Thanks,

**Comment by waltonrp** [comment]
Thanks Ed, I’ll get KA lite installed on the new Ubuntu install and let you know my result.

Robert Walton
Regional Information Technology Specialist
DOC – CTSU – Field Services Unit

**Comment by j-schwartz** [comment]
Hi Team,

Do you know why I might be getting the following in my startup log?  Ubuntu 12.04

I ran the script at install to boot at startup.  I can't really tell from the wording in this thread if this is a known issue or not.

Thanks!

  File "/media/preloaded/ka-lite/kalitectl.py", line 504, in <module>
    args=arguments['DJANGO_OPTIONS']
  File "/media/preloaded/ka-lite/kalitectl.py", line 341, in start
    with open(STARTUP_LOCK, "w") as f:
IOError: [Errno 13] Permission denied: '/home/ken/.kalite/kalite_startup.lock'

**Comment by EdDixon** [comment]
Hi @j-schwartz is this using the current version on git or from a previous install ( I ask only because of the ubuntu version?)

**Comment by j-schwartz** [comment]
This is the current git version v13.01.  The Ubuntu has to be a little
dated for some other compatibility issues totally unrelated.

On Sat, May 16, 2015 at 6:23 PM, Ed Dixon <notifications@github.com> wrote:

> Hi @j-schwartz <https://github.com/j-schwartz> is this using the current
> version on git or from a previous install ( I ask only because of the
> ubuntu version?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/learningequality/ka-lite/issues/3654#issuecomment-102719786>
> .
>



-- 
Please fill out our user survey
<https://docs.google.com/forms/d/1yLJZvJMnP8AG0CFKJdcD7NvuvTZrZzVdcAWJuaZ_SwA/viewform>.
This
is critical for our fundraising.

Jeremy Schwartz <jeremy@worldpossible.org>
Executive Director
World Possible <http://www.worldpossible.org>
(m) 415.535.2138
World Possible is a 501(c)(3) nonprofit organization

**Comment by EdDixon** [comment]
Thanks I will try to see if we can replicate that here. In 14 up it seems pretty solid and I had been running it on debian (stable) for years prior to that.. Can you verify your python version for me python -V?

**Comment by j-schwartz** [comment]
2.7.3

On Sat, May 16, 2015 at 6:34 PM, Ed Dixon <notifications@github.com> wrote:

> Thanks I will try to see if we can replicate that here. In 14 up it seems
> pretty solid and I had been running it on debian (stable) for years prior
> to that.. Can you verify your python version for me python -V?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/learningequality/ka-lite/issues/3654#issuecomment-102720299>
> .
>



-- 
Please fill out our user survey
<https://docs.google.com/forms/d/1yLJZvJMnP8AG0CFKJdcD7NvuvTZrZzVdcAWJuaZ_SwA/viewform>.
This
is critical for our fundraising.

Jeremy Schwartz <jeremy@worldpossible.org>
Executive Director
World Possible <http://www.worldpossible.org>
(m) 415.535.2138
World Possible is a 501(c)(3) nonprofit organization

**Comment by waltonrp** [comment]
While issue with run at boot remains (I'll do workaround later), I found my problem with starting the server. In the install window (terminal) is says to run "/home/aguila/ka-lite/bin/kalite start" to start the server.

The Linux install guide says:
Use sudo service kalite stop to stop the server
OR sudo service kalite start to start the server.

While the correct info was right in front of my face all along, I was following the guide

**Comment by EdDixon** [comment]
@waltonrp Excellent yes sir, we are transitioning to that command and will hopefully have the new documentation page up soon to match. We have hopes that in the very near future the kalite command will be available on all platforms as a system wide command so the full path (including user) will no longer be necessary."/home/aguila/ka-lite/bin/kalite help" and"/home/aguila/ka-lite/bin/kalite help manage" will give you some idea of the amazing capabilities to come. Enjoy! @j-schwartz I haven't setup a test for Ubuntu 12 yet just to give the developers here time to chime in with their experience on that OS with python 2.7.3 (I am sure they have some) before doing so.

**Comment by waltonrp** [comment]
Ed. Edited the rc.local file as you mentioned and rebooted, server is up. Thanks for your good help. As I stated, I'll be setting up a few servers this week for deployment. Please keep me in the loop on whether there is a permanent fix. 

For the installation guide, I can't express strongly enough how important it is for end users to have accurate install information. I'm a beginner level Linux user and as I told you, I follow the installation guide line by line. That needs to be updated when there are changes.

Excited to have this project rolling, I'm going to add another HDD to this box and trial running content from that and then I can start rolling them out.

**Comment by EdDixon** [comment]
Yes sir, I am am very excited to see those initial sites up and running using version 13 with many more on the way. It is so great working with you on this! Thank you for helping us find these types of issues and being proactive in working with us to help resolve them!

**Comment by MCGallaspy** [comment]
@waltonrp the script `runatboot.sh` gives you an error? And I've noted that the documentation is inaccurate, I'll update it.

**Comment by EdDixon** [comment]
@MCGallaspy The script is still failing @aronasorman suggested I add a PR for the rc.local fix but I am fairly confident that this will be addressed in the short term so, perhaps just adding my notes above about how to add the start command to rc.local to get it start at bootup going for now to the docs?

**Comment by MCGallaspy** [comment]
Okay, I see two issues here: `runatboot.sh` is broken and no longer works in `0.13.x`; this was apparently an oversight. Furthermore, no equivalent command exists for the `kalite` executable. @benjaoming can we add such a command, at least for Linux? It's a different bag of worms on Windows, and is furthermore handled by the installer in that case.

**Comment by MCGallaspy** [comment]
@waltonrp 

>The Linux install guide says:
Use sudo service kalite stop to stop the server
OR sudo service kalite start to start the server.

>While the correct info was right in front of my face all along, I was following the guide

Actually, I think this information is accurate if the previous step (running `runatboot.sh`) succeeds; in your case it did not. The command displayed in your terminal at the end of the setup process will indeed start the server, but will not create a service that starts the server at boot. I do agree that the documentation isn't entirely clear, though, so I am still amending it.

**Comment by MCGallaspy** [comment]
@j-schwartz

Seems like a different issue. Can you open another issue and provide more details on how you installed KA Lite?

**Comment by j-schwartz** [comment]
Ya, I'll check it out this evening and write something more up

On Tue, May 19, 2015 at 6:34 PM, Michael Gallaspy <notifications@github.com>
wrote:

> @j-schwartz <https://github.com/j-schwartz>
>
> Seems like a different issue. Can you open another issue and provide more
> details on how you installed KA Lite?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/learningequality/ka-lite/issues/3654#issuecomment-103715175>
> .
>



-- 
Please fill out our user survey
<https://docs.google.com/forms/d/1yLJZvJMnP8AG0CFKJdcD7NvuvTZrZzVdcAWJuaZ_SwA/viewform>.
This
is critical for our fundraising.

Jeremy Schwartz <jeremy@worldpossible.org>
Executive Director
World Possible <http://www.worldpossible.org>
(m) 415.535.2138
World Possible is a 501(c)(3) nonprofit organization

**Comment by benjaoming** [comment]
> Furthermore, no equivalent command exists for the kalite executable. @benjaoming can we add such a command, at least for Linux?

Yes, it's there... but I don't know if it works:

    kalite manage initdconfig

**Comment by EdDixon** [comment]
@benjaoming @aronasorman is this planned for 0.13 in a later minor version? It will affect needed user documentation for this branch if so but will be great to have in 0.13.x if possible and much prefered to the method I provided VADOC with earlier! Also this is a very *nix based feature of the command how will it affect windows users trying to use the command? This may have already been addressed but is there any check to hide those features unavailable by OS built into the kalite command other wise I can see a windows user trying to use with a huge fail? Thank You @benjaoming ! Excellent work!

**Comment by aronasorman** [comment]
Fixed in develop. Cherry picking to 0.13.x.

**Comment by aronasorman** [comment]
@MCGallaspy also updated the documentation on 0.13.x.

**Comment by aronasorman** [comment]
@EdDixon it's only a Debian feature. It shouldn't affect Windows.

**Comment by EdDixon** [comment]
@aron I am aware of that but, we really should have a windows equivalent
option I think? I thought the whole point of this command was to make it
cross platform? When the user types kalite help to try to find a means to
do this via shell it will reveal itself as an available option which could
lead the unknowing windows user to think it may work to fill this need it
would make sense without any other alternative and the option available?

Ed Dixon
Corrections Adviser
Foundation for Learning Equality <http://learningequality.org/>
Give to FLE, Support FLE via Amazon Smile!
<https://learningequality.org/donate/>
M (575)-636-9549

On Wed, May 20, 2015 at 11:12 AM, Aron Fyodor Asor <notifications@github.com

**Comment by aronasorman** [comment]
@EdDixon ideally we'd have one for Windows, but given how much time we've invested to making it work across all 3 supported Windows platforms I don't think we have time to do it for 0.14. We also have this same functionality in the GUI, so supporting it through the command line isn't urgent for me.

**Comment by EdDixon** [comment]
I agree so much to do so little time! It makes me wish I was a kid all over again but having these cool tools to learn with! But yea future feature would be extremely cool!

**Comment by benjaoming** [comment]
@EdDixon the command is called "initdconfig" so it will hopefully not appeal much to the Windows crowd :)

**Comment by MCGallaspy** [comment]
@benjaoming 

>Yes, it's there... but I don't know if it works:

> `kalite manage initdconfig`

Duh, you're right. Should work on *nix again.

**Comment by benjaoming** [comment]
Another PR is coming in because I found that the produced script actually didn't work.

**Comment by elvistek** [comment]
I have installed ka lite v 0.15.1 on a raspberry pi and gone through the process as expressed in [http://ka-lite.readthedocs.org/en/0.15.x/installguide/install_all.html#raspberry-pi ](url) but teh server will not start when the pi is booted. What can the problem be? 

I had some problems during installation but running `kalite manage setup` fully completed the installation and i can connect other devices to the server but i have to run the server manually after start up. Any help? as automatic startup of server will be my ideal situation for deployment.
 
Here are screen shots of the process with the error in image = unknown-1
![unknown-1](https://cloud.githubusercontent.com/assets/18245124/14232769/7deef4d4-f97a-11e5-8323-810eac0f9623.png)
![unknown-2](https://cloud.githubusercontent.com/assets/18245124/14232770/7df707f0-f97a-11e5-8d7c-496a23c2dbce.png)
![unknown-3](https://cloud.githubusercontent.com/assets/18245124/14232771/7df7872a-f97a-11e5-9220-28be8be47677.png)
![unknown-4](https://cloud.githubusercontent.com/assets/18245124/14232772/7dff1dd2-f97a-11e5-949f-d8a57e65ee9c.png)
![unknown-5](https://cloud.githubusercontent.com/assets/18245124/14232773/7e04e51e-f97a-11e5-91a0-284c17fb0e52.png)
