### ISSUE TITLE
Exercise Keypad not working on Chrome.

### ISSUE THREAD

**Issue by anuragkanungo** [learningequality/ka-lite#3655]
Branch: Nalanda-phase3

Show hide keypad works but clicking on numbers doesn't work in chrome. It works in default browser.

**Comment by aronasorman** [comment]
Hmm strange. I believe there's a fix made in the `release-0.12` branch, but it was made for IE 8. Can you try finding that commit and cherry picking it to your branch for testing?

**Comment by anuragkanungo** [comment]
@aronasorman , Sure will do it and let you know

**Comment by iCHAIT** [comment]
This can be closed I guess?

**Comment by benjaoming** [comment]
@iCHAIT yup, better late than never :)

Tested and confirmed working in Chromium for the record.
