### ISSUE TITLE
Portuguese Support

### ISSUE THREAD

**Issue by axpence** [learningequality/ka-lite#3656]
Hi All,
I am taking 20 chromebooks to Mozambique, Africa and would like to get a version of KA lite installed on these chromebooks including portuguese language support. 

Is this a possibility?

thanks
Alex

**Comment by aronasorman** [comment]
Hi @axpence,

We do support portuguese! (the Brazilian dialect)

![image](https://cloud.githubusercontent.com/assets/191955/7684273/9f30ad1a-fd39-11e4-99ed-b2001315c671.png)

We have instructions here on how to download language packs: https://learningequality.org/docs/usermanual/userman_admin.html#language-packs

However, we are not aware yet on how to install KA Lite on a non-rooted Chromebook, as Chrome OS is pretty locked down. Do you plan to install another OS on top of the chromebook?
