### ISSUE TITLE
Add visual indication in Coach Reports to see if struggling students have watched the video

### ISSUE THREAD

**Issue by mjptak** [learningequality/ka-lite#366]
Bunches of learners may probably just plow ahead in the exercises without watching videos which is great.  However it would be great to see if students who are struggling have used the initiative to watch the video...once (or even twice).  As more "content" is mapped to particular exercises...there is more than one way to do any one thing ...the interface could also show if the learner has accessed more than one particular approach to it.

I can see that this information is actually pretty readily available by clicking on the student name in the exercise report.   My bad.  The comment about how many of a set of videos around a topic have been watched is probably still valid.

**Comment by aronasorman** [comment]
Not a priority; closing.
