### ISSUE TITLE
Can't download videos using admin account

### ISSUE THREAD

**Issue by amodia** [learningequality/ka-lite#3671]
Branch: `develop`
Expected behavior: Must show `topic tree` when navigate to `Videos` tab.
Current behavior: Cannot open `topic tree` when navigate to `Videos` tab.
Steps to reproduce:

 1. Log-in as admin user.
 2. Navigate manage tab.
 3. Click `videos` tab.

![screen shot 2015-05-19 at 4 29 14 pm](https://cloud.githubusercontent.com/assets/8663934/7698935/ca22c964-fe46-11e4-812f-4213d35f55e6.png)

**Comment by rtibbles** [comment]
This appears to have been fixed by @MCGallaspy in #3698
