### ISSUE TITLE
Unbundle unittest2

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#3675]
I'm moving the dependency of unittest2 to requirements_dev because it isn't used anywhere else than in one test:

```
➜  ka-lite git:(dist-packages) ack-grep --python unittest2 kalite
kalite/basetests/tests.py
18:import unittest2
42:class DependenciesTests(unittest2.TestCase):
231:        "unittest2": "0.7.1",
363:#     suite = unittest2.TestSuite()
377:    unittest2.main(verbosity=0)
```

Secondary to this: Can someone maybe completely get rid of the usage of this library since it seems to be used only to test its own version and then this one single TestCase that I think could probably be implemented in a smarter way?

**Comment by aronasorman** [comment]
Python 2.7 has unittest2 built in. Once we move to that it will be much easier to "remove" this library. :)

**Comment by benjaoming** [comment]
@aronasorman but if it's only for testing then we can just have it in requirements_dev right?

**Comment by aronasorman** [comment]
@benjaoming yup sure. Feel free to move it there.
