### ISSUE TITLE
Unbundle postmark

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#3677]
The package `postmark` seems to be unused:

```
➜  ka-lite git:(dist-packages) ack-grep --python postmark kalite
kalite/basetests/tests.py
223:        "postmark": "0.1.6",
➜  ka-lite git:(dist-packages) ack-grep --python postmark python-packages
python-packages/fle_utils/build/management/commands/generate_blacklist.py
64:            "python-packages/postmark"

python-packages/playground/test_tools/mount_branch.py
78:            local_settings.write("EMAIL_BACKEND = 'postmark.backends.PostmarkBackend'\n")

```

It is definitely a condition for getting rid of `pytz`.

It seems that `playground` wants it. But this one is totally unused. See #3676

**Comment by benjaoming** [comment]
@jamalex can you pitch in here? This package looks stale judging from the fact that it's there because of another unused package.

```
commit 7db904d446e3fe4c0bd8df8ef67f1d295447d565
Author: Jamie Alexandre <jamalex@gmail.com>
Date:   Tue Nov 27 14:56:51 2012 -0800

    Many central server changes; fixed registration and tweaked landing page.
```

**Comment by aronasorman** [comment]
@benjaoming yeah I believe postmark is used in the central server, not the distributed. This can be safely removed.

**Comment by MCGallaspy** [comment]
Then it's probably good to add it to the requirements for the central server!

**Comment by benjaoming** [comment]
Yes, I'll make requirements_central for this

**Comment by MCGallaspy** [comment]
Or add it to requirements.txt in the central server repo?

**Comment by jamalex** [comment]
> This can be safely removed.

:+1: 

> Or add it to requirements.txt in the central server repo?

:+1: (https://github.com/fle-internal/ka-lite-central/blob/develop/requirements.txt)

**Comment by benjaoming** [comment]
Thanks for the pointer, Jamie.. I had already gone ahead, there's a PR :)
