### ISSUE TITLE
Unbundle werkzeug

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#3679]
This package seems to be unused.

```
➜  ka-lite git:(develop) ack-grep --python werkzeug kalite         
kalite/basetests/tests.py
232:        "werkzeug": "0.8.3",
```

```
➜  ka-lite git:(develop) ack-grep --python --ignore-dir=python-packages/werkzeug werkzeug python-packages
python-packages/django_extensions/management/commands/runserver_plus.py
57:        # Redirect werkzeug log items
58:        werklogger = logging.getLogger('werkzeug')
97:            from werkzeug import run_simple, DebuggedApplication
99:            raise CommandError("Werkzeug is required to use runserver_plus.  Please visit http://werkzeug.pocoo.org/ or install via pip. (pip install Werkzeug)")
131:            print "Using the Werkzeug debugger (http://werkzeug.pocoo.org/)"

python-packages/requests/utils.py
165:# From mitsuhiko/werkzeug (used with permission).
196:# From mitsuhiko/werkzeug (used with permission).
230:# From mitsuhiko/werkzeug (used with permission).
```

**Comment by benjaoming** [comment]
@jamalex I don't know so much about what werkzeug does or can be used for, can you advice? It doesn't seem to be used by other libraries that we use or by kalite itself.

So it could be a candidate for straight-up removal?

**Comment by jamalex** [comment]
It gets used by the `runserver_plus` management command, which is part of django-extensions and a fantastic tool for getting a much richer error traceback in the browser (including being able to drop into an interactive shell anywhere in the traceback). So, not needed for distribution, but good to have in requirements_dev.txt

**Comment by benjaoming** [comment]
Great, thanks for getting back!!

Aufwiedersehen in requirements_dev, Werkzeug!
