### ISSUE TITLE
Coach can access the sign up page.

### ISSUE THREAD

**Issue by amodia** [learningequality/ka-lite#3682]
Branch: `develop`
Expected behavior: when `coach` is log in sign up page must not show.
Current behavior: coach log in can access sign up page.
Steps to reproduce: 

 1. Log in as coach.
 2. Go to the [sign up](http://localhost:8008/securesync/signup/) page 

![screen shot 2015-05-20 at 2 52 55 pm](https://cloud.githubusercontent.com/assets/8663934/7720819/35bee384-ff04-11e4-9fb8-7f4ce6050c55.png)

**Comment by cpauya** [comment]
I think we need to disable the signup page if there is a logged-in user, either a User or FacilityUser (coach/student).
