### ISSUE TITLE
Transfer markdown files into our sphinx-docs folder

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3684]
branch: develop

Right now we have KA Lite documentation in two places: Github Wiki (markdown) and [our docs page](https://learningequality.org/docs/) (RST). We should move most of our documentation into a single place. This makes it easier to maintain as we don't have to look at multiple domains in order to make a change, as well as giving our users a central place for all of our documentation.

I prefer if that central location be our leq docs, since RST is much more powerful than markdown (albeit a bit more complex).

**Comment by benjaoming** [comment]
Please see #2920 ;)
