### ISSUE TITLE
Low level cross platform commands should check OS compatability

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite#3687]
I feel it is important moving forward with our kalite command and the huge amount of options and functionality coming with it that we have a check built into the command which can disable functionality for systems on which those features or functions do not exist. My only example right now is a recent addition to the kalite command that modifies init.d configuration for starting the server on boot. It is an excellent and much needed addition to our linux platforms but will not work and could potentially create a lot of confusion and possibly malfunctions on other systems not supporting init.d. A common method of checking the os then disabling those features which do not exist would resolve this problem by eliminating the user's ability to mistakenly use these features where they do not exist.

**Comment by benjaoming** [comment]
@EdDixon I think the `kalite manage initdconfig` command (which is a django management command) is a very harmless command that just outputs some text for a configuration file on Mac or Linux (furthermore it only works on Ubuntu/Debian like systems).

It's only there temporarily and the sort of thing that it does will be moved into installers.

For the future, we shouldn't have any OS-specific commands, neither as `kalite` command options or django management commands... anything OS specific goes in the OS specific distributions (installers).

**Comment by aronasorman** [comment]
I agree with @benjaoming, we're deprecating `initdconfig` anyway and moving that functionality to the installers. Closing.
