### ISSUE TITLE
Login error message mentions facility, which cannot be selected yet

### ISSUE THREAD

**Issue by mtorourk** [learningequality/ka-lite#369]
I tried to login and got an error that mentioned my facility, although I hadn't made any changes to facilities and had no ability to. 

![screen shot 2013-08-02 at 11 41 54 am](https://f.cloud.github.com/assets/1326025/903069/ec076662-fba4-11e2-8d68-8dc228eaf1cb.png)

**Comment by aronasorman** [comment]
We no longer mention "facility" in this specific message in the latest develop.
