### ISSUE TITLE
Failed to load coach report's table.

### ISSUE THREAD

**Issue by amodia** [learningequality/ka-lite#3715]
Branch: `develop`
Expected behavior: Coach report's table must load when navigating on `teach` tab.
Current behavior: Can't access `coach report's table`.
Steps to reproduce:

 1. Log in as coach. 
 2. Navigate to `teach` tab.

![screen shot 2015-05-25 at 12 03 21 pm](https://cloud.githubusercontent.com/assets/8663934/7792236/c1511418-02e1-11e5-8a11-b26677471ba3.png)

**Comment by rtibbles** [comment]
Hopefully fixed by: #3649
