### ISSUE TITLE
Admin "Teach" page leads to a 404

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3731]
branch: develop

Clicking teach as an admin:
![screen shot 2015-05-26 at 10 57 52 am](https://cloud.githubusercontent.com/assets/191955/7819361/1c99d706-0396-11e5-993e-971c339d5003.png)

Leads to this:

![screen shot 2015-05-26 at 10 58 34 am](https://cloud.githubusercontent.com/assets/191955/7819371/2e1377ee-0396-11e5-8c31-ca8e9cf566ba.png)

**Comment by rtibbles** [comment]
Not extant on develop. Are you sure you're up to date?

**Comment by rtibbles** [comment]
(For further context, this was fixed in the PR you just merged #3725)

**Comment by aronasorman** [comment]
Yup, fixed now.
