### ISSUE TITLE
"Access from another computer message" showing 127.0.0.1

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#3732]
When, for instance, you run `kalite start`, you might see the following message:
>To access KA Lite from another connected computer, try the following
address(es):
    http://127.0.0.1:8008/

Which won't work from _another_ computer, as suggested.

**Comment by aronasorman** [comment]
We should change the text instead to say:

> You can now access KA Lite by opening one of the following addresses in your web browser:
