### ISSUE TITLE
Support multiple versions of the docs

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3740]
Similar to what Django does:

![screen shot 2015-05-26 at 2 57 45 pm](https://cloud.githubusercontent.com/assets/191955/7824415/a2503a40-03b7-11e5-8f49-32ad59c3ab39.png)

We default to the latest stable release (0.13.x currently) but then also provide a "bleeding edge" doc.

**Comment by MCGallaspy** [comment]
Duplicate of #4098.

**Comment by benjaoming** [comment]
This is now implemented via ReadTheDocs, http://ka-lite.readthedocs.org/en/latest/
