### ISSUE TITLE
Learn tab flickers when video playing

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#3742]
On `develop`:
Expected behavior: The learn tab doesn't blink.
Actual behavior/steps to reproduce: Log in as a student (other account types untested). Play a video. Notice that the color of the Learn tab flickers from green to white. Pausing the video causes the flickering to cease.

**Comment by rtibbles** [comment]
Muy curioso - OS/browser combo?

**Comment by rtibbles** [comment]
I suspect this may come from overly aggressive rerendering of the now Backbonified Nav bar, @jtamiace

**Comment by MCGallaspy** [comment]
Chrome/Windows client, served from Ubuntu 14.04.

**Comment by rtibbles** [comment]
Have (briefly) chatted this over with @jtamiace.

**Comment by rtibbles** [comment]
Fixed in #3792
