### ISSUE TITLE
404 for reverse.js

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#3744]
On `develop`:
Observed behavior/steps: Ran `kalite manage kaserve` (instead of `kalite start`) to get that sweet debug output. This:
>GET http://127.0.0.1:8008/static/django_js_reverse/js/reverse.js 

Gets a 404 response. No such problem with `kalite start`. Is it me?

Edit: The consequence is that the login dropdown doesn't seem to work anymore.

**Comment by aronasorman** [comment]
I get these errors when running kaserve with `DEBUG=False`:

![image](https://cloud.githubusercontent.com/assets/191955/7842271/fe331fcc-0456-11e5-850f-34eeca9feb42.png)

**Comment by MCGallaspy** [comment]
@aronasorman I think those files are legitimately missing, whereas in my case it's not serving the file for some reason.

**Comment by MCGallaspy** [comment]
I suspect this might be an error in django_js_reverse. Can someone try to replicate with `DEBUG=True`?

**Comment by rtibbles** [comment]
I have had similar behaviour when running tests locally, but with DEBUG=True. Will investigate.

**Comment by rtibbles** [comment]
@aronasorman Note one of those errors is flagged here: #3720

**Comment by rtibbles** [comment]
@MCGallaspy I can't replicate this error.

```call_command("collectstatic_js_reverse", interactive=False)``` is called during kaserve, so this file should be present.

Are you able to replicate after clearing all *.pyc files?

**Comment by MCGallaspy** [comment]
Yeah, on `develop`, cleared pyc files. Still getting this 404. Must be an issue with my system. It seems there's an alternate use [as a view](https://github.com/ierror/django-js-reverse#usage-with-views), which may be more robust. Let me try that out.

**Comment by rtibbles** [comment]
Can you check that the file itself exists? If you look in the Base
template, I am using the view if debug is true.

**Comment by MCGallaspy** [comment]
Where should I look for it? It doesn't exist in `static-libraries`.

**Comment by MCGallaspy** [comment]
Unconditional use of the view works fine for me.

**Comment by rtibbles** [comment]
It gets generated and put into your kalite/static folder at server start.
The command might be erroring for you?

**Comment by MCGallaspy** [comment]
`collectstatic_js_reverse` runs without error, if that's what you mean.

**Comment by MCGallaspy** [comment]
How about we use the view, but if `DEBUG` is falsy it's cached forever?

**Comment by rtibbles** [comment]
Could do, but do you get errors in production mode? I would rather use the
static file for production if its works. It seems like the debug template
context is not triggering properly for you.

**Comment by MCGallaspy** [comment]
No error in production.
