### ISSUE TITLE
CommandError: Unknown command: 'migrate'

### ISSUE THREAD

**Issue by arceduardvincent** [learningequality/ka-lite#3746]
Branch:` Develop`
Target: `0.14.x`
Current Behaviour: When running the `kalite manage setup` can't proceed for database migration.

Expected Behaviour: When running the migration command the changing of database schema from one version into another must succeed.

Steps to reproduce:
1. Open a `terminal`
2.  `cd ~/ka-lite`      *which is your kalite directory.*
3. run `vagrant up` or  `vagrant provision`        *this will up the box or re-provision our kalite box.*
4. run `vagrant ssh`       *This will ssh to your box*
5.` cd ~/ka-lite`      *go to your kalite directory*
6.  run `kalite manage setup` then supply the question ask.
7. when the `kalite manage setup`is done notice that the migration command didn't execute and it fails.

See the attach image for demo.
![screenshot 2015-05-27 12 58 47](https://cloud.githubusercontent.com/assets/4099119/7829120/22507bfc-0470-11e5-97e7-90a82cee7d3e.png)

**Comment by cpauya** [comment]
This is because `South` is not being seen among the python packages - however, it was installed during vagrant box provisioning, perhaps it was installed somewhere else?
![screenshot 2015-05-27 13 16 18](https://cloud.githubusercontent.com/assets/175580/7829281/979a624a-0472-11e5-9afa-4ce2d8e62837.png)

**Comment by jamalex** [comment]
Just need to delete all pyc files, that fixed it for both @rtibbles and me. Might be worth trying to track down what file is causing it, before deleting all, if that's easy, so we can find a way to avoid this for others.

**Comment by jamalex** [comment]
`find . -name "*.pyc" -delete`

**Comment by arceduardvincent** [comment]
Hello @jamalex thanks for help
the migration works using the suggested command you have given, Deleting all `pyc` files
I will track down that file causing this error.

**Comment by MCGallaspy** [comment]
User error.
