### ISSUE TITLE
RaspberryPi 2 not recognised as Raspberry

### ISSUE THREAD

**Issue by arnoan** [learningequality/ka-lite#3751]
Expected behaviour: When running the Unix installation script "./setup_unix.sh" kalite should recognise if it is being run on a RaspberryPi and if so perform some optimisations. 

Actual behaviour: The new RaspberryPi 2 (Released in February) is not being recognised as a Pi. -> No optimisations are taking place. 

For the time being is there a way to manually force the selection of the RPi package?

**Comment by aronasorman** [comment]
Interesting. Can you run `uname -a` and paste the output here?

**Comment by arnoan** [comment]
Sure:
pi@raspberrypi ~ $ uname -a
Linux raspberrypi 3.18.14-v7+ #792 SMP PREEMPT Sat May 23 16:19:32 BST 2015 armv7l GNU/Linux

**Comment by arnoan** [comment]
Running the newest Raspbian Wheezy Build. (2015-05-05-raspbian-wheezy.img)
Another Raspberry Pi B+ running the same system is being identified as expected.

**Comment by benjaoming** [comment]
@arnoan would you be able to have a look at the current develop to see if it correctly detects your RPi2?

**Comment by arnoan** [comment]
@benjaoming Yes, identification is working on develop. Some other errors popping up though. But that might be normal on the develop branch.

```
pi@raspberrypi ~/develop/ka-lite $ ./setup_unix.sh
Traceback (most recent call last):
  File "/home/pi/develop/ka-lite/kalitectl.py", line 75, in <module>
    from docopt import docopt
ImportError: No module named docopt

Do you wish to configure the Raspberry Pi optimizations for this server?
You will need root/sudo privileges and an Internet connection.

Optimize now? [Y/N] Y
Optimize will start the KA Lite server now, 
    and automatically on every system boot.

Traceback (most recent call last):
  File "/home/pi/develop/ka-lite/kalitectl.py", line 75, in <module>
    from docopt import docopt
ImportError: No module named docopt
```
etc...

**Comment by benjaoming** [comment]
@arnoan ah yes, the source dist doesn't bundle all deps anymore.. so when running from source, you should do `pip install -r requirements.txt` from command line first (perhaps with a `sudo` in front).

I've released a new version on PyPi that should have both the fix for RPi and bundled packages, you can install it with `pip install ka-lite-static --pre`.

**Comment by arnoan** [comment]
@benjaoming Thank you. Maybe I should note that I am not a programmer and only recently started to develop some rudimentary understanding of the functioning of python and github to manage a particular Project Implementation for Refugees here in Freiburg. So I'm grateful if you take it easy on me. ;)

Will try my luck to get the dependencies working now and report back in a moment.

**Comment by benjaoming** [comment]
@arnoan please do ask, in case you need help, join us on Hipchat => https://www.hipchat.com/gzQfGFgv1

**Comment by arnoan** [comment]
Thanks, will get back to that if needed. For now I managed to install PyPi and `sudo pip install -r requirements.txt` worked out well. Also the installation of 0.14.dev10 is working fine and Raspberry optimisation is happening as expected now. The content sidebar is loading much faster now (took ~30sec to appear on client devices before, now it's almost instantaneous) but that might also be since I didn't add any content to this installation.

`pip install ka-lite-static --pre` gives me an error though:
```
pi@raspberrypi ~/develop/ka-lite $ sudo pip install ka-lite-static --pre
Usage: /usr/bin/pip install [OPTIONS] PACKAGE_NAMES...
/usr/bin/pip install: error: no such option: --pre
```

Can we still insert the optimisation into the 0.13 build?

**Comment by benjaoming** [comment]
@arnoan thanks for this feedback, I am not quite sure why you are getting this error from pip, could you tell me what's the output of `pip --version` so we can know if this is due to an old version of pip? Also, would it work by moving the `--pre` option like this: `pip install --pre ka-lite-static` ?

**Comment by arnoan** [comment]
`pip --version` returns:
```
pip 1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
```

`pip install --pre ka-lite-static` 
returns the same error as before:

```
pi@raspberrypi ~/develop $ pip install --pre ka-lite-static
Usage: /usr/bin/pip install [OPTIONS] PACKAGE_NAMES...

/usr/bin/pip install: error: no such option: --pre
pi@raspberrypi ~/develop $ 
```

**Comment by aronasorman** [comment]
Oh, that's a really old version of pip @arnoan. Can you try running `pip install --upgrade pip`?

**Comment by aronasorman** [comment]
for reference, this is what `pip version` returns in my computer:
```
~/src/github.com/aronasorman/ka-lite-central $ pip --version
pip 6.0.8 from /home/aron/src/virtualenvs/ka-lite-central/local/lib/python2.7/site-packages (python 2.7)
```

**Comment by benjaoming** [comment]
The pip available on Ubuntu 14.04 is 1.5.4.

@arnoan as @aron says, try with a later version of pip or try removing `--pre` and see if your pip succeeds in finding the latest version.

**Comment by arnoan** [comment]
@aronasorman @benjaoming Thanks for pointing out the old version. I need to get into the habit of immediately updating all modules after their installation. Could have guessed that myself. After running the suggested pip update I'm on version 7.0.1 now. (On Raspbian Wheezy.) 

Both `pip install ka-lite-static` and `pip install ka-lite-static --pre`are working now:  
`Requirement already satisfied (use --upgrade to upgrade): ka-lite-static in /usr/local/lib/python2.7/dist-packages` 

Are we still trying to verify something in particular now? I can confirm that 0.14.dev10 recognises the Raspberry Pi 2 during setup and performs the expected optimisations.

**Comment by 66eli77** [comment]
I know that our original implementation detects the CPU model to identify Raspberry Pi, since RP2 uses different CUP, this behavior is expected. Is @benjaoming 's new approach solved the issue?

**Comment by arnoan** [comment]
@66eli77 Yep, in the newest dev build the recognition is working.
