### ISSUE TITLE
Update command for 0.14: Installers, PyPi, git -- decisions

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#3774]
Trying to structure this a bit to make it more "operational" for the imminent release..

Important question 1
================

Should KA Lite support `kalite manage update` for 0.13? (It's already there in the 0.13)

Command is already implemented in 0.13, so there's no way around the fact that *something will happen when users run it*. The command would download the latest KA Lite from Git or be pointed to a source .zip. I have a feeling we could potentially make parts of this work. In that case, usual practice is (short version):

1. Update the application from zip/git
1. Run `kalite manage start` as is currently the case. This makes the database migrate itself because `kaserve` will detect `DatabaseError` and then run `setup`.

As you know, 0.14 would support running KA Lite from a source tree. This stores all data in the source tree as practice from 0.13. So after this practice, everything should still be working!

But once a user moves to a PyPi distribution or if they are using an installer, data is stored somewhere else, either defined by the installer (the KALITE_HOME environment var) or by default `~/.kalite` on *nix systems.

In other words, we really need users to stop running KA Lite in a git clone and with all their data in the application source. (If you need more motivation, see last section)

One major draw-back already of the current `kalite manage update` command is that no new assessmentitems are downloaded. This is possibly already such a major lack, that we might consider dumping the whole command.

Solution 1
-------------

We risk a lot of mess by trying to be "automatic" about things, but this is a possible approach:

1. Let the update script run its course, resulting in a new source tree installation with data stored in the source three (as outlined above).
1. Change `kaserve` to detect that upon the first run of KA Lite, the user receives a prompt to migrate all data to `~/.kalite` and install from PyPi -- Most likely, users that run `kalite manage update` are already running from a command line on a *nix system. We could even attempt this process manually!
1. Following the data migration, prompt the user to install kalite from PyPi `pip install ka-lite-static` and inform them that they should read the updated guide for installing. Hopefully ALL installers respect the new universal location of user data. I don't think this should be attempted automatically since there is a recommended way of installing KA Lite if it's Windows, Mac, Debian/Ubuntu or another *nix respectively.

Solution 2
-------------

Instead of spending time fixing `kalite manage update`, we leave the command succeeding and data being stored in a 0.14 source tree. The challenge is now to be ready for 0.15.

The combination of `DEBUG=False` and running from a source tree should then spawn a deprecation warning to install from PyPi or from an installer and store data in `~/.kalite` with the suggestion of running `kalite manage migrate_source_tree_data` (pending implementation).

Important question 2
================

Should we completely remove the `kalite manage update` command from 0.14 ?

It really depends on whether we want to ship a source tree for 0.15 that still supports using user data sources placed within the source tree.

My clear feeling is that we can make all 769 lines in update.py redundant by using Solution 1 or Solution 2 to migrate user's data away from the source tree.

Repeating from Important Question 1: One major draw-back already of the current `kalite manage update` command is that no new assessmentitems are downloaded. This is possibly already such a major lack, that we might consider dumping the whole command.

My recommendation is to remove the update command in 0.14 and ensure that users upgrading from 0.13 land in a 0.14 environment that's ready for a different release management.

Furthermore, we should in 0.15 ensure that no one can upgrade directly from 0.13 or at least hint this very clearly in the release notes.

Motivation recap: Why users shouldn't be running directly from a source folder
==============================================================

For anyone who thinks this is stupid :)

1. Risking git conflicts or loosing data through source .zip overwrites
1. Implicitly encouraging source changes, if anyone went and modified a file that would seem okay since they just downloaded a collection of them (files) and might have found something they wished to customize.
1. KA Lite is shipping dependencies rather than depending on them (allowing online updates contradicts this approach and thus targets a different user segment). This has left KA Lite with a very out-dated set of bundled packages.
1. Unnecessarily delegating responsibility of software updates to the KA Lite application rather than a real software distribution framework like PyPi, Apt, Windows/Mac installers etc.
1. All the benefits related to a real software distribution channel like PyPi / PPAs / debian repos etc.
1. User running `kalite` may be different from user installing the source tree and thus not have read/write access to the source tree. Or in short: Moving user data into userspace!

**Comment by benjaoming** [comment]
Awaiting comments and questions, will upgrade above description to reflect discussion below......

**Comment by aronasorman** [comment]
Yeah, as the last guy that touched the `update` command, it's sorely outdated and should just be rewritten. Right now the 'happy path' is basically a frontend to `git fetch upstream; git checkout upstream/nalanda-rct3; python manage syncdb`. Which was a decent solution when we expected everyone to have a git repo, but won't hold true anymore for the installers age and the upcoming unified update UI.

Solution 2 seems to be the best -- we should deprecate git repos and tell people to migrate to an installer. We already have an [open issue for the migration command](https://github.com/learningequality/ka-lite/issues/3335), someone just has to implement it. We've also purged any reference to `manage update` in 0.13 I think.

re: question 2 -- yes, let's just remove it. Though we eventually want to be able to restore this functionality when a unified update mechanism is in place, it's just better to burn this down and make a new software update mechanism that's more integrated with p2p syncing. We can also leverage setuptools to streamline that update process.

**Comment by MCGallaspy** [comment]
Yes, let's remove the `update` command in 0.14; it doesn't align with our supported installation methods now. We should provide a migration path for users switching from "source" distributions to the now-supported method (meaning putting the .sqlite db file and the data/khan directory in the right places).

**Comment by MCGallaspy** [comment]
Resolved.

**Comment by benjaoming** [comment]
And just for the record:

If you run a **git-based installation**, do not worry. It will still work, and running `bin/kalite manage setup` after doing `git pull` is still a valid updating scheme.. it's what all the devs would do :)

**Comment by MCGallaspy** [comment]
Yes, and also for the record there are a few more steps which are not well-documented. Please attempt to use our recommended installation methods first, but if you wish to run from source (as you might if you wish to develop KA Lite) then you should reach out to the devs to get the latest info for how to set up a development environment.
