### ISSUE TITLE
RPi warning message - can it be removed?

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#3782]
The video download page warns users about only downloading one video at a time. But it doesn't say that this is already what happens. So it kind of makes you look for the button that goes "Fetch videos one by one" or even worse would make users tick one video, download it, and then tick the next.

![one_at_a_time](https://cloud.githubusercontent.com/assets/374612/7958984/0912efe6-09f5-11e5-8cef-e5f8d22476ad.png)

My suggestion: Remove the warning, write something in the Docs on bulk downloading with btsync because that's where the problem occurs.

**Comment by jamalex** [comment]
> or even worse would make users tick one video, download it, and then tick the next

I think this is actually what it is recommending, as we've had problems on low-powered devices when many video files are queued at once. One at a time is probably a bit conservative, but more than, say, 100 at a time may cause problems. More testing is needed, and improvements to the way the queuing works are also needed.

**Comment by benjaoming** [comment]
Let's get it sorted out like this: We have a `raspberry_pi` settings module and an automated script for setting up Raspberry Pis (that doesn't look nice in plural), and so we should have a setting that forces linear downloading.

**Comment by rtibbles** [comment]
Downloading *is* already linear.

The issue here is that the current downloading code uses the database to track downloading progress. Trying to create the entries for too many videos at once in an SD card backed SQLite database causes problems, because there is too much write activity at once.

It is not about downloading, so much as queuing for download.

**Comment by rtibbles** [comment]
(But I think the user is best spared that level of semantics)

**Comment by benjaoming** [comment]
Thanks for explaining, @rtibbles 

Maybe we can fix this for 0.15 by having a better queue mechanism and thus make the message redundant.

**Comment by rtibbles** [comment]
I think that is definitely the best way. @jamalex and I had discussed only
holding the queue in memory as an alternative.

Another possibility, which could tie into making the cache invalidation
more efficient, is to complete @MCGallaspy's database backed content
caches, and we could then track downloading there, and then trigger cache
updates there too.

**Comment by rtibbles** [comment]
This issue is no longer extant since #4630
