### ISSUE TITLE
Attempting to download language pack results in error

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#3788]
On `develop`.
Steps to reproduce: log in as admin, attempt to download a language pack. Results in a bubble alert on the page with the text `Unexpected error; contact FLE with the following information: 200` along with the html for the language pack download page.

Screenshot:
![ss](https://cloud.githubusercontent.com/assets/8888020/7972909/1c6bae1a-0a05-11e5-9927-d256f36e1b1e.png)

**Comment by rtibbles** [comment]
This does sound very familiar.

**Comment by MCGallaspy** [comment]
@rtibbles 
Okay, I remember what's going on now. The request fails because the `window.sessionModel.get("START_LANGUAGEPACKDOWNLOAD_URL")` is undefined (how did that slip back in?), but something funny is going on with the server's response; failure shouldn't return a rendered page, just a message.

**Comment by rtibbles** [comment]
Fixed in #3790

**Comment by rtibbles** [comment]
Found this again today...

**Comment by radinamatic** [comment]
I'm not getting this error, and I just pulled develop and updated my Spanish language pack...

But then again, I'm basking in Windows mud, so that might be an issue (again) :P

**Comment by rtibbles** [comment]
Hrm. Might be a pyc issue? Will close for now and double check in the morning.

**Comment by rtibbles** [comment]
Yep, was a pyc issue @MCGallaspy.
