### ISSUE TITLE
Degenerate video and exercise ids

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#3807]
Branch: develop
Expected Behaviour: Clicking on the link for, or going to this URL: http://127.0.0.1:8008/learn/khan/math/early-math/cc-early-math-add-sub-basics/cc-early-math-add-subtract-10/addition-and-subtraction-within-10/ should take you to the exercise with that name
Current Behaviour: Clicking on the relevant link, or going to this URL, actually takes you to the video that has the same id.

![image](https://cloud.githubusercontent.com/assets/1680573/8047617/c549bcac-0dfc-11e5-9e27-ed4e86522102.png)

**Comment by 66eli77** [comment]
do you think this is caused by the data in json file that we use to populate the list?(slug)
If that's the case, I loosely remember we encounter the same issue before, but don't recall what the solution is at that time. By modifying the json file?

**Comment by MCGallaspy** [comment]
The problem occurs on the front end, where nodes are looked up by slug. The slug evidently is not unique, and so makes for a poor primary key.

**Comment by MCGallaspy** [comment]
Taking a stab at a fix now.

**Comment by rtibbles** [comment]
Fixed in #3915
