### ISSUE TITLE
Command line for running specific behavior test

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#3829]
Branch: develop
Current: with a hacky way of renaming the testing folder, we still have to run through all the behavior tests
Goal:  be able to run specified B-test from command line

**Comment by 66eli77** [comment]
this isn't urgent, but nice to have to boost productivity.

**Comment by MCGallaspy** [comment]
See #3689

**Comment by 66eli77** [comment]
cool already has PR. close this
