### ISSUE TITLE
No need (or use) in asking for email address when creating superuser, and password should be hidden

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3833]
Expected: The form that shows up when the server is first run without running setup asks for the critical information for setting up the server, and handles it appropriately.

Observed:

- The user is asked for an email address, which won't get used anywhere, and might be problematic for some users who are totally offline. We should just put a dummy email address into the user creation, and not show this to the user at all.
- The password field is shown in plaintext, rather than as ******. To fix this, set `<input type="password" ...>`. There should also be a second "confirm password" box, to avoid problems from typos, since there's no easy way to reset the password later.

![image](https://cloud.githubusercontent.com/assets/618416/8141126/8673a862-1117-11e5-8c43-7d87e95c8b81.png)

**Comment by jamalex** [comment]
Probably best to ask for the password twice, also, to avoid typos, since they don't have any clear ways to recover the password.

**Comment by 66eli77** [comment]
fix is in PR #3888
