### ISSUE TITLE
Some topic tree API calls take a long time

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3835]
Branch: develop
OS: Ubuntu

Expected: sidebar navigation should now be fast, given the fancy refactoring @rtibbles did.

Observed: Clicking around the top-level topics, often it would take much longer than usual (8+ seconds) to load the contents of the topic into the second level of the sidebar.

![image](https://cloud.githubusercontent.com/assets/618416/8141250/1deaa474-1119-11e5-81cd-6defd0754f6b.png)

Note: The video download process was going on in parallel, which could be affecting this.

**Comment by jamalex** [comment]
Sometimes it seems to return `{"error": "Unexpected error: 'str' object has no attribute 'get'"}` as well.

![image](https://cloud.githubusercontent.com/assets/618416/8141293/e028933e-1119-11e5-8025-a1e69db3af0c.png)

**Comment by jamalex** [comment]
The slowdowns seem to have resolved now that the video download process is complete. I wonder whether there's any way we can reduce the priority level of the video download task, so it doesn't mess with other site interactions as much?

**Comment by rtibbles** [comment]
@jamalex this might be related to the apparent recurrence of #2976.

**Comment by MCGallaspy** [comment]
Leaving this open; seems fine to me, but is somewhat subjective.

**Comment by rtibbles** [comment]
@jamalex Can you check to see if this is extant now that #3906 has been merged?

**Comment by jamalex** [comment]
Will check on the latest 0.14.x branch.

**Comment by jamalex** [comment]
The testing I did on this was unable to replicate it, so I'd say we're good for now.
