### ISSUE TITLE
Clicking icon to run KA Lite app does not pop up task tray or give feedback that it did something

### ISSUE THREAD

**Issue by jtamiace** [learningequality/ka-lite#3836]
Windows 8.1

It wasn't until I checked the icon tray after clicking the KA Lite app icon multiple times that I saw that it had done something. Should the icon tray pop up right away since it wasn't too apparent that it had done something to the task tray? 

There were also as many icons as the number of times that i clicked on the app: 
![task tray](https://cloud.githubusercontent.com/assets/6668144/8141422/6524b968-111b-11e5-884f-03472f6d6d93.png)

Steps to reproduce:
-Install KA Lite
-Set so the server does not start on computer start up
-Restart computer
-Click app icon for KA Lite

**Comment by benjaoming** [comment]
@cpauya is this still an issue and should we move it to installers?

**Comment by djallado** [comment]
I already transfer this issue in installers. I'll close this.
