### ISSUE TITLE
"Show tabular report" is enabled even when there's no data to show, and shows the legend but no table.

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3837]
Expected: Buttons should only be enabled when they will do something useful.

Observed: "Show tabular report" is enabled even when there's no data to show, and shows the legend but no table.

![image](https://cloud.githubusercontent.com/assets/618416/8141423/66e34404-111b-11e5-857d-7be3b860da47.png)

**Comment by rtibbles** [comment]
Is there literally no data here, or just no recent data?

**Comment by rtibbles** [comment]
Fixed in #3886.
