### ISSUE TITLE
Tabular coach report numbers don't continue all the way across the table

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3839]
Expected: Numbers show up on all cells in the tabular report table.

Observed: After scrolling a ways to the right, the numbers no longer show up.

![image](https://cloud.githubusercontent.com/assets/618416/8141452/dfaf428e-111b-11e5-90de-0ff4fa753d0f.png)

Steps to replicate: Run `kalite manage generaterealdata`, go to coach reports, select "Wilson Elementary", and click "show tabular report", then scroll across.

**Comment by rtibbles** [comment]
Yeah, I noticed this just before we did the demo on Thursday - I can't for the life of me think what might be causing it.

**Comment by rtibbles** [comment]
I am too clever for my own good. The blank ones are videos! Fixing now.

**Comment by rtibbles** [comment]
Fixed in #3886.
