### ISSUE TITLE
My Progress on mobile does not work

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3840]
Browser: Firefox 37

Is unclickable.

![image](https://cloud.githubusercontent.com/assets/191955/8141493/98e799ae-111c-11e5-9773-02f57273f90f.png)

**Comment by MCGallaspy** [comment]
To add to this "My Progress" appears to be interactable on the desktop, but clicking it doesn't do anything (as a student).

**Comment by 66eli77** [comment]
When click "My Progress" on Mac Chrome, nothing happened.

**Comment by jtamiace** [comment]
Yeah, there's no url in the handlebars template for the nav bar.

**Comment by rtibbles** [comment]
Fixed in #3866
