### ISSUE TITLE
Detail view 

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3845]
Expected: Clicking a cell in the tabular report should expand down and show a detail view below the clicked cell.

Observed: When scrolled a ways to the right and clicking a cell, an empty white space expands down below the row that was clicked, but it appears to be empty:

![image](https://cloud.githubusercontent.com/assets/618416/8141497/ae980db0-111c-11e5-8b17-e5e1af4c97ed.png)

Scrolling all the way back to the left shows that the details were rendered at the far left of the expanded row, which isn't so helpful:

![image](https://cloud.githubusercontent.com/assets/618416/8141603/666914c4-111e-11e5-90c8-e36270ae28f1.png)

**Comment by rtibbles** [comment]
Ah, seems that @Joymysoy never got time to fix this.

**Comment by Joymysoy** [comment]
Ah yes! I never figured it out.

**Comment by rtibbles** [comment]
And now you are freeeeeeeee!

But yes, I am pretty sure I know what to do here.

**Comment by Joymysoy** [comment]
WAHOOOO!! Sike, Not really that free. 🌝

Also thank you!!

**Comment by rtibbles** [comment]
Fixed in #3886.
