### ISSUE TITLE
Clicking that topic 'back button' too fast results in an empty topic

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3847]
Browser: Firefox 37
branch: develop

steps to reproduce:
1. Go to a node that's at least 3 levels deep.
2. Rapidly click on the 'back' button.
3. Get this:

![image](https://cloud.githubusercontent.com/assets/191955/8141606/6e0a6bce-111e-11e5-8bf4-094e7010572d.png)

![image](https://cloud.githubusercontent.com/assets/191955/8141609/8835ecda-111e-11e5-9a37-3d34dd0591ec.png)

  4.) (non-)profit.

**Comment by rtibbles** [comment]
Solution: Disable the back button until the current sidebar tab has finished being deleted?

**Comment by aronasorman** [comment]
:+1:

**Comment by rtibbles** [comment]
Oh, I tell a lie. This is actually happening because the topic display is potentially being removed twice due to race conditions.

**Comment by rtibbles** [comment]
Fixed in #3901
