### ISSUE TITLE
[MAC] KA-Lite Installer \\ Error Message When Installing

### ISSUE THREAD

**Issue by whitzhu** [learningequality/ka-lite#3849]
===ERROR MESSAGE===
"Either the set environment variables or symlink of chalet failed to complete! Please check the Console."

===SYSTEM SPECS===
OS X Yosemite Version 10.10
Macbook Air 
Processor 1.7 GHz Intel Core i5
Memory 4GB 1333 MHz DDR3

===SCREENSHOT===
![screen shot 2015-06-12 at 3 35 21 pm](https://cloud.githubusercontent.com/assets/12800136/8141623/a8b0f0a4-111e-11e5-9c5e-581f38343ea7.png)

**Comment by aronasorman** [comment]
Should be fixed in the latest mac installer.
