### ISSUE TITLE
some JSON not being rendered properly in coach reports

### ISSUE THREAD

**Issue by jtamiace** [learningequality/ka-lite#3850]
Shown in attempts 3 and 5

![json problem](https://cloud.githubusercontent.com/assets/6668144/8141653/2118ea38-111f-11e5-834e-b429bd285ce0.PNG)

**Comment by rtibbles** [comment]
For this, I think the only practical solution for 0.14 is to hide non-simple answers, as rendering the object-type answers requires digging into the guts of perseus.

**Comment by rtibbles** [comment]
Fixed in #3886.
