### ISSUE TITLE
Loading new coach report data does not clear old warning messages

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3854]
Expected: "No recent learner data for this group is available" message is shown after selecting options in the dropdowns for which there is no matching data, but should go away when new options are selected that result in data being available.

Observed: It. never. goes. away. Like. never.

![image](https://cloud.githubusercontent.com/assets/618416/8141679/879e8f56-111f-11e5-8bf5-dfd6baebe499.png)

**Comment by rtibbles** [comment]
Well,that's why we put that little 'x' there for them to dismiss it, of course!

**Comment by rtibbles** [comment]
Fixed in #3886.
