### ISSUE TITLE
Unfinished line on the language page

### ISSUE THREAD

**Issue by jtamiace** [learningequality/ka-lite#3855]
![unfinished line on language page](https://cloud.githubusercontent.com/assets/6668144/8141735/639ecd36-1120-11e5-95eb-ce02b57cd628.PNG)

**Comment by MCGallaspy** [comment]
I'm not seeing it. Can you describe what you expected?

**Comment by MCGallaspy** [comment]
Oh, it's the horizontal separator, I see.
