### ISSUE TITLE
in Coach Reports, click exercise leading to the exercise content with sidebar opened

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#3856]
Mac installer
Chrome
Current: in side Coach Reports, click a exercise inside Learner's report will direct you to the exercise content, but the content is covered by the open sidebar, and the sidebar is displayed with problem(the fade area is not shown and require two clicks to close the sidebar)
Expected: direct to the exercise content with sidebar closed, so that the user can see the content directly.

**Comment by benjaoming** [comment]
@radinamatic I think you've reported this, too somewhere?

**Comment by benjaoming** [comment]
Can't recreate, but the more pressing issue is that we don't deeplink to individual questions of the exercises #5044
