### ISSUE TITLE
Logging in as a teacher redirects to splash screen instead of coach reports

### ISSUE THREAD

**Issue by jtamiace** [learningequality/ka-lite#3857]
![teacher login](https://cloud.githubusercontent.com/assets/6668144/8141910/7c3801fc-1123-11e5-8143-231550630305.PNG)

Also, if you navigate to the "learn" page as a guest, and then try to login as a teacher from the learn page, it stays on the learn page instead of doing any kind of redirect.

**Comment by jtamiace** [comment]
Also logging in as a teacher from the "sign up" page keeps you on the sign up page:

![teacher login from sign up](https://cloud.githubusercontent.com/assets/6668144/8142086/18cf9d24-1127-11e5-9ba7-3fddf53a0f70.PNG)

**Comment by rtibbles** [comment]
Fixed in #3899
