### ISSUE TITLE
Confusing interface in tabular report cell detail view

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3858]
Context: When data is generated using `generaterealdata`, the detail view for tabular report cells is confusing. Some parts of this probably apply with actual real data, as well.

We should:

- Improve generaterealdata to generate realer data
- Fix these reports to better handle missing pieces

![image](https://cloud.githubusercontent.com/assets/618416/8141759/d884beda-1120-11e5-9a88-14de9dd5549a.png)

1. The empty attempt table doesn't need to be shown.
2. It's unclear what the relationship is between the "Question 1-4" down the left and the pagination "1-4" at the bottom.
3. Clicking on one of the pagination numbers scrolls you back to the top of the page (likely because of the # link), but doesn't change anything.
4. "Time taken: seconds" is shown, even though there's no number in there.

**Comment by jamalex** [comment]
@rtibbles I'm assigning all these coach report issues to you just because you're probably the best person to triage and re-assign them. :)

**Comment by rtibbles** [comment]
Yeah, getting the pagination to appear outside the tabs was unusually difficult for some reason.

Question: Does the pagination even work? I honestly have no recollection of implementing it.

**Comment by rtibbles** [comment]
Fixed in #3886.
