### ISSUE TITLE
Extra hurdles: Show the installation information right away in central server FAQ 

### ISSUE THREAD

**Issue by ghost** [learningequality/ka-lite#386]
Situation: When click on "How do I install ka-lite", I was shown with this 
![img_3547](https://f.cloud.github.com/assets/4604132/903663/a017cc2c-fbb0-11e2-94a4-3643e71d5297.PNG)

![img_3548](https://f.cloud.github.com/assets/4604132/903658/8e5f1d32-fbb0-11e2-8ad9-7cfb19c4f07d.PNG)

Then, after clicking on the "installation page" link, I was shown the installation process (which I am looking for) 
![img_3546](https://f.cloud.github.com/assets/4604132/903666/c200efa8-fbb0-11e2-9480-6f98f53c0bc7.PNG)

It could save users an extra step if they can see the installation page (what they asking for) as soon as they click on the related question.

**Comment by aronasorman** [comment]
Fixed in the upcoming docs: http://field.learningequality.org/docs/installguide/install_main.html
