### ISSUE TITLE
Videos not rendering properly when subtitles are present

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3861]
Expected: Subtitles render on videos A-OK.

Observed: Videos with subtitles aren't rendering at all.

Steps to replicate: Download videos, then upgrade EN language pack, then go to a video page which should have subtitles.

![image](https://cloud.githubusercontent.com/assets/618416/8142076/98f1ae94-1126-11e5-88ab-6808d981cee7.png)

With JS error message `Uncaught TypeError: Cannot read property 'apply' of undefined`, which comes from the Django JS reverse stuff, for the line `window.Urls[url_name].apply(window.Urls,arguments);`.

The problem is that we're referencing `{{ url }}` in the [video player handlebars template](https://github.com/learningequality/ka-lite/blob/develop/kalite/distributed/hbtemplates/video/video-player.handlebars#L5) for the subtitles, but @rtibbles recently also added a Handlebars helper for url reversal, with the same name, which is now getting called instead. Not sure the best way to resolve this, but we probably either need to rename the helper method, or modify the name of the subtitle URL attribute getting stamped onto video data.

**Comment by jamalex** [comment]
Not quite sure how this is related to #3831.

**Comment by rtibbles** [comment]
In this case, this is pretty easily resolved just by using ```{{ this.url }}``` instead of just ```{{ url }}```.

**Comment by jamalex** [comment]
This would be a good idea!

**Comment by jamalex** [comment]
I will do this!

**Comment by jamalex** [comment]
Woohoo!!!!!

![image](https://cloud.githubusercontent.com/assets/618416/8142133/86a5bdd2-1128-11e5-8393-7fd36d56dae6.png)

**Comment by rtibbles** [comment]
Fixed in #3864
