### ISSUE TITLE
Content Recommendation Explore display issue

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#3863]
when the screen is wide enough to show the three cards(Resume, NextSteps, Explore) in a row, "Arithmetic" sticks into "Description"
![screen shot 2015-06-12 at 5 34 33 pm](https://cloud.githubusercontent.com/assets/5577205/8142157/65d62712-1129-11e5-81d6-10c4c3d27c6c.png)

**Comment by manipalsingh013** [comment]
hey @66eli77 I think overlapping of text is also there, 
![explore in same row](https://cloud.githubusercontent.com/assets/13970876/13284259/25164bd4-db19-11e5-9449-9ad55611cfcf.png)

how about displaying heading and description in different rows like(i.e setting their width to 100%)?
![explore in different rows](https://cloud.githubusercontent.com/assets/13970876/13284280/48c2f23a-db19-11e5-95f4-739db09c0979.png)

**Comment by 66eli77** [comment]
@manipalsingh013  nice finding and suggestion!

**Comment by rtibbles** [comment]
Looks good!

**Comment by rtibbles** [comment]
Fixed in #4922
