### ISSUE TITLE
Message about initial login

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#3874]
Could we just remove this? After the built-in UI form for creating the first user, the "createsuperuser" alternative, this becomes somewhat inaccurate...

![screenshot from 2015-06-15 20 45 18](https://cloud.githubusercontent.com/assets/374612/8167579/7ed248a4-139f-11e5-91b3-a0dbf8713c1c.png)

**Comment by 66eli77** [comment]
@benjaoming  this message will gone if you login with a superuser and create a facility and then register the device. So, it functions as a reminder to guide the user finishing setup process. Since it's kinda useful, do we really want to remove it?

**Comment by benjaoming** [comment]
@66eli77 read it again, it says **with the account you created while running the installation script**

**Comment by 66eli77** [comment]
how about changing the message to this: 
"Please login with the superuser account you created, then create your facility and register this device to complete the setup."

**Comment by benjaoming** [comment]
:+1:
