### ISSUE TITLE
Coach Report error -  AttributeError: 'VideoLog' object has no attribute 'exercise_id'

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#3882]
**Branch/Date**: Latest develop

**Expected behavior**: Choosing the Facility should present info about learner activity, or clean alert message that there is no recent one.
 
**Actual behavior**: Choosing the Facility from the drop down throws an `AttributeError: 'VideoLog' object has no attribute 'exercise_id'` error

![attributeerrorvideolog](https://cloud.githubusercontent.com/assets/1457929/8195813/c7d7b32c-1485-11e5-9fd7-ecfa8f7771c6.png)

 
**Steps to reproduce**:
1. Log-in as admin
2. Go to Teach tab
3. Choose a Facility from the drop down

**Important: I have a fresh database with only one Facility & one Learner in it.**

Hitting the "Show Tabular Report" gives no errors at this point so I'm not sure if/how this is related with @rtibbles #3880 issue.

![tab-report](https://cloud.githubusercontent.com/assets/1457929/8195908/776c9e74-1486-11e5-8f4e-977a03192d6b.png)

**Comment by radinamatic** [comment]
More info: Selecting back the "Default Facility" from the drop-down maintains the same error but displays the alerts correctly:

![tab-report-def-facility](https://cloud.githubusercontent.com/assets/1457929/8196041/ab424b30-1487-11e5-8080-94e60cd9924a.png)

**Comment by rtibbles** [comment]
Fixed in #3886.
