### ISSUE TITLE
Add basic instruction for "generaterealdata" into wiki and doc pages

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#3883]
Until a more elaborated "gentle dev introduction" docs are created, we should add the basic instruction for running the "generaterealdata" to create a facility, learners, and coaches, into both the [Getting Started](https://github.com/learningequality/ka-lite/wiki/Getting-started) wiki page and our documentation pages.

**Comment by radinamatic** [comment]
I added the basic instruction to the Getting Started wiki page, so as soon @rtibbles' PR is merged, this can be closed.

**Comment by rtibbles** [comment]
Fixed in #3886.
