### ISSUE TITLE
Feature request -- subtitle availability indication

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#3889]
We should indicate somehow whether subtitles are available on a video. Otherwise, especially in the case of incomplete subtitle coverage, users just have to guess. @radinamatic might have some ideas on how to best implement this.

**Comment by aronasorman** [comment]
This is actually a feature regression. With KA Lite <= 0.12 we had an indicator on each topic in the topic tree that shows which subtitles and dubbed videos are available.

**Comment by radinamatic** [comment]
Opened as "nice to have" option for Kolibri, and not going to happen within the scope of KA Lite.
Can be closed.  @aronasorman  @MCGallaspy

**Comment by benjaoming** [comment]
Yup, guessing that's how it is!
