### ISSUE TITLE
`kalite manage` does not process positional arguments.

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3891]
On the latest develop:

`kalite manage test <test arg>` runs all tests.

`kalite manage unpack_assessment_zip <zipfile>` errors out because the `args` argument in `handle` is empty.

Somewhere in `kalitectl.docopt` these positional arguments aren't getting processed and passed on correctly.

**Comment by MCGallaspy** [comment]
Duplicate of #3892?
