### ISSUE TITLE
Remove *pyc files

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#3895]
This will make you smile @jamalex :)

In #3783, I removed django_extensions which was just being used by the update command (removed) and to run the management command `clean_pyc`. This made the codebase over 33,000 lines shorter :)

The `clean_pyc` command is pretty much equivalent to `find -name '*pyc' -exec rm {} \;` or something.

So we need a simple python-version of this command to run in the "setup" management command to make up for its removal.

**Comment by rtibbles** [comment]
Fixed in #3896
