### ISSUE TITLE
Unused templates (cleanup)

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#3907]
These two templates are not used anymore:

`kalite/playlist/templates/playlist/view_playlist.html`

and

`kalite/distributed/templates/distributed/video.html`
  
  

  

Should be eliminated during the 0.15 cleanup of unused files.

**Comment by rtibbles** [comment]
I think it is reasonable to have a purge of this sort at the beginning of every development cycle.

**Comment by MCGallaspy** [comment]
This also involves removing unused views and urlconfs.

**Comment by rtibbles** [comment]
I am punting this, as I have a lot of this cleanup in an open PR, but too risky for 0.15.

**Comment by rtibbles** [comment]
This was fixed in #4261
