### ISSUE TITLE
Testing cleanup TODOs

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#3909]
Each scenario needs to be more carefully isolated. One scenario should not affect another. TODO:
- [x] In `base_environment.py`, create a new webdriver instance before each scenario, and close it afterwards.
- [x] Reverse any DB transactions made after each scenario, so that we start with a clean slate.
- [ ] ~~Use `before_tag` and `after_tag` hooks. [See here](http://pythonhosted.org/behave/api.html#environment-file-functions).~~
- [x] Address any scenarios that implicitly rely on side effects from previous scenarios.

**Comment by benjaoming** [comment]
# Nominating: Query tests

I would like to nominate removing `self.assertNumQueries` and possibly the whole `query_tests` module for the following reasons:

1. When it fails, it's very hard to work with. Is it failing for a good reason? Which query shouldn't have been there? Which query is missing? There's no usable output.
1. What is it actually testing? Is there a specific goal in having X number of queries?

Let's say someone optimizes something and reduces the number of queries. Why are they imposed test failures and have to clean up the tests?

Tests are not supposed to make development impossible and freeze the codebase! They are supposed to test that specific *critical* elements of functionality remain.

**Comment by rtibbles** [comment]
I concur @benjaoming - keeping the number of queries to a minimum should be something we are tracking using profiling, not tests.

**Comment by aronasorman** [comment]
+1. I remember this was my main blocker for moving to CircleCI.

**Comment by benjaoming** [comment]
I've been spending the past couple of hours getting debug output and figuring out why there's 76 queries and not 33-38 as the tests say... still not getting anywhere.

**Comment by rtibbles** [comment]
My guess would be the page is loading twice.

**Comment by benjaoming** [comment]
Yes, but I don't understand why my local develop is different from the one that is currently passing in Travis.

**Comment by aronasorman** [comment]
Note: Query tests have been cleared ever since we migrated to CircleCI ([PR](https://github.com/learningequality/ka-lite/pull/3932)).

**Comment by MCGallaspy** [comment]
The specific bullet points were addressed in https://github.com/learningequality/ka-lite/pull/4130. Test improvements continue.
