### ISSUE TITLE
Says username incorrect when password is incorrect

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#3910]
Branch: develop
Reproducing: Type in correct username and incorrect password

![wrong_username](https://cloud.githubusercontent.com/assets/374612/8283435/b10661fe-18f7-11e5-96ac-c4f464a558dd.png)

**Comment by rtibbles** [comment]
This is because we only give username based warnings for FacilityUsers not Django Users. Do you think it is helpful to expose the Django Users in this way too?

**Comment by benjaoming** [comment]
Well, it's a bit confusing to be told that the username doesn't exist when it does, that was my main grief :)

**Comment by rtibbles** [comment]
Yeah, I guess we were willing to tolerate the admin being confused.

**Comment by benjaoming** [comment]
okay, I guess the fundamental problem then is more about creating a different auth system and still using it together with django.contrib.auth :)

**Comment by rtibbles** [comment]
Yep. We can fix that when we do breaking changes in the database! :+1:
