### ISSUE TITLE
Put built html docs in a static source

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#3911]
If docs are supposed to be distributed and used, I suggest moving the outputs of "make html" to a static source so they can be browsed by users.

**Comment by benjaoming** [comment]
Adding release blocker as I suppose we want to release with docs bundled?

**Comment by MCGallaspy** [comment]
Okay, but do we really wish to commit the built docs to the repository? Is that what you're suggesting, or only that we change the default output location?

**Comment by benjaoming** [comment]
Well, how would I obtain the docs when I run "setup.py sdist" to create a source distribution?

**Comment by MCGallaspy** [comment]
> Well, how would I obtain the docs when I run "setup.py sdist" to create a source distribution?

Fetch them from field.learningequality.org

**Comment by benjaoming** [comment]
Yeah, I'm suggesting to put the built docs in git as of now so we can run "python setup.py sdist" -- otherwise you'd have to have a URL that would go something like:

http://somewhere.com/our_docs.zip?branch=develop

You could do that by creating a new repository on  github and have the built docs there until we have a better solution.

**Comment by MCGallaspy** [comment]
Turns out the only thing you need to do is invoke make with a new option: `make BUILDDIR=/my/cool/dir html`

**Comment by benjaoming** [comment]
Yup, I was hoping for that, too :) But you're still saying that building these files is too complicated for the `setup.py sdist` person, right?

**Comment by MCGallaspy** [comment]
I'm saying try it out, but expect frustrating timeouts as with the tests at this point.

**Comment by benjaoming** [comment]
Hurray :)

**Comment by benjaoming** [comment]
Removing the "release blocker" part as I'm not sure anymore if this blocks the release :)

**Comment by MCGallaspy** [comment]
Addressed in https://github.com/learningequality/ka-lite/pull/3814

**Comment by benjaoming** [comment]
@MCGallaspy perhaps we should add docs/_built to MANIFEST.in.dist ? Then they will be included in the sdist.

**Comment by MCGallaspy** [comment]
Sounds good.
