### ISSUE TITLE
Error during completion of language pack download (`Error during update: Error: [Errno 13] Permission denied: '/static'`)

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3919]
Branch: develop

Downloaded the Spanish language pack. It went through all the stages, and at the end popped up with:

![image](https://cloud.githubusercontent.com/assets/618416/8313245/606a3604-1996-11e5-9207-b30041e75c2f.png)

It doesn't seem to have properly unpacked the subtitles or exercises (these go under `static`).

**Comment by jamalex** [comment]
Ok, I've determined where the problem in the code is. Fixing now.

**Comment by rtibbles** [comment]
Fixed in #3923
