### ISSUE TITLE
Duplicate settings files for topic tools

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3920]
Branch: develop

`kalite/topic_tools/settings.py` and `kalite/legacy/topic_tools_settings.py` seem to have the same stuff in them, making it unclear which should be edited.

**Comment by jamalex** [comment]
The settings actually seem to have been modified in one, and no longer match the other file. There's a comment saying "This will be cleaned up in KA Lite 0.14".

**Comment by benjaoming** [comment]
It's done in #3809
