### ISSUE TITLE
Feature Request - User Accessibility Settings

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#3921]
After we discussed the general color & contrast issues for better accessibility during our recent meeting, @jtamiace and I came with the idea to implement **User Accessibility Settings**. We thought of starting with options that should help primarily the users with low vision, and therefore nicely complement the efforts on video/captions improvements front (for hearing disabilities), and keyboard navigation improvement front for blind users. 

### Implementation examples  

**FluidProject - Learner Options** http://fluidproject.org/  
Check the **color & contrast** options in the **show display preferences** tab in the upper right corner. This solution is based on the whole **Infusion framework** and probably not the option we should try to implement right now, but serves as the nice example.  

![fluid](https://cloud.githubusercontent.com/assets/1457929/8317912/19c75842-1a01-11e5-8caa-73c9980a6cef.png)

**Alzheimer's Society - User Settings** http://www.alzheimers.org.uk/site/scripts/user_settings.php
Simple **High Contrast & Background** options that the users can choose from.  

![alzheimersociety](https://cloud.githubusercontent.com/assets/1457929/8317919/22c96098-1a01-11e5-8850-506cab0109c2.png)

-----------------------------------
I will be joining the Design team weekly meetings and @jtamiace mentioned that one of their interns may be available to work together on implementing this feature... :)

Anybody with other ideas, opinions and suggestions, feel free to chime in!

**Comment by rtibbles** [comment]
Not going to happen within the scope of KA Lite.

@radinamatic please open an issue for this on the Kolibri repo.
