### ISSUE TITLE
Sign-up form for Learners who already logged in

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#3926]
**Branch**: latest develop  

**Current Behavior**: If by error Learner user presses the "Sign up" button on the homepage, and once the sign-up form appears they realize the mistake and press the Login button, after they login with modal dialog, they remain on the **/securesync/signup/** page with the "Sign up for an account" content below the welcome message, and the "Sign up for an account" in the window title.  

![sign-up-loggedin-user](https://cloud.githubusercontent.com/assets/1457929/8331666/ccdfebfa-1a89-11e5-944a-374c2aded521.png)

This is confusing and will make no sense to the users.  

**If you do the same but login as an Admin user, you will end up (correctly) on the Manage page.**
 
**Expected Behavior**:  I suppose most of the time Learner wants to go to "learn", or check their Progress report, the only two options they have, if I understand well. The most appropriate destination is the recommended content with Resume and the Next steps options, but this doesn't happen if by error they try to sign-up first..

**Steps to reproduce**:

1. Press the "Sign up" button on the homepage
2. Press the Login button, and enter Learner credentials inside modal dialog.

**Comment by radinamatic** [comment]
This is still valid on 0.16, but is a fairly minor issue... Punt to 0.17 @benjaoming!

**Comment by benjaoming** [comment]
Fixed in #5315
