### ISSUE TITLE
Decide whether to resurrect deleted tests

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#3933]
In #3932 some tests are deleted (https://github.com/aronasorman/ka-lite/commit/bc13993fa319eec9084773f71cc81413e8c2a3d7). We should decide whether:
* The test was irrelevant and will not be missed.
* We really want the coverage the test was attempting to provide and should write a better test.

Goes hand-in-hand with #3909.

**Comment by MCGallaspy** [comment]
More deleted tests here: https://github.com/aronasorman/ka-lite/commit/84527bae4f964fa6bc5c1644abef66a9eba8ec1f

**Comment by rtibbles** [comment]
I don't think we should resurrect these, and new tests should be written as code is maintained to prevent regression bugs.
