### ISSUE TITLE
Convenience: Settings module convention

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#3937]
# Problem statement.....

(scroll down for proposal)

Since #3809, it's now required to customize settings through Python module inheritance. This means that we have to use `kalite <command> --settings=settings_module`, where `settings_module` is a Python module in user's `sys.path`. That could be a file in the current directory.

So this is great, now we don't force injection of `local_settings.py` into the application source files (but still available as a deprecated pattern), and settings have a much more clean load path.

Now, consider this use case: We are building a UI, that has an interface for setting options:

![settings](https://cloud.githubusercontent.com/assets/374612/8376858/f64d597c-1c0b-11e5-812c-d9fa81beb16e.png)

Some settings are for invoking `kalite` from command line by setting options, like `--port`, while others will affect it's settings module, maybe by injecting Python code into a file or by having a custom settings module that reads from another INI/JSON file.. Most likely, the UI will have `kalite` will run with a `kalite <command> --settings=kalite_gtk.kalite_settings` or similar.

But this sucks from a user perspective!

It means that a user running `kalite` from command line will not have settings from the UI, unless they know which settings module the UI runs from.

This is inconvenient, and the conclusion from previous discussions on deprecating local_settings is that it has to be at least as convenient as the previous practice....

# Proposal then......

* First time KA Lite runs, it will create `~/.kalite`. This directory should always be populated with `my_settings.py`. If the file exists, it will be loaded, and if it doesn't, we run with default settings.

The change would happen in `kalite.project.settings.default` (should also be the default value of `DJANGO_SETTINGS_MODULE`, rather than .base).

```python
import os
DEFAULT_USER_SETTINGS_FILE = os.path.join(os.environ["KALITE_HOME"], 'custom_settings.py')

# Check if default user file exists and load settings from there
if os.path.isfile(DEFAULT_USER_SETTINGS_FILE):
    execfile(DEFAULT_USER_SETTINGS_FILE)

# If not, write a new custom user settings file and continue loading with
# defaults.
else:
    with open(DEFAULT_USER_SETTINGS_FILE, "w") as my_settings:
        my_settings.write("from kalite.project.settings.base import *\n# Put your custom settings here\n# MY_SETTING = 123")
    from .base import *

...
```

**Comment by MCGallaspy** [comment]
Seems pretty reasonable. About to take a peek at the corresponding PR>

**Comment by benjaoming** [comment]
Just a little note on the original description: I went for `~/.kalite/settings.py` for ease.

**Comment by benjaoming** [comment]
So, this is merged, hurray!
