### ISSUE TITLE
kalite.bat can't accept user input

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#3944]
On windows 8, in `develop`:

Scripts which require user input (like the setup management command without the no-interaction flag) can't accept input when you call them with "kalite.bat manage mycoolscript". Works ok with "python.exe kalite mycoolscript". Since the main commands (start, stop, status) all don't require input, I'm not considering this a release blocker.

**Comment by benjaoming** [comment]
You mean input as in interactive command line input, e.g. `kalite manage setup` ?

**Comment by benjaoming** [comment]
The new `setup.py` uses its own .bat template, so we can actually deprecate bin/windows/kalite.bat ?

https://github.com/learningequality/ka-lite/blob/develop/setup.py#L172

**Comment by MCGallaspy** [comment]
>You mean input as in interactive command line input, e.g. kalite manage setup ?

Yes.

**Comment by aronasorman** [comment]
@MCGallaspy is this still the case?

**Comment by MCGallaspy** [comment]
Yes.

**Comment by aronasorman** [comment]
Alright. I'm leaving this on 0.15.0 as this seems like a critical bug.
