### ISSUE TITLE
Test suite gets stuck in a subprocess for considerable time

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#3945]
branch: develop
Since changes by @benjaoming and @MCGallaspy were merged to develop, I am now finding that the test suite will frequently stall (or at least take an incredibly long time to continue).

Pressing Ctrl-C breaks out of this subprocess, and the tests seem to continue without any problems.

Any explanations? It's making fixing the behave tests on develop rather tricky.

**Comment by benjaoming** [comment]
That sounds very odd, but the CTRL+C does suggest a subprocess or a thread.

Can you `ps ax | grep kalilte` and see which processes are running when the tests are stuck?

**Comment by benjaoming** [comment]
Also, on a supposedly unrelated note, my PR about process hasn't been merged, anyways ( #3917 )
