### ISSUE TITLE
I cannot find the assessment items package / How can I start KA Lite?

### ISSUE THREAD

**Issue by dogday** [learningequality/ka-lite#3948]
Hi everybody,

KA Lite worked perfectly until I restarted my macbook. After that I could not run http://127.0.0.1:8008/.

I launched terminal.
Here is what I have done:

===QUOTE===

MY NAME:~ MY NAME$ cd /Applications/KA\ Lite 
MY NAME:KA Lite ARS$ cd ka-lite
MY NAME:ka-lite ARS$ ./setup_mac.command
                                  
  _   __  ___    _     _ _        
 | | / / / _ \  | |   (_) |       
 | |/ / / /_\ \ | |    _| |_ ___  
 |    \ |  _  | | |   | | __/ _ \ 
 | |\  \| | | | | |___| | ||  __/ 
 \_| \_/\_| |_/ \_____/_|\__\___| 
                                  
http://kalite.learningequality.org
                                  
         version 0.13.2
                                  
--------------------------------------------------------------------------------
This script will configure the database and prepare it for use.
--------------------------------------------------------------------------------
Press [enter] to continue...
-------------------------------------------------------------------
WARNING: Database file already exists!
-------------------------------------------------------------------
Keep database file and upgrade to KA Lite version 0.13.2? (yes or no) no
Remove database file '/Applications/KA Lite/ka-lite/kalite/database/data.sqlite' now? (yes or no) no
Upgrading database to KA Lite version 0.13.2
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)

Synced:
 > kalite.topic_tools
 > django.contrib.sessions
 > kalite.contentload
 > django.contrib.staticfiles
 > south
 > django.contrib.auth
 > django.contrib.messages
 > django_extensions
 > kalite.testing.loadtesting
 > kalite.coachreports
 > kalite.control_panel
 > kalite.dynamic_assets
 > django.contrib.admin
 > django.contrib.contenttypes
 > kalite.distributed
 > kalite.basetests
 > kalite.testing

Not synced (use migrations):
 - kalite.facility
 - kalite.main
 - fle_utils.config
 - kalite.i18n
 - securesync
 - fle_utils.chronograph
 - kalite.updates
 - tastypie
 - kalite.playlist
 - kalite.student_testing
 - kalite.store
(use ./manage.py migrate to migrate these)
Running migrations for facility:
- Nothing to migrate.
 - Loading initial data for facility.
Installed 0 object(s) from 0 fixture(s)
Running migrations for main:
- Nothing to migrate.
 - Loading initial data for main.
Installed 0 object(s) from 0 fixture(s)
Running migrations for config:
- Nothing to migrate.
 - Loading initial data for config.
Installed 0 object(s) from 0 fixture(s)
Running migrations for i18n:
- Nothing to migrate.
 - Loading initial data for i18n.
Installed 0 object(s) from 0 fixture(s)
Running migrations for securesync:
- Nothing to migrate.
 - Loading initial data for securesync.
Installed 0 object(s) from 0 fixture(s)
Running migrations for chronograph:
- Nothing to migrate.
 - Loading initial data for chronograph.
Installed 0 object(s) from 0 fixture(s)
Running migrations for updates:
- Nothing to migrate.
 - Loading initial data for updates.
Installed 0 object(s) from 0 fixture(s)
Running migrations for tastypie:
- Nothing to migrate.
 - Loading initial data for tastypie.
Installed 0 object(s) from 0 fixture(s)
Running migrations for playlist:
- Nothing to migrate.
 - Loading initial data for playlist.
Installed 0 object(s) from 0 fixture(s)
Running migrations for student_testing:
- Nothing to migrate.
 - Loading initial data for student_testing.
Installed 0 object(s) from 0 fixture(s)
Running migrations for store:
- Nothing to migrate.
 - Loading initial data for store.
Installed 0 object(s) from 0 fixture(s)

Starting in version 0.13, you will need an assessment items package in order to access many of the available exercises.
If you have an internet connection, you can download the needed package. Warning: this may take a long time!
If you have already downloaded the assessment items package, you can specify the file in the next step.
Otherwise, we will download it from https://learningequality.org/downloads/ka-lite/0.13/content/assessment.zip.
Do you wish to download the assessment items package now? (yes or no) no
Have you already downloaded the assessment items package? (yes or no) yes
Please enter the filename of the assessment items package you have downloaded (): 

===END OF QUOTE===

Where is the assessment items package? What should I put there? I tried many variants, but nothing made http://127.0.0.1:8008/ work.

**Comment by dogday** [comment]
I did it!

I did:

cd /Applications/KA\ Lite 
cd ka-lite
./bin/kalite start

**Comment by rtibbles** [comment]
Great!
