### ISSUE TITLE
Coach Report charts not responsive on small displays

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#3967]
**Branch**: 0.14 

**Current Behavior**: Circlecharts start to overlap with devices smaller than 600px in width.

**Expected Behavior**: DIV's with class circlechart should overflow and stack in columns.

![responsivecoachreport](https://cloud.githubusercontent.com/assets/1457929/8475477/82291246-20b8-11e5-8ed7-729f5c810f5a.png)

Learner Progress Reports do stack correctly:

![responsiveprogressreport](https://cloud.githubusercontent.com/assets/1457929/8475728/5cbd94c6-20ba-11e5-89c7-fb3f4e3d9cbc.png)

**Steps to reproduce**:

1. Download & install the 0.14
2. Do some activities (view videos or do exercises) as learner.
3. View Coach reports as Admin/Coach

**Comment by rtibbles** [comment]
Fixed in #4454
