### ISSUE TITLE
BadZipfile: Bad magic number for central directory 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#3968]
**Branch**: 0.14 on Windows

**Current Behavior**: Error while unpacking the **assessment.zip** file downloaded with `kalite manage unpack_assessment_zip https://learningequality.org/downloads/ka-lite/0.14/content/assessment.zip -f`` command:

`BadZipfile: Bad magic number for central directory `

![assessment zip](https://cloud.githubusercontent.com/assets/1457929/8476141/9c01c61c-20be-11e5-91c7-6e841a93e1ae.png)

**Steps to reproduce**:

1. Download & install the 0.14
2. Run the `kalite manage unpack_assessment_zip https://learningequality.org/downloads/ka-lite/0.14/content/assessment.zip -f`` command from your ka-lite folder (C:\Program Files (x86)\KA Lite\ka-lite for me).

**Comment by radinamatic** [comment]
While installing on a second testing machine I realized that assessment.zip is now part of the 0.14 installer itself, so the procedure was not necessary. However, it might be useful to provide feedback to the user that the assessment items are already there... And of course, figure out the why of the "magic number" error :)

**Comment by aronasorman** [comment]
Interesting. So the bad magic number means either an incomplete download of the zip file, or that what we downloaded isn't a zip file in the first place.

**Comment by aronasorman** [comment]
Although yeah, you don't really need to run this command since it's supposed to be part of the windows installer.

**Comment by radinamatic** [comment]
Yeah, I realized that on another machine, but from the output above it seems that the download finished, and the unpacking was unsuccessful...

**Comment by MCGallaspy** [comment]
If you are using the windows installer, this is not a step you need to take.

**Comment by radinamatic** [comment]
Ok, closing.
