### ISSUE TITLE
Cancel downloading video not working.

### ISSUE THREAD

**Issue by amodia** [learningequality/ka-lite#3969]
**Branch:** `develop`
**Steps to reproduce:**

1. Log in as admin
1. Navigate to videos tab.
1. Download any video and click cancel button. 

![ka-lite-a](https://cloud.githubusercontent.com/assets/8663934/8477261/5135ac1a-20fb-11e5-8176-8a67bc67ba1b.gif)

**Comment by radinamatic** [comment]
I tried to replicate this on 0.14 on Windows 7, and it seems to be working on both FF and IE (from your screencast it seems you were using IE).

**Comment by rtibbles** [comment]
I am a little confused, as I see no indication that the video download is continuing in the animation shared here.

**Comment by MCGallaspy** [comment]
Looks like user error.
