### ISSUE TITLE
Pip dependemcies has failed to install

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#3970]
**Branch**: Updating 0.13 to 0.14 on Windows 7

**Current Behavior**: Error while installing 0.14 over 0.13 (fully functional with several coaches & learners & language packs):

Pip depende**m**cies **has** failed to install.

![pip-dependencies](https://cloud.githubusercontent.com/assets/1457929/8480917/c0fa0d9a-20e0-11e5-9d2b-bff43d5b0edf.png)

The installation continued after this error, but is probably why the 0.14 server was unable to start at the end. I had no issues with Pip this morning when I did a clean new install on another Win 7 machine.  

A part form figuring out the error itself, revise the English too... :)

**Steps to reproduce**:

1. Download & install the 0.14 on the machine with previous 0.13 installation of KA Lite

**Comment by MCGallaspy** [comment]
Please open issues with the Windows installer over here: https://github.com/learningequality/installers

The spelling error at least has been fixed in https://github.com/learningequality/installers/pull/73

**Comment by radinamatic** [comment]
Issue opened at https://github.com/learningequality/installers/issues/74, closing this one.
