### ISSUE TITLE
Provide an uninstall option for mac (and other OSes) kalite installer that cleans up environment variables

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#3971]
Improperly uninstall kalite on Mac (installed with kalite installer) can mess up KALITE_DIR environment var, and lead to server start failure.

Steps to reproduce the issue on Mac:
1. install kalite via kalite Mac installer
2. uninstall kalite (we currently don't have uninstall option, so you probably will just delete kalite)
3. get a fresh repo of current develop branch
4. run "python kalitectl.py start" or other command to start the server, you will get an error complains about "RuntimeError: KALITE_DIR environment var is invalid: "

notice: to solve this problem, you need to run "$unset KALITE_DIR" in your terminal

**Comment by benjaoming** [comment]
This should be opened in the installers repo.

>  4. run "python kalitectl.py start" or other command to start the server, you will get an error complains about "RuntimeError: KALITE_DIR environment var is invalid: "

This method of invoking `kalitectl.py` isn't recommended, have you tried running bin/kalite ?

I suspect the installer creates a permanent KALITE_DIR and doesn't unset it after installing, but please try not invoking kalitectl directly first.

**Comment by EdDixon** [comment]
@66eli77 Cyril had me leverage the launchctl command to unset those variables in his latest builds something like : sudo launchctl unload -w ~/Library/LaunchAgents/org.learningequality.kalite.plist
or : sudo launchctl unsetenv KALITE_PYTHON
may be required, although that may have changed?

**Comment by benjaoming** [comment]
The approach of setting a permanent be it KALITE_PYTHON or KALITE_DIR is good, though, because it ensures that users can run `kalite` independently from their own Terminal.

**Comment by aronasorman** [comment]
This should be present already right @cpauya? I believe there's a 'clear env vars' option already.

**Comment by cpauya** [comment]
Yes @aronasorman - we have a "Reset App" button on the Advanced tab of the Preferences dialog.

**Comment by aronasorman** [comment]
"Reset App" works well enough for the Mac.

**Comment by EdDixon** [comment]
However does not delete the ~./kalite folder which may be an issue in reinstalling or upgrading at a later point because having that folder prevents the current 0.14.0 from installing correctly.

**Comment by aronasorman** [comment]
@EdDixon we don't delete that in case they want to keep their data. Let's find issues as they come once @cpauya gets the mac installer building for develop.

**Comment by mctdog** [comment]
I've run into the problem exactly on my Mac.  I'm not a coder - just an end user.  Can anyone provide guidance on how to delete  the ~./kalite folder so I can get second install work?  When I load KA Lite Monitor it loads, but I'm unable to "Start" KA Lite.  I've tried every permutation of how to get it start, but KA Lite always stops and I can never open KA Lite in the browser.  Any guidance is GREATLY appreciated.  I have not data I'm worried about losing, I'd just love to do a complete clean install

**Comment by EdDixon** [comment]
Hi @mctdog first allow me to apologize for the typo on the path that likely created a problem for you deleting it it should be "~/.kalte" so my recommendation would be (provided you know for sure you do not need any of the data there) open a terminal and first "ls ~/.kalite" you should see several subfolders such as database etc. knowing that it now exists a " sudo rm -R ~/.kalite " will get rid of it and all subfolders and the data they contain. If you are certain all environment variables for KA Lite have been reset, you should be able to proceed with a clean installation at that point although a reboot never hurts. Good Luck! Changing the typo now!

**Comment by mctdog** [comment]
Thanks so much for your help.
