### ISSUE TITLE
KA-Lite superuser access creation is being denied to the installers 

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite#3973]
In all tests on every desktop OS supported (All  WIndows version, MAC, and Linux) after installation the user is taken to a "modal" super user creation page which is intended to be a fall back from the proper landing page which would be our typical login page. Having researched this extensively with the team I can really offer few clues. Screen Shot of the modal superuser page from the most recent WIndows 8 test but again, all desktop OS's affected by this same issue which is why I am issuing it against the ka-lite repo rather than installers it is common to all. Pinging @rtibbles @benjaoming HELP!
![2015-07-02_13-34-23](https://cloud.githubusercontent.com/assets/4349806/8486762/62e4e192-20c4-11e5-9773-db25cc744695.png)

**Comment by benjaoming** [comment]
I would like to draw attention to the fact that the landing page causes not only one view function to be called, but also several API views.

This in case, causes a number of modules to be initialized.

Cherrypy uses threads.

See where I'm going? :)

**Comment by rtibbles** [comment]
The issue as described does not suffer this problem, @benjaoming. @EdDixon can you clarify what the issue is here?

Either:
a) We should be creating the super user during setup rather than relying on the modal.
b) The issue we actually discussed in HipChat, whereby the first time the modal opens, and the content does not load, which *would* be explained by @benjaoming's explanation.

**Comment by benjaoming** [comment]
a) doesn't work, we have to provide a browser-based superuser creation. This is already integrated for Raspberry Pi and Debian UIs where `kalite manage setup` is not meant to be mandatory for the future.

**Comment by benjaoming** [comment]
@rtibbles what is the issue described? That KA Lite prompts for a superuser when there isn't one? Because that's expected behavior.

I thought we were continuing on the talks from Hipchat about the modal itself being broken?

**Comment by rtibbles** [comment]
That's what I thought too, @benjaoming which is why I was seeking clarification, because both the title and the screenshot do not indicate this.

**Comment by jamalex** [comment]
I agree that this is standard/expected behavior now, in general, so I think this may be more of a UX issue than anything else.

Perhaps we could add some "welcome" text, along the lines of "Thanks for installing KA Lite! Your first step now is to create an administrator account -- you'll use this later for creating coach accounts or administering the server."

One question here, though: does the Windows installer still ask the user to provide a username and password during the wizard process? Because if it's doing that, and then it still pops up this modal, that sounds like a bug.

**Comment by rkurata** [comment]
@jamalex yes, I'm using Windows and during installation, I was prompted to create an account, as well as after installation, when I opened it in a web browser.

**Comment by radinamatic** [comment]
Windows installer asks the user to provide admin username and password during the installation wizard process, but does not ask for the "Super User" in the login modal. There is the usual alert text to login with credentials used during the installation.

**Comment by MCGallaspy** [comment]
For the windows users here the expected behavior is this:
* User is prompted for admin credentials by the setup wizard.
* When user opens the app in the browser for the first time, they are _not_ prompted to create a super user.
* The user should be able to login with the credentials provided to the setup wizard.

It seems what's happening with @EdDixon and @rkurata is this:
* User is prompted for admin credentials during setup wizard.
* When the user opens the app in the browser for the first time, the user _is_ prompted to create a super user, with the dialog in the screenshot from the original post.

@radinamatic it sounds like you experienced the expected behavior?

**Comment by MCGallaspy** [comment]
Windows users, can you provide the version of windows that you experienced errors on? And, if you recall during the setup wizard, there is a step which says something like "Setup will now configure the database...". That step should take some time, and a very fast or immediate completion could indicate an error. Did you windows users also experience that?

**Comment by radinamatic** [comment]
What you described in the first case (expected behavior) is exactly what I experienced on 2 different Windows 7 machines @MCGallaspy.

**Comment by EdDixon** [comment]
All above being the case I would agree that it does sound like a race issue, as @benjaoming is suggesting I think regarding the multiple threads? @radinamatic for this to be the same version of the windows installer the /users/<yournamehere>/.kalite folder would have to exist which you said the other day it does not? This is where logging is done as well as several other important functions as I understand it. So I am I still not sure what to think? If the folder is still not there (again it is hidden) I don't think you are installing the same installer, we are testing and cannot reliably assume then that it is working for some but not all installations. @richard I have been trying to get that clarification about the modal system and how the "initial user " is to create their account for some time and have been repeatedly told no, it is still the same, that the modal was just a fall back should a database not exist at all, and that is an issue with each individual installer? However @benjaoming seems to be thinking this is going to have to be the default method (as labeled in the screenshot @radinamatic , I agree it is confusing having it go by two names) and I have commented a few times now, that it is more efficient but have been forced to assume this is an error based on what I was told and the redundancy of providing this information twice for the one admin/superuser account during the installation.

**Comment by EdDixon** [comment]
@MCGallaspy you're absolutely right about the database step just flashing by when I saw that happen on windows 8 during the install here I knew it was going to fail!

**Comment by radinamatic** [comment]
@EdDixon I can't check on the machine I was referring to the other day, since it's booted with Ubuntu ATM, but on another one with Windows 8 (believe it or not, I have 3 comps in front of me now), where I just installed KA Lite, there is indeed **/Users/Radina/.kalite** folder.

**Comment by EdDixon** [comment]
Cool good to know! I was concerned! Then yea I guess that is what is going on those pesky threads are not staying in step the way we need them too!

**Comment by arceduardvincent** [comment]
Hi @EdDixon I verified it on `Mac OS X yosemite`.

I installed the `OS X Installer` `ka-lite 0.14 Build #165`. 
After entering the admin credentials during setup wizard. I open the `KA-lite app` in the browser then I click `Login tab` and the `Login modal` dialog appear. The browser-based superuser creation modal did not appear.
 
See the image attach below.
![screenshot 2015-07-04 16 50 23](https://cloud.githubusercontent.com/assets/4099119/8507298/35d5674c-226f-11e5-8c9c-2221f3687155.png)

**Comment by EdDixon** [comment]
Hi Eduard,

That is good to hear!  It has been an issue on MAC for several weeks now,
and I can see you are in chrome as am I? There are others reports now such
as #3995, as well confirming my experience with the installer. However that
build #165, I have not tested prior to this report so I will see what
outcome I get now!

Thanks,

Ed Dixon
Corrections Adviser
Foundation for Learning Equality <http://learningequality.org/>
Give to FLE, Support FLE via Amazon Smile!
<https://learningequality.org/donate/>
M (575)-636-9549

**Comment by 66eli77** [comment]
here is how to reliably reproduce the superuser modal 403 issue:
1. start kalite server
2. on Chrome, open Settings, click "show advanced settings..."
3. under "Privacy", click "Clear browsing data..."
4. make sure "Cookies and other site and plug-in data" is checked
5. click "Clear browsing data..."
6. refresh kalite homepage, you will see this issue.

**Comment by rtibbles** [comment]
Good to know, @66eli77. Could also just use an Incognito window then to reproduce it.
