### ISSUE TITLE
Remove settings.PROJECT_PATH

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#3974]
This setting causes user data to be accessed or generated in application directories and application data to be mis-managed.

Ideally, this is replaced by individual settings.

For instance, this:

```
all_playlists = json.load(open(os.path.join(settings.PROJECT_PATH, 'playlist/playlists.json')))
```

Should be:

```
all_playlists = json.load(open(settings.PLAYLIST_PATH))
```

_Or_ by accessing files as package data:

```
from pkg_resources import resource_filename
all_playlists = resource_filename("playlist", "data/playlists.json")
```

Overview of problem:

```
✗ ack-grep --python PROJECT_PATH kalite

kalite/playlist/management/commands/checkplaylistentries.py
22:        all_playlists = json.load(open(os.path.join(settings.PROJECT_PATH, 'playlist/playlists.json')))

kalite/basetests/tests.py
6:PROJECT_PATH = os.path.realpath(os.path.join(THIS_PATH, "..", ".."))
11:        os.path.join(PROJECT_PATH),
12:        os.path.join(PROJECT_PATH, "kalite"),
13:        os.path.join(PROJECT_PATH, "python-packages"),
315:        content_path = os.path.realpath(os.path.join(PROJECT_PATH, "content"))
320:        khan_path = os.path.realpath(os.path.join(PROJECT_PATH, "data", "khan"))
325:        khan_path = os.path.realpath(os.path.join(PROJECT_PATH, "data", "khan"))
351:        scripts_path = os.path.realpath(os.path.join(PROJECT_PATH, "scripts"))

kalite/distributed/management/commands/apacheconfig.py
34:            "project_path": settings.PROJECT_PATH,

kalite/distributed/management/commands/nginxconfig.py
76:        self.stdout.write(config_template % {"root_path": os.path.realpath(settings.PROJECT_PATH + "/../"),

kalite/distributed/management/commands/setup.py
357:        # call_command("clean_pyc", interactive=False, verbosity=options.get("verbosity"), path=os.path.join(settings.PROJECT_PATH, ".."))
462:                        os.path.join(settings.PROJECT_PATH, "..", "bin", kalite_executable))
465:                        os.path.join(settings.PROJECT_PATH, "..", "bin", "windows", "kalite.bat"))

kalite/distributed/management/commands/screenshots.py
184:            self.output_path = os.path.join( os.path.realpath(os.path.join(settings.PROJECT_PATH, '..')),

kalite/distributed/management/commands/initdconfig.py
84:            executable_path = os.path.abspath(os.path.join(settings.PROJECT_PATH, "..", "bin", "kalite"))
85:            cwd = settings.PROJECT_PATH

kalite/settings/base.py
119:    # BEING DEPRECATED, PLEASE DO NOT USE PROJECT_PATH!
120:    PROJECT_PATH = os.path.realpath(
123:            "PROJECT_PATH",
131:    # BEING DEPRECATED, PLEASE DO NOT USE PROJECT_PATH!
132:    PROJECT_PATH = os.environ.get(
```

**Comment by iCHAIT** [comment]
@benjaoming Can I try this? If this has not already been fixed?

**Comment by benjaoming** [comment]
Absolutely! :)

Just a quick elaboration on this:

>     all_playlists = json.load(open(settings.PLAYLIST_PATH))

It should actually be `settings` from the app (sub-package) and not the django project's settings. I'm not sure if this json file is even relevant anymore, though. A lot of the JSON data is being removed because of the newly introduced content packs (see: #4807 )

Regarding settings patterns, please refer to #4054 for a brief explanation of what it means to have settings contained in an app (sub-package of KA Lite) and only using the project's settings for changing defaults.

But please feel free to ask questions from within a PR, it's easier to explain stuff looking at the code.

**Comment by iCHAIT** [comment]
@benjaoming Okay. I have a question - 

Where does these content packs lie? I mean we now need to specify the paths for these content packs instead of the earlier used json data, right?

**Comment by benjaoming** [comment]
@iCHAIT let's put this for 0.17, then we can decide later if we can backport it. AFAIK all the json data stuff is going to leave the codebase for 0.17.

The contentpacks are provided from an online source, however the English Khan Academy content pack will be a default part of the distribution.

Just skimming through the original search, it seems that very few occurrences are still relevant. So this might be a freebie :) You could possibly start your work by merging @rtibbles 's work in #4807 and merging it into `develop`..

**Comment by benjaoming** [comment]
This was removed in #5429
