### ISSUE TITLE
MAC Installer

### ISSUE THREAD

**Issue by whitzhu** [learningequality/ka-lite#3979]
After dragging KA Lite to the application folder and it finished transfering, a login screen for admin account and password was loaded. I set up a user name and password and click the button to proceed forward and this error code came up. Then KA - Lite crashed.

![screen shot 2015-07-02 at 2 21 05 pm](https://cloud.githubusercontent.com/assets/12800136/8488476/af0ff54a-20c7-11e5-9ecd-f1e49b011eb6.png)

"Either the set environment variables or symlink of kalite failed to complete! Please check the Console."

**Comment by aronasorman** [comment]
Should be fixed now.
