### ISSUE TITLE
progress bar for lessons

### ISSUE THREAD

**Issue by rkurata** [learningequality/ka-lite#3986]
![image](https://cloud.githubusercontent.com/assets/10429889/8488734/d3861042-20c9-11e5-83cf-98da900a0754.png)

I was testing out one of the lessons and because of the blue message at the top, I was expecting to do about 10 problems, but it seems more like the questions never end. I think if there were a progress bar at the bottom to indicate how many problems the user has completed and how many total problems there are, that could be helpful

**Comment by rtibbles** [comment]
Seems like we should suppress this message for admins - for admins the lesson never ends!

**Comment by rtibbles** [comment]
Solution for this is to prompt admins and teachers differently, so that they know they can never make any progress (for now).
