### ISSUE TITLE
"No recent learner data for this group available" and yet many hours have been logged

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#3987]
Branch: 0.14.x
Platform: Ubuntu
Installer: Deb

Expected Behaviour: If there is no recent learner data, then there should not be any data displayed in the landing page.

Current Behaviour: A huge number of logged hours is reported despite there being no recent learner data.

![image](https://cloud.githubusercontent.com/assets/1680573/8488760/23a8b1f6-20ca-11e5-82fd-4d3b92a3d6b4.png)

In addition, for a group for which there is data, the total hours is reported as 0:

![image](https://cloud.githubusercontent.com/assets/1680573/8488765/3705eeb2-20ca-11e5-9cbf-5ecefadfd701.png)

**Comment by MCGallaspy** [comment]
So this was due to an omission in `generaterealdata`?

**Comment by rtibbles** [comment]
Not only, but also. The userlogs were also being filtered on invalid
fields.
