### ISSUE TITLE
For Mac OS, Video Downloading Issue

### ISSUE THREAD

**Issue by JohnJCZhou** [learningequality/ka-lite#3990]
After selected videos and clicking on download, it will take really long to process, even if the notification bar shows: "Launched video download process successfully." , it is said to take longer than 10 mins.

**Comment by aronasorman** [comment]
@cpauya can you look into this? I think we should just show a warning right now for Mac users to wait a while for video download to start.

**Comment by cpauya** [comment]
Hi @JohnJCZhou - how did you setup ka-lite and can you please specify your: Mac OS version and browser used?  I'm assuming you used the OSX installer for this and may I also know what build number?

While waiting for the OSX .dmg download, I did the following for a quick check:
1. `pip install ka-lite` inside a virtualenv on my OSX 10.10.3 Yosemite  (I have `ka-lite 0.14.alpha2`)
1. go to http://192.168.2.101:8008/ on Chrome 43.0.2357.130 browser
1. download a video - it downloaded right-away after I clicked on the `Download` button.

I am still downloading the OSX installer and will try that next.

**Comment by cpauya** [comment]
@JohnJCZhou I am not sure if the video download finished after the 10 minutes window that you mentioned.

Here's the same issue reported earlier: #3704 - so I will close this as duplicate.

**Comment by cpauya** [comment]
I'm reopening this with the TODO: "Show a warning to wait for the video download to start." assigning it to @amodia.

**Comment by djallado** [comment]
Downloading video will not start immediately. 

**Steps to reproduce:**

1. Log in as `admin`
2. Click on `Video` tab
3. Click on any video you want to download.

Observe that downloading will not start immediately after clicking `Download selected video` button.
The download progress bar will appear after `5` seconds:
![screen shot 2015-07-22 at 5 46 41 pm](https://cloud.githubusercontent.com/assets/8664071/8824012/695d640a-30a4-11e5-824b-eb7c65a170d6.png)

 Download will start after `25` seconds after clicking the `Download selected video` button:
![screen shot 2015-07-22 at 5 49 08 pm](https://cloud.githubusercontent.com/assets/8664071/8824050/c1fd9030-30a4-11e5-9520-1156685906eb.png)

**Comment by aronasorman** [comment]
Should be fixed now.
