### ISSUE TITLE
For Mac OS, Coach Reports Doesn't show up

### ISSUE THREAD

**Issue by JohnJCZhou** [learningequality/ka-lite#3994]
I created two facilities, F1 and F2. And I created new coach in F2. I had student login into F1 and take couple of quizzes and exercises. Then I login with coach in F2. I assume I could see reports of F1 from this coach in F2, but there is no information showing up.

**Comment by aronasorman** [comment]
screenshots @JohnJCZhou?

**Comment by rtibbles** [comment]
More information needed to replicate. Screenshots would help.

**Comment by rtibbles** [comment]
Not been able to replicate. Closing.
