### ISSUE TITLE
"Create Super User"???

### ISSUE THREAD

**Issue by aleeshanderson** [learningequality/ka-lite#3995]
Branch: 0.14
Date: 7/2/15
Build Affected: OSX
Expected behavior: not quite sure
Actual behavior: user is prompted to "Create Super User" The pop-up does not allow you to access the site or interact with it in anyway.

Steps to reproduce: Open KA Lite in Browser(chrome) after a fresh install

![screen shot 2015-07-02 at 3 59 06 pm](https://cloud.githubusercontent.com/assets/12928107/8489713/968416f8-20d3-11e5-9702-a065d0cdc8b0.png)
![screen shot 2015-07-02 at 3 59 21 pm](https://cloud.githubusercontent.com/assets/12928107/8489717/9d3264c8-20d3-11e5-80e3-e1e5a81d6f6c.png)

**Comment by aleeshanderson** [comment]
* I closed KA-Lite and re opened it again, and it seems to be working properly the second time.

**Comment by 66eli77** [comment]
@aleeshanderson  great finding, so this issue happens on macbook too. confirmed that it's a cross platform issue

**Comment by radinamatic** [comment]
Confirmed on Ubuntu too, correct modal appears after re-loading the page.

**Comment by aronasorman** [comment]
Quite urgent. We don't want the user to be blocked from interacting with the site.

**Comment by 66eli77** [comment]
@aronasorman I'm working on it

**Comment by 66eli77** [comment]
here is how to reliably reproduce this issue:
1. start kalite server
2. on Chrome, open Settings, click "show advanced settings..."
3. under "Privacy", click "Clear browsing data..."
4. make sure "Cookies and other site and plug-in data" is checked
5. click "Clear browsing data..."
6. refresh kalite homepage, you will see this issue.
