### ISSUE TITLE
For Mac OS, Coach account accessability

### ISSUE THREAD

**Issue by JohnJCZhou** [learningequality/ka-lite#3996]
Based on the document:

Who is a “coach”?
A person who :
adds, manages, and tracks the progress of groups of students.
has access to student progress data in the form of coach reports
provides instructions to students

but it looks like the coach have more access to the database than that: it can add coach, add facilities, and download videos and language packs.

So may be good to add more detailed descriptions to the definition of "coach".

**Comment by aronasorman** [comment]
Maybe a section in the user manual explaining this @MCGallaspy @jamalex @rtibbles?
