### ISSUE TITLE
minor UI suggestion

### ISSUE THREAD

**Issue by aleeshanderson** [learningequality/ka-lite#3997]
As someone opening this program for the first time, I was confused by why some of the modules at the end were grayed out. I assumed that it was uninstalled programs or something of the nature, but then I was unsure about where to get these files and whether I needed them, and if something was wrong. 

![screen shot 2015-07-02 at 4 07 11 pm](https://cloud.githubusercontent.com/assets/12928107/8489816/949cfd90-20d4-11e5-8fbf-c1924e9045df.png)

**Comment by aronasorman** [comment]
Clicking those links would show a notification that you need to download the corresponding video. However it would be nice to have a warning beforehand of why those items are grayed out.

**Comment by rtibbles** [comment]
This would require user interface text for a warning.

Past string freeze, so let's punt this.

**Comment by rtibbles** [comment]
We should just hide unavailable content.

**Comment by rtibbles** [comment]
Fixed in #4824
