### ISSUE TITLE
For Mac OS, exercises pages not Scrollable conditionally

### ISSUE THREAD

**Issue by JohnJCZhou** [learningequality/ka-lite#3999]
Scrolling doesn't works occasionally, but the scrollbar on the right side is functional; sometimes when not logged in, it would not work; sometimes when the exercise question is too long, it would not work. When logged in on the exercise page, it wouldn't work; when refresh, it will work again. Also, when open up the course categories, scroll the list and close to go back to the page, it will work again.

**Comment by benjaoming** [comment]
Which browser were you using?

**Comment by JohnJCZhou** [comment]
I was using chrome.

**Comment by benjaoming** [comment]
Cool, thanks for clarifying. It's probably worth investigating if Chrome on other platforms does the same...

**Comment by rtibbles** [comment]
Not going to happen within the scope of KA Lite.
