### ISSUE TITLE
For Mac OS, some resized UI is off position

### ISSUE THREAD

**Issue by JohnJCZhou** [learningequality/ka-lite#4000]
When resized the page with magnifier UI will be off position. This is more obvious with reducing size like the navigation tags will have a gap between the horizontal navigation bar.

**Comment by aronasorman** [comment]
@JohnJCZhou screenshots?

**Comment by JohnJCZhou** [comment]
Sorry, not available right now, I will be able to look into the issues later today, across the boarder in TJ.

**Comment by JohnJCZhou** [comment]
Reduced size
![welcome ka lite](https://cloud.githubusercontent.com/assets/9564925/8506899/3f5311fa-21e0-11e5-96ce-2fab49fad40c.png)
Normal size
![welcome ka litex](https://cloud.githubusercontent.com/assets/9564925/8506900/3f6c723a-21e0-11e5-8bdd-e74f1cf6bbae.png)

**Comment by rtibbles** [comment]
Perhaps my eye is not keen enough to pick it up, but I am not seeing the issue here.

**Comment by rtibbles** [comment]
Not going to happen within the scope of KA Lite.
