### ISSUE TITLE
Some exercise questions' options are on the right side

### ISSUE THREAD

**Issue by JohnJCZhou** [learningequality/ka-lite#4002]
Some exercise questions' options are on the right side (For example, Jade Cong (AP) Exercise), which is not consistent with the rest of the exercises.

**Comment by aronasorman** [comment]
@JohnJCZhou screenshots?

**Comment by JohnJCZhou** [comment]
Normally the layout is like this:
![learn sat math level 1 quiz 1 ka lite](https://cloud.githubusercontent.com/assets/9564925/8506921/ef44b460-21e0-11e5-93ec-90a620beb574.png)
For some of the quizzes it is like this:
![learn jade cong ap ka lite](https://cloud.githubusercontent.com/assets/9564925/8506922/ef4955b0-21e0-11e5-889e-01c7d4f8548c.png)
This is more of a UX issue than functionality issue.

**Comment by rtibbles** [comment]
This is internal to Khan Academy's encoding, not much we can do.
