### ISSUE TITLE
[Errno 13] Permission denied: '/usr/lib/python2.7/dist-packages/kalite/i18n/static/js/i18n/en.js'

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4003]
**Branch**: 0.14 on Ubuntu

**Current Behavior**: Error while installing trying to update English language pack:

`Error during update: Error: [Errno 13] Permission denied: '/usr/lib/python2.7/dist-packages/kalite/i18n/static/js/i18n/en.js'`

![update languages ka lite](https://cloud.githubusercontent.com/assets/1457929/8490587/b88f3c34-212b-11e5-9bd2-2c2b5bf734ec.png)

**Steps to reproduce**:

1. Login as Admin
2. Try to update English language pack

**Comment by radinamatic** [comment]
The same error appeared when I tried to install the Spanish language pack. Seems as if the packs are downloaded, though...

**Comment by benjaoming** [comment]
Grrr, that used to work on the .deb

**Comment by radinamatic** [comment]
Sorry, @benjaoming  I have a new one for you after the latest update to alpha2:

`[Errno 13] Permission denied: '/usr/lib/python2.7/dist-packages/kalite/i18n/data/dubbed_video_mappings.json'`  


![update languages ka lite2](https://cloud.githubusercontent.com/assets/1457929/8502255/e04c5838-21ad-11e5-918a-d8c071ef3f8b.png)

Same as yesterday, the update itself seems to finish fine (see the 'Up to Date' status), it just throws these errors at the end.  

Do you think it's the same problem, or should I open a separate issue?

**Comment by benjaoming** [comment]
this is definitely an error, I will look at it, no need to test it further before there's a patch... thanks!

**Comment by benjaoming** [comment]
There are two different issues at play here, but they both revolve around that the language packs are  mis-designed, something that was missed initially when moving the language data to user directories.. we only created ~/.kalite/locale

We need two new user-writable locations:

1. A general user-writable static_dir that will be picked up by `collectstatic`. This will address the write-error on `/usr/lib/python2.7/dist-packages/kalite/i18n/static/js/i18n/en.js`.
1. We have start copying out the json sources that are modified when new language packs are added and read them from a user-location. This will address the latter write error on dubbed_video_mappings.json

This will also prevent future updates from over-writing user-downloaded language packs.

**Comment by benjaoming** [comment]
@radinamatic this is fixed now and released in alpha7

It might actually make #4037 -- could you verify that? AFAIK there is actually a call to collectstatic implemented in the management script languagepackdownload

**Comment by benjaoming** [comment]
Confirming that this works on a .deb

**Comment by radinamatic** [comment]
Good news, this is no longer appearing on alpha7, updated English & Spanish languages packs with no issues! :+1:
