### ISSUE TITLE
"DatabaseError: database is locked" after Ubuntu install with old KA Lite user data dir

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#4006]
Version: Debian installer, 0.14.alpha2-0ubuntu1 (but with data from previous runs in `~/.kalite`)

Note: this issue goes away if I rename my `~/.kalite` directory, so it's something to do with the old stuff in there.

Steps to replicate:
- use my `.kalite` dir (will look into which pieces matter most; probably the DB and lockfile)
- `kalite start`
- try to load in browser
- it hangs for a long, long time (4 mins?)
- eventually it loads this error page:

![image](https://cloud.githubusercontent.com/assets/618416/8491394/883346fa-20ec-11e5-98da-b0a9f68fe862.png)

    <h1>Error</h1>

    <p><b>Sorry, but there was an error while trying to load the page.</b></p>

    (DatabaseError: database is locked)

**Comment by radinamatic** [comment]
I got exact same error after updating to 0.14.alpha2 (described in https://github.com/learningequality/installers/issues/82).

**Comment by jamalex** [comment]
Hmm, info gleaned so far:
- It's not the locale directory renaming it doesn't prevent the problem)
- It only happens when running in daemon mode. With `--foreground` everything runs smoothly.

Still digging...

**Comment by jamalex** [comment]
Seems to happen after the cronserver_blocking thing crashed (so maybe the cron process is locking the DB) -- @benjaoming's new fix may address this?

**Comment by benjaoming** [comment]
This is plausible! It could well be that unclean termination of threads are causing the database to be left in a locked state.

**Comment by aronasorman** [comment]
Don't get this error anymore. Closing.
