### ISSUE TITLE
Overlapping alert error during downloading language packs.

### ISSUE THREAD

**Issue by amodia** [learningequality/ka-lite#4008]
**Branch:** 0.14.x

Steps to reproduce:

1. Log in as admin user.
2. Navigate to language tab.
3. Download `danish` language.

![ka-lite-a](https://cloud.githubusercontent.com/assets/8663934/8495399/fa9c26fe-219f-11e5-8a6a-0c872a240a5f.gif)

**Comment by radinamatic** [comment]
I haven't been able to reproduce this on 0.14 on Windows 7. Danish & Spanish language packs downloaded correctly.

**Comment by aronasorman** [comment]
@radinamatic @amodia DEBUG=False right?

**Comment by radinamatic** [comment]
If this is on KA Lite installation with the installer for the end user, we don't have to set DEBUG, right?

**Comment by aronasorman** [comment]
Can't reproduce this anymore on the latest 0.14.

**Comment by radinamatic** [comment]
I've never seen this issue on my installations.
