### ISSUE TITLE
Videos in Firefox are not responsive on manual window resize 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4009]
**Branch**: 0.14 installer
Firefox 38 on Windows 7

**Expected behavior**: Videos should resize according to available window size.

**Actual behavior**: The issue seems to be affecting only the manual (bit-by-bit) window width resize in FF (Chrome and IE work as expected), because if I use Developer Tools "Responsive Design View", video is correctly resized according to available display sizes. It seems to happen around 700px width when FF stops resizing the video, and the hamburger menu also becomes unavailable:

![ff-cuts-video](https://cloud.githubusercontent.com/assets/1457929/8498481/6d05f094-2187-11e5-90fa-3aa11f8f1c94.png)

IE window of the same width:

![ieresponsive](https://cloud.githubusercontent.com/assets/1457929/8498484/78f2aece-2187-11e5-9aef-4fb41b36827c.png)

Chrome window of the same width:

![chromeresponsive](https://cloud.githubusercontent.com/assets/1457929/8498491/8ff39b1a-2187-11e5-8a2e-0909f140b44c.png)

**Steps to reproduce**:

1. Open any video page on FF
2. Grab left or right edge of the FF window and start resizing until the video inside stops resizing.

**Comment by radinamatic** [comment]
Retested on 0.14 started from local repo (not installed), and it works fine for Firefox 38 on Windows XP. I will try on Win8 latter.

**Comment by aronasorman** [comment]
0.15. It's resizing correctly on tablets I have tested it with, so it's not too urgent for me.

**Comment by radinamatic** [comment]
I agree, I haven't been able to replicate this yet too, so it may just be a quirk.

**Comment by aronasorman** [comment]
Works on firefox 40.
