### ISSUE TITLE
Unclear Search result categories

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4010]
**Branch**: 0.14 installer

**Actual behavior**: Search query separates results into **Topics**, **Content** and **Exercise**. I find the term **Content** to be questionable because it is generic (topics and exercises are content too), and because those links actually lead to **Videos**.

![search-categories](https://cloud.githubusercontent.com/assets/1457929/8498710/48a43f78-218a-11e5-9da0-21e414c27842.png)

**Expected behavior**: Rename **Content** to **Videos**? 

**Steps to reproduce**:

1. Use the Search box and observe the result categories

**Comment by aronasorman** [comment]
I think the naming scheme was a way of looking forward for when we can serve more than just videos (which we can already do, actually!). However I agree that we may be renaming our interface too early when we haven't released the feature yet.

**Comment by jtamiace** [comment]
I agree. The fix that I will make then is to change it back to videos for now then and keep this in mind for when the change to different types of content actually happens.

**Comment by radinamatic** [comment]
:+1: 

Including other types of content will most probably require some rearranging of the way they are presented in the page, so that sounds like a good moment to include names for specific content types.

**Comment by rtibbles** [comment]
Note: This will happen automatically in 0.16.

**Comment by rtibbles** [comment]
Punting to 0.16.

**Comment by radinamatic** [comment]
Fix confirmed on latest installers, closing!
