### ISSUE TITLE
Create the 'New issue' template

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4022]
Reading the conversation between @aronasorman and @rtibbles on HipChat regarding the formatting of the issues filed during the bug bash, leads to conclusion that people rarely read the [guidelines for contributing](https://github.com/learningequality/ka-lite/blob/master/CONTRIBUTING.md) in CONTRIBUTING.md. 

Could we make an automatic template for it? I have my own, which is a plain text file with:  

```
**Branch**: develop  


**Expected Behavior**: 


**Current Behavior**: 

(add screenshots if necessary to better illustrate the issue)

**Steps to reproduce**:

1. Log in as...
2. 
3.
4.
```

But I still have to open it, and c/p the content in the GH Issue field each time. 

Something like this, maybe? 

https://github.com/learningequality/ka-lite/issues/new?body=**Branch**:%0A%0A**Expected%20Behavior**:%0A%0A**Current%20Behavior**:%0A%0A**Steps%20to%20reproduce**:%0A%0A1.%20Log%20in%20as%20the%20administrator.%0A2.%0A3.%0A4.

I did a little research and found this: http://issuetemplate.com/#/new-template. I even tried to make a template for **learningequality**, but it complained saying that I am not **collaborator** and that I couldn't save the template... :(  
  
Folks at [GitLabs](https://gitlab.com/gitlab-org/gitlab-ce/issues/1378) are thinking of implementing something similar, but until they do, maybe we can make our own?

**Comment by radinamatic** [comment]
An now I can't remember what was the issue I actually wanted to file before I came with this proposal... :P

**Comment by benjaoming** [comment]
It would be great to have more precise issues! I think the best thing to add would be some overall debugging steps:

Read your log, try running with `kalite start --foreground`, switch DEBUG mode on etc.

But in general, the most common failure is that people simple don't read the contribution docs because they're too busy :D

**Comment by radinamatic** [comment]
I agree and understand about being "busy"... :)

The point is that the template should actually save time and offer proper indication of what a good issue and/or feature proposal should contain.

**Comment by benjaoming** [comment]
Yup, maybe adding tips for debugging right after the template would work?

**Comment by radinamatic** [comment]
If I understand correctly, https://github.com/kentcdodds/issue-template should allow you to make different templates: new issue with debugging tips, new issue for installers with fields for OS, new feature...

**Comment by benjaoming** [comment]
It's been done a while ago!
