### ISSUE TITLE
The --git-migrate setup option is not working

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#4024]
Installed: ka-lite-source - 0.14.alpha2-0ubuntu1

Tried to follow the [release note instructions](http://field.learningequality.org/develop/docs/installguide/release_notes.html#id1) for importing stuff from an old Git-based installation. It didn't seem to do anything (it just created a new database from scratch as usual, and didn't give any indication of importing anything from the old install).

    jamalex@hummingbird:~$ kalite manage setup --git-migrate /home/jamalex/fle/ka-lite
                                      
      _   __  ___    _     _ _        
     | | / / / _ \  | |   (_) |       
     | |/ / / /_\ \ | |    _| |_ ___  
     |    \ |  _  | | |   | | __/ _ \ 
     | |\  \| | | | | |___| | ||  __/ 
     \_| \_/\_| |_/ \_____/_|\__\___| 
                                      
    http://kalite.learningequality.org
                                      
             version 0.14.alpha2
                                      
    WARNING:root:It's recommended that you install Python version 2.7.9. Your version is: sys.version_info(major=2, minor=7, micro=6, releaselevel='final', serial=0)

    --------------------------------------------------------------------------------
    This script will configure the database and prepare it for use.
    --------------------------------------------------------------------------------
    Press [enter] to continue...
    Please choose a username and password for the admin account on this device.
      You must remember this login information, as you will need
      to enter it to administer this installation of KA Lite.
    Username (leave blank to use 'jamalex'): 
    ...

(Removing UX note from here, as that was meant for #4025)

**Comment by jamalex** [comment]
Note: I'm in the process of rewriting `gitmigrate` -- so nobody take this one just now, please.

**Comment by jamalex** [comment]
Fixed in #4026.

**Comment by benjaoming** [comment]
@jamalex I moved the issue of `--option value` to #4039, thinking that this was indeed the problem you were experiencing as I could reliably see that options with a dash '-' were not blocked.

**Comment by benjaoming** [comment]
Suggesting to close as a blocker for 0.14?
