### ISSUE TITLE
Missing instructions for server restart after adding languagepack

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4034]
As seen in  #4027, it's pretty costly that we're missing an instruction for server restart.

Could someone figure out a nice and visible place for such a message?

**Comment by aronasorman** [comment]
0.15.

**Comment by rtibbles** [comment]
This is fixed in this line:
https://github.com/learningequality/ka-lite/blob/develop/kalite/updates/static/js/updates/bundle_modules/update_languages.js#L293
