### ISSUE TITLE
Downloading language pack is not working.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/ka-lite#4035]
From [dungeon](http://dungeon.learningequality.org:8085/browse/KL-KALITE014-168) build `#168` osx installer.

I have this `DatabaseError: no such table: chronograph_job` on the server log. When I try to download language pack.
![screen shot 2015-07-06 at 5 27 28 pm](https://cloud.githubusercontent.com/assets/8663934/8519309/60f7cba4-2404-11e5-8e34-48cf7e56c6d1.png)

Steps to reproduce:
1. Install the osx installer build `#168` from  [dungeon](http://dungeon.learningequality.org:8085/browse/KL-KALITE014-168).
2. Log in as admin.
3. Navigate to language tab.
4. Download any language.

![screen shot 2015-07-06 at 4 31 37 pm](https://cloud.githubusercontent.com/assets/8663934/8519510/bb5fc1cc-2405-11e5-98ad-f0547fed8921.png)

**Comment by aronasorman** [comment]
@amodia looks like the migration didn't work. Can you find out what database is being read by the server, and see if it has the necessary tables?
