### ISSUE TITLE
Get docopt to understand "kalite manage django_command --option value" with spaces instead of '='

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4039]
Problem:

    ✗ bin/kalite manage command --option value
    Please only use --option=value patterns. The option parser gets confused if you do otherwise.

Expected:

Command runs.

Instead of messing around with a parser that detects "--option value" and then fails and even fails to fail (see #4036), we should have a parser that understands "--option value" and not only "--option=value".

**Comment by jamalex** [comment]
I started describing some of these in a new issue, because I couldn't find this one. Putting the notes relevant to this one here instead (also, renamed this one to include keywords I was looking for when searching for the issue):

- Long-form options need to be separate from their values by `=`, not a space (e.g. `--path=/a/b/c` not `--path /a/b/c`)
- Short-form options cannot have spaces between the option letter and the argument (e.g. `-v3` not `-v 3`)

**Comment by MCGallaspy** [comment]
Look, it seems like the original motivation for dropping in our own modified version of `docopt` comes from #3827. Hindsight is 20/20, but I think it's safe to say this has crept beyond the initial motivation of being a quick fix and instead is becoming one more weird thing to maintain. Before we go down this rabbit hole any further, I suggest we revert to using "plain" docopt and live with whatever constraints it imposes.

**Comment by benjaoming** [comment]
@MCGallaspy agreed that it sucks to do get our hands dirty with command line parsing.. that's what docopt was for.. the goal is to make this layer as thin as possible. But I don't have any idea about make the layer thinner without modifying the command line API, which I think should be a no-go.. which makes the docopt constraints a bit hard to live with, unless there is a way that we've overlooked.

**Comment by MCGallaspy** [comment]
> agreed that it sucks to do get our hands dirty with command line parsing

I would say that it more than sucks. Modifying 3rd party libraries is classically forbidden. Now we're maintaining that code in addition to our own. We've already spent a lot of time debugging unrelated issues when command-line argument parsing changed because of our modifications. It's impossible to say with certainty how much more dev time we will spend on that and the fallout from it, so I say we do indeed live with modifying the `kalite` command line API, hard though it may be. It will be a pain now to revert it (but hopefully not too much), but I think it will be substantially more painful down the line not to.

**Comment by MCGallaspy** [comment]
To be clear, I'm suggesting we revert it in 0.15.

**Comment by benjaoming** [comment]
@MCGallaspy we haven't modified docopt, just had to make a work-around, we're still calling a vanilla docopt listed in requirements.txt

**Comment by MCGallaspy** [comment]
Uh... are we not overwriting the `docopt.docopt` function?

**Comment by benjaoming** [comment]
No, we added our own based on that one to access "left" and "collected": It's a step up from modifying dependencies or monkey patching them :)

**Comment by benjaoming** [comment]
I opened the PR on docopt so we wouldn't have to do that part at least.

**Comment by MCGallaspy** [comment]
I think this is a matter of semantics here... adding our own is effectively the same as modifying the library. I'm saying I think it's harmful, especially given that we never had such trouble parsing django options before. I dunno how to say it any more clearly, we've already spent a lot of time on this and it's not clear how much more time it will take in the future.

**Comment by benjaoming** [comment]
Reverting it and breaking the command line API is a very strange solution. The command line API is first priority IMO. If there is a way to use docopt *as is* then let's do that... but I never found that, so instead of making a very long and cluttered description of our command line options and their order, I went with a work-around for doctopt and an upstream PR to mend some of it.

The fact that it has caused issues and extra work for 0.14 is as doubtless as it's a fact... that it will continue to do so is more doubtful.

**Comment by MCGallaspy** [comment]
Still an issue on `0.15.x`. I tried the following command: `python bin\kalite manage contentload --import -dD:\ka-lite\import_test\`. The argument gets parsed as `-dD:\ka-lite\import_test\`. Same with the long-form version, it gets parsed as `-data=D:\ka-lite\import_test\`.

Both `-d D:\ka-lite\import_test\` and `--data D:\ka-lite\import_test\` are errors.

**Comment by MCGallaspy** [comment]
I'm going to create a set of test cases for this.

**Comment by MCGallaspy** [comment]
Update about the above `--import` requires an argument, and it's value is being set to `-dD:\ka-lite\import_test\`... however, I would expect it to fail, given that there is whitespace.

**Comment by MCGallaspy** [comment]
So it seems that some combinations of arguments actually foil correct parsing, but not all.

**Comment by jamalex** [comment]
> So it seems that some combinations of arguments actually foil correct parsing, but not all.

This sounds accurate. It's like an easter egg hunt!

**Comment by jamalex** [comment]
I'm putting this back to 0.15 milestone for now, just to remind us to remove the "Will be fixed for next version 0.15" message, if we're not going to fix it for 0.15.

    [root@chip .kalite]# kalite start --port 7007
    Please only use --option=value or -x123 patterns. No spaces allowed between option and value. The option parser gets confused if you do otherwise.
    Will be fixed for next version 0.15

**Comment by aronasorman** [comment]
Installers are finalized. Punting to 0.16.

**Comment by MCGallaspy** [comment]
Will update message right now.

**Comment by MCGallaspy** [comment]
Now looking at this for 0.16, so I'm trying to make a list of valid commands.

Sanity check commands (work now, should still work):
* `kalite start`
* `kalite start --port=8010`
* `kalite manage unpack_assessment_zip my_cool_file.zip`
* `kalite manage runserver 0.0.0.0:8008 --setttings=kalite.project.settings.dev`

Commands that don't work, but should:
* `kalite start --port 8010`
* `kalite manage runserver 0.0.0.0:8008 --setttings kalite.project.settings.dev`
* `kalite manage contentload --import -dD:\ka-lite\import_test\`
* `kalite manage contentload --import --data=D:\ka-lite\import_test\`
* `kalite manage contentload --import --data D:\ka-lite\import_test\`

Invalid commands:
* `kalite manage contentload --import -d D:\ka-lite\import_test\` (maybe? or is this valid?)

**Comment by benjaoming** [comment]
Let's make sure that  #4766 also solves this.

Closing as a duplicate.
