### ISSUE TITLE
videoscan adds arbitrary mp4 files, even if it's not a recognized youtube ID

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#404]
Background:
videoscan looks at the video files in the database and actual files in the CONTENT_ROOT, and puts them in sync.

Expectation:
MP4 files that are not recognized (i.e. KA videos) would be ignored.

Current behavior:
They are added as video files, then never used.

Suggested fix:
When adding video files, use the ID2slug reverse lookup dictionary to validate the youtube_id.

**Comment by rtibbles** [comment]
Feature, not a bug.
