### ISSUE TITLE
Version number in docs is confusing to users

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#4043]
(From call with Team4Tech today)

Users were confused about why it said "KA Lite 2" in the docs, and weren't sure if they were on the right page:

![image](https://cloud.githubusercontent.com/assets/618416/8534521/f49813cc-23f1-11e5-8d57-9d6dc4e94602.png)

It looks like, on the latest develop build of the docs, it's got: "KA Lite dev11 documentation".

Ideally, this should read "KA Lite 0.14 documentation" (or possibly the full "0.14.0", though I think we decided to have the docs just versioned by minor release).

**Comment by MCGallaspy** [comment]
I'll update this.

**Comment by MCGallaspy** [comment]
Seems like on master (i.e. 0.13.x) it's using the patch number there (hence KA Lite 2). A fix to that would mean a change to master/0.13.x.

**Comment by jamalex** [comment]
Probably good to do for 0.13.x eventually, if we're planning on leaving versioned docs up there, otherwise just for 0.14.x
