### ISSUE TITLE
Document the ability to install language packs offline

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#4049]
(From call with Team4Tech today)

Right now, [according to our documentation](http://field.learningequality.org/develop/docs/usermanual/userman_admin.html#language-packs), you need to have Internet access to download language packs. However, we actually have a management command (`kalite manage languagepackdownload --from-file=FILE`) that allows for this to be done offline, and I was asked today how to do that.

Two things are needed here:
- Additional documentation, possibly as a separate "doing installations offline" section also linked from both the Download Videos and the Download Language Packs sections. Basically, we need to tell people what files to copy, where to put the files after installing, and what commands to run.
- Links to the zip files for the language packs for each language. Might be easiest to just hardcode these into the docs for now, unless we want to finish fixing up https://hub.learningequality.org/languages/dashboard instead (@aronasorman?)

This isn't a release blocker, but will be important to do by late July for Team4Tech's deployments.

**Comment by jamalex** [comment]
Any progress on this, @aronasorman?

**Comment by aronasorman** [comment]
Will add this in later today.

**Comment by MCGallaspy** [comment]
I think we talked with Team4Tech about this privately, but it would still be good to add to the docs. In the meantime, moving to 0.15.

**Comment by benjaoming** [comment]
I think that splitting our installation documentation into "Online methods" vs. "Offline methods" is a great idea! :+1:

**Comment by aronasorman** [comment]
Good idea @benjaoming! Maybe @arnoan can take that into account for his planned docs refactor.

**Comment by arnoan** [comment]
@aronasorman (y) Will do, that's exactly the kind of inconsistencies/incomplete information I'm currently looking out for.

**Comment by aronasorman** [comment]
Fixed in https://github.com/learningequality/ka-lite/pull/4533.
