### ISSUE TITLE
Installing alpha7 deb on Ubuntu - issues and recommendations

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4060]
Ok, so I had alpha2 installed previously, used the link from https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite/+packages, deb file opened in Ubuntu Software Center:

![alpha7-1](https://cloud.githubusercontent.com/assets/1457929/8551441/df1b69b4-24d6-11e5-8411-f46ddecd16b0.png)

Maybe not urgent right now, but consider putting a pic/logo and shortening the title so it's not truncated in the Ubuntu Software Center window. I pressed the `Upgrade` button and the installation started. At certain point this Debconf window appeared:

![alpha7-4b](https://cloud.githubusercontent.com/assets/1457929/8551908/e5b8ba4e-24d9-11e5-9aa5-af51f22fd511.png)

Again, maybe not urgent, but consider putting a more human-redable window title, and `Yes` instead of `Forward` (to me at least sounds like a clearer message). Is `ka-lite` script and `/etc/init.d/` folder? The phrase might not be overly clear for non advance users... Next window:

![alpha7-5b](https://cloud.githubusercontent.com/assets/1457929/8552125/578463de-24db-11e5-9570-09d321d9b237.png)
 
Is `ka-lite` a new user you are proposing to create? It may be better to retrieve the users already available on the machine and offer the person who is installing to choose who will be the `owner`.

This is potentially important decision, so would it be possible to include this text directly inside the window itself, and not visible only by pressing the `Help` button? Second issue I'm not not clear about is: what is `by default`? User who will be the `owner`? I've changed the text in the field to my desktop user `didi`, pressed `Forward` and the following error appeared:

![alpha7-6b](https://cloud.githubusercontent.com/assets/1457929/8552518/e7851f12-24dd-11e5-9f96-12bd7651baf3.png)

```
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 309746 files and directories currently installed.)
Preparing to unpack .../ka-lite_0.14.alpha7-0ubuntu1_all.deb ...
Unpacking ka-lite (0.14.alpha7-0ubuntu1) over (0.14.alpha2-0ubuntu1) ...
Setting up ka-lite (0.14.alpha7-0ubuntu1) ...
Creating config file /etc/init.d/ka-lite with new version
insserv: script ka-lite: service kalite already provided!
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
dpkg: error processing package ka-lite (--install): 
subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing: ka-lite
```

Once I closed the window, it seemed that KA Lite was installed:

![alpha7-7](https://cloud.githubusercontent.com/assets/1457929/8551784/ecea73f8-24d8-11e5-9348-a593a1c55bf1.png)
 
At this point it is unclear what is user supposed to do, and how to start KA Lite, so maybe a message is warranted - it's not like in Windows system that you know it will be in the task bar. The only thing I could think of is to open Terminal and do the `kalite manage setup`. That part finished without any issues and I was able to start the server... :+1:

**Comment by radinamatic** [comment]
I'm going to try the `kalite manage generaterealdata` now, keep your fingers crossed...

**Comment by jamalex** [comment]
Thanks @radinamatic! This probably actually belongs on the installers repo, if it's easy to port across: https://github.com/learningequality/installers/issues

**Comment by radinamatic** [comment]
It must be the high @jamalex, I didn't even remember there was an installer repo... :P 
I'll port it over there!

**Comment by radinamatic** [comment]
Opened as #86 in installers repo, closing here.
