### ISSUE TITLE
Browser "Save passwords" feature takes wrong field for "username" 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4062]
**Branch**: alpha7 on Ubuntu (so technically 0.14.x), but I remember encountering this issue weeks ago on Windows - NOT urgent so maybe 0.15? 

**Expected Behavior**: When user registers, or Admin registers a new Learner or Coach, if browser is configured to save passwords, it will offer to do so for this new register. For this feature to be useful, browser needs to save the content of fields `username` and `password`. 

**Current Behavior**: Instead of `Username` field, browsers grab the `Last Name` field and if users do not notice it (I didn't), they will end up with useless login data that they will have to correct every time, or go and clear saved passwords. In the pic below, I left the  `Last Name` field empty, and browser should have grabbed the  `Username` **pincop**. This situation happens also every time password is changed for a given user. 

![username_password](https://cloud.githubusercontent.com/assets/1457929/8555250/0d9e8718-24ef-11e5-808c-e718783018e9.png)

**Steps to reproduce**:

1. Log in as Admin and create a new user or change password for an existing one.

At first I thought it might have something to do with `autocomplete="off"`, which I'm not sure is useful since most modern browsers don't support and/or ignore it:

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

Further research hinted that at least FF, and obviously Chrom(ium) from the pic above, tend to grab the first text input field above the password as the `username`. Hence in our case they offer to save `Last Name` instead of `Username`. The solution could be to rearrange the input fields:
- Last Name
- First Name
- Username
- Password

or

- Username
- Password
- Last Name
- First Name

**Comment by benjaoming** [comment]
This has worked fine in FF since the new login dialogue was implemented.
