### ISSUE TITLE
Add user warning for server restart after language packs download/update

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4070]
**Branch**: develop  
Regarding the `restart` requirement after language pack download (see #4027 for context), another even more straightforward place where to put the user warning than the Admin docs ( #4037), should be the `/update/languages/` page itself: 

![restart_server](https://cloud.githubusercontent.com/assets/1457929/8585841/de62eeb8-25e7-11e5-8043-2efd5116ae26.png)

Or similar phrase to that effect, with the link for instructions on [doc pages](http://field.learningequality.org/develop/docs/usermanual/userman_admin.html#restarting-your-server).

**Comment by rtibbles** [comment]
This can't be done in 0.15 due to string freeze.

**Comment by rtibbles** [comment]
Fixed in #4489
