### ISSUE TITLE
cannot download second video on RPi

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#4074]
platform: PRi 512RAM Raspbian
kalite: ka-lite_0.14.alpha7-0ubuntu1_all.deb
steps to reproduce:

1. login as admin and go to video download page and download one video
2. once the first video download finished, select another video and hit download video button
3. you will never see the downloading progress bar again and have no way to know if the video is downloaded even after long waiting
4. if you refresh the page, you will find out the second video was not downloaded, and you can repeat the problem again following steps 1, 2, 3.

**Comment by 66eli77** [comment]
@rtibbles the problem seems that after the first video download, kalite will re-Preloading exercise data/content data/topic tree for language en. This process takes a long time(15+ mins). If I wait this process to be finished and then choose the second video to download, then everything works fine.

**Comment by benjaoming** [comment]
@rtibbles assuming we could mark content and topic tree data *changed*, would there be a way to load these data structures quicker into memory when initializing the server? It's not just that RPi is slow to start, but all other platforms could be said to have the same symptoms more or less. A slow or busy computer could produce the above error just as well as the RPi can?

**Comment by rtibbles** [comment]
@benjaoming More intelligently invalidating the caches will be the ultimate way to fix this, but I don't want to churn the code that much just before release. I have made a PR that just invalidates the disk based caches for now, meaning that the caches will get rebuilt at next reboot.

**Comment by rtibbles** [comment]
Fixed in #4077
