### ISSUE TITLE
Endlessly running points (after video ends) 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4078]
**Branch**: develop  

**Expected Behavior**: I haven't paid much attention to the way learners earn points so far, so I'm guessing that upon watching every video they get a certain **finite** amount.

**Current Behavior**: While testing something unrelated, and jumping towards the end of the video, I noticed that the points kept accumulating even after video finished:  

![running_points](https://cloud.githubusercontent.com/assets/1457929/8630996/b56fbe32-276d-11e5-86ba-e40b5575ad47.gif)
(gif has a single loop, so reload and clear cache to see the animation again)  

**Steps to reproduce**:

1. Log in as learner.
2. Choose a video and watch it until the end. 
3. Do not leave the video page after it finishes and observe points accumulating endlessly.

**Comment by benjaoming** [comment]
@radinamatic could you possibly triage all the issue reports you have opened? There are 32 :)

https://github.com/learningequality/ka-lite/issues/created_by/radinamatic

**Comment by radinamatic** [comment]
@benjaoming Life saver!!! 

I was just trying to figure out what would be the best way to approach (re-test/confirm...) the gazillion issues you managed to triage today, and this does seem the best place to start! Jumping into it now... 😉

**Comment by benjaoming** [comment]
You're most welcome @radinamatic :) Going back in time is fun :)

**Comment by radinamatic** [comment]
Non extant on 0.16, closing!
