### ISSUE TITLE
Perseus load timeout on RPi

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#4080]
platform: RPi 512RAM Raspbian
kalite: ka-lite_0.14.alpha7-0ubuntu1_all.deb & ka-lite-raspberry-pi_0.14.alpha7-0ubuntu3_all.deb
steps to reproduce:
1. when install kalite on RPi, choose to download assessment at command line prompt
2. after kalite starts, go to Learn page and you will see the exercises are not grey out
3. use the sidebar to open an exercise
4. you will get the error message on Chrome console log as:
```
Uncaught Error: Load timeout for modules: /static/perseus/build/perseus-2.js
http://requirejs.org/docs/errors.html#timeout
```

from the terminal on RPi ($kalite start --foreground --debug):
```
INFO:cherrypy.access.93575248:192.168.1.15 - - [14/Jul/2015:00:45:05] "GET /static/perseus/build/perseus-2.js HTTP/1.1" 200 1451207 "http://192.168.1.39:8008/learn/khan/math/early-math/cc-early-math-counting-topic/cc-early-math-counting/counting-out-1-20-objects/" "Mozilla/5.0 (macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36(KHTML, like Gecko) Chrome/43.0.2357.130 Sfari/537.36"
```

**Comment by benjaoming** [comment]
Thanks for testing the RPi stuff! Is this related to the ka-lite .deb which uses the django static serve? I mean, did the new ka-lite-raspberry-pi deb manage to get the static file served (it uses ngnix for static files) ?

**Comment by 66eli77** [comment]
@benjaoming  the exercise won't work for both .deb's.  for the latest deb(ka-lite-raspberry-pi_0.14.alpha7-0ubuntu3_all.deb), during installation, it asked me if I want to use new ngnix stuff, I opted yes.

**Comment by benjaoming** [comment]
@66eli77 so ka-lite-raspberry-pi also fails trying to retrieve static media? Can you confirm that it uses nginx to serve static media? Do you have any theories about this? It would seem obvious that it's related to memory.
