### ISSUE TITLE
"Syncing through the GUI is slow and seems to get stuck. Using terminal this process takes just a few seconds."

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#4090]
This was reported by Abhinav for the Nalanda project, on the 0.13 release code.

Would be good to do some testing on this, and determine what the cause might be, since we shouldn't expect the web-based sync process to be any slower than the command-line sync (*both* should be slow! :laughing:).

Not a release blocker for 0.14, if it's already extant in 0.13, but important to resolve soon.

**Comment by aronasorman** [comment]
I'm leaving this for 0.15, @jamalex can you take a quick peek on why this is happening?

**Comment by rtibbles** [comment]
Any progress on this?

**Comment by jamalex** [comment]
On 0.16, it can take a while, and while it's annoying that it doesn't show a progress bar, it doesn't seem to be slower than the command line for me.
