### ISSUE TITLE
Hosted documentation should be namespaced by language and version number, with default redirects

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#4098]
In order to be able to have persistent links for docs pages (e.g. from error messages or on the web), we should shift immediately to a permanent and standard schema.

Similar to Django (e.g. [here](https://docs.djangoproject.com/en/1.5/topics/db/multi-db/)) we should probably have it look something like:
https://learningequality.org/docs/en/0.14/

Since we already have links in various places to docs pages that don't use this schema, we should put in a few redirects -- probably the FAQ and install page would be enough:
https://learningequality.org/docs/faq.html -> https://learningequality.org/docs/en/0.14/faq.html
https://learningequality.org/docs/installguide/* -> https://learningequality.org/docs/en/0.14/installguide/*

(For simplicity, these redirects can be set up in the frontend proxy server like this: https://github.com/fle-internal/ansible-playbooks/blob/master/roles/gatehouse/vars/main.yml#L127 -- happy to help with that part)

**Comment by MCGallaspy** [comment]
Addressed in https://github.com/fle-internal/ansible-playbooks/pull/50 and https://github.com/fle-internal/ansible-playbooks/pull/51, yes? Can we now close this @jamalex?

**Comment by benjaoming** [comment]
This is now implemented via ReadTheDocs, http://ka-lite.readthedocs.org/en/latest/
