### ISSUE TITLE
Docs tweaks for 0.14

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#4106]
Just in skimming the admin page docs, a huge number of things popped out as wrong. This page (and, I'm guessing others) need a thorough review and update, but I wanted to highlight the main things that popped out at me in my skim.

---

* [x] http://field.learningequality.org/develop/docs/en/usermanual/userman_admin.html#raspberry-pi

`USE_MPLAYER` setting no longer exists, so this section can be deleted.

---

* [x] http://field.learningequality.org/develop/docs/en/usermanual/userman_admin.html#optimization-of-storage-and-system-load

- `CRONSERVER_FREQUENCY`: description here is not quite right, as it only actually runs the sync cron job every hour, even though the cronserver runs every 10 mins (by default). Making this smaller won't increase the frequency of syncs, but making it longer than 1 hour will reduce the frequency.

> This is how frequently KA Lite tries to synchronize user data with other Devices on your Zone.

should be

> This is how frequently KA Lite tries to synchronize user data with the online Hub server.

- `CACHE_TIME`: I don't think we're using the Django page cache any more, are we, @rtibbles? In any case, the description of what it does is now out of date.

- `CHERRYPY_THREAD_COUNT`: We now hardcode this as `'server.thread_pool': 18,` in kalitectl.py, so this setting won't do anything

---

* [x] http://field.learningequality.org/develop/docs/en/usermanual/userman_admin.html#changing-base-settings

These instructions are incomplete (the example is missing). Also, what will go in the autogenerated settings.py if it's a Raspberry Pi -- will it automatically know to import the RPi base settings? Otherwise, it won't use the RPi settings by default, right?

---

* [x] http://field.learningequality.org/develop/docs/en/usermanual/userman_admin.html#running-ka-lite-with-your-own-settings

It would be clearer to have:

> on Windows, locate C:\Users\<username>\.kalite

be:

> on Windows, locate C:\Users\<username>\.kalite\settings.py

Is this currently the correct argument order, after @aronasorman's PR?

> kalite <command> --settings=my_settings_module

---

* [x] http://field.learningequality.org/develop/docs/en/usermanual/userman_admin.html#updating-on-mac-os-and-linux

- This doesn't seem to be updated at all. Updating from source is no longer recommended!

- "See the Windows installation guide" isn't an actual link

---

* [x] http://field.learningequality.org/develop/docs/en/usermanual/userman_admin.html#downloading-videos-in-bulk

We no longer support BTSync. Traditional torrent files should be downloaded from https://learningequality.org/downloads/ka-lite/0.14/content/

---

* [x] http://field.learningequality.org/develop/docs/en/usermanual/userman_admin.html#administrator-glossary

> "A sharing network is a group of devices that share data between one another. Data can mean video content, access software applications, and certain files."

is incorrect, and should be changed to:

> "A Sharing Network is a group of devices that share user data. This data is synced to the central server when an Internet connection is available, and then synced down onto other devices in the same Sharing Network."

> "A device should be able to run a KA Lite server (most computers) and other devices to be used as clients. [...]"

should be changed to:

> "A Device is a computer running the KA Lite server software. Each Device has a name and unique ID, stored in the KA Lite database on that device."

The following definitions are confusing and unnecessary, and should be deleted:

> "Torrent", "Seeder", "Bandwidth"

benjaoming additions from #4095:

* [x] Sort out example settings.py file
* [x] Change "note" to "warning" and move documentation about CONTENT_ROOT that contains assessment items https://github.com/learningequality/ka-lite/pull/4095/files#r34739023
* [x] @aronasorman : *Rather than ~, can we explicitly label that as <user's home directory>/? Normal users might not know what ~ means.*

**Comment by jamalex** [comment]
Flagging @aronasorman and @MCGallaspy in here as well, as they've got their hand in docs, but assigning to @benjaoming as requested.

**Comment by benjaoming** [comment]
Tasks added

**Comment by MCGallaspy** [comment]
> on Windows, locate C:\Users<username>.kalite

This directory won't exist on Windows XP (`~` gets expanded as something else... I think `X:\Documents and Settings\<username>`).

**Comment by benjaoming** [comment]
Description for CRONSERVER_FREQUENCY: Removed. Changing its value doesn't have any critical effects. Video download jobs are started immediately, anyways.

See: https://en.wikipedia.org/wiki/Convention_over_configuration

**Comment by benjaoming** [comment]
> CACHE_TIME: I don't think we're using the Django page cache any more, are we, @rtibbles? In any case, the description of what it does is now out of date.

What I'm seeing about cache in settings.base is absurd by default so opened up a new issue => #4125

**Comment by benjaoming** [comment]
CHERRYPY_THREAD_COUNT: As Jamie said, the setting has no effect. Removed from docs, *convention over configuration*.

**Comment by benjaoming** [comment]
> These instructions are incomplete (the example is missing). Also, what will go in the autogenerated settings.py if it's a Raspberry Pi -- will it automatically know to import the RPi base settings? Otherwise, it won't use the RPi settings by default, right?

There was a syntax err for the example block, but it came back in a previous PR: http://ka-lite.readthedocs.org/en/0.14.x/usermanual/userman_admin.html#running-ka-lite-with-your-own-settings

Yes, the raspberry pi .deb creates a settings module automatically with `kalite.project.settings.raspberry_pi` loaded.
