### ISSUE TITLE
No content in develop branch 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4108]
**Branch**: develop  

**Current Behavior**: Not really sure what has gone wrong, but my develop branch seems devoid of content: sidebar is empty, nothing in content rec nor progress reports, and I get a 500 error on search:

```
KeyError at /search/

'kind'

Request Method: 	GET
Request URL: 	http://192.168.1.33:8008/search/?query=math
Django Version: 	1.5.1
Exception Type: 	KeyError
Exception Value: 	

'kind'

Exception Location: 	d:\github15\KA\ka-lite\kalite\distributed\views.py in <lambda>, line 187
Python Executable: 	g:\Python27\python.exe
Python Version: 	2.7.9
Python Path: 	

['d:\\github15\\KA\\ka-lite\\python-packages',
 'd:\\github15\\KA\\ka-lite\\dist-packages',
 'd:\\github15\\KA\\ka-lite\\kalite',
 'd:\\github15\\KA\\ka-lite',
 'g:\\Python27\\lib\\site-packages\\sphinx-1.3.1-py2.7.egg',
 'g:\\Python27\\python27.zip',
 'g:\\Python27\\DLLs',
 'g:\\Python27\\lib',
 'g:\\Python27\\lib\\plat-win',
 'g:\\Python27\\lib\\lib-tk',
 'g:\\Python27',
 'g:\\Python27\\lib\\site-packages']

Server time: 	Thu, 16 Jul 2015 01:17:57 +0200
```

 (traceback here: http://dpaste.com/2A04CVP). 

All was working fine this evening when I posted a PR (#4105), but I only touched handlebars, no actual code involved...

**Comment by radinamatic** [comment]
Mystery solved, as @66eli77 reported on #4109, it happens on **develop** too, `DO_NOT_RELOAD_CONTENT_CACHE_AT_STARTUP = True` is the culprit!

Closing as duplicate.

**Comment by 66eli77** [comment]
@radinamatic  can you tell us what OS you use when encounter this problem?

**Comment by radinamatic** [comment]
@66eli77 This happened on Windows XP, I can try it on Ubuntu if it helps.
