### ISSUE TITLE
Reduce assessment items data

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4112]
@jamalex mentioned that current assessment items include image files that may be replaced by smaller filesize javascript rendering. This will be more costly to clients, however given that my current builds are heavily loaded by the many image files and that this may reduce download and distribution resources, I vouch for the alternative.

Would this be possible?

**Comment by benjaoming** [comment]
As an additional comment, builds of the debian packages with assessment items are taking 30+ mins on my local machine.

**Comment by rtibbles** [comment]
Not going to happen within the scope of KA Lite.
