### ISSUE TITLE
Changing default language and updating language packs not working (develop)

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4135]
**Branch**: develop

**Expected Behavior**: Admin should be able to use the `Set as default` button to change the default language, and `Upgrade` button to update language packs 

**Current Behavior**: Both `Set as default` and `Upgrade` buttons do nothing, and it seems that both `set_server_language` and `start_languagepack_download` are **undefined**:

![set_server_language_not_defined](https://cloud.githubusercontent.com/assets/1457929/8812663/ba51ce70-2ffd-11e5-9157-5ee65931a2fd.png)

Could it be some step that I missed from `browserify` refactor, @rtibbles? 

**Steps to reproduce**:
1. Log in as Admin.
2. Go to Manage > Languages
3. Try updating language packs or changing the default language.

**Comment by rtibbles** [comment]
No, it's a step *I* missed from the `browserify` refactor.

**Comment by radinamatic** [comment]
All sins will be forgotten, as soon as you do your penance (and fix whatever is missing).

**Comment by rtibbles** [comment]
@aronasorman you missed this one, something of a release blocker!

**Comment by rtibbles** [comment]
Fixed in #4334
