### ISSUE TITLE
Slow sidebar performance using language pack

### ISSUE THREAD

**Issue by jinchuika** [learningequality/ka-lite#4144]
The general performance is very slow, specially in the sidebar, when using a language pack. I tested this with two different servers, connecting from various devices and the same issue appeared in almost all of them.

### Server 1 info
Spec | Description
------------ | -------------
Processor | Intel(R) Atom(TM) CPU E3815 @ 1.46GHz
RAM | 2 GiB SODIMM DD3 1066 MHz (x1)
Network | RTL8111/8168B PCI Express Gigabit Ethernet
Disk | 500GB TOSHIBA MQ01ABF0
System | Ubuntu 12.04.3 LTS
ka-lite version | 0.13.2

### Server 2 info
Spec | Description
------------ | -------------
Processor | AMD Athlon(tm) 64 Processor 3500+
RAM | 2GiB DIMM DDR2 Síncrono 667 MHz (x3) (total 6 GiB)
Network | NetXtreme BCM5755 Gigabit Ethernet PCI Express
Disk | 250GB WDC WD2500AAKX-6
System | Ubuntu 14.04.1 LTS
ka-lite version | **0.13.2**

### Server 3 info
_The same as **Server 2**, but running the **version 0.12.8**_

***

#### Test with language pack loaded
These are the test ran when loading the Spanish language pack.

No | Client | Browser |  Syntom
------------ | ------------ | ------------- | -------------
1 | Windows XP PC (1GB RAM, Intel Centrino CPU) | Chrome 43 | Sidebar not responding. Very slow general performance. Impossible to use.
2 | Generic Tablet (Android 4.2, 1GB RAM, Dual Core CPU) | Android default browser | Sidebar not showing, not responding or very slow. The tab and the browser app often crash. Not practically usable.
3 | Nexus 7 2013 Tablet (Android 5.1, 1GB RAM, Quad Core CPU) | Mobile Chrome 43 | Slow sidebar rendering. Slow system performance when loading pages.
4 | iPad mini (iOS 8.4) | Mobile Safari | Impossible to access to the system. Pages don't load.
5 | iPad mini (iOS 8.4) | Mobile Chrome | Impossible to access to the system. Pages don't load. App crashes.
6 | iMac 2013 (OSX 10.10, 8GB RAM, Quad Core i5 CPU) | Chrome 43 | Slow performance for a while. It works faster after some time and it is more usable.
7 | Ubuntu 14.04 PC (6GB RAM, Dual Core i5 CPU) | Firefox 39 | Slow performance on navigation through the system; some pages take too long to load. General slow performance in loading pages; but the side bar isn't that slow.

When connecting the **Server 2**, the results in overall the clients are the same, except for:

No | Client | Browser |  Syntom
------------ | ------------ | ------------- | -------------
2 | Generic Tablet (Android 4.2, 1GB RAM, Dual Core CPU) | Android default browser | Slow sidebar, but a little mor fluid. The tab doesn't crash. It is usable, but still very slow.
3 | Nexus 7 2013 Tablet (Android 5.1, 1GB RAM, Quad Core CPU) | Mobile Chrome 43 | Useful sidebar, way more responsive. Might get slow when tapping the "Learn" panel.
7 | Ubuntu 14.04 PC (6GB RAM, Dual Core i5 CPU) | Firefox 39 | Significantly faster entering the first time, not a big deal. It works really nice after that.

Testing some of the previous clients with the **Server 3** (version 0.12) gave no problem to use KA-Lite at all. I didn't have chance to test devices 1, 5 and 6; but I guess it they would have worked fine. Everything works well in that version - having in mind the expected results for each device.

#### Test WITHOUT the language pack
These are the devices I tested without loading the language pack. The results are almost the same for both **Server 1** and **Server 2**, so I'm including the results on the same page.

No | Client | Browser |  Syntom
------------ | ------------ | ------------- | -------------
2 | Generic Tablet (Android 4.2, 1GB RAM, Dual Core CPU) | Android default browser | Really faster than the previous test. The sidebar shows up faster and it is more responsive.
3 | Nexus 7 2013 Tablet (Android 5.1, 1GB RAM, Quad Core CPU) | Mobile Chrome 43 | Smooth performance. Not a trouble in using it.
4 | iPad mini (iOS 8.4) | Mobile Safari | Performance is slow, but usable. Sidebar is responding well.
5 | iPad mini (iOS 8.4) | Mobile Chrome | Able to use it without trouble. Could be slow sometimes, but still working fine.
6 | iMac 2013 (OSX 10.10, 8GB RAM, Quad Core i5 CPU) | Chrome 43 | No problem at all. Good performance.
7 | Ubuntu 14.04 PC (6GB RAM, Dual Core i5 CPU) | Firefox 39 | No problem at all. Good performance.

Server 3 was not tested without the language pack because it didn't have trouble in first place.

**Comment by jamalex** [comment]
Thanks @jinchuika! We'll need to do some testing in 0.14 to see that this problem has been improved.

**Comment by aronasorman** [comment]
Still the same case for 0.14. Unfortunately we don't have enough time to solve this for the current release.

**Comment by aronasorman** [comment]
Solved in https://github.com/learningequality/ka-lite/pull/4278.
