### ISSUE TITLE
Coach report is not getting updated for the learners for the exercises in version 0.13.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/ka-lite#4145]
Branch: master
Detailed description:
After solving few exercises the learners status is not getting updated for all the completed exercises, instead only a few is getting updated under the coach report.

Individual learner progress report seams to get update properly.

For example:
The learner has completed the following exercises, but the coach report does not reflect the same:
1. Addition and subtraction word problems within 20: Level 1
2. Addition and subtraction word problems within 20: Level 2
3. Addition and subtraction word problems within 20: Level 3
4. Addition and subtraction word problems within 20: Level 4
5. Multi-digit division without remainders

The learner has completed the following exercise and the report is updated properly:
6. Count to 100
7. Counting in scenes
8. How many objects 1

Expected behavior:
All the 8 completed exercises should get updated for the learners under coach report.

Actual behavior:
Only 3 exercises are getting updated for the learners under coach report.

Note:
1. I have reported only few exercises that are not getting updated but there might be same issue persisting for many other exercises. 
2. The same behavior is seen across all the implemented classrooms using version 0.13.

Please refer the screenshots for more details.

![learner](https://cloud.githubusercontent.com/assets/13453618/8848412/cd46564c-3154-11e5-96b5-ef61597d6312.png)
![learners](https://cloud.githubusercontent.com/assets/13453618/8848422/dca8c1f6-3154-11e5-8637-0580583cd1f8.png)
![student coach report updated](https://cloud.githubusercontent.com/assets/13453618/8848424/dcf7e448-3154-11e5-8024-5935e483ac6e.png)
![student progress report](https://cloud.githubusercontent.com/assets/13453618/8848425/dcfb2ef0-3154-11e5-8c72-a5e175b7251d.png)
![student2 coach report not updated](https://cloud.githubusercontent.com/assets/13453618/8848426/dcffc14a-3154-11e5-974b-2b50205ff76f.png)
![student2 progress report](https://cloud.githubusercontent.com/assets/13453618/8848427/dcffe166-3154-11e5-9e26-af14b078331c.png)
![student3 coach report not updated](https://cloud.githubusercontent.com/assets/13453618/8848428/dd0a264e-3154-11e5-8f64-f8e9238e5f3a.png)
![student3 progress report](https://cloud.githubusercontent.com/assets/13453618/8848423/dcd72a5a-3154-11e5-8e80-2681aa740561.png)

**Comment by aronasorman** [comment]
Hi @harishbalachandran, we're coming out with a new version soon that revamps the coach reports. We'll send the installers to the nalanda folks (you guys!) soon.

**Comment by rtibbles** [comment]
Not extant on 0.15.
