### ISSUE TITLE
Mac OS: Toolbar icons ideas

### ISSUE THREAD

**Issue by JohnJCZhou** [learningequality/ka-lite#4153]
After starting KA-Lite on Mac OS, the Leaf icon will turn into a Stop icon:
<img width="23" alt="2015-07-24 10 33 39" src="https://cloud.githubusercontent.com/assets/9564925/8880703/7a511990-31ef-11e5-964d-457f69fea18f.png">
Which brings up the concern that it is hard to locate later and may make user think when clicking on it, it will stop the server but it actually doesn't.
<img width="431" alt="2015-07-24 10 36 39" src="https://cloud.githubusercontent.com/assets/9564925/8880763/eb8d6514-31ef-11e5-87c2-ef086842b84f.png"> (Try to find it!)

I am having an idea of changing icons by make the default icon a black leaf, something like this:
<img width="364" alt="2015-07-24 10 40 03" src="https://cloud.githubusercontent.com/assets/9564925/8880824/78541e98-31f0-11e5-8293-e84e9f546250.png">

When KA-Lite is started, turn it into green:
<img width="356" alt="2015-07-24 10 41 42" src="https://cloud.githubusercontent.com/assets/9564925/8880840/9966a204-31f0-11e5-8514-9fea760f15ab.png">

**Comment by cpauya** [comment]
Good idea to finally have those icons for our system menu item @JohnJCZhou.  I didn't have a set of icons when we started so I just looked for appropriate ones from the ka-lite repo. :smiley_cat: 

This should be filed, more appropriately, on the learningequality/installers repo.

**Comment by benjaoming** [comment]
@cpauya if this is still relevant, it should be moved to the installers repo :)

**Comment by cpauya** [comment]
An FYI: Here's the related issue on the `installers` repo: [Cross-platform design of the tasktray icon launcher menu](https://github.com/learningequality/installers/issues/6)
