### ISSUE TITLE
Mac OS: Videos wouldn't instantly update in the content (Maybe for Mac ONLY)

### ISSUE THREAD

**Issue by JohnJCZhou** [learningequality/ka-lite#4154]
After downloading videos, the videos will not show up in the content directly. Users will have to restart the server to be able to see the updates, regardless the user login as an admin or student.

This issue cannot be duplicated on PC, so it may apply to Mac OS only.

Currently two solutions have been discussed:
Show instructions for how to view the updates of the videos in the success notification, something like:
"Download successful! Please restart KA-Lite to view the videos!"

Otherwise, take this as a bug and fix it.

**Comment by djallado** [comment]
@JohnJCZhou. Good idea to put a message to restart KA_Lite to view the videos after download.

**Comment by benjaoming** [comment]
This is no longer relevant, the content database is refreshed instantly :)
