### ISSUE TITLE
Mac OS: Video download Progress bars

### ISSUE THREAD

**Issue by JohnJCZhou** [learningequality/ka-lite#4155]
Video download Progress bars have different colors and widths.
<img width="1164" alt="2015-07-24 11 42 00" src="https://cloud.githubusercontent.com/assets/9564925/8882071/3813e2e2-31f9-11e5-8412-e4b332163017.png">

Based on research, most two progress bars displays are in identical styles; sometimes colors may vary.
It might be optimized to make them identical:
![indesigncs4-pdfexport](https://cloud.githubusercontent.com/assets/9564925/8882205/10105496-31fa-11e5-8c9d-620abf2dbf7b.png)

Also refer to:
https://ux.stackexchange.com/questions/40046/is-it-a-bad-idea-to-have-two-progress-bars-in-one-dialog/40048#40048?newreg=944337a082c54cc99472a5d84c4b8d1b

**Comment by benjaoming** [comment]
I don't even think we should display progress bars, but I'm also pretty conservative about not bloating stuff :)

The progress bars are now the same in height, can't see why we should give them the same color.
