### ISSUE TITLE
Errors on opening videos (develop)

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4157]
**Branch**: develop on Ubuntu 15.04

**Current Behavior**: I have been unable to watch videos since the **browserify** refactor. At first I thought it might have something to do with the script version, but it doesn't seem so (#4151). When trying to watch videos, I just get a completely blank page, and the 301 error in debugger.

![301-video](https://cloud.githubusercontent.com/assets/1457929/8882712/758ab010-3249-11e5-9431-8eafa1b70cdb.png)

I've been looking forward to see the Development Toolbar, but it's not opening on `/learn/` template.

**Comment by radinamatic** [comment]
Another Console screenshot with Chrome this time:

![more_video_errors](https://cloud.githubusercontent.com/assets/1457929/8883381/bd3987ce-324e-11e5-8e68-322db2d46ff9.png)

**Comment by radinamatic** [comment]
Code must have changed in develop so there's a new error among the others:
`Uncaught ReferenceError: VideoLogCollection is not defined`

![workspace 1_002](https://cloud.githubusercontent.com/assets/1457929/8991114/b8c764c0-36f6-11e5-8251-c9c331f0e199.png)

**Comment by rtibbles** [comment]
I think this should be fixed by #4199

**Comment by radinamatic** [comment]
It did get better, but not completely :(

Video seems to load, but then the player resizes:

![learn introduccion a la suma ka lite - chromium_007](https://cloud.githubusercontent.com/assets/1457929/9035505/ad3d9d10-39d8-11e5-8d19-23ba306fdacf.png)


On Firefox, though, I get a much longer list of errors:

![learn introduccion a la suma ka lite - chromium_004](https://cloud.githubusercontent.com/assets/1457929/9035514/c6d166da-39d8-11e5-8bc6-6c18dfd40485.png)

Since there is a "big-play-button", once you press it, the video container disappears completely: 

![learn introduccion a la suma ka lite - chromium_005](https://cloud.githubusercontent.com/assets/1457929/9035532/f63eaffe-39d8-11e5-80d9-6327dae2525c.png)
 
I tested the responsive view (maybe something in #4199 ?), but the result was the same:

![learn introduccion a la resta ka lite - chromium_006](https://cloud.githubusercontent.com/assets/1457929/9035583/9b31b204-39d9-11e5-8556-9d285dc6ec4d.png)

**Comment by radinamatic** [comment]
Just switched again to Chromium, in time to see the `User ID required for get_uuid` error that appeared while the window was in the background:

![learn introduccion a la suma ka lite - chromium_008](https://cloud.githubusercontent.com/assets/1457929/9035624/07d07b70-39da-11e5-901b-34bda282c6e1.png)

**Comment by radinamatic** [comment]
Could somebody reopen this? @aronasorman @rtibbles 
Videos & exercises are still not loading on `develop`, not even after the recent merges from 0.14.x.

**Important detail**: my default language is Spanish (unable to change it because of #4135), so I can't verify if the issue is valid for the interface in English.

![videos-exercises-not-loading](https://cloud.githubusercontent.com/assets/1457929/9229171/1f78db84-411c-11e5-8444-275e9afc2c4d.png)
