### ISSUE TITLE
Mac OS: Sidebar bug

### ISSUE THREAD

**Issue by JohnJCZhou** [learningequality/ka-lite#4159]
When we click and get in deep in the list of the sidebar, the going back button is not working right. Even if the address bar shows that the we are going up in the list, the parts that are supposed to disappear remains its position.
<img width="1212" alt="2015-07-24 4 04 29" src="https://cloud.githubusercontent.com/assets/9564925/8886371/fc833be0-321d-11e5-9154-4e06062a6eb3.png">

**Comment by benjaoming** [comment]
Thanks for reporting @JohnJCZhou - However, I can't reproduce this on 0.16. You're welcome to open up a new report if you can reproduce it, please follow our new issue template if you do so.
