### ISSUE TITLE
KeyError: "There is no item named 'assessmentitems.json' in the archive". 

### ISSUE THREAD

**Issue by cts-prog3** [learningequality/ka-lite#4163]
I am getting this error when I tried to update from .12 to .13.  Apparently others are getting it also: https://forums.learningequality.org/t/there-is-no-item-named-assessmentitems-json-in-the-archive/234/2

I am running Ubuntu 14

**Comment by cts-prog3** [comment]
I have tried both kalite manage unpack_assessment_zip https://learningequality.org/downloads/ka-lite/0.14/content/assessment.zip -f and downloading it on another machine and FTPing it to the server but neither seems to work.  Any ideas what to try?  Is this the wrong place to ask these type of questions?

**Comment by MCGallaspy** [comment]
From the forums:

>Hi,

>This is my first post here and would like to take the opportunity to congratulate the ka-lite team for their wonderful work. I wish them all the best.

>I have been trying to install ka-lite version 0.13 on a raspberry pi. The installation goes fine until it gets to assessment items package. It doesn't matter if I follow the instruction and allow the setup to download the package or I download the package separately and specify its path, I keep getting the following error:

>KeyError: "There is no item named 'assessmentitems.json' in the archive".

>What am I not doing right? I would appreciate it very much if someone can give me a hint. Thanks

>Richard

Seems like it could be an error in the archive? @aronasorman @jamalex

**Comment by MCGallaspy** [comment]
@cts-prog3 you said you're using version 0.13? Can you try downloading [this version of the file](https://learningequality.org/downloads/ka-lite/0.13/content/assessment.zip) and using that as the target of unpack_assessment_zip? e.g. `kalite manage unpack_assessment_zip [[the file linked to above]]`

**Comment by cts-prog3** [comment]
I am running 0.13 and didn't even notice the document referred to 0.14. I will try downloading the one for 0.13.   KA-Lite is a great product!  Keep up the good work.  I can't wait to see what new features there are in 0.14.

**Comment by cts-prog3** [comment]
I downloaded the assessment.zip for 0.13 but still get the same message.  I open the archive and see assessmentitems.sqlite and assessmentitems.version.  When I open the assessmentitems.version it say 0.14.  I wonder if the wrong file got placed there?

**Comment by MCGallaspy** [comment]
> I wonder if the wrong file got placed there?

Possibly, looking in to it. @jamalex might have some insight.

**Comment by aronasorman** [comment]
Hi @cts-prog3, can you try downloading it again? I've fixed it on our side. As per https://github.com/learningequality/ka-lite/issues/4193, it seems to be working now.

**Comment by aronasorman** [comment]
Assuming fixed. Reopen if still extant.
