### ISSUE TITLE
problem viewing coach reports

### ISSUE THREAD

**Issue by rkurata** [learningequality/ka-lite#4167]
I created a learner account and a coach account and then completed some exercises while logged in as the learner. The progress reports correctly indicate the amount of exercises I completed as the learner, but when I log in as a coach, no data is represented for the coach reports.

![image](https://cloud.githubusercontent.com/assets/10429889/8914967/f4f715a0-3456-11e5-907c-86825040d774.png)

**Comment by benjaoming** [comment]
Thanks for the issue report, sorry that it got drowned. Coach reports work, and have been known to work albeit with a couple of smaller known issues. But the above scenario should definitely not be an issue anymore.
