### ISSUE TITLE
asking for a more forgiving device registration

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#4179]
there seems no way to register the device again once you registered with 'one-click-register'.
some users changed their mind and wanted to be able to access their online data, but not able to do so with  'one-click-register'.
@jamalex  @aronasorman what you think?

**Comment by benjaoming** [comment]
This will have to be done manually in these special cases. As with this request: https://community.learningequality.org/t/is-it-possible-to-change-device-registration/225/3
