### ISSUE TITLE
Forced log-out of the Admin user during the language pack download/upgrade

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4181]
**Branch**: 0.14 alpha12 installed today from PPA on Ubuntu 15.04

**Expected Behavior**: Admin user should be able to download/upgrade language packs.

**Current Behavior**:  The issue first happened when I was upgrading language packs for English - process was apparently interrupted towards the end and my Admin user was logged out. I did not make a screenshot at that point (bad), but once I logged in again, the English Language pack appeared updated. So I tried to replicate by downloading Spanish one, and the same error reappeared:

![update-es](https://cloud.githubusercontent.com/assets/1457929/8942285/d75ccee4-3574-11e5-84a3-fc2e799a8882.png)

Sometime at the above point the process interrupts (notice that English appears updated), the Admin user is logged out and the error implies no authorized access:

![update-es2](https://cloud.githubusercontent.com/assets/1457929/8942345/22e9f3be-3575-11e5-9083-160638a819c7.png)

However, when I log in as Admin again everything seems fine:

![update-es3](https://cloud.githubusercontent.com/assets/1457929/8942361/3d7e5df0-3575-11e5-8fde-4ea790de34ff.png)

I can understand the connection problem to central server, however it should not force the log-out of the Admin user.

**Comment by EdDixon** [comment]
I can confirm having this same experience while testing a PyPi install of alpha11. There were other times afterwards that I was unexpectedly logged out while working with it leading me to believe it was related to the Virtual Machine I was working with at the time. However, the first encounter I had with it, is exactly as Radina describes here?

**Comment by aronasorman** [comment]
Isn't critical. Putting it to 0.14.

**Comment by aronasorman** [comment]
s/0.14/0.15/g

**Comment by EdDixon** [comment]
Also experiencing the same behavior in the most current MAC build for 0.14. Happens logging in and going to the language management screen as described above. I have not seen this behaviour in windows but will double check.

**Comment by aronasorman** [comment]
Shouldn't be happening anymore with the move to cookie-based sessions. https://github.com/learningequality/ka-lite/pull/4257

**Comment by EdDixon** [comment]
Happening now on 0.15 development builds where the user is logged out of the session after navigating away from the video download tab but it also seems to sometimes happen randomly as well. I have not been able to reliably reproduce this but, it is still happening.

**Comment by EdDixon** [comment]
Expected behavior, admin session will timeout automatically in 30 minutes as a security precaution!
