### ISSUE TITLE
i have a question, activate kalite server.... and problems

### ISSUE THREAD

**Issue by wizard872** [learningequality/ka-lite#4184]
yea,  this kalite server for raspi2 B, IT,s work!  but  have a problem,

i did,
$ sudo service kalite start    
or
$ /home/pi/ka-lite/bin/kalite  start  .  and  kalite server worked,
i can sign in this site,  i can login that kalite server, [1.1.1.1:8008]
but problem is 1~2minute later.

i did'n never! stop kalite server, but this wtf, raspi kalite server automatically down. 
what's happend?

 my kalite server is stop when 1~2minute later.  i want use kalite server, but i can,t.

(my english is bad, sorry about that.  but i want solved this hell problem.....  ㅠㅠ plz help...)

**Comment by wizard872** [comment]
i use  kalite  AP  wifi  ,  i installed 

 git clone https://github.com/learningequality/ka-lite-pi-scripts.git,

but this kalite server  down,  1 or 2minute later.

i want continues kalite server.

**Comment by jaredestroud** [comment]
Do you have any logs or additional error messages you could provide?

**Comment by wizard872** [comment]
not  error messages.  it's  run and do work,  but  1~2minute later,  this kalite server  down...

i don't know  why....

**Comment by jaredestroud** [comment]
Something must be occurring with the  web server.  Can you describe the system you're running it on please? Ubuntu/Centos, what web server you're using, and other information that might be useful.

**Comment by wizard872** [comment]
i used raspberry pi2  B,   OS is raspbian wheezy //(2015-05-05-raspbian-wheezy) 

https://www.raspberrypi.org/downloads/   (OS  DOWNLOAD LINK)


AND I TRY THIS PAGES, 
https://learningequality.org/docs/installguide/install_rasp_pi.html    (KA-LITE  INSTALL LINK)

AP  (access point)  kalite  is available,  and i connect this kalite ap,  kalite is work.

but 1~2minute later,  connection is disable, kalite server down....

**Comment by aronasorman** [comment]
Thanks @wizard872. We're getting a couple of RPi 2s in the following days and we should be able to see if the new hardware is affecting KA Lite somehow.

**Comment by aronasorman** [comment]
Btw, how did you get KA Lite? Did you clone from the repo, or used one of our alpha debian installers?

**Comment by wizard872** [comment]
i installed  
this  first.
https://learningequality.org/docs/installguide/install_linux.html

step1~8.
and next,
https://learningequality.org/docs/installguide/install_rasp_pi.html
this page,

but i didn's use this 2 dongle
[ Note Two Wi-Fi USB modules have been tested with KA Lite on the Raspberry Pi  ]
[ Raspberry Pi WiPi adaptor                                                                                      ]
[ Edimax EW-7811Un                                                                                                ]

and i skip this 4 step,

///////////////////////////////////////////////////////////////////////////////////////////////////////
Install the USB adaptor software.
If using the WiPi, run this command:
cd /opt/ka-lite-pi-scripts
sudo ./use_wipi.sh
If using the Edimax EW-7811Un, run this command:
cd /opt/ka-lite-pi-scripts
sudo ./use_edimax.sh
//////////////////////////////////////////////////////////////////////////////////////////////////////

i used  RT-2870 wifi USB dongle,  and it works.

and then,  no error messages, kalite server work,  i can login my kaliteserver, 
i can create superuser account.

but 1~2minute later,. this kalite server down. off.  i don't know why this kalite stop,


////////////////////////

pi$ /home/pi/ka-lite/bin/kalite start     // i do

and

if i want  stop,  i typing this.

pi$ /home/pi/ka-lite/bin/kalite stop

but  do it, 

already stopped,    and  kalite server down.
.....

**Comment by aronasorman** [comment]
Hi @wizard872, we just announced 0.14, which we tested with the RPi 2. Everything is working on our side. Can you download the RPi version [here](https://learningequality.org/docs/0.14/en/installguide/install_all.html#raspberry-pi) and see if it works for you?
