### ISSUE TITLE
Missing Assessment items in latest Windows installer

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4185]
**Branch**: *KALiteSetup-0.14.0.exe* compiled on Jul 24 14:13, tested on Windows 8 & XP

As on **ka-lite-bundle** tested yesterday (#4182), @rtibbles code: 

```
bin/kalite shell
...
from kalite.topic_tools import get_exercise_cache
cache = get_exercise_cache()
for key, value in cache.iteritems():
    if not value.get("available", False):
        print key
```

Gives as the result the same 4 missing exercises:

```
increasing-decreasing-intervals-of-functions
dividing_decimals
dividing_fractions_word problems_2
matrix_determinant
```

However, in both these Windows installations a lot of the exercises are grayed-out and not available from the sidebar:

![sidebar-gray-ed](https://cloud.githubusercontent.com/assets/1457929/8968088/83e8a590-363b-11e5-8d03-626aa94dbb8f.png)

![sidebar-gray-ed2](https://cloud.githubusercontent.com/assets/1457929/8968092/8aacfc46-363b-11e5-98e2-aea1748f7733.png)

All the exercises that are greyed-out give the usual message:
```
This content was not found! Please contact your coach or an admin to have it downloaded.
```
![sidebar-gray-ed3](https://cloud.githubusercontent.com/assets/1457929/8968134/bff2abbc-363b-11e5-81ff-3891e5fd510b.png)

That's the difference with the **ka-lite-bundle** which did have present all the exercises, a part from the 4 listed as result from the script on top.

KA Lite root path on Windows 8:
```
C:\Users\Radina>echo %KALITE_ROOT_DATA_PATH%
C:\Program Files (x86)\KA Lite\ka-lite\
```

KA Lite root path on Windows XP:
```
D:\Program Files\KA Lite\ka-lite\bin>echo %KALITE_ROOT_DATA_PATH%
D:\Program Files\KA Lite\ka-lite\
```
In both installations the folder `\Program Files\KA Lite\ka-lite\assessment\khan` has `assessmentitems.sqlite`, `assessmentitems.version` files, and a lot of content in subfolders, each one with various .svg, .png, .html & json files.

**Comment by cpauya** [comment]
Just want to mention that the same set of assessments are also missing on the OSX install using the same script as per below:

```python
cyril-lappy6:~ cyril$ kalite shell
Python 2.7.9 (default, May  9 2015, 00:17:45)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from kalite.topic_tools import get_exercise_cache
>>> cache = get_exercise_cache()
for key, value in cache.iteritems():
    if not value.get("available", False):
        print key

>>> for key, value in cache.iteritems():
...     if not value.get("available", False):
...         print key
...
increasing-decreasing-intervals-of-functions
dividing_decimals
dividing_fractions_word problems_2
matrix_determinant
>>>
```

On the browser, we also have some menu items that are greyed-out:

![screenshot 2015-07-30 15 32 32](https://cloud.githubusercontent.com/assets/175580/8977971/80203f78-36d0-11e5-95e0-d49a3208b24d.png)

![screenshot 2015-07-30 15 37 08](https://cloud.githubusercontent.com/assets/175580/8978024/ef5802b8-36d0-11e5-9b7f-3dfac9d2162f.png)

But all the greyed-out items have non-existing videos, but the quizzes are all there.

**Comment by radinamatic** [comment]
No idea how or why, but today both installations do not seem to be missing any assessment items... Weird! @MCGallaspy @EdDixon 

I don't know if updating the English lang pack, and downloading & activating the Spanish one could have made a difference there, but that's the only thing I did since making the above screenshots that I might conceive having any influence.

I have another Win 7 machine where I can test this hypothesis, I'll report back!

**Comment by rtibbles** [comment]
@radinamatic Try simply restarting the machine to see if that causes the 'missing' items to disappear. It may simply be an availability stamping issue.

**Comment by radinamatic** [comment]
That's what happened @rtibbles : 

- Installation
- Assessments missing (yesterday)
- Overnight restart
- Assessments available (today)
- Restart 
- Assessments available again

**Comment by rtibbles** [comment]
This is an issue with the availability stamping not being properly run then.

**Comment by radinamatic** [comment]
On XP I didn't even restart the machine, just ka-lite itself to make the language pack available last night, and this morning I noticed that all the exercises were, in fact, available. There are still some items in the menu grayed-out, but those are topics & tutorials that have only video content, as observed by @cpauya.

**Comment by MCGallaspy** [comment]
This is not an issue in the application, but rather the windows installer.

**Comment by MCGallaspy** [comment]
See: https://github.com/learningequality/installers/issues/123
