### ISSUE TITLE
Error starting kalite service

### ISSUE THREAD

**Issue by waltonrp** [learningequality/ka-lite#4193]
Any thoughts on this?

This error came up after download of assesment data:

KeyError: "There is no item named 'assessmentitems.json' in the archive"

After install, I got this error on two servers running Ubuntu 15.04:

[sudo] password for aguila: 
aguila@LUCC-KALITE:~/ka-lite$ sudo service kalite start
[sudo] password for aguila: 
Job for kalite.service failed. See "systemctl status kalite.service" and "journalctl -xe" for details.

aguila@LUCC-KALITE:~/ka-lite/scripts$ systemctl status kalite.service -l
● kalite.service - LSB: ka-lite daemon, a local Khan Academy content server
   Loaded: loaded (/etc/init.d/kalite)
   Active: failed (Result: exit-code) since Thu 2015-07-30 06:34:33 EDT; 1min 13s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1153 ExecStart=/etc/init.d/kalite start (code=exited, status=203/EXEC)

Jul 30 06:34:33 LUCC-KALITE systemd[1]: Starting LSB: ka-lite daemon, a local Khan Academy content server...
Jul 30 06:34:33 LUCC-KALITE systemd[1]: kalite.service: control process exited, code=exited status=203
Jul 30 06:34:33 LUCC-KALITE systemd[1]: Failed to start LSB: ka-lite daemon, a local Khan Academy content server.
Jul 30 06:34:33 LUCC-KALITE systemd[1]: Unit kalite.service entered failed state.
Jul 30 06:34:33 LUCC-KALITE systemd[1]: kalite.service failed.

**Comment by aronasorman** [comment]
Hi @waltonrp, can you retry the installation of the assessment zip again? I think I fixed the issue now. You can try it again by running the `setup` management command:

`bin/kalite manage setup`

**Comment by waltonrp** [comment]
aronasorman, ur the man! Thanks, resolved
