### ISSUE TITLE
Allow JS browserify modules to be loaded from any app in INSTALLED_APPS

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#4195]
On the latest develop (0.15), JS modules are only loaded from a specific set of folders. It would be most flexible to be able to have them load from any app folder for apps in `INSTALLED_APPS`. An example of traversing these folders can be found here: https://github.com/learningequality/ka-lite/blob/4f674ac2470cc2808207c7b3e50c15f4b3c9aa82/python-packages/fle_utils/handlebars/loader.py

**Comment by rtibbles** [comment]
Punting.

**Comment by benjaoming** [comment]
We took the inspiration from this and implemented in Kolibri, well done everyone :)
