### ISSUE TITLE
Unable to run "bin/kalite manage setup" on Windows

### ISSUE THREAD

**Issue by jtamiace** [learningequality/ka-lite#4198]
OS: Windows 8.1 

This error occurs for environment setup.
The command tries to write dubbed_video_mappings.json into a 'locale' folder, which doesn't exist.

**Comment by aronasorman** [comment]
Branch @jtamiace?

**Comment by jtamiace** [comment]
develop

**Comment by rtibbles** [comment]
Dupe of #4796 - closing this as other issue has more context.
