### ISSUE TITLE
User menu fails to load

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4201]
**Branch**: develop

**Current Behavior**: I've been bumping into this error every now and then, without being able to pinpoint the trigger. Page loads, but without the user menu (`Learn`, ``Sìgn in`...). It usually reappears after reloading and/or restarting the server, but here is the Console screenshot if it can help to figure out the "why":

![no-user-menu](https://cloud.githubusercontent.com/assets/1457929/9035160/af5c392e-39d5-11e5-876a-9493e83d4163.png)

**Comment by radinamatic** [comment]
This now happens almost every time I restart the server, and I need to refresh the page at least a couple of times to get the user menu items to appear.

**Comment by radinamatic** [comment]
Today I wasn't able to load the 'develop' branch at all:

![screenshot from 2015-08-06 15 43 26](https://cloud.githubusercontent.com/assets/1457929/9112956/505b953a-3c52-11e5-9be3-bc5293cf40cd.png)

Seems that the `es.js` takes the longest to load. @aronasorman

**Comment by radinamatic** [comment]
If I try to access from another machine in the network:

![no-menu2](https://cloud.githubusercontent.com/assets/1457929/9113059/ba415ed0-3c52-11e5-8775-48751afd431e.png)

**Comment by radinamatic** [comment]
Finally managed to load the menu, although 10 seconds sounds a lot to me... :(

![screenshot from 2015-08-06 16 01 39](https://cloud.githubusercontent.com/assets/1457929/9113353/72c018d8-3c54-11e5-8d8b-fd7aee0524ed.png)

**Comment by radinamatic** [comment]
Load from another networked machine takes 3 times longer:

It does seem to be waiting for the `es.js` file:

![long-load](https://cloud.githubusercontent.com/assets/1457929/9113510/5373a14c-3c55-11e5-8681-65581ef698bd.png)

![long-load2](https://cloud.githubusercontent.com/assets/1457929/9113553/894aa2e8-3c55-11e5-9234-02ca67d3c060.png)

**Comment by aronasorman** [comment]
Note: `es.js` should be cached after the 1st load, so it shouldn't take this long on subsequent page loads.

**Comment by radinamatic** [comment]
Non extant on 0.16, closing!
