### ISSUE TITLE
ReferenceError: ExerciseParams is not defined - when opening exercises

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4202]
**Branch**: develop  

**Current Behavior**: Trying to open an exercise (which is probably not available) as a Learner user from the contentrec page gives me `ReferenceError: setGetParamDict is not defined` and `ReferenceError: ExerciseParams is not defined`:

![exerciseparams](https://cloud.githubusercontent.com/assets/1457929/9063192/9b2bb0d2-3ac6-11e5-81ec-53d8ee928231.png)

I'm not sure if it's related to #4157 which still needs some work.

**Steps to reproduce**:

1. Log in as Learner.
2. Try to open an exercise from the content recommendation.

**Comment by EdDixon** [comment]
This info may help, on the latest develop MAC installation I can not replicate the issue when logged in as a learner?
![2015-08-04_09-09-57](https://cloud.githubusercontent.com/assets/4349806/9064297/1a87845c-3a89-11e5-8ad7-0896c9009a2b.png)

**Comment by radinamatic** [comment]
At one point I even got this scary message, `Cannot find module 'learn'`... :disappointed: 

![no-module-learn](https://cloud.githubusercontent.com/assets/1457929/9068370/69f9dc7e-3ae3-11e5-961b-b7781f0aaeb1.png)

**Comment by radinamatic** [comment]
Long gone... :)
Closing.
