### ISSUE TITLE
api.js -- handleFailedAPI callback problematic

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4203]
It's possible for the error callback of a jqxhr object to be called even is the response's status is 200 -- in particular if there's a parse error.

That makes this snippet from `api.js` problematic, if the response content type is HTML (when it expects JSON):

``` js
var error_msg = sprintf("%s<br/>%s<br/>%s", resp.status, resp.responseText, resp);
messages = {error: sprintf(gettext("Unexpected error; contact the FLE with the following information: %(error_msg)s"), {error_msg: error_msg})};
```

All the HTML will be printed out in the error bubble, which we've seen in several different issues now. It's possible to reproduce this using Backbone.Models by setting the url attribute to an endpoint which serves HTML, but the fastest way to see what's happening is to try this in the console on the learn page:

``` js
$.ajax({ url: "#", dataType: "json" }).done( function() { console.log("success"); }).fail( function() { console.log("failure"); });
```

Note the problem is the `dataType` header is being set to `json` when `html` is returned. Changing `dataType` to `html` will call the success callback.

There's a couple of ways to handle this:
1) In our views, reject requests with the wrong dataType header.
2) In `api.js`, handle `parseerror` separately from other error types.

The first one is more explicit but will probably require more work -- it's also possible that some existing features rely on this weird behavior. For the second one will be pretty quick to implement, but seems to address the symptom rather than the cause. By which I mean there's the possibility that we will handle some future, unrelated parseerror incorrectly.

@rtibbles @aronasorman @jamalex thoughts on this?

**Comment by benjaoming** [comment]
I'm not sure I understand this... Why would a supposed json view return status 200 and html contents?

**Comment by MCGallaspy** [comment]
It wouldn't. But as I've noted, several bugs we've seen now had been making an ajax request to endpoints which returned html.

**Comment by benjaoming** [comment]
I think the good thing to do would be to handle the parse error and not to have server-side checks for data type... but the client-side should preferably blow up in a very explicit manner if it gets 200 + html for a json view.

**Comment by MCGallaspy** [comment]
> but the client-side should preferably blow up in a very explicit manner if it gets 200 + html for a json view.

What are you suggesting, then?

**Comment by benjaoming** [comment]
> All the HTML will be printed out in the error bubble, which we've seen in several different issues now.

Is it a problem then because it isn't escaped? Maybe the error bubble should have a textarea and do something like textarea.value = resp.responseText

**Comment by MCGallaspy** [comment]
Escaping the html isn't the problem -- first of all a request which accepts JSON should not have a 200 response to a view which returns only HTML. We can try to carefully avoid making such requests, but it's happened before and it's bound to happen again. Therefore either the server should reject such requests, or the front-end code should handle a request/response content type mismatch. (It currently does not.)

I'm hoping to either get a consensus that the server should handle this, or if not then suggestions on the best way to handle it on the front end.

**Comment by benjaoming** [comment]
If you think that the main problem is that we accept the wrong request types, I think that's a good one to go for... it doesn't sound like a difficult refactor, on the other hand it sounds like it has caused lots of annoyance.

Beware that there exists a sort of polymorphism in django views where a view can do something like:

    if request.is_ajax():
        return HttpResponse(json.dumps([]), content_type="application/json")
    else:
        return render_to_response("template.html", {})

**Comment by MCGallaspy** [comment]
I was just thinking about this due to a similar issue I encountered in 0.14. Definitely would be nice to have, if we think explicit is better than implicit.

**Comment by benjaoming** [comment]
Did a related change in #5403 by removing some magic JsonToHTML middleware (active with `DEBUG=True`).

But moreover, #5308 added some pretty nifty error handling.

![screenshot from 2017-04-07 17-05-51](https://cloud.githubusercontent.com/assets/374612/24806234/77539b54-1bb4-11e7-8c91-b8b9dc92ce98.png)
