### ISSUE TITLE
Unnecessary link `Back to facilities` in Learner page.

### ISSUE THREAD

**Issue by djallado** [learningequality/ka-lite#4210]
**Branch**: 0.14.x

**Expected Behavior:** `Back to facilities` link would not be in learner's page.

**Current Behavior:** There's an alert message when clicking the link `Back to facilities`.

**Steps to reproduce:**

1. login as `Admin`.
2. Create `Learner's` account.
3. logout as `Admin`.
4. login as `Learner`. 
5. Do some exercises.
6. Click Learner account tab then click `My Progress` menu.

![screen shot 2015-my-progress](https://cloud.githubusercontent.com/assets/8664071/9109906/f218bc5e-3c6b-11e5-84a7-5ddcafe61c08.png)
7. Click on `Back to Facilities` link.

![screen shot 2015-back-to-facility](https://cloud.githubusercontent.com/assets/8664071/9109909/00c08b06-3c6c-11e5-817b-efc160a08985.png)

There's a Alert message prompting the user like in the snapshot below:

![screen shot 2015-error-final](https://cloud.githubusercontent.com/assets/8664071/9109980/7ff9b29e-3c6c-11e5-8001-465f5237ec44.png)

@EdDixon. I tested this using the source `0.14.x` milestone.

**Comment by radinamatic** [comment]
Filed the issue for that a while back (#3927), and there's a PR too (#4086).
