### ISSUE TITLE
Network loading times

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4211]
Network loading times

**Branch**: develop

**Current Behavior**: Recently I've changed my setup, and I'm running the server from my repo on Ubuntu laptop, and doing the a11y & screen reader testing on a networked PC. I've noticed some, to me at least, long loading times, some are described in #4201, but maybe it's better to open a separate issue.

Spanish is the default language, and I can't change it and test the English version because of another issue (#4135). 

Load time on server averages 10 seconds: 

![screenshot from 2015-08-06 16 42 47](https://cloud.githubusercontent.com/assets/1457929/9114690/684b104a-3c5b-11e5-8e12-61a394d99a8b.png)

Load time on a networked client goes from 20-30 to a whopping 60 seconds!
(screenshot coming!)

**Comment by radinamatic** [comment]
Loading sidebar on the networked PC:  

![long-load3](https://cloud.githubusercontent.com/assets/1457929/9114882/7073112c-3c5c-11e5-9b0a-06bac202496f.png)

**Comment by radinamatic** [comment]
Trying to download videos from the networked clients - there may be some process that goes on and on here by design, but just loading the topic tree took more than 60 seconds (is that fetched from the central server?):

![long-load4](https://cloud.githubusercontent.com/assets/1457929/9114998/1c03c36a-3c5d-11e5-9936-4e65e59910dc.png)

**Comment by aronasorman** [comment]
That huge `es.js` is probably the culprit. I'll mark this as a bugfix and not a blocker (since this happens in 0.13), but will be my priority once we have a release.

**Comment by radinamatic** [comment]
Great, let me know if I can help in any way!

**Comment by aronasorman** [comment]
Fixed in https://github.com/learningequality/ka-lite/pull/4278.

**Comment by radinamatic** [comment]
I know this is closed, but I just wanted to give you guys (@aronasorman) a big :+1: for fixing it!
Now it runs and purrs... :heart_eyes_cat: :heart_eyes_cat: :heart_eyes_cat:
