### ISSUE TITLE
Video sizes & quality

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4214]
Video sizes & quality

**Branch**: Windows installer @MCGallaspy complied today (so technically 0.14.x), but I don't think it's the installer issue per-se, and therefore I'm filing here. 

**Current Behavior**: While testing I downloaded the 2 videos from `Arithmetic > Intro to Addition & Subtraction` and I was surprised that the size reported before the download started was 26Mb, since I remember it being smaller, probably by half, all the other times (and trust me, I did download those 2 **numerous** times :P ).

However, once I tried playing them, they appear to be super-compressed, or more like one of those first examples of vectorized videos @jamalex posted months ago:

![low-res-video2](https://cloud.githubusercontent.com/assets/1457929/9125317/de719610-3c9f-11e5-8842-b912226f859d.png)

![low-res-video](https://cloud.githubusercontent.com/assets/1457929/9125321/ec40205e-3c9f-11e5-8b7d-afdbfed02948.png)

So this may not be a problem, but just me being unaware that those "vectorized" and/or super-compressed versions were in production, a part from their **size being ill-reported** in the `Manage` interface page: those two visually do appear very low-quality and can't possibly weigh 26Mb.

**Comment by radinamatic** [comment]
On another hand, regarding this same installer, there is still no way to have the interface, exercises and subtitles working in Spanish, so all the i18n fixes have not been merged. 

And even if the problem is that current production central servers don't have functional language packs for 0.14 (as @aronasorman explained in #4186), that would be, IMHO, **central-server-release-blocker**, as it (I imagine) concerns all localized versions, not only Spanish.

**Comment by MCGallaspy** [comment]
@jamalex video file sizes are only an estimate, right? As for the low-quality videos, I wasn't able to reproduce that on Windows 8, using the same installer. Anyone have any insight as to why that might happen? For localization stuff, let's re-open that issue.

**Comment by radinamatic** [comment]
Here is the screenshot on my Windows 8 (fresh KA Lite install with the bug bash doc installer, and just downloaded both videos again):

![fireshot capture - learn_ basic addition i ka lite_ - http___127 0 0 1_8008_learn_khan_mat](https://cloud.githubusercontent.com/assets/1457929/9143115/a551b0ae-3d44-11e5-9208-06068a48d3f0.png)  

File name is AuX7nPBqDts.mp4, and is less than 6Mb on my drive (C:\Users\Radina\.kalite\content folder).

**Comment by radinamatic** [comment]
I'm still seeing this "crappy" quality video on 0.16.5, but that must be something on KA side, so I'm closing here!

**Comment by jamalex** [comment]
Yep, KA still has a few early videos that haven't been redone; the "basic {addition,subtraction}" ones are examples of that:
https://www.khanacademy.org/math/arithmetic/addition-subtraction/basic-addition/v/basic-addition
