### ISSUE TITLE
Topic tree errors for dubbed Danish videos 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4226]
**Branch**: 0.14.x on Ubuntu (not a release blocker IMHO), I'll review what happens on develop  

**Current Behavior**: I downloaded the first 2 dubbed available videos in the Math > Arithmetic category and it should have been the topic **Subtracting withing 1000**:

![opdater videoer ka lite - chromium_026](https://cloud.githubusercontent.com/assets/1457929/9213133/c3849f5c-408f-11e5-8eed-a4f2956ad0a7.png)

However, once I opened them, something seemed wrong. Granted my understanding of Danish is rudimentary, but these 2 do not seem to talk about subtraction:

![learn fratraekning omgruppering to gange ka lite - chromium_025](https://cloud.githubusercontent.com/assets/1457929/9213165/13707c70-4090-11e5-9e71-fb0a63f0d5e7.png)

![learn fratraekning tre-cifrede tal og grundlaeggende omgruppering ka lite - chromium_027](https://cloud.githubusercontent.com/assets/1457929/9213194/5ce21170-4090-11e5-9869-72d5be1f4c85.png)

It should have probably been these two:

https://da.khanacademy.org/math/arithmetic/addition-subtraction/sub_borrowing/v/basic-regrouping-or-borrowing-when-subtracting-three-digit-numbers

https://da.khanacademy.org/math/arithmetic/addition-subtraction/sub_borrowing/v/regrouping-twice-when-subtracting-three-digit-numbers

Not sure if I can do any any more debugging at this point, so I leave it to @benjaoming & @aronasorman to assign the proper milestone.

**Comment by benjaoming** [comment]
@radinamatic that seems spot on, looks like the videos don't match the titles and the descriptions. The ones you link to are correct.

I would be a bit cautious... what if this one find indicates more similar problems? @rtibbles you have any insights about this, do we need to rebuild a language pack and then it works?

**Comment by rtibbles** [comment]
This seems to be an issue with the video mapping code - which takes the youtube id associated with the English video, and maps it to the youtube id for the other language video.

Currently, I believe this comes from a spreadsheet that we get from Khan Academy (that is no longer being updated, @aronasorman?). We could, in future, get this data from the API instead, but that would remove our ability to support unofficial languages.

@aronasorman would probably have a better idea of possible break points here.

**Comment by benjaoming** [comment]
Are the youtube id's in question part of the language pack ? I.e. can we release and fix this after if it's relevant?

**Comment by benjaoming** [comment]
Is there an issue already open about pulling in video mappings directly from the API?

**Comment by radinamatic** [comment]
I don't recall seeing one, so we might as well open it.

**Comment by aronasorman** [comment]
@radinamatic since it's a central server issue, please open it [there](https://github.com/fle-internal/ka-lite-central/issues).

**Comment by radinamatic** [comment]
Danish is not available atm, so I can't check if this is still extant. @aronasorman Will Danish be available in 0.16?

**Comment by radinamatic** [comment]
Non extant on 0.16.5 anymore, closing!
