### ISSUE TITLE
Standard method for returning messages to be displayed in browser along with JSON responses

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#424]
It would be cool to have a standard method for sending messages back to be displayed in the browser, along with any JSON response, and have `doRequest` pick up on these and display them. This could be used by the "status" API request, for displaying the queued messages (currently the only way messages get to the browser), and also by other API calls to add things to be displayed, on demand (e.g. error messages or the result of an operation.

**Comment by rtibbles** [comment]
This happens now.
