### ISSUE TITLE
Hiding large tabular report takes... an amount of time that is indistinguishable, in practical terms, from forever

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#4244]
Loading a tabular coach report with quite a few cells, and then clicking the "Hide Tabular Report" button, hangs the page for me.

Looking into the stack trace, it looks as if it might be because we remove the view, which then recursively removes all subviews, which then removes their DOM elements one by one, which causes a cascading sequence of page reflows.

Possible solution: remove top-level element (via `Backbone.View.prototype.remove.call(this);`) before doing the recursive subview removal, in `BaseView.remove`.

Temporary solution: hide the "Hide Tabular Report" button?

**Comment by rtibbles** [comment]
Ouch. I guess we should just use react instead.

**Comment by rtibbles** [comment]
Yep, @jamie fixed in #4253

**Comment by rtibbles** [comment]
Apologies @jamie - I meant @jamalex.

**Comment by jamie** [comment]
@rtibbles no problem, I get one or two mis-PMs a month, it's no big deal :)
