### ISSUE TITLE
Behave-ify Control Panel Browser Tests that fail on Circle

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#4249]
Several tests fail on Circle CI but complete just fine on local machines.

These were commented out in #4239 but should be reinstated as they test useful functionality.

**Comment by benjaoming** [comment]
I'll solve this by quickly checking if commented out tests are working now, otherwise removing the code that was commented out.

**Comment by benjaoming** [comment]
Fixed in #5433
