### ISSUE TITLE
Demo server message overload madness

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#4251]
Upon first loading the new 0.14 demo server, three messages are shown at the top of the page, and two of them are duplicates:

![image](https://cloud.githubusercontent.com/assets/618416/9321758/5a4c8006-451f-11e5-83c0-4af77d9f4bc2.png)

After creating a user, there are 4 messages. Then, after signing in, we're faced with the following:

![image](https://cloud.githubusercontent.com/assets/618416/9321772/7d9f85da-451f-11e5-943e-02da52c768de.png)

**Comment by benjaoming** [comment]
At least they're not error messages :)

**Comment by aronasorman** [comment]
Fixed in #4267.
