### ISSUE TITLE
Fixes needed on the "installation" page in the docs

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#4258]
Based on http://field.learningequality.org/docs/0.14/en/installguide/install_main.html (looks identical, in terms of the things I'm mentioning here, to the develop version).

- [x] PPA and pip instructions, and the "advanced topics" stuff, should move to a separate advanced page (and not show up on this main installers page), as discussed previously with @benjaoming 
- [x] OSX installer needs to point to something like https://learningequality.org/r/osx-installer-latest rather than disney.com
- [x] Primary Debian installation instructions should point to https://learningequality.org/r/deb/ka-lite-bundle/0.14
- [x] Raspberry Pi instructions need to be similarly updated (CC https://github.com/learningequality/ka-lite/issues/4082)
- [x] "KA Lite is currently not supported on Internet Explorer version 8 or lower. You must use IE9 or later." should be changed to mention that essentially any version of Chrome, Firefox, or Safari should work fine too. We've had people email asking why they can only use IE.

**Comment by MCGallaspy** [comment]
> OSX installer needs to point to something like https://learningequality.org/r/osx-installer-latest rather than disney.com

Yes, what is the link for the latest OSX installer? Do you know @aronasorman?

It seems also the windows installer link learningequality.org/r/windows-installer-latest needs to be updated to point to the latest window installer. How can I upload the installer (which is currently on field) to the homepage server? The admin interface?

**Comment by MCGallaspy** [comment]
> OSX installer needs to point to something like https://learningequality.org/r/osx-installer-latest rather than disney.com

It seems you were viewing an outdated version of the docs.

**Comment by jamalex** [comment]
> Yes, what is the link for the latest OSX installer? Do you know @aronasorman?

We should have it point to https://learningequality.org/r/osx-installer-latest or https://learningequality.org/r/mac-installer-latest, which can then be configured to point to the latest version of the docs.

> It seems also the windows installer link learningequality.org/r/windows-installer-latest needs to be updated to point to the latest window installer. How can I upload the installer (which is currently on field) to the homepage server? The admin interface?

The files under /downloads/ are on the `pantry` server, which it looks like you should have SSH access to (according to the Ansible scripts). Windows installer should go in `/var/www/downloads/ka-lite/0.14/installers/windows`. We'll want to keep using a consistent naming scheme (that includes the LONG_VERSION).

(Long-term, the build box will be uploading this directly itself, rather than us uploading it, but for now you should be able to scp the file in manually)

**Comment by aronasorman** [comment]
Ah yes. I updated the link in the docs yesterday. I'll update it again with the redirect.

**Comment by jamalex** [comment]
@aronasorman You were going to look into renaming the OSX installer into something more standardized too, right?

**Comment by jamalex** [comment]
(right now the file has no version number in it -- and no need to have "monitor")

**Comment by aronasorman** [comment]
re: link update -- i'm piggybacking on to this PR: https://github.com/learningequality/ka-lite/pull/4256/files#diff-6000842a6e786a18dda39ef8736f9d26R10

re: installer versioning: Yup, already uploaded a new one yesterday with the correct name : https://learningequality.org/downloads/ka-lite/0.14/installers/mac/KA-Lite-0.14.0-beta3.dmg

**Comment by aronasorman** [comment]
Although internally it's still named KA-Lite-Monitor.app -- but it might be good to push that off for now.

**Comment by benjaoming** [comment]
@MCGallaspy @jamalex I changed the link in the issue / docs to `https://learningequality.org/r/deb/0.14` -- we should pin the major version in the URL, otherwise we'll have 0.14 documentation builds pointing to a 0.15 release in the future.

Could you make sure something like that is implemented and ping me about the final URL ?

**Comment by benjaoming** [comment]
Furthermore, @jamalex @MCGallaspy IMO it's important that people receive the file with the exact same name it was given by the PPA builders, e.g. `ka-lite-bundle_all_0.14~b3-0ubuntu1.deb`.

**Comment by benjaoming** [comment]
@jamalex and @MCGallaspy since there are several versions of the .deb, I'm going to make yet another suggestion for the URL scheme:

https://learningequality.org/r/deb/ka-lite-bundle/0.14
https://learningequality.org/r/deb/ka-lite-raspberry-pi/0.14

As you can see, I put the package name in the URL.

**Comment by MCGallaspy** [comment]
> we should pin the major version in the URL, otherwise we'll have 0.14 documentation builds pointing to a 0.15 release in the future.

Yes, that's a good point. We can create redirects like `/r/windows-installer-0.14` (in addition to `/r/windows-installer-latest`.

**Comment by benjaoming** [comment]
@MCGallaspy 
I don't know who manages to code for the site, but ideally we have a URL structure like

    /r/os-platform/package-name/version/

So we can count statistics on OS, package, and version separately.

But I guess the `/r/` is a generic redirect view that only accepts one slug?

**Comment by benjaoming** [comment]
But yeah, to get 0.14 out ASAP, let's just make something that works for now by adding the version in the slug :)

**Comment by benjaoming** [comment]
@MCGallaspy @aronasorman just a reminder that I've put another set of broken "latest" URLs in the docs... the need to be non-fiction :)

**Comment by benjaoming** [comment]
Closing since everything has be ticked!
