### ISSUE TITLE
Replace "------" option for dropdown selections

### ISSUE THREAD

**Issue by wangguan59** [learningequality/ka-lite#426]
Most "-----" were placeholder for quick hack. This should be replaced by a better phrase depends on different contexts. For example, this following ---- would be replace by "Select a facility"
![screen shot 2013-08-08 at 1 43 26 am](https://f.cloud.github.com/assets/1319955/930257/c46a647c-0006-11e3-904a-f76c6d4601ae.png)

For some situation, we should make this header be unselectable, which could avoid some error if we require the user must choose an option.

Be aware that some of "----" are for "ungroup" option because not every user have a group, e.g. individual user

**Comment by rtibbles** [comment]
Only extant for Group selection now, and that is needed to provide a blank option.
