### ISSUE TITLE
Remove dependency on dateutil

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4266]
It's 3,764 lines of code we don't really use. See #4264.

**Comment by benjaoming** [comment]
It also has its own individual license, so removing it will simplify the legal mumbo jumbo, too :)

**Comment by rtibbles** [comment]
Fixed in #4264

**Comment by benjaoming** [comment]
Actually not quite, it's only been unbundled, still in requirements.txt sorry about the confusion... I don't think it should be terribly hard to remove.

**Comment by rtibbles** [comment]
Should be removable, coachreports uses datetime for date parsing, so if we are a little more careful in formatting dates on the frontend, we can probably get rid of this.

e.g. https://github.com/learningequality/ka-lite/blob/develop/kalite/coachreports/api_views.py#L93

**Comment by benjaoming** [comment]
Usage of dateutil might also require figuring out exactly what tastypie wants from it. I'm going to throw the towel on this.

```
kalite/packages/dist/tastypie/fields.py
4:from dateutil.parser import parse

kalite/packages/dist/tastypie/utils/formatting.py
9:# Try to use dateutil for maximum date-parsing niceness. Fall back to
12:    from dateutil.parser import parse as mk_datetime

kalite/packages/bundled/fle_utils/chronograph/models.py
7:from dateutil import rrule
45:            '<a href="http://labix.org/python-dateutil" target="_blank">rrule '

kalite/updates/api_views.py
4:import dateutil.parser
50:                start_time = make_naive(dateutil.parser.parse(request.GET["start_time"]), get_current_timezone())

kalite/main/models.py
10:from dateutil import relativedelta

kalite/facility/api_resources.py
2:from dateutil.tz import tzlocal

kalite/control_panel/views.py
4:import dateutil
471:        period_end = dateutil.parser.parse(period_end)
472:        period_end = period_end + dateutil.relativedelta.relativedelta(days=+1, microseconds=-1)
```
