### ISSUE TITLE
Add favicon to our docs page

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#4271]
![image](https://cloud.githubusercontent.com/assets/191955/9393711/64d11ce2-4738-11e5-8128-5fb14e5540b7.png)

Some of us might have lots of tabs in our browser. With such a condition I can't tell offhand which tabs have the docs page:

![image](https://cloud.githubusercontent.com/assets/191955/9393721/7f7c0386-4738-11e5-8961-2356c96c56bc.png)

So I propose we have a favicon. Because favicons solve everything.

@66eli77 can you design a favicon with some kind of indicator that it's the documentation for KA Lite?

**Comment by 66eli77** [comment]
sure thing

**Comment by 66eli77** [comment]
<img width="182" alt="screen shot 2015-08-21 at 11 00 25 am" src="https://cloud.githubusercontent.com/assets/5577205/9415385/d96977aa-47f3-11e5-8465-0a1f1627466e.png">

**Comment by 66eli77** [comment]
@aronasorman  I introduce the new kolibri design elements to this favicon, so it can be used at both kalite and kolibri ('K').  I cannot upload .ico format here, let me know if you want to use this one.

**Comment by MCGallaspy** [comment]
@66eli77 looks great, please email the resource to me

**Comment by aronasorman** [comment]
Has this been fixed?

**Comment by MCGallaspy** [comment]
Not yet.

**Comment by 66eli77** [comment]
@MCGallaspy  did you get my favicon email?

**Comment by aronasorman** [comment]
Has this been done @MCGallaspy ?

**Comment by MCGallaspy** [comment]
No, since the question of where to host the docs was under consideration. Now since it's on RTD it uses the RTD favicon. Not sure if we can override their theme to include our own, I'll check it out.
