### ISSUE TITLE
Need to add get_uuid to ContentLog to make initial id predictable across devices

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#4273]
We add a `get_uuid` method to syncable models that might be created in parallel on multiple devices, so that they receive an ID that is consistent and predictable on the basis of their `unique_together` fields, to avoid ending up with duplicate records that violate the uniqueness (instead, as they have identical IDs, they will be merged).

Examples:
https://github.com/MCGallaspy/ka-lite/blob/d4903ed95c84e652fdca6e61528c856db52ca861/kalite/main/models.py#L82
https://github.com/MCGallaspy/ka-lite/blob/d4903ed95c84e652fdca6e61528c856db52ca861/kalite/main/models.py#L174

We need to add these to the `ContentLog` and `ContentRating` models, and I would suggest code such as:

```
    def get_uuid(self, *args, **kwargs):
        namespace = uuid.UUID(self.user.id)
        hashtext = ":".join([c.__class__.__name__, self.content_source, self.content_kind, self.content_id])
        return uuid.uuid5(namespace, hashtext.encode("utf-8")).hex
```

## Checklist
- [ ] `ContentLog` has `get_uuid`
- [x] `ContentRating` has `get_uuid`
- [x] Look through to see whether this would be needed for any other models

**Comment by rtibbles** [comment]
Fixed in #4451
