### ISSUE TITLE
i18n js files are massive and slow to load

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#4276]
es.js is like... 40MB, is it? Takes several minutes to load the page on the Pi.

When pulling translations from KA, we should only put strings into the JS i18n files that will be used on the frontend. Most of them are only used on the backend.

This is a blocker for i18n on the Pi.

**Comment by benjaoming** [comment]
PR merged and approved, closing this then!

**Comment by benjaoming** [comment]
...otherwise maybe reopen and change milestone if there's still room for improvement.
