### ISSUE TITLE
faq-question-bittorrent seems to be outdated or incomplete

### ISSUE THREAD

**Issue by ewann** [learningequality/ka-lite#4277]
I reviewed https://learningequality.org/ka-lite/faq/#faq-question-bittorrent with the intention of seeding the latest (in fact any) version of KA Lite. 

I step through the btsync install process, but eventually I face the approval issue that seems to be described by Jamie Alexandre at: https://groups.google.com/a/learningequality.org/forum/#!topic/dev/DIVbQATtdV8

I was able to start seeding using:

rtorrent https://learningequality.org/downloads/ka-lite/0.14/content/ka-lite-0.14-resized-videos.torrent

(as an aside, Deluge BitTorrent Client on ubuntu 15.04 never successfully started the seed / download, but I didn't dig into that)

**Comment by MCGallaspy** [comment]
Thanks for the heads up @ewann

**Comment by benjaoming** [comment]
Hi @ewann and thanks for the report!

We now host on Read The Docs, and this is a nice reminder of why we need this sort of community-including platform for the docs :)

Btw. the torrent instructions look up to date: http://ka-lite.readthedocs.io/en/latest/usermanual/userman_admin.html#bulk-video-downloads
