### ISSUE TITLE
generaterealdata produces extremely large numbers for time spent logged in

### ISSUE THREAD

**Issue by sethachoi** [learningequality/ka-lite#4288]
When using the generaterealdata command, the logged in hours are ridiculously large (like, in the millions total), although all the other data looks somewhat reasonable. 

Steps to reproduce:
1. type bin/kalite manage generaterealdata
2. launch kalite
3. observe giant numbers

seen on current develop as of aug 25, 2015, and as early as aug 18, 2015 for certain.

**Comment by benjaoming** [comment]
Seems like it's not just the generation of data that's broken for login stats but possibly both coach report and logging as well #5157

**Comment by radinamatic** [comment]
After #4999 & #5015, I eventually stopped using the command.
