### ISSUE TITLE
Video & language pack download page broken

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4294]
On `develop`. No js errors. See attached screenshots:

![ss](https://cloud.githubusercontent.com/assets/8888020/9508184/61a07f66-4c08-11e5-8693-267298911a50.png)

![](https://s3.amazonaws.com/uploads.hipchat.com/86198/1623193/qR02fOuTi7rLzrL/ss.png)

**Comment by benjaoming** [comment]
This is possibly related to #4265 ?

**Comment by rtibbles** [comment]
Also possible, if there are no language packs available on the central server for 0.15.

**Comment by radinamatic** [comment]
This smells a bit like what I reported some time ago in #4135.

**Comment by rtibbles** [comment]
Can't replicate, please provide steps for replication.

Page loads fine, and no evidence of a request for 'icons.gif' on the Network tab.

![image](https://cloud.githubusercontent.com/assets/1680573/9613519/b3173fc8-50a0-11e5-95f9-ca721f573382.png)

**Comment by MCGallaspy** [comment]
I'll try to replicate and post the steps here.

**Comment by rtibbles** [comment]
Nevermind, found the reason I can't replicate. Submitting a fix now.

**Comment by aronasorman** [comment]
Fixed in #4330.
