### ISSUE TITLE
making the video download page more mobile friendly

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#4300]
the icons are too small for tablet user to click
<img width="500" alt="screen shot 2015-08-27 at 10 41 01 am" src="https://cloud.githubusercontent.com/assets/5577205/9528226/5d06972e-4ca8-11e5-8eed-2202ace3efa4.png">

**Comment by 66eli77** [comment]
The currently implementation uses Fancytree. For the first iteration, we can do some minor cosmetic modification on Fancytree ( http://wwwendt.de/tech/fancytree/demo/#../3rd-party/extensions/hotkeys/hotkeys.html )

**Comment by MCGallaspy** [comment]
What branch is this? `develop`?

**Comment by 66eli77** [comment]
@MCGallaspy  all branches

**Comment by 66eli77** [comment]
I opened a PR  #4358 for this

**Comment by 66eli77** [comment]
merged
