### ISSUE TITLE
Export page error for unregistered device

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4307]
On `0.15.x`.~~my branch `beautify-content-rating` (and soon `develop`?)~~ CSV export of rating data has no output when a facility is not selected -- the expected behavior is some output, either a default facility or all facilities (@jamalex any input?).

To replicate, pull that branch, create a migration and run it on the main app, log in as student and create some ratings, then log in as an admin and export the ratings from the management interface. Without a facility selected the file will be empty.

**Comment by MCGallaspy** [comment]
This is now targeting branch `0.15.x`.

**Comment by MCGallaspy** [comment]
Can't replicate, @jtamiace can you give it a shot? Just see if when you create some ratings as student, log in as an admin, and try to export them without selecting a facility, that the generated .csv file is not empty.

I suspect I was running from source with polluted static files, which may have caused some error.

**Comment by aronasorman** [comment]
Is this citical for 0.15 @MCGallaspy ?

**Comment by jamalex** [comment]
Needed for Aflatoun.

**Comment by MCGallaspy** [comment]
See above:

> Can't replicate, @jtamiace can you give it a shot?

Perhaps someone else can try?

**Comment by MCGallaspy** [comment]
Updated original comment with branch info.

**Comment by rtibbles** [comment]
Unable to replicate. Seems fine!

**Comment by 66eli77** [comment]
@MCGallaspy if you didn't register your device, meaning you zone_id is none, then you select "All" when export data, you will get an empty output file. I think many of you cannot reproduce the issue only because your device is registered.

**Comment by MCGallaspy** [comment]
@66eli77 this is on branch `develop`?

**Comment by 66eli77** [comment]
@MCGallaspy  yeah, it's also on wch branch and probably on all branches. I opened an issue for this #4668

**Comment by MCGallaspy** [comment]
Duplicate of #4668.
