### ISSUE TITLE
Add instruction for editing a content rating

### ISSUE THREAD

**Issue by jtamiace** [learningequality/ka-lite#4308]
The current ability of being able to edit one's rating directly, without clicking an edit button or going to another form is intuitive enough, but there still needs to be an indication, either visual or instructional, that it's possible to edit

**Comment by MCGallaspy** [comment]
Hmm, as I'm looking at this now my first thought was to add a little bit of text, like

> Your feedback will help us make better content for future learners! __You can change your rating at any time.__

But that will now violate the string freeze, right @aronasorman?

**Comment by MCGallaspy** [comment]
Any suggestions for visual cues that it's editable?

**Comment by MCGallaspy** [comment]
Strings unfrozen, will now do.

**Comment by rtibbles** [comment]
Fixed in #4750
