### ISSUE TITLE
Import / export management commands

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4311]
We have identified that the .kalite folder should be more portable. But it won't be entirely portable ever because it contains a database with device registration etc. So an explicit import/export management command is better.

@jamalex @aronasorman please edit the description with additional info if you like.

**Comment by aronasorman** [comment]
Based on my understanding of the 0.16 planning meeting we had, we really only want an MVP of this. Basically the only platform that actually needs this is the RPi. If that's correct then should this be in the installers repo then?

**Comment by benjaoming** [comment]
Yes, this is for 0.16. It's a universal feature for anyone wanting to replicate KA Lite across multiple platforms on their own -- or for package maintainers creating installers with preseeded languagepack/assessment items/databases etc.

**Comment by jamalex** [comment]
We do want to keep it fairly MVP, but there are several known use cases
beyond the Pi:

- Android (e.g. custom settings)
- Bundled assessment items could be unloaded through this mechanism?
- Could be a good way to get the prebuilt databases unpacked
- Custom channel needs of Aflatoun

**Comment by benjaoming** [comment]
This is a feature in Kolibri.

For KA Lite, it's not currently expected to be implemented, and keeping the issue pinned for various releases doesn't help solve it.

## Work-around

We encourage to use the following mechanism:

1. Copy your `~/.kalite` to a back-up location
2. Run `kalite manage clearuserdata`
3. Your `~/.kalite` is now portable in the sense that it contains no device registration or database with user accounts. Only the installed content packs etc. are there. You can compress the folder as a `.zip` file to be used in other deployments.
4. Copy back the ~/.kalite` folder from step 1) to have your previous functioning installation with all its user data.

**Comment by benjaoming** [comment]
Closing this because of the above reasons + workaround and because we have similar instructions in the docs.
