### ISSUE TITLE
Make kalitectl.py magically append virtualenv to KALITE_HOME

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4312]
@jamalex more discussion to follow... we need to ensure that this is a feature and not a regression for whatever purposes we are trying to satisfy :) We could add option switches for kalite that controls the behaviour... let's see! #tobediscussed

**Comment by MCGallaspy** [comment]
Could this be related to #4315?

**Comment by benjaoming** [comment]
It should mainly effect that you have issues with a mismatch between the user data's version (database schema) and the dependencies installed in the virtualenv.

```
git checkout master
workon my_kalite_0.14_env
kalite manage setup
workon my_kalite_0.15_env
git checkout develop
kalite start
```

...would probably break

**Comment by benjaoming** [comment]
Here's a suggestion for you @jamalex - Create an alias in your .bashrc:

    alias dev_kalite_015="KALITE_HOME=~/.kalite_015 bin/kalite"

Now you can run `dev_kalite_015` in your git checkout and it will use the home dir defined in the alias.

I've tested and it works like a charm:

```
➜  ka-lite git:(0.16.x) dev_kalite_015 start
Running 'kalite start' as daemon (system service)

Stand by while the server loads its data...

To access KA Lite from another connected computer, try the following address(es):
	http://10.42.0.1:8008/
	http://192.168.40.156:8008/
To access KA Lite from this machine, try the following address:
	http://127.0.0.1:8008/

Going to daemon mode, logging to /home/benjamin/.kalite_015/server.log
```

I hope it's okay to close this with the above workaround.
