### ISSUE TITLE
The learn tab takes an absurdly long time to load when using the debug server

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#4325]
It takes around 45 seconds before the sidebar loads the content. Always happens when we first load the learn tab after a server start. Doesn't happen after subsequent refreshes.

![image](https://cloud.githubusercontent.com/assets/191955/9611467/99013456-5094-11e5-8979-fa4bfb040bba.png)

Steps to reproduce:
1. Kill KA Lite.
2. Run `kalite manage runserver --settings=kalite.project.settings.dev`
3. Load the learn tab.
4. ~~Profit~~ make coffee.

**Comment by aronasorman** [comment]
90 seconds now!

![image](https://cloud.githubusercontent.com/assets/191955/9611588/54e53d16-5095-11e5-8c3c-1bcf07185522.png)

**Comment by rtibbles** [comment]
This is not a bug.

This is because the topic tree annotation happens on the fly on the first request.
