### ISSUE TITLE
Videos not displayed correctly

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4336]
On branch `0.15.x` on Windows 8, with videos in my ~/.kalite content directory from previous installation, when I log in as a learner and navigate to an available video I see this:

![ss2](https://cloud.githubusercontent.com/assets/8888020/9620440/efe5d490-50ce-11e5-8074-476b289e58cb.png)

Note how the pane containing the video is almost totally collapsed. Resizing the window results in the js error in the picture: `Uncaught TypeError: this.set_container_size is not a function` variously either from `bundle_videos.js` or `video/views.js` -- odd that both are included?

**Comment by rtibbles** [comment]
Assume this is fixed as relevant PR has been merged.
