### ISSUE TITLE
Coach reports exercise detail view inconsistently displayed

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4338]
On `0.15.x`, when viewing the detail view for exercises from the coach reports, panels with only one exercise log have a buggy display:
![ss4](https://cloud.githubusercontent.com/assets/8888020/9620594/e276cde4-50d0-11e5-8bcd-a53b77578a5e.png)

Compare to:
![ss_good_detail](https://cloud.githubusercontent.com/assets/8888020/9620607/0f86bb28-50d1-11e5-9b93-da4972e57ecd.png)

In case of one attempt, I expect the "Attempt-Status-Time-Action" subtable to have the same alignment as with multiple attempts.

**Comment by rtibbles** [comment]
Fixed in #4414
