### ISSUE TITLE
Coach reports video detail view does nothing on click

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4339]
On `0.15.x`, I navigated to the video page as student to create an attempt record (%-completion seems to have no effect here). As an admin, clicking on the corresponding item in the coach reports does not expand a detail view, despite the panel being "clickable" -- the cursor changes and there is a hover effect. It _does_ close another open detail view for e.g. an exercise, but otherwise has no effect.

Opening the console reveals the following js error: `Uncaught TypeError: Cannot read property 'meta' of undefined` from `bundle_coach_report.js`.

Edit: Expected behavior is a detail view -- but if none exists, perhaps we should make the element "unclickable"?

Double edit: Perhaps we should also describe in the documentation what to expect from the detail view for various content types?

**Comment by rtibbles** [comment]
Fixed in #4414
