### ISSUE TITLE
Text display issues on tabular report

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4340]
On `0.15.x`, this is really two separate issues.

First, long words in content titles have weird line breaks. See screenshot. Can we perhaps expand the column size to fit the longest word?

Secondly, the user's name (first + last name, not the username) overflows the row. See screenshot. Overflow is bad, scrolling seems less than ideal, and truncating names may be confusing. If the row must be fixed-height, then I suggest using smaller font size for too-large names. Otherwise I suggest expanding the height of the row.

![ss3](https://cloud.githubusercontent.com/assets/8888020/9620732/1471d1ca-50d3-11e5-86ae-fef9ebca79fb.png)

**Comment by MCGallaspy** [comment]
Exhibit B:

![ss1](https://cloud.githubusercontent.com/assets/8888020/9620768/a4e37628-50d3-11e5-9d91-f33b4647f8a3.png)

**Comment by rtibbles** [comment]
@MCGallaspy for the first issue, I think the ellipsis is probably going to be best here, with a good tooltip on hover.

**Comment by MCGallaspy** [comment]
Sounds good. What about tablets? Perhaps we can expand the column on a press or a long press?

**Comment by rtibbles** [comment]
Probably the way to go.

**Comment by rtibbles** [comment]
Actually, I don't think there is much need for the tablet feature, going by this screenshot:
![image](https://cloud.githubusercontent.com/assets/1680573/9799663/88935358-57bd-11e5-9c7c-5658670ed6e6.png)

Titles are still fairly self explanatory even without tooltips, and modifying the linking behaviour would seem to me to be more trouble than it's worth, so I'll stick with this fix.

**Comment by MCGallaspy** [comment]
Sounds good to me.

**Comment by rtibbles** [comment]
Fixed in #4414
