### ISSUE TITLE
Coach report date selector missing navigation icon

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4341]
On `0.15.x`, on the coach reports, clicking on the date selectors reveals a calendar. Where I would expect an icon to navigate months I see nothing, however there is a clickable element there (my mouse is hovering over it in the screenshot) and it does work as expected. The icon is just missing:

![ss](https://cloud.githubusercontent.com/assets/8888020/9620786/e267f9d8-50d3-11e5-80a6-4c46ae7015d8.png)

**Comment by rtibbles** [comment]
Fixed in #4414
