### ISSUE TITLE
Coach report date refresh button -- can we remove it?

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4342]
On `0.15.x`, when you change the date on the coach reports page, then the tabular report does not change -- you need to first click the refresh button next to the date range and then click the "show tabular report" button again. Can we eliminate the refresh button? I would expect the date to be updated automatically when I use the selector, without clicking the refresh button, and if the tabular report is expanded then I would expect it to be updated as well.

This is not a bug, hence the 0.16.0 milestone -- but if it's a safe change then we can consider incorporating it in `0.15.x`.

**Comment by rtibbles** [comment]
No, the query can be costly, particularly for large data sets. In addition
if the user is trying to specify a date range, then having to wait for a
long query to complete before being able to continue to set the other date
is bad UX.

I am happy to iterate on how to make it more intuitive, but it needs to at
least hold off until the user has set their desired date range, which we
can only know by user action.

**Comment by MCGallaspy** [comment]
Maybe a big indicator that there's a mismatch between the currently displayed date range and the selected date range? I'll upload a mockup eventually.

**Comment by rtibbles** [comment]
Fixed in #4414
