### ISSUE TITLE
Update coach report documentation

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4343]
We need to update the coach report documentation for 0.15. This means at least updating the screenshot as it does not include the date picker. That's blocked until we get that working again on `0.15.x`, so I'll make that a priority. We should also describe the use of the date picker, since the user flow with the refresh button may not be immediately obvious. It might be helpful to also describe what's expected in the detail view for various content types.

**Comment by rtibbles** [comment]
Fixed in #4414
