### ISSUE TITLE
Coach reports -- tabular report vertical scrolling

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4351]
On `0.15.x` using `generaterealdata --scenario-1`: When there are many attempt logs, then the tabular report scrolls vertically. This creates very wide log detail views:

![ss1](https://cloud.githubusercontent.com/assets/8888020/9642382/a9b8e6ae-5170-11e5-8368-186a92c6309e.png)

Additionally, the scroll bar at bottom of the tabular report pane is out of view when looking at the titles of the content items. I suspect this could make it not-so-obvious that it is indeed scrollable. I also wonder what effect what effect the touch-and-swipe style of scrolling will have (as with touchscreens) given that every element in the tabular report is clickable.

Finally, scrolling within the detail view of an attempt log blocks scrolling in the outer tabular report. Ideally the detail view would not be scrollable, and scrolling within it would cause the tabular report to scroll instead.

For future iterations, can we paginate the number of columns in the tabular report? Or perhaps make the tabular report searchable/filterable by content items as well? That could help to reduce the number of columns displayed at once.

**Comment by rtibbles** [comment]
Fixed in #4414
