### ISSUE TITLE
Can not download languange pack using IE11 (0.14.0 on Windows 7)

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite#4352]
During 0.14.0 Windows 7 testing the language pack failed to download using the native IE11 browser however did download using chrome. Afterwards other language packs could be downloaded from the IE11 browser.
![2015-09-02_13-28-30](https://cloud.githubusercontent.com/assets/4349806/9642645/a314d95c-517a-11e5-851b-6a0dbb3b2f17.png)
![2015-09-02_13-31-31](https://cloud.githubusercontent.com/assets/4349806/9642647/a31bdd9c-517a-11e5-8cad-ccb250236ad0.png)
![2015-09-02_13-51-31](https://cloud.githubusercontent.com/assets/4349806/9642646/a3171596-517a-11e5-895e-21bb0e318e20.png)

Screenshots show the first fail on IE11, then a download of the same language pack which did complete on chrome, then a subsequent IE11 download of another language pack on IE11.

**Comment by MCGallaspy** [comment]
Let's see if this exists on 0.15 as well, and then target a fix there. @jtamiace can you try to replicate this?

**Comment by EdDixon** [comment]
Just wanted to update this with a few more tests ran here on this same server instance which may provide some clues. So after successfully downloading the Swahili language pack I decided to try and update the English language pack which again failed with an additional warning about the connection. I then tested the connection by opening a new tab and going to google news which was successful. I think this may indicate a timeout issue within the application but not sure.

![2015-09-02_14-19-53](https://cloud.githubusercontent.com/assets/4349806/9643312/67834fbe-517e-11e5-91ba-8f347555973c.png)
![2015-09-02_14-20-18](https://cloud.githubusercontent.com/assets/4349806/9643313/6785e238-517e-11e5-8047-d3981f20d4b1.png)

**Comment by EdDixon** [comment]
Then going back to chrome logging in and navigating to the languages tab I find the process completing and eventually completed as shown here without doing anything but just navigating to the TAB (I did not restart the English language update) which now appears to be successful.
![2015-09-02_14-29-59](https://cloud.githubusercontent.com/assets/4349806/9643473/67b5c844-517f-11e5-843b-59719a634d39.png)

**Comment by EdDixon** [comment]
I did manage to replicate this issue on Windows 7 tonight by installing, creating an admin account and  and then logging into the server as admin. afterwards navigating to the languages tab and selecting the Spanish language pack and then clicking the get language pack button.
![ugh1](https://cloud.githubusercontent.com/assets/4349806/9680157/13e576c2-52b2-11e5-8d5a-990dbb24b12b.png) 
WIthout shutting down or making any changes I checking the same server instance over LAN using the chrome browser which revealed the process was still running:
![ugh2](https://cloud.githubusercontent.com/assets/4349806/9680208/67f0b01a-52b2-11e5-845d-c0a97e8107f3.png)
And it did eventually complete.

**Comment by MCGallaspy** [comment]
@EdDixon in this case, did you use one-click or long registration before downloading a language pack?

**Comment by MCGallaspy** [comment]
Does not seem to be an issue in 0.15, but worth trying in 0.14 as well.

**Comment by EdDixon** [comment]
@mike I don't think I did use the one click registration but it os too long ago to be sure I can test again both ways here?

**Comment by EdDixon** [comment]
@benjaoming this issue also happened here today after installing on Debian Stable using the dpkg -i installation method. For clarity can you confirm that we are supporting dpkg -i of the deb package in the 0.14.0 release? Somehow I was thinking we decided not to and wait to work out issues in 0.15 but the worst seem to have been resolved prior to release and it is still documented as the prefered install method? Thanks,

**Comment by benjaoming** [comment]
@ed both PPA and dpkg -i are supported, the dpkg -i is documented as the main method because that's what makes sense in offline environments.

Regarding the issue, I suspect that it's universal and not related to Win/OSX/deb.

**Comment by EdDixon** [comment]
Thanks @benjaoming I am rerunning the test now to make absolutely sure, it does not make a lot of sense to me that it wasn't encountered during the PPA installation tests on Ubuntu which went fine?

**Comment by aronasorman** [comment]
Try downloading again. Error just means a failed download.
