### ISSUE TITLE
Coach report -- struggling figures are struggling

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4353]
On `0.15.x` using `generaterealdata --scenario-1`, I'm logged in as a coach for Facility Dos, and attempt logs from that same facility are color coded correctly:

![ss2](https://cloud.githubusercontent.com/assets/8888020/9642778/02066104-5173-11e5-8572-3feb736d7ebe.png)

But viewing them for Facility One (the _other_ facility) they are not colored correctly:

![ss1](https://cloud.githubusercontent.com/assets/8888020/9642794/11fb8df0-5173-11e5-9075-9ba3d529dc06.png)

Could it be a quirk of `generaterealdata`?

**Comment by MCGallaspy** [comment]
Addendum: it's also the case when viewing Facility One's tabular report with a Facility One coach, so the problem seems to be with those specific attempt logs.

**Comment by rtibbles** [comment]
Yeah, there seem to be some issues with generate real data that is not producing realistic data...

I am confident that the display is working correctly for actual data, so I will punt this as an issue with generaterealdata for now.

**Comment by benjaoming** [comment]
I don't know how coach reports are defining "struggling" and it doesn't show anywhere in the UI.

Here's an example of something that doesn't show as struggling, even though I have registered tonnes of wrong answers :)

![screenshot from 2017-04-07 15-23-40](https://cloud.githubusercontent.com/assets/374612/24801901/3d87847a-1ba6-11e7-8390-ee955254b5e5.png)

![screenshot from 2017-04-07 15-24-13](https://cloud.githubusercontent.com/assets/374612/24801915/4a167e76-1ba6-11e7-9743-82bdf2eaa3ee.png)

**Comment by mrpau-eugene** [comment]
@benjaoming 
Seems like struggles are determined by this condition
```
 if self.attempts > 20 and not self.complete:
    self.struggling = True
```

Can someone verify if I understood what @MCGallaspy did:
1. Logged in to Facility Dos
2. Viewed tabular reports for that facility.
3. Still logged in to Facility Dos, and then viewed Facility One.

Has this issue been fixed? Tried it on 0.17 and I don't see any problems with the Tabular Reports. It displays correctly when I am logged in to `Facility Dos`, then viewed `Facility One` and vice-versa..

**Comment by benjaoming** [comment]
@mrpau-eugene 

> Addendum: it's also the case when viewing Facility One's tabular report with a Facility One coach, so the problem seems to be with those specific attempt logs.

Could you post a screenshot of your data from `generaterealdata` ? As I remember, I was failing to provoke anything "struggling", even by creating a lot of attempts, but I could be wrong.

**Comment by mrpau-eugene** [comment]
@benjaoming how did you try to make a learner `struggle`? As far as I have observed on how KA Lite handles this, if you take on an exercise, and then make your answer wrong, the attempts you made for that will increase. And if you make another wrong answer for that question, your attempts will still be the same. This continues until you get it right.

**Comment by mrpau-eugene** [comment]
>Could you post a screenshot of your data from generaterealdata ?

Logged in as a coach for Facility One, viewing Facility One:
![logged in as facility one - viewing facility one](https://user-images.githubusercontent.com/27984604/27065142-33c8ba96-502e-11e7-83d6-5d4f8e2ad413.png)

Logged in as a coach for Facility Dos, viewing Facility One:
![logged in as facility dos viewing facility one](https://user-images.githubusercontent.com/27984604/27065170-46494226-502e-11e7-88ba-108fd3de93c4.png)

**Comment by benjaoming** [comment]
@mrpau-eugene I can't see any struggling figures in those screenshots from the `generaterealdata` command ;)

Can you reproduce struggling figures manually... as you noted below I may have overlooed a condition when I tried to manually reproduce them..

> @benjaoming 
> Seems like struggles are determined by this condition
> ```python
>  if self.attempts > 20 and not self.complete:
>     self.struggling = True
> ```

**Comment by mrpau-eugene** [comment]
@benjaoming here's a screenshot which has struggling figures. Sorry bout the previous one.

Logged in to `Facility One` viewing `Facility One`
![screen shot 2017-07-06 at 4 19 51 pm](https://user-images.githubusercontent.com/27984604/27902119-20e896b2-6267-11e7-8bab-3b62bb9f1c0c.png)

Logged in to `Facility Two` viewing `Facility One`
![screen shot 2017-07-06 at 4 19 56 pm](https://user-images.githubusercontent.com/27984604/27902151-46844196-6267-11e7-850c-a1cdc3b537a5.png)




Here's the manually produced struggling figure:
![screen shot 2017-07-06 at 4 47 37 pm](https://user-images.githubusercontent.com/27984604/27903164-d9c38518-626a-11e7-899f-a66d1aa36bbe.png)

**Comment by benjaoming** [comment]
@mrpau-eugene so the two facilities are displaying the same data? In that case the original issue is gone!
