### ISSUE TITLE
Learn page -- extra whitespace on available videos

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4357]
On `0.15.x` there is a lot of whitespace below the footer on available videos _if_ you're not logged in as a learner. If the video is unavailable or if you're logged in as a learner, the whitespace doesn't appear. Unsure who to assign, @rtibbles feel free to pass the torch -- I'll even take it over if you'd like.

![ss](https://cloud.githubusercontent.com/assets/8888020/9646474/e9014dde-5188-11e5-8dc3-ebbdf065b232.png)

**Comment by jinchuika** [comment]
I'm having the same space in 0.14 

![image](https://cloud.githubusercontent.com/assets/5230176/9816963/622a7016-585d-11e5-8fcd-cd98c3ed17b2.png)

**Comment by MCGallaspy** [comment]
@jinchuika thanks for the additional info.

**Comment by rtibbles** [comment]
This is due to the way that videojs displays the thumbnails - not quite sure how to fix it at this point, but simply deleting the <img> tag that contains the thumbnail definitely gets rid of the whitespace.

**Comment by rtibbles** [comment]
Fixed in #4421
