### ISSUE TITLE
On mobile, Sidebar tab not stay in its position when scroll

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#4361]
branch: 0.15.x
![screen shot 2015-09-03 at 10 26 24 am](https://cloud.githubusercontent.com/assets/5577205/9665645/7314f9a6-5226-11e5-9037-649d42f81158.png)

**Comment by rtibbles** [comment]
Not sure I understand the issue here.

I am finding that it remains in a fixed position relative to the viewport, which is by design, so that users don't lose it when they scroll around the page - is that what you are describing?

**Comment by 66eli77** [comment]
the sidebar tab moved from the center position to near the top(half covered) as this picture shows

**Comment by rtibbles** [comment]
It is designed to go near the top, so as not to obscure the content. I am finding that it is most of the way to the top, but not all the way to the top as in your screenshot.

If it was most of the way to the top, this is intended behaviour.

**Comment by 66eli77** [comment]
closed because this behavior is intentional
