### ISSUE TITLE
Sidebar backbutton missing icon

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#4362]
branch: 0.15.x
os: Mac
browser: Chrome
suggestion: the backbutton could also be vertically centered
![screen shot 2015-09-03 at 10 29 50 am](https://cloud.githubusercontent.com/assets/5577205/9665714/d05912be-5226-11e5-9a20-04078532d6fe.png)

**Comment by rtibbles** [comment]
Platform, browser?

**Comment by 66eli77** [comment]
@rtibbles  edited the description to include Platform, browser

**Comment by rtibbles** [comment]
Like this?

![image](https://cloud.githubusercontent.com/assets/1680573/9829372/accf0e7a-58b6-11e5-873e-60410e93a2a5.png)

**Comment by 66eli77** [comment]
merged

**Comment by rtibbles** [comment]
Fixed in #4421
