### ISSUE TITLE
nothing shown on Progress Report when having 0 point

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#4364]
branch: 0.15.x
os: Mac
browser: Chrome
![screen shot 2015-09-03 at 11 29 27 am](https://cloud.githubusercontent.com/assets/5577205/9667168/11e0a60e-522f-11e5-80d1-27122cf41d9c.png)

**Comment by rtibbles** [comment]
@66eli77 Just a note that you should be running the server in production mode when doing this testing - not dev mode. The Django debug toolbar gives you away....

**Comment by 66eli77** [comment]
@rtibbles verified, under production mode, this issue is gone

**Comment by rtibbles** [comment]
@cpauya I think you said you were working on this, so heads up that it is a non-issue!

**Comment by cpauya** [comment]
Thanks for the update @rtibbles.
