### ISSUE TITLE
student progress reports when no videos under the subject, video icon should display "0"

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#4366]
branch: 0.15.x
os: Mac
browser: Chrome
no number displayed when no videos under the subject
![screen shot 2015-09-03 at 12 35 47 pm](https://cloud.githubusercontent.com/assets/5577205/9668795/7b11cdac-5238-11e5-8015-64cf6d555443.png)

**Comment by rtibbles** [comment]
![image](https://cloud.githubusercontent.com/assets/1680573/9804047/1cf66c0e-57de-11e5-803b-2f98414d3228.png)

**Comment by rtibbles** [comment]
Fixed in #4414
