### ISSUE TITLE
Content recommandation "Next Steps" show exercise I already finished

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#4369]
branch: 0.15.x
os: Mac
browser: Chrome
the "Counting in order" already finished but still show in Next Steps.
Also, the Topic and arrow icon could in different color to distinguish itself from the rest since it redirect to different place. Right now I think the whole Next Steps list item is One buttom
![screen shot 2015-09-03 at 1 01 35 pm](https://cloud.githubusercontent.com/assets/5577205/9669568/ed468f1c-523c-11e5-8e27-8b683853eeeb.png)

**Comment by rtibbles** [comment]
Is this any better?

![image](https://cloud.githubusercontent.com/assets/1680573/9829352/f6b18500-58b5-11e5-8965-7c6d0a50ef78.png)

**Comment by 66eli77** [comment]
look good, merged

**Comment by rtibbles** [comment]
Fixed in #4421
