### ISSUE TITLE
Add documentation to sdist

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4375]
MANIFEST.in.dist should include the documentation.

The debian dist is built from an sdist, so that would immediately fix it. Windows already adds it in another way.

@cpauya does the OSX installer build from a PyPi sdist or do you create an sdist with `setup.py sdist`? Because in that case, fixing this issue will likely also add documentation to the OSX installer.

**Comment by aronasorman** [comment]
Not right now, although eventually it will, so it would be good to have it working through PyPi.

**Comment by benjaoming** [comment]
@aronasorman okay but does it use the output of `python setup.py sdist` because that was my impression...

**Comment by aronasorman** [comment]
No, it does not use the `sdist` yet.

**Comment by benjaoming** [comment]
Thanks, I got the link from Cyril to the setup.sh script :)

**Comment by rtibbles** [comment]
Status?

**Comment by benjaoming** [comment]
Well, the docs (html output like the stuff on RTD) are bundled in, and part of the sdist. What's remaining now is that they are served in urls.py?

It's a waste to ship the docs without making the accessible to users. And it's not that hard to add, let this be a release blocker, I shall attend to it.

**Comment by MCGallaspy** [comment]
It's already the case. However, the link only appears in the user menu when you're logged in.

**Comment by MCGallaspy** [comment]
The docs are served as static files: https://github.com/learningequality/ka-lite/blob/0.16.x/kalite/settings/base.py#L406

**Comment by MCGallaspy** [comment]
Link is created here: https://github.com/learningequality/ka-lite/blob/0.16.x/kalite/distributed/static/js/distributed/user/hbtemplates/navigation.handlebars#L47

**Comment by MCGallaspy** [comment]
Admittedly there's probably a much better way to present it.

**Comment by benjaoming** [comment]
Maybe we can assign this to someone who will come up with a suggestion of how to refer the user to the bundled docs?

**Comment by MCGallaspy** [comment]
I'll do it.

**Comment by benjaoming** [comment]
Just a quick note: Currently, we show documentation link to learners.. that doesn't make much sense?

![screenshot from 2016-02-15 11 49 30](https://cloud.githubusercontent.com/assets/374612/13046636/330da44e-d3da-11e5-8e49-1eda66cbb463.png)

**Comment by MCGallaspy** [comment]
> that doesn't make much sense?

Who should be able to see it then?

**Comment by MCGallaspy** [comment]
My first thought is to create another tab (*a la* "Learn" or the User tab) as a top-level nav item. This can be enabled or disabled by user type.

**Comment by radinamatic** [comment]
Or maybe link the **Learner User Manual** page instead of the docs' index:
http://ka-lite.readthedocs.org/en/latest/usermanual/userman_learner.html

**Comment by benjaoming** [comment]
@MCGallaspy docs contain contents for quite different audiences, it's important to provide the right deeplinks.

IMO our User Manual is suitable for Managers and Teachers, not Learners, it's way too technical. If we want documentation for learners, it's a symptom of our whole UI being to complicated.. defeats the purpose.

If you can add a Help tab and only show it to logged-in users who aren't learners, and as @radinamatic mentions deeplink to the User Manual, that'd be sufficient IMO?

**Comment by radinamatic** [comment]
True up to the point @benjaoming. 

Our docs as a whole are pretty technical, but the [Learner User Manual](http://ka-lite.readthedocs.org/en/latest/usermanual/userman_learner.html) page is down-to-the-ground enough _(how to sign up, how to login)_. Granted maybe not for the kids learning how to count, but there is a lot of more advanced content in there (AP placement, college prep) that presume certain age and a minimum of tech-familiarity, if not "savvyness". Though I did add in my internal todo bucket, to think about the wording of the [Accessing KA Lite](http://ka-lite.readthedocs.org/en/0.14.x/usermanual/userman_learner.html#accessing-ka-lite) topic.
