### ISSUE TITLE
Topic Tree loads from the outside in with multiple API requests

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#4392]
Expected Behaviour: Sidebar should load all the data needed at once, rather than multiple API requests.

Current Behaviour: Sidebar parses each slug in the path and loads the data incrementally, rather than fetching all the data needed at once.

**Comment by 66eli77** [comment]
@rtibbles you can assign this to me if you like.

**Comment by MCGallaspy** [comment]
Do you mean that currently there is one request per sidebar entry, and the desired behavior is that _all_ visible sidebar entries are fetched in one request?

**Comment by rtibbles** [comment]
yep

**Comment by rtibbles** [comment]
Wait, no. One request per sidebar level.

**Comment by 66eli77** [comment]
did we load all the data needed at once in previous kalite?

**Comment by rtibbles** [comment]
@66eli77 previously we loaded *ALL THE DATA* at once, even stuff we *didn't* need.

What we should do here is load only the data we do need, the motivation for loading one level at a time is to make sure we show the user relevant data fast - but the way to do this is not to load the topmost sidebar level first, but the innermost one, and then fill in the others.

**Comment by rtibbles** [comment]
Also, note: this is slated for 0.17, so no need to do now timecrunch wise.

**Comment by 66eli77** [comment]
kk

**Comment by benjaoming** [comment]
This would be great to have done, but we don't seem to have any performance issues related to it. The closest I can think of is #5254 

Closing this as we are preparing to become more stable etc in the time coming :) As KA Lite works fine with this tweak, we can probably expect that it won't ever be a priority.
