### ISSUE TITLE
kalite manage setup: Detect and use prebuilt database

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4395]
To save time creating and migrating a database, we can ship a new and empty one.

 * [x] `setup.py sdist` should create a blank sqlite database
 * [x] `kalite manage setup` should detect if there is an empty database available and use it instead of running `kalite manage syncdb`. For `migrate`, it should just perform this step regardless.

**Comment by rtibbles** [comment]
Status, @benjaoming ?

**Comment by benjaoming** [comment]
Done!

https://github.com/learningequality/ka-lite/blob/0.16.x/Makefile#L91
