### ISSUE TITLE
Remove collectstatic from startup

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4401]
As per discussion on when to run `kalite manage collectstatic`, we have delegated it for `kalite manage setup` for now.

This should be a very low hanging fruit, does anyone have objections against removing it from `kaserve` where it's currently run?

        logging.info("Copying static media...")
        call_command("collectstatic", interactive=False, verbosity=0)

        call_command("collectstatic_js_reverse", interactive=False)

@rtibbles @jamalex @MCGallaspy @aronasorman @cpauya

**Comment by rtibbles** [comment]
Do we even use kaserve any more, though?

**Comment by benjaoming** [comment]
Only for confusion I guess :)

**Comment by benjaoming** [comment]
It's the `initialize_kalite` command:

        # Copy static media, one reason for not symlinking: It is not cross-platform and can cause permission issues
        # with many webservers
        logging.info("Copying static media...")
        call_command("collectstatic", interactive=False, verbosity=0)
        call_command("collectstatic_js_reverse", interactive=False)

**Comment by MCGallaspy** [comment]
It sounds reasonable to only run at setup -- with maybe the exception of running it every time when using the kalite.project.settings.dev settings module?

**Comment by benjaoming** [comment]
agreed, that's a good point about settings.dev -- but also kind of reminds
me about why runserver is cool, it will dynamically serve static files from
the applications' static dirs.

**Comment by rtibbles** [comment]
Yeah, we don't need to run collectstatic in dev mode at all.

**Comment by benjaoming** [comment]
@rtibbles but that only applies to Django's dev server, right? Not
cherrypy... anyways, we should be able to take responsibility for running
collectstatic manually, and there's all sorts of automated tools for
running it.. and it's even possible to use `collectstatic -l` which will
create links instead of copying files.

**Comment by rtibbles** [comment]
I believe that symlinking can cause permissions issues, and does not work terribly well cross platform.

**Comment by benjaoming** [comment]
@rtibbles yes I know, I'm suggesting it as a means for development so you don't have to run `collectstatic` every time you change a file.......

**Comment by benjaoming** [comment]
Fixed in #4441
