### ISSUE TITLE
Remove the RemovedInKALite_v015_Warning warning

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#4402]
![image](https://cloud.githubusercontent.com/assets/191955/9774841/fef415dc-56ff-11e5-9071-b45c93cb4d8b.png)

**Comment by aronasorman** [comment]
@benjaoming I've assigned you, but feel free to pass on the honor to someone else :dancer:

**Comment by benjaoming** [comment]
I can start work on issues I'm assigned to next week, would that be in due time?

**Comment by rtibbles** [comment]
Fixed in #4495
