### ISSUE TITLE
On page load, content rating makes 4 POST requests, 2 of which return a 400 status.

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#4407]
Branch: 0.15.x

Expected Behaviour: We shouldn't have to make any saves until something actually changes in the content rating, and all those should be well formed requests.

Current Behaviour: Content Rating attempts four saves immediately on page load, even though I have not interacted with the content rating widget at all. 2 of these attempts at saves return a 400 error from the server.

![image](https://cloud.githubusercontent.com/assets/1680573/9794411/c3365cf8-579f-11e5-97d7-f0157200a163.png)

**Comment by MCGallaspy** [comment]
Can you provide the headers or the body of the 400 requests?

**Comment by rtibbles** [comment]
Fixed in #4409.
