### ISSUE TITLE
Pages not scrolling 

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite#4413]
While testing on MAC using Chrome I seem to encounter a very intermittent issue and not one I am sure is related to KA-Lite and could be my setup here but, I have noticed that while working with some of the content both video and assessments on the MAC occasionally the pages will not scroll properly with my "magic mouse" however the up and down arrows on the keyboard will allow the page to scroll. I think I have only seen this while viewing on MAC but will be watching for this in other platforms as well.

**Comment by jinchuika** [comment]
I'm testing in Chrome on Ubuntu and the same issue is happening. The page won't scroll using the scroll wheel, mostly when watching a video.

**Comment by MCGallaspy** [comment]
Seems like a video page issue. @jamalex do you have the opportunity to address this? If not, please assign me.

**Comment by jamalex** [comment]
We've seen this on the exercises before, especially ones with draggable elements -- they absorb scroll events. I wonder whether the new version of video.js integrated does the same -- if testers could see whether it makes a difference where the mouse pointer is when trying to scroll, that'd be handy (i.e. on the video player, on the sidebar, on the page background, etc).

@MCGallaspy I won't have time for dev in the immediate future, so I'll assign to you.

**Comment by MCGallaspy** [comment]
Can you guys give some examples of exercises or videos where you encountered this issue?

**Comment by MCGallaspy** [comment]
Unable to replicate on Chrome or Firefox on Windows 8.
