### ISSUE TITLE
Add warning to test runner

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4415]
@rtibbles perhaps can explain better, but we encountered a snafu with tests passing locally and failing remotely because running `collectstatic` doesn't clear old files -- just overwrites. Should we add a warning to the test command to remind ourselves to clear the static directory from time to time?

**Comment by benjaoming** [comment]
I'm okay with this, basically, for the future, remote tests (Circle CI) will 100% decide if a PR gets merged or not.

Actually, we have gotten rid of various user data (language pack data) from STATIC_ROOT so we won't get such false positives in the future. Whatever is in STATIC_ROOT is the same as what's found by STATIC_FINDERS
