### ISSUE TITLE
 Progress bar is not working on the language pack download.

### ISSUE THREAD

**Issue by arceduardvincent** [learningequality/ka-lite#4417]
**Master:** 0.15.x

**Expected Behaviour:** Able to show the Progress bar in the language pack download page when downloading the selected language pack.

**Current Behaviour:** Progress bar is not showing on the language pack download page when downloading the selected language pack.
See image as demonstration 
![screenshot 2015-09-11 17 43 08](https://cloud.githubusercontent.com/assets/4099119/9811963/d3b98970-58ac-11e5-9bde-d306af1f9392.png)

**Steps to Replicate**
>1. Logged as Admin
>1. Navigate to `language tab`
>1. Select a language pack
>1. click `Get Language Pack` button
>1. Notice that the progress bar is not showing

**Comment by jinchuika** [comment]
My progress bar, in 0.14.0, always freezes at 16.6% and then jumps to 87% before finishing. Is this a normal behavior?

**Comment by aronasorman** [comment]
Hi @jinchuika, it's the expected behaviour right now, as the stages during language pack download aren't all the same length.

**Comment by aronasorman** [comment]
However @arceduardvincent's issue is different, as the progress isn't getting shown in the first place. Will test and confirm.

**Comment by rtibbles** [comment]
```sprintf is not defined```

Thought I had fixed this... but maybe only on develop.

**Comment by rtibbles** [comment]
Fixed, but getting these errors during actual download now:
![image](https://cloud.githubusercontent.com/assets/1680573/9830707/412275ea-58ed-11e5-9509-1e7b19849f48.png)

**Comment by aronasorman** [comment]
@rtibbles did you try downloading that here in the office? It seems our office wifi is dropping downloads halfway.

**Comment by rtibbles** [comment]
No, this was at home.

**Comment by rtibbles** [comment]
Reported issue is fixed by #4424 though, so let's close this.
