### ISSUE TITLE
(13) Allow entry of GPS coordinates into Facility add/edit form

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#442]
We have latitiude / longitude, but allow them to be entered directly and to update the map properly.  Currently they cause script errors. 
See https://support.google.com/maps/answer/18539?hl=en for proper GPS entry for Google maps.

![image](https://f.cloud.github.com/assets/4072455/943342/d59fe57e-020d-11e3-8d93-7bb768b92a8e.png)

**Comment by aronasorman** [comment]
Not a priority; reopen if it's a big UX issue.
