### ISSUE TITLE
KA Lite splash image off-center

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4432]
On `0.15.x`. I pulled this from the docs, but I've also noticed when using the app, or viewing sl screencasts. The splash image overflows it's container.

![image](https://cloud.githubusercontent.com/assets/8888020/9893486/be9ca724-5bcd-11e5-9a35-f75233fccbf3.png)

I think it's a vector asset, right? Can we resize it dynamically?

**Comment by 66eli77** [comment]
if you set the width the same as its container, it should resize correctly

**Comment by rtibbles** [comment]
Fixed in #4435
