### ISSUE TITLE
Error while uninstalling using apt-get

### ISSUE THREAD

**Issue by jinchuika** [learningequality/ka-lite#4434]
**Version**: 0.14 (master)
**Expected behavior**: trying to remove the ka-lite package (from the PPA) using the ```apt-get``` command.
**Actual behavior**: downloads and installs the *ka-lite-bundle* package.

**Steps**:
A normal uninstall in Ubuntu 14.04 using:
```apt-get remove --purge ka-lite```

I have been unable to uninstall ka-lite using this method.

**Comment by jinchuika** [comment]
I was able to uninstall the package doing the following:

```sudo ppa-purge ppa:learningequality/ka-lite```

It removed the ppa; after that I ran the `apt-get remove --purge` command and it removed the `ka-lite` and `ka-lite-gtk` packages. How ever, I had to install a third party tool (ppa-purge). Will this dependencies issue be solved in the future?

**Comment by benjaoming** [comment]
@jinchuika do you have ka-lite-gtk installed? In that case, it's because it depends on ka-lite *or* ka-lite-bundle. In case you uninstall one of them, it will fetch the other to satisfy this dependency.

Instead, try `sudo apt-get purge ka-lite-gtk ka-lite ka-lite-bundle`.

**Comment by jinchuika** [comment]
@benjaoming Exactly, I had ka-lite-gtk installed, but not the ka-lite-bundle package. When I ran the order you wrote, without the ka-lite-bundle package, I was able to uninstall both ka-lite and ka-lite-gtk.

So, it worked. Thanks.

**Comment by benjaoming** [comment]
@jinchuika cool, glad it worked and thanks for reporting back. I think this is an issue about making our docs about uninstalling better. I'll remember this for next time and try to experiment with a universal uninstallation command.

Btw. using --purge does not remove data you may have downloaded. For that, you need to locate and delete you `.kalite` folder.
