### ISSUE TITLE
Better way to specify CHANNEL setting

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4438]
This isn't a bug by a usability consideration. Since we're deprecating the user of local_settings.py, if one wishes to specify the CHANNEL setting, one has to also specify a number of derived settings (I'm looking at CHANNEL_DATA_PATH and CHANNEL_DATA).

I think the best solution is to remove derived settings into the relevant app within kalite, so that it's loaded _after_ the user's settings module. There may be other considerations in this specific case, depending on how the derived settings are used.

**Comment by MCGallaspy** [comment]
@aronasorman incidentally, despite my best efforts I'm having some trouble importing a channel for testing. Could there be other settings I'm missing? What is the recommended way to import a channel?

**Comment by rtibbles** [comment]
Fixed in #4440
