### ISSUE TITLE
User locked out / can't log in

### ISSUE THREAD

**Issue by mikewray** [learningequality/ka-lite#4439]
Hi there, this happens about once or twice a month at our centres, a user is not able to login into their account with the error message below. This problem only applies to the local device i.e. the only way I can fix this is to create a brand new database which is a pain and logistically difficult.  Otherwise the other alternative is to create a new student account but then the student loses all their past activity which causes them a lot of stress. 

It looks like the account gets locked out or something - is there a line of code I can run to unlock the account, I have their unique id string. Do you know what causes this so I can  try prevent it happening, I have not figured it out. Appreciate your help. 

![user cant login error](https://cloud.githubusercontent.com/assets/7093712/9926154/50d28172-5d13-11e5-9987-d157111667e0.png)

**Comment by MCGallaspy** [comment]
Hi @mikewray. What version of KA Lite are you using when you encounter this error?

**Comment by mikewray** [comment]
Hi, so sorry for late response - I somehow missed it. I'm on version 0.12.10, I know its an old one, was waiting for 0.13 and 0.14 to settle in - plan to migrate in a few months. Is there line of code I could run to get rid of the assertion error? Also, would be great to know what cause is so I can try avoid it in future.

**Comment by mikewray** [comment]
Hi, I think hopefully this is sorted. I was talking to Jamie and he sent me a line of syntax I can run to resolve this. It's only an issue on v12 and is fixed later. The syntax is in case anyone else has this problem is: UserLogSummary.objects.filter(user__username="loginname")[1:].delete()

Many thanks. Michael
