### ISSUE TITLE
(9a) New student view coach report

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#444]
From Johnny Long:
>The report below is similar to the existing Coach report.

>However, we can show reports by student, and by Topic. Note that each line shows video progress (colored blocks where dark green=complete, light
green=partial complete, red=watch less than 10% of video) and also a summary of the exercise scores for each section. This gives us a single view into student progress.

![image](https://f.cloud.github.com/assets/4072455/943358/dc27be42-020f-11e3-8272-9ce4734bfc5c.png)

**Comment by rtibbles** [comment]
Student progress reports implemented.
