### ISSUE TITLE
MP3 playback looks overly minimal, has dead link

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4442]
On `0.15.x`. Looks like this:

![ss2](https://cloud.githubusercontent.com/assets/8888020/9945284/2d6fbdfc-5d41-11e5-9377-58dc6cc9cdbc.png)

Play/Pause works fine. The `<li>` link at the bottom is broken (leads to `http://127.0.0.1:8008/content/.mp3`). Could it be because I didn't include a metadata file?

**Comment by 66eli77** [comment]
the stylesheet does not get loaded maybe, but this looks pretty trendy though

**Comment by MCGallaspy** [comment]
No milestone, as we don't currently include mp3s and its not required by any of our partners at this point AFAIK.

**Comment by benjaoming** [comment]
Haven't see mp3s, should be okay to close this.
