### ISSUE TITLE
Video availability annotation does not correctly propagate into topic tree

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#4443]
Branch: 0.15.x
Ubuntu, Chrome

Videos that are not downloaded seem to be correctly annotated within content_cache, but their availability is not correctly flagged on the topic tree itself.

**Comment by aronasorman** [comment]
Since you were testing the sqlitedict stuff before this, did you make sure to delete the `sqlitedict` generated to make sure everything's vanilla? The path to it should be given by:

```
CONTENT_CACHE_FILEPATH = os.path.join(settings.CHANNEL_DATA_PATH, "contents.sqlite")
```

**Comment by rtibbles** [comment]
Yep, this was the issue. Must have been my hamfisted attempt to commit stuff. Closing!
