### ISSUE TITLE
(9b) Periodic class summary coach report (daily/weekly/monthly)

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#445]
From Johnny Long:
>How about a teacher dashboard to show summaries for the class including points for each student, perhaps a graph showing points over time, active time (may be hard, but “active” as opposed to logged in time). I need the teacher plugged into what the students are doing daily, weekly, monthly by student and by facility. (Note that there is no “class” entity. There should be. A facility can have more than one class.)
Here’s an example of a teacher’s report. The dropdown allows us to update statistics to “Weekly” or “Monthly”

![image](https://f.cloud.github.com/assets/4072455/943360/1d107c46-0210-11e3-95da-00c7785d0b63.png)

**Comment by aronasorman** [comment]
In development; let's open another issue once implementation for that has begun.
