### ISSUE TITLE
Makefile for common build tasks

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4459]
As per discussion on how we build and distribute installers, a lot of tasks can be outlined and unified in a simple Makefile.

One principle as per discussion: The Makefile has to be readable.

Common tasks outlined in learningequality/installers#158

@cpauya @MCGallaspy I'm hoping you can adopt the file for the installers in 0.15 -- is that reasonable? I guess it's a matter of having make available on the build system and then replacing all previous steps with `make sdist`, grabbing the resulting sdist (we'll need a way to automatically determine the name) and proceeding with the installer build as usual.

**Comment by cpauya** [comment]
I'd like to use this and clean-up the installer scripts but I'm not sure we can squeeze this into 0.15.x @benjaoming :smile_cat:.   If we aim stability for that milestone, I think it's best to punt the use of this in the installers for 0.16.x.

**Comment by MCGallaspy** [comment]
Agree with @cpauya, as per our discussion, I find it preferable to make no changes to the Windows installer build process in the limited time remaining -- let it be a project for the next cycle.

**Comment by benjaoming** [comment]
Yeah, as @MCGallaspy mentioned we had a quick discussion about how to unify the installers more.

In 0.15, we introduce the Makefile and use it in the .deb process.

For 0.16, we use the Makefile for all installers -- and introduce the concept of an import/export for KA_LITE home directories such that languagepacks, database, and video downloads can be bundled for a preseeded installation. #4311

**Comment by rtibbles** [comment]
Status, @benjaoming?

**Comment by benjaoming** [comment]
The Makefile is a cool new and modern thing we dig now! :D
