### ISSUE TITLE
(9c) Use topic-tree and expanded info for student coach report

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#446]
From Johnny Long:
>Or, perhaps a student report? On each line list:
>• Student name
>• Total points earned
>• Total exercise points earned / possible / percent
>• Total video hours watched (watched / possible / percent)
>• Last Completed Exercise / Video

>I’ve considered graphical / text elements similar to Khan for reporting these things, like:

![image](https://f.cloud.github.com/assets/4072455/943364/68a1041e-0210-11e3-8997-a721e5243c85.png)

>Essentially these show, from right to left: Total video time in section, total length of all clicked videos, total time watched of clicked videos. White represents untouched content. Green represents good progress (the student has watched a majority of videos in the section), red reveals struggles (the percent of watched vides in the section <= 50 or percent of clicked vides watched <- 50). In this way, we can see students that are clicking around like crazy but not completing anything.
>Since Exercises and videos don’t line up we can get a complex Khan-like display like this:

![image](https://f.cloud.github.com/assets/4072455/943362/5ae4d3be-0210-11e3-83a3-8bf571e3d4a4.png)

**Comment by rtibbles** [comment]
Superseded by #1871.
