### ISSUE TITLE
Clean up labels

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4460]
@aronasorman there's currently 21 labels. Suggested to remove a bunch of them in a previous email.

> The forrest of labels for the ka-lite repo has grown a bit dense and could do with a bit of thinning?
> 
> Seeing that our goal is to produce a platform-independent flavor, we can say that these labels defeat the purpose... and can be replaced:
> 
> Windows
> Linux
> Android
> Mac
> iOS
> 
> ...with one new label:
> 
> OS-specific
> 
> For instance, Mike spotted that I forgot to use os.sep yesterday. The problem could be labeled as an issue on Windows, but it's actually more an issue of an OS-specific pattern.
> 
> All other issues arising from a specific installer should be referred to the Installers repo.
> 
> 
> Suggestion 2: Merge these:
> 
> Refactoring and cleanup + performance
> 
> (because they are almost always correlated)
> 
> 
> Suggestion 3: Rename:
> 
> Internationalization to translations
> vulnerability to security
> 
> 
> Suggestion 4: Remove? Maybe it's part of Waffles and can't be removed?
> 
> "ready", I've never seen it in use?
> 
> 
> Suggestion 5: Out-dated:
> 
> 0.14.x bugbash
> 
> 
> But that should cut 1/3 of the labels :)

**Comment by benjaoming** [comment]
@aronasorman I'll immediately unassign you if you're off duty with the wrist... otherwise, this is a good "mouse clicking" activity :)

**Comment by MCGallaspy** [comment]
Seems ok. Note that as @cpauya pointed out, some labels (like "ready") are managed by waffle.

**Comment by benjaoming** [comment]
Work in progress!

**Comment by benjaoming** [comment]
All OS platform labels are removed now. They were barely in use, anyways. The "Android" label has been created over in learningequality/installers.

Not creating an "OS specific" label anyways, it can be a "bug" just.

Created "Browser compatibility" label so we can track browser issues when we create system requirements documentation.

**Comment by benjaoming** [comment]
Renamed "ux issue" to "ux / frontend"

**Comment by benjaoming** [comment]
"vulnerability" => "security"

@radinamatic input:

"internationalization" => "translation"

**Comment by benjaoming** [comment]
"performance": deleted

"refactoring and cleaning" => "refactoring and performance"

**Comment by benjaoming** [comment]
"enhancement" => "new feature"

**Comment by benjaoming** [comment]
For the record, there's a nice definition of labels here:

http://issuehub.io/label-guide

We don't have all these labels, but I'm not sure I would agree to this "label jungle" :)
