### ISSUE TITLE
Localized content (pt-br)

### ISSUE THREAD

**Issue by maluta** [learningequality/ka-lite#4461]
Taking Portuguese as example, translation isn't available on left side menu even checking it.

See screenshots below:  

![image](https://cloud.githubusercontent.com/assets/23658/9999036/970ec0e2-606a-11e5-8dfd-dd28943d542b.png)

![image](https://cloud.githubusercontent.com/assets/23658/9998976/5584c0e0-606a-11e5-859e-0218c4d1d029.png)

**Comment by maluta** [comment]
Update: today I redid the tests and still got the same problem. 

We are going to do an pilot in Manaus, located in the northwestern corner of Brazil. A place with a lot of connectivity challenges and we are struggling to get all content localized in this build. 

Said that, is there any direction (or workaround) for that issue?

**Comment by aronasorman** [comment]
Hi @maluta, can you describe your setup? OS, browser used, KA Lite version?

**Comment by maluta** [comment]
Hi @aronasorman 
I'm using Windows7, Firefox and KA Lite 0.15.1

**Comment by radinamatic** [comment]
The issue that was present on 0.14 (I'm reminded now while testing Mac upgrade scenarios) is that PT-BR topic titles content was not showing in the sidebar, but those exercises that were localized, show correctly once opened. 

@maluta, could you check that if you open this exercise:

![units2](https://cloud.githubusercontent.com/assets/1457929/13086388/4c2134d2-d4e3-11e5-877d-2b25ddb429dd.png)

...you see the content in Portuguese?

![units](https://cloud.githubusercontent.com/assets/1457929/13086413/687aa9c4-d4e3-11e5-95ef-89978aa4bc1c.png)

**Comment by maluta** [comment]
Hi @radinamatic - thanks for reply

I thought that only the titles content wasn't in pt-br

![capturar49](https://cloud.githubusercontent.com/assets/23658/13090000/7c935b3a-d4da-11e5-8194-4d94bbf5c270.PNG)

But the exercises are still in english...

![capturar50](https://cloud.githubusercontent.com/assets/23658/13090054/c8b18de8-d4da-11e5-818e-7e181bc84247.PNG)

I got all the videos for "Unit conversion"
![capturar51](https://cloud.githubusercontent.com/assets/23658/13090094/f8eacb50-d4da-11e5-925d-4529809a7b8f.PNG)

**Comment by radinamatic** [comment]
I was unable to replicate this on the same configuration (0.15.1, Windows 7, FF). The issue of topic titles in the sidebar still being in English persists, but the exercises do open in Portuguese. 
We should make sure this is fixed in 0.16 ( @aronasorman ).   

@maluta

1. Did you install [assessment items](http://ka-lite.readthedocs.org/en/0.14.x/faq.html#i-skipped-the-step-for-downloading-the-assessment-items-during-install-how-can-i-do-it-now)?
2. Could you try deleting and re-installing the PT-BR language pack? Remember to restart the server after.

**Comment by aronasorman** [comment]
Debugging this now.

I first investigated if the language pack just wasn't bundling the topic tree translations. Nope, the strings are there and translated.

So the bug must be in KA Lite's side.

**Comment by aronasorman** [comment]
Possible causes:
1. Translations aren't being applied to the topic tree strings.
2. We are not reading the mo files correctly.
3. There's something with the `pt-BR` code which is messing up Django.

**Comment by maluta** [comment]
I noted that some topics content are translated and others not. 

![capturar55](https://cloud.githubusercontent.com/assets/23658/13125497/fb4838ec-d5ac-11e5-9f79-44ae409ba0fb.PNG)

![capturar56](https://cloud.githubusercontent.com/assets/23658/13125520/246654a2-d5ad-11e5-9c22-421282b7c178.PNG)

**Comment by aronasorman** [comment]
Thanks @maluta for that. Seems like that untranslated exercise did have a translated entry in the po file:


![screen shot 2016-02-18 at 10 34 52](https://cloud.githubusercontent.com/assets/191955/13153922/4616608c-d62b-11e5-9539-7f02c01d5c19.png)

Strange how KA Lite is selective in translating exercises. Looking further.

**Comment by aronasorman** [comment]
Note to myself: bug may lie in the pretranslation phase, during cache invalidation.

**Comment by benjaoming** [comment]
This should be safe to close now that the exercise format has completely changed with the arrival of content packs. Please feel free to open a new issue if it persists in 0.16+ and thanks for reporting, @maluta !
