### ISSUE TITLE
Make fields.learningequality.org/docs redirect to RTD

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4462]
I don't know if there might be dangling references, but we should point as following:

http://field.learningequality.org/docs/0.13/en/ => http://ka-lite.readthedocs.org/en/0.13.x/
http://field.learningequality.org/docs/0.14/en/ => http://ka-lite.readthedocs.org/en/0.14.x/
http://field.learningequality.org/docs/develop/en/ => http://ka-lite.readthedocs.org/en/latest/

@MCGallaspy would you be up for this, I don't have access to the server..?

**Comment by MCGallaspy** [comment]
@jamalex and I tired to get rid of all the references. We had a series of redirects set up from www.learningequality.org which now redirect to RTD. We also tried to purge any references to field.learningequality.org. But perhaps it's now time to simply remove the docs from field?

**Comment by benjaoming** [comment]
@MCGallaspy ah cool, I was thinking about redirects, but cleaning up properly is much better. Yeah, deleting it is a good idea... then we can check to see if there are any 404s and what their HTTP referers are!

**Comment by MCGallaspy** [comment]
Okay, now removing docs from field then.

**Comment by MCGallaspy** [comment]
Done.

**Comment by benjaoming** [comment]
Awesome! Let's check the 404 logs in a week.
