### ISSUE TITLE
0.15 dev Could be missing assessment items

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite#4464]
Apologies for such a vague title but, currently in testing we really do not know if entire categories of assessment items are missing or when shown if there are assessments within those categories missing that I am aware of. I am seeing what I think are new topics within the 0.15 MAC develop build without any assessment items. It could be that these are new and there are no assessment items for them yet and only video content but just in case thought I should make the dev team aware, also any solution to be able to tell such as a listing of assessments would be helpful so as to know for sure all assessments are included?

**Comment by aronasorman** [comment]
@EdDixon can you list which assessment items are missing?

**Comment by EdDixon** [comment]
Well that is exactly the problem I have no way to know for sure and have been told that if they are not showing up in the side bar they simply do not exist so I can only assume that is the case with all of these. Particularly the newer topics but if they should have assessment items (which they typically do) then they are missing you can see from this capture using the most recent MAC installer entire upper level topics are showing nothing like economics and art where I do think there were assessments before? 

![2015-09-30_14-36-52](https://cloud.githubusercontent.com/assets/4349806/10205877/09049e8e-6781-11e5-99b4-3574f533a953.png)

So I really don't know for sure but suspect there are some missing?

**Comment by aronasorman** [comment]
Looked into it. That's because they all contain videos now. Non-issue for me, until we can find some concrete examples.
![screen shot 2015-10-01 at 10 47 43](https://cloud.githubusercontent.com/assets/191955/10228863/f312ff5e-6829-11e5-9f5f-6c72a310ef41.png)
