### ISSUE TITLE
"Error during update: Error: File is not a zip file" when downloading Hindi language pack

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#4466]
Branch: 0.14.x (running from source)

After the language pack finished downloading, I got:

![image](https://cloud.githubusercontent.com/assets/618416/10025241/20d7c8fa-6110-11e5-968c-4466688360d0.png)

**Comment by jamalex** [comment]
The first time I tried, I think I got "list index out of range". But I thought maybe it was because I needed to refresh the page (it had been open since yesterday).

**Comment by jamalex** [comment]
Also curious: why does it already switch to Hindi in several places while downloading the language pack? How does it even have the strings yet?

![image](https://cloud.githubusercontent.com/assets/618416/10025362/bdac92f0-6110-11e5-9c4f-3f12449f5f5c.png)

**Comment by jamalex** [comment]
Apparently "अमान्य कैश" means "Invalid cache", but I'm guessing "Invalidating cache". Hangs for a long time on that step. General/known 0.14 problem, @rtibbles?

**Comment by jamalex** [comment]
And the third time it did eventually complete.

**Comment by rtibbles** [comment]
Yes, invalidating the cache takes a while. However, as we need to restart the server to load a new language pack, that might be a bad idea anyway.

**Comment by jamalex** [comment]
On the video download page for Hindi (http://127.0.0.1:8008/update/videos/?lang=hi), it's been hanging for a long time.

It seems the topic tree endpoint (http://127.0.0.1:8008/api/videos/topic_tree?lang=hi) is returning `null`.

**Comment by jamalex** [comment]
> as we need to restart the server to load a new language pack

Oh. We don't say that anywhere. :/

**Comment by jamalex** [comment]
Is that in order to load the new Po files, or something?

**Comment by rtibbles** [comment]
No, there is an open issue and open PR for it, but I only found the issue after the string freeze for 0.15, so it is currently targeted to develop....

**Comment by rtibbles** [comment]
I imagine it is a po files thing - @aron can probably say most clearly.

**Comment by jamalex** [comment]
I'd say it seems worth putting a message even into 0.14 about that (if it's not something easy to fix), since  the disadvantage of the Languages tab having an untranslated string would probably be outweighed by the disadvantages of the user thinking i18n was completely broken.

**Comment by jamalex** [comment]
I restarted the server, and http://127.0.0.1:8008/api/videos/topic_tree?lang=hi still returns `null`.

**Comment by aronasorman** [comment]
null topic tree solved by redownloading the language pac. "File is not a Zip File" solved by turning off varnish for lang pack downloads.
