### ISSUE TITLE
New Video Tree not updating video data after download

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite#4467]
On MAC 0.15 develop the videos tree is not updated to show which videos have been downloaded after downloading them. In the screenshot all counting videos were selected and 9 out of 10 did download according to the notification but the tree is not updated to reflect this? 
![2015-09-22_12-26-32](https://cloud.githubusercontent.com/assets/4349806/10028017/60901706-6127-11e5-9327-06de7427b79a.png)

**Comment by EdDixon** [comment]
A refresh reveals I was logged out during the process which may help debug the problem. Also, note: this is after installation and without a reboot or restart of the server.  
![2015-09-22_12-56-43](https://cloud.githubusercontent.com/assets/4349806/10030120/455788be-6133-11e5-8d0e-478b2ade72dc.png)

**Comment by EdDixon** [comment]
After which the videos are shown to have been downloaded.
![2015-09-22_13-26-37](https://cloud.githubusercontent.com/assets/4349806/10030153/71ed92c4-6133-11e5-891a-3fb69ee25104.png)

**Comment by EdDixon** [comment]
Very odd and may need to become a separate issue but, while looking at the assessments I noticed that the videos that where just downloaded are not showing in the learn tab despite the fact they are listed in the Video Tree? I did test downloading language packs but made no changes to the default language before checking here?
![2015-09-22_14-14-56](https://cloud.githubusercontent.com/assets/4349806/10030359/9713a222-6134-11e5-9ca0-27b9512d5ad4.png)

**Comment by EdDixon** [comment]
Stopping the server and then restarting and logging back in does make the downloaded videos appear in the learn
![2015-09-22_14-47-26](https://cloud.githubusercontent.com/assets/4349806/10031190/0dd10784-6139-11e5-8458-097c71608adc.png)
 tab.

**Comment by cpauya** [comment]
Hi @ed - I tried this on a Yosemite VM and it worked.  See screenshots below, I downloaded "Counting in order" video and it updated the tree after the download.

![osx-yosemite-107](https://cloud.githubusercontent.com/assets/175580/10540554/a17ab0a6-743b-11e5-8880-e80af1dab56f.png)

After download:
![osx-yosemite-108](https://cloud.githubusercontent.com/assets/175580/10540555/a1a971d4-743b-11e5-95dc-e867de750a66.png)
