### ISSUE TITLE
Can't switch to another language to download dubbed videos

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#4468]
branch: 0.15.x

In the download videos page, we have this: 

![image](https://cloud.githubusercontent.com/assets/191955/10028052/2cc90cc8-611f-11e5-8e2f-32a57b0b8920.png)

Expected behaviour: Clicking the "English" link will change the link to a dropdown box, allowing me to download dubbed videos for that language.

Current behaviour: Clicking said link will just reload the same page.

**Comment by 66eli77** [comment]
fixed in PR #4469

**Comment by rtibbles** [comment]
Should be fixed by #4469.
