### ISSUE TITLE
(8) Add info about most recent activity on student dashboard

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#447]
From Johnny Long:
>Students don’t have an easy way to see where they left off. On the student dashboard, we need a history that shows Last Practices Performed and Last Videos Watched. In addition, provide a link to that specific practice or video, provide a link to that subtopic so the student can get working quickly.

Note: this would require extension of the UserLog feature.  Could start as simply keeping a large enough log set that all students could access their recent progress, but could change into an option to keep only each student's most recent activity.

**Comment by rtibbles** [comment]
Superseded by #3368.
