### ISSUE TITLE
Exercise title and assessment item content not translated

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#4472]
Branch: 0.15.x
Ubuntu/Chrome

Expected Behaviour: Both exercise title and assessment item content should be translated.
Current Behaviour: Neither are.

![image](https://cloud.githubusercontent.com/assets/1680573/10053963/9e034ac4-61e3-11e5-97b5-c6338293e03d.png)

**Comment by rtibbles** [comment]
Same issue is arising on video pages.

![image](https://cloud.githubusercontent.com/assets/1680573/10053979/c47dbd9c-61e3-11e5-8648-56ba0696a410.png)

**Comment by rtibbles** [comment]
And also in the titles of the tabular report view on the coach reports.

![image](https://cloud.githubusercontent.com/assets/1680573/10054400/b089cd6a-61e5-11e5-998f-7f05b673e259.png)


Seems like the topic tree is getting translated, but content caches not?

**Comment by aronasorman** [comment]
Exercise translations seem to be a thorn on my side every release :)

**Comment by rtibbles** [comment]
Fixed in #4475
