### ISSUE TITLE
Language switches during language pack download

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#4473]
Branch 0.15.x
Ubuntu/Chrome

Expected Behaviour: Language should always be in the currently selected language.
Current Behaviour: When downloading a language pack, the stage tracker switches to that language name when on the final step.

![image](https://cloud.githubusercontent.com/assets/1680573/10054576/a51d7b60-61e6-11e5-8a9a-01fe132315d5.png)

I think @jamalex had reported something similar too.

**Comment by jamalex** [comment]
Mentioned here: https://github.com/learningequality/ka-lite/issues/4466#issuecomment-142348861

**Comment by rtibbles** [comment]
Quite possible this is just displaying the name of the language pack with no other text, as seen in the command line output:
```
INFO:kalite:Finished processing language pack العربية.
```

**Comment by rtibbles** [comment]
Fixed in #4497
