### ISSUE TITLE
Static files are not rendered when running 'bin/kalite manage setup --settings=kalite.project.settings.dev'.

### ISSUE THREAD

**Issue by arceduardvincent** [learningequality/ka-lite#4479]
**Branch:** 0.15.x

**Expected Behaviour:** Able to render the static files when running the `kalite start`.

**Current Behaviour:** When using the 'bin/kalite manage setup --settings=kalite.project.settings.dev' and choosing Yes during 'kalite start' does not render the static files.
![screenshot 2015-09-22 14 02 57](https://cloud.githubusercontent.com/assets/4099119/10066808/21b15204-62c9-11e5-8105-4cc3431e270f.png)

**Steps to Replicate:**

>1. Clear the KALITE_PYTHON env var
>1. Clone  ka-lite repo then check out 0.15.x branch.
>1. Create new virtualenv and activate it.
> 1. Run 'pip install -r requirements_dev.txt'
>1. Run 'bin/kalite manage setup --settings=kalite.project.settings.dev'
>1. When asked to run 'kalite start' - select Yes.
>1. Go to http://127.0.0.1:8008/ and notice the page doesn't have the static files as per screenshot

**Comment by rtibbles** [comment]
This is not expected behaviour.
