### ISSUE TITLE
Add instructions for upgrading vs new install

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4481]
@EdDixon asked:

> is the user expected to uninstall the application first or simply install over existing?

So let's add an answer to the docs.

**Comment by MCGallaspy** [comment]
@cpauya or @aronasorman, what is the answer to this question for OSX?

**Comment by cpauya** [comment]
For Mac upgrade of the OSX installer, two possible answers:

1. Drag the new installer over to the `KA-Lite-Monitor` application in the `Applications` folder, and confirm to overwrite the existing app.
2. Delete the existing app by dragging it to the `Trash` and proceed with the installation by dragging the new installer into the `Applications` folder.

**Comment by aronasorman** [comment]
Fixed in https://github.com/learningequality/ka-lite/pull/4514.
