### ISSUE TITLE
(3) Use topic tree for tabular view coach reports

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#449]
We force one level of granularity with the dropdown box.  Allow users to choose any level of granularity by exposing the topic tree in the tabular view coach reports.

From Johnny Long:
>There’s a bug in the existing coach reports. For example, my kids are diligently watching Algebra videos and working on the exercises. However, as a teacher I can’t see that. The dropdown for topic skips subjects and topics. I can’t find their Algebra work anywhere. Here is the complete dropdown, side by side with the beginning Math topics. There is no correlation and it will be VERY confusing for teachers. There should be a one-to-one relationship between subtopics and the coach dropdown.

**Comment by rtibbles** [comment]
Superseded by #1739
