### ISSUE TITLE
Trouble playing videos on iPad

### ISSUE THREAD

**Issue by mtorourk** [learningequality/ka-lite#45]
The H.264 encoding used in Khan Academy videos does not render properly on the iPad, making it impossible to watch videos in either Safari or Chrome on the iPad. This issue has been noted by other iPad users outside of the KA Lite project as well - http://stackoverflow.com/questions/6431111/ipad-doesnt-render-h-264-video-with-html5

**Comment by rtibbles** [comment]
Fixed by using re-encoded videos.
