### ISSUE TITLE
Error message during login is confusing.

### ISSUE THREAD

**Issue by arceduardvincent** [learningequality/ka-lite#4500]
**Branch:** `0.15.x`

**Windows installer:** kalite-setup-0.15.0--9-18-2015.exe

**Platform:** IE11 on Windows 8.1

**Expected Behaviour:** Show an appropriate error message for the username or password is not entered correctly.

**Current Behaviour:**  When you entered wrong password the error message show you that your username is not found. The username that I use is the admin account, it show the wrong error message.
See demonstration.
![screenshot 2015-09-25 15 17 42](https://cloud.githubusercontent.com/assets/4099119/10095263/0246a4fa-639b-11e5-85e0-c5f8b1bf71be.png)

**Steps to reproduce:**

> 1.  Create admin account.
> 2.  Navigate to login tab then click it.
> 3.  When the login modal appear enter correct username  of your admin account but in the password, text box enter the wrong password. 
> 4. Notice that the error message is inappropriate "Username was not found. Did you type your username correctly?"

**Comment by manipalsingh013** [comment]
opened PR #4871 for the issue
