### ISSUE TITLE
Final docs review

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4501]
Prior to release, take a careful look at the documentation. Create a documentation tarball for inclusion in installers.

**Comment by MCGallaspy** [comment]
The red border applied for element highlighting in the screenshots appears to displace elements slightly -- should just lay on top, instead of moving them.

**Comment by rtibbles** [comment]
Mike - perhaps use the outline property instead?
http://stackoverflow.com/questions/2748637/how-to-give-border-to-any-element-using-css-without-adding-border-width-to-the-w

**Comment by benjaoming** [comment]
@MCGallaspy I'm working on embedding the docs in another issue, #4348

**Comment by jinchuika** [comment]
Did you added the suggestion in #4049? I find it really useful

**Comment by rtibbles** [comment]
I think @aronasorman is assigned to that, we will bug him about it today!

**Comment by MCGallaspy** [comment]
@benjaoming 

>  I'm working on embedding the docs in another issue, #4348 and #4375

Do those issues relate to this one? I wasn't very specific, but to be clear I'm only reviewing the documentation for accurate content, good layout, etc.

**Comment by benjaoming** [comment]
@MCGallaspy 

I was reacting on this part:

>  Create a documentation tarball for inclusion in installers.

...because what I'm working on is including them in the sdist.. but since this isn't part of the Windows installer, I guess we're talking about two different things here :)

**Comment by MCGallaspy** [comment]
@benjaoming if you need some files to include now, my suggestion is to grab a tarball/zipfile from RTD. If you can wait a bit for me to upload fixed-up screenshots, then you can also build the html yourself. [This is the relevant logic for including docs.](https://github.com/learningequality/ka-lite/blob/0.15.x/kalite/settings/base.py#L407) You just need to drop the html output of sphinx-build into the source directory's `docs/_build/html/` subdirectory. Lemme know if this needs some tweaking to build a .deb file.

**Comment by MCGallaspy** [comment]
I suppose we're done here.

**Comment by MCGallaspy** [comment]
Oof, actually, I haven't created a tarball -- but now that updated screenshots have been committed, it's as simple as running `make html` in the `docs` directory. That will create all the appropriate files in the `docs/_build/html` directory. Will upload tarball upon request.

**Comment by benjaoming** [comment]
@MCGallaspy actuall RTD has one:

http://readthedocs.org/projects/ka-lite/downloads/htmlzip/latest/ (still 0.14)

and

http://readthedocs.org/projects/ka-lite/downloads/htmlzip/0.15.x/

**Comment by MCGallaspy** [comment]
@benjaoming it's a single-page document.

**Comment by benjaoming** [comment]
@MCGallaspy grr, okay, but it's in the right layout with anchors and everything :)

the new sdist in pypi has docs/_build/html included
