### ISSUE TITLE
Integrate content database into language pack generation, download, and unpacking

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#4505]
Database backed content caches require language specific database files to be distributed in the language packs.

**Comment by aronasorman** [comment]
Dubbed video mappings too.

**Comment by rtibbles** [comment]
This is still WIP, afaik, dubbed video mappings are not currently integrated into the pipeline.

**Comment by MCGallaspy** [comment]
So this will be resolved by new content packs?

**Comment by rtibbles** [comment]
Yes.

**Comment by rtibbles** [comment]
This is done.
