### ISSUE TITLE
Reduce peak memory usage of content annotation

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#4506]
Gist of current benchmarks from @gwong89 

https://gist.github.com/gwong89/b05d4dc0b47af2438304

the annotate_content_items takes 85mb and takes about 27.5 seconds

**Comment by gwong89** [comment]
https://gist.github.com/gwong89/b05d4dc0b47af2438304

the gist has been updated and annotate_content_models actually takes 130

**Comment by rtibbles** [comment]
Yep - looks like the main memory bloat comes from loading all the content data into memory from the query. Much better for us to do it one item at a time, I would think.

**Comment by rtibbles** [comment]
Can probably create a generator for querying the content models, so that we can iterate through them all without loading the whole list into memory, and then run update on an individual model at a time.

Would be interesting to see how this impacted performance, particularly on slow disk writing systems.

**Comment by rtibbles** [comment]
http://docs.peewee-orm.com/en/latest/peewee/api.html#SelectQuery.iterator

We can use this behaviour to construct the generator for a more memory efficient query.

**Comment by rtibbles** [comment]
Fixed in #4551
