### ISSUE TITLE
Migrate assessment item database to new system

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#4508]
This is desirable because we will want to distribute a new assessment item database for each language, rather than having the translation happen on the fly using the Django mo files (which when loaded into memory increase memory usage).

**Comment by aronasorman** [comment]
We'll also want to put KA strings into the DB as well. So now the po files should only contain our strings (+ one po files from KA, for the exercise interface).

**Comment by rtibbles** [comment]
Fixed in #4630
