### ISSUE TITLE
There's something wrong with the fonts

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#4509]
branch: 0.15.x

![image](https://cloud.githubusercontent.com/assets/191955/10110756/2aaf9828-6384-11e5-9436-6f3955900f0f.png)

![image](https://cloud.githubusercontent.com/assets/191955/10110773/3e2ad174-6384-11e5-8266-3cdce625279a.png)

URL: http://127.0.0.1:8008/learn/khan/math/early-math/cc-early-math-counting-topic/cc-early-math-numbers-120/number-grid/

**Comment by rtibbles** [comment]
Doesn't happen in debug mode, so must be something funny with the production building. Trying to reproduce now.

**Comment by aronasorman** [comment]
Also, this was in your `persist_annotation` branch, so this might've been fixed in the latest 0.15.x. Let me check that.

**Comment by aronasorman** [comment]
Still the case. If it helps, I ran my server with:

```
kalite start --foreground --settings=kalite.project.settings.disk_based_cache
```

**Comment by rtibbles** [comment]
Had you run
```node build.js``` first?

**Comment by rtibbles** [comment]
I am unable to replicate it.

**Comment by aronasorman** [comment]
Fixed now. Just needed to update my assets.
