### ISSUE TITLE
Clicking a particular sidebar entry has unexpected results

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4512]
On `0.15.x`, clicking the exercise in the screenshot causes the user to be navigated *up* one level, instead of going to the exercise:

![ss2](https://cloud.githubusercontent.com/assets/8888020/10113053/7220ccc0-6395-11e5-9f1b-07a396ba06bd.png)

After clicking, the url is `/learn/khan/math/early-math/cc-early-math-counting-topic/numbers-to-120_1/` -- looks like something fishy with the duplicated slugs. Navigating directly to `/learn/khan/math/early-math/cc-early-math-counting-topic/cc-early-math-numbers-120/numbers-to-120_1/` takes me to the exercise.

**Comment by rtibbles** [comment]
Weird - I'll take a look.
