### ISSUE TITLE
Unresolved: "invalidate_on_video_delete"

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4519]
This function no longer exists:

https://github.com/learningequality/ka-lite/blob/0.15.x/kalite/updates/management/commands/videoscan.py#L104

@rtibbles hoping you know if the fix is to remove the whole management command or how to go about with this?

**Comment by rtibbles** [comment]
Well, that is interesting - it's nowhere in current master either, so it must have been gone a while...

**Comment by benjaoming** [comment]
As in we didn't use `videoscan` for a while?

**Comment by rtibbles** [comment]
No, we use videoscan - but that particular function is not in 0.13.x either.

Because the reference happens after the return statement, I assume that is why videoscan has run without issue.

**Comment by benjaoming** [comment]
Heh, you're right... I was also seeing the unresolved func in a test, so I didn't read the code surrounding... in a process of manually reading through whatever unresolved references we have according to my PyDev static code reference checker.

Also resolved this in #4520

**Comment by rtibbles** [comment]
Fixed in #4520
