### ISSUE TITLE
Select facility via drop-down in "add facility user" form.

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#453]
When creating a new facility user, we have to go through a multi-page process to select a facility.  To change the facility, one has to click and go through the multi-page process again, potentially losing form data.

Seems this could be solved easily by simply having a normal dropdown dialog box that is a required field in the form.  This would allow more simple selection and changing of the facility.

![image](https://f.cloud.github.com/assets/4072455/944727/9e38c0cc-02d2-11e3-82bf-e10f8d9e2b8f.png)
![image](https://f.cloud.github.com/assets/4072455/944728/a2f25c18-02d2-11e3-9e00-f45d1fb5147f.png)

@wangguan59 could you triage?

**Comment by rtibbles** [comment]
Fixed.
