### ISSUE TITLE
Are migrations possibly blocked by stale content types?

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4535]
From `bin/kalite start`:

```
Running migrations for main:
 ! Migration main:0039_log_timestamps should not have been applied before main:0039_auto__del_assessmentitem__add_contentrating__add_unique_contentrating_ but was.
 - Migrating forwards to 0040_auto__del_unique_contentrating_content_kind_content_id_user__add_uniqu.
 > main:0039_auto__del_assessmentitem__add_contentrating__add_unique_contentrating_
 > main:0040_auto__del_unique_contentrating_content_kind_content_id_user__add_uniqu
The following content types are stale and need to be deleted:

    main | assessmentitem

Any objects related to these content types by a foreign key will also
be deleted. Are you sure you want to delete these content types?
If you're unsure, answer 'no'.

    Type 'yes' to continue, or 'no' to cancel: 
```

**Comment by MCGallaspy** [comment]
Something's wrong with migrations. It kept trying to delete a table (main.assessment_items) that didn't exist, and now it thinks there's a stale content type? What about this is a blocker? The model does not even exist.

**Comment by MCGallaspy** [comment]
I think we need to either 1) amend past migrations to remove this crud or 2) create a new migration that handles this.

**Comment by benjaoming** [comment]
Did a migration for this model exist in our dev version at some point?

**Comment by MCGallaspy** [comment]
That seems likely.

**Comment by rtibbles** [comment]
I believe so, but I am damn sure we didn't release it.

**Comment by rtibbles** [comment]
Was this during an upgrade, @benjaoming?

**Comment by MCGallaspy** [comment]
Yeah, what branch is this? `0.15.x`? I'll try to resolve it.

**Comment by benjaoming** [comment]
This was 0.15.x -- running on some kind of dev environment. Sorry about the lacking info from my side.

**Comment by benjaoming** [comment]
Gonna test the PR, I'll merge when I verify it :)

**Comment by benjaoming** [comment]
Had issues with ghost migrations from a previous develop branch. Those migrations were never part of 0.14 or 0.14.1. Mike cleaned up the migration path.

Everything looks good!
