### ISSUE TITLE
Responsive design issues on localized interfaces

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4539]
Responsive design issues - this should probably be tested further with other languages (German for example) that usually have even longer localized strings than English or Spanish.

**Branch**: 0.15 (**ka-lite_0.15~b2-0ubuntu1_all.deb** installer  on Ubuntu 15.04, but it's not an installer issue)

**Current Behavior**: 
Resizing the window yields some problems with the menu tabs and other elements:

![responsive](https://cloud.githubusercontent.com/assets/1457929/10177647/710cfdc2-66fb-11e5-9879-bc2ef2109dec.png)

Hamburger menu appears correctly at 768px, but still with a small glitch:

![responsive2](https://cloud.githubusercontent.com/assets/1457929/10177707/e1d1b200-66fb-11e5-8b9d-2649ec509cb0.png)

Resizing the window further reveals other issues:

![responsive3](https://cloud.githubusercontent.com/assets/1457929/10177891/eaca915a-66fc-11e5-97da-723c41f23e87.png)

The above (two separators?) occurs even on English version:

![responsive4](https://cloud.githubusercontent.com/assets/1457929/10177995/7573e824-66fd-11e5-9966-3eba7ddbd5dc.png)

**Comment by rtibbles** [comment]
The answer to this, of course, is always to test interface layouts in German.

**Comment by rtibbles** [comment]
This is bad, but it's not terrible. Don't want this as a release blocker, so punting.

**Comment by benjaoming** [comment]
We can only hope that someone annoyed enough to fix it will pop up. But not going to leave the issue dangling, as it won't get it fixed.
