### ISSUE TITLE
Add an option to show "All students" under user management

### ISSUE THREAD

**Issue by wangguan59** [learningequality/ka-lite#454]
Currently, we offer option to view students in each different group under user management (Admin > User Management)
But it important to just show all the students under one facility, so we need to add an option to show "All students".

![screen shot 2013-08-11 at 4 25 31 pm](https://f.cloud.github.com/assets/1319955/944809/d9afb380-02dd-11e3-9f03-0788b0b01486.png)

**Comment by rtibbles** [comment]
Fixed.
