### ISSUE TITLE
Coach user - link to register device not working

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4541]
Coach user - link to register device not working

**Branch**: 0.15, **ka-lite_0.15~b2-0ubuntu1_all.deb** installer  on Ubuntu 15.04

**Expected Behavior**: 
The link `Please follow the directions to register your device, so that it can synchronize with the central server.` should lead to the `/securesync/register/` page with instructions.

**Current Behavior**: If Coach user is logged in, the message is displayed and the link seems to be correct one:

![coach_register](https://cloud.githubusercontent.com/assets/1457929/10180822/3c1e3b4c-6711-11e5-8994-b932312dba1a.jpg)

##### However, once the user follows the link nothing seems to happen, they end up at the `http://192.168.1.42:8008/?login=true&next=/securesync/register/` page and are unable to register:

![coach_register2](https://cloud.githubusercontent.com/assets/1457929/10180845/81364bca-6711-11e5-8471-b529ec560f6d.jpg)
    
**Steps to reproduce**:

1. Log in as Coach on unregistered device.
2. Follow the link to register device.

**Comment by EdDixon** [comment]
I was not aware the coach is given the ability to register the device? That is only done once immediately after login in by the admin user as far as I know. It is good I think, that it does not allow any other user to do the registration but removing the potential to do so would be better. Perhaps simply removing that link from the page if a non admin user has logged in prior to registration?

**Comment by radinamatic** [comment]
Yeah, that option was a surprise for me too. The solution in that case, as you say, would be to ensure only Admin/Superuser has the ability to register the device and can see the corresponding message alert.

**Comment by radinamatic** [comment]
Non extant on 0.16.5. Closing!
