### ISSUE TITLE
Compress khan_assessment.zip - it's 165 MB too big.

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4542]
Current zipball is 469MB:

https://learningequality.org/downloads/ka-lite/0.15/content/

I can zip its contents to a zip that's 304 MB. Command is just: `cd where/items/are && zip -r ~/newzip.zip *`

Be sensitive about the new .zip, though. I *think* we might have had issues before with the Python zip library not being able to read the new zip... so running `kalite manage unpack_assessment_zip file.zip` is a good idea for testing.

**Comment by rtibbles** [comment]
Compression requires a non-Python library: https://docs.python.org/2/library/zipfile.html#zipfile.ZIP_DEFLATED

**Comment by benjaoming** [comment]
From SO:

> This is because ZipFile requires you to specify the compression method. If you don't specify it, it assumes the compression method to be zipfile.ZIP_STORED, which only stores the files without compressing them. You need to specify the method to be zipfile.ZIP_DEFLATED. You will need to have the zlib module installed for this (it is usually installed by default).

Closing this, we have to keep in mind that we can never use compressed .zip files for distribution of content if we keep the pure-python requirement.
