### ISSUE TITLE
BadZipFile if languagepack doesn't exist

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4543]
I'm marking this a release blocker until @EdDixon comments on how severe it is. I know that he has reported this on a number of occasions during testing.

It's pretty easy to recreate, just ask for a languagepack that doesn't exist. For instance, due to a bug in command line arg parsing, "=es" does not exist and gives us this error:

```
✗ bin/kalite manage languagepackdownload -l=es --commandline
INFO:kalite:Downloading language pack for lang_name==es, software_version=0.15
INFO:kalite:Downloading language pack '=es'
INFO:kalite:Retrieving language pack: =es
INFO:kalite:Unpacking language pack '=es'
INFO:kalite:Unpacking new translations
INFO:kalite:Error: File is not a zip file
INFO:kalite:Cancelling process languagepackdownload
Traceback (most recent call last):
  File "ka-lite/python-packages/django/core/management/base.py", line 224, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "ka-lite/python-packages/fle_utils/django_utils/command.py", line 214, in execute
    super(LocaleAwareCommand, self).execute(*args, **kwargs)
  File "ka-lite/python-packages/fle_utils/chronograph/management/croncommand.py", line 38, in execute
    super(CronCommand, self).execute(*args, **kwargs)
  File "ka-lite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "ka-lite/kalite/updates/management/commands/languagepackdownload.py", line 81, in handle
    unpack_language(lang_code, zip_filepath=zip_filepath)
  File "ka-lite/kalite/updates/management/commands/languagepackdownload.py", line 126, in unpack_language
    z = zipfile.ZipFile(zip_fp or (zip_data and StringIO(zip_data)) or open(zip_filepath, "rb"))
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
```

**Comment by EdDixon** [comment]
I will need to see again how severe it is in 0.15. I remember seeing it in 0.14 testing on Linux but they may be because I would have a console indicating what the problem was where on other installation methods it may only be available in the log file for the installation? I think it maybe related to the bad magic number error seen in the past as well, but could be mistaken about that. Regardless setting up here now to test for this and will let you know. Thanks,

**Comment by aronasorman** [comment]
I don't think this needs to be a release blocker. We solved this for language packs [here](https://github.com/learningequality/ka-lite/issues/4466). So this only happens now if you give an invalid language pack code. That can only happen if you mess with things through the command line. Starting with 0.15 we now give a [table](http://ka-lite.readthedocs.org/en/0.15.x/faq.html#how-can-i-install-a-language-pack-without-a-reliable-internet-connection) for people to refer to when installing language packs offline.

**Comment by benjaoming** [comment]
@aronasorman the alternative to something being a release blocker is not that it isn't an issue at all? :)

**Comment by aronasorman** [comment]
I closed it because of this line:

> I'm marking this a release blocker until @EdDixon comments on how severe it is. I know that he has reported this on a number of occasions during testing.

Like I said, there is no way for a user to download a nonexistent language through the web interface, and the only way we mention this command is accompanied by a chart of languages *and* an example on how to specify the language code. So yes, I don't think this is a bug at all.

**Comment by benjaoming** [comment]
IMO it's a bug that we don't test for the existence of the language code / language pack before creating a broken (empty) zip file.

**Comment by aronasorman** [comment]
Opened a PR that shows a better error message: #4547.

**Comment by benjaoming** [comment]
Confirming that this works now!

```
✗ bin/kalite manage languagepackdownload -l=es --commandline
INFO:kalite:Downloading language pack for lang_name==es, software_version=0.15
INFO:kalite:Downloading language pack '=es'
INFO:kalite:Retrieving language pack: =es
INFO:kalite:Error: Language pack =es not found. Please double check that it exists.
INFO:kalite:Cancelling process languagepackdownload
Traceback (most recent call last):
  File "ka-lite/python-packages/django/core/management/base.py", line 224, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "ka-lite/python-packages/fle_utils/django_utils/command.py", line 214, in execute
    super(LocaleAwareCommand, self).execute(*args, **kwargs)
  File "ka-lite/python-packages/fle_utils/chronograph/management/croncommand.py", line 38, in execute
    super(CronCommand, self).execute(*args, **kwargs)
  File "ka-lite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "ka-lite/kalite/updates/management/commands/languagepackdownload.py", line 81, in handle
    zip_filepath = get_language_pack(lang_code, software_version, callback=self.cb)
  File "ka-lite/kalite/updates/management/commands/languagepackdownload.py", line 124, in get_language_pack
    raise requests.exceptions.HTTPError("Language pack %s not found. Please double check that it exists." % lang_code)
HTTPError: Language pack =es not found. Please double check that it exists.
```

**Comment by benjaoming** [comment]
It would actually also create an invalid languagepack in the folder, so good thing we got it resolved :)

```
INFO:kalite:Ignoring non-language pack =es in /ka-lite/locale/
```
