### ISSUE TITLE
Content rating responsive design issues

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4544]
Content rating responsive design issues

**Branch**: 0.15, **ka-lite_0.15~b2-0ubuntu1_all.deb** installer  on Ubuntu 15.04

Issue on both WXP & Ubuntu, FF & Chrom(ium) 

**Current Behavior**: 
On browser's window at >1200px, all's well:

![responsive-cr](https://cloud.githubusercontent.com/assets/1457929/10200168/0fb2f57c-67a5-11e5-81d3-f7d262b3ae8d.png)

On <1200px, one star slides below:

![responsive-cr2](https://cloud.githubusercontent.com/assets/1457929/10200225/6a6774fc-67a5-11e5-98b7-a335a49746d7.png)

Going further, star returns to its place, but strings **Poor/High** appear above and below:

![responsive-cr3](https://cloud.githubusercontent.com/assets/1457929/10200987/e52f354a-67a9-11e5-85df-580537c9f8e3.png)
  
This is specially confusing while hovering over stars:

![responsive-cr4](https://cloud.githubusercontent.com/assets/1457929/10201012/0701a612-67aa-11e5-8632-9248efd02d61.png)

**Comment by rtibbles** [comment]
Fixed in #4750
