### ISSUE TITLE
Delete my content rating button visibility 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4545]
Delete my content rating button visibility 

**Branch**: 0.15 (**ka-lite_0.15~b2-0ubuntu1_all.deb** installer  on Ubuntu 15.04, but it's not an installer issue)

**Current Behavior**: 

`Delete my review` button is visible even if the user did not leave any review (yet):

![responsive-cr](https://cloud.githubusercontent.com/assets/1457929/10201489/994437ae-67ac-11e5-945b-c15031a7ed05.png)

**Expected Behavior**:
I believe the user experience would be better if the button appeared only **after** they actually left the "review".

**Comment by MCGallaspy** [comment]
A valid point.

**Comment by rtibbles** [comment]
Fixed in #4548
