### ISSUE TITLE
KALite .PNG IMAGE DOES NOT LOAD

### ISSUE THREAD

**Issue by Revathikul** [learningequality/ka-lite#4553]
![ka_1](https://cloud.githubusercontent.com/assets/14935772/10239559/b044c222-6912-11e5-907d-6d4e11c597d9.png)
The attached is the screenshot of the issue.Please help

**Comment by cpauya** [comment]
Please indicate your OS, web browser, and the ka-lite installer version @Revathikul - they'll be helpful in tracing the issue.

**Comment by Revathikul** [comment]
WIndows 8.1
web browser i am trying many browsers from IE  , 10 and 11 and nothing works

**Comment by rtibbles** [comment]
Yeah, looks like an assessment item issue.

Is this the only question this happens on, @Revathikul, or does it happen on lots of questions?

**Comment by Revathikul** [comment]
@rtibbles Happens on all questions...Tried in safari browser as well, it doesnt work
