### ISSUE TITLE
On recent 0.14.1 builds the update english language button is missing

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite#4566]
On both Windows and MAC tests of the current 0.14.1 development build the button that updates the english language packs seems to be missing? 

![2015-10-02_17-58-29](https://cloud.githubusercontent.com/assets/4349806/10260399/5c806f5e-6932-11e5-8977-7e9ee3add749.png)

What it should look like? 
![2015-10-02_17-45-55](https://cloud.githubusercontent.com/assets/4349806/10260401/67984f7e-6932-11e5-810d-58d1613de8b1.png)

**Comment by aronasorman** [comment]
Fixed in #4587.
