### ISSUE TITLE
Installed languages panel is not updating properly

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4574]
Installed languages panel is not updating properly, neither language pack updates, nor new language pack installation.

**Branch**: 0.15, installer compiled by @MCGallaspy today on WinXP  

**Expected Behavior**: 
New language should appear as available in the **Installed languages** panel immediately after the successful language pack installation (at least that was the behavior on previous releases).

**Current Behavior**: 

1. Language pack updates: alert message reports successful update, but the red `Update` button is still present. I have no screenshot of this, so you'll have to take my word for it... :P

2. New language pack installation: alert message reports successful process, but the new language is not in the **Installed languages** panel.

![finished-langpack-es](https://cloud.githubusercontent.com/assets/1457929/10295000/e7d17a98-6bbd-11e5-8bba-0063b3aa4597.png)

Only after users navigate away from the **Languages** tab and return, they can see the new language as available. 

![finished-langpack-es2](https://cloud.githubusercontent.com/assets/1457929/10295006/efabf324-6bbd-11e5-96ff-4ad7294652e7.png)

Tested it with the German pack afterwards too, just to exclude some kind of delay, but it has been sitting the same as on above screenshot, and not updating the panel.
 
I'm guessing that this has something to do with the #4538 that has been fixed recently. 

**Steps to reproduce**:

1. Log in as Admin
2. Choose a new language pack to install or update the existing

**Comment by rtibbles** [comment]
@radinamatic Is the language pack available if you then refresh the page, or restart the server?

**Comment by radinamatic** [comment]
Yes, language pack is available after navigating somewhere else and back, it's just not appearing in the **Installed languages** panel immediately after the successful language pack installation, as it used to on previous releases. Maybe the "persistent"  `Update` button is even worse for the user as it gives contradictory info since alert message says update was successful.

**Comment by rtibbles** [comment]
Could you check the javascript console for errors?

**Comment by radinamatic** [comment]
Already did, no errors whatsoever appearing during the update process.

**Comment by radinamatic** [comment]
I'm downloading Danish now, but I suspect the result will be the same...

**Comment by rtibbles** [comment]
@radinamatic I am wondering if the language pack update process is not giving the correct signal back to the client somehow. Could you see what the output is of the most recent API call is on the network tab when the 'invalidating caches' step completes?

**Comment by radinamatic** [comment]
Will do, it's at it right now with Danish...

**Comment by radinamatic** [comment]
You were right (as usual) - there was an `Uncaught ReferenceError: process_log is not defined` error after the `Invalidate caches`:

![finished-langpack-da](https://cloud.githubusercontent.com/assets/1457929/10296168/58f5c12c-6bc6-11e5-9c47-38339c6148dc.png)

**Comment by rtibbles** [comment]
Fixed in #4576
