### ISSUE TITLE
Removing the single-dir mode

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4575]
Since we are removing Python 2.6 support, I gather there are a couple of old-time git based installations that we can remove support for as well. And I think in saying, we have been removing support for these a lot of times.

The single-dir mode is basically running kalite from the same directory as the application itself and the accessing all user data such as the database from that same directory.

This behaviour has the following drawbacks, which I don't think we need to discuss....

 * Application code and user data is mixed up. In some cases (possibly deprecated now), user data is/was even in the `kalite/` application folder.
 * Portability: How do you export your data from the app?
 * Packaging: When cleaning up and packaging a repo clone, we are forced to always create a new clone or run `git clean` out of sheer concern of shipping something that doesn't belong.
 * Settings are messed up because they account for two different possible locations of every single user-generated file.

I'm assigning @aronasorman  just to wrap up / facilitate the discussion :) Feel free to re-assign!!

@66eli77 please also comment about the state of the Android distribution, is it okay to pull out single-dir mode for 0.16, are you fine about setting the KALITE_HOME env?

**Comment by 66eli77** [comment]
the current Android apk is using KALITE_HOME env, which is point to /kalite folder

**Comment by benjaoming** [comment]
Great! Then I see no real challenge in removing this! :)

**Comment by MCGallaspy** [comment]
Doesn't seem to be a single issue *per se* so much as a a philosophy going forward.

**Comment by benjaoming** [comment]
Yes, and we might stick with it for test and dev purposes.
