### ISSUE TITLE
Subtitles not showing 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4578]
Subtitles not showing 

**Branch**: 0.15, installer compiled by @MCGallaspy today on WinXP, both FF & Chrome
Had the same issue on Ubuntu installation previously, but thought it was related to other problems I had with that install. Unfortunately, it seems not OS specific, though... :(

**Expected Behavior**: Subtitles should appear when activated through the `CC` button on the video player command bar.

**Current Behavior**: I have the updated EN & ES language packs; downloaded the two videos from the `/early-math/cc-early-math-add-sub-basics/cc-early-math-add-sub-intro/` category, and restarted the server. No JS or loading errors in the console for the `.srt` files when I try to activate them through the `CC` button (just the below warning about MIME types), but no subs either :( 

![nosubs](https://cloud.githubusercontent.com/assets/1457929/10295813/aae88d46-6bc3-11e5-8373-5182c7145b14.png)

The `GET` error below appears when I press the Pause button to stop the video, so not sure if it's related:  

![nosubs2](https://cloud.githubusercontent.com/assets/1457929/10295842/de6b50b8-6bc3-11e5-90e1-b8a0f911e18a.png)

I opened all 4 `srt` files in text editor, there's nothing apparently wrong with them...

**Comment by MCGallaspy** [comment]
Seems pretty important. Adding to my queue. Will discuss implications in tomorrow's dev meeting.

**Comment by radinamatic** [comment]
Could this be a version problem? See #4151 for context.

`package.json` says `4.11.4`, but `bundle_videos.js` says `VERSION="4.12.15"`:


![video js](https://cloud.githubusercontent.com/assets/1457929/10298204/742ab40a-6bdc-11e5-9319-88a56d03569f.png)

**Comment by rtibbles** [comment]
This is almost certainly my mess, will clear up.
