### ISSUE TITLE
Not all assessments listed in the side bar are available to the user.

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite#4583]
After installation On MAC and after downloading language packs to the installation on XP, I find that not all of the assessments are available to the user after 0.15 installation. Because they appeared to be available immediately after the XP installation but are then "deactivated" after some time or by downloading the language packs (not sure what the cause is.) I do not feel like they are missing but are some how just being "grey-ed out" or "deactivated" by some process. 

![2015-10-06_17-30-12](https://cloud.githubusercontent.com/assets/4349806/10325702/fce01d34-6c50-11e5-8588-19ba0783978e.png)

![2015-10-06_17-31-21](https://cloud.githubusercontent.com/assets/4349806/10325709/15c015a2-6c51-11e5-8d1f-8b4c8481efd5.png)

**Comment by EdDixon** [comment]
But then again they do appear to be missing when opened as above. So I honestly have no clue?

**Comment by radinamatic** [comment]
@EdDixon Did you try the script from #4182? 

```
bin/kalite shell
...
from kalite.topic_tools import get_exercise_cache
cache = get_exercise_cache()
for key, value in cache.iteritems():
    if not value.get("available", False):
        print key
```

**Comment by EdDixon** [comment]
Thanks Radina, I have not tried that but this seems to have to do with them not being available rather than missing on a fresh reinstall on both MAC and Windows of the same 0.15 develop installer. I have two different outcomes. But what is more concerning is that the assessments that were listed in the side bar suddenly were not there after a period of time and downloading some language packs on XP Yesterday. This is the result of the clean install tests and the particular assessment used as a sample above:

Install on Mac.
Check for Assessments missing.  Missing some assessments
Restart Server.
Check for Assessments Missing. Missing some assessments
Download a video.
Restart server.
Check for assessments missing. Missing some assessments
Restart server.
Download Language pack.
Restart server.
Check for Assessments Missing. Missing some assessments

ON XP:
Check for Assessments missing. All there and working
Restart Server.
Check for Assessments Missing. All there and working
Download a video.
Restart server.
Check for assessments missing. All there and working
Download Language pack.
Restart server.
Check for Assessments Missing.All there and working

Which in the case of XP had been the outcome before but then later as I stated the assessments suddenly were not available as described above? 

Assessment Listing MAC:

![2015-10-06_19-05-32mac top veiw](https://cloud.githubusercontent.com/assets/4349806/10343162/c0cb5e6a-6cd9-11e5-8257-c6113e617b80.png)

Assessment Listing XP:

![2015-10-06_19-11-33xp top view](https://cloud.githubusercontent.com/assets/4349806/10343181/dddad940-6cd9-11e5-9b30-35bae9f8b3bf.png)


Working Assessment previously not working on XP now working in XP
![2015-10-06_18-39-55xpfirstassignmentpresent](https://cloud.githubusercontent.com/assets/4349806/10343238/2105ab82-6cda-11e5-8736-9e8effe721c8.png)

I wish I could provide more to go on here as I have no clue how this can be.

**Comment by amodia** [comment]
Hi @EdDixon  I cannot reproduce this issue on windows xp  with a fresh installation. I followed your instructions above, here's my screenshots. 

![screen shot 2015-10-08 at 8 50 46 pm](https://cloud.githubusercontent.com/assets/8663934/10367184/9b9ed27e-6e01-11e5-907c-e5032fbc45f9.png)

![screen shot 2015-10-08 at 9 16 30 pm](https://cloud.githubusercontent.com/assets/8663934/10367240/dfc1fb20-6e01-11e5-8315-5c724e87dc72.png)

![screen shot 2015-10-08 at 8 56 24 pm](https://cloud.githubusercontent.com/assets/8663934/10367272/08bcf70a-6e02-11e5-84aa-c61ccfccde8a.png)

![screen shot 2015-10-08 at 8 01 11 pm](https://cloud.githubusercontent.com/assets/8663934/10367299/24985794-6e02-11e5-889b-4906b450643d.png)

**Comment by cpauya** [comment]
Hi @ed, I tried this on a fresh VM of OSX Yosemite and was not able to replicate.  I have tried combo fresh install, downloaded a video, downloaded a language pack, restarted the server, and enabled a language pack but with no dice too.  Btw, I used Safari v8.0.8.

Pls refer to these screenshots:
![osx-yosemite-3](https://cloud.githubusercontent.com/assets/175580/10367815/197714b0-6e05-11e5-8224-31ddcbf8be54.png)

Here's a shot of the sidebar after downloading the French language pack:
![osx-yosemite-4](https://cloud.githubusercontent.com/assets/175580/10367847/4601f18a-6e05-11e5-8c53-52bd61d1065b.png)

**Comment by EdDixon** [comment]
I have not had any luck replicating the issue on Windows XP here either. I have been trying since running into this issue with no luck so far. Very glad to hear the new build for OSX has resolved this for MAC. I will close for now and continue to try and replicate it here.
