### ISSUE TITLE
File is not a zip file language pack is corrupted.

### ISSUE THREAD

**Issue by arceduardvincent** [learningequality/ka-lite#4589]
__Branch:__  0.15.x

**Expected behaviour:** Show an appropriate message, Example if the user try 5 unsuccessful download we will show a message like "Currently the download source is not available, Please try again later." . In these case the user will not wait to long coz they know that the download source is not yet available.

**Current behaviour:** Can't download language pack and it return an error 'Error during update:File is not a zip file language pack is corrupted. Please try downloading language pack again in a few minutes'. 
I wait momentarily then the download succeed however it will took you a long period of time. In my case it took me 1hr+.
![screenshot 2015-10-07 15 43 44](https://cloud.githubusercontent.com/assets/4099119/10356551/e7fd1d80-6daa-11e5-97d4-17017d84cc66.png)

**Steps to reproduce**
>1. Login as Admin.
>1. Navigate to `Language` tab.
>1. Select language then click the `Get language pack`.
>1. Notice that it will return an error 'Error during update:File is not a zip file language pack is corrupted. Please try downloading language pack again in a few minutes'.

**Comment by aronasorman** [comment]
Fixed in https://github.com/learningequality/ka-lite/pull/4591. Please comment here if you still encounter this error.

**Comment by shreyasmahimkar** [comment]
I am still getting this error on 0.15.0 kalite version when I am trying to install Swahili language pack.

**Comment by EdDixon** [comment]
Hi @shreyasmahimkar ,

I just tried to replicate this error using a windows installation, but it did not replicate. Can you provide more details on the installation and hosting operating system? Also, the server does have to be restarted after downloading the language packs. I am assuming you are doing that.

**Comment by shreyasmahimkar** [comment]
Hi @EdDixon,

It worked today morning. I just restarted my raspberry pi and it started working :+1: 

Yes. I was using it on Raspberry pi on the below version.
Linux pi-15294 3.18.7-v7+ #755 SMP PREEMPT Thu Feb 12 17:20:48 GMT 2015 armv7l GNU/Linux

Thanks a ton!
