### ISSUE TITLE
Kalite incorrectly reports video collection sizes

### ISSUE THREAD

**Issue by m-anish** [learningequality/ka-lite#4596]
On master (0.14.x), in EN langauge, kalite reports certain collections filesizes, but the actual downloaded filesizes are different, in some cases, VERY different. Please check the table below. 

collection|kalite-reported-size | actual-size-on-disk
------------|-------------------------|----------------
**arts-and-humanities**|**13**|**82**
**science**|**33**|**45**

These are some examples, there are other mismatches in filesizes as well.

**Comment by radinamatic** [comment]
I remember noticing this too some time ago: #4214.

**Comment by MCGallaspy** [comment]
Thanks for the heads up @m-anish

**Comment by aronasorman** [comment]
Will fix with the new i18n pipeline.

**Comment by rtibbles** [comment]
Please confirm this is fixed with content pack timeline, @aronasorman

**Comment by benjaoming** [comment]
There's another possible issue in the new video download: #4950

However, this seems to be extent, since the interface mentioned has been replaced.

Thanks for reporting!
