### ISSUE TITLE
Progress bar obscures video

### ISSUE THREAD

**Issue by craigleat** [learningequality/ka-lite#4604]
branch: 0.14
client: chrome browser on android, 7" tablet

The video progress bar obscures the video content. See attached screenshot. Try hiding the progress bar by default.
![screenshot_2015-10-12-16-08-11](https://cloud.githubusercontent.com/assets/12593105/10431295/90fe2364-7104-11e5-8a57-bad995e834e3.png)

**Comment by radinamatic** [comment]
I don't have 0.14 installed atm to test, but isn't the progress bar supposed to fade-out when the user is inactive, and cursor is not hovering the player? I'd say it's a feature, not an issue...

@craigleat Could you confirm that the progress bar stays visible on top of, or covering, the video, even if you do not move your mouse or place it outside the player? Or does progress bar fades out and disappears?

**Comment by craigleat** [comment]
I'm browsing the content with a touch screen tablet, so there's no mouse cursor. But I discovered the progress bar DOES fade-out if I touch outside the window. Thanks for the tip ;) Please mark the issue as closed.
