### ISSUE TITLE
Cannot hide scratchpad

### ISSUE THREAD

**Issue by craigleat** [learningequality/ka-lite#4605]
branch: 0.14
client: chrome browser on android, 7" tablet

Once activated the scratchpad cannot be hidden and the scratch marks persist when a new exercise appears. I can draw on the "hide scratchpad" button but cannot activate it.

**Comment by 66eli77** [comment]
Tested on 
branch: develop and 0.15.x
client: chrome browser on android, 7" tablet 
the issue is not observed

**Comment by rtibbles** [comment]
Assumed fix by @66eli77's report.
