### ISSUE TITLE
client browser crash (firefox)

### ISSUE THREAD

**Issue by craigleat** [learningequality/ka-lite#4606]
branch: 0.14
client: firefox browser on android, 7" tablet

firefox crashes when trying to load a video. The crash occurs while the video is loading and before playback. chrome works fine.

**Comment by 66eli77** [comment]
Tested on 
branch: develop and 0.15.x
client: firefox browser on android, 7" tablet 
the issue is not observed

**Comment by rtibbles** [comment]
Assumed fixed by @66eli77's report.
