### ISSUE TITLE
%hintsLeft on exercises

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#4619]
on 0.15.x mac installer:

![screen shot 2015-10-13 at 09 47 53](https://cloud.githubusercontent.com/assets/191955/10461715/97dc6e3a-718f-11e5-9be0-ff6eb0d062a3.png)

**Comment by MCGallaspy** [comment]
Are you sure the installer you used incorporates the PR from yesterday meant to address this issue? See https://github.com/learningequality/ka-lite/pull/4607

**Comment by radinamatic** [comment]
Described the same in #4602 on Windows, not sure if it was already fixed by  #4607.

**Comment by radinamatic** [comment]
Wow, @MCGallaspy beat me for 21 seconds... :P

**Comment by aronasorman** [comment]
@MCGallaspy it uses the one I built this morning. Do I need to run `setup` though? Let me try that.

**Comment by rtibbles** [comment]
Yeah, this should work fine for English, and give English for plural translations due to our broken ngettext implementation.

**Comment by aronasorman** [comment]
Just needed to run `setup` again.

**Comment by MCGallaspy** [comment]
Is setup a required manual step for OSX installation? Anyway, works ok on Windows.

**Comment by aronasorman** [comment]
We might not be running it during upgrading. @cpauya can you confirm?

**Comment by rtibbles** [comment]
We should run it during upgrade, as collectstatic is now delegated to it!

**Comment by cpauya** [comment]
Yes, setup is NOT ran during an upgrade because it detects that a database already exists.

User can click on `Advanced -> Setup` button again as @aronasorman did above.

I have created [Run setup during upgrade.](https://github.com/learningequality/installers/issues/224) on this.
