### ISSUE TITLE
Forward admin user to Manage tab after device registration

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4622]
Forward admin user to Manage tab after device registration - small improvement.

**Branch**: develop  

**Current Behavior**: 
After the successful device registration, admin user is left sitting duck on the confirmation page.

![forward-to-manage](https://cloud.githubusercontent.com/assets/1457929/10470531/24d02d26-720e-11e5-9570-6368f19ae18a.png)

I suggest that implementing the automatic forward to the Manage tab after, say 10 seconds, would be a better UX.

**Steps to reproduce**:

1. Log in as Admin on a new device.
2. Register device.
3. Enjoy watching the `Congratulation` message.

**Comment by radinamatic** [comment]
Very minor issue, punt or close @benjaoming!

**Comment by benjaoming** [comment]
I noticed this, too. I agree very much that it should be fixed.

**Comment by benjaoming** [comment]
Alright, done :)
