### ISSUE TITLE
NotABug | Customize kalite user directory

### ISSUE THREAD

**Issue by m-anish** [learningequality/ka-lite#4625]
Have a technical question. Is there an easy way to customize the kalite user directory in the pip install method. By default I guess kalite user data including videos gets installed to ~/.kalite. Is there a supported method to change that, other than creating a symlink which I am currently doing.

**Comment by MCGallaspy** [comment]
Set the `KALITE_HOME` environment variable to the desired directory. You can copy your existing .kalite directory to that location prior to starting the server in order to maintain existing data.

**Comment by MCGallaspy** [comment]
See the development version of the docs, someone else had a similar question: http://ka-lite.readthedocs.org/en/develop/faq.html#how-do-i-change-the-directory-where-all-of-ka-lite-s-runtime-files-go-including-content
