### ISSUE TITLE
Ka-lite logging shows Assertion Error

### ISSUE THREAD

**Issue by vishal3105** [learningequality/ka-lite#4629]
Expected Behavior: I expect students to be able to log-in and carry on with their work. I now have to create a new log-in although their data is still in the database (See screen shot, as an example look at student iviwe dumayo.)
Current Behavior: Whenever I try to log-in with this student, I get the following Assertion Error:
AssertionError: There should never be multiple summaries in the same time period/device/user/type combo

Please let me know how to fix this error: vishal@zaya.in Thank you!

![57a7ea4a-70fb-11e5-9fc7-d48339322a04](https://cloud.githubusercontent.com/assets/10860506/10509758/8d1d4910-734c-11e5-9cdc-528af4bc5800.png)

**Comment by rtibbles** [comment]
Hi Vishal - we didn't even know you guys were still using KA Lite at Zaya! If you have some more info about your deployments, our implementations team (implementations@learningequality.org) would love to hear more about what you guys have been up to, and put you on our map (learningequality.org/ka-lite/map).

Unfortunately, this is an extant bug on version 0.12 - which is no longer supported. We recommend upgrading to a newer version of KA Lite.

**Comment by rtibbles** [comment]
No longer extant in supported versions of KA Lite. Closing.
