### ISSUE TITLE
Delete or rephrase the Spanish language content entry in the FAQ sections of the docs

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4636]
Delete or rephrase the Spanish language content entry in the FAQ sections of the docs

The current entry reads:

```
Is there somewhere I can find Spanish language content organized by topic?

Yes! Thanks to the efforts of an awesome volunteer deploying KA Lite and other
OER in the Sacred Valley in Peru, you can download blocks of Spanish Lanugage
content from his public Google Drive folder. You can also follow 
his deployment at http://www.huacamayu.org/.
```

I don't know if the Google Drive folder has been placed elsewhere, but the one linked from our docs does not contain **blocks of Spanish Language content** as stated. 

Furthermore, the above domain is not valid, and it seems that the whole project has stalled with [no updates in the past 18 months](https://huacamayu.wordpress.com/).

**Comment by radinamatic** [comment]
IMHO this should be deleted from the docs, but it's not urgent. Assign the issue to me and punt to 0.17 @benjaoming.

**Comment by benjaoming** [comment]
@radinamatic please feel invited to delete it from the docs. There's now a develop branch of the docs on RTD where you can super-user-friendily click the "Edit on Github" button top right :)

http://ka-lite.readthedocs.org/en/develop/
