### ISSUE TITLE
Handle assessment item db as readonly system-wide data

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4638]
In 0.15, I had to do a hotfix in the debian dist, because assessmentitems.sqlite was unpacked the same place as all the other data.

However, if we can somehow make Django use it as a readonly sqlite DB, that'd be great.

Otherwise, we have to figure out a way to copy it into a user-writeable location.

**Comment by rtibbles** [comment]
assessmentitems.sqlite no longer exists.
