### ISSUE TITLE
Re-activate the video player speed setting

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4639]
Re-activate the video player speed setting  

**Branch**: 0.15  

**Expected Behavior**: Up to release 0.15 video player had a speed setting in the control bar that allowed to set the playrate to slower or faster.

**Current Behavior**: Video player speed setting has been lost, probably as the consequence of the `video.js` version upgrade.

**Comment by rtibbles** [comment]
I have a bad feeling this actually got dropped from videojs itself.

**Comment by radinamatic** [comment]
There must be a plugin, then, if I remember correctly... I'll dig in my notes and find out.

**Comment by radinamatic** [comment]
According to the pic on their blog, it's still there:

![VideoJS UI](http://40.media.tumblr.com/7936bfddeddf68058784eb6d815cd631/tumblr_inline_nveuwhsdFu1qzc111_540.png)

**Comment by radinamatic** [comment]
https://github.com/videojs/video.js/blob/v4.11.4/docs/api/vjs.Player.md#playbackrate-rate-

**Comment by rtibbles** [comment]
Mea culpa.

**Comment by rtibbles** [comment]
Fixed in #4917
