### ISSUE TITLE
Windows Installation to secondary drive not effective

### ISSUE THREAD

**Issue by mmutee** [learningequality/ka-lite#4644]
Hello. I am not a very technical person but I wanted to report some problems with Windows (v 0.15.0) installation of KA lite. Using Windows 7 32bit, I installed the program in "D:\KA Lite\". Upon downloading videos via KA Lite interface, I discovered that all content was being stored in "C:\Users\Mutee\.kalite\content". If I move the videos to the appropriate content folder in the original install directory (D:\KA Lite\ka-lite\content), the files are not found by the program. Since I don't have a lot of space in C drive, this is troublesome.

**Comment by MCGallaspy** [comment]
Hi @mmutee, you can set the directory where KA Lite files are stored using the environment variable `USER_DATA_ROOT`. [See this SO answer on setting environment variables in Windows](http://stackoverflow.com/questions/31177463/set-environment-variables-windows). If you copy your existing directory to the location you set *before* starting the server, it should seamlessly pick up the content you've already downloaded.

**Comment by MCGallaspy** [comment]
I am checking the documentation to make sure this feature is clearly indicated.
