### ISSUE TITLE
Silverlight content not visible in any browser I have

### ISSUE THREAD

**Issue by mmutee** [learningequality/ka-lite#4645]
Using the v0.15.0 of KAlite for Windows 7 x86, the Silverlight content does not show in Firefox (v41.0.2). All the addons were disabled for the test (like Adblock) and Silverlight is set to "Always Activate".

![silverlight not working1](https://cloud.githubusercontent.com/assets/15348404/10768788/9d63f38e-7d04-11e5-9e0b-17aa1df1f803.png)

The plugin is installed and working.

![silverlight not working_verify install](https://cloud.githubusercontent.com/assets/15348404/10768857/ec605766-7d04-11e5-9e6b-858e49aa8f95.png)

I can drag the embedded object out of the browser and if I drop it back in browser it displays.

![silverlight not working_verify install2](https://cloud.githubusercontent.com/assets/15348404/10768872/03b7338a-7d05-11e5-915b-aee2b5d72710.png).

I also tested the pages in Opera (v12.16), Vivaldi (v1.0.118.19), Chrome (v46.0.2490.71) with same results.

**Comment by MCGallaspy** [comment]
We don't use the silverlight plugin as far as I know. However, I'll check that content is displaying correctly before closing this.

**Comment by MCGallaspy** [comment]
Works on 0.16.x using Firefox 44.
