### ISSUE TITLE
Arrangement of video files

### ISSUE THREAD

**Issue by mmutee** [learningequality/ka-lite#4646]
This is not a version related problem but about the way the videos are labelled and stored. The file names are not relevant so there is no way you can arrange and transfer them as needed. For example, I just wanted the Maths, Physics, Chemistry and Biology videos but I cannot start download all at once due to space restrictions. If using Ka lite's interface to download, all the files are placed in the "content" folder with no way of recognizing which files belong to which topic/category and I will be forced to transfer and store all videos together (even when I do not need them all in one place due to various reasons like space, only focusing on one subject at a time etc).

If I grab the videos from torrent, the same problem returns where I have to download all the content (most of which is not required by me) and store it together.

A) is there a Subject-wise list of videos that I can use to download files sequentially, subject-by-subject and use them separately.

B) Can more torrents be made but divided by subjects instead of a single file?

**Comment by MCGallaspy** [comment]
Hi @mmutee. Thanks for the feedback. We're considering this issue in future versions of the software, however at this time the only way to manage video downloads is through the admin interface or, as you note, by downloading all the videos in bulk and unpacking the files in the content directory.

Perhaps another team member can chime in about the possibility of creating subject-specific torrents -- if you create one, we'd certainly be happy to publicize it!

**Comment by mmutee** [comment]
Since I don't have the complete set of videos I cannot create the torrents. However, I can provide Windows batch scripts that, when executed inside the folder containing all the videos, will move all the files to relevant folders (like all 199 MP4s and PNGs of Calculus will be moved to a folder "Calculus"). This then can be used to create the new torrents.

![batch script to rearrange files](https://cloud.githubusercontent.com/assets/15348404/10860379/0014ae52-7f89-11e5-95b8-a498f555b776.GIF)

Secondly, as a solution to my problem, I can take the Youtube URL lists (as used above) and write a script to download files using the "Youtube-dl" program. Will KA Lite have trouble playing videos of different resolution/size?

**Comment by MCGallaspy** [comment]
> Will KA Lite have trouble playing videos of different resolution/size?
@rtibbles or @jamalex could provide an answer more readily than me. I don't think it matters, interested to hear your results.

**Comment by benjaoming** [comment]
Since we cannot create file system links in a cross-platform friendly manner, and we know that the video IDs are reused across different topics, it's hard to achieve the above goal.

Ideally, the user should be able to see the file system location of a video if logged in as admin.

I'm going to close this, but if someone wants to create an informational list view of all videos downloaded with titles and file system paths, I think they should do so! The use case is good!
