### ISSUE TITLE
Some translated strings still being displayed in English

### ISSUE THREAD

**Issue by jinchuika** [learningequality/ka-lite#4650]
**Version**: 0.15

The Spanish translations page shows that 0.15 is translated at 99%. But some words still in English.
- In the tabular report, the titles for the themes are not translated; but they are shown translated in the topic-tree from the sidebar. Also, the word "Question" is still not translated.
  ![selection_016](https://cloud.githubusercontent.com/assets/5230176/10822212/d4061d1e-7e1b-11e5-8245-db7af533dafd.png)
- The string "I'd like another hint" is not translated in the plural form. But it is translated as seen in the [CrowdIn page](https://crowdin.com/translate/ka-lite/28881/en-es#1984757)
  ![selection_020](https://cloud.githubusercontent.com/assets/5230176/10822303/2e4ec992-7e1c-11e5-89ba-024c0c633717.png)
- The topic name and description isn't translated from the recommendations section in the home screen.
  ![selection_018](https://cloud.githubusercontent.com/assets/5230176/10822340/61aca6d8-7e1c-11e5-97f6-f54b90d17e14.png)

**Comment by aronasorman** [comment]
Hi Luis,

Thank you for bringing this to our attention. I won't be doing any
development today, but I'll take a look at this tomorrow or early next
week.

**Comment by jinchuika** [comment]
Found another part which is not showing translations.

![selection_004](https://cloud.githubusercontent.com/assets/5230176/11000399/252ffdb2-8467-11e5-962d-ee4cdddc8403.png)

**Comment by benjaoming** [comment]
Seems this was fixed long ago through PRs, CrowdIn rebuilds and new content packs :) Good job! And thanks for reporting @jinchuika !
