### ISSUE TITLE
v15 can't logon using Internet Explorer 11

### ISSUE THREAD

**Issue by waltonrp** [learningequality/ka-lite#4655]
v15 KaLite running on Ubuntu 15.04. I can logon to KA Lite using Firefox or Chrome from Windows clients. I cannot logon using Internet Explorer 11 running in Win 7 or Edge running in Win10. It's not recognizing password. This happens with admin, coach and learner logons.

**Comment by waltonrp** [comment]
Additional information. The server I installed today and had an issue logging on to from IE is a clone of the server I have at my office. Using the same laptop as client, I was able to log on the office server when I returned this afternoon. Both using IE and Edge worked perfectly.

I played videos off the server I installed, so I know the network is good, but am wondering if it's the cloning. I use Clonezilla. I'll troubleshoot a bit further, maybe clone another drive over the weekend.

**Comment by EdDixon** [comment]
Hi Robert, I have tested this quite a bit without issues (not cloning) but, using the Edge and IE11 browsers on our current 0.15.0 version without issue. I have started to prefer Edge over even Chrome at this point which for me is pretty amazing. I do know that we are using session cookies (which is something you need to be aware of anyway) in this version and feel it may have something to do with what you are experiencing with these issues. Clearing all cookies before attempting to login may get around this for now if my hunch about this is correct?

**Comment by waltonrp** [comment]
Good idea. So just clearing the cookies in the browser is what you suggest? If you saw my update, everything worked fine off the same client when I logged on to the master server at my office.

Robert Walton
Regional Information Technology Specialist
DOC – CTSU – Field Services Unit
Sent from my iPhone

On Oct 30, 2015, at 7:53 PM, Ed Dixon <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Robert, I have tested this quite a bit without issues (not cloning) but, using the Edge and IE11 browsers on our current 0.15.0 version without issue. I have started to prefer Edge over even Chrome at this point which for me is pretty amazing. I do know that we are using session cookies (which is something you need to be aware of anyway) in this version and feel it may have something to do with what you are experiencing with these issues. Clearing all cookies before attempting to login may get around this for now if my hunch about this is correct?

**Comment by EdDixon** [comment]
Hi Robert,

Please do let us know if that seems to resolve the issue, I have no way to
try and replicate it here.

Thanks,

Ed Dixon
Corrections Adviser
Foundation for Learning Equality <http://learningequality.org/>
Give to FLE, Support FLE via Amazon Smile!
<https://learningequality.org/donate/>
M (575)-201-3691

**Comment by waltonrp** [comment]
Ed,

Deleting cookies did not work. I've tried this in several locations(wireless/domain) with several KALite servers running v15. All the KA LIte servers have a static IP and are not joined to the domain. I can log on to KA LITE using IE or Edge when on my home network (wireless/workgroup). I'm not joining any of these machines to the domain or doing any group policy to secure IE, problem happens when I access KA LIte from domain member and non domain member clients.

**Comment by rtibbles** [comment]
Could you give a screenshot of what happens when you do attempt to login?

Also, if you could press "F12" before logging in, and click on the 'Console' tab that appears, and take a screenshot of anything that appears in there when you attempt to login, that would also help.

**Comment by waltonrp** [comment]
There is nothing to show via screen shot. I type user name and pwd, enter. The login window flickers and then come back blank.

Robert Walton
Regional Information Technology Specialist
DOC – CTSU – Field Services Unit
Sent from my iPhone

On Nov 3, 2015, at 11:57 AM, Richard Tibbles <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you give a screenshot of what happens when you do attempt to login?

Also, if you could press "F12" before logging in, and click on the 'Console' tab that appears, and take a screenshot of anything that appears in there when you attempt to login, that would also help.

**Comment by waltonrp** [comment]
Here is a screenshot from MS Edge, after I enter username and password


![kalite logon issue source](https://cloud.githubusercontent.com/assets/9379591/10973187/42017ea6-83aa-11e5-8c74-823a2c05ef5a.png)

**Comment by EdDixon** [comment]
Thanks Robert, can you get a screenshot of the next tab over of the console?

**Comment by waltonrp** [comment]
Can you call me 804-212-5765?

Robert Walton
Regional Information Technology Specialist
DOC – CTSU – Field Services Unit
Sent from my iPhone

On Nov 5, 2015, at 10:49 AM, Ed Dixon <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks Robert, can you get a screenshot of the next tab over of the console?

**Comment by EdDixon** [comment]
Thanks for the call this morning glad to hear the other deployments are moving forward! I just want to update this with a capture of the console will be provided here as soon as possible. So the dev team knows where we are on this. Please know your help in reporting things you have encountered is very appreciated by all of us. Keep them coming!

**Comment by MCGallaspy** [comment]
I can't replicate this. It may have something to do with cloning, as @waltonrp suggests, but I have no easy way of testing that. Please let me know if any new information comes to light.
