### ISSUE TITLE
Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method SqliteDict.__del__ of SqliteDict(/home/pi/.kalite/channel_cache_data/contents.sqlite)> ignored

### ISSUE THREAD

**Issue by Aypak** [learningequality/ka-lite#4659]
Everytime i start kalite on my raspberry pi i get the error above. I have installed v0.15 according to the instructions in the documentation, and manually added the khan_assessment.zip file. When i stop the server with the kalite stop command, i get the message Already stopped: unclean shutdown

**Comment by benjaoming** [comment]
Confirming that this is also a problem on the latest ka-lite-bundle .deb. Not a released one, just what I'm working on ATM.

**Comment by benjaoming** [comment]
After removing the .kalite directory and reinstalling everything works. Suspecting a 0.16 version of contents.sqlite or likewise to be the cause of this. @Aypak any chance you had a development installation of kalite before trying this?

**Comment by benjaoming** [comment]
Nevermind, this actually happens everytime the server is reinstalled in any way -- even though the versions are identical.

**Comment by benjaoming** [comment]
I'm not sure what caused this: Note to self: Post a proper traceback and steps to reproduce, otherwise things will seem very blurry 7 months later...
