### ISSUE TITLE
Modals on deployment map don't scroll on Mac OS

### ISSUE THREAD

**Issue by fbui** [learningequality/ka-lite#4661]
Deployments map on Learning Equality website: https://learningequality.org/ka-lite/map/
On Mac OS, the modals that open up after clicking on green houses cannot scroll down. 

<img width="783" alt="screen shot 2015-11-10 at 12 46 41 pm" src="https://cloud.githubusercontent.com/assets/10431552/11075285/4d9444a8-87a9-11e5-8d12-ff9c52a6f7b1.png">

Using the arrow keys while the modal is open scrolls the map underneath instead.
![bug](https://cloud.githubusercontent.com/assets/10431552/11075327/9f98e86c-87a9-11e5-922f-02c773cd7de5.gif)

**Comment by 66eli77** [comment]
Hi @fbui  this repo is for kalite the software. Can you move this issue to https://github.com/fle-internal/fle-home  ? thank you
