### ISSUE TITLE
download size of videos not being properly displayed

### ISSUE THREAD

**Issue by gwong89** [learningequality/ka-lite#4663]
Whether its a bulk download or single download, the download button does not properly update the size of the download after selecting file(s) to download

![Image of download error]
(http://s22.postimg.org/bsehusvm9/Screenshot_2015_11_10_18_30_53.png)

**Comment by benjaoming** [comment]
This was a known error previously and fixed, sorry that I'm too lazy to look up the issue report and PRs related, but it's fixed in 0.16, I promise :)
