### ISSUE TITLE
0.15 Raspberry Pi / Linux Install Not Completeing

### ISSUE THREAD

**Issue by j-schwartz** [learningequality/ka-lite#4664]
Branch: Master
Expected Behavior: Update KA-Lite from 0.13.1 and 0.13.2 to 0.15 following instructions here:
![image](https://cloud.githubusercontent.com/assets/9270388/11130531/64aeff9c-893a-11e5-80fb-f971c44e6069.png)

Current Behavior: Errors reported (below)

Steps to reproduce: 

```
pi@rachel:~$ sudo wget https://learningequality.org/r/deb-pi-installer-0-15 --no-check-certificate
```
![image](https://cloud.githubusercontent.com/assets/9270388/11130589/af3d347a-893a-11e5-8e02-719d07682dae.png)

so I edited command to initiate the deb-pi-installer-0-15, which overcame that issue:

![image](https://cloud.githubusercontent.com/assets/9270388/11130613/d2757420-893a-11e5-9e66-8a725047c7b2.png)

however, further in the process, when agreeing to download assessment items:

![image](https://cloud.githubusercontent.com/assets/9270388/11130638/efd5742a-893a-11e5-8045-e7361f5bfb6e.png)

Upon reboot, process has not completed at nginx fails due to address already in use.  old version of KA-lite does boot still.

**Comment by MCGallaspy** [comment]
So you have two errors: something happened when you tried to install the ka-lite-raspberry-pi package (more on that in a bit), and you say that:

>Upon reboot, process has not completed at nginx fails due to address already in use. old version of KA-lite does boot still.

Can you elaborate on that? Which process does not complete? As a guess, I'd say you must first stop the old version of ka-lite (0.13.x) and then try to start the new version.

Regarding the failed install, as a workaround you could choose *not* to download the assessment items, and then complete that after successful installation using the following steps.

1. Download the assessment items file from `http://pantry.learningequality.org/downloads/ka-lite/0.15/content/khan_assessment.zip`
2. Run the command `kalite manage unpack_assessment_zip <filename>`, where you replace `<filename>` with the file down just downloaded. Example: `kalite manage unpack_assessment_zip my_cool_zip_file.zip`

@benjaoming however might have more insight into why the installation failed in the first place.

**Comment by j-schwartz** [comment]
I passed on installing the exercise data and received the following, I also stopped KA-Lite manually before running the install, however the install looks to stop KA-Lite as an initial step I believe:

![image](https://cloud.githubusercontent.com/assets/9270388/11132031/7801a3bc-8942-11e5-8a56-00ec4008056a.png)

**Comment by j-schwartz** [comment]
BTW, this installer is now labeled 0-15.1, it was 0-15-0 a few minutes ago, just so you know I'm grabbing stuff live.

**Comment by MCGallaspy** [comment]
> BTW, this installer is now labeled 0-15.1, it was 0-15-0 a few minutes ago, just so you know I'm grabbing stuff live.

Curious, it's still 0.15.0 for me... are you sure it's not appending a `1` because you downloaded a file with the same name twice?

**Comment by MCGallaspy** [comment]
BTW, I was seeking clarification on this statement:

>Upon reboot, process has not completed at nginx fails due to address already in use. old version of KA-lite does boot still.

**Comment by j-schwartz** [comment]
Sorry about that, I thought I had pasted in a picture of the nginx issue:

![image](https://cloud.githubusercontent.com/assets/9270388/11134931/96c5d85a-8955-11e5-8ac1-6b8f17c1f0da.png)

**Comment by MCGallaspy** [comment]
Can you also describe the steps you took to install 0.13.x in the first place?

**Comment by j-schwartz** [comment]
I wish I remembered, but I really don't.  I am 99% sure there wasn't
anything unusual about my install, except I vaguely recall having to add a
script at boot that prevents the user data from locking up on shutdown and
preventing KA-Lite from rebooting.  Is there anyway I can check out a
current config and tell how I installed it?

**Comment by MCGallaspy** [comment]
Did you use the setup script from this repo? https://github.com/rachelproject/rachelplus

**Comment by j-schwartz** [comment]
No, that's just the one we use on the CAP device (which I don't have any
more).  I think for 0.13 I was still cloning into the LE github and running
setup scripts that way.

**Comment by MCGallaspy** [comment]
Okay, I'll try to replicate your error and offer suggestions based on that.

**Comment by j-schwartz** [comment]
Is 0.14 available somewhere I can get and try incremental upgrades in the
meantime?  Many thank you's for the help.

**Comment by MCGallaspy** [comment]
See here: http://pantry.learningequality.org/downloads/ka-lite/0.14/installers/

**Comment by MCGallaspy** [comment]
Try this one specifically: http://pantry.learningequality.org/downloads/ka-lite/0.14/installers/debian/ka-lite-raspberry-pi-0.14.2.deb

**Comment by j-schwartz** [comment]
Thanks - I hadn't seen this earlier, but 0.13 to 0.14 requires installing
in a new location and migrating.  I'm guessing that's my hold up with 0.13
to 0.15 as well.  Going to try with a clean image shortly.

**Comment by j-schwartz** [comment]
I was unsuccessful with 0.15 in a new location with a new user:

[image: pasted1]

**Comment by MCGallaspy** [comment]
I suspect the main issue is the dpkg errors out before the installation can complete, but I'll let you know as soon as I'm done testing it out.

**Comment by MCGallaspy** [comment]
I think you'll be able to successfully install KA Lite 0.15.0 from the deb file if you first manually undo some configuration done by installing 0.13.x. Try these steps

1. Remove the `/etc/init.d/kalite` script installed by 0.13: `sudo rm /etc/init.d/kalite`
2. Unregister the ka-lite service: `sudo update-rc.d kalite remove`
3. Remove 0.13 nginx configuration files:
  1. `sudo rm /etc/nginx/sites-available/kalite` 
  2. `sudo rm /etc/nginx/sites-enabled/kalite`
3. Install 0.15.0: `sudo dpkg -i <filename>` where `<filename>` is the deb file.

I tested this out on an older Raspberry Pi B, by first installing 0.13.2 and then installing 0.15.0 on top of it. The installation succeeded, but I'm now troubleshooting an issue where the ka-lite init script times out. Which model of the Pi are you using? I'll offer a fix for the issue I've described as soon as I have one, but if you're using the Pi 2 it may not be a problem (we did our internal testing of 0.15.0 on Pi 2s).

**Comment by j-schwartz** [comment]
We're mostly using Pi 2s but we have a couple hundred Pis of various
hardware deployed we'll want to offer updates to if there is significant
performance improvements.

**Comment by j-schwartz** [comment]
Thanks for this though, I will try asap. Out of town for the weekend
though.

**Comment by benjaoming** [comment]
@j-schwartz I would recommend to set the .deb packages in motion if you haven't already. That way you can have an upgrade path in place for the future. I think @MCGallaspy's suggestion sounds plausible: Cleaning up from the non-deb installation. You should be able to install the 0.14.2 and continue using the 0.13 data, however you probably want to re-fetch assessment items and videos since this changes over time.

**Comment by benjaoming** [comment]
A new candidate is available in the [proposed PPA](https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed), please note that it doesn't have a systemd script yet. It is also well-known that installing directly from PPA with `apt-get install` prompts that debconf questions are re-asked after the installation is completed, however it seems harmless.

Installing directly from a .deb file with `dpkg -i` as the original post says is AFAIK working fine, please do continue this, you can find the newest files here:

http://ppa.launchpad.net/learningequality/ka-lite-proposed/ubuntu/pool/main/k/ka-lite-source/

**Comment by j-schwartz** [comment]
Hi @MCGallaspy - sorry I'm just getting back to this.  We have version 0.13.1 installed on most of our devices.

here's what I am doing:
```
pi@rachel:~$ ka-lite/bin/kalite stop
kalite stopped
pi@rachel:~$ sudo rm /etc/init.d/kalite
update-rc.d: using dependency based boot sequencing
```
My version 0.13.1 install doesn't appear to have nginx installed anywhere.  Is that possible?

**Comment by MCGallaspy** [comment]
> My version 0.13.1 install doesn't appear to have nginx installed anywhere. Is that possible?

Certainly seems suspicious. Is there any way you can provide me with an image of a device with 0.13.1 installed, prior to attempting to upgrade, so that I can troubleshoot it here?

**Comment by j-schwartz** [comment]
Yep, shall I mail it?  Just a micoSD card OK?

**Comment by MCGallaspy** [comment]
> Yep, shall I mail it?  Just a micoSD card OK?

That's fine, but it would be more convenient to upload the image somewhere that I can download it. Otherwise contact me using the email on my github profile and I'll provide a mailing address.

**Comment by j-schwartz** [comment]
Sorry misunderstood. It's here.
http://rachelfriends.org/rachelpi_64EN/rachelpi2_64EN_3.4.img

**Comment by j-schwartz** [comment]
Also, we had a patch on that version (rachelpi_3.4). A number of devices
were not rebooting KA-Lite after a shut down.  This was the volunteer
report on it:

 It turns out that there is a bug in the kalite init script that prevents
the lock directory to be removed even when the machine is cleanly shutdown.
The kalite startup and shutdown scripts need to be run as Pi. They do not
work properly when run as root. The kalite init script is setup to switch
to the Pi user when starting the server, but not when shutting down. This
causes the init script to fail even on a clean shutdown and not delete the
lock file.

**Comment by MCGallaspy** [comment]
@benjaoming should we open a new issue about the initscript?

**Comment by benjaoming** [comment]
@MCGallaspy `/etc/init.d/kalite` must come from another source, manually created perhaps? The .deb's provide it with a dash `/etc/init.d/ka-lite`.

Regarding unclean shutdowns, see #4536 

Regarding systemd, see https://github.com/learningequality/installers/issues/271

**Comment by MCGallaspy** [comment]
0.13.x did not have a deb file, it must be installed from source. Presumably the initscript was generated from the now-removed initscript mgmt command, so I guess it's no longer an issue on develop.

**Comment by MCGallaspy** [comment]
I'm currently using an older Rachel Pi image with KA Lite 0.13.1 that I found we had in our office (since the download is very large). I'll take a look at the latest image when I get the opportunity.

> My version 0.13.1 install doesn't appear to have nginx installed anywhere. Is that possible?

KA Lite version 0.13.x comes with a `setup_unix.sh` script, where you should have been prompted to configure KA Lite for the RPi. Did you run this script at setup and choose not to run the RPi optimization scripts we included? That could explain why you don't have nginx installed.

So far I've come up with the following:
1. Follow steps 1 & 2 [in the previous comment](https://github.com/learningequality/ka-lite/issues/4664#issuecomment-156600520). Since you don't have nginx installed, ignore step 3.
2. Install KA Lite version 0.15.x from the deb. This will also install nginx. You'll also have the new `kalite` command on your path.
3. nginx will fail to start -- it can't bind to port 80, since that's in use by another service (apache?).
4. Stop KA Lite 0.15.x: `kalite stop`
5. Go to `/etc/nginx/sites-enabled` and delete the file `default` there. KA Lite does not use this configuration file.
6. Restart the RPi.
7. At this point KA Lite 0.15.x should work normally. I'm still testing out how you can best upgrade from 0.13.x to 0.15.x -- in principle you should be able to use the [documented gitmigrate command](http://ka-lite.readthedocs.org/en/latest/installguide/release_notes.html#id3), but please test it out before trying it in the field.

**Comment by MCGallaspy** [comment]
@j-schwartz know anything about an initscript called `pp-kalite-clean`?

**Comment by j-schwartz** [comment]
Yes, that was to address the kalite.lock which prevented KA-lite from booting up on a reboot.  That was our fix to the issue 4 messages above. 

Is that what's causing 0.15.x to continually reinstall on my machines following your 7 steps above?  Just about to dig into that.

![image](https://cloud.githubusercontent.com/assets/9270388/11604525/7b15c8f0-9aa2-11e5-94bf-868e91584e74.png)

**Comment by MCGallaspy** [comment]
Yes, that's it. I also encountered that issue. Remove that script, or if you still encounter issues with the lockfile not being removed (e.g. because of an unclean shutdown) then you can amend it to *actually* remove the lockfile instead of the whole .kalite directory (which contains lots of other essential data). Though our lockfile behavior is now more robust, so I don't expect any issues.

**Comment by MCGallaspy** [comment]
Great, I think we've got everything here to migrate you from 0.13.x to 0.15.x -- let me know if you have any other issues. I'll close this thread if nothing comes up.

**Comment by j-schwartz** [comment]
Fantastic.  That should do it, except for some reason I'm getting KA-Lite on port 7007 instead of 8008 now that I removed that script.  That's strange right?

**Comment by MCGallaspy** [comment]
> That should do it, except for some reason I'm getting KA-Lite on port 7007 instead of 8008 

That's a known bug. You should still be able to access KA Lite from port 8008, despite what the message says. Expect a fix in the next release.

**Comment by j-schwartz** [comment]
Amazing, thank you both @MCGallaspy @benjaoming for the tremendous help.  I'll let you know if we run into any migration of data issues as we test over the next few days.  Great stuff guys.

**Comment by benjaoming** [comment]
@j-schwartz you provide really good feedback, pleasure to help!! :)

**Comment by j-schwartz** [comment]
hi guys - quick note, and I'll document it better when I can recreate on purpose, but I'm not sure the init issue has been fixed yet.  After an unexpected shutdown on the raspberry pi, upon reboot, KA-lite does not reboot and is again hindered by the lock file we were fixing the pp-kalite-clean boot init script we created.  see screenshot after a failed shutdown:

![image](https://cloud.githubusercontent.com/assets/9270388/11611767/61e5df18-9b93-11e5-98ab-f62f751c947e.png)

**Comment by j-schwartz** [comment]
I can't seem to recreate this, so I'm not sure what triggered it.  I had a 504 error during some video downloads and rebooted my Pi.  Upon reboot KA-Lite would not start due to the lock error.  On second reboot it appears to operate normally.  I'll attempt to recreate, but seems like a minor issue at most.

**Comment by benjaoming** [comment]
@j-schwartz the lock file is removed after a successful start and if something breaks during initialization (running django migrations, collecting static files etc), the lock file may linger:

```
    # Write current PID and optional port to a startup lock file
    with open(STARTUP_LOCK, "w") as f:
        f.write("%s\n%d" % (str(os.getpid()), port))

    manage('initialize_kalite')

    if watch:
        watchify_thread = Thread(target=start_watchify)
        watchify_thread.daemon = True
        watchify_thread.start()

    # Remove the startup lock at this point
    if STARTUP_LOCK:
        os.unlink(STARTUP_LOCK)
```

**Comment by benjaoming** [comment]
I mean, therefore it could be interesting to know if somehow things are broken during `initialize_kalite` -- you can run this directly with `kalite manage initialize_kalite`.

**Comment by benjaoming** [comment]
No, actually one more thing that's important: If a lock exists and the PID in the lock doesn't, it will silently remove the lock file and continue. This should mean that the only way to have the error you experienced is if there's an active process with a startup lock.

**Comment by MCGallaspy** [comment]
Let's open a new issue for this.
