### ISSUE TITLE
Why dont start?

### ISSUE THREAD

**Issue by johnfelipe** [learningequality/ka-lite#4665]
notroot@dhcppc4:~$ kalite start
	Running 'kalite start' as daemon (system service)

	Stand by while the server loads its data...

	Traceback (most recent call last):
	  File "/usr/share/kalite/kalitectl.py", line 916, in <module>
		port=arguments["--port"]
	  File "/usr/share/kalite/kalitectl.py", line 507, in start
		f.write("%s\n%d" % (str(os.getpid()), port))
	IOError: [Errno 28] No space left on device

**Comment by MCGallaspy** [comment]
Seemingly because there's no space left on the device. Try removing some unnecessary files, and use `df -h` to view how much space is available on your filesystem.

**Comment by johnfelipe** [comment]
Where can i download only spanish and assesment videos?
