### ISSUE TITLE
torrent for spanish videos and asset?

### ISSUE THREAD

**Issue by johnfelipe** [learningequality/ka-lite#4666]

**Comment by Aypak** [comment]
http://pantry.learningequality.org/downloads/ka-lite/0.14/content/

**Comment by johnfelipe** [comment]
I have 0.15, not matter?

**Comment by Aypak** [comment]
http://pantry.learningequality.org/downloads/ka-lite/0.15/content/ for version 15. Not sure if videos can be changed to Spanish though

**Comment by johnfelipe** [comment]
latest link, have english version, but 0.14 link works, only need restart server and download 11 new videos.

Now spanish assets how works?
where download for 0.15 and how upload, ONLY SPANISH pls

Tnks

**Comment by johnfelipe** [comment]
spanish assets how works?
