### ISSUE TITLE
"Contact us" for distributed server

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#467]
Title says it all.  Let's have a SyncableModel that represents contact from people on distributed servers.

And yes, @jamalex , we'll have to have a setting such that this can be turned off for prison-based deployments :)

**Comment by benjaoming** [comment]
A thought: We can just put our email somewhere (which we've already done in the static docs!) and let's assume people figure it out :) Device registrations are already a thing that we do, so for stats we're covered.

Closing this.
