### ISSUE TITLE
Remove 301 redirect on learningequality.org

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4672]
This is very urgent as assessment items cannot be downloaded through the .deb anymore since a change in our central server nginx configuration.

From #4664, we re-learned that our SSL certificate is invalid with default Debian and Ubuntu. We cannot force people downloading assessment items from `http://learningequality.org/downloads/ka-lite/0.15/content/khan_assessment.zip` to be 301 forwarded to an HTTPS connection.

**Comment by benjaoming** [comment]
Alternatively, buy a better certificate :)

**Comment by aronasorman** [comment]
I distinctly remember @jamalex removing this already. Perhaps it wasn't committed to ansible and got restored back again. Will do today

**Comment by benjaoming** [comment]
It's definitely still a problem:

```
wget http://learningequality.org
--2015-11-17 17:35:09--  http://learningequality.org/
Resolving learningequality.org (learningequality.org)... 23.253.32.238
Connecting to learningequality.org (learningequality.org)|23.253.32.238|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
```

**Comment by jamalex** [comment]
We still redirect the homepage to https, but the downloads stuff we shouldn't be.

Looks like what's happening is we changed the redirects for the /downloads/ stuff to redirect to the pantry server directly, as we were having nginx truncation issues in proxying big files. If you take a look at the 301 for the assessment zip, it's redirecting to https, and then sending to the pantry server -- so it passes through an https redirect on its way to the http endpoint.

```
$ wget http://learningequality.org/downloads/ka-lite/0.15/content/khan_assessment.zip--2015-11-17 08:40:07--  http://learningequality.org/downloads/ka-lite/0.15/content/khan_assessment.zip
Resolving learningequality.org (learningequality.org)... 23.253.32.238
Connecting to learningequality.org (learningequality.org)|23.253.32.238|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://learningequality.org/downloads/ka-lite/0.15/content/khan_assessment.zip
```

Looks like we may just need to turn off `force_https` [on the redirect](https://github.com/fle-internal/ansible-playbooks/blob/master/roles/gatehouse/vars/main.yml#L108). Will try that now.

**Comment by jamalex** [comment]
Fixed in https://github.com/fle-internal/ansible-playbooks/pull/63, and applied to proxy server -- please test; thanks!

**Comment by jamalex** [comment]
(Note that we may want to track issues like this on the ansible-playbook repo)

**Comment by benjaoming** [comment]
Nope, still redirecting, was the server reloaded with new conf?

```
wget http://learningequality.org/downloads/ka-lite/0.15/content/khan_assessment.zip
--2015-11-17 17:57:25--  http://learningequality.org/downloads/ka-lite/0.15/content/khan_assessment.zip
Resolving learningequality.org (learningequality.org)... 23.253.32.238
Connecting to learningequality.org (learningequality.org)|23.253.32.238|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://pantry.learningequality.org/downloads/ka-lite/0.15/content/khan_assessment.zip [following]
--2015-11-17 17:57:25--  http://pantry.learningequality.org/downloads/ka-lite/0.15/content/khan_assessment.zip
Resolving pantry.learningequality.org (pantry.learningequality.org)... 162.209.63.41
Connecting to pantry.learningequality.org (pantry.learningequality.org)|162.209.63.41|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 515586311 (492M) [application/zip]
```

**Comment by jamalex** [comment]
Correct; redirecting to the pantry server's HTTP connection (to avoid the Nginx truncation issue). Shouldn't be going through HTTPS anymore?

**Comment by aronasorman** [comment]
wget might be doing some caching here, seeing as we used 301 (permanent redirect) instead of 301 (temporary).

**Comment by benjaoming** [comment]
@jamalex ah, too quick here -- i was pasting output showing that it does work :D
