### ISSUE TITLE
Videos not showing

### ISSUE THREAD

**Issue by Aypak** [learningequality/ka-lite#4674]
I installed v0.15 according to the instructions, then downloaded khan_assessment.zip and the torrent of videos. I ran kalite manage setup to unpack the assessment items, and placed all the videos in /home/pi/.kalite/content. Some assessment items are not showing on the learn tab, and none of the videos are showing either even though it shows that they exist on the videos tab under admin. It is similar to the behavior described in #4583

**Comment by MCGallaspy** [comment]
Hi @Aypak, thanks for the report. This is on a raspberry pi? Which model? And what OS are you using? I'd first suggest restarting KA Lite. If that doesn't work, then we'll investigate further.

**Comment by Aypak** [comment]
Thank you for your response. Yes, i'm running this on a raspberry pi. Its the rpi 2 B+ running on the latest raspbian wheezy. I added the line 
```
CONTENT_ROOT = '/home/pi/.kalite/content'
```
to settings.py. Now all the assessment items work, but the videos still do not work even though it shows that they exist on the manage tab. When i run 'kalite manage setup' and follow the prompts i get the following screen
![capture](https://cloud.githubusercontent.com/assets/7353802/11267334/6d11385c-8eb3-11e5-8afc-24ee741906bd.PNG)

and the videos are still not showing on the learn tab even after restarting the server and rebooting the rpi

**Comment by rtibbles** [comment]
I imagine this is due to the use of the disk based content cache on the Raspberry Pi. 

Deleting the cache files in <USER_DATA_ROOT>/cache will allow the caches to be regenerated.

This is fixed in 0.16 with the 'scan for videos' option in the management page.
