### ISSUE TITLE
nginx bind error : Address already in use

### ISSUE THREAD

**Issue by Aypak** [learningequality/ka-lite#4679]
I'm running ka lite v0.15 on the rpi 2. I get the following error everytime i switch on the rpi.
nginx: (emerg) bind() to 0.0.0.0:80 failed (90: Address already in use)
nginx: (emerg) bind() to 0.0.0.0:80 failed (90: Address already in use)
nginx: (emerg) bind() to 0.0.0.0:80 failed (90: Address already in use)
nginx: (emerg) bind() to 0.0.0.0:80 failed (90: Address already in use)
nginx: (emerg) still could not bind()
nginx.
 After which the kalite server starts and I am able to login but the server either stops responding or runs very slow
When i run kalite status. I get the response: Not responding(5)

**Comment by benjaoming** [comment]
This looks like two separate issues. For performance on RPI, we should look at #4664. 

For the bind issue, make sure you don't already have another HTTP server (like Apache) running on port 80. Also, you may see that a wild nginx process occupies the port. Try killing all nginx processes or restarting the pi.

**Comment by j-schwartz** [comment]
If I install using the deb, I get port 7007 and the nginx errors, but this doesn't seem to affect actual operation of KA-lite.  Is that true?  Should the deb installer initiate KA-lite on 7007 or 8008?  The PIP package gets me installed on 8008.

**Comment by benjaoming** [comment]
@j-schwartz ka-lite-raspberry-pi has ka-lite configured to listen on 7007 and nginx on 8008.

Nginx will handle all traffic and proxy the scripted parts to ka-lite on 7007 while handling all the static media within nginx. This is the optimization that makes the big difference on RPi.

**Comment by j-schwartz** [comment]
Great, thanks @benjaoming.  Why is nginx trying to grab port 80 in the above error (which I've had also)?  Is port 80 used by the raspberry pi configuration somewhere?

**Comment by benjaoming** [comment]
Try `fuser 80/tcp` to get the PID of the process listening on port 80. Then
you can use `px ax | grep PID` to see what's active. As I said earlier,
sometimes its a run-away nginx.

**Comment by j-schwartz** [comment]
At the end of running on a Raspberry Pi with Raspian
```sudo dpkg -i ka-lite-raspberry-pi-0.15.0 deb```

My output shows KA-Lite running on 7007, does this make sense?

![image](https://cloud.githubusercontent.com/assets/9270388/11573392/f113a24a-99ba-11e5-86e0-d19d0d31be35.png)

**Comment by benjaoming** [comment]
The last message is slightly mis-informing. You can access kalite on port 7007, but you should access it on port 8008 where nginx is listening.

I should try to change the message in this PR:

https://github.com/learningequality/ka-lite/pull/4611

**Comment by benjaoming** [comment]
Related: https://github.com/learningequality/ka-lite/issues/4599

**Comment by Aypak** [comment]
I found that the nginx bind error stops when you comment out the line ```  pre-up sudo python /opt/ka-lite-pi-scripts/redirect_port80_to_port8008.py &``` in /etc/network/interfaces. The script commented out is to listen on port 80 and redirect any requests to port 80 to 8008. I think the bind error occurs because when you start the pi, network interfaces is read before nginx is started.

**Comment by benjaoming** [comment]
@Aypak thanks for investigating, I guess the script is part of [this repo](https://github.com/learningequality/ka-lite-config-pi). I don't like it, it's a very silly hack. I think if people want port 80, either they should configure nginx themselves by adding 'listen 80;' to the vhost or we should discuss setting up the .deb to listen to port 80 by default, wouldn't be too bad :)
