### ISSUE TITLE
Remove dependency on django_snippets

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4713]
Only used for SessionIdleTimeout

So we can probably copy out that *snippet*

**Comment by iCHAIT** [comment]
Can I take this?

**Comment by benjaoming** [comment]
:+1:  This is on the menu for 0.17, so do a PR for `develop` and it should be easy to merge :)

**Comment by iCHAIT** [comment]
@benjaoming Can you give me some pointers that would get me started? As I am not very much familiar with the codebase.

**Comment by benjaoming** [comment]
Search the codebase to see where it's in use, if any, and factor them out :) I don't have a documented list of its usage unfortunately, that's the kind of dependency management we should do in the future.

**Comment by iCHAIT** [comment]
@benjaoming  Okay I found the part which contained django_snippets, I want to know where should I copy out the method `SessionIdleTimeout` so that it makes most sense?

**Comment by benjaoming** [comment]
@iCHAIT perhaps it's possible not to copy it out anywhere, but to seek out a way to make existing functionality work without it?

**Comment by benjaoming** [comment]
@iCHAIT okay it seems like a very simple middleware to copy out.. `kalite/distributed/middleware.py` is a good location!

**Comment by iCHAIT** [comment]
@benjaoming  Opened a PR, can you review and suggest changes if any?

**Comment by MCGallaspy** [comment]
Fixed in #4822.
