### ISSUE TITLE
KAlite hotspot edimax connecting problems

### ISSUE THREAD

**Issue by miresh15** [learningequality/ka-lite#4715]
Hi, I have installed a fresh copy of the latest kalite install on my raspberry pi using the wiki guide. I then followed through the wifi hotspot setup under the Specific system setups - Raspberry Pi Wi-Fi steps 1-6. After this I see the ka-lite hotspot on the devices I'm trying to connect however the devices are undable to connect. Any help would be appreciated! I'm using the edimax dongle :)

**Comment by pateljj04** [comment]
I am having the same issue, getting a 168 ip address from the client when trying to connect to kalite.

**Comment by miresh15** [comment]
Hi, I struggled a long time with this and swapped the edimax for the rpi
wifi adapter and had no issues. Sorry I cant be more help.

**Comment by pateljj04** [comment]
What wifi adapter did you switch to?

**Comment by benjaoming** [comment]
Closing this, missing input from original reporter @miresh15 - but thanks for reporting nonetheless and good luck with your project. For any support etc. know that we've opened up a new community support forum: http://community.learningequality.org/
