### ISSUE TITLE
Prettify unpack_assessment_zip output

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4719]
On `develop`:

With the Windows installer, we now call `unpack_assessment_zip` as part of the installation process. It's output is displayed on a console, but it's really minimal (`Unpacking...`) and can take a long time. Some users will undoubtedly think that it is hung, and inadvertently cancel it, resulting in a failed installation. So let's give it better output -- some kind of progress bar. Something that will quell the rising panic in our user's throats.

**Comment by benjaoming** [comment]
This issue lives on in #5356
