### ISSUE TITLE
No apparent order to coach report headings

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite#4728]
While testing 15.1 on Ubuntu 14 LTS, I noticed that the coach report for the student seemed very out of sequence with how the events actually happened which were in the sequence of the sidebar design for this section. The session they were done in was uninterrupted so I suspect this could be a bug or feature request not sure which.  I expected them to be listed in the chronological order they were done in. 
![2015-12-03_14-47-32](https://cloud.githubusercontent.com/assets/4349806/11575506/a7c7e204-99ce-11e5-9f04-0d0371d6f687.png)

**Comment by AOS002** [comment]
I Would like to work on this bug. It would be great if someone could guide me through this.

**Comment by MCGallaspy** [comment]
Just noticed this one -- perhaps a good beginner exercise to get familiar with the codebase?

**Comment by shubhsingh594** [comment]
hi i am new to this community , and this would be a good opportunity for me to get familiar with the codebase. i would like to work on this ticket.

**Comment by MCGallaspy** [comment]
Hi @shubhsingh594, sure thing! Take a look at our [getting started documentation](https://github.com/learningequality/ka-lite/wiki/Getting-started) to set up a development environment. Then I would suggest pulling the latest stable branch (`0.15.x` at this time) and try to replicate the issue. The code for coachreports lives in the [`kalite/coachreports` directory](https://github.com/learningequality/ka-lite/tree/0.15.x/kalite/coachreports). Then perhaps @rtibbles can offer guidance on which api endpoint generates the headings, and whether it would be more appropriate to sort the api response before its sent to the client, or to sort on the client.

**Comment by MCGallaspy** [comment]
@shubhsingh594 feel free to pop into our hipchat room or email the dev mailing list for more guidance as well. Email is probably better if you're outside the US, since our hipchat room is only active during daytime hours in California.

**Comment by rtibbles** [comment]
The get_learner_logs function inside api_views.py is the first place to look for this. The content headers are defined by the dicts in the "output_objects" list.

**Comment by shubhsingh594** [comment]
hi all, 
i have submitted a pull request - https://github.com/learningequality/ka-lite/pull/4821 .
i request you to review the code and suggest changes. Thank you !
@MCGallaspy  @rtibbles

**Comment by shubhsingh594** [comment]
okay, while tackling this ticket. i noticed that if there is just one learner. sorting his activities in chronological order makes sense, but if there are multiple learners then all of them may have unique order of activities. At such point it would make more sense to just order the activities in lexicographical order rather than in chronological order.

**Comment by rtibbles** [comment]
Fixed in #4919
