### ISSUE TITLE
0.16 Video status updates not working properly

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite#4739]
The video "tree" does show which items have been downloaded but do not show partial or full content for the higher level folder containing them as they should. A picture describes this much better than I can in the picture below all 10 counting videos have been downloaded:

![2015-12-07_16-44-16](https://cloud.githubusercontent.com/assets/4349806/11644012/8ba8138e-9d05-11e5-940e-7903317e3d73.png)

**Comment by rtibbles** [comment]
This is not extant in latest 0.16:

![image](https://cloud.githubusercontent.com/assets/1680573/13270447/15ec2506-da43-11e5-8674-09edd28a137b.png)
