### ISSUE TITLE
Make gooder inline help narratives.

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4742]
Inline help is now a feature. But we need someone to create more narratives for this feature to become really useful. See https://github.com/learningequality/ka-lite/blob/develop/data/narratives.yml for examples of existing narratives -- making new ones and editing existing ones requires some dev knowledge. Could be a good intro to the codebase.

Unfortunately, the format for narratives is not well-documented here. See https://github.com/learningequality/ka-lite/issues/3407 to find the scattered pieces of the original documentation. Anyone tackling this should add a docs page about how to create new narratives.

**Comment by MCGallaspy** [comment]
I'm available to help sort out the documentation situation.

**Comment by manipalsingh013** [comment]
hey @MCGallaspy 
I would like to work on this. Any thoughts where I should start.

**Comment by MCGallaspy** [comment]
It's a little subjective, and it's also depends on the UI (which changes slightly from version to version). I would start by:

1. Get a development version of KA Lite running from the `develop` branch. (The branch is not stable and is subject to change, so please stop by our slack room or mail the development mailing list if you have issues here.)
2. Try out the existing inline help features.
3. Write a documentation page for how to create new inline help narratives. (Again, you can seek more detailed guidance on our mailing list or slack room.)
4. Propose a new narrative you think would be helpful by emailing your suggestion to the dev mailing list.

**Comment by benjaoming** [comment]
The way to write new narratives has been changed a bit to avoid having `yml` data in our codebase. I'm absolutely open to having more inline help as it doesn't break anything.

Just needs to happen before 0.17 string freeze.

Anyways, we haven't received an proposals AFAIK. But opening those in separate issues would make it easier. Closing this and opening an issue about documenting the inline feature.
