### ISSUE TITLE
benchmark management command broken

### ISSUE THREAD

**Issue by edresor** [learningequality/ka-lite#4747]
I cannot get Selenium Student to run on a client computer.  I tried the Selenium Script below after I installed and started the normal (non-developer) version of Kalite 0.15.0 on a MacBook with OS X 10.9.5 (Mavericks).

I tried to run the script as sudo from the from the "/" directory in the Apple terminal.  The computer could not find the command as indicated below.
$ sudo ./kalite/manage.py benchmark seleniumstudent --url= http://rasp.pi.IP.address:8008 --clients=4 --duration=2
Password:
sudo:  ./kalite/manage.py:  command not found

It's not clear to me if:
  1.) I need to install a developers' version of KA-Lite or, at least some extra scripts
  2..) If the Selenium Student based web browser simulation is still included in 0.15.0
  3.) If I need to install Selenium on Firefox or if Selenium is loaded by the Python scripts
  4.) if KA-Lite needs to be running or just installed on the client so that the scripts that run the Selenium Student test clients can be run
  5.) if I should use 0.15.x to get the Selenium Student scripts to test a server with 15.0.0 or an earlier version of KA-LIte if the scripts have be dropped

If I need to install a developers' version of KA-Lite, is there a simple way to do it for a non-developer who will not be writing or submitting any code?

I am just trying to use these scripts to test different hardware platform.

Thanks, Ed Resor

**Comment by MCGallaspy** [comment]
Hi @edresor, two things:

1. Since KA Lite version 0.13.0 we now provide [a `kalite` command](http://ka-lite.readthedocs.org/en/latest/installguide/release_notes.html#id5). To run management commands, the invocation is now `kalite manage <your command and options here>`, e.g. `kalite manage benchmark seleniumstudent`.
2. I hate to be the bearer of bad news, but the benchmark management command has not been under active development for quite some time -- I just tried it out and it does not appear to be functioning correctly.

**Comment by edresor** [comment]
Thanks. I hope the fix will not be too much trouble.

I should have mentioned I tried using the manage command.  BTW, its a great command.  I love the option generaterealdata and look forward to using icantbelieveitsnotrealdata.
Thanks again, Ed

**Comment by aronasorman** [comment]
Hi @edresor, I'm reiterating @MCGallaspy's note that `benchmark` has been unmaintained now -- probably around 2 years since the last active development on it. We are currently developing a new system that tracks KA Lite's performance, but most of the pieces will be decoupled from the actual KA Lite repo.

**Comment by aronasorman** [comment]
We'll make sure to tag you once we have a new solution up. You do bring up a good point of testing performance on multiple hardware platforms.

**Comment by edresor** [comment]
Is there anyway to move this to a wish list and not make it a bug?
I would be happy write a brief draft of the requirement.
I think decoupling from the KA Lite repro is absolutely the right way to go.
It may be possible to write the scripts within Selenium and not even need to use Python.

This kind of testing is very important to many serious users with limited funds.

I work in East Africa with World Possible and we are making a big push on KA-Lite Math. I go back to Africa in January to try KA-Lite with 40 BRCK Education Kio tablets on an Intel Atom server [RACHEL-Plus] (http://store.worldpossible.org/collections/frontpage/products/rachel-plus)
I will also take an i7 laptop for backup and comparison. Our folks in Liberia report the same problems we have with the Exercises.  So a test targeted at the exercises is focused on a key bottleneck.

We are pushing on Intel to get better performance from their reference design, but that is going slowly.

The only change and simplification which I would make for the tests would be to set up the users first, and just test the how many users could log on randomly and work simultaneously.  We already recommend to our users to set up the user accounts before class.

What we really need to know is how many students can work without crashes on the exercises.  Delays are OK as long as the student does not think the problem is her fault.

I have three platforms for comparison (Pi 2, RACHEL-Plus, and high end i7 Desktop).  I am setting up multiple computers to run Selenium.  Once I get to Africa, I will have lots of real data to compare with the selenium tests.  I will need some guidance on what logs and other data from the server will be most helpful to your team.
