### ISSUE TITLE
Bugfix for "Invalid cross-device link"

### ISSUE THREAD

**Issue by spatiald** [learningequality/ka-lite#4751]
We run KA Lite on custom content access points.
OS:  Ubuntu 12.04 32bit

## Branch
KA Lite "Branch":  Using ka-lite-bundle-0.15.1.deb

## Build
KA Lite Build:  0.15.1

## Expected behavior
We ran into an issue running the following command:
```
kalite manage unpack_assessment_zip khan_assessment.zip -f
```
We expect this command to install the downloaded khan_assessment.zip; this file was downloaded from [here](https://learningequality.org/downloads/ka-lite/0.15/content/khan_assessment.zip).

## Actual behavior
Installer fails with ```OSError: [Errno 18] Invalid cross-device link```

## Steps to reproduce (be detailed!)
```
root@server:~# kalite manage unpack_assessment_zip khan_assessment.zip -f
Unpacking...
Traceback (most recent call last):
  File "/usr/share/kalite/python-packages/django/core/management/base.py", line 224, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/share/kalite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/kalite/contentload/management/commands/unpack_assessment_zip.py", line 64, in handle
    unpack_zipfile_to_content_folder(zf)
  File "/usr/lib/python2.7/dist-packages/kalite/contentload/management/commands/unpack_assessment_zip.py", line 105, in unpack_zipfile_to_content_folder
    settings.KHAN_ASSESSMENT_ITEM_DATABASE_PATH
OSError: [Errno 18] Invalid cross-device link
```

## Proposed fix
Looking at a similar issue [here](https://github.com/foosel/OctoPrint/issues/710), I believe it's related to our file system setup.  To fix this issue, we executed the same fix they did; that is, "maybe shutil.move must be used instead of os.rename os.rename should be ok for ones who had /tmp on same FS".  To support that change, we imported the shutil module.
```bash
sed -i "s/os.rename/shutil.move/g" /usr/lib/python2.7/dist-packages/kalite/contentload/management/commands/unpack_assessment_zip.py
sed -i '6 a import shutil' /usr/lib/python2.7/dist-packages/kalite/contentload/management/commands/unpack_assessment_zip.py
```

After modifying the python code, we successfully imported the zip file and tested the assessments:
```
root@server:~# kalite manage unpack_assessment_zip khan_assessment.zip -f
Unpacking...
root@server:~#
```

**Comment by MCGallaspy** [comment]
Thanks for the detailed report!

**Comment by MCGallaspy** [comment]
Looks like an easy enough fix to implement for 0.16.x

**Comment by MCGallaspy** [comment]
Actually I think this will not be relevant in 0.16.0 anymore, since the unpack_assessment_zip management command will not be used. Is that correct @aronasorman?

**Comment by aronasorman** [comment]
Yup, `unpack_assessment_zip` is gone, to be replaced with `retrievecontentpack`.
