### ISSUE TITLE
Does not delete videos from content folder

### ISSUE THREAD

**Issue by Odia1** [learningequality/ka-lite#4759]
I would like to trim the video content size by removing certain sections like, say, GMAT. The admin interface seems to allow selecting and asking to delete. But when I check the content folder size it does not shrink, although the admin interface said the videos were deleted.
Later restart of ka-lite shows all the videos (the original set without any deletes).

DP

**Comment by MCGallaspy** [comment]
Hi @Odia1, which version of KA Lite are you using, and what is your operating system?

**Comment by Odia1** [comment]
I am using it on Windows-10 . ka-lite version is 0.15.1

**Comment by dakkad** [comment]
@MCGallaspy I am happy to try and see if I can debug this if you can point me in the right direction?

**Comment by MCGallaspy** [comment]
Hi @dakkad are you able to replicate @Odia1's error? I would start with that, and I would try to identify which lines of code are responsible for deleting videos -- I can help you with the latter task.

**Comment by MCGallaspy** [comment]
Just a guess, but maybe [this LOC](https://github.com/learningequality/ka-lite/blob/0.15.x/python-packages/fle_utils/videos.py#L64) fails, raises an exception, and then the exception is ignored. :(

If you're able to replicate the original error, I would start by either setting a breakpoint there or removing the try-except block (so that the exception isn't squelched) and seeing if that LOC does indeed raise an exception.

**Comment by Odia1** [comment]
Hi Guys,
I have another question/issue: Can I add a second administrator?
Is there anyway for a user to self-change password (I know the admin can
change it for a non-admin)?

Thanks

**Comment by MCGallaspy** [comment]
> I have another question/issue: Can I add a second administrator?

Yes, run the `kalite.bat manage createsuperuser` command and follow the prompts. You'll find the `kalite.bat` script in your /Python27/Scripts directory, wherever you installed Python.

> Is there anyway for a user to self-change password

No.

**Comment by dakkad** [comment]
Sorry for the delay, I will see about getting KA-Lite running on a VM over the weekend.

**Comment by dakkad** [comment]
Hmm. This could be a bit tricky for me as I am a *nix bod with not a lot of experience on Windo$e recently. Is it worth me trying to replicate it on *nix?

**Comment by MCGallaspy** [comment]
> Is it worth me trying to replicate it on *nix?

Yes.

**Comment by rtibbles** [comment]
@radinamatic Please verify that this is fixed in 0.16.

**Comment by Odia1** [comment]
Will do

Darshan's phone

**Comment by radinamatic** [comment]
Deleting seems to be working fine on 0.16, no JS or user alert errors, deleted videos non present in content folder. 

I'd say it could be closed, but if we are aiming for pre-release this week, let's wait so I can test it with Windows installer! @MCGallaspy

**Comment by rtibbles** [comment]
Confirming this is fixed in 0.16.
