### ISSUE TITLE
Unexpected error: no such table: item - 500 INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4765]
Unexpected error: no such table: item - 500 INTERNAL SERVER ERROR

**Branch**: 0.16 installer (build # 81) on Windows 8

**Expected Behavior**:  Homepage for Learner user should load the contentrec stuff 

**Current Behavior**:  `Unexpected error: no such table: item` error.

![ie11 - win8 1 pre python 3 5 running - oracle vm virtualbox_103](https://cloud.githubusercontent.com/assets/1457929/11858653/9d968f7a-a463-11e5-8512-19a8c036b228.png)

**Comment by MCGallaspy** [comment]
Expected. Need content packs to be available and incorporated into build process. Will leave open until we fix that.

**Comment by radinamatic** [comment]
This one also looks like solved on latest 0.16! @MCGallaspy

**Comment by nakam28** [comment]
I installed KA Lite version 2016.20 on an RACHEL-Plus when I ope the KA Lite I get the error message as shown in the screen shot below.
![unexpected error - no such table](https://cloud.githubusercontent.com/assets/24987742/22067551/ad95e9a6-dd89-11e6-9ff9-f22aa246154b.jpg)
![rachel version info](https://cloud.githubusercontent.com/assets/24987742/22067676/27de63dc-dd8a-11e6-8382-8d1bc13e4958.png)
