### ISSUE TITLE
Exercise page doesn't load

### ISSUE THREAD

**Issue by amodia** [learningequality/ka-lite#4774]
**Branch:** `develop`
**Current behavior:** Exercise page doesn't load.
**Expected behavior:** Exercise page must load after the assessment items extracted.

**Steps to reproduce:** 
 1. Run KA Lite server.
 2. Navigate to learn tab.
 3. Select any exercise.
 4. Observe that the exercise doesn't load.

I attached a sample screenshot of the exercise page.

![screen shot 2015-12-21 at 8 12 47 pm](https://cloud.githubusercontent.com/assets/8663934/11930537/473d002c-a81f-11e5-81ac-c3a40974499a.png)

**Comment by cpauya** [comment]
I was able to reproduce this issue too - here's a screenshot taken last 2015-Dec-21 and I've experienced the same today:

Here's the error message on the page:

    Sorry, this request could not be processed. Please try again later.

And this is displayed continuously in the Error Console of Safari, it now has 999+ error messages there:

    ...
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (xcd7ba1c0c381fadb, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (x4cb56360820eece5, line 0)
    ...

![screenshot 2015-12-21 12 31 58](https://cloud.githubusercontent.com/assets/175580/12046689/97de6ffe-aef8-11e5-9642-66e572ba3ff1.png)

**Comment by dylanjbarth** [comment]
Logged in as an admin
![screen shot 2016-01-31 at 9 11 59 am](https://cloud.githubusercontent.com/assets/1319950/12701228/bcfc7b9e-c7fa-11e5-8a97-9e666f3ab3d0.png)

Logged in as student 
![screen shot 2016-01-31 at 9 15 58 am](https://cloud.githubusercontent.com/assets/1319950/12701242/4759d7be-c7fb-11e5-8485-68ffabb67914.png)

Additionally, no console errors & network requests look fine. Perhaps this has been resolved incidentally? I'd say that the warning message covers this.

**Comment by cpauya** [comment]
Oh @dylanjbarth is back! :smile_cat: 

Yes, that seemed to fixed it, @amodia please verify so we can close this issue.

**Comment by amodia** [comment]
@cpauya the same behavior on me. The assessment console error in not showing. I think the warning message fixed this issue.
![screen shot 2016-02-01 at 11 05 58 am](https://cloud.githubusercontent.com/assets/8663934/12707831/cd36ee66-c8d3-11e5-99a3-1845663b5303.png)

**Comment by cpauya** [comment]
Thanks!

**Comment by dylanjbarth** [comment]
haha hi again @cpauya
