### ISSUE TITLE
Outdated release notes

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#4778]
branch: 0.16.x
OS: Mac

The OS X installer now has a handy 'release notes' page during installation:
![screen shot 2016-01-05 at 08 05 50](https://cloud.githubusercontent.com/assets/191955/12118283/37b4c172-b38b-11e5-85d0-f4bf9c816a28.png)

It indicates that a restart is needed for the videos to be available. This is not the case anymore. Release notes need to be amended. Other user visible changes, such as a faster startup time, and a preview of the inline help feature, should be added there.

**Comment by cpauya** [comment]
Ah yes @aron, I've noticed there's no need to restart the server after downloading videos anymore during testing.  Will update the documentation for v0.16 release.  

I think we should file this on the `installers` repo?

**Comment by benjaoming** [comment]
Fixed in installers repo
