### ISSUE TITLE
Speed changing menu option appears on video even when not supported by browser

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#478]
Background:

We use a plugin for video.js (in video-speed.js/.css) that adds a menu item to select faster or slower speeds. It is only supported in the HTML5 player, so it is disabled when the Flash fallback is used. In supported browsers (in particular, those based on WebKit), the HTML5 video object has a `playbackRate` attribute that can be modified to change the speed of playback.

Expected:

On browsers (e.g. mobile browsers, from my testing) where `playbackRate` isn't supported, the menu item shouldn't be shown.

Observed:

The menu item shows up, and speeds can be selected, but it has no effect.

Notes:

It's hard to sniff whether the browser supports this, because even on many browsers that don't support speed changing, the `playbackRate` is still defined (and starts at `1`). Changing it does change the value (with no other effect). The closest thing I could think of for sniffing would be to have a hidden dummy video object with a 2 second video. Try playing it at double speed, and see if it only runs for 1 second before stopping, otherwise hide the speed changing menu item. Or, just figure out which browsers support it, and detect what the browser is.

**Comment by aronasorman** [comment]
Not a priority; reopen if it's a big UX issue.
