### ISSUE TITLE
Not using S3 for video download

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4780]
Just noticing this behavior for video downloads in `kalite.updates.videos`:

```python
def download_video(youtube_id, format="mp4", callback=None):
    """Downloads the video file to disk (note: this does NOT invalidate any of the cached html files in KA Lite)"""

    download_url = ("http://%s/download/videos/" % (settings.CENTRAL_SERVER_HOST)) + "%s/%s"
    return videos.download_video(youtube_id, settings.CONTENT_ROOT, download_url, format, callback)
```

This overwrites the default Amazon S3 download url specified in `fle_utils.videos.download_video`.

This behavior also affects 0.15.

**Comment by benjaoming** [comment]
Okay nevermind, `kalite.learningequality.org` redirects to S3 hosting :) But this whole download thing is spread out over several packages, so really hard to understand what's going on. Suggesting a complete rewrite.

**Comment by rtibbles** [comment]
I concur, @benjaoming - but probably best left for Kolbiri.
