### ISSUE TITLE
issues trying to run /bin/windows/kalite.bat manage setup

### ISSUE THREAD

**Issue by jumbojim101** [learningequality/ka-lite#4783]
1/13/2016
I have a fresh install of Win XP Pro sp3
I do a fresh install of KA-Lite 0.15.1 (I selected to add python to path)
I downloaded the torrent of the new video files
I copied them to the content folder
I opened a cmd 
cd to to C:\Program Files\KA Lite\ka-lite folder containing the bin folder
i ran /bin/windows/kalite.bat manage setup
I am unable to get the program to accept my input correctly and get errors ... 
see the attachment
[error.txt](https://github.com/learningequality/ka-lite/files/89180/error.txt)

please advise

Sincerely 
James M Hammons
james_m_hammons@yahoo.com

Thanks

**Comment by EdDixon** [comment]
Not that it is any of my business or that XP is not still supported by us here for 0.15 but, I am curious about the use-case and the need to install this on XP. I hope you do not mind me asking but with the free upgrade from XP to 10 available why do you have this need?

**Comment by jumbojim101** [comment]
I am preparing to support some missionary folks in Uganda. We are looking at the Raspberry-PI and some older laptops and pc's that are in place there. I hope to be there about March 1 and I am trying to prepare for about any option short of new hardware. I am told there are severe import taxes.
My best guess at this point is old pc's/laptops with whatever old Windows os they have with maybe the option to install linux where we need to. I was told there is some "old" Dell pc's there
There is 1 place where there is no electricity and we are thinking about a PI , a solar panel an a couple of tablets. 
I retired about a year ago. I was a windows and unix admin previously. I am helping some friends that see the need for KA-Lite because of the lack of internet access , there.
And no , I don't think I know everything  :-)   Still learning. I appreciate your help.
Sincerely,Jim Hammons 

    On Wednesday, January 13, 2016 11:18 AM, Ed Dixon <notifications@github.com> wrote:
 

 Not that it is any of my business or that XP is not still supported by us here for 0.15 but, I am curious about the use-case and the need to install this on XP. I hope you do not mind me asking but with the free upgrade from XP to 10 available why do you have this need? —

**Comment by MCGallaspy** [comment]
> Not that it is any of my business or that XP is not still supported by us here for 0.15

Windows XP is supported, but [not Internet Explorer 8](http://ka-lite.readthedocs.org/en/latest/installguide/release_notes.html#windows). Any modern browser on XP (like Firefox or Chrome) should work fine with KA Lite.

@jumbojim101 if you have installed on XP using the Windows installer, it shouldn't be necessary to run the `setup` management command -- the necessary setup actions will be taken during installation, and others will be resolved the first time you start the server. Is there something in particular you're trying to accomplish? Or did you read something in the documentation that indicated you should do this? If so it probably means we need to update the docs!

That said, I too have noticed issues with the particular script you're indicating. You should find another `kalite.bat` script in your `C:\Python27\Scripts` directory (or wherever you installed Python) which should be preferred for running KA Lite management commands on Windows.

**Comment by jumbojim101** [comment]
The reason I think I need to run the script is that I am manually copying the videos into the content folder and I think the docs say you have to run manage setup so KA-Lite sees the new videos. Did I get that part right ?

I read the part about explorer 8 , I installed the newest firefox (forgot to mention that earlier)
I will try the script in the Python27\scripts folder.
Thank youJim Hammons 

    On Wednesday, January 13, 2016 12:14 PM, Michael Gallaspy <notifications@github.com> wrote:
 

 
Not that it is any of my business or that XP is not still supported by us here for 0.15
Windows XP is supported, but not Internet Explorer 8. Any modern browser on XP (like Firefox or Chrome) should work fine with KA Lite.@jumbojim101 if you have installed on XP using the Windows installer, it shouldn't be necessary to run the setup management command -- the necessary setup actions will be taken during installation, and others will be resolved the first time you start the server. Is there something in particular you're trying to accomplish? Or did you read something in the documentation that indicated you should do this? If so it probably means we need to update the docs!That said, I too have noticed issues with the particular script you're indicating. You should find another kalite.bat script in your C:\Python27\Scripts directory (or wherever you installed Python) which should be preferred for running KA Lite management commands on Windows.—

**Comment by MCGallaspy** [comment]
> I think the docs say you have to run manage setup so KA-Lite sees the new videos. 

I don't think that's the case, but let me double check. Can link to the location in the docs here it might say that?

On Windows, as long as you unpack the videos in the correct location (see the [docs on this topic](http://ka-lite.readthedocs.org/en/latest/usermanual/userman_admin.html#downloading-videos-in-bulk)), you should just need to *restart* the server without running setup. On Windows in particular the location to dump video files is the running user's `%USERPROFILE%\.kalite\content` directory, which on XP I believe expands to: `C:\Documents and Settings\<username>\.kalite\content`. Thus if my username is `Mike` and I start the KA Lite server as that user, then I should put the video files in `C:\Documents and Settings\Mike\.kalite\content`.

Do let us know if that procedure doesn't work!

Note that lately we've also discovered a bug in the "Start KA Lite at system start" option on XP which could affect where video files are downloaded/stored. I do not recommend using this option, however I can also attempt to offer workarounds if you need to use it.

**Comment by jumbojim101** [comment]
Running the c:\python27\scripts\kalite.bat manage setup ran perfect
I am working on an xp and a win10 version.  After moving videos to the "user folder"\.kalite\content folder the windows 10 version works perfectly ... Thanks
There was no .kalite folder in the xp version "user folder" I manually created one and moved \content folder there. restarted but was not able to see videos. I am very close and feel confident I will sort this out from here. I am going to uninstall and reinstall . Thanks for all your help. I really appreciate it.
 

    On Wednesday, January 13, 2016 12:41 PM, Michael Gallaspy <notifications@github.com> wrote:
 

 
I think the docs say you have to run manage setup so KA-Lite sees the new videos. 
I don't think that's the case, but let me double check. Can link to the location in the docs here it might say that?On Windows, as long as you unpack the videos in the correct location (see the docs on this topic), you should just need to restart the server without running setup. On Windows in particular the location to dump video files is the running user's %USERPROFILE%\.kalite\content directory, which on XP I believe expands to: C:\Documents and Settings\<username>\.kalite\content. Thus if my username is Mike and I start the KA Lite server as that user, then I should put the video files in C:\Documents and Settings\Mike\.kalite\content.Do let us know if that procedure doesn't work!Note that lately we've also discovered a bug in the "Start KA Lite at system start" option on XP which could affect where video files are downloaded/stored. I do not recommend using this option, however I can also attempt to offer workarounds if you need to use it.—

**Comment by MCGallaspy** [comment]
Glad to help! Please keep us updated here on how things pan out in Windows XP. It may be that you have discovered a bug frustrating other users, so your report could help to resolve it!

**Comment by EdDixon** [comment]
Thank you for your reply @jumbojim101 in regards to the use case question. Your answer is helpful in determining the need and resources allocated to continue to support XP beyond it's official lifetime.
