### ISSUE TITLE
Upgrading from 0.13.x to dev version causes error on facility management page

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4787]
On `develop`

Steps to reproduce (I did this on Windows, but I expect similar results on other OSes):
1. Install KA Lite 0.13.x
2. Create a student account and log some activity -- presumably you'd need to get a streak on an exercise at least.
3. Upgrade to 0.16.0.
4. Log in as an admin and go to the facility management page.

I see the following error, in place of the normal management console:
```txt
Error

Sorry, but there was an error while trying to load the page.
(KeyError: 'streak_progress') 
```

Screenshot:
![virtualbox_ie11 - win7_25_01_2016_10_01_02](https://cloud.githubusercontent.com/assets/8888020/12559543/9824f350-c34a-11e5-8b87-c6af544e1240.png)

**Comment by rtibbles** [comment]
Fixed in #4836
