### ISSUE TITLE
Need Guidance on Hardware Requirements

### ISSUE THREAD

**Issue by edresor** [learningequality/ka-lite#4790]
Do you have any guidance on the hardware requirements for schools that want to use KA-Lite 0.15.1 math exercises with classes with up to 40 of students on 40 WiFi tablets?

Do you have some tests that you have run on various hardware with multiple clients or maybe some feedback from the field on hardware that has been adequate for using the Math Exercises with large groups of students?

Would you recommend Windows 7 64-bit or Ubuntu 12.04.5 64-bit for the best performance and stability?
For us, KA-Lite is the most important application on the server.

Are there some settings for swappiness or niceness in Ubuntu that will help?

Particularly, it might help to keep the data.sqlite file and the related process in RAM as this seems to be the bottleneck when the students are trying to save their exercises and move on to another exercise or a video.

I am going to South Sudan next week so I have set up a old Lenovo ThinkPad with an Intel Dual Core i5-2430M (2.40 GHz), 8 GB of RAM, and 240 GB of SSD hard drive as a backup for less powerful servers with the idea that this configuration should be able to handle the load of 40 tablets.

We have received reports of problems with over 15 users on a server with a single core Intel Atom with only 2 GB of RAM and 32-bit Ubuntu and a 5400 rpm hard drive.

Do you have any monitoring software such a Monitorix that you use to identify bottlenecks or scripts that you use to collect data for analysis, possibly iotop if I/O is the bottleneck?

**Comment by MCGallaspy** [comment]
>Would you recommend Windows 7 64-bit or Ubuntu 12.04.5 64-bit for the best performance and stability?

>Are there some settings for swappiness or niceness in Ubuntu that will help?

I don't have a recommendation at this time. @benjaoming @aronasorman ?

> Particularly, it might help to keep the data.sqlite file and the related process in RAM as this seems to be the bottleneck when the students are trying to save their exercises and move on to another exercise or a video.

An interesting idea -- it's quite easy to configure KA Lite to use an in-memory database, but the drawback is that the database is lost when the machine powers down. But I wonder if we might be able to use an in-memory database which we *occasionally* write to disk? Data would still be lost when power is unexpectedly lost, but it might improve performance. How big, typically, is the data.sqlite file in your deployments?

>Do you have any monitoring software such a Monitorix that you use to identify bottlenecks or scripts that you use to collect data for analysis, possibly iotop if I/O is the bottleneck?

Not that I'm aware of. @aronasorman ?

**Comment by edresor** [comment]
Thanks for the quick reply.  The reason I am suggesting an in memory database is that all of our servers have internal batteries as they are laptops or the RACHEL-Plus / Intel Servers from World Possible.

Of course, we all want to have our cake and eat it too, so an in memory database that saved a copy to the hard drive every 5 minutes would be great.

**Comment by aronasorman** [comment]
Hi @edresor,

We can try out and see if an in-memory db will be performant. To test it out, add the following to your `~/.kalite/settings.py` file:

```python
DATABASES =  {"default": {"ENGINE": "django.db.backends.sqlite3", "NAME": ":memory:"}}
```

**Note that this will not contain any of your students' data, and the data saved when this option is set will not persist when KA Lite is restarted**. But if you can try replicating your use case with a lot of concurrent users, we can see if going with an in-memory option will solve the bottleneck.

**Comment by MCGallaspy** [comment]
Note that an in-memory database will *also* be lost if the KA Lite server process dies, regardless of whether the machine powers down or not.

Additionally, the location of the `.kalite` directory in 0.15.x on Windows depends on whether you're using the "start at boot" option or not -- if you're not using that option, it will be in the home directory of the user running KA Lite. But if you do use that option, it will use the SYSTEM user's profile, which can be found at `C:\Windows\SysWOW64\config\systemprofile` on 64-bit machines or `C:\Windows\System32\config\systemprofile` otherwise.

**Comment by MCGallaspy** [comment]
Additionally @aronasorman's comment is in error, we're now both working on creating a correct configuration for using an in-memory database.

**Comment by edresor** [comment]
Thanks guys.  this is great.  When you are ready, I will try to get some preliminary data here in the U.S. before I leave and then get real data when I have 40 cooperative South Sudanese school girls.  My volunteers here are limited, but they can simulated about 4 students with two different browsers open on two different machines.

Earlier work suggested that I/O was the problem.  I now have everything installed on an SSD drive, but it may be only SATA 2.

**Comment by edresor** [comment]
Since I have a lot of RAM, the idea of adjusting Swappiness was to set it down to about 10 in order to prevent swapping from the RAM to the hard drive.  I was also hoping adjusting niceness would also help.
I have the locations identified for all of the files and a special username to see if that helps identify processes in top and iotop.

**Comment by MCGallaspy** [comment]
Yeah, unfortunately due to the fact that KA Lite uses multiple concurrent processes, an in-memory database is apparently not accessible to other processes handling requests. I experimented with running KA Lite using a single process, but there are still issues to resolve, and our dev resources are too tied up right now to address this in the near future.

If you're comfortable setting one up and you'd like to try using a more performant database backend, we can give you guidance for that.

**Comment by edresor** [comment]
Rather than putting the data base in RAM, let me start me try with the SSD.  I hope the SSD plus ample RAM is going to give me a big improvement.

For possible next steps, do you guys already have a dev version of KA-Lite 015.1 set up with a Python Profiler?  A profiler might give us a better idea of where the problem is if it persists.  In the meantime lets see what I get from Monitorix which can monitor file system activity at the folder level.  I am in a crunch now, so I don't want to create any work on your side that I won't be able to put to use.

FYI, a group of World Possible users in East Africa are making a big push documented improvements in math.  This work and similar work in Liberia is where this problem came up.  World Possible is working with local a NGO called African Maths Initiative.  Although none of us are believers in the supremacy of high stakes exams, the primary and secondary school leaving exams are a fact of life so we want help students and teachers with something better than memorizing questions from past exams.

**Comment by rtibbles** [comment]
That sounds like great data to feed back to us - we would love to hear the impact.

We've not had these issues with simultaneous database writes on other similarly specced hardware, so I am also curious exactly where the performance bottleneck is occurring in this particular system.

**Comment by edresor** [comment]
Up to know the problem seems to be I/O related on our RACHEL-Plus / Intel server which uses eMMc memory and also on the Raspberry Pi.  I have not yet had tests with the SSD drive memory.  I hope to get some volunteers together this weekend.

**Comment by benjaoming** [comment]
@edresor 
> Would you recommend Windows 7 64-bit or Ubuntu 12.04.5 64-bit for the best performance and stability?

You could install the ka-lite-raspberry-pi version on Ubuntu. It features an nginx server for serving static files which is faster than KA Lite's bundled CherryPy server.

Any reason you are asking about Ubuntu 12.04? The latest LTS is 14.04, and in a few months, 16.04 is coming out :)

**Comment by edresor** [comment]
Updates from South Sudan.  Please excuse the rambling.
Using 12.04 because we are stuck with a 32-bit BIOS.  Hope the have this fixed sometime after June, 2016.

Actually getting up about 35 students doing exercises on BRCK Education Kio Tablets, which connect to the WiFi at just 1 Mb/s.  the slow connection might help.  Samsung SSD died in transit from NYC to Nairobi.  Lenovo with 14.04 has problems connecting more than 15 students with hostapd and just does not do as well as the RACHEL-Plus server.  Maybe I allowed too many things to load with the default load for server 14.04.

If I could get one wish right now it would be to bring back the "exercises only" option in the Coach Reports for 15.1 and even order the columns as the exercises appear on the Topic Tree.

Should I try version 16 on a back up server?  If so how do I get a .deb file?

**Comment by benjaoming** [comment]
Hi Edmund,

You may find the 0.16b1 here:
https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed

However, I would suggest that you wait a day or two until I can have 0.16b2
as AFAIK this one is without known issues. It works on 32 bits, as well,
and I don't think you should fear any significant performance slow downs
because of 32 bit. I also deploy 32 bits still, due to the occasional old
platform :)

Best,
Ben

**Comment by benjaoming** [comment]
Hi there!

The guide was updated a little while ago. Any specific requests for it should be opened as separate issues or discussions on community.learningequality.org

@edresor we would love to hear back regarding your experience in the community. Several people have been asking for deployment experience, and the more technical feedback we can collect, the better!

Here's the new docs section:

http://ka-lite.readthedocs.io/en/latest/installguide/system_requirements.html
