### ISSUE TITLE
RaspberryPi guidance for rebooting server

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4791]
Using: 0.15.1
Installer: ka-lite-raspberry-pi

After downloading new videos, videos won't show. In fact, everything in the menu disappears.

After some reloads, it shows up. This does not seem to be related to restarting the server.

**Comment by benjaoming** [comment]
http://ge.tt/4tSoakW2/v/0

**Comment by benjaoming** [comment]
http://ge.tt/7Yp3bkW2/v/0

**Comment by benjaoming** [comment]
![screenshot from 2016-01-29 13_39_51](https://cloud.githubusercontent.com/assets/374612/12678092/59897304-c69d-11e5-8864-13b455dc7a06.png)

**Comment by benjaoming** [comment]
I'm pretty sure this happens while `create_content_db` is running. However, is this relevant for 0.16 ?

**Comment by rtibbles** [comment]
Content cache files have to be deleted on RPi for 0.15.x, otherwise the annotation will not be recreated. This is not an issue for 0.16.x.

**Comment by benjaoming** [comment]
@rtibbles how does it work on 0.16? When a video file has been downloaded, does it just update the content db and the menu doesn't suffer from any caching anymore?

**Comment by rtibbles** [comment]
Praecis.

**Comment by benjaoming** [comment]
You can borrow this: æ

But I need it back, writing some Danes shortly.
