### ISSUE TITLE
init_content_items fails if locale dir doesn't exist

### ISSUE THREAD

**Issue by dylanjbarth** [learningequality/ka-lite#4796]
@aronasorman ran into this trying to get the build up and running again. 

To reproduce, with a fresh clone of KA Lite, follow steps 1-8 here https://github.com/learningequality/ka-lite/wiki/Getting-started. Step 8 will throw a `IOError: [Errno 2] No such file or directory: '/.../ka-lite/locale/dubbed_video_mappings.json'`.

Not sure what the expectation is (maybe this is legacy stuff?) or maybe the docs need an update, or maybe we just need to create the locale dir for the user when we are setting data locations in `base.py`. Lmk what you want to do here, will submit a PR.

**Comment by dylanjbarth** [comment]
this is the line that throws the error: https://github.com/learningequality/ka-lite/blob/master/kalite/legacy/i18n_settings.py#L70

**Comment by rtibbles** [comment]
@aronasorman I thought you had enforced this?

In good news, @dylanjbarth we should be getting rid of the dubbed video mapping file completely before we release 0.16 - so maybe the best way to solve this is to excise all references to it?

**Comment by dylanjbarth** [comment]
:+1: 

this is a dupe of https://github.com/learningequality/ka-lite/issues/4198. Going to boldly close that one, since this one has a bit more context. 

NB this occurs on develop, Windows 8.1 and Mac

**Comment by dylanjbarth** [comment]
annnnnnd I can't close issues I don't own :laughing:

**Comment by benjaoming** [comment]
This shouldn't be a problem anymore. I didn't try out the steps directly, but a lot of the steps seemed out-dated. I've removed most of the wiki page and instead refer to this page:

http://ka-lite.readthedocs.io/en/develop/developer_docs/environment.html
