### ISSUE TITLE
Use latest tastypie

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4797]
Because of issues in the previous tastypie, we made a patch to use a pre-release directly from Github.

But it seems the latest version is now out: https://github.com/django-tastypie/django-tastypie/issues/1005#issuecomment-177321680

**Comment by rtibbles** [comment]
@benjaoming is this done? Should I take this for a quick fix?

**Comment by benjaoming** [comment]
the latest tastypie is released, I remember taking it for a test spin without issues

**Comment by benjaoming** [comment]
geh, actually I think tastypie undundling is only done in develop... setup.py has this though:

        # Hotfix for the one single tastypie dependency link. Not nice.
        # To be removed as soon as an upstream tastypie fixes our
        # Django 1.5 issue
        opts.process_dependency_links = True

**Comment by benjaoming** [comment]
But it looks like tastypie is in python-packages for 0.16.x

**Comment by rtibbles** [comment]
OK, should we punt this to 0.17 then?

**Comment by benjaoming** [comment]
Yup, I think the intention of having it as a release blocker was that the unbundling had caused issues with the Mac installation builder because the installation source for tastypie was git repo. Which it shouldn't be anymore.

**Comment by benjaoming** [comment]
Leaving this open, however it should be noted that we cannot upgrade Tastypie before we move to Django 1.7+ and can use django.db.migrations. The fix for South mentioned in the description was never released for the 0.12 tastypie branch.

**Comment by benjaoming** [comment]
We are now sadly using our own fork, `django-tastypie-legacy` and it will remain so until and if ever KA Lite stops being dependent on South + Django 1.5.
