### ISSUE TITLE
No content database on first run of dist

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4802]
Creating a dist and installing it, renders a KA Lite without a content db:

```
make dist
mkvirtualenv test
workon test
pip install dist/ka-lite-0-16a1.tar.gz
```

@rtibbles I can try fixing this if you give me a hint about what's wrong below:

```
➜  ~  kalite start
Running 'kalite start' as daemon (system service)

Stand by while the server loads its data...

Error reading secret key file. Generating one now. Error was: [Errno 2] No such file or directory: '.kalite/secretkey.txt'
2016-02-02 02:39:19,419 - INFO:kalite: Setting up KA Lite; this may take a few minutes; please wait!

                                     
   _   __  ___    _     _ _          
  | | / / / _ \  | |   (_) |         
  | |/ / / /_\ \ | |    _| |_ ___    
  |    \ |  _  | | |   | | __/ _ \   
  | |\  \| | | | | |___| | ||  __/   
  \_| \_/\_| |_/ \_____/_|\__\___|   
                                     
https://learningequality.org/ka-lite/
                                     
         version 0.16.a1
                                     
WARNING:root:It's recommended that you install Python version 2.7.9. Your version is: 2.7.6

Cleaning *pyc files (if writable) from: .virtualenvs/kalite_pip/share/kalite/dist-packages
Cleaning *pyc files (if writable) from: .virtualenvs/kalite_pip/share/kalite/python-packages
(Re)moving database file to temp location, starting clean install. Recovery location: /tmp/tmpuoTjGT
Copying database file from .virtualenvs/kalite_pip/lib/python2.7/site-packages/kalite/database/data.sqlite to .kalite/database/data.sqlite
Found bundled assessment items
Generating 2048-bit RSA encryption key (may take a few minutes; please wait)...
Done!
Device 'test' has been successfully initialized.
Annotating availability of all content, checking for content in this directory: (.kalite/content)
2016-02-02 02:39:23,478 - INFO:kalite: Annotating content for language: en, channel: khan
INFO:kalite:Annotating content for language: en, channel: khan
2016-02-02 02:39:23,479 - ERROR:kalite: No content database file found
ERROR:kalite:No content database file found
```

**Comment by benjaoming** [comment]
I see the problem.

The content database is not part of the dist, but it's user data. It's being generated as user data with the Makefile, but we need to copy it into a distributed location.

Furthermore, we need to alter the setup script to detect if there is a bundled in database in the package data (as we do with the pre-migrated default database).

**Comment by benjaoming** [comment]
I'm struggling to understand the role of the newly introduced and separate Python 3.5 project `content-pack-maker` and how it fits into our dist chain. Does KA Lite now have a new build dependency? And is it requiring Python 3.5? And which components does it affect? My initial speculation was that `make assets` had been prepared to invoke `init_content_items`, however I see this command is very slow and `--bulk-create` is borked.

I would like to continue to work on this approach from #4804, though, as I think it's going to be difficult to integrate content-pack-maker into KA Lite's dist chain.

**Comment by benjaoming** [comment]
It seems that the `--bulk-create` would be key to cutting down runtime costs of `init_content_items`, however it has this problem:

``` 
2016-02-02 20:54:57,329 - INFO:kalite: Creating database file at code/ka-lite/kalite/database/content_khan_en.sqlite
2016-02-02 20:54:57,510 - INFO:kalite: Generating flattened topic tree for import
2016-02-02 20:54:59,781 - INFO:kalite: Bulk creating 14804 topic and content items
Traceback (most recent call last):
  File "code/ka-lite/python-packages/django/core/management/base.py", line 224, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "code/ka-lite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "code/ka-lite/kalite/contentload/management/commands/init_content_items.py", line 148, in handle
    bulk_insert(items, database_path=database_path)
  File "code/ka-lite/kalite/topic_tools/content_models.py", line 124, in wrapper
    output = function(*args, **kwargs)
  File "code/ka-lite/kalite/topic_tools/content_models.py", line 496, in bulk_insert
    Item.insert_many(map(parse_model_data, items[idx:idx + 500])).execute()
  File "code/ka-lite/dist-packages/peewee.py", line 2980, in execute
    cursor = self._execute()
  File "code/ka-lite/dist-packages/peewee.py", line 2469, in _execute
    sql, params = self.sql()
  File "code/ka-lite/dist-packages/peewee.py", line 2954, in sql
    return self.compiler().generate_insert(self)
  File "code/ka-lite/dist-packages/peewee.py", line 1772, in generate_insert
    value = row_dict[field]
KeyError: <peewee.CharField object at 0x7f2f64e16850>
```

**Comment by benjaoming** [comment]
To avoid implementing a new feature in all the installers just before the release, we are going to try and make the source distribution comply with the usual deal: That it contains Khan Academy in English. This only requires the content item db, not a full language pack.

For future installers to ship with a pre-bundled content pack, I recommend that we discuss a universal way of preseeding content packs into a well-known location. I scheduled it for 0.17, but please disagree if you think installers with different content packs should already be on the menu for 0.16: #4805

**Comment by rtibbles** [comment]
It seems there has been a severe breakdown of communication here - sorry that we have not communicated these things. My understanding was that we were shifting all content database generation to content-pack-maker, and that the installers would be pulling in the English content DB from there.

As it is, the plan to use init_content_items to generate the content database will not work. The content database also includes the AssessmentItem database now, but init_content_items does not generate that data, and would need contentload to be run during installer build to fetch the assessment_items.json if it were implemented (if you're worried about build speed, you don't want to be running contentload).

**Comment by benjaoming** [comment]
I just had a call with @aronasorman and the understanding was that we can continue to use `init_content_items` and ship a source dist with a bundled English content item db so we don't have to change all the installers for 0.16. But if the assessment items zip won't contain adequate data, then we can't do it.

I see signs that changes are missing in the codebase, namely the Makefile, that should reflect that assessment items are now loaded through content packs. Can you list the consolidations that are missing? And what are the instructions for the installers maintainers? @aronasorman was going to outline the contents of a content pack, where they can be downloaded, and what commands the installers should call the install them.

Furthermore, where does this leave our assessment item downloads which are bundled into the installers? It seems they have to be correlated to a specific content pack?

**Comment by aronasorman** [comment]
@benjaoming, sorry, talking at lunch wasn't conducive to the conversation we had :) I sent an email to the dev list containing the changes that had to be made. We can continue the conversation there.

**Comment by aronasorman** [comment]
@benjaoming 

> Richard has pointed out that the assessment items db is now a part of
the content packs, and that init_content_items doesn't create it.
Wouldn't this lead to inadequate assessment item data because combining
an sdist with the current state of the installers would provide: sdist
data (content item db) + assessment item .zip... but NO assessment item db.

The assessment item db is now part of the the single content db. So it should work!

**Comment by benjaoming** [comment]
> The assessment item db is now part of the the single content db. So it should work!

But not the one generated with `init_content_items` command?

**Comment by rtibbles** [comment]
No, I rather crossed the Rubicon on this one...

**Comment by benjaoming** [comment]
Okay cool, I shall continue #4804 tomorrow and try to make the --bulk-create option work.
