### ISSUE TITLE
Platform independent well-known location for bundled content packs

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4805]
Installers for Mac/Win/Debian should be able to place a content pack at a well-known location, and `kalite manage setup` should then discover and install them.

This is an issue to solve in KA Lite so we avoid duplicating the same logic in the installers.

**Comment by cpauya** [comment]
:+1: on this

**Comment by MCGallaspy** [comment]
Are content packs user data (in other words, are they only available on a per-user basis)? Or if there are two KA Lite users on the same machine, should they share content packs?

**Comment by benjaoming** [comment]
@MCGallaspy good question! Problem is that the answer is both *yes* and *no* :)

Yes:

 * Content item + assessment item db is updated by means of user actions when videos are downloaded and marked available. Video content folders are user data, so this can't be shared.

No:

 * Subtitles
 * Interface translations
 * Assessment item db (but that's now part of content item db so can't be separated)

**Comment by benjaoming** [comment]
NB! Solving this issue will have a side-effect in that the content pack .zip will be placed in a system-wide location and remain after unpacking, so our Hardware Requirements' disk space item should be bumped by ~600 MB.

**Comment by benjaoming** [comment]
We assume that  `setup` is only run when installing new systems or upgrading. Therefore, it should be safe to assume that an auto-discovered content pack is always provided by the installer.

Automatically unpacking it means over-writing the content.db of that language. The harm this can do should only happening to systems with an unclean upgrade path, i.e. `install 0.17 deb -> install 0.18 from pip -> kalite manage setup`. The 0.18 pip installer will then discover the assessment item zip from 0.17 regardless and unpack it. We can avoid the worst cases by always detecting that we're running from a virtual environment and in that case skip auto-discovery.

**Comment by benjaoming** [comment]
Fixed in #5285

If content packs are placed in `<kalite.ROOT_DATA_PATH>/preseed/contentpack.<lang>.zip` (for instance `/usr/share/kalite/preseed/contentpack.en.zip`), it will be automatically found and installed with `retrievecontentpack local <lang> <path>` during `kalite manage setup`.

...if a virtuanenv is active, the whole process is skipped
