### ISSUE TITLE
No sort order on content items

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#4811]
Currently there is no way for determining which order items at the same level and under the same parent in the topic tree should be sorted.

This was not apparent previously, due to the particular idiosyncratic way in which init_content_items sorted through the nodes. Due to this, the order of the ids (which I believe defines the default sort order) happened to coincide with the original sort order of the nodes.

This will no longer be the case when the content packs are imported.

**Comment by aronasorman** [comment]
So if I get this correctly, we'll now have to codify the order we get from KA into some other field that we can use to order in KA Lite?

**Comment by rtibbles** [comment]
Yeah - this also aligns nicely with what we have in the content curation, so it will map well to that.

Come to think of it, we also need this in the Kolibri content app!

**Comment by rtibbles** [comment]
Fixed in #4818
