### ISSUE TITLE
Unpacking assessment zip items doesn't update content item db

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4815]
Branch: 0.16.x

Scenario:

1. Empty .kalite dir
1. Run `kalite start`
1. Run `kalite manage unpack_assessment_zip assessments.zip`
1. `kalite restart`

Expected result: That you can use assessment items.

Result: You can't  :) Everything is disabled, seems db isn't updated.

![screenshot from 2016-02-05 01 16 27](https://cloud.githubusercontent.com/assets/374612/12834211/1ddeb77a-cba6-11e5-9630-75e184c2d166.png)

**Comment by rtibbles** [comment]
Fixed in #4814
