### ISSUE TITLE
XO Laptop Browsers not working.  Any suggestions?

### ISSUE THREAD

**Issue by edresor** [learningequality/ka-lite#4820]
This is a report from a location in Kenya with 50 old XO Laptops with keyboards.
Is there a browser that could be installed on these laptops that would work with KA-Lite?
The existing browsers are working with other content on a RACHEL Server.
Is there an Internet site that could be used to test the browser if the laptop was taken to an Internet Cafe.
I hope to get you more information on the specific hardware and software version, both the Sugar Operating System and the browser.  Is there any specific information that I should request?
Is there an older version of KA-Lite that would work?
We will probably recommend using the XOs for other duties, but we do want to offer this option if it exists.

I found this browser, but it seemed to be designed just to play downloaded videos:
https://github.com/llaske/KAView.activity

**Comment by MCGallaspy** [comment]
I am not familiar with the Sugar Operating System. KA Lite (from version 0.13.0 or later) should work on the latest versions of Firefox and Chrome, as well as IE 9 or later. Here's the [doc page](http://ka-lite.readthedocs.org/en/latest/installguide/system_requirements.html#supported-browsers).

I am also not familiar with the other project you link to -- personally I recommend installing the latest version of Firefox or Chrome available to you, and seeing if it works. If it doesn't, it would be helpful to report back to us the browser version and KA Lite version, so we can note the incompatibility.

>Is there an Internet site that could be used to test the browser if the laptop was taken to an Internet Cafe.

I'm not sure what you mean exactly -- are you asking if there's a way to test KA Lite's compatibility with several different browsers? You could install the browsers and try it out. We also host a version of KA Lite for demo purposes that you could test with different browsers (it appears to be down just now, investigating): http://demo.learningequality.org/

Finally, it would be helpful to know *what* exactly the error is -- the given details are too vague even to know if there's truly a browser incompatibility.

**Comment by benjaoming** [comment]
Closing this, missing input from original reporter @edresor - but thanks for reporting nonetheless and good luck with your project. For any support etc. know that we've opened up a new community support forum: http://community.learningequality.org/

**Comment by quozl** [comment]
Noticed this issue by accident as it was closed; as far as I can tell it didn't come to OLPC.

No, there is no solution available other than transcoding to a different format or lower resolutiuon.

(Even if the CPU instruction set compatibility issue was overcome with custom builds of Firefox or Chrome, or if a modern WebKit was rebuilt, the I/O bandwidth of the graphics system is too low for the bandwidth of the videos.  The bandwidth chosen by KA Lite is not suited to these old XO laptops in Kenya.)
