### ISSUE TITLE
No exercises in the english content pack

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#4828]
![screen shot 2016-02-09 at 10 59 44](https://cloud.githubusercontent.com/assets/191955/12927290/4d29bfb0-cf1c-11e5-9344-ad379daaea8e.png)

@rtibbles is this expected behaviour? How can I make them appear again?

**Comment by benjaoming** [comment]
@aronasorman inspiration? https://github.com/learningequality/ka-lite/pull/4814/files#diff-3c6d0f7bbed8027d175ec1956e17e8eeR69

**Comment by aronasorman** [comment]
This turned out to be an issue on the `content-pack-maker` side.
