### ISSUE TITLE
Remove legacy local_settings and CONFIG_PACKAGE code

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4830]
Prior to 0.16.0 we deprecated some code. In 0.16.0 we began raising exceptions (see #4829). However, it remains to remove the old unused code:
- In `kalite/settings/__init__.py`, remove the logic dealing with CONFIG_PACKAGE -- this may have ramifications in other parts of the settings pipeline that need to be dealt with.
- In `kalite/settings/base.py`, remove logic that uses `local_settings` -- importing them is now an error.

**Comment by yash14123** [comment]
I would like to work on this.

**Comment by MCGallaspy** [comment]
Hi @yash14123, you're more than welcome! Please target your changes to the `develop` branch.

**Comment by benjaoming** [comment]
Fixed in #5375
