### ISSUE TITLE
Video download: Successful error

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4833]
If downloading fails, you get this sort of really weird error.

![screenshot from 2016-02-10 18 02 02](https://cloud.githubusercontent.com/assets/374612/12954818/76eeb04e-d020-11e5-83d3-656a03411003.png)

Furthermore, there's no instructions advising the user what went wrong.

**Comment by yash14123** [comment]
I am on it. :)

**Comment by benjaoming** [comment]
Cool! I can't assign you, though, something's messed up with the Github "Assignee" function atm. But consider yourself assigned, anyways :)

**Comment by benjaoming** [comment]
Fixing #4892 will address issues like this.
