### ISSUE TITLE
"Login" modal on top of "Create Admin Account" modal

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4834]
How to recreate:

1) Have a clean installation w/o user accounts
2) Hit a url that's login protected, for instance: http://localhost:8008/update/videos/

Result:
![screenshot from 2016-02-10 19 56 29](https://cloud.githubusercontent.com/assets/374612/12958191/c7e9e81e-d030-11e5-9473-64a7f1b859ed.png)

Expected result: The "Create Admin Account" is always on top.

**Comment by 66eli77** [comment]
is this master or 0.16?

**Comment by 66eli77** [comment]
yes, I can reduplicate the issue on 0.16.x
