### ISSUE TITLE
Javascript error on "My Progress" page

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4840]
Currently on `0.16.x` (see [this comment](https://github.com/learningequality/ka-lite/pull/4832#issuecomment-183450219)):

To reproduce, log in as a student (possibly with 0 points) and navigate to the "My Progress" page from the user's dropdown menu.
Observe the following error in the console:

```
Uncaught ReferenceError: show_message is not defined
  collection.fetch.success @ views.js:96
  options.success @ backbone.js:1027
  fire @ jquery.js:3099
  self.fireWith @ jquery.js:3211
  done @ jquery.js:8264
  (anonymous function) @ jquery.js:8605
```

**Comment by shubhsingh594** [comment]
can i take this ?

**Comment by rtibbles** [comment]
Yes, @shubhsingh594 - first check that the JS module that defines 'show_message' is being imported, and if it is, make sure that show_message is being referenced as a method of it. My guess is that it probably just needs to be properly namespaced.
