### ISSUE TITLE
Contentrec error after upgrade to 0.16

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4844]
#### Upgrade scenario

0.14 to 0.16 on OSX Yosemite.
Build: # 64 .pkg installer

Confirmed on 0.14 to 0.16 upgrade on Win7
Build: # 114 .exe installer

#### Current Behavior

After upgrade to 0.16, logging in as learner gives `no such table: item` error on contentrec /welcome page.

Mac:

![no_such_table_item_err_0 14-to-016_yosemite](https://cloud.githubusercontent.com/assets/1457929/13049444/446f4d10-d3ed-11e5-808b-ee4c582ac0ac.png)

Windows:

![no_such_table_item_err_0 14-to-016_win7](https://cloud.githubusercontent.com/assets/1457929/13049450/4da5f370-d3ed-11e5-9e21-b783d7816859.png)

#### Steps to reproduce
1. Upgrade from 0.14 to 0.16
2. Login as learner.

**Comment by radinamatic** [comment]
Confirmed on both:
- upgrade 0.15 to 0.16 on OSX Yosemite. (# 64 build)
- upgrade 0.15 to 0.16 Win7 (build # 114)

![danish_err_0 15-to-016_yosemite](https://cloud.githubusercontent.com/assets/1457929/13049527/e863665e-d3ed-11e5-85ce-f30afce515ef.png)

**Comment by radinamatic** [comment]
With latest merges on 0.16 branch, this error changed to `no such column: t1.sort_order`:

![content_rec](https://cloud.githubusercontent.com/assets/1457929/13059981/69311160-d42e-11e5-8bf7-25e977a0efaa.png)

**Comment by MCGallaspy** [comment]
I assume this has something to do with the fact that content packs are not properly bundled in?

**Comment by MCGallaspy** [comment]
Thanks for the report!

**Comment by radinamatic** [comment]
No prob @MCGallaspy! I suspected the issues I opened yesterday had something to do with content packs, but I prefer to have a record of issue to re-check (instead of trying to remember what the heck was wrong the first time around), and close when it's fixed - it's cathartic! ;)

**Comment by radinamatic** [comment]
Latest merge from upstream/0.16.x there is still `no such table: item` error on contentrec, probably 'cause I still can't get any content in it (`Channel khan does not exist` issue).

However, on Alpha3 deb installer, which comes bundled with exercises, my Learner gets a different contentrec error:

![contentrec](https://cloud.githubusercontent.com/assets/1457929/13273439/db0235a0-daa3-11e5-9b5c-bbe244d4a2dc.png)

Hm, maybe I should open a separate issue...?

**Comment by aronasorman** [comment]
First time i've ever seen that error @radinamatic. File a separate issue!

**Comment by radinamatic** [comment]
Me neither, @aronasorman... 

Trying to replicate on another VM today with the same 0.16 Alpha3, but no luck so far!

**Comment by rtibbles** [comment]
Let's close this as contentpack related, and I'll look into the content rec issue.
