### ISSUE TITLE
Too much recursion 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4845]
#### Version

0.15.1 on OSX Yosemite.
Not sure if worth correcting, I'm reporting in case if it can give clues to other upgrade issues and/or it needs to be taken into account.

#### Current Behavior

No error in UI, but it appears in console while downloading videos in French: 

![0 15 1_yosemite_too_much_recursion_err](https://cloud.githubusercontent.com/assets/1457929/13049820/c79d06bc-d3ef-11e5-823e-3a98b6758b0b.png)

#### Steps to reproduce
1. Login as admin.
2. Download French language pack.
3. Try to download videos.

**Comment by MCGallaspy** [comment]
Cool, thanks again for the detailed reports!

**Comment by rtibbles** [comment]
@radinamatic When the language packs are ready, can you confirm this is fixed? I suspect this will no longer be the case in 0.16.x

**Comment by radinamatic** [comment]
Yes, I haven't commented on this one again, it seems like one-time-only bug so far... Waiting for the progress bar on languages pack to be working correctly, to chalk it off definitely!

**Comment by radinamatic** [comment]
Seeing now that it doesn't happen only with videos in French, but every other language (tested on Danish & Portuguese so far) a part form English. 0.15 on OSX Yosemite.

**Comment by radinamatic** [comment]
Seems fixed on the latest Beta1 on Ubuntu, will retest on .pkg later and close it then.

**Comment by radinamatic** [comment]
Non extant on latest .pkg installer (build 76). Closing.
