### ISSUE TITLE
Errors viewing exercises after upgrade  

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4846]
#### Upgrade scenario

0.15 to 0.16 on OSX Yosemite.
Build: # 64 .pkg installer

#### Current Behavior

I'm not able to open any exercise after upgrade:

![exercise_err_0 15-to-016_yosemite](https://cloud.githubusercontent.com/assets/1457929/13050041/23178944-d3f1-11e5-9445-7f4df0137b6c.png)

I have similar issues on direct install of 0.16 on El Capitan, but will issue them separately.

**Comment by MCGallaspy** [comment]
As with your other error, I think this has something to do with the incomplete nature of 0.16 at this time. Will update you when we have a fix for this. Thanks for the report!

**Comment by rtibbles** [comment]
I can no longer replicate this error, closing.
