### ISSUE TITLE
Errors viewing exercises - 0.16 on OSX 10.11 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4847]
#### Version

0.16 (build: # 64) on OSX El Capitán

#### Current Behavior

It seems impossible to view any exercise, but error messages are different:

Logged in as learner
![addition-exercise-err_el_capitan](https://cloud.githubusercontent.com/assets/1457929/13050198/1bc48d30-d3f2-11e5-9fa2-71829aa8041d.png)

![stoch-exercise-err_el_capitan](https://cloud.githubusercontent.com/assets/1457929/13050204/236c338a-d3f2-11e5-9ba6-d074c399bc32.png)

#### Non logged-in user
![kritiosboy-exercise-non-logged-in-err_el_capitan](https://cloud.githubusercontent.com/assets/1457929/13050257/75608c2c-d3f2-11e5-8f0b-2da84ccd78f7.png)

**Comment by rtibbles** [comment]
Two issues going on here:

1) Assessment items not being in the content database.
2) Exercise templates not being properly referenced in the content database.

@aronasorman I think you were in the process of fixing these issues, yes?

**Comment by radinamatic** [comment]
Not sure which PR fixed this at this point, but it's not extant on newest installers or 0.16 branch. Closing!
