### ISSUE TITLE
Wrong screenshot for video download in user docs

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#4848]
Branch: 0.15.x and 0.16.x

Expected Behaviour: Docs page for downloading videos should show video download page.

Current behaviour: Not that.

![image](https://cloud.githubusercontent.com/assets/1680573/13057565/df95db86-d3d1-11e5-8e2b-d3eecdfe8950.png)

**Comment by manipalsingh013** [comment]
Hey @rtibbles can I take this one?

**Comment by rtibbles** [comment]
Please do. Should be a very small fix!

Branch from 0.16.x and target your PR there.

**Comment by manipalsingh013** [comment]
@rtibbles alright.

**Comment by manipalsingh013** [comment]
can't solve as error appear on taking new screenshots(#4862)

**Comment by rtibbles** [comment]
@MCGallaspy could you do a quick fix for this with your screenshot expertise?

**Comment by radinamatic** [comment]
Fixed in  #5047 and non extant in current docs, closing!
