### ISSUE TITLE
KA-Lite Wifi isn't letting connections.

### ISSUE THREAD

**Issue by SkaeX** [learningequality/ka-lite#4860]
I have set up KA-Lite 0.15 on Rasbian Wheezy. I tried setting up the Raspberry Pi wifi as the ka-lite docs instructed (with wipi and edimax), but the kalite network just comes up not allowing any connection (i.e. tablets keeps attempting to connect without success). I don't know if i am the only one who ran into this.

**Comment by MCGallaspy** [comment]
Hi @SkaeX, thanks for the report! I'm tagging this so we can attempt to replicate it while testing 0.16 on the Raspberry Pi.

**Comment by benjaoming** [comment]
The resources here:

https://github.com/learningequality/ka-lite-hotspot

and here:

https://github.com/learningequality/ka-lite-config-pi

...Are only very sparsely tested! :)

We can try to help you with suggestions, but we need some more feedback. Could you provide some kind of error description? Like does the network SSID show up on your clients? Is it the WIFI authentication? Is it the KA Lite app that you can't connect to? Can you ping the RPi using its local IP address on the WIFI interface?

**Comment by SkaeX** [comment]
Thank you for the reply. The SSID shows up but not allowing clients to connect. I narrowed the problem to the /etc/network/interfaces where it say wpa-conf .... Commenting these lines allows clients to connect

**Comment by benjaoming** [comment]
In that case you've created an open WIFI I guess. If it suits your needs, then go for it, it's much easier to manage!

**Comment by SkaeX** [comment]
In addition, I have a problem with the port. 80 sends me to nginx welcome page. I'll have to specify 7007. This however stops the pop up window in iOS and Mac OSs clients. So I sometimes edit the python redirect script to 7007

**Comment by SkaeX** [comment]
Sorry but is the open network good? The wpa-conf spit out errors for ifup and ifdown

**Comment by benjaoming** [comment]
You are free to change the port to port 80. It's not the default, but you can customize your settings in `/etc/nginx/sites-enabled`

1. remove the `default` file
1. Change the ka-lite file to listen to port 80
1. (set `PRODUCTION_PORT=80` as the last line in `/home/pi/.kalite/settings.py`)

**Comment by benjaoming** [comment]
@SkaeX I can't support you on wpa-conf, sorry.

**Comment by SkaeX** [comment]
Thank you @benjaoming. I really like the learning equality and looking forward to being part of it.

**Comment by benjaoming** [comment]
You are most welcome :)

I forgot a step regarding the nginx port reconfiguration:

4: `service nginx restart` and `service ka-lite restart`

**Comment by benjaoming** [comment]
Closing this in favor of #5228
