### ISSUE TITLE
Coach Reports - tabular view seems to specifically pull up "absolute values" course

### ISSUE THREAD

**Issue by sethachoi** [learningequality/ka-lite#4867]
Branch: 0.16.x
Dev mode, Mac OSX 10.10

Steps to Reproduce:
1. Log in as coach/admin
2. Go to "teach" tab
3. Switch groups/facilities/date, whatever needed to retrieve some actual data
4. Open up tabular view

Expected Results:
Tabular view data of all the courses that have been selected OR that have any data within the time frame in the case of default overview course selection

Actual Results:
For some reason, every time (or most times) I open it up, I see specifically just one column, for Absolute Values. In the case I specifically select absolute values, there's two columns of absolute value and for some reason a third other topic.

Notes:
It would really be good to get some second eyes on this because it might be some weird edge case from me messing with the admin panel / putting in content logs and such.

![screen shot 2016-02-18 at 11 48 37 am](https://cloud.githubusercontent.com/assets/5778980/13156248/62642278-d636-11e5-8432-1b3c1946c2a2.png)
![screen shot 2016-02-18 at 11 48 55 am](https://cloud.githubusercontent.com/assets/5778980/13156249/626a72b8-d636-11e5-85ae-bff4248b9aa3.png)

**Comment by rtibbles** [comment]
Have you also tried just running `kalite manage generaterealdata` and then looking at that data in the tabular report too?

**Comment by sethachoi** [comment]
That was the base of my data, I added specific logs on top of that to test the radial visualization stuff (hours logged vs content hours)

**Comment by rtibbles** [comment]
Gotcha. If there's plenty of other data in there, then yes, it's a weird catch. May be to do with the way we are handling the topic selector?

**Comment by sethachoi** [comment]
Upon further testing it was specific to my case, I think it had something to do with some manually created content/exercise log entries? Either way it looks like it works just fine in the typical use case, but for testing the issue might still exist

**Comment by MCGallaspy** [comment]
Oh, it's been closed. Carry on.
