### ISSUE TITLE
Coach Reports - tabular view pulls up full range of data regardless of  topic selection

### ISSUE THREAD

**Issue by sethachoi** [learningequality/ka-lite#4869]
Branch/Build: 0.16.x, OSX 10.10

Steps to Reproduce:
1. Sign in as admin/coach
2. Go to Teach tab
3. Do what is needed to fetch some real data (different facility, group, dates, etc)
4. Check the tabular view
5. Now do some topic selection
6. Check tabular view again

Expected Results:
Tabular view should have different data depending on usage of topic selection or "default overview"

Actual Results:
Tabular view shows the same full range of data both times

**Comment by MCGallaspy** [comment]
Thanks for the report @sethachoi!

**Comment by shubhsingh594** [comment]
can i work on this issue ?

**Comment by rtibbles** [comment]
This already has an open pr for a fix.

**Comment by shubhsingh594** [comment]
@rtibbles  oh okay, this didnot have a hasPR label so i was enquiring

**Comment by rtibbles** [comment]
Oh, sorry, I made the fix but didn't open the pr yet, my mistake!

**Comment by rtibbles** [comment]
Fixed in #4919
