### ISSUE TITLE
GSoC 2016?

### ISSUE THREAD

**Issue by amtrivedi91** [learningequality/ka-lite#4876]
Hello Everyone, 

I wanted to know whether FLE applied as a mentoring organization for GSoC 2016 ? If yes, where can I find the idea list?

Pardon me, I could not find a better place to ask this question.

**Comment by rtibbles** [comment]
Yes.

**Comment by amtrivedi91** [comment]
@rtibbles Thanks, but I couldn't find the idea list, when will the list be out?

**Comment by MCGallaspy** [comment]
FYI, please email our `info (at) learningequality (dot) org` mailing list for GSoC inquiries.
