### ISSUE TITLE
Does not show login modal after first creating the account

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4879]
## Summary

After  #4855, the login modal isn't allowed to display when a user has just created a new admin account.

@66eli77 could you do a quick fix?

## Branch or installer method

 - Branch: develop (?)

## Traceback or relevant snippet from server.log

The page is called, but nothing happens, no modal is displayed

```
[INFO] [2016-02-21 22:57:09,226] django.request: HTTP Request /api/django_user_form - Response: 200
[INFO] [2016-02-21 22:57:12,011] django.request: HTTP Request /api/django_user - Response: 200
```

## How to reproduce

1. Clean install, create admin account
1. Click the "Login" button in main menu

## Screenshots

*If applicable*

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

*If applicaple*

**Comment by rtibbles** [comment]
Fixed in #4896
