### ISSUE TITLE
Failed download is marked as available

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4880]
## Summary

If a video file failes to download, it's still marked as available

## Branch or installer method

 - Branch: develop

## Traceback or relevant snippet from server.log

```
None
```

## How to reproduce

1. Start KA Lite and navigate to Video tab
1. Kill your external internet connection
1. Start a download using the Video tab

## Screenshots

*If applicable*

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

*If applicaple*

**Comment by shubhsingh594** [comment]
can i take this ?

**Comment by benjaoming** [comment]
I'm going to replace the whole download logic over in #4892 :)

**Comment by shubhsingh594** [comment]
okay

**Comment by rtibbles** [comment]
Not able to replicate this issue.

**Comment by rtibbles** [comment]
@aronasorman please confirm as part of your video download testing.

**Comment by benjaoming** [comment]
Nope, works now! It must've been related to the progress log issue.
