### ISSUE TITLE
Python 2.7 warning overkill?

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4883]
## Summary

We are warning current Ubuntu Trusty users about their Python version.

## Branch or installer method

 - Branch: develop

## Traceback or relevant snippet from server.log

```
[WARNING] [2016-02-22 03:29:14,870] root: It's recommended that you install Python version 2.7.9. Your version is: 2.7.6
```

**Comment by rtibbles** [comment]
Fixed in #4889
