### ISSUE TITLE
Summary of correctly answered questions missing

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4895]
## Summary

Usually, you'd get green check marks for each correctly answered question.

## Branch or installer method

 - Branch: prereleases/0.16a3

(actually the PPA 0.16~a3-ubuntu1 installer)

## Traceback or relevant snippet from server.log

```
less ~/.kalite/server.log | grep 404
(nothing returned)
```

## How to reproduce

1. Answer an exercise correctly
1. Go to next question
1. Nothing

## Screenshots

![screenshot from 2016-02-23 01 12 41](https://cloud.githubusercontent.com/assets/374612/13237246/e27cd77e-d9ca-11e5-90cf-75437df5b259.png)

![screenshot from 2016-02-23 01 12 51](https://cloud.githubusercontent.com/assets/374612/13237253/f0f5ec1e-d9ca-11e5-8dea-1c88d95e2028.png)

**Comment by rtibbles** [comment]
What kind of user are you logged in as? What is JS console output?

**Comment by benjaoming** [comment]
No JS errors, just the usual:

    mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

**Comment by benjaoming** [comment]
Logged in as admin

**Comment by rtibbles** [comment]
And the kind of user you are logged in as?

**Comment by rtibbles** [comment]
No answer tracking as admin.

**Comment by benjaoming** [comment]
Okay I see, it was just having a weird empty space for those types of users.

![screenshot from 2016-02-23 01 20 13](https://cloud.githubusercontent.com/assets/374612/13237345/a18f9fb6-d9cb-11e5-9363-b8dd0904c6c6.png)
