### ISSUE TITLE
Videos shown twice in Update tab

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4901]
## Summary

See subject

## Branch or installer method

 - Branch: develop

## Screenshots

![screenshot from 2016-02-23 17 38 36](https://cloud.githubusercontent.com/assets/374612/13258650/4c30b396-da54-11e5-91dc-e1ac5ce2dc4b.png)

**Comment by benjaoming** [comment]
@aronasorman this is possibly associated with the total_files=0 bug, dunno. I leave it to you :)

**Comment by aronasorman** [comment]
The `total_files` bug is now fixed though with the latest content db. So there's something else going on here.

I'll get to this by tomorrow.

**Comment by benjaoming** [comment]
@aronasorman okay I see that en-minimal.zip has been updated, making sure it's in use and total_files check is not the cause.

**Comment by benjaoming** [comment]
Cool, it works after the new content.db from en-minimal is loaded and total_files=0 is used. Making a PR.

**Comment by benjaoming** [comment]
![screenshot from 2016-02-23 18 15 47](https://cloud.githubusercontent.com/assets/374612/13259905/aa11187a-da59-11e5-9c67-76ab853d5870.png)

**Comment by rtibbles** [comment]
Fixed in #4903
