### ISSUE TITLE
Reinstate annotation_tests

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#4902]
## Summary

I deleted the annotation tests in [this commit](https://github.com/aronasorman/ka-lite/commit/a6370654915c0a9287f8335ce48353c2458fdf7b), since they weren't fit for purpose. I need to bring them back again to make sure that the annotation is properly tested, at least for videos.

**Comment by manipalsingh013** [comment]
You want to bring " from annotate_tests import * " this back or is there something else you want. If so, Please explain.

**Comment by aronasorman** [comment]
Good catch! Turns out I just deleted the import. However, these tests will still fail: https://github.com/learningequality/ka-lite/blob/0.16.x/kalite/topic_tools/tests/annotate_tests.py

Because it's not capturing the right behaviour anymore.

**Comment by aronasorman** [comment]
So we'll need to make the tests pass now.
