### ISSUE TITLE
'Done' button looks disabled when inline help is complete

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#4905]
## Summary

When the final step has been reached in the inline help - the 'Done' button is still grayed out, especially compared to the 'Back' button, making it seem as if going back is the only option.

## Branch or installer method

 - Branch: 0.16.x

## How to reproduce

- Login as admin.
- Click on 'show me how'
- Click 'next' until all the steps have been exhausted.

## Screenshots

![image](https://cloud.githubusercontent.com/assets/1680573/13270260/b8088926-da41-11e5-9e87-b82394597c43.png)

**Comment by manipalsingh013** [comment]
Hey @rtibbles I would like to work on this, can I?

**Comment by manipalsingh013** [comment]
Skip button also seems to be disabled.
![skip key](https://cloud.githubusercontent.com/assets/13970876/13280310/39a9ebd4-db03-11e5-9e2a-e4fa428e549d.png)

should that also be changed?

**Comment by manipalsingh013** [comment]
Skip and Done are actually same button with button value changing when inline help steps are finished.

**Comment by rtibbles** [comment]
Yes, restyling it would be handy!

**Comment by manipalsingh013** [comment]
hey @rtibbles styling for button is coming from some other repo (https://github.com/usablica/intro.js/blob/master/introjs.css#L266 color used here sets the skip button text color )or is there anything that I'm missing??

**Comment by rtibbles** [comment]
Probably, but we could try to override it in our style.

**Comment by rtibbles** [comment]
Fixed in #4916
