### ISSUE TITLE
Erroneous warning that khan channel is not present

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#4906]
## Summary

Erroneous Warning in logging output.

## Branch or installer method

 - Branch: 0.16.x

## Traceback or relevant snippet from server.log

```
[WARNING] [2016-02-23 15:22:02,206] kalite: Channel khan does not exist.
```

## How to reproduce

- Run make assets.
- Start server.

**Comment by benjaoming** [comment]
Not seeing that no more somehow.
