### ISSUE TITLE
Suggestion: pictograms instead of passwords

### ISSUE THREAD

**Issue by gimick** [learningequality/ka-lite#491]
@gimick says:  Since this ticket was raised, the login CPU performance issues have been largely eliminated - as a result this ticket is now only discussing an alternative to student passwords

Currently, login performance is slow on Raspberry Pi.
This is due to security concerns if ka-lite passwords are discovered and that student has used the same password for another (more sensitive) site.

This CPU overhead is likely to be a significant bottleneck when using Raspberry Pi in larger classes.

Can I float the idea of using pictograms to login instead of textual passwords?

Some advantages:
* There is no possibility of a shared password with another site.
* CPU overhead can be reduced because high-security hashing isn't needed.
* Pictograms could be adapted tor a particular region, culture, agegroup, or whatever
* The pictograms themselves could have an underlying arbitary text value, so beneath the surface, they act as textual passwords.
* Usernames could potentially be concealed beneath the surface.
* Pictograms would need to be carefully chosen so that the sequence would be memorable.

**Comment by rtibbles** [comment]
Superseded by #2035
