### ISSUE TITLE
Weird artifact when no coach report data is available

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#4913]
## Summary

Multiselect for topics seems not to have failed to collapse completely when there are no topics.

## Branch or installer method

 - Branch: 0.16.x

## How to reproduce

- With no recent learner data, login as teacher or admin and go to coach reports.

## Screenshots

![image](https://cloud.githubusercontent.com/assets/1680573/13298201/ad0b6be8-daea-11e5-82ab-cdb6c9894ae5.png)

@sethachoi could you see if this is something you could fix easily?

**Comment by rtibbles** [comment]
Woops, nevermind, this was a result of some bad code that I was in the middle of implementing!

**Comment by sethachoi** [comment]
cool cool
