### ISSUE TITLE
Progress report message for Learner with 0 points not displayed in Firefox/Windows

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4918]
## Summary
1. After issue #4662 was fixed, user message appears correctly on both FF & Chromium on Ubuntu, and Chrome on Windows, but is missing on FF on Windows. 
2. Heading "Progress report" seems to load at first, but then disappears as the message for the user is displayed. This might be an a11y issue, so even if there's nothing to report, I believe page H1 should appear above the user message.
## Branch or installer method

0.16 Alpha4 deb on Ubuntu & build 150 on W7.
## How to reproduce
1. Add learner user
2. Login as new learner and go straight to `My progress`
## Screenshots

![workspace 1_002](https://cloud.githubusercontent.com/assets/1457929/13339545/dec13434-dc29-11e5-9737-b7a7928cf3f0.png)

![ie11 - win7 0 16 build 150 running - oracle vm virtualbox_239](https://cloud.githubusercontent.com/assets/1457929/13339694/e431a6fa-dc2a-11e5-8ddd-6a0faff3af60.png)

**Comment by radinamatic** [comment]
Message displays properly on both Chrome & Firefox on OSX Yosemite.

**Comment by MCGallaspy** [comment]
What version of FF did this fail on? Is there a console error?

**Comment by radinamatic** [comment]
43 and still the same after upgrading to 44 today, @MCGallaspy. No console errors a part from the usual woff2 fonts.

**Comment by radinamatic** [comment]
Non extant on 0.17b4, closing!
