### ISSUE TITLE
Admin message displayed to Learner

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4920]
## Summary

The "welcome" message for Admins (`Please login with the admin account you created, then create your facility and register this device to complete the setup.`), that appears after the superuser creation modal remains active even when Learner user logs in. It disappears only after the device registration.
## Branch or installer method

0.16 Alpha4 deb on Ubuntu & build 150 on W7.
## How to reproduce
1. Login as Admin.
2. Do not register the device.
3. Create a Learner user.
4. Login as Learner.
## Screenshots

![welcome ka lite - mozilla firefox_001](https://cloud.githubusercontent.com/assets/1457929/13352404/5c6d6f02-dc8d-11e5-8feb-4ad977c5a858.png)

**Comment by MCGallaspy** [comment]
I think that's the intent!

**Comment by radinamatic** [comment]
The intent I would understand is for it to be displayed to non logged-in users and logged in admins. What can a Learner do with this message? She/he is not able to act on it, right? @MCGallaspy

**Comment by MCGallaspy** [comment]
> The intent I would understand is for it to be displayed to non logged-in users and logged in admins.

Yes, that's reasonable.

**Comment by benjaoming** [comment]
I don't think this is a problem. It's about device registration and it will only appear if the device is online.

>  Please login with the admin account you created, then **create your facility and register this device to complete the setup.**

**Comment by radinamatic** [comment]
What I see as a problem here @benjaoming is that, even if it appears only when device is online, Learner user sees a potentially confusing message she or he can do nothing about, and think they might have done something wrong themselves.

IMHO it should only be view-able by admins who can actually register the device... Similar concerns voiced back in #4023.

**Comment by radinamatic** [comment]
To illustrate, this is what a Learner user sees **as the first message above everything else**, once they login onto non-registered device if it happens to be online:

![selection_460](https://cloud.githubusercontent.com/assets/1457929/16024562/e50a822a-31c2-11e6-8b66-23f56e8a19b6.png)

**Comment by benjaoming** [comment]
> Learner user sees a potentially confusing message she or he can do nothing about, and think they might have done something wrong themselves.

It's fine they get confused if the admin / person deploying hasn't completed the installation, that's just collateral. It's good that we display this message as much as possible. People also get confused when road workers don't do their job :)

![blah](https://s-media-cache-ak0.pinimg.com/236x/98/02/e2/9802e27bb409adc5a51f4a127a6dbcce.jpg)

**Comment by radinamatic** [comment]
There's no reason to follow bad examples just because they exist, nor should we burden learners with "confusion", even if their own admins do not (for whatever reason) finish the device registration as we want them to. That shouldn't be acceptable "collateral" IMHO.

Isn't this the similar argument we discussed in #5123 under the suggestion of @j-schwartz?

**Comment by j-schwartz** [comment]
I agree with @radinamatic of course, but with my use-case we almost never have a learner online regardless.

I think we can all agree it's not an ideal message, the question is, is the potential additive data you get from maybe one or two more devices getting registered, worth the confusion it likely causes to the 10x as many learners who get discouraged by the notice and can't act on it.  

I say that as a very legitimate question.  The data is incredibly valuable, so I could see it being worth it to continue to attempt to force registration places.  If you agree that you've found the data is valuable, and that getting a few more devices registered would be marginally very valuable, I could understand the business case for keeping it.

**Comment by benjaoming** [comment]
Registering devices is valuable, and the message will only appear on an unregistered device in an online environment, so I really don't see the issue.

For Learning Equality's ability to exist and prove its impact, it's quite important that people register their use, and so far this is our best option.

After all, there's an option of a "One-Click" registration :)

Also, if someone has made an unregistered deployment where there's no one around with the ability to actually login as a manager and register the device with a one-click registration, even though it's online, then I would say that there are more fundamental issues in the deployment.

@jamalex maybe you can join this conversation.

If we can find a compromise about a better instructional message, I'm up for it.

**Comment by mrpau-eugene** [comment]
Hi guys! May I have an explanation on why this issue still exists and what needs to be changed/fixed? Maybe I can help. Thanks.

**Comment by radinamatic** [comment]
@mrpau-eugene I was for removing the message in Learner view, but was overruled... 😛

**Comment by benjaoming** [comment]
Unless I misunderstand the scenario, here's my conclusion: I think we should close it. We are essentially just catering for a scenario of *online* devices that aren't registered.

I don't see this acknowledged in any responses.

**Comment by benjaoming** [comment]
Btw thanks for triaging @mrpau-eugene !
