### ISSUE TITLE
'Search completed message' when Search is complete

### ISSUE THREAD

**Issue by manipalsingh013** [learningequality/ka-lite#4927]
## Summary
Search result should display some message when nothing was found for that search so as to make user clear that search is complete. Some message like "Search completed, no content was found for your search. Try something else."

Branch: **0.15.x**
**Ubuntu 14.04**

## How to reproduce
1. Login as some user
2. Search for something, maybe some random string for which nothing exists in content.

**Comment by rtibbles** [comment]
Fixed in #4928
