### ISSUE TITLE
Inline narratives displayed on wrong page.

### ISSUE THREAD

**Issue by manipalsingh013** [learningequality/ka-lite#4931]
## Summary
Messages of inline narratives appearing on wrong page. Some of the inline messages say "Click on this link" although there isn't any such link.
 
Branch: 0.16.x
Ubuntu 14.04
Firefox

## How to reproduce
1. Login as admin
2. Go to manage tab and click on some existing facility(like Default facility)
3. Now click on Show me how! button.
4. Click next until you see some narrative that isn't actually for this page.(step 4,5,6 of narrative)

**Comment by MCGallaspy** [comment]
Thanks for the report @manipalsingh013, I'll look in to this.

**Comment by MCGallaspy** [comment]
Fixed in #5001.
