### ISSUE TITLE
Images not loading in exercise

### ISSUE THREAD

**Issue by manipalsingh013** [learningequality/ka-lite#4932]
## Summary
Images in exercise are not loading due to which learner can't solve them.
Branch: 0.16.x
Ubuntu 14.04
Firefox

## How to reproduce
1. Login as some user
2. Go to learn
3. Start some exercise for which images should be there
4. Images not loading.

**Comment by radinamatic** [comment]
@manipalsingh013 did you install content pack? 
Can you give more details which exercise is not loading (screenshot, traceback)?

**Comment by manipalsingh013** [comment]
Yes, I have installed content pack and every exercise I tried images ain't loading
![no image1](https://cloud.githubusercontent.com/assets/13970876/13376422/f74b242e-dde1-11e5-88f6-5a725571369b.png)

**Comment by radinamatic** [comment]
Unable to replicate on my end, I'm seeing all the funny caterpillars, seals, turtles at all... :smirk: 

Getting just some React error in the console but nothing in the server.log:

![learn how many objects 1 ka lite - mozilla firefox_241](https://cloud.githubusercontent.com/assets/1457929/13376614/ca1a2a0c-ddc0-11e5-8de6-8ef04105b1ad.png)

@manipalsingh013 try fetching the latest upstream, getting the latest [contentpack](http://pantry.learningequality.org/downloads/ka-lite/0.16/content/contentpacks/en.zip), clearing the browser cache...

**Comment by manipalsingh013** [comment]
I already did it twice but I'm still not getting images.

**Comment by manipalsingh013** [comment]
@radinamatic I removed kalite from my PC and reinstalled it from github but still not getting images. Anything else that I should do?

This warning I'm getting when executing **bin/kalite manage retrievecontentpack download en**
**[WARNING] [2016-02-29 09:11:15,963] kalite: No en_icu.js file found in locale_path /home/manipalsingh/ka-lite/locale/**

These two warning I'm getting on terminal everytime I refresh the page.
**[WARNING] [2016-02-29 09:01:54,220] django.request: Not Found: /content/assessment/khan/e38/e386922f80fdb67bfa1959d1e0289dafe6f4281a.png
[WARNING] [2016-02-29 09:01:54,269] django.request: Not Found: /content/assessment/khan/fc8/fc80c797b2688c0f0e60bea5a136a688210e6528.png**

**Comment by MCGallaspy** [comment]
Also not able to reproduce. Very odd, I checked the latest en content pack (from today, 2/29, downloaded around 4pm PST) for the specific files you listed. I confirm they are indeed there. If you're running from source, then you should be able to find those files in the `ka-lite/content/assessment/khan/fc8/` directory (replacing `fc8` with other values as appropriate, just like in the url). Can you confirm that the files are missing?

@aronasorman when using the `download` option of `retrievecontentpack`, is the zipfile cached anywhere where @manipalsingh013 could inspect it? Perhaps the file had been corrupted?

@manipalsingh013 alternatively, try downloading the contentpack separately ([link](http://pantry.learningequality.org/downloads/ka-lite/0.16/content/contentpacks/)) and using the command `kalite manage retrievecontentpack local en <path to zipfile>` flavor.

**Comment by aronasorman** [comment]
@MCGallaspy it could possibly be cached. @manipalsingh013 please try the `local` version of the command, as that can shed light on what might be wrong.

**Comment by cpauya** [comment]
My 2-cents: I've [experienced the missing images](https://github.com/learningequality/installers/pull/359#issuecomment-188734184) on the exercise page while building the OS X installer.  The fix as per https://github.com/learningequality/installers/pull/359/ is to run the following commands in order:

* `kalite manage syncdb --noinput`
* `kalite manage setup --noinput`
* `kalite manage retrievecontentpack local en path-to-en.zip`

Though I'm on OS X - I hope it can help @manipalsingh013 in some ways.

**Comment by manipalsingh013** [comment]
I tried the local version of command but unfortunately still no images  :disappointed: 

When running "kalite manage retrievecontentpack local en path-to-en.zip" I'm getting this on my terminal.

**[WARNING] [2016-03-01 23:43:50,923] kalite: Channel khan does not exist.**
[INFO] [2016-03-01 23:43:51,259] kalite: Installing a local content pack.
[INFO] [2016-03-01 23:43:51,621] kalite: Moving content files to the right place.
**[WARNING] [2016-03-01 23:43:51,784] kalite: No en_icu.js file found in locale_path /home/manipalsingh/mani/ka-lite/locale/**
[INFO] [2016-03-01 23:43:51,784] kalite: Writing i18nized js file to /home/manipalsingh/mani/ka-lite/content/locale/js/i18n/en.js
[INFO] [2016-03-01 23:44:03,969] kalite: Looking for available content items.
[INFO] [2016-03-01 23:44:05,369] kalite: Annotating content for language: en, channel: khan
[INFO] [2016-03-01 23:44:09,457] kalite: Annotation complete for language: en, channel: khan
[INFO] [2016-03-01 23:44:09,457] kalite: Finished processing content pack.

**Comment by MCGallaspy** [comment]
@manipalsingh013 those warnings I think are irrelevant in this case. After downloading the zipfile and unpacking it locally, can you confirm that:
1. The images appear in the archive itself, and are not corrupt.
2. That after you've unpacked the archive using `retrievecontentpack local` the images appear uncorrupted in the directory I indicated above?

**Comment by manipalsingh013** [comment]
@MCGallaspy I tried it and my **ka-lite/content** doesn't even have any directory named **assessment**

**Comment by manipalsingh013** [comment]
ka-lite/content contains some .png, .mp4 and a directory named locale and a 04TLVP4.pdf and README.txt file

**Comment by aronasorman** [comment]
Your branch might be outdated, as a lot of fixes for `retrievecontentpack` came last week.

**Comment by manipalsingh013** [comment]
Well I pulled it yesterday morning I believe, doing it again now.

**Comment by manipalsingh013** [comment]
I pulled the latest 0.16.x code and repeated the steps told by @cpauya but still nothing, no directory named assessment.

**Comment by manipalsingh013** [comment]
I created the **assessment** directory and pasted **khan** directory in it(extracted en.zip) and everything is working fine now.

**Comment by MCGallaspy** [comment]
That's odd, is it possible you were pulling 0.16.x from your own fork, instead of from learningequality's repo?

**Comment by manipalsingh013** [comment]
I checked it already I'm pulling from learningequality's repo.

**Comment by MCGallaspy** [comment]
It seems there must be some error with `retrievecontentpack`, then.

**Comment by manipalsingh013** [comment]
Although not the right place to ask but can someone add me to slack room.(I believe that's the chat room we are using)@aronasorman @MCGallaspy

**Comment by aronasorman** [comment]
Adding you now.

**Comment by aronasorman** [comment]
I sent the invite to the email you use for git commits.

**Comment by manipalsingh013** [comment]
Joined, Thanks @aronasorman

**Comment by benjaoming** [comment]
@manipalsingh013 - I'm hoping this works for you now :)

**Comment by saiap** [comment]
Just install personal web server on your PC and you should be good to go.

**Comment by saiap** [comment]
I think the root cause was, KALite content gets installed/downloaded in the 'user' folder of the installing user, bad bad idea. If that user has is no admin access then installation may go fine by prompting for the admin credential, but next time KAlit started by that user will have limited access !!. I tried to execute the litle KAlite icon with admin access and every time it showed the images and each time I opened using my user account, the problem was reproduced. So the work around until KAlite changes this idea will be to run the KALite as admin by right clicking on it, select run as admin and provide admin password!

**Comment by benjaoming** [comment]
@saiap noted, thanks -- not all Windows systems are experiencing this problem, but it's a known issue that you can't install KA Lite as User A and use it for User B. If it's of importance for someone to want to work with, then the relevant repository is https://github.com/learningequality/installers/

**Comment by saiap** [comment]
Well,  I used to work for Microsoft as a Sr.Engineer, in my opinion all Microsoft OS since 2000 will have this issue with this scenario. But if there was little extra care taken by the developer, this could have been fixed. Direct the contents to a common place and give read access to all users including IIS_USR if IIS is running. Plain and simple :)

**Comment by saiap** [comment]
This is a great application and the Developer has done a great job!!. . So I want to add my two cents. To fix this minor issue, this is what I did. I have an admin user and a regular user. I installed KALite using admin user so it created a content file in the C:\User\Admin\.Klite folder and the images were stored in to the C:\Users\Admin\.kalite\content\assessment\khan\245 folder. What did was, moved the folder C:\Users\Admin\.kalite\content\assessment\khan to C:\Users\RegularUser\.kalite\content\assessment\ and that fixed the issue. Hope that helps.

**Comment by benjaoming** [comment]
> in my opinion all Microsoft OS since 2000 will have this issue with this scenario

Somehow miraculously they don't :) But the issue seems to be obvious so the fix could easily be implemented by someone willing and able to do that. As I said, the repo with the installer code is this one: https://github.com/learningequality/installers/

There's a readme here:

https://github.com/learningequality/installers/tree/master/windows
