### ISSUE TITLE
Search paginator not working properly

### ISSUE THREAD

**Issue by manipalsingh013** [learningequality/ka-lite#4934]
## Summary
Although the next arrow key of paginator seems disabled after clicking for a few times but user can still click on it and go to empty page. 

**Branch: 0.15.x
Ubuntu 14.04
Firefox**

## How to reproduce
1. Login as some user
2. Search for something for which some results appear(eg 'count')
3. Click on next button of paginator(arrow button)
4. Keep clicking next until you find that mouse cursor changed to unclickable when hovering on next button.
5. Click again on next button.
6. It takes you to an empty page.

## Screenshots
![paginator](https://cloud.githubusercontent.com/assets/13970876/13385792/0c5b9ad0-decb-11e5-9678-7b4c2c1f5e0d.png)

**Comment by MCGallaspy** [comment]
I'm not sure I consider this a critical bug for 0.16.0, but we can take a look at fixing it on `develop` for future releases.

**Comment by benjaoming** [comment]
Fixed in #5155
