### ISSUE TITLE
Videos downloaded in a non-english language pack aren't showing up in the topic tree.

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#4937]
## Summary

When I download a video in a non-english lang pack, it's not showing up in the topic tree.

## Branch or installer method

*Please specify if you are using the current `develop` branch or which installation source you were using when the issue occurred.*

0.16.x

## How to reproduce

1. Download a language pack, activate said language
2. Download a video through the video download interface
3. Scroll through topic tree, trying to find the said video in vain

**Comment by radinamatic** [comment]
And the video topic tree is still not showing localized (this is after installing the latest `es-ES-zip`:


![actualizar_videos](https://cloud.githubusercontent.com/assets/1457929/13405401/76fe968c-df1e-11e5-934a-32837e21d759.png)

**Comment by rtibbles** [comment]
Yeah, I think I see what is wrong here, trying a fix now!

**Comment by rtibbles** [comment]
This is fixed by #4938.
