### ISSUE TITLE
Download video cancel button not appearing

### ISSUE THREAD

**Issue by fairdklab** [learningequality/ka-lite#4949]
## Summary

Upgrading from 0.16a4 to 0.16b1........

1. The existing content db is not being overwritten, that's great because it contained all my current video downloads!
1. Existing downloads are being annotated! So even if my content db was overwritten, I would retain my available videos and the are even showing up on first run! It took 5 minutes, but there was logging feedback during the process!
1. I can download videos! I'm even resuming downloads that I started in 0.16alpha4.
1. The topic tree is nice!

## Branch or installer method

 - Installer: Debian
 - Version: 0.16b1

## Screenshots

![screenshot from 2016-03-02 18 49 52](https://cloud.githubusercontent.com/assets/12937701/13469572/4969be14-e0a8-11e5-967b-8644dae67efd.png)

![screenshot from 2016-03-02 18 53 42](https://cloud.githubusercontent.com/assets/12937701/13469706/d077f25e-e0a8-11e5-80b5-1168853f85f4.png)

![ok](https://media0.giphy.com/media/WyeodYfrqvHCo/200_s.gif)

...except the "Cancel downloads" button still ain't showing

**Comment by aronasorman** [comment]
> except the "Cancel downloads" button still ain't showing

Such great buildup!

**Comment by radinamatic** [comment]
Drat, @aronasorman, you stole my line!
I was about to ask: where is the issue exactly??? :grinning:

**Comment by benjaoming** [comment]
Why did you change the title, the OP was obviously very excited... whoever that person might be :D

**Comment by radinamatic** [comment]
I'm seeing this button just fine (and it works :wink:, sans Français) on fresh Beta1/Ubuntu install!

**Comment by benjaoming** [comment]
It happened by means of restarting the server, but I can't reproduce it, tried:

1. Restarting the server
1. Reloading the page
1. Logging out and back in
