### ISSUE TITLE
Download progress count wrong after starting downloads

### ISSUE THREAD

**Issue by fairdklab** [learningequality/ka-lite#4950]
## Summary

Download count wrong after starting downloads

Related to #4929 
## Branch or installer method
- Installer: Debian
- Version: 0.16b1
## How to reproduce
1. Select videos for download.
2. Start the download
3. Observe the count in the progress
## Screenshots

![screenshot from 2016-03-02 18 59 54](https://cloud.githubusercontent.com/assets/12937701/13469864/6649161e-e0a9-11e5-92f9-5e017dbbfa4c.png)

![screenshot from 2016-03-02 19 00 08](https://cloud.githubusercontent.com/assets/12937701/13469867/68d1c840-e0a9-11e5-8663-fa59b5b2e7aa.png)

**Comment by benjaoming** [comment]
Confirming this issue for 0.16.9

**Comment by benjaoming** [comment]
These issues will have to be unresolved for the purpose of just finalizing the new scheduler #5094
