### ISSUE TITLE
Scan content folder for videos

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4952]
## Summary

Technically works, but after I copied 6 Spanish videos I had downloaded a while ago via torrent, it only recognized one. Did the video ids, or filenames change with latest refactor? @aronasorman @rtibbles 

## Branch or installer method

0.16b1 .deb installer on Ubuntu 15.10.

## How to reproduce

1. Copy videos to `.kalite/content` folder
1. Press the  `Scan content folder for videos` button

## Screenshots
![scan](https://cloud.githubusercontent.com/assets/1457929/13477623/9e31f5b8-e0cd-11e5-97ed-e086ffe2c766.png)

**Comment by radinamatic** [comment]
This seems to be working fine on OSX Yosemite, build 76. 
15 videos copied in the content folder, all of them apparently recognized and green in the topic tree. :+1:

**Comment by rtibbles** [comment]
Closing then - reopen if it recurs.

**Comment by radinamatic** [comment]
Deal!
