### ISSUE TITLE
Language pack donwload progress bar...

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4955]
## Summary

...is still missing. I can't find any issue regarding this, and it's a definite release blocker!

Delete this if I'm blind... :stuck_out_tongue_closed_eyes:

**Comment by radinamatic** [comment]
I am blind, or too tired, closed the  #4914 myself a few hours ago... :facepunch: 

Anyway, since that one got too general anyway I'll leave it closed and let's keep this one as valid, if everybody agrees...  @aronasorman?

**Comment by aronasorman** [comment]
Sounds good! This is now the official 'the language pack download progress bar is missing' page.

**Comment by aronasorman** [comment]
Hi, can someone else take this over? I think I don't have enough time before our March 18 deadline to finish this.

**Comment by jamalex** [comment]
Looks like the fix for this has been merged.
