### ISSUE TITLE
Video download: Topic shown as completed but subtopics aren't

### ISSUE THREAD

**Issue by fairdklab** [learningequality/ka-lite#4959]
## Summary

I've run videoscan a couple of times and I don't believe it annotates the tree correctly, although it completes without errors.

## Branch or installer method

 - Installer: Debian
 - Version: 0.16b1

## How to reproduce

1. Download lots of videos
1. Copy some old stuff into the content folder
1. Run `videoscan`

## Screenshots

Partner contents shown as completed but sub topics aren't:

![screenshot from 2016-03-03 15 07 34](https://cloud.githubusercontent.com/assets/12937701/13496770/613dedd0-e152-11e5-932f-5b2fae1b7beb.png)

**Comment by radinamatic** [comment]
Reported the same in #4952, confirmed on Ubuntu & Windows XP.

**Comment by benjaoming** [comment]
@radinamatic this is a different issue. It's about showing an upper topic as completed while the nested topics aren't.

**Comment by radinamatic** [comment]
Shoot, totally right @benjaoming: I latched on the mention of videoscan and you testing on some old videos!

**Comment by rtibbles** [comment]
Could you inspect the database for these nodes, and see if the parent node has total_files == complete_files?

I am trying to differentiate between the annotation not working properly, and the display logic of the annotation not working properly.

**Comment by rtibbles** [comment]
Happily, I think this is probably a rendering issue in the Javascript, and not a problem with the database annotation itself - I will attempt to replicate locally.

**Comment by rtibbles** [comment]
Not able to replicate locally :/

**Comment by benjaoming** [comment]
I'll look at this next time in the lab, it takes a lot of video data to reproduce if it's still relevant.

**Comment by benjaoming** [comment]
Can't replicate this at present, better to just wait and reopen if it really occurs, otherwise we can assume that @rtibbles 's previous fix works!
