### ISSUE TITLE
windows.sessionModel is undefined

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#4971]
## Summary

After pulling the latest `0.16.x`, this is what I get:

![screen shot 2016-03-08 at 08 32 41](https://cloud.githubusercontent.com/assets/191955/13608198/8b6f6610-e508-11e5-8e0f-a13847e905ac.png)

Loading failed due to this error:

![screen shot 2016-03-08 at 08 33 05](https://cloud.githubusercontent.com/assets/191955/13608210/973eb176-e508-11e5-85fb-747dee23f1fa.png)

But none of the JS files before that failed to load.

Exact line where the error occurred:
![screen shot 2016-03-08 at 08 33 10](https://cloud.githubusercontent.com/assets/191955/13608218/a5c95868-e508-11e5-8638-cb0a355b83c3.png)

## How to reproduce

1. Pull latest 0.16.x
1. `node build.js`
1. `bin/kalite collectstatic --noinput`
1. `bin/kalite start --foreground`

Voila

**Comment by rtibbles** [comment]
Looks like the build failed or was aborted.

For some reason, build.js seems to be aborting without finishing its output.

**Comment by rtibbles** [comment]
Needed an npm install.

**Comment by aronasorman** [comment]
Needed an `npm install` to pull the latest `videojs`.
