### ISSUE TITLE
IP addresses for learners

### ISSUE THREAD

**Issue by bonijiang** [learningequality/ka-lite#4973]
## Summary

The Ka-lite system (KA Lite version 0.15.1) is installed and server is running. According to the manual," Once the server has been started, you will be given a few IP addresses. You can use these addresses to access KA Lite by copying and pasting them into a web browser of your choice." I don't see any IP addresses from anywhere. How do I find these IP addresses for learners?
Thank you!

## Branch or installer method

*Please specify if you are using the current `develop` branch or which installation source you were using when the issue occurred.*

 - Installer: Windows/OSX/Debian (?)
 - Version: 0.15.1 (?)

or:

 - Branch: develop (?)

## Traceback or relevant snippet from server.log

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

1. Steps
1. To
1. Reproduce

## Screenshots

*If applicable*

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

*If applicaple*

**Comment by MCGallaspy** [comment]
I think this issue could be addressed with clearer documentation.

**Comment by benjaoming** [comment]
Documentation seems to have changed, but it's still more of a problem with one of the installers that have been used, i.e. that they don't display the IP address of the server.

Latest stable docs:

http://ka-lite.readthedocs.io/en/stable/usermanual/userman_admin.html#accessing-ka-lite
