### ISSUE TITLE
KA-Lite customization

### ISSUE THREAD

**Issue by SkaeX** [learningequality/ka-lite#4975]
Hello Learning Equality,
I am looking towards making some changes to my ka-lite. Please I would like to know the possibility of me adding local content (pdf files) to my KA-lite. If this is possible, please tell me the steps involved

**Comment by rtibbles** [comment]
Hi @SkaeX - this is something that KA Lite is already somewhat capable of doing.

In the current master (0.15.x) branch there is a command called 'contentload' that will scan a folder structure and create a topic tree. Alternatively, you can edit the json files that define the content.

PDFJS is already installed, and will render files that have the kind "Document".

Note: This feature is unsupported, so we have limited bandwidth to provide further information, but it is possible.

If your timescale is a bit longer, then we are currently developing Kolibri - https://github.com/learningequality/kolibri - a platform designed to allow just this sort of custom content curation. It is scheduled for public release in September 2016.

**Comment by SkaeX** [comment]
Hi @rtibbles - Thank you for the response.
Please can you help me with a workflow on how I can achieve adding the contents (mp3, mp4, and pdf) to the topic tree.
These are the steps I tried:
- I had a pdf file and a mp4 file in a folder called `local`
- Using the `kalite manage videoscan --import=pathtofolder/local` command and it failed.

Please elaborate a little more on your response. Thank you.

**Comment by rtibbles** [comment]
> Note: This feature is unsupported, so we have limited bandwidth to provide further information, but it is possible.

You are using videoscan according to your paste here, not contentload.
