### ISSUE TITLE
Improving UX of KA Lite --> User Manual 0.16

### ISSUE THREAD

**Issue by jtamiace** [learningequality/ka-lite#4977]
## Summary

There is no button to direct back to the ka lite application from the user manual. A user could just use the browser's back button, but the change in look and feel is abrupt.

![user manual](https://cloud.githubusercontent.com/assets/6668144/13646016/6c58615c-e5e2-11e5-884b-1b351dbb5e9d.JPG)

Possible solution is to add an html tag in this link that allows the user manual to open in a new tab 
(```<a target="_blank"></a>```)
Further improvement to the UX of this solution is to add an alert modal to let the user know they will be directed away from the ka lite app, so that they can confirm or cancel that request.

## Branch or installer method

 - Installer: Windows
 - Version: 0.16

## How to reproduce

1. Be logged in as admin
2. Click User Manual tab

**Comment by radinamatic** [comment]
Fixed in #5010, can be closed!
