### ISSUE TITLE
Content not translated on student Progress Report

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#4980]
## Summary

Content titles and descriptions are not translated when viewing them on the progress report.

## Branch or installer method

 - Installer: Debian
 - Version: 0.16.x beta1

## How to reproduce

- Login as learner with some learning history.
- Go to progress report.
- Switch to e.g. Spanish.

## Screenshots

![image](https://cloud.githubusercontent.com/assets/1680573/13654158/470728c4-e60b-11e5-82e6-01293d374252.png)

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

Very confusing for non-English speaking learners.

**Comment by radinamatic** [comment]
Thanks, noted that on Windows too in #4951, never got around to file the issue.

**Comment by 66eli77** [comment]
confirm the issue with French language pack, I'm working on this issue

**Comment by rtibbles** [comment]
Fixed in #5018
