### ISSUE TITLE
Translated Khan Exercise templates not being used

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#4981]
## Summary

When using a Khan Exercise template, only the English language ones are loaded.

## Branch or installer method

 - Installer: Debian
 - Version: 0.16.x beta1

## Traceback or relevant snippet from server.log

![image](https://cloud.githubusercontent.com/assets/1680573/13654251/dede51f4-e60b-11e5-96f7-55673d12ed56.png)

## How to reproduce

- Login as learner.
- Navigate to /learn/khan/math/arithmetic/multiplication-division/multiplication_fun/number_line/
- Observe.

## Screenshots

![image](https://cloud.githubusercontent.com/assets/1680573/13654265/0045f2b6-e60c-11e5-9c63-8f0aff3d9ee8.png)

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

Bad for non-English speaking learners.

**Comment by aronasorman** [comment]
@rtibbles would you be able to look into this issue?

**Comment by 66eli77** [comment]
I can work on this issue if you haven't yet. just fixed a related issue about translation.

**Comment by aronasorman** [comment]
Feel free to assign yourself @66eli77!

**Comment by rtibbles** [comment]
This should be fixed in #5049 - @66eli77 can you test? You will need to run in production mode.

**Comment by aronasorman** [comment]
@66eli77 you'll need to use this content pack too: https://files.slack.com/files-pri/T0KT5DC58-F0VHJ1Y9H/download/es-es.zip

**Comment by 66eli77** [comment]
ok

**Comment by aronasorman** [comment]
Fixed in latest 0.16.x.
