### ISSUE TITLE
Obsolete error message on video download page

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#4982]
## Summary

We should no longer be warning people to limit downloads on Raspberry Pi.

## Branch or installer method

 - Installer: Debian
 - Version: 0.16.x beta1

## How to reproduce

- Login as admin.
- Go to video download page
- See message.

## Screenshots

![image](https://cloud.githubusercontent.com/assets/1680573/13654516/b31c29b8-e60d-11e5-9cd9-bface89e5424.png)

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

People might believe our warning.

**Comment by radinamatic** [comment]
How many videos can one actually download concurrently on RPi?

**Comment by radinamatic** [comment]
Not seeing this warning on Ubuntu with Beta2...

**Comment by benjaoming** [comment]
Done and released!
