### ISSUE TITLE
User Manual poor navigability

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#4984]
## Summary

Once I click in the user manual tag, I have to solely rely on the browser back button to navigate back to kalite.

The ideal situation is that I can go back using some navigation UI within the page. One possible solution could be that we keep the top nav bar display when show the user manual

## Branch or installer method

 - Branch: 0.16.x

**Comment by MCGallaspy** [comment]
Duplicate of https://github.com/learningequality/ka-lite/issues/4977
