### ISSUE TITLE
Disable previous / next video links, when those videos are not downloaded.

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#499]
Background:
We allow admins to download an arbitrary set of videos.  We also choose to hide / disable links for videos that don't exist.

On the video page, there are links to the "previous" and/or "next" videos in a sequence.

Expectation:
These video links would be disabled if the video files that they point to don't exist.

Current behavior:
They are live links.  When you click them, they take you to a page with no available video.

Notes:
One challenge to implementing this is to invalidate the "previous" / "next" pages inside utils/caching.py: `invalidate_all_pages_related_to_video`

**Comment by rtibbles** [comment]
No longer relevant.
