### ISSUE TITLE
Annotating content takes 40+ minutes when full set of videos exists locally, on non-SSD

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#4991]
## Summary

Annotating content happens whenever we upgrade or run `setup`. If all ~8K videos are in the content folder, it has a lot of annotation to do. If it's on a non-SSD disk, this can take a long time. In particular, it takes over 40 minutes on a high-powered Rackspace server (8 vCPUs, 15GB RAM, Disk IO "Good").

I'm opening this here at @aronasorman's request, not as a release blocker, but as a reminder for us to figure out faster ways of doing this -- with the main bottleneck likely being the way we write to the SQLite DB. Solving this in the context of KA Lite will hopefully inform how best to handle this type of operation (bulk writes to DB) in Kolibri as well, and hence be worthwhile longer-term.

## Branch or installer method

 - Branch: 0.16.x

## Traceback or relevant snippet from server.log

```
[INFO] [2016-03-12 01:36:54,677] kalite: Downloading content pack from http://pantry.learningequality.org/downloads/ka-lite/0.16/content/contentpacks/en.zip
[WARNING] [2016-03-12 01:37:39,284] kalite: No en_icu.js file found in locale_path /videos/ka-lite/locale/
[INFO] [2016-03-12 01:37:39,284] kalite: Writing i18nized js file to /videos/ka-lite/content/locale/js/i18n/en.js
[INFO] [2016-03-12 01:37:46,515] kalite: Annotating content for language: en, channel: khan
[INFO] [2016-03-12 02:20:20,720] kalite: Annotation complete for language: en, channel: khan
[INFO] [2016-03-12 02:20:20,851] root: Copying static media...
Annotating availability of all content, checking for content in this directory: (/videos/ka-lite/content)
[INFO] [2016-03-12 02:20:22,143] kalite: Annotating content for language: en, channel: khan
```

(note also that in the log above it seems to start annotation _again_ after it finishes -- once triggered by having downloaded the content pack, and once as a separate stage in the `setup` command, I'm guessing)

## How to reproduce

1. Put 8K videos in content folder
1. Run `bin/kalite manage setup`

**Comment by aronasorman** [comment]
Looked into some of SQLite pragmas. One low hanging fruit is disabling or
caching the write ahead log in memory. I'll try to make a test case, then
see what the effects of different pragmas are.

**Comment by rtibbles** [comment]
I think the main take away for Kolibri is to not encode things like "subtitle url" and "stream_url" in the topic data. This should be something that is calculated on the client side, based on the file name. This would avoid a lot of the stamping logic that has to be done at an individual level.

If we can do this, we can just bulk update content as 'available' over many rows in a single SQL query.

**Comment by jamalex** [comment]
> If we can do this, we can just bulk update content as 'available' over many rows in a single SQL query.

Yeah, that would presumably be fast (atomic) but also not too memory-intensive (doesn't have to load and manipulate the full models in memory).

However, it may not be a particularly simple update. In Kolibri, availability will be based on File > Version > ContentNode related models. We can probably do some nice SQL queries if needed, though, to do efficient updates there.

**Comment by fheslouin** [comment]
Hello, 

I there anyway to fix this issue ? I'm using 0.16.5 on raspberry like and it's endless. 
No videos appear in Kalite although there is more than 20G of them...

Thanks

**Comment by radinamatic** [comment]
Hi @fheslouin! 

This issue has been fixed in [#5201](https://github.com/learningequality/ka-lite/pull/5201) (more details about performance in #5200), please download the latest 0.16.8 release and let us know if it performs better now: [Raspberry Pi installer](https://learningequality.org/r/deb-pi-installer-0-16)

Cheers!

**Comment by radinamatic** [comment]
Closing as fixed in #5201.

**Comment by fheslouin** [comment]
Thank you ! 
The release 0.16.8 helps a lot : 10min for 9G

**Comment by radinamatic** [comment]
Awesome, glad it helped! :+1:
