### ISSUE TITLE
problems with Coach Reports on 15.1

### ISSUE THREAD

**Issue by jumbojim101** [learningequality/ka-lite#4995]
We are having issues trying to use the Coach Reports
We are working with KA Lite 15.1 on Windows 7. We are testing with Chrome and FireFox.
We install, register, add admin, teacher, group and a couple of students.

We do several exercises. We intentionally fail some exercises so we can see when the report tells the coach they need to help the student.

The first problem is the scroll bar to see all the exercises intermittently
disappears and we can not see all exercises. 

The second problem is we are unable the trigger a "Struggling" or Orange condition on the report even after missing exercises and the details show many incorrect answers. 

Thanks for your help

**Comment by MCGallaspy** [comment]
@jumbojim101 thanks for the report! Will look in to this.

**Comment by rtibbles** [comment]
Hi @jumbojim101 - the struggling condition currently gets set if more than 20 attempts have been made and mastery has not yet been achieved. Does this explain the lack of struggling triggering, perhaps?

We can definitely think about whether we should flag as struggling earlier if a student are getting many responses wrong.

Is it the top or the bottom horizontal scrollbar that disappears, or both?

**Comment by jumbojim101** [comment]
I think the scroll bar problem was my fault because I did not extend the time to include all the exercises .

Can you define achieving mastery ?

**Comment by rtibbles** [comment]
Mastery is achieved when the last 8 out of 10 attempts are correct.

**Comment by jumbojim101** [comment]
I am selecting an incorrect answer then a correct answer and I get a red  mark. I repeat this 22 times and I see 22 red marks. I log off as student and login as coach. I run report and do not see "struggling".
I log back in as student and only see 10 red marks. not sure what I am doing wrong

**Comment by rtibbles** [comment]
Let's keep this issue opened, as it sounds at the very least like there is something going wrong here. Will investigate!

**Comment by 0o0TheDude0o0** [comment]
I am also experiencing this issue.

**Comment by jumbojim101** [comment]
After a fresh install of 15.1 in windows vista I was able to get the red struggling indicator on the coach reports.  All is good.
I am able to sync regularly.

When I log in to learningequality.org , I am unable to get any info from a coach report. Am I supposed to be able to see student progress from  learningequality.org after the data sync ?

**Comment by rtibbles** [comment]
This should be fixed in 0.16.x by #5039
