### ISSUE TITLE
Language pack download and offline installation docs revision

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#5000]
## Summary

[Link in our docs](http://ka-lite.readthedocs.org/en/latest/faq.html#how-can-i-install-a-language-pack-without-a-reliable-internet-connection) does not seem to be valid anymore: 

http://keep.learningequality.org/media/language_packs/

@aronasorman Could you review what happened to it?

Docs need revising, as well as adding info regarding the new contenpacks.

**Comment by radinamatic** [comment]
Wow, I just made issue nº 5k... :dancers: :grinning:

**Comment by radinamatic** [comment]
Or is it that languagepack download/installation is completely substituted by contentpack download/installation for each available language and only this has to be properly documented?

**Comment by aronasorman** [comment]
For 0.16 the link will change to the one in pantry. The one in 0.15 and below is totally undiscoverable.

**Comment by aronasorman** [comment]
Can you make a PR for that? :D

**Comment by radinamatic** [comment]
Sure, but just so I understand completely: there is no such thing as a `languagepack`download anymore for 0.16, right? To get KA Lite to speak their language, user has to download just the new contentpack, and that's it?

**Comment by radinamatic** [comment]
I mean the new `contentpack`in their language on top of the base KA Lite `en.zip` with all the assessment items...

**Comment by radinamatic** [comment]
It's just a bit unclear for me if the `unpack_assessment_zip` is to be completely substituted with `retrievecontentpack` command for end users...? If it so, should we delete that part form the relevant documentation page?

http://ka-lite.readthedocs.org/en/0.16.x/usermanual/userman_admin.html#adding-assessment-items-exercises

**Comment by aronasorman** [comment]
@radinamatic for end users, yup. Purge mentions of `languagepackdownload`, we now have them use `retrievecontentpack`. And yes, they will first have to make sure `en.zip` has been installed on KA Lite (already taken care of by the installers), and then they'll have to either download the language through the language pack download interface, or run `kalite manage retrievecontentpack download <langcode>` in the terminal.

**Comment by aronasorman** [comment]
re: `unpack_assessment_zip` -- yup, that command should be turned into `kalite manage retrievecontentpack download en` or `kalite manage retrievecontentpack local en <en.zip path>`.

**Comment by radinamatic** [comment]
Perfect, onto the docs changes now, thanks! :+1:

**Comment by radinamatic** [comment]
As user pointed out in #5053, the original issue should be fixed independently of the new release.

**Comment by benjaoming** [comment]
The links in the docs are fixed, it's now a matter of restoring keep.learningequality.org for the sake of old docs... which I've pinged @jamalex about. Closing this. Thanks for the report and the fix @radinamatic :)
