### ISSUE TITLE
Previous installations with unavailable contentpacks on 0.16

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#5002]
## Summary

*Disregard and close if we are going to produce the contentpacks for all previously available languages.*

If that is not the case, we need to think about what to present to users upgrading from previous version who used languages we don't have contentpack for in 0.16. 

## Branch or installer method

0.14 installation on XP, upgraded to 0.16 (build 177). 

Having Danish as default on previous version, or switching to it after the upgrade to 0.16, results in empty sidebar.

## Screenshots

![danish](https://cloud.githubusercontent.com/assets/1457929/13831522/861f4aea-ebd4-11e5-99a0-74142a418bc9.png)

**Comment by aronasorman** [comment]
The plan is to support all preexisting language packs.

**Comment by radinamatic** [comment]
And all the new contentpacks for "preexisting language packs" will be available before the official release of 0.16? Because if they're not, the above problem will arise.

**Comment by aronasorman** [comment]
Yes.

**Comment by radinamatic** [comment]
:+1:

**Comment by aronasorman** [comment]
This is a content pack issue.
