### ISSUE TITLE
New controls for video download/managment do not scale correctly

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#5004]
## Summary

Different in Firefox & Chrome, evident in locales that have longer strings than English.

Probably simple to fix, needs some design/css love... :wink: 
@66eli77 @jtamiace 
## Branch or installer method

Screenshots below from 0.14 installation on XP, upgraded to 0.16 (build 177), but it's general design issue.
## Screenshots

Firefox, button width not enough for string length:

![video-buttons-firefox](https://cloud.githubusercontent.com/assets/1457929/13832242/924b51d2-ebda-11e5-9735-d32ad8ca6b8b.png)

Chrome, button wide enough but overlaps the container:

![video-buttons-chrome](https://cloud.githubusercontent.com/assets/1457929/13832250/ab785858-ebda-11e5-822b-aa488fccb9d8.png)

**And while you're at it, review the media queries, because the hamburger menu does not behave well below 1000px, and main menu ends up in two rows**:

![responsive1](https://cloud.githubusercontent.com/assets/1457929/13832379/07650df4-ebdc-11e5-8fee-5eec61d5220f.png)

![responsive2](https://cloud.githubusercontent.com/assets/1457929/13832381/0df70672-ebdc-11e5-8841-f2319ed5c6e6.png)

**Comment by benjaoming** [comment]
Fixed in #5448, let's keep an eye out for regressions in other aspects of button rendering.
