### ISSUE TITLE
On a device synced to multiple facilities, after adding a user, user must again select a facility.

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#501]
Title says it all.  We should carry the facility info.  Setting a "default" facility is a workaround, but ... what if you're adding users to a facility that's not your default?

![image](https://f.cloud.github.com/assets/4072455/981731/55ea149a-0784-11e3-82a0-01c0bbf57946.png)

**Comment by rtibbles** [comment]
Fixed due to way facilities are selected.
