### ISSUE TITLE
improvement on bootstrap disable and enable for "show me how!"

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#5011]
## Summary

improvement on bootstrap disable and enable. Ideally, we want to avoid reloading bootstrap everytime the "show me how!" button is clicked.
## Branch or installer method
- Version: 0.16

or:
- Branch: 0.16.x
## How to reproduce
1. login as admin and go to Manage tag
2. open your dev tool and check the Network; everytime the "show me how!" button is clicked, a new copy of bundle_bootstrap.js is loaded into the browser.

**Comment by benjaoming** [comment]
Not seeing this behaviour, when I click "show me how", only the JSON resource for the inline help is loaded.
