### ISSUE TITLE
Facilities missing after upgrade 0.15 > 0.16 on Windows 7

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#5015]
## Summary

I'm having a worrisome case of device appearing as unregistered and my 2 facilities missing after upgrading to 0.16 from 0.15. Had a `Default facility` with 2 users and the the whole bunch of them in Wilson Elementary generated with `kalite manage generaterealdata`. No trace of any of them now on 0.16... :cry:

All languagepacks and videos do seem to be there.

@MCGallaspy 
## Branch or installer method

0.15.1 installation on Windows 7 upgraded to 0.16 (build 177).
## Traceback or relevant snippet from server.log

At loss what to put here as no error whatsoever appeared during the upgrade process.
## Screenshots

**0.15 installation** 
![015-pre-upgrade](https://cloud.githubusercontent.com/assets/1457929/13863481/65d2c58e-ec9a-11e5-9cc6-9f8272b48f6c.png)

Migration was uneventful, I snapped just one shot:

![migrate](https://cloud.githubusercontent.com/assets/1457929/13863521/b8948eba-ec9a-11e5-950e-47a5c1e84c72.png)

I can upload the screenshot of 0.16 as-is, but it's just like the 0.15, asking to register the device and showing one `Default facility` with 0 users.

**Comment by radinamatic** [comment]
Confirmed on 0.14.2 installation on Windows 7, after upgrade to 0.16 (build 177).

DB pre-upgrade:

![0 16-from-0 14 2-original-db](https://cloud.githubusercontent.com/assets/1457929/13866584/2b553992-ecb7-11e5-8697-c6e899da1058.png)


DB after upgrade:

![0 16-from-0 14 2-new-db](https://cloud.githubusercontent.com/assets/1457929/13866588/3db0ed3e-ecb7-11e5-8b84-8796a18a5ae8.png)

**Comment by radinamatic** [comment]
@MCGallaspy 
This morning I re-tried the first scenario on another computer, but with this Win7 VM I was unable to create the "Wilson Elementary" with `kalite manage generaterealdata`, no idea why... I run the command several times but upon starting the server, the facility was never there. 

Anyway, I added 2 facilities more of my own (meaning I had the `Default` one, `test1` & `test2`, each with a couple of users), proceed to upgrade, and this time they did survive! :smiley: 

So at this point I'm not sure if the issue has more to do with "Wilson Elementary" facility itself, and not with the migration during the upgrade...

**Comment by MCGallaspy** [comment]
Maybe it does have to do with the `generaterealdata` command. In versions 0.15 to 0.13, the *location* of `data.sqlite` used depends on *how you start* KA Lite. If it's started by the auto-boot process, then it won't use the `data.sqlite` file in your home directory (but rather in the system profile directory). Let me double check how the upgrade process works -- IIRC if you have data in the system profile, then KA Lite 0.16.x will prefer to use that rather than what's in your home directory.

**Comment by radinamatic** [comment]
Upgrade scenario 0.13 > 0.16 on Windows 7, all 3 previous facilities survived, included the infamous "Wilson Elementary" :wink:. 

> In versions 0.15 to 0.13, the location of data.sqlite used depends on how you start KA Lite. If it's started by the auto-boot process, then it won't use the data.sqlite file in your home directory (but rather in the system profile directory).

And what happens if the server has been running with no auto-boot for a while, and then setup to run on startup? There would be 2 `data.sqlite` files, or it would be transferred to system profile? Haven't really tested that, just curious...

**Comment by radinamatic** [comment]
This is what the user's home directory looks like on fresh 0.13 install - no `.kalite/` folder and the `data.sqlite` is in the `C:\Program Files` folder. 

![data sqlite0 13](https://cloud.githubusercontent.com/assets/1457929/13901793/ba8937de-ee2f-11e5-9f78-ba8612a3e881.png)

**Comment by radinamatic** [comment]
@MCGallaspy 
Run an upgrade from 0.14.2 on Windows 7 with build 199, and lost my previous users (4 in 3 groups). I had created them directly, nothing to do with `generaterealdata` command.

**Comment by radinamatic** [comment]
@benjaoming 

This, sadly, is still an issue, meaning the upgrade from 0.15.1 to 016.5 does not work **out of the box**, as Facilities from previous version get lost in the process.

##### 0.15.1
![ie11 - win7 0 15 running - oracle vm virtualbox_464](https://cloud.githubusercontent.com/assets/1457929/16026859/b86a99d0-31d1-11e6-950c-e5f9d5002122.png)


##### 0.16.5 (No Wilson Elem. facility and no users in Default one)
![selection_465](https://cloud.githubusercontent.com/assets/1457929/16026851/ab6ac00c-31d1-11e6-8546-f09816d2de07.png)


Restoring the old DB from `./kalite.backup` folder by copying it to the new `./kalite/database` folder seems to work, but we should at least document this explicitly.

**Comment by benjaoming** [comment]
@radinamatic 

Could you try on an Ubuntu 0.15 to run `generaterealdata` and then upgrade to 0.16 and see if it's the same issue?

**Comment by radinamatic** [comment]
My guess is that it will not (as it has never turned up in Ubuntu upgrade scenarios), and that it has smth to do with the whole Windows SYSTEM user mess, but I'll re-test it first thing... We don't consider this a release-blocker, right? 
@benjaoming

**Comment by benjaoming** [comment]
> We don't consider this a release-blocker, right? 

That's a bit too late now ¯_(ツ)_/¯

**Comment by benjaoming** [comment]
@radinamatic - if the problem still exists on Windows for upgrading from 0.16 to 0.17, I would suggest that we create an entry in "Known Issues".

Furthermore, we should probably move this issue to installers repo, it might be the installer tossing out the whole database?

**Comment by radinamatic** [comment]
Saying goodbye to this issue, upgrade from 0.16 to 0.17b4 on Win 8.1 is flawless: installer detects the previous version, asks the user if they want to maintain it, and preserves the database (I made a copy of `.squilte` files, but it wasn't necessary as both facilities with their users survived 😉 ). This issue has most probably been caused by something in the `generaterealdata` command, IMHO.
