### ISSUE TITLE
Red crosses for incorrect exercises will vanish if the user refresh the page.

### ISSUE THREAD

**Issue by djallado** [learningequality/ka-lite#5017]
## Summary

This is in a `Functional Testing Checklist` of every installers.
`Do some exercise items incorrectly, refresh the page and make sure both incorrect and correct points (green check marks and red crosses are still there).`
When testing this the red crosses for incorrect exercises, will vanish if the learner refresh the page.

I tested this in OS X Yosemite and using Google Chrome browser.

## Branch or installer method

 - Version: 0.16.x

or:

 - Branch: 0.16.x

## How to reproduce

1. Login as learner
1. Do some exercise items incorrectly.
1. Refresh the page.  

## Screenshots
![screen shot 2016-03-18 at 2 51 24 pm](https://cloud.githubusercontent.com/assets/8664071/13870874/9e87375e-ed1a-11e5-941a-7d19b752eae3.png)
Taking exercises with 3 incorrect answers.

![screen shot 2016-03-18 at 2 56 36 pm](https://cloud.githubusercontent.com/assets/8664071/13870871/93ce0c02-ed1a-11e5-9dc7-24f970edc444.png)
Red crosses will vanish after a refresh.

**Comment by radinamatic** [comment]
Confirmed on IE11, FF & Chrome - 0.13 upgraded to 0.16 (build 182) on Windows 7.

**Comment by radinamatic** [comment]
Confirmed with .deb installer too (0.14.2 upgraded to 0.16b2 on Ubuntu 15.10).

**Comment by jamalex** [comment]
I've been investigating. This has the same cause as the `Upload error: {'exercise_id': [u'This field cannot be blank.']}` error we're seeing with syncing, namely that we're apparently no longer storing the `exercise_id` on `AttemptLogs`... This renders `AttemptLogs` pretty meaningless, so I'm prioritizing fixing this now.

**Comment by rtibbles** [comment]
Fixed in #5039
