### ISSUE TITLE
Error when im trying to sign up on KA Lite

### ISSUE THREAD

**Issue by j4pr1** [learningequality/ka-lite#5019]
Im trying to installing KA Lite on my raspberry 2, everything is well but when im trying to SIGN UP the KA Lite is error : 
Error
Sorry, but there was an error while trying to load the page.

(TemplateSyntaxError: Could not parse the remainder: '% block manage_nav %}{{ block.super' from '% block manage_nav %}{{ block.super')

This is my screenshoot 
![kalite](https://cloud.githubusercontent.com/assets/8577293/13905153/8a159c36-eee9-11e5-840e-fc494e0f3eda.png)

Can someone in this forum help me? what's matter with this error?

**Comment by benjaoming** [comment]
Thanks for the report @j4pr1 -- I'm sorry that no one has responded.

We have done a lot of bug fixes, and you're welcome to try out the latest alpha for Raspberry Pi here:

https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed
