### ISSUE TITLE
Total exercise attempted number on Coach report is not displaying the correct numbers - Verision 0.15

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/ka-lite#5020]
**Detailed description:**
Total exercise attempted on the coach report does not show the correct number for the date range selected.
**Expected behavior:**
The exercise attempted should show the exact number of the attempted exercise for the selected date range.
**Actual behavior:**
Upon attempting 1 exercise for the selected date range, Exercise attempted should be shown as 1 , instead the number is displayed as 2.

Note: I attempted 1 exercise and 2 questions of "Counting with small numbers" 

Please refer the screenshots for more details.
![screen shot 2016-03-21 at 4 30 16 pm](https://cloud.githubusercontent.com/assets/13453618/13918043/b44433d6-ef8a-11e5-8e47-f41eca26fda0.png)
![screen shot 2016-03-21 at 4 31 27 pm](https://cloud.githubusercontent.com/assets/13453618/13918050/bbc2364e-ef8a-11e5-8fcb-32ee43b1ffb2.png)
![screen shot 2016-03-21 at 4 32 17 pm](https://cloud.githubusercontent.com/assets/13453618/13918053/c04c85d4-ef8a-11e5-8fe6-522a21945924.png)

**Comment by sethachoi** [comment]
Report is accurate, but bug or feature? If feature we should rename "exercise attempts" to "question attempts" or something.

To clarify, as of 0.16.x, each question is being counted as an exercise attempt, rather than the exercise itself as one attempt. 

@rtibbles

**Comment by harishbalachandran** [comment]
Oh, Just to confirm "exercise attempted" displayed is number of questions attempted attempted for that date range. 

Then in that case we should rename it to number of **Questions attempted** instead of Exercise attempted. 
Because as a teacher I will be really confused.

**Comment by sethachoi** [comment]
Sorry if it was unclear, once again I was just confirming and jotting down notes that the bug is present in 0.16 and not just 0.15

**Comment by harishbalachandran** [comment]
Oh! sorry I miss understood. Thanks. :100:

**Comment by rtibbles** [comment]
The clarification here is that 'exercise attempts' means 'attempts at an exercise' not 'exercises attempted'. 

If it said 'Exercise*s* attempted' it would mean the latter. I agree that a change in wording would probably be good.

**Comment by benjaoming** [comment]
I disagree on changing language. I've just fixed it so that numbers add up (the graph below showing struggling, in progress, and completed). So everything is now about exercise attempts.

Before, this was possible:

![screenshot from 2017-04-07 14-02-56](https://cloud.githubusercontent.com/assets/374612/24800792/e20749a4-1ba1-11e7-83ce-157522474efc.png)

A teacher with no background in this, supposing to understand these coach report, will scratch her head about these figures.

**Comment by benjaoming** [comment]
Btw. what the above example is meant to show: During some period, there has been 17 exercise attempts recorded, however data has been updated on `latest_activity_timestamp` for loads more exercises.

I have no intention of finding out why, so instead I'll leave the "Total exercise attempts" (so we don't bother translators) and assume that it appeals to some level of intuition.

**Comment by benjaoming** [comment]
After the change:

![screenshot from 2017-04-07 14-56-45](https://cloud.githubusercontent.com/assets/374612/24800942/7b9b8ab2-1ba2-11e7-875d-ac3b82180d18.png)

**Comment by benjaoming** [comment]
Fixed in #5435
