### ISSUE TITLE
Answers for “Counting with Small numbers” exercise is not displayed in the coach report – Version 0.15

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/ka-lite#5021]
**Detailed description:**
Answers for “Counting with Small numbers” exercise is not displayed in the coach report. 

**Expected behavior:**
The answer should be displayed in a format so that the teacher could understand what the kids has entered.

**Actual behavior:**
Answers presently shows the image files, which teachers cannot understand.
**Note:**
Same is the case for the exercise where the kid have to sort the right order, like Ordering fractions exercise the answers are not getting displayed. 
![screen shot 2016-03-21 at 5 16 53 pm](https://cloud.githubusercontent.com/assets/13453618/13919309/ae81f958-ef92-11e5-902c-59b4916e60be.png)
![screen shot 2016-03-21 at 5 17 09 pm](https://cloud.githubusercontent.com/assets/13453618/13919313/b453b8ee-ef92-11e5-83fa-8c8508892283.png)
![screen shot 2016-03-21 at 6 26 31 pm](https://cloud.githubusercontent.com/assets/13453618/13919395/2dea3be2-ef93-11e5-91b5-e3c76a5943d9.png)
![screen shot 2016-03-21 at 6 26 44 pm](https://cloud.githubusercontent.com/assets/13453618/13919396/2e4f217e-ef93-11e5-9f07-37c0183642b0.png)

Please refer the screenshots for more details.

**Comment by sethachoi** [comment]
Confirmed still an issue on latest 0.16.x, tested on OSX

**Comment by rtibbles** [comment]
This will require the question preview logic requested in #5044.

**Comment by benjaoming** [comment]
Yeah, let's just do #5044 (rephrased its title)
