### ISSUE TITLE
Video topic tree not complete in German

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#5024]
## Summary

German video topic tree in 0.16 seems to contain only the Math topics, and none of the other 3 that it had on previous versions.

## Branch or installer method

Confirmed on both Windows (build 182) & Beta2 .deb installer on Ubuntu.

## How to reproduce

1. Install KA Lite 0.14 or 0.15 and upgrade to 0.16. 
1. Install German contentpack (otherwise you won't be able to load the tree).
1. Go to `Manage > Videos` and select German. 

## Screenshots

German video topic tree in 0.14.2. 

![igerman-video-tree-win7-0 14 2](https://cloud.githubusercontent.com/assets/1457929/13937901/183054a4-efc9-11e5-98b0-8e0a39356b45.png)

German video topic tree in 0.16. 

![german-video-tree-0 16](https://cloud.githubusercontent.com/assets/1457929/13937997/ba4b25ac-efc9-11e5-9616-49435d8958e3.png)

## Real-life consequences

None of the previously downloaded/used videos & exercises for non-math topics are available anymore...

@aronasorman

**Comment by aronasorman** [comment]
Will look into this. I also uploaded a new set of lang packs (and will upload automatically everyday) so I'll check if this is a one time thing.

**Comment by radinamatic** [comment]
@aronasorman Just did one more upgrade pass with Windows XP (0.13 to 0.16), downloaded German language pack form KA Lite UI, and video topic tree is all here, even more complete than it used to be! :joy_cat: 

![0 13-0 16-on-xp](https://cloud.githubusercontent.com/assets/1457929/13953685/6e0dd788-f03d-11e5-95c6-6ab70066d28d.png)

**Comment by aronasorman** [comment]
@radinamatic nice! How about the language pack metadata? They should now include the subtitle metadata too.

**Comment by radinamatic** [comment]
Yes, I think it did... :+1: 

Let me see if I can dig the screenshot (on the other testing computer).

**Comment by radinamatic** [comment]
Size is still missing on latest languagepack in 0.16:

![germanlangpackmetadata](https://cloud.githubusercontent.com/assets/1457929/13957747/dff58cf0-f04d-11e5-962a-3a1f42b6c275.png)

This is what it looked like in 0.13.2 installation before the upgrade:

![germanlangpack0 13](https://cloud.githubusercontent.com/assets/1457929/13957782/00539a46-f04e-11e5-8a3f-3667ca621c2f.png)

Where did the 1000 subs more from 0.13 disappear? It says 1771 on 0.13 version and only 706 in latest German langpack...

**Comment by aronasorman** [comment]
@radinamatic we don't cache subtitles for 0.16 anymore, and the cache that's been in the old lang pack builder has been existing since 0.11.1. So a lot of those are outdated, while the ones we bundle in for 0.16 are fresh from Amara.

However, there is still no file size included. Let me try to fix that.

**Comment by radinamatic** [comment]
Awesome! Sounds like we're almost there... :+1:

**Comment by aronasorman** [comment]
Zip file size should be fixed now. Otherwise, this issue has been closed with the latest language packs.
