### ISSUE TITLE
No language pack available in 0.16.x. 

### ISSUE THREAD

**Issue by djallado** [learningequality/ka-lite#5025]
## Summary

No language pack available when user click on `Select language pack` dropdown list.
Using `OS X Yosemite` and `Safari` browser.

## Branch or installer method

*Please specify if you are using the current `develop` branch or which installation source you were using when the issue occurred.*

 - Installer: `OS X` latest from [Dungeon](http://dungeon.learningequality.org/browse/KL-MT16-92).
 - Version: `0.16.x`

or:

 - Branch: `0.16.x`

## How to reproduce

1. Login as admin
1. Click on the `MANAGE` tab
1. Click on the `Select language pack` dropdown list in the `Language` tab.

## Screenshots

![select language](https://cloud.githubusercontent.com/assets/8664071/13943900/c4e7c3fe-f03b-11e5-8e28-1666880eef0f.png)

**Comment by amodia** [comment]
@djallado I tested this on OS X Mavericks [build 93 on bamboo](http://dungeon.learningequality.org/build/result/gotoBuildResult.action?buildKey=KL-MT16&buildNumber=93&returnUrl=%2Fbrowse%2FKL-MT16-93%2Fmetadata). It's working fine, the languages are available in dropdown list.

![screen shot 2016-03-22 at 3 53 48 pm](https://cloud.githubusercontent.com/assets/8663934/13945508/d75a923e-f048-11e5-9db6-fb88a7a37065.png)

**Comment by djallado** [comment]
@amodia, I check this also using [build 93 from dungeon](http://dungeon.learningequality.org/build/result/gotoBuildResult.action?buildKey=KL-MT16&buildNumber=93&returnUrl=%2Fbrowse%2FKL-MT16-93%2Fmetadata).

Here's my screenshot:

![build93](https://cloud.githubusercontent.com/assets/8664071/13945660/ffb472bc-f049-11e5-930f-b1e7a6e73851.png)

Thank @amodia. I'll close this issue.
