### ISSUE TITLE
"Compatilibity" issue

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#5026]
## Summary

A naming typo in loading a module means it will never actually be loaded.

See: https://github.com/learningequality/ka-lite/blob/0.16.x/kalite/distributed/static/js/distributed/bundle_modules/base.js#L47

(`compatilibity` -> `compatibility`)

## Branch or installer method

 - Branch: 0.16.x

**Comment by rtibbles** [comment]
Fixed in #5046
