### ISSUE TITLE
Documentation links still point to v0.15.

### ISSUE THREAD

**Issue by amodia** [learningequality/ka-lite#5027]
## Summary

Documentation links still point to v0.15.

## Branch or installer method

 - Installer: Windows/OS X/Debian
 - Version: 0.16.x

## How to reproduce

1. Run the KA Lite server.
1. Log in as admin.
1. Navigate to "DOCS" tab.
1. Download any KA Lite installers.

## Sample screenshots.

![screen shot 2016-03-23 at 6 51 43 pm](https://cloud.githubusercontent.com/assets/8663934/13983081/8683ca16-f128-11e5-9631-6d436460c03f.png)

![screen shot 2016-03-23 at 6 39 36 pm](https://cloud.githubusercontent.com/assets/8663934/13982814/1acf42ce-f127-11e5-8fdc-1bc3178defa5.png)

![screen shot 2016-03-23 at 6 40 24 pm](https://cloud.githubusercontent.com/assets/8663934/13982808/0ee14eee-f127-11e5-9efd-9cb546f1cbbc.png)

![screen shot 2016-03-23 at 6 40 46 pm](https://cloud.githubusercontent.com/assets/8663934/13982800/059da418-f127-11e5-9543-28bebfc36f45.png)

![screen shot 2016-03-23 at 6 41 10 pm](https://cloud.githubusercontent.com/assets/8663934/13982788/f552e208-f126-11e5-84e8-59b498f30795.png)
.

**Comment by radinamatic** [comment]
@amodia Yes, we still have to do a lot of docs revisions... You can add more items to `Pending to be documented` list on the [Trello Board](https://trello.com/c/ZIOuvz9L), or put a PR directly!

**Comment by benjaoming** [comment]
That seems fixed!
