### ISSUE TITLE
Languagepack updating, metadata and other questions

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#5037]
## Summary

Trying to understand languagepack metadata upon upgrading...

## Branch or installer method

Upgrade scenario on OSX Yosemite from 0.15 to 0.16 with .pkg build 99, but it's probably a general issue.

#### Problem 1.
1. Upgrade from 0.15 to 0.16, that brings the updated English contentpack.
1. Previously had Danish, French & Portuguese installed. This last one offers an update, so I gladly do it. 
1. Upon update that's the only one with the `Up to Date` label. 

If the 0.16 installer brings the updated English languagepack, shouldn't it have the `Up to Date` label by default?

#### Problem 2.

1. Select Spanish for download.
2. `0MB/0 exercises` info below - not sure if that's still missing/to-be-fixed... 
3. Upon download Spanish also has the `Up to Date` label.

I'm wondering: how difficult it would be to insert `Please Update & restart the server` label for all the languages that user had on previous version?
 
#### Problem 3.
Danish languagepack is still unavailable - no sign of it in the language selector.
If I recall well, we also had Bulgarian in the previous versions...

## Screenshots

![langpack-metadata](https://cloud.githubusercontent.com/assets/1457929/14025230/561d60d8-f1ed-11e5-99fe-acb41dc12aae.png)
@aronasorman

**Comment by aronasorman** [comment]
Problem 2: Is this still the case? I can see the zip size at least on my side:

![screen shot 2016-03-24 at 15 20 08](https://cloud.githubusercontent.com/assets/191955/14032994/f8e2847a-f1d3-11e5-8298-6187592cc594.png)

Exercise count is still not shown though, that's expected. Will fix if I still have time.

Problem 3: Should be fixed now once this build succeeds: http://dungeon.learningequality.org/browse/CP-KL-93

Problem 1: Minor issue. Won't fix this release.

**Comment by aronasorman** [comment]
![screen shot 2016-03-24 at 15 25 54](https://cloud.githubusercontent.com/assets/191955/14033087/bc9fbe0a-f1d4-11e5-9589-bce478481ff3.png)

**Comment by radinamatic** [comment]
It's still `0.00 MB (on disk) 0 exercise(s)`in the second row.
What's the difference between "to download" and  "on disk"?

**Comment by radinamatic** [comment]
Something must be different with the contentpack metadata @aronasorman, since the new one does not overwrite the old ones when upgrading from 0.14. They both remain among the installed languages and might confuse the users:

![es-es-updated-ie9 - win7 0 16 build 199](https://cloud.githubusercontent.com/assets/1457929/14082292/7a9298b4-f50f-11e5-8c9f-9589a5f6da51.png)

The old one was named `Spanish; Castilian`, while the new one is `Spanish, Spain`.

**Comment by radinamatic** [comment]
Both locales are there, @aronasorman, the old `es` and the new `es_ES`:

![ie9 - win7 0 16 build 199 running - oracle vm virtualbox_390](https://cloud.githubusercontent.com/assets/1457929/14082794/37fdcdcc-f512-11e5-9f69-b027e8135e22.png)

**Comment by radinamatic** [comment]
Reviewing this with OSX pkg installer build 105, and still seeing the option to download `Spanish, Spain` which installs in `es_ES` locale folder, and coexists with preexisting `Spanish; Castilian` in `es` locale folder:

![es-on-16b](https://cloud.githubusercontent.com/assets/1457929/14125185/0a45e970-f60a-11e5-9f3b-f96b5f8a05fd.png)

![es-on-16-3](https://cloud.githubusercontent.com/assets/1457929/14125187/16ae8032-f60a-11e5-94fc-85c14a53c8fd.png)

 @aronasorman

**Comment by aronasorman** [comment]
@radinamatic yup, fix will be on the content pack side. Will do later this week, but there should be no change involved code-wise.

**Comment by radinamatic** [comment]
Ok, so I'll leave this open until it's fixed on contentpack side!

**Comment by radinamatic** [comment]
And let's keep in mind that this also affects the availability ("findability") of previously downloaded videos. This installation was an upgrade scenario from 0.15 with several Spanish videos - they don't seem available in the new `es_ES` video topic tree and the old `es` one cannot even open the topic tree. 

I'm only insisting on this locale because it's one that potentially has the most users.

![es-on-16c](https://cloud.githubusercontent.com/assets/1457929/14125472/a8d1f416-f60b-11e5-885f-caeeed735655.png)

**Comment by aronasorman** [comment]
@radinamatic how about if you switch to es-ES as your language? does it show the previously downloaded videos?

**Comment by radinamatic** [comment]
Switching to `Spanish, Spain` as default language:

![es-on-16d](https://cloud.githubusercontent.com/assets/1457929/14125776/5b03d662-f60d-11e5-82a9-d9f778e06239.png)

Scanning for videos in `Español`, seems to be looking for `es_ES`, but  doesn't find any:

![es-on-16e](https://cloud.githubusercontent.com/assets/1457929/14125796/71e25cb4-f60d-11e5-81a2-fc5217869cfa.png)

Scanning for videos in `Español; Castellano`, doesn't open video topic tree.

**Comment by radinamatic** [comment]
And scanning for videos in Portuguese does not open the video topic tree either (contentpack updated and server restarted afterwards):

![pt-on-16](https://cloud.githubusercontent.com/assets/1457929/14125980/62c50636-f60e-11e5-8fee-7bff0cf726da.png)

**Comment by aronasorman** [comment]
Problem is in the content pack. No videos included.

**Comment by benjaoming** [comment]
Problem reported by @elvistek is solved in #5141

Closing this because the focus of the report "Languagepack updating, metadata and other questions" is unclear :) I hope that's cool, @radinamatic -- I think we've solved the bulk of our content pack issues now so we should try to be very concise about further issues.
