### ISSUE TITLE
unexplained raspberry pi slowdown

### ISSUE THREAD

**Issue by gimick** [learningequality/ka-lite#504]
When benchmarking 10 simultaneous client logins, time to login was in the range 30-60 seconds.
To verify the result, the test was also tried on another server.  Results were similar.

After rebooting the distributed raspberry pi server, login response time immediately reduced to 3-7 seconds. 

Prior to reboot and testing, the server had zero swapfile used, cpu 2%, no zombie or defunct processes.  There were no signs that the server was under any load.  The server is dedicated to benchmark testing, so there is no extra software installed.

Both raspberry pi servers tested had been up for a period of time (between 15 and 20 days).

**Comment by rtibbles** [comment]
Superseded.
