### ISSUE TITLE
documentation error - language pack links not working

### ISSUE THREAD

**Issue by needlestack** [learningequality/ka-lite#5053]
## Summary

Following the instructions under "How can I install a language pack without a reliable internet connection?" - the links described do not work. For example:

http://keep.learningequality.org/media/language_packs/0.15/es.zip

Results in a 404.

## Branch or installer method

Online documentation - part of the o.15.x branch

## How to reproduce

1. Visit http://ka-lite.readthedocs.org/en/0.15.x/faq.html#how-can-i-install-a-language-pack-without-a-reliable-internet-connection
2. Try to download a language pack following the instructions
3. No dice

As a bonus, it might be nice to have the links right in the documentation, instead of just the example URL and a list of language codes. The list of language codes could be made into links to the packs themselves. This would also make it so that a link-check on the website would catch this error.

Cheers - keep up the great work!

**Comment by radinamatic** [comment]
@needlestack We are in the process of updating documentation for the release of 0.16, since the process has changed: https://github.com/learningequality/ka-lite/wiki/Content-packs

To download the new contentpacks for 0.16:
http://pantry.learningequality.org/downloads/ka-lite/0.16/content/contentpacks/

@aronasorman Can we restore the old languagepacks for users who run previous releases?

**Comment by needlestack** [comment]
Thank you for the prompt response - the 0.16 release sounds like a great one! But as someone who will be stuck with 0.15 for a while, it would be great to have access to the old language packs until 0.16 is released and we can update our system. Thanks for your consideration!

**Comment by benjaoming** [comment]
Hello all!

The docs for 0.16 have been fixed: http://ka-lite.readthedocs.io/en/latest/faq.html

As for 0.15, use a URL like this: `https://kalite.learningequality.org/media/language_packs/0.15/es.zip`

Sorry that the `keep.learningequality.org` doesn't work anymore, didn't live much up to its name. Maybe @aronasorman can have a look at the server and make it a redirect to `kalite.learningequality.org`.

**Comment by jamalex** [comment]
That link never worked before; `keep.learningequality.org` is a direct pointer to the backend server, which runs on port `8008`. This was a documentation error. I have now updated the server to support the documentation error. :)

**Comment by jamalex** [comment]
(Now, the backend server listens on both `80` and `8008`)
