### ISSUE TITLE
Spanish topic tree - contentpack issue

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#5064]
## Summary

*I know you are still working on this @aronasorman, just listing the things we need to make sure work contentpack-wise, prior to final release.*

I've seen it the other day, and confirmed with the latest install on Ubuntu via PyPi: Spanish sidebar & video topic tree have only 4 first-level items:

![ubuntu 14 04 ready running - oracle vm virtualbox_402](https://cloud.githubusercontent.com/assets/1457929/14151701/7fb17e4a-f6af-11e5-9e7a-7220b4d3145e.png)
 
## Branch or installer method

Latest 0.16 release installed today via PyPi on Ubuntu 14.04.

**Comment by aronasorman** [comment]
@radinamatic we filter out unavailable topics both in the content pack and in the distributed server, so this seems more like KA's issue. I'll confirm after I rebuild the spanish content pack.

**Comment by radinamatic** [comment]
Something must be wrong anyway, because now it seems that there's only **12** videos total for Math in Spanish... :anguished: 

Here is what video topic tree looks like on freshly installed OSX (signed installer from pantry):

![spanish_videos_on_mavericks_build_108](https://cloud.githubusercontent.com/assets/1457929/14152021/3725e510-f6b1-11e5-9235-3757a12a4ddb.png)

**Comment by aronasorman** [comment]
I built a new `es.zip` (with the correct lang code!) and this is the topic tree I get:

![screen shot 2016-03-30 at 11 26 59](https://cloud.githubusercontent.com/assets/191955/14152935/73442832-f66a-11e5-96b3-3ae4d98d3324.png)

Is this the topic tree you're expecting @radinamatic? If so, I'll push my changes now and then have the buildserver make the lang packs.

**Comment by radinamatic** [comment]
That's more like it... :+1: 

I'm downloading the new es.zip, will try it out!

**Comment by radinamatic** [comment]
Seems OK regarding the nº of videos (more than 3k with this new contentpack) @aronasorman. 

It is still just 4 first-level items, which might come as a surprise to some of the users when they upgrade, but if it's KA issue, not much we can do...

**Comment by radinamatic** [comment]
We are back to calling it `Spanish, Castellano`? :grinning: 

It does not have the `Up To Date` label either...

![ubuntu 14 04 0 16 pypi running - oracle vm virtualbox_403](https://cloud.githubusercontent.com/assets/1457929/14155254/3f6d84f2-f6c1-11e5-8109-97471cec2dde.png)

**Comment by aronasorman** [comment]
@radinamatic that's because it's not in pantry yet! Should be fixed once it's OK and we start building it there.

**Comment by radinamatic** [comment]
And only 110 subtitles? That's also highly suspicious! @aronasorman

**Comment by radinamatic** [comment]
German topic tree is back to having only Math... :unamused: 
I'm guessing contentpack has to be rebuild, right?

**Comment by radinamatic** [comment]
Hm, I'm not getting the usual output then trying to install these latest `es.zip` and `pt-BR.zip` contentpacks on Win7 (with latest/signed Win installer from pantry) @aronasorman

I installed both on Ubuntu without problems, not sure what's up with Windows, I tried both with server running and stopped...

![cpacks-ie10_win7](https://cloud.githubusercontent.com/assets/1457929/14156720/3d63b986-f6c8-11e5-8cc9-47042efb88a9.png)

**Comment by aronasorman** [comment]
@radinamatic strange error, was python installed when you installed kalite?

**Comment by aronasorman** [comment]
Good catch on the # of subtitles, I should change the mapping of that to
es-ES.
ᐧ

**Comment by radinamatic** [comment]
> strange error, was python installed when you installed kalite?

I installed the signed Win .exe from pantry, so there's Python that came with it (2.7.9 or 10?) 

@aronasorman

**Comment by radinamatic** [comment]
I'm not sure where exactly is the problem, but I'm back at having only 12 videos & 110 subtitles with the latest Spanish contentpack... :sob: 

Windows XP, signed installer from pantry, latest `es` & `pt-BR` contentpacks:

![es](https://cloud.githubusercontent.com/assets/1457929/14189999/ab318d9e-f790-11e5-9c54-96eb7cd5e7c6.png)

![es-videos](https://cloud.githubusercontent.com/assets/1457929/14190003/b357b1ec-f790-11e5-9236-b4f1a8211c2b.png)

Slightly better situation for Portuguese, but still far from what KA has on their PT site:

![pt-br-math](https://cloud.githubusercontent.com/assets/1457929/14190011/b94dd586-f790-11e5-8aa2-f265a230eb47.png)

We seem to be having only the last 3 Math topics from those available on KA site:

![pt-matematica___khan_academy](https://cloud.githubusercontent.com/assets/1457929/14190129/6d2e0652-f791-11e5-92f3-9e6276b28c7d.png)

**Comment by aronasorman** [comment]
@radinamatic was this the case before the switch from `es-ES` to `es`?

**Comment by radinamatic** [comment]
I honestly don't remember now @aronasorman, but I did see the more complete Spanish topic tree yesterday at some pint (ref. my comment above: https://github.com/learningequality/ka-lite/issues/5064#issuecomment-203598472)

**Comment by aronasorman** [comment]
@radinamatic the complete spanish topic tree was due to the removal of the filter deleting undubbed and unsubtitled videos. This content pack restores it, and hence it's gonna be more restricted than yesterday. Can you compare the available videos in KA for spanish with the ones we have in the content pack, and see what we're missing?

**Comment by radinamatic** [comment]
Then our filter must be fricking-super-over-zealous, because it's leaving only 4 Math topics from those available on Spanish KA Math site:

![es-matematica___khan_academy](https://cloud.githubusercontent.com/assets/1457929/14190520/8b4c6ea6-f793-11e5-8c2c-a93a4641eadd.png)

**Comment by radinamatic** [comment]
And I'm still getting the meager-to-non-existent output when I try to install through the Command Prompt:

![command-prompt-ie8 - winxp](https://cloud.githubusercontent.com/assets/1457929/14190633/1d0b9d9e-f794-11e5-9b78-c6972abdd29f.png)

It's not the cause for our current woes, as I get the same "restricted" topic tree when I install through the UI, but it's weird nonetheless...

@aronasorman

**Comment by aronasorman** [comment]
Verified that there are more videos in KA than `es` lang pack. It might be an issue with the lang code we use for fetching to KA. Will verify.

**Comment by rtibbles** [comment]
@aronasorman Wondering if we might be having some issues from using their v2 rather than internal API for retrieving these video lists - they may have changed something in the backend that their v2 public API is not tracking properly?

**Comment by aronasorman** [comment]
That's a likely possibility as well -- looks like they use the internal API for their site. I'll test out the `es` content pack i'm generating then report back here.

**Comment by rtibbles** [comment]
Yeah, they also don't use a direct API call to populate most topic rendering, as it is prerendered into the serverside HTML template rather than accessed via an AJAX call.

**Comment by aronasorman** [comment]
@radinamatic this seems to have more content in it:

![screen shot 2016-03-31 at 14 56 49](https://cloud.githubusercontent.com/assets/191955/14192187/e23ca50c-f750-11e5-87cd-d5683e2f4c6c.png)

This is really annoying, given that their URL is `es.khanacademy.org` but they want their code to be `es-ES`. I'll make the change then push to the content pack maker.

**Comment by rtibbles** [comment]
Well, at least it does show up when we use that language code :)

**Comment by aronasorman** [comment]
Although said content pack still doesn't have this video available for download: https://es.khanacademy.org/math/early-math/cc-early-math-counting-topic/cc-early-math-counting/v/counting-with-small-numbers

**Comment by aronasorman** [comment]
So... I'm gonna take a look if that's getting filtered out, and why. If it's not in the topic tree we're getting from the v2 API at all, then we should try out the internal API.

**Comment by rtibbles** [comment]
The only issue with the internal API is that it doesn't have a projection function - we will have to create a new function that restricts to just the specified fields instead.

Let me know if you need me to pitch in.

**Comment by aronasorman** [comment]
@rtibbles Yup, I'll probably need your help when it comes to that part. Will ping you!

**Comment by rtibbles** [comment]
Fortunately, we already explicitly list the fields for the projections, so it should be relatively straightforward to just fetch the data and then run dict comprehensions on every node to only include the required keys.

**Comment by radinamatic** [comment]
@aronasorman I now have 28 videos donwloaded from the latest `pt-BR` (all 8 available in `Pré-cálculo`, and 20 more in `Cálculo integral`) and each and every one of them is Sal's original with working Portuguese subtitles. Are you sure the filter is including the dubbed videos at all?

![pt-br-some-math](https://cloud.githubusercontent.com/assets/1457929/14193526/de8a455e-f7a5-11e5-80a4-ab42eb1a9a64.png)

**Comment by aronasorman** [comment]
I think I finally solved this with the latest content packs:

![screen shot 2016-04-01 at 12 41 10](https://cloud.githubusercontent.com/assets/191955/14218116/18f9aaa2-f807-11e5-8270-b25419666327.png)

**Comment by aronasorman** [comment]
> 27.9 GB

That's more like it.

**Comment by benjaoming** [comment]
The outer-most level still has only 4 elements. Same result for French. But it's the same for the Spanish and French KA.org language sites.

Does it mean we can close this?

**Comment by radinamatic** [comment]
I agree @benjaoming, the specific problem that was the cause of this issue originally has been fixed in the meantime. I'm closing this, and if new one arises, will file again!
