### ISSUE TITLE
Enabling caching prevents translated videos from working

### ISSUE THREAD

**Issue by needlestack** [learningequality/ka-lite#5066]
## Summary

When enabling disk caching (by uncommenting `from kalite.project.settings.raspberry_pi import *` in `settings.py`, translated videos no longer show up. The translated content tree works, the translated exercises work, but the video entries in the content tree show as unavailable, even though the are there and work correctly when disk caching is turned off.

If I install the English videos, those will show up instead, and the text on the video pages will be in English, even though everything else is in Spanish. It seems that caching causes kalite to not use the `locale/dubbed_video_mapping.json` list at all (when building the topic tree and when showing video pages).

I have cleared everything in `cache` and `channel_cache_data` and restarted the server and it's always the same: works correctly with disk caching turned off, but fails with disk caching turned on.

I installed the videos from my own archive, not by downloading through the kalite interface, but again, it works with disk caching turned off.

## Branch or installer method

 - Installer: Raspbian Jessie / pip install ka-lite-static
 - Version: 0.15.1 (?)

## How to reproduce

1. Install kalite, install with Spanish language pack
2. Upload videos (I have them already; I don't get them through the kalite interface)
3. enable disk caching in `settings.py` with `from kalite.project.settings.raspberry_pi import *`
4. restart kalite
5. navigate to a translated video that you are sure exists (i.e. appears in `locale/dubbed_video_mapping.json`), it will be grayed out and will not play
6. navigate to an untranslated video (i.e. does not appear in `locale/dubbed_video_mapping.json`), it will show properly

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

Without disk caching the kalite startup process on the pi is 10 minutes or more, which most users interpret as "kalite failed to start". With disk caching we can't deploy in Spanish.

## Thanks

You guys are great - thanks for your wonderful project! I know you're working towards 0.16, but it would be nice if someone can give insight into why this is happening, and hopefully a workaround. I have symlinked the English videos to the Spanish ones, and that works except the video pages and their text is still not translated.

**Comment by needlestack** [comment]
Just confirmed that this is no longer a problem on 0.16 - specifically there's no caching to enable/disable as the content is now stored in a sqlite db and no JSON parsing is required at startup. Startup time is now very fast - great job!

**Comment by radinamatic** [comment]
@needlestack Thanks, we apreciate it! :+1: 
:dancers::dancers::dancers:
