### ISSUE TITLE
kalite manage setup gives cherrypyserver import error (OSX 10.11)

### ISSUE THREAD

**Issue by Kevsy** [learningequality/ka-lite#5071]
## Summary

kalite manage setup throws an import error for cherrypyserver

## Branch or installer method

 - OSX El Capitan
 - Version: 0.16

## Traceback or relevant snippet from server.log

```
 ~/Code/foundation/ka-lite$ ./bin/kalite manage setup --username=admin --password=silverfox --noinput
Traceback (most recent call last):
  File "<pyrun>/pyrun2.7.py", line 823, in <module>
  File "<pyrun>/pyrun2.7.py", line 699, in pyrun_execute_script
  File "/Users/kevinsmith/Code/foundation/ka-lite/kalitectl.py", line 116, in <module>
    from kalite.distributed.cherrypyserver import DjangoAppPlugin
ImportError: No module named cherrypyserver
```

Note that making the pythonpath explicit does not seem to have any effect (which is expected, since it reflects the working directory)

```
 ~/Code/foundation/ka-lite$ ./bin/kalite manage setup --username=admin --password=pass --noinput  --pythonpath=~/Code/foundation/ka-lite/
Traceback (most recent call last):
  File "<pyrun>/pyrun2.7.py", line 823, in <module>
  File "<pyrun>/pyrun2.7.py", line 699, in pyrun_execute_script
  File "/Users/kevinsmith/Code/foundation/ka-lite/kalitectl.py", line 116, in <module>
    from kalite.distributed.cherrypyserver import DjangoAppPlugin
ImportError: No module named cherrypyserver
```

However attempting the import from python shell is fine:

 ~/Code/foundation/ka-lite$ python
Python 2.7.10 (default, Oct 23 2015, 18:05:06) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import kalite.distributed.cherrypyserver
>>> 

## How to reproduce

1. Run kalite manage setup as per script above, on OSX El Capitan; Python 2.7.10

## Screenshots

*If applicable*

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

*If applicaple*

**Comment by amodia** [comment]
@Kevsy I can't replicate this issue on OS X El Capitan 10.11.4 with KA Lite branch 0.16.x. 

On terminal I run the following inside my kalite `virtualenv`:

1. `pip install -r requirements.txt`
2. `pip install -r requirements_dev.txt`
3. `./bin/kalite manage setup --username=admin --password=admin --noinput`

Here's the sample GIF.

![a-temp](https://cloud.githubusercontent.com/assets/8663934/14238247/32f31a04-fa61-11e5-8518-6523a007ac75.gif)

**Comment by djallado** [comment]
I tested this also using OS X El Capitan. I can't replicate this issue.
I can run `kA-Lite`  source using steps above. 
Here's my screenshot:
![el-capitan](https://cloud.githubusercontent.com/assets/8664071/14240971/60c8227a-fa7b-11e5-81db-cc980d21fe40.png)

**Comment by Kevsy** [comment]
Thanks @amodia and @djallado  - I'm still getting the problem even with reinstalls of virtualenv, npm etc. . Very strange, __init.py__ is in place so the subdirectories of ka_lite should be treated as modules... I will keep digging, but this must be a problem with my environment. When I get it working I will post an update, but for now will close the issue. Thanks again for your time!

**Comment by Kevsy** [comment]
Quick update: the bin/kalite script was not setting KALITE_PYTHON to the python of the virtualenv. By setting KALITE_PYTHON manually as an enviroment variable I get past the issue documented above...but then straight into #5035 , which I will now work on.

**Comment by indirectlylit** [comment]
Hi Kevsy – I committed a change regarding the referenced issue and forgot to add a comment. I just added a ref to that commit.

**Comment by Kevsy** [comment]
@indirectlylit thanks so much, all sorted now. Cheers!
