### ISSUE TITLE
Learner current score is not recorded when watching video and refresh the page.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/ka-lite#5072]
## Summary

Watching videos  without finishing it and refresh the page will not record the current score of the learner. I tested this on OS X EL Capitan build [111](http://dungeon.learningequality.org/build/result/gotoBuildResult.action?buildKey=KL-MT16&buildNumber=111&returnUrl=%2Fbrowse%2FKL-MT16-111) from dungeon OS X installer.

Related issue [#384](https://github.com/learningequality/installers/issues/384)
## Branch or installer method
- Installer: OS X
- Version: 0.16.x 
## How to reproduce
1. Log in as learner.
2. Watch video without finishing it and refresh the page.
## Here's a sample GIF.

![a-temp](https://cloud.githubusercontent.com/assets/8663934/14244359/3f5fd7f6-fa8d-11e5-85ea-2c751195b502.gif)

/cc: @radinamatic @aronasorman

**Comment by djallado** [comment]
@amodia: Confirmed. When I watch a video and refresh the page it will not record the score.  I tested this  on IE11 Windows 7 using (build 208) from dungeon.

**Comment by cpauya** [comment]
@aronasorman / @radinamatic Are we okay to push this for 0.17?  

This only manifests when a browser is refreshed manually by a user while viewing a video.

**Comment by cpauya** [comment]
@djallado / @amodia Let's test this using the latest builds for OS X (112) and Windows (213).

**Comment by aronasorman** [comment]
Yeah let's push this to 0.17.

**Comment by benjaoming** [comment]
Fixing this would mean calling an API endpoint at the same crazy interval as points are accumulated.

Lots of other unaswered questions like:

 - Quitting in the middle of a video will - no matter what if it's using Refresh or navigating away - not save points
 - Skipping to the end, points are not saved.
 - Watching a video again seems to deduct points, so when I score 750 points on Counting Squirrels and go back to watch it again, my points are deleted.

The only way to get points saved is to watch a full video without skipping, and then navigating away from the page (not clicking refresh or closing the browser).
