### ISSUE TITLE
Don't write content to staticfiles dirs

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#5073]
## Summary

Currently we unpack Khan Exercise translated html templates, and subtitle files into the collected static files folder.

We should instead put them into the content folder - this would avoid issues with overwriting when we force collectstatic to clear all files, and also mean that we can better test these features in debug mode also.
## Branch or installer method

Branch: master

**Comment by benjaoming** [comment]
Is this actually a bug? Does it mean that `collectstatic` will effectively remove parts of an unpacked content pack?

**Comment by rtibbles** [comment]
Potentially it could. It also makes dev with these features harder, because this can only be tested in production mode.

**Comment by benjaoming** [comment]
Some notes

subtitles:
.kalite/httpsrv/static/srt

metadata + locale files in locale dir
.kalite/locale

assessment item data go to
.kalite/content/assessment

html exercises go to:
.kalite/httpsrv/static/js/distributed/perseus/exercises/<lang_code>

**Comment by benjaoming** [comment]
Fixed in #5386
