### ISSUE TITLE
Browser interface problem

### ISSUE THREAD

**Issue by DavidBraun777** [learningequality/ka-lite#5075]
## Summary
          The sever tries to start up, however, when attempting to open up in browser the terminal: Google chrome, it states: 
URL: http://127.0.0.1:8008/update/videos/
This site can’t be reached

127.0.0.1 refused to connect.
ERR_CONNECTION_REFUSED
ReloadHide details
Check your Internet connection
Check any cables and reboot any routers, modems, or other network devices you may be using.
Allow Chrome to access the network in your firewall or antivirus settings.
If it is already listed as a program allowed to access the network, try removing it from the list and adding it again.
If you use a proxy server...
Check your proxy settings or contact your network administrator to make sure the proxy server is working. If you don't believe you should be using a proxy server: Go to the Chrome menu > Settings > Show advanced settings... > Change proxy settings... > LAN Settings and deselect "Use a proxy server for your LAN".
----------------------------------------------------------------------------------------------------------------------------------------
## Branch or installer method

*Please specify if you are using the current `develop` branch or which installation source you were using when the issue occurred.*

 - Installer: Windows 10 Home - Activated
 - Version: 0.15.1
----------------------------------------------------------------------------------------------------------------------------------------
## Traceback or relevant snippet from server.log

``` -I don't know how to find this relevant information...
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
``` -I don't know how to find this relevant information...


## How to reproduce

1. Steps: Start "KA lite", says: "The server is starting... please wait." 
Then attempting to go to web browser: "Load in Browser." button from right-clicking the icon in the icon tray doesn't darken up to be pressed for some reason...
1. To: Utilize Khan Academy offline while away from College campus in homeless shelter...
1. Reproduce:

![2342](https://cloud.githubusercontent.com/assets/18289527/14288837/fc78180e-fb1d-11e5-9419-ec108a6e702b.PNG)


*If applicable*

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

It may possibly be Norton security that thought it was a malicious software attack, then blocked it or deleted it...

**Comment by benjaoming** [comment]
Hi @DavidBraun777 

Thanks for the report. This isn't supposed to happen, but I don't think we can go further with the report without more data.

Please try to install the latest release of KA Lite and in case you still cannot connect to with through your browser, you should check that any firewall isn't stopping you.

In case you still have problems, please refer to the server log in your `.kalite` folder inside "Documents and settings" or something similar (sorry I'm not a Windows user). The file is called `server.log`. It can show you details in case the server has failed to start.

Thanks!
