### ISSUE TITLE
Custom content on ka-lite

### ISSUE THREAD

**Issue by SkaeX** [learningequality/ka-lite#5078]
Hi guys,
I don't know if it will be possible I get a workflow on how to add some local (mp3, mp4, and pdfs) to my ka-lite. I learnt it was possible with `kalite manage contentload`. Can someone please elaborate on the steps I need to achieve this.

**Comment by rtibbles** [comment]
As noted in #4975:
> Note: This feature is unsupported, so we have limited bandwidth to provide further information, but it is possible.
