### ISSUE TITLE
Error while downloading Language pack without reliable internet connection

### ISSUE THREAD

**Issue by koham66** [learningequality/ka-lite#5079]
## Summary

I am trying to download http://keep.learningequality.org/media/language_packs/0.15/<code>.zip

for different language codes, I get 404 " page not found " error

## Branch or installer method

Tried for both .16 and .15 release. I get the same error

 - Installer: Windows/OSX/Debian (?)
 - Version: 0.15.1 (?)

or:

 - Branch: develop (?)

## Traceback or relevant snippet from server.log

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

1. in  a web browser reach http://keep.learningequality.org/media/language_packs/0.15/en.zip
2. You will get 404 error

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

*If applicable*

**Comment by radinamatic** [comment]
Hey, @koham66, we apologize for this issue!

We are reorganizing folders on our server while getting ready to release the new 0.16, and some of the links for previous language packs have changed. Could you try this:  
```
https://hub.learningequality.org/media/language_packs/0.15/<language_code>.zip
```

Let us know if the problem is solved!

**Comment by koham66** [comment]
hi,

thanks a lot. It has worked for me.

regards

NSH

On Wed, Apr 6, 2016 at 5:56 PM, Radina Matic <notifications@github.com>
wrote:

> Hey, @koham66 <https://github.com/koham66>, we apologize for this issue!
>
> We are reorganizing folders on our server while getting ready to release
> the new 0.16, and some of the links for previous language packs have
> changed. Could you try this:
>
> https://hub.learningequality.org/media/language_packs/0.15/<language_code>.zip
>
> Let us know if the problem is solved!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/learningequality/ka-lite/issues/5079#issuecomment-206347356>
>



-- 
hurry home hurry..

**Comment by radinamatic** [comment]
Awesome, have a good day! :smiley:
