### ISSUE TITLE
no html docs in /usr/share/kalite/docs/_build/html 

### ISSUE THREAD

**Issue by tim-moody** [learningequality/ka-lite#5085]
## Summary

clicking on docs in gui gives 404 error

## Branch or installer method

0.16.1 on x64 VM and 0.16.2 on rpi3
both installed with pip

## How to reproduce

1. install
2. browse to gui
3. click on docs

**Comment by MCGallaspy** [comment]
Not sure why this is the case, but if you have root access then a possible workaround would be to navigate to the `/usr/share/kalite/docs/` directory, where you should find a make script. If you install the right dependencies (just `sphinx` I believe) then you can run `make html` to generate the docs.

**Comment by tim-moody** [comment]
there is no script either
to be clear /usr/share/kalite/docs/_build/html/ has the expected directories but
developer_docs, installguide, and usermanual are empty.
this is true of 0.16.1 and 0.16.2
docs are present in those directories in 0.16.0

**Comment by benjaoming** [comment]
I've checked this on 0.16.3 which I'm uploading to PyPi now -- I don't find said directories missing in the files that I'm putting up on PyPi.

![screenshot from 2016-04-25 17 05 20](https://cloud.githubusercontent.com/assets/374612/14788404/f7c91c8c-0b07-11e6-891c-53a36f5108b7.png)

I hope you can find the cause of the issue @tim-moody - perhaps it has something to do with a mixture of virtualenvs and debian installations in which one has left behind an empty directory? Try uninstalling or manually removing potentially conflicting folders (`/usr/share/kalite` vs `/usr/local/share/kalite` vs `/some/virtualenv/share/kalite`)

Best,
Ben
