### ISSUE TITLE
1 teacher can see/delete another teachers learners

### ISSUE THREAD

**Issue by jumbojim101** [learningequality/ka-lite#5089]
## Summary

A School has 2 computer labs running 8 hours per day. There can be a different coach each hour for each lab. In v15.x I was able to create a facility (First Hour - Lab 1)  for each coach so that only that coach could see learner reports for that facility(Hour/Lab). With 16.x , after a coach logs in to their facility , they can then select another facility and view/modify/delete users. Am I supposed to configure the site differently, is this a bug, or is this how things are supposed to work ? 
## Branch or installer method

_Please specify if you are using the current `develop` branch or which installation source you were using when the issue occurred._
- Installer: Windows 7
- Version: 0.16.1 and 0.16.2

or:
- Branch: develop (?)
## Traceback or relevant snippet from server.log

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```
## How to reproduce
1. Steps
2. To
3. Reproduce
## Screenshots

_If applicable_
## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

_If applicable_

**Comment by 0o0TheDude0o0** [comment]
I can confirm this issue. Bad deal for larger schools.

**Comment by rtibbles** [comment]
Hrm, the documentation seems to have lapsed for this, but this setting `RESTRICTED_TEACHER_PERMISSIONS=True` can be set in your settings file to prevent teachers from administering users.

Let's leave the issue open until the documentation is updated.

**Comment by 0o0TheDude0o0** [comment]
Thank you! Is there a way to output all possible options that kalite is capable of? I attempted kalite --help but did not provide much. Thanks again!

**Comment by benjaoming** [comment]
Fixed in #5371
