### ISSUE TITLE
100% width for notification bar and add in positive words for successful action  

### ISSUE THREAD

**Issue by ghost** [learningequality/ka-lite#509]
Something to consider: 
Longer notification on top, positive words used such as: "congrat!" , "successfully"

screen shot 2013-08-16 at 9 45 22 am![screen shot 2013-08-16 at 9 45 22 am](https://f.cloud.github.com/assets/4604132/976891/4946ced2-0698-11e3-884a-5b47724742e3.png)

Current: 
![screen shot 2013-08-19 at 1 37 31 pm](https://f.cloud.github.com/assets/4604132/989136/41f2af06-090f-11e3-8424-2be4523b301f.png)

**Comment by rtibbles** [comment]
Implemented.
