### ISSUE TITLE
Progress Streak for the exercise is not getting reset in a lerner starts a fresh exercise in Version 0.16

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/ka-lite#5096]
## Summary
The progress streak on the exercise is not getting reset when a learner starts a new exercise, instead the previous progress streak is getting displayed.

## Branch or installer method
OS: Ubuntu version 14 LTS
Installer: "pip install ka-lite" and "sudo kalite manage setup" 
Version: 0.16.1 
assessment file: en.zip (697.1 MB)

## How to reproduce
Pre- Requisite:
The learner should have already finished few exercise.

Steps to Reproduce: 
1. Login as learner 
2. Start a new exercise
3. Observe the progress streak bar.

## Screenshots
![screenshot from 2016-04-21 08_51_40](https://cloud.githubusercontent.com/assets/13453618/14697470/c1890b8c-07a1-11e6-93d6-359a2bda0b12.png)
![screenshot from 2016-04-21 08_52_24](https://cloud.githubusercontent.com/assets/13453618/14697471/c189e67e-07a1-11e6-8ba5-4c062884e019.png)
![screenshot from 2016-04-21 08_53_08](https://cloud.githubusercontent.com/assets/13453618/14697472/c18ab5d6-07a1-11e6-81b2-829369048ee1.png)
![screenshot from 2016-04-21 08_53_32](https://cloud.githubusercontent.com/assets/13453618/14697473/c18cbd90-07a1-11e6-8c2a-c96a8437f050.png)
![screenshot from 2016-04-21 08_53_40](https://cloud.githubusercontent.com/assets/13453618/14697474/c18e35bc-07a1-11e6-9856-ab8eb79bd1e2.png)
![screenshot from 2016-04-21 08_54_44](https://cloud.githubusercontent.com/assets/13453618/14697475/c190640e-07a1-11e6-8982-942bd3dc5f14.png)
![screenshot from 2016-04-21 08_55_30](https://cloud.githubusercontent.com/assets/13453618/14697477/c1a8cf3a-07a1-11e6-83a2-b50b0ca25ee2.png)
![screenshot from 2016-04-21 08_55_51](https://cloud.githubusercontent.com/assets/13453618/14697478/c1a94d84-07a1-11e6-9848-aaa19e9fbf21.png)
![screenshot from 2016-04-21 08_58_01](https://cloud.githubusercontent.com/assets/13453618/14697476/c1a7d12a-07a1-11e6-9ee3-b7b465405c77.png)
![screenshot from 2016-04-21 08_58_19](https://cloud.githubusercontent.com/assets/13453618/14697479/c1ac0042-07a1-11e6-8827-b4531fc6e18c.png)
![screenshot from 2016-04-21 08_58_31](https://cloud.githubusercontent.com/assets/13453618/14697480/c1b5e3e6-07a1-11e6-9157-13eaeebf109f.png)

**Comment by jamalex** [comment]
Fixed in the latest 0.16.2 installer.
