### ISSUE TITLE
Congruence & transformation exercise is not working - Version 0.16.1

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/ka-lite#5097]
## Summary
The Exercise: Math ---> Geometry --> Congruence --> Transformations-Congruence --> Congruence & transformation.
The above exercise does not work and we are unable to proceed further.  

## Branch or installer method
OS: Ubuntu version 14 LTS
Installer: "pip install ka-lite" and "sudo kalite manage setup"
Version: 0.16.1
assessment file: en.zip (697.1 MB)

## How to reproduce

1. Access the following exercise: Math ---> Geometry --> Congruence --> Transformations-Congruence --> Congruence & transformation.
2. Unable to submit or proceed to next question.

## Screenshots
![screenshot from 2016-04-21 12_47_56](https://cloud.githubusercontent.com/assets/13453618/14701136/4c68d9d4-07c1-11e6-9e37-22e9e2069af1.png)
![screenshot from 2016-04-21 12_48_06](https://cloud.githubusercontent.com/assets/13453618/14701141/5274290a-07c1-11e6-9778-5e0f38ec8b76.png)

**Comment by benjaoming** [comment]
Thanks for reporting this, it's quite thorough, though perhaps #5099 is slightly more thorough so closing this in favor of the other :) But don't worry about the issue itself, it's confirmed!
