### ISSUE TITLE
Questions are not loading for the exercise: Writing expression with variable - Version 0.16.1

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/ka-lite#5098]
## Summary
The Exercise: Math ---> Grade 7 (NCERT) --> Chapter 12: Algebraic Expression --> How are expressions formed? --> Writing expressions with variables

Questions are not displayed for this exercise. 

## Branch or installer method
OS: Ubuntu version 14 LTS
Installer: "pip install ka-lite" and "sudo kalite manage setup"
Version: 0.16.1
assessment file: en.zip (697.1 MB)

## How to reproduce
1. Access the following exercise: Math ---> Grade 7 (NCERT) --> Chapter 12: Algebraic Expression --> How are expressions formed? --> Writing expressions with variables

2.  Questions are not loading, even after refreshing page multiple times.

**Note:**
1. The questions in other exercises under Chapter 12: Algebraic expressions are loading, but after refreshing the page once.

## Screenshots
![screenshot from 2016-04-21 13_21_51](https://cloud.githubusercontent.com/assets/13453618/14701743/6d5ebfe8-07c4-11e6-84e9-394a7bba7f4e.png)
![screenshot from 2016-04-21 13_21_58](https://cloud.githubusercontent.com/assets/13453618/14701744/6d5ef21a-07c4-11e6-9e2a-40f51b135cc5.png)

**Comment by benjaoming** [comment]
Hi @harishbalachandran !

Thanks for a thorough description. This identifies very well as an issue we had in the packaging of the .deb which has just been solved in the 0.16.2-ubuntu2 release: https://github.com/learningequality/installers/pull/367

You can use the latest release from our proposed PPA: https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed

I'm gonna go ahead and close the issue, but feel free to yell if the latest release doesn't solve it!

...or wait a couple of hours, and I will have it out in its entirety.
