### ISSUE TITLE
'What do you think?' Feedback prompt - Any way to get rid of it?

### ISSUE THREAD

**Issue by Aypak** [learningequality/ka-lite#5104]
I am running ka-lite 0.16.2 on a rpi 2 and accessing it using android tablets. The prompt asking users to rate the quality and difficulty of the content appears everytime a student attempts an exercise. I understand that feedback is important to the ka-lite team. However, I think it takes up too much space on the small screen of the tablet, and also distracts students as it appears before every exercise. Is there any way to disable or hide this feedback prompt for students?

**Comment by benjaoming** [comment]
Thanks for the feedback, @Aypak 

I think this sounds like a reasonable feature. Something that should be configurable as a project setting. Please see #4054 for a description about app-based settings.

Setting something `KALITE_DISABLE_USER_FEEDBACK = True` in `~/.kalite/settings.py` would be a good solution.

If you're willing to contribute this, we would definitely have a look.

**Comment by Aypak** [comment]
Hi @benjaoming, thank you for your response. I'm sorry for the late reply. I currently have scanty knowledge of django and thus I don't know how I can contribute to this. I will follow along and try to learn as much as i can. I'll create a pull request if i arrive at a solution.
Thanks!

**Comment by radinamatic** [comment]
Or maybe activating the rating only after the learner completed the "8 out of 10" exercises? Rating would be based on a more complete learning experience...

**Comment by benjaoming** [comment]
@radinamatic I think that's a feature that's more appropriate for Kolibri :)

**Comment by radinamatic** [comment]
You're reading my mind @benjaoming!
I was about to suggest it as a feature for Kolibri and than got distracted... 😃

**Comment by benjaoming** [comment]
Sorry I had some issues getting this to work and kept force-pushing new commits on top of the old one :)

But it's fixed now @Aypak
