### ISSUE TITLE
Untranslated exercise questions

### ISSUE THREAD

**Issue by rifatbd** [learningequality/ka-lite#5107]
## Summary

When Bengali is selected as default Language the exercise should be shown in Bengali but for most exercise the question is in English Language. The exercise works fine but its not translated. Well the hint does show in Bengali.
As a try in fixing i looked into ".kalite\content\locale\js\i18n\bn.js" file but most of those string is not there so i tried adding a string myself like this `>> catalog['What number is missing?'] = '\u0995\u09CB\u09A8 \u09B8\u0982\u0996\u09CD\u09AF\u09BE\u099F\u09BF \u0985\u09A8\u09C1\u09AA\u09B8\u09CD\u09A5\u09BF\u09A4?';` which is -"কোন সংখ্যাটি অনুপস্থিত?"
But still that string is not translated in exercises. The screenshots will explain better i guess.

## Branch or installer method

- Installer: Windows installer from pantry (win7 64 bit)
- Version: 0.16.2
- language pack- latest bn.zip downloaded from (http://pantry.learningequality.org/downloads/ka-lite/0.16/content/contentpacks/)

## Traceback or relevant snippet from server.log

server.log is empty

## How to reproduce

1. Select Bengali as default language
2. go to learn/khan/math/early-math/cc-early-math-counting-topic/cc-early-math-numbers-120/count-to-100/
3. The question will be "কোন সংখ্যাটি অনুপস্থিত?" but its showing English

## Screenshots
![capture11](https://cloud.githubusercontent.com/assets/18570759/14857164/fedc59ec-0cbc-11e6-9d12-8ce127fc6de8.PNG)
![capture12](https://cloud.githubusercontent.com/assets/18570759/14857166/fedd70b6-0cbc-11e6-8e92-5e0d2cca2eb8.PNG)
![capture13](https://cloud.githubusercontent.com/assets/18570759/14857165/fedcddc2-0cbc-11e6-8299-bf10703663c2.PNG)
![capture14](https://cloud.githubusercontent.com/assets/18570759/14857622/cb0620e2-0cbe-11e6-9fd4-18894d276798.PNG)
![capture15](https://cloud.githubusercontent.com/assets/18570759/14857162/fedb72fc-0cbc-11e6-8d3b-55ca28b3ad20.PNG)

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

I don't know if i'm missing something here or am i able to add strings myself or how long it will take to pack those Bengali content for KA Lite ...
Actually I'm working on Khan Academy Bengali Localization Team and we are trying to deploy KA in some remote village where its only possible through KA Lite 
So if i can be of any assistance please let me know...

**Comment by benjaoming** [comment]
Thanks for this report!

Is it that the KA exercise data has already been translated but isn't present in the content pack?

**Comment by rifatbd** [comment]
@benjaoming yes that's the case...if you look again at those screens shots i added.. 4th one-- thats the same exercise on KA site

**Comment by rifatbd** [comment]
I tested the issue for some other language to check if the issue is only with Bengali, and what i found is for all the language i tested it is the same....
Here are some screenshots...
![es](https://cloud.githubusercontent.com/assets/18570759/15009365/d0acba80-1207-11e6-8fb3-17e6cb4859da.PNG)

![hi](https://cloud.githubusercontent.com/assets/18570759/15009366/d0afa6b4-1207-11e6-8b69-64219b839d4d.PNG)

![po](https://cloud.githubusercontent.com/assets/18570759/15009367/d0b19e10-1207-11e6-83a9-d2362be63e19.PNG)

**Comment by benjaoming** [comment]
@rifatbd thanks for elaborating more!

@rtibbles @aronasorman can you tell if the exercise question in the translation **is supposed to be translated** and if that's a bug or if its data missing in our content pack or from KA's APIs?

**Comment by rtibbles** [comment]
I think one of the issues here is with our *% Translated* - which only refers to *our* interface strings.

Looking at KA's Bengali site, it appears that very little of the content is currently translated: https://bn.khanacademy.org/

As such, we include the English exercise content as a fallback, due to the sparsity of the other content.

**Comment by rtibbles** [comment]
Oh, sorry - missed the final exercise screenshot on KA's site there. Yes, seems like a genuine issue with the exercise text then.

@aronasorman Any ideas why the Bengali exercises are untranslated?

**Comment by benjaoming** [comment]
@rtibbles as OP @rifatbd indicates, the problem seems to be consistent across many languages.

**Comment by rtibbles** [comment]
@aron This seems like it might be time to switch our assessment item translation over to fetching directly from the KA API endpoint - as it seems possibly that their PO files no longer contain the most up to date data for exercise translations?

**Comment by rtibbles** [comment]
e.g. this should be fetched for one of the assessment items for this exercise:
https://bn.khanacademy.org/api/internal/assessment_items/xac0726dbc9aae99d?lang=bn

**Comment by djallado** [comment]
I tried to replicate this also, here's my screenshots:
![screen shot bingali-100](https://cloud.githubusercontent.com/assets/8664071/15499344/4d8384ac-21d6-11e6-8bdd-3d1f855e49db.png)

But when I try this exercise: http://127.0.0.1:8008/learn/khan/math/early-math/cc-early-math-counting-topic/cc-early-math-counting/counting-out-1-20-objects/, the question is translated. Here's the screenshot:
![screen shot bingali](https://cloud.githubusercontent.com/assets/8664071/15499487/17b1ae70-21d7-11e6-83ba-435ca39b9690.png)
**Bengali**

![screen shot hindi](https://cloud.githubusercontent.com/assets/8664071/15499506/28cd6fe6-21d7-11e6-9c19-5220fa75a369.png)
**Hindi**

**Comment by arceduardvincent** [comment]
I download the `Bengali` language pack, then check the `bin.js`, which has an array of catalog. The content of this catalog is the value of translated string. 

Some of the string is not yet included in the catalog. I try to search the "What number is missing?" in the catalog, but it is not yet included.
See image attach:
![screen shot 2016-05-24 at 9 08 48 pm](https://cloud.githubusercontent.com/assets/4099119/15504929/cb161444-21f3-11e6-8722-af9d9141456c.png)

**Comment by rtibbles** [comment]
The translated exercise text will no longer appear either in a frontend
catalog, nor a po file. The translations are now stored directly in the
database file that is included in the content pack.

I think something odd isn't happening in the way we are getting data from
Khan Academy here, the content that is on their website does not seem to
match up to their public API that we use.

**Comment by radinamatic** [comment]
I had the same suspicion while testing this issue, about the difference on KA site and the API we use.

For the record, here is the doc with results of all the exercises in Early Math topic in Spanish:
[i18n errors 0.16.5](https://docs.google.com/spreadsheets/d/1fnPun_8qtCphMryEjak--TQ1ABgyCoIC3yk3ciXUabA/edit#gid=0)

In case somebody else goes on testing with other languages they might just add the appropriate column with results and we may be closer to finding a pattern.

**Comment by jinchuika** [comment]
I'm experiencing the same issue with the Spanish translation, as well as others presented in #5114 
 
![image](https://cloud.githubusercontent.com/assets/5230176/15581756/009eba8e-232b-11e6-9184-7dc1496dbea3.png)

**Comment by aronasorman** [comment]
Fixed in the PR above. Updated content packs should be available the next day.

**Comment by benjaoming** [comment]
@aronasorman please make sure to ping all the participants in this issue when content packs are built so we don't have to guess :) Thanks ;)

**Comment by rifatbd** [comment]
@aronasorman @benjaoming .....yep....the problem is fixed now
>>latest content-pack in 0.16.6.dev1 (windows 7 64bit)<<
