### ISSUE TITLE
Translated strings still showing in English

### ISSUE THREAD

**Issue by jinchuika** [learningequality/ka-lite#5114]
## Summary

Some translated strings are not being shown for Spanish (I don't know if applies to other languages). See screenshots.

Some of them still in the same way since #4650.

## Branch or installer method

 - Installer: Ubuntu 16.04 (from PPA)
 - Version: 0.16.2
 - Branch: master

#### Teach tab
The strings for _Keys_, the topic names and answer details.
![image](https://cloud.githubusercontent.com/assets/5230176/14992040/696aa0e4-1121-11e6-9583-bc079c8d528d.png)
Topic names on the Topic filters.
![image](https://cloud.githubusercontent.com/assets/5230176/14992089/95fb84b6-1121-11e6-82e0-f99c97efe4c6.png)

#### Help tooltips and popovers
Help popovers for Videos tab. [It's translated](https://crowdin.com/translate/ka-lite/28887/en-es#1986674) but still being shown in English.
![image](https://cloud.githubusercontent.com/assets/5230176/14992132/bbf8ec1c-1121-11e6-9c8f-85c2f4e2b831.png)
The same applies to the Languages Page, where the popovers [are translated](https://crowdin.com/translate/ka-lite/28887/en-es#1986668) but they still appear in English.

Regardless of the translation being displayed, the controls for the popovers are always in English.
![image](https://cloud.githubusercontent.com/assets/5230176/14992408/35762d6a-1123-11e6-8cc4-4794e956cc86.png)

#### Exercises
Whenever you ask for a hint, the button for how many hints are left appears in English.
![image](https://cloud.githubusercontent.com/assets/5230176/14992246/65528700-1122-11e6-8572-e75d477ce232.png)

Also, lots of exercises that used to appear in Spanish in version 0.15 now appear in English.

**Comment by radinamatic** [comment]
I can still replicate this with 0.16.5 on Windows 7 and Ubuntu 16.04 with the latest Spanish contentpack.
@aronasorman

**Comment by radinamatic** [comment]
![coach-report_spanish](https://cloud.githubusercontent.com/assets/1457929/15861668/511aaa44-2ccd-11e6-9e17-892a71ff1bf7.png)



![coach-report_spanish2](https://cloud.githubusercontent.com/assets/1457929/15861675/571d5bc6-2ccd-11e6-8304-fdb22188c722.png)

Check the weird values in the column `Acción`, cell `answer` in the screenshot above.

**Comment by aronasorman** [comment]
Investigating now.

**Comment by aronasorman** [comment]
For the inline docs, they're shown as translated in the Management page, but not in the VIdeos nor the Langauges page.

**Comment by aronasorman** [comment]
Aha! Looks like the problem is that we haven't triggered a "build" in CrowdIn in a while, hence why it was sending us outdated translations.

I had CrowdIn build all the langauges now, and once that's done I'll generate another content pack locally and see if that fixes the problem. I'll keep this thread updated.

**Comment by aronasorman** [comment]
I'll also add an API call to have CrowdIn build the translations before we fetch them!

**Comment by aronasorman** [comment]
![screen shot 2016-06-07 at 12 16 19](https://cloud.githubusercontent.com/assets/191955/15871495/b859f544-2ca9-11e6-8109-c66c12a01718.png)

Translated now!

However, there's still no easy way to get the "Next", "Back" and "Skip" buttons translated using our current translation system without editing the JS files directly and causing a fork. I'll push the current solution I have for now, and make a fix for the button translations once I find a good solution.
