### ISSUE TITLE
Activating lockdown causes page redirect error

### ISSUE THREAD

**Issue by Aypak** [learningequality/ka-lite#5117]
## Summary

Activating the setting LOCKDOWN = True in settings.py to prevent users from accessing exercises and videos without logging in causes a page redirect error ERR_TOO_MANY_REDIRECTS.

## Branch or installer method
 - Installer: Debian
 - Version: 0.16.5

## How to reproduce

1. Add the line LOCKDOWN = True to settings.py
2. Restart ka-lite

## Screenshots

![screenshot from 2016-05-11 17 03 28](https://cloud.githubusercontent.com/assets/7353802/15185671/8196d0e6-179a-11e6-8f6c-a6719a8c2f92.png)

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

Capturing student activity data is really important to us. When students are not supervised they sometimes watch videos or do exercises without logging in, and their progress is not recorded. This would be a good way to 'force' students to log in.

**Comment by benjaoming** [comment]
Hi @Aypak - I agree with your description and it's easy to recreate.

Luckily it was also easy to fix!

If you want to test it, feel free, otherwise we're closing this issue as soon as the PR is merged.

**Comment by Aypak** [comment]
Thanks @benjaoming ! I will confirm as soon as I test

**Comment by benjaoming** [comment]
Fixed in #5150 and merged to have it in 0.16.6. Thanks for the help @Aypak !

**Comment by kenny55d** [comment]
Please did anyone get a chance to test this? I have just tested it on my system (RPi3 with 0.16.6post1) but I am unable to login when _LOCKDOWN=True_, I get the login prompt but nothing happens when I select login; Is anyone getting the same or is it just me?

**Comment by kenny55d** [comment]
![selection_002](https://cloud.githubusercontent.com/assets/17641005/16744569/a09a28f0-47a9-11e6-8ceb-0b86ecbf4ddd.jpg)

When I select login, I get the following output in the terminal despite the fact that the same user can login when LOCKDOWN is disabled but with LOCKDOWN enabled, permission is denied:

![selection_003](https://cloud.githubusercontent.com/assets/17641005/16744773/8c6bfce0-47aa-11e6-93a2-64276cb9dd7d.jpg)

**Comment by Aypak** [comment]
Hi @kenny55d , I have just tested and get the same result as above. @benjaoming, I'm sorry I didn't test this much sooner.  My hunch is that the url "/securesync/api/user/login" is not whitelisted when lockdown is activated

**Comment by kenny55d** [comment]
@Aypak Just tested the change you made and it appears to have fixed the login issue. Thanks.
