### ISSUE TITLE
How to access KALite website without port in Ubuntu 14.04

### ISSUE THREAD

**Issue by Revathikul** [learningequality/ka-lite#5122]
## Summary

How to access KALite website without mentioning port in Ubuntu 14.04

Currently i used ubuntu ppa to install the KA-Lite and it work very well

It works well with http://10.0.0.1:8008,

But i want to somehow make it work just with the http://10.0.0.1 without mentioning the port, any help will be greatly appreciated

**Comment by benjaoming** [comment]
Hi @Revathikul - I would recommend installing the `ka-lite-raspberry-pi` package from our PPA:

https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite

After installing it, edit `/etc/nginx/sites-available/kalite.conf` and change `listen 8000;` to `listen 80 default_server;`.

You should then disable the default server by doing `sudo rm /etc/nginx/sites-enabled/default` and the `sudo service nginx reload` to make changes take effect.
