### ISSUE TITLE
Captions do not appear in Epiphany on a Raspberry Pi

### ISSUE THREAD

**Issue by richsegal** [learningequality/ka-lite#5125]
## Summary

Captions do not appear in Epiphany on a Raspberry Pi.
## Branch or installer method
- Installer: pip install ka-lite-static
- Version: 0.16.5 (?)
## Traceback or relevant snippet from server.log

n/a
## How to reproduce
1. Boot Raspbian 2016-05-10
2. Install ka-lite: sudo pip install ka-lite-static
3. Start ka-lite: sudo kalite start
4. Login to KA-Lite using the url http://localhost:8008/
5. Download a language pack with captions (eg. french)
6. Download a video with captions
7. Run a video scan to get captions to be recognized
8. Play the downloaded video
9. Use the CC button on the bottom of the player to enable captions
10.  At this point captions should appear but do not

I reproduced the above using the video Science / Physics / One Dimensional Motion / Displacement, velocity, and Time / Intro to vectors & scalars 
## Screenshots

n/a
## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

We have reverted to KA-Lite 0.15.x for Powering Potential deployments as English language captions are critical for non-native English speakers.  We cannot upgrade to the 0.16.x stream until this is fixed.

**Comment by j-schwartz** [comment]
@richsegal are you seeing captions on other browsers?  I'm not getting English captions at all, despite the admin page saying they are downloaded.

**Comment by richsegal** [comment]
I am not seeing subtitles for English in the admin page when I follow the instructions above.   For English I see the status listed as 100% translated, 0 subtitles.   The KA-Lite UI does not allow you to easily download English subtitles.   I can manually download English subtitles using the command:

`sudo kalite manage retrievecontentpack download en`

After I run the above command and do a video scan, the admin page lists the status of English as 0% translated and 5951 subtitles.  I can then go and view a video with English subtitles from a remote computer and it works fine. I have verified that English subtitles work with the above procedure with both Safari and Firefox on OSX.   However, as described above, subtitles cannot be viewed on the Raspberry Pi itself.

**Comment by j-schwartz** [comment]
@benjaoming - subtitle thread here. Thank you!

**Comment by benjaoming** [comment]
Thanks, self-assigning :D

**Comment by j-schwartz** [comment]
@benjaoming do you know where in a linux install the subtitles are stored?  not seeing them on first glance here.  They are .vtt not .srt now right?

**Comment by benjaoming** [comment]
Hi @j-schwartz , I'll investigate tomorrow when I'm with my beloved test device again!

**Comment by benjaoming** [comment]
Don't worry about investigating this further, I'm sure it's a legit issue, just gotta sit in front of Epihany and all that and then I'll figure out what to do from there :)

**Comment by benjaoming** [comment]
Step 1: Confirmed! Above mentioned video `http://127.0.0.1:8008/learn/khan/science/physics/one-dimensional-motion/displacement-velocity-time/introduction-to-vectors-and-scalars/` plays with subtitles in Firefox, but not in Epiphany on Raspbian Jessie.

**Comment by benjaoming** [comment]
Javascript error in Epiphany is the following:

```
** Message: console message: http://localhost:8008/static/js/distributed/bundles/bundle_video.js @19: TypeError: undefined is not a constructor (evaluating 'new(l.vttjs.VTTCue||l.window.VTTCue)(0,0,"")')
```

@rtibbles you can install Epiphany like this:

    sudo apt-get install epiphany-browser epiphany-browser-dbg

The error is reproducable on Ubuntu 14.04. But it doesn't for some reason install into the launcher area, so launch it from the console.

    EPHY_ENABLE_INSPECTOR=true epiphany

After that, right-click somewhere and choose "Inspect element" to start the inspector.

Could the solution be to switch to http://captionatorjs.com/ ?

**Comment by benjaoming** [comment]
Tried latest video.js, 5.10.4, same result.

**Comment by JMNB** [comment]
Today I managed to run KA Lite including subtitles on a RaspberryPI 2B.

NOOBS version: V2_0_0
KA Lite version: 0.16
Iceweasel/Firefox version: 45.4.0

**Comment by benjaoming** [comment]
Thanks for testing @JMNB  - It's definitely the older version of Epiphany that's to blame, but I don't anyone is going to try to fix it... could happen by accident if we upgrade video.js and they have the problem sorted upstream.

**Comment by benjaoming** [comment]
Updates and of video.js and vtt.js have occurred in the latest release available via  `pip install ka-lite-static --pre`. Please feel invited to test :)

**Comment by JMNB** [comment]
Dear Benjamin, good morning, 

For testing I installed the new version of KA-Lite in a RaspberryPI and did the test with the languages and subtitles. It still does not work.

But I am not sure if I did the installation correct. Where is the location of those two files on the RaspberyPI so I check?

BY the way subtitles and CC is also functioning the Chromium webbrowser, which is included in Raspbian.

Kind regards, 

Julia Nolles

**Comment by benjaoming** [comment]
@JMNB thanks for testing! video.js and vtt.js aren't files - they are names of javascript libraries used to show subtitles.

Did you do a clean install or upgrade?

If you have upgraded an existing installation, you might have to do `kalite manage setup`, not sure if it's run automatically with the `pip install` method.

**Comment by benjaoming** [comment]
@JMNB oh, by the way yes, everything hopefully works in Chromium, it's the new default browser in the latest Raspbian.

**Comment by benjaoming** [comment]
I don't think we'll be able to troubleshoot this any further. Ultimately, it's a problem with vtt.js or Epiphany.

The solution for now, is to use a new version of Raspbian or install another browser (e.g. Firefox or Chromium) on the older Raspbian.

**Comment by benjaoming** [comment]
Btw thanks for reporting and please feel invited to report any other issues any other time :)
