### ISSUE TITLE
Move user data to new 16.5 installation

### ISSUE THREAD

**Issue by waltonrp** [learningequality/ka-lite#5128]
## Summary

I need to move user data from KALITE 13.2 to 16.5 server. Can anyone point me to or provide instructions?

## Branch or installer method

Debian/Ubuntu

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

I have 10+ KALITE servers running v 13.2, I want replace them with v 16.5. Upgrade is not practical. I'll image a new hard drive and replace that out in the server. I'd like to avoid having users lose data.

**Comment by waltonrp** [comment]
I think I resolved my issue.

I read this:>>>>
Backing up data: is there any easy way to do it locally?
Yes! Just copy the file

ka-lite/kalite/database/data.sqlite
to a secure location. To restore, simply copy the backup data file to the same location. If you have changed versions, please run
python kalite/manage.py migrate --merge
to guarantee your database is compatible with the current version of KA Lite you have installed!<<<<<

Since I can't find the manage.py file (It no longer exists in current version?), I ran this:
kalite restart

This is on test servers, but it appears that the new db was upgraded and merged.....

**Comment by benjaoming** [comment]
@waltonrp your previous 0.13 installation must be a copy of the Git repository? I think you could try just stopping KA Lite, upgrading the repo and running `bin/kalite start`.

Make sure to backup stuff beforehand!

p.s. prepare that no videos or exercises can be reused -- most of the content is replaced, so you need to download new videos and exercises. I would recommend just deleting everything that you have already downloaded and re-fetching it.

**Comment by waltonrp** [comment]
Thanks. See my post. Did just about as you say. I've got a new set of vids so okay in that dept. 

Robert Walton
Regional Information Technology Specialist
DOC – CTSU – Field Services Unit

**Comment by benjaoming** [comment]
> Since I can't find the manage.py file (It no longer exists in current version?)

Correct, we removed that one! `bin/kalite start/stop/restart` automatically detects if the database should be upgraded.

**Comment by benjaoming** [comment]
Funny/unlucky that you replied+closed at the same time that I responded :)
