### ISSUE TITLE
Questions are not completelly  loaded

### ISSUE THREAD

**Issue by PASTJL** [learningequality/ka-lite#5129]
## Summary

KA Lite on my desktop Windows 10. Questions are incompletely loaded, missing JPG images

## Branch or installer method

Installed from the Windows executable KALiteSetup-0.16.5.exe

 - Installer: Windows/
 - Version: 0.16.5 with fr translation
I ran succefully
kalite manage retrievecontentpack local fr fr.zip

## Traceback or relevant snippet from server.log
server.log no error tracked

With mozilla Inspector i got 2 HTT404 as shown below
GET http://localhost:8008/content/assessment/khan/6e6/6e68574abb61d2b4a12644d777006fcfa8a73cff.png [HTTP/1.1 404 Not Found 3 ms]
GET http://localhost:8008/content/assessment/khan/f7e/f7ee2b71e450c5867e6721d1e1a2f2301eaa4f46.jpg [HTTP/1.1 404 Not Found 2 ms]

When looking in **content/assessment/khan folder, it is empty,** so the 404 http error
How i can retrieve these JPG files ?

## How to reproduce

See the screen shots in joined pdf

It seems like the issue #5119 

[KALiteBug.pdf](https://github.com/learningequality/ka-lite/files/293961/KALiteBug.pdf)

**Comment by PASTJL** [comment]
Perhaps found the solution for this issue.
I got the khan folder in en.zip and put it in content/assessment/ and all seems to work.
Can you validate this workaround ?
I doen't close the issue, if you validate the workaround, you can close by yourself

**Comment by benjaoming** [comment]
Interesting @PASTJL, and thanks for taking the time to write good feedback!

To summarize from your solution: The French content pack is missing assessment items that are in the English?

@aronasorman will soon be addressing issues with the content packs, so I'm assigning him for now,

**Comment by PASTJL** [comment]
For your question, you are right, in fr.zip no "khan" folder.

**Comment by rtibbles** [comment]
This is intentional - the built assets are too big to distribute with *every* language pack, so we include them in English which should be bundled by default with all full installers.

**Comment by PASTJL** [comment]
Ok.
But i certainly miss something when installing KA Lite because my folder assessment/khan was empty.
Must i run the two commands below :
kalite manage retrievecontentpack local en en.zip
kalite manage retrievecontentpack local fr fr.zip
?

**Comment by rtibbles** [comment]
Hrm - seems like something is going wrong with the correct placement of the english language pack during install then!
Yes, running those two commands *should* produce the result you want.

@cpauya Can you check out if this is an issue with the Windows installer in particular?

**Comment by benjaoming** [comment]
It sounds like a problem with how system-wide folders *are assumed to be* intermixed with user directories. If the English content packs are placed in a system-wide location, but the user installed content packs depend on them, the mere existence of a user folder will shadow out all static content items from the system-wide location as it was originally designed... I can check this tomorrow.

**Comment by cpauya** [comment]
Copy, we will help check this out today.

**Comment by djallado** [comment]
I can't replicate this using `KALiteSetup-0.16.5.exe` from [pantry](http://pantry.learningequality.org/downloads/ka-lite/0.16/installers/windows/) using Windows 10.
Here's my screenshot:
![screen shot question win10](https://cloud.githubusercontent.com/assets/8664071/15748068/fd74df24-290f-11e6-8f10-abbd14887d7b.png)

`.kalite/content/assessment/khan` is not empty, Here's the screenshot: 
![screen shot khan win10](https://cloud.githubusercontent.com/assets/8664071/15748099/1875ad26-2910-11e6-8f3b-7907d1ce9648.png)

On IE11 Windows7.
Here's my screenshot:
![screen shot question1](https://cloud.githubusercontent.com/assets/8664071/15741237/5f68cf6c-28eb-11e6-9f7a-ec72fce54e1c.png)

`.kalite/content/assessment/khan` is not empty, Here's the screenshot: 
![screen shot questionkhan](https://cloud.githubusercontent.com/assets/8664071/15741471/7cb9effa-28ec-11e6-9ff2-089863f8d395.png)

I'll continue testing this tomorrow using build from dungeon.

**Comment by radinamatic** [comment]
I don't have Win10, but retested this on fresh 0.16.5 version on Win8 (the next closest thing to Win8), and could not replicate with French contentpack installed locally:

![ie11 - win8 1 0 16 5 running - oracle vm virtualbox_453](https://cloud.githubusercontent.com/assets/1457929/15751157/5e538a1a-28e9-11e6-86f5-3430ba5d5480.png)

It could have, as @benjaoming noted, something to do with user installing the local contentpack...
@PASTJL could you try downloading and installing a contentpack for another language but **make sure that you are logged in as the same user** that installed KA Lite?

**Comment by benjaoming** [comment]
@radinamatic 's suggestion sounds like something worth investigating!

**Comment by amodia** [comment]
I can't also reproduce this on win10 using KALiteSetup-0.16.5 installer and fr language downloaded from pantry.

![screen shot 2016-06-03 at 4 43 44 pm](https://cloud.githubusercontent.com/assets/8663934/15775179/1259f19c-29b3-11e6-8326-086356d55658.png)

**Comment by djallado** [comment]
I can replicate it on `windows 10` by creating new user account in my machine. I logged in that new account and download `fr` language and then visit some exercise.  

Here's the screenshot:
![screen shot issue](https://cloud.githubusercontent.com/assets/8664071/15782167/ccf816dc-29db-11e6-9291-471e1e68af35.png)

**Comment by amodia** [comment]
@benjaoming & @radinamatic  I can also reproduce this issue with @djallado comments above.

![screen shot 2016-06-03 at 10 27 11 pm](https://cloud.githubusercontent.com/assets/8663934/15781967/074d3868-29db-11e6-80cf-467f44c4a29e.png)

**Comment by radinamatic** [comment]
@amodia @djallado

Just to be sure that I understood correctly the scenario where you managed to replicate this: 

1. You installed KA Lite as User A.
2. Created an User B, logged in and installed a new contentpack for non-English language.

If this is a case, we may have to amend the docs and stress the requirement that **contentpacks MUST be installed by the same user as the base installation**.

**Comment by PASTJL** [comment]
I am the original poster. On my desktop there is only a user with administrator profile.But you have found another issue!
On my desktop, i have 2 versions of Python ( 3.5 and 2.7), i suspect a mismatch because i have not set the variable KALITE_PYTHON  in system variable, i have set it only in kalite.bat. Perhaps it is not correctly inherited.
For my issue, i think you can close it.

**Comment by djallado** [comment]
That's exactly what we did @radinamatic to replicate the issue. We will update the docs then.

**Comment by benjaoming** [comment]
@djallado thanks! sounds like a documentation fix is the way to go.

You could potentially mirror the system-wide installation location of the Debian installer, but it might not be easy to achieve on windows with all sorts of permission issues lurking.

Here's a suggestion, please adjust :)

```
.. warning::
    KA Lite runs in **user spacer**. That means, if install while you're logged in as ``User A`` then you cannot use KA Lite as ``User B`` because all downloaded contents and videos will exist only for ``User A``.
```

**Comment by benjaoming** [comment]
Closing this as we now have a warning about installing and using KA Lite on different user accounts, seems like the best solution at present.
