### ISSUE TITLE
The answer box is not present to enter the correct answer.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/ka-lite#5131]
## Summary
The answer box is not available to enter the correct answer. 
The check answer button works even when the learner has not entered any answer and proceeds to the next question. 

Math > Pre-algebra> Apply mathematical reasoning> Constructing numeric expressions> Evaluate expressions with parentheses

**Note:
Same problem exists in the http://demo.learningequality.org/ also.**

## Branch or installer method

OS: Ubuntu version 14.04 LTS
Installer: "pip install ka-lite" and "sudo kalite manage setup"
Version: 0.16.5
assessment file: en.zip

## How to reproduce

1. Math > Pre-algebra> Apply mathematical reasoning> Constructing numeric expressions> Evaluate expressions with parentheses  
2. Observe that there is no place where we can enter the correct answer.
3. Click on the check answer.
4. Observe that the quesion proccessed to next question even without entering any response. 

## Screenshots
![photo_20160603_193636](https://cloud.githubusercontent.com/assets/13453618/15781370/6661baee-29c3-11e6-9c7f-2d6540232090.jpg)
![photo_20160603_193650](https://cloud.githubusercontent.com/assets/13453618/15781369/6661abc6-29c3-11e6-8215-4eac247b5a48.jpg)
![photo_20160603_193701](https://cloud.githubusercontent.com/assets/13453618/15781368/6661101c-29c3-11e6-9ab1-10c8e5d4eddc.jpg)
![photo_20160603_193737](https://cloud.githubusercontent.com/assets/13453618/15781367/665f6e9c-29c3-11e6-88b8-63c42e673d53.jpg)

**Comment by radinamatic** [comment]
@harishbalachandran Thank you for reporting this!

I can confirm on both demo server as a registered user, and on local Windows 7 installation as Learner user, but with differences in console errors: none in local, but `ReferenceError: Calculator is not defined` on demo server.

(screenshots coming)

**Comment by benjaoming** [comment]
@aronasorman confirming it doesn't work with the latest test build of the english content pack.

**Comment by benjaoming** [comment]
Possibly related: #5154

**Comment by aronasorman** [comment]
@rtibbles Here's the data for the offending exercise:
```
{
    "answerArea": {
        "calculator": false,
        "options": {
            "answerType": "number",
            "inexact": false,
            "maxError": 0.1,
            "simplify": "required",
            "size": "normal",
            "value": "42"
        },
        "type": "input-number"
    },
    "hints": [
        {
            "content": "This expression can be evaluated in two different ways: using the order of operations or using the distributive property.",
            "images": {},
            "widgets": {}
        },
        {
            "content": "Solving this problem using the order of operations, we start with the parentheses: \u00a0$(5 + 9) = 14$.",
            "images": {},
            "widgets": {}
        },
        {
            "content": "Replacing $5 + 9$ with $14$ gives us $3\\times(14)$, or $3 \\times 14$.",
            "images": {},
            "widgets": {}
        },
        {
            "content": "$\\qquad 3 \\times 14=42$",
            "images": {},
            "widgets": {}
        },
        {
            "content": "Solving this problem using the distributive property, we consider that we have three of everything inside the parentheses since we are multiplying by $3$. That means we have three $5$s and three $9$s.\n\n$\\qquad\\begin{align}&\\quad3\\times(5+9)\\\\\n&=3\\times5 + 3\\times9\\\\\n&=15 +27\\\\\n&=42\n\\end{align}$",
            "images": {},
            "widgets": {}
        },
        {
            "content": "Notice that both methods give us the same result of $42$.",
            "images": {},
            "widgets": {}
        }
    ],
    "itemDataVersion": {
        "major": 0,
        "minor": 1
    },
    "question": {
        "content": "**Evaluate the expression $3\\times(5 + 9)$.**",
        "images": {},
        "widgets": {}
    }
}
```

On my side there seems to be a bunch of exercises not loading their textboxes:

- http://127.0.0.1:8008/learn/khan/humanities/us-history/road-to-revolution/declaration-of-independence/aspen-us-declaration-of-independence-quiz/
- http://127.0.0.1:8008/learn/khan/humanities/us-history/road-to-revolution/benjamin-franklin/benjamin-franklin-quiz/
- http://127.0.0.1:8008/learn/khan/humanities/art-history-basics/artists-materials-techniques/materials-techniques-quiz/art-history-media/

Here's an exercise that's properly loading the textbox:
```
{
    "answerArea": {
        "calculator": false,
        "chi2Table": false,
        "periodicTable": false,
        "tTable": false,
        "zTable": false
    },
    "hints": [
        {
            "content": "![](web+graphie:/content/assessment/khan/004/0041a87d6104cbbdb130f3b63baf4b57523e5acd)",
            "images": {
                "web+graphie:/content/assessment/khan/004/0041a87d6104cbbdb130f3b63baf4b57523e5acd": {
                    "height": 180,
                    "width": 60
                }
            },
            "replace": true,
            "widgets": {}
        },
        {
            "content": "![](web+graphie:/content/assessment/khan/004/0041a87d6104cbbdb130f3b63baf4b57523e5acd)![](web+graphie:/content/assessment/khan/0cb/0cbdb6630c9c10d70c463acc811eb748bc2cd0ca)",
            "images": {
                "web+graphie:/content/assessment/khan/004/0041a87d6104cbbdb130f3b63baf4b57523e5acd": {
                    "height": 180,
                    "width": 60
                },
                "web+graphie:/content/assessment/khan/0cb/0cbdb6630c9c10d70c463acc811eb748bc2cd0ca": {
                    "height": 150,
                    "width": 60
                }
            },
            "replace": true,
            "widgets": {}
        },
        {
            "content": "There are $\\blue{3}$ blue dots. There is $\\green{2}$ green dots.",
            "images": {},
            "replace": false,
            "widgets": {}
        },
        {
            "content": "There are a total of $5$ dots.",
            "images": {},
            "replace": false,
            "widgets": {}
        }
    ],
    "itemDataVersion": {
        "major": 0,
        "minor": 1
    },
    "question": {
        "content": "![](web+graphie:/content/assessment/khan/d59/d5916b4b435a03824b1677236bf2a9e0798696ca)\n\n[[\u2603 numeric-input 1]]",
        "images": {
            "web+graphie:/content/assessment/khan/d59/d5916b4b435a03824b1677236bf2a9e0798696ca": {
                "height": 80,
                "width": 480
            }
        },
        "widgets": {
            "numeric-input 1": {
                "alignment": "default",
                "graded": true,
                "id": "numeric-input 1",
                "options": {
                    "answers": [
                        {
                            "maxError": 0,
                            "message": "",
                            "simplify": true,
                            "status": "correct",
                            "strict": false,
                            "value": 5
                        }
                    ],
                    "coefficient": false,
                    "labelText": "",
                    "size": "normal",
                    "static": false
                },
                "static": false,
                "type": "numeric-input",
                "version": {
                    "major": 0,
                    "minor": 0
                }
            }
        }
    }
}
```

My gut feeling here is that numeric input in general seems to be working, possibly because it's bundling the widget attribute with the appropriate data, while the widget attribute is suspiciously empty in the non-working exercise.

@rtibbles What's your sense on this? Do we do any processing whatsoever on `item_data`, and is any information possibly getting filtered out?

**Comment by aronasorman** [comment]
I've tested a locally built content pack and most of the problem questions seem to be gone now! However, there still are a few questions that don't show answer areas. This time, they seem to be focused on True/False questions. Here's an example I found:

http://127.0.0.1:8008/learn/khan/humanities/us-history/road-to-revolution/declaration-of-independence/aspen-us-declaration-of-independence-quiz/
