### ISSUE TITLE
picture not displaying

### ISSUE THREAD

**Issue by harishgangwar** [learningequality/ka-lite#5140]
Pictures are not displaying while doing the math geometry exercise. 
Version : Kalite 0.16
OS : Window XP
Browser : Chrome , Firefox

![ka1](https://cloud.githubusercontent.com/assets/19798337/15856915/2711a244-2cd6-11e6-8787-39af01d0f40d.JPG)
![ka2](https://cloud.githubusercontent.com/assets/19798337/15856926/2e8cd3c2-2cd6-11e6-8a65-73b28fa4543e.JPG)

**Comment by radinamatic** [comment]
On Windows 7 & 0.16.5, image displays correctly, will confirm asap if I can replicate on XP.

**Comment by harishgangwar** [comment]
I am facing same issues with other exercises too. I inspected one more exercise in chrome and noted that svg file has been called and opening properly in new tab. It  seems there is some issue in fetching the svg files in kalite. 
 
![ka3](https://cloud.githubusercontent.com/assets/19798337/15930778/5663e8de-2e72-11e6-906e-714d42d64a42.JPG)

**Comment by benjaoming** [comment]
@harishgangwar thanks for another great detailed issue report! Are you using the new content pack that @aronasorman uploaded?

**Comment by benjaoming** [comment]
@harishgangwar 

I'm not able to reproduce this with the latest 0.16.6 alpha, but it looks from your screen shots like this should work. When you say:

> It seems there is some issue in fetching the svg files in kalite. 

...what do you mean exactly? Because it does a "200 OK" so your browser receives the SVG file. However, I see there is "text/html" in the content-type header, and when I make this request to my local Ubuntu-based ka-lite server, I receive "image/svg+xml". I'm wondering if cherrypy (the HTTP server bundled into KA Lite) uses the host system to resolve the content type and create the header.

**Comment by harishgangwar** [comment]
@benjaoming  I used chrome , Safari and mozilla browser for same exercise but picture could not be displayed in any of browser. I am having the assessment zip file bundled with content pack available on http://ka-lite.readthedocs.io/en/latest/installguide/install_all.html.  
The file is there in 'inspect window' but somehow not displaying.

**Comment by benjaoming** [comment]
@harishgangwar is it possible for you to install KA Lite on a non-xp device and then connect to it from the affected Windows XP browser?

That way, we can see if it's something related to HTTP content type headers and if running the KA Lite server on a different device fixes it...

**Comment by harishgangwar** [comment]
I tried Ka-lite-0.16.6.post1 on win 7 , 64 bit , with browser chrome , but still facing the same problem where images in question are not being displayed. In inspection window the content type is text/html. 

@radinamatic , which browser did you use in window 7 for replicating this issue ? 

@benjaoming I am not having any non-xp device and hence can not did what you suggested above but arranging a raspberry soon.  Do i need to install some specific application / extensin/plugin  for SVG files.

**Comment by radinamatic** [comment]
@harishgangwar The above screenshot is from the test performed in Firefox, but the result was the same in Chrome and IE11. I'll re-run the test on that VM and see what is the SVG association, just to be sure...

**Comment by harishgangwar** [comment]
@benjaoming Adding two more snapshots for same exercise

Kalite is accessed from a Win XP device using Chrome browser 
case 1: KALite installation is on Raspberry device. **The SVG image  type is  svg/xml**
![rasp](https://cloud.githubusercontent.com/assets/19798337/16712467/23396cf8-46a6-11e6-816f-20fcb933b97b.JPG)

case 2: KALite installation is on Win-XP device. **The SVG image type is text/html.** 
![xp](https://cloud.githubusercontent.com/assets/19798337/16712468/2955930a-46a6-11e6-9266-080bbdbc07a6.JPG)

**Comment by benjaoming** [comment]
Please test and make noise in case the above PR did not fix the issue... the description made it very likely that the fix applied should work because cherrypy relies on the host system's know MIME types.

**Comment by benjaoming** [comment]
@harishgangwar can you check if the latest beta solved your issues?

**Comment by harishgangwar** [comment]
@benjaoming Yes , with 0.16.7 , the issue has been resolved. Thanks
