### ISSUE TITLE
Cannot see spanish videos in topic tree

### ISSUE THREAD

**Issue by elvistek** [learningequality/ka-lite#5141]
## Summary

I have been installing KA lite on RPi 3s for deployment in different parts of Latin America through the [Muskoka Foundation](www.dogoodasyougo.org). I have downloaded the latest version of ka lite unto a raspberry pi 3 and finished all the setup. I downloaded spanish videos in bulk and transferred them to the CONTENT folder. Logged into KA lite, MANAGE and scan for videos but it did not sure any videos in the tree as the circles are still grey. 

Also tried from LXTerminal with 
`kalite manage videoscan -les` and received error messages

## Branch or installer method

*Please specify if you are using the current `develop` branch or which installation source you were using when the issue occurred.*

 - Installer: Debian on Raspberry pi 3
 - Version: 0.16.5

## Traceback or relevant snippet from server.log

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## Screenshots
![captura de pantalla 2016-06-07 a la s 5 43 07 p m](https://cloud.githubusercontent.com/assets/18245124/15877543/1baf9ef2-2cda-11e6-9527-6349a13ad44d.png)

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

I am not able to access videos so that will be impossible to use the program in the communities here.

**Comment by benjaoming** [comment]
Hi @elvistek !

I've tried to reproduce this without any immediate luck.

You may be missing the Spanish content pack. Could you either try to Download it through the Manage > Languages tab or through command line:

    kalite manage retrievecontentpack download es

**Comment by elvistek** [comment]
Hi @benjaoming 

Thank you. This code in command line worked. 

I had tried downloading it through Manage>Languages tab and it completed but  it looks like for some reason not all the files might have been downloaded.

**Comment by benjaoming** [comment]
Thanks @elvistek for giving feedback, and please feel welcome to open up an issue anytime you find something suspicious in KA Lite :)

Btw downloading content packs has two steps that both take time: 1. downloading (for obvious reasons) and 2. unpacking, loading in the new database and iterating new video contents

There are numerous changes to Khan Academy upstream data between releases of KA Lite, and many existing videos change, either that their ID is changed or the video itself is changed.. both such changes requires downloading the videos again unfortunately.

**Comment by tim-moody** [comment]
using 0.17 kalite manage videoscan --language=es worked for me.
