### ISSUE TITLE
install ubuntu 32 bits

### ISSUE THREAD

**Issue by johnfelipe** [learningequality/ka-lite#5147]
Please give me instructions for installation in ubuntu 32 bits with git clone method
Tnks
Stay alert

**Comment by quozl** [comment]
The instructions that helped me were a combination of two pages;
* https://github.com/learningequality/ka-lite/wiki/Getting-started (dated 25 March 2016), and;
* http://ka-lite.readthedocs.io/en/0.16.x/developer_docs/environment.html#development-environment (dated 2015).

**Comment by benjaoming** [comment]
Dear @johnfelipe 

Please don't use the `git clone` method if you can avoid it.

32 bits is irrelevant, none of the code is compiled.

There is a guide you can follow for Ubuntu here: http://ka-lite.readthedocs.io/en/latest/installguide/install_all.html#linux

Closing this, as it isn't a problem report but a support request.
