### ISSUE TITLE
error downloading videos web interface 0.16 ubuntu 64 bits

### ISSUE THREAD

**Issue by johnfelipe** [learningequality/ka-lite#5148]
![kalite1](https://cloud.githubusercontent.com/assets/428820/15983457/0c902bda-2f6e-11e6-8357-3535b9b810ad.png)

![kalite2](https://cloud.githubusercontent.com/assets/428820/15983456/0c7d58de-2f6e-11e6-94f6-3b9f6c880b1d.png)

How can i solve this

**Comment by benjaoming** [comment]
Hi @johnfelipe 

You haven't filled in any details from the original issue template so we cannot help you. It's a problem that we don't give a lot of feedback regarding download errors #4907 #5123 #3310 

If you state precisely what you're doing and which version / operating system you're using and that you're confident the network connection works, it's easier.

Your problem looks a bit like #5126 which is solved and will be released in 0.16.6 - so if you wait a few days, we can help you.

**Comment by johnfelipe** [comment]
when release it and how update it?

**Comment by johnfelipe** [comment]
any advance for 0.16.6?

**Comment by j-schwartz** [comment]
@johnfelipe 0.16.6 is out if you want to test this now

**Comment by johnfelipe** [comment]
is not there
http://pantry.learningequality.org/downloads/ka-lite/0.16/installers/debian/ka-lite-bundle_0.16.6.deb

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-06-16 15:40 GMT-05:00 Jeremy Schwartz <notifications@github.com>:

**Comment by johnfelipe** [comment]
http://ka-lite.readthedocs.io/en/0.16.x/installguide/install_all.html#linux

Is not good referred

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-06-16 15:40 GMT-05:00 Jeremy Schwartz <notifications@github.com>:
