### ISSUE TITLE
Learner stats: Wrong login count and session tracking

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#5157]
## Summary

Received the following report:

> After running the same tests as I had in IE, Chrome appears to be having the same issues, including no Student/Coach/Group Login and Login Times being recorded.

> Below is a screenshot showing that students who have watched videos and completed exercises still do not have a Login of Login Time.

![image001](https://cloud.githubusercontent.com/assets/374612/16011936/9fe2c490-3187-11e6-92bd-268de36ceaf6.png)

I can confirm this, using our latest 0.16.x branch and a clean installation.

## Branch or installer method

 - Branch: 0.16.x

## How to reproduce

1. Create a learner account
1. Login
1. Solve exercise
1. Login as manager
1. Go to facility
1. See that there is no login count for the learner.

**Comment by jamalex** [comment]
:+1: on this, from a report from Liberia today; this probably shouldn't hold back the 0.16.6 release (since that's coming tomorrow), but is an important bug to address soon.

**Comment by j-schwartz** [comment]
Hey @benjaoming - I know we lose you soon, if we haven't already.  Just curious if you think you'll be able to attack this prior to taking off.  Any idea?

**Comment by radinamatic** [comment]
@j-schwartz, we lost @benjaoming already, at least until the end of the month... :stuck_out_tongue: 

#5180 has already been merged, so you can check out the repo directly, try the 0.16.7 debian pre-release on PPA, or the latest Win build in Dungeon!

**Comment by benjaoming** [comment]
@j-schwartz -- this will be included in 0.16.7 as the PR is already merged, shall close this issue now :)

**Comment by j-schwartz** [comment]
Fantastic, many thanks Ben
