### ISSUE TITLE
OSX installer link on website links to Windows installer

### ISSUE THREAD

**Issue by josephclawrence** [learningequality/ka-lite#5161]
## Summary

The link to the OSX installer on this page: http://ka-lite.readthedocs.io/en/0.16.x/installguide/install_all.html#installation links to the Windows installer, so I cannot get the OSX installer anywhere

## Branch or installer method

 - Installer:OSX

**Comment by cpauya** [comment]
Hi @josephclawrence - so sorry about this.  We will fix this ASAP.  The OS X installer URL at https://learningequality.org/r/osx-installer-0-16

Just noticed that even the link to the Ubuntu/Debian and Raspberry Pi installers points to the Windows installer too.  Hope @benjaoming can help to update the links?

Thanks for the report.

**Comment by cpauya** [comment]
This is now fixed.
