### ISSUE TITLE
KALITE_HOME env and syspath missing when ka-lite is deployed using Apache on Ubuntu. 

### ISSUE THREAD

**Issue by clvx** [learningequality/ka-lite#5195]
## Summary

According to this [tutorial](http://ka-lite.readthedocs.io/en/0.16.x/installguide/advanced.html) you can serve ka-lite using apache instead of ka-lite webserver; however, kalite/project/wsgi.conf doesn't set all the environment variables as expected. 

1.  `KALITE_HOME` is needed on [kalite/project/settings/default.py](https://github.com/learningequality/ka-lite/blob/master/kalite/project/settings/default.py#L3),  but it's not set anywhere, not even in [kalite/project/wsgi.py](https://github.com/learningequality/ka-lite/blob/master/kalite/project/wsgi.py#L27). 

2. At least on Ubuntu the sys.path is not completely defined with all the paths to run the project. For instance, securesync is needed in [kalite/settings/base.py](https://github.com/learningequality/ka-lite/blob/master/kalite/settings/base.py#L543) but the package is not in the sys.path defined in [kalite/project/wsgi.py](https://github.com/learningequality/ka-lite/blob/master/kalite/project/wsgi.py#L18) which is `/usr/local/lib/python2.7/dist-packages/`, but it's in `/usr/share/kalite/python-packages/`. 

## Branch or installer method

 - Installer: pip install ka-lite
 - Version: ka-lite==0.16.7b1
 - OS: Ubuntu 12.04 Precise

## How to reproduce

if you want to reproduce this error, just follow the [advanced installation tutorial](http://ka-lite.readthedocs.io/en/0.16.x/installguide/advanced.html)

--------------------------
I can't deploy using the kalite cli program because of business policies, but neither I want to modify or add my own wsgi.py config because any update/upgrade might break my installation.

> One  thing I find odd is that using the kalite cli program all the env variables and sys.path are configured correctly. I assume the kalite program has its own configuration settings which are not part of the django kalite project structure.

I've been digging in this issue, and I found kalitectl.py is located in `/usr/share/kalite/`, so when it's called the [sys.path](https://github.com/learningequality/ka-lite/blob/master/kalitectl.py#L79) is updated with its current location. 

So, a workaround to fix the sys.path is to add `/usr/share/kalite` in wsgy.py sys.path definition.  and to fix `KALITE_HOME` env is to add  `os.environ.setdefault("KALITE_HOME", os.path.join(os.path.expanduser("~"), ".kalite"))` in `wsgy.py`.

**Comment by benjaoming** [comment]
AFAIK mod_wsgi does not support setting env vars in the Apache config like Nginx+UWSGI does. So you would have to create your own wsgi.py. It isn't hard, just copy the existing one.

Some ideas could perhaps be taken from this tutorial: https://gist.github.com/GrahamDumpleton/b380652b768e81a7f60c

I agree with this addition for wsgi.py:

    os.environ.setdefault("KALITE_HOME", os.path.join(os.path.expanduser("~"), ".kalite"))

But hard-coding `/usr/share/kalite` would be problematic when installing in virtual envs.

**Comment by benjaoming** [comment]
Fixed in #5217
