### ISSUE TITLE
Scanning videos from bulk downloaded videos

### ISSUE THREAD

**Issue by rajnikumbh** [learningequality/ka-lite#5196]
## Summary

Trying to scan 36 GB of videos downloaded through torrent on KA Lite 0.16.5 but it is stuck at "Scanning for videos started" and nothing really happens even after waiting for hours. I did not see any error as well.

## Branch or installer method

*Please specify if you are using the current `develop` branch or which installation source you were using when the issue occurred.*

 - Installer: Windows 7 and XP
 - Version: 0.16.5

## Traceback or relevant snippet from server.log

```
No spefic error in the server log
```

## How to reproduce

1. Steps
1. To
1. Reproduce

Install KALiteSetup-0.16.5 on a Window 7 and XP. Go to Manage Tab and try "Scan Content Folder for Videos" 
## Screenshots

![image](https://cloud.githubusercontent.com/assets/8493000/16540281/7cf514de-407c-11e6-8940-bedf5da5250d.png)

**Comment by kenny55d** [comment]
You didn't mention what hardware platform you're using. I've found that the process can take hours to complete depending on your hardware.

On my raspberry pi 3, with about 36GB of videos, it can take between 8 to 10 hours to complete.

On my Lenovo T420 (4GB RAM, 2.5GHz cpu), it takes from 45 minutes to 1 hour to complete.  

Unfortunately there is no obvious progress monitor but I've found that if you look in the USERHOME/.kalite/database folder, while the scan is in progress, you will see a sqlite journal file, which grows gradually to about 16MB and when the scan completed it disappears.

**Comment by kenny55d** [comment]
I started a scan on my Raspberry pi3 about 7 hours ago and now the journal file is currently about 11MB so I know that it is about 68% completed, so about 3 hours to go.

**Comment by rajnikumbh** [comment]
Sorry. I was trying on a Acer 4720 (old laptop) - Core2 Duo (1.66 Ghz) 2GB RAM. I left the laptop on for overnight and scan has completed as you had mentioned. I am not sure why it would take such a long time in order to scan.

Thanks for reply. By the way on Raspberry Pi 3 are you using a 64GB SD Card to store that much of data or any other means?

**Comment by kenny55d** [comment]
Glad I could help. Yes, I'm using a 64GB SD card on the RPi 3.

**Comment by rajnikumbh** [comment]
I think this issue can be closed. 

Some kind of progress bar may be helpful but as explained by "kenny55d" looking at the sqlite journal in USERHOME/.kalite/database folder, while the scan is in progress can be a workaround.
Increase in size and final size should be around 16MB means that scan is progressing. Once the scan is completed this file is automatically removed.

For scan to complete 36GB of torrent downloaded videos 
On a Lenovo T420 (4GB RAM, 2.5GHz cpu) -  1 hour
 Acer 4720 (1.66 Ghz, 2GB RAM) - 8 hours
Raspberry Pi 3 - 8 hours

With this I am closing the issue for now.

**Comment by radinamatic** [comment]
It is very satisfying when we see KA Lite users help one another with everyday issues they encounter... :+1: 

Thank you @rajnikumbh and @kenny55d for sharing your experiences! We are aware that video scanning feature in KA Lite could be improved, and we will certainly include your insights and suggestions into the design of [Kolibri](https://learningequality.org/kolibri/) where we concentrate the majority of our efforts at the moment.
