### ISSUE TITLE
Can't find pip.exe please help!

### ISSUE THREAD

**Issue by mayurnath5r** [learningequality/ka-lite#5199]
I'm trying to install KA Lite, during the setup installation  at the end it says:
![image](https://cloud.githubusercontent.com/assets/17098604/16706040/65cf438a-45bb-11e6-8ae9-7551463abc91.png)
what to do? please help!
The version is 0.15.1

**Comment by benjaoming** [comment]
Hi @mayurnath5r -- thanks for posting. You've deleted the original issue template, so we don't know what version you have been trying to install. Please don't delete the issue template, it's there for a reason ;)

**Comment by mayurnath5r** [comment]
Hi benajaoming I can't understand what you're saying? what template

**Comment by benjaoming** [comment]
When you create a new issue, there's some text in the description field where we request some information, like the version number...

![screenshot from 2016-07-28 17 58 05](https://cloud.githubusercontent.com/assets/374612/17219783/ec3f9600-54ec-11e6-908d-11cc119536e4.png)

**Comment by mayurnath5r** [comment]
DONE!
THE VERSION IS 0.15.1

**Comment by benjaoming** [comment]
@mayurnath5r could you try the latest version instead?

http://ka-lite.readthedocs.io/en/latest/installguide/install_all.html

**Comment by benjaoming** [comment]
@cpauya unless you think this issue report concerning 0.15.1 is of concern for the upcoming 0.17 release, I think we should close it...

**Comment by cpauya** [comment]
@benjaoming We haven't experienced this so far in our testing.  @mayurnath5r please re-open if this still manifests when you use the latest installer as linked above.
