### ISSUE TITLE
Unclean shutdown in OS X installer

### ISSUE THREAD

**Issue by arceduardvincent** [learningequality/ka-lite#5211]
## Summary

I can install it successfully and start the server but when I load it in browser the server will quit. 

## Branch or installer method

 - Installer: OSX
 - Version: 0.16.7b3
 - Branch: 0.16.x

## Screenshots
![f052b7f2-3e69-11e6-9087-7492e24338db](https://cloud.githubusercontent.com/assets/4099119/17150750/34435fae-53a3-11e6-96f7-1752b11597f7.png)

**Comment by benjaoming** [comment]
We have to leave this as a "known issue" for now since there are so many bug fixes in 0.16.7 at this point, it makes no sense to delay it any further.

**Comment by arceduardvincent** [comment]
@cryil and I discuss about this. We agree on that this issue will remain as "known issue" for now. We apologise for the delay of this fix. We will follow up this fix as soon as possible.

**Comment by benjaoming** [comment]
@arceduardvincent could this be related to the way that Pyrun is built for the installer? It seems a similar issue has been solved previously regarding downloads... https://github.com/learningequality/installers/issues/100

**Comment by benjaoming** [comment]
But the mystery of this issue is also a great motivational factor for: https://github.com/learningequality/installers/issues/98

**Comment by arceduardvincent** [comment]
@benjaoming Yeah, maybe similar on the video downloads issue. 
However the mystery on this `Unclean shutdown`,  if we downgrade `requests>=1.0,<1.2.3`. 
The `Unclean shutdown` will not replicate.

**Comment by arceduardvincent** [comment]
I think we will venture some alternatives for `pyrun` like [PEX](https://pypi.python.org/pypi/pex) or `Virtualenv` perhaps. 
What are your thoughts @cpauya?

**Comment by benjaoming** [comment]
@arceduardvincent - I've just checked out [the documentation](http://docs.python-requests.org/en/v1.1.0/user/advanced/#streaming-requests) for `requests` 1.1.0 and it seems it has the `stream=True` option for `get()` which was my main concern since I just refactored all the video download stuff to use requests.

We could try to change to use 1.1.0?

The problem must somehow be in the Python libraries that requests expects and that Pyrun supplies.... brokenly...

**Comment by benjaoming** [comment]
I would be okay with that, as long as we just test the basic things that invoke requests: Content pack and video downloads and the legacy assessment item download.

**Comment by arceduardvincent** [comment]
@benjaoming Ok working on it now. So we can have a OS X installer release too.

**Comment by benjaoming** [comment]
No, not for 0.16.7 -- but for 0.16.8 we will :) As I said, as soon as this issue is fixed, we should release 0.16.8 so we won't have much pause. No problem in releasing often when we fix critical stuff :)

**Comment by benjaoming** [comment]
0.16.7 is already almost totally shipped :)

**Comment by arceduardvincent** [comment]
Yeah. I forgot that :).

So far I have tested content pack, video downloads and the assessment item are working.
![screen shot 2016-08-03 at 1 57 28 am](https://cloud.githubusercontent.com/assets/4099119/17339616/3d87ff3a-591f-11e6-82f2-978f3fd9db2d.png)
![screen shot 2016-08-03 at 2 10 27 am](https://cloud.githubusercontent.com/assets/4099119/17339668/78ad817a-591f-11e6-8f35-11ae8b99dd5e.png)

**Comment by benjaoming** [comment]
Downgrading `requests` already caused the first issue it could seem?

https://github.com/learningequality/ka-lite/issues/5257

**Comment by mrpau-eduard** [comment]
@benjaoming it seems that the downgrading the requests cause the issue #5257. Based on "Short time work around" by @fheslouin. 
For the next release, we will implement [PEX](https://github.com/pantsbuild/pex) to replace Byron then we will upgrade the requests to requests==2. 10.0.
