### ISSUE TITLE
Remove "Error reading secret key file"

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#5236]
## Summary

Previous issue reported by @radinamatic : https://github.com/learningequality/installers/issues/320

    Error reading secret key file [Errno 21]

This should be a message that doesn't make the user think the system is broken.

Windows 7

![secret_key](https://cloud.githubusercontent.com/assets/1457929/11842191/4ddbe216-a402-11e5-878b-d6139ac3fcd6.png)

## Branch or installer method

 - Branch: develop

## How to reproduce

1. Run `kalite start` on a clean system, i.e. without a `.kalite` user folder
1. Observe the error message

**Comment by benjaoming** [comment]
Done, no longer contains the word "error" :)

**Comment by radinamatic** [comment]
Way to go @benjaoming! :+1:
