### ISSUE TITLE
Ka-lite installed with PIP break the latter

### ISSUE THREAD

**Issue by fheslouin** [learningequality/ka-lite#5257]
## Summary

Ka-lite installed with PIP break the latter and can not be used any more

## System information

 - Operating system: Debian Jessie 
 - Version: 0.16.8
 - Browser: Firefox

## Traceback or relevant snippet from server.log

```
root@debian:~# pip
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
```

## How to reproduce
From a fresh debian install 

1. apt-get install python-pip
2. pip install ka-lite==0.16.8

PIP got broken

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

*PIP can not be used anymore*

## Short time work around 
```
mv /usr/local/lib/python2.7/dist-packages/requests /usr/local/lib/python2.7/dist-packages/requests.old/
mv /usr/local/lib/python2.7/dist-packages/requests-1.1.0-py2.7.egg-info /usr/local/lib/python2.7/dist-packages/requests-1.1.0-py2.7.egg-info.old
```
## Long time work around
```
apt-get remove --purge -y python-pip && easy_install -U pip
```

**Comment by fheslouin** [comment]
# Upgrading pip to the last version solve the issue
1. `sudo pip install --upgrade pip` (install pip 8.1.2)
2. Logout/login from the CLI then` pip --version` should show 8.1.2
3. `pip --no-cache-dir install ka-lite`, ` --no-cache-dir` option can be useful if you get a memory error

**Comment by radinamatic** [comment]
Thanks for offering the solution for this issue @fheslouin! :+1: 

I've taken the liberty of [including it ](https://community.learningequality.org/t/ka-lite-install-breaks-pip/78)into our [Community Forums](https://community.learningequality.org/). It would be great if you could post there any contributions that could be useful to a wider LE community, meaning when they are not strictly bug fixes or code related and should be posted here on GH. Thanks again! :100:

**Comment by fheslouin** [comment]
Thanks, I'll do that next time !

**Comment by benjaoming** [comment]
@fheslouin is this because we downgraded our `requests`? Another work-around could be to install the `ka-lite-static` version which has all the dependencies bundled?
