### ISSUE TITLE
"Kannada" Language Pack not listed

### ISSUE THREAD

**Issue by yogeshmr** [learningequality/ka-lite#5262]
## Summary

The release notes of KA Lite version 0.16.7 mentioned that this version supports "Kannada" language content packs. But as can be seen in the attached screen snapshot, the "Download Language Packs" window doesn't list Kannada language pack.
## System information

_Please specify the KA Lite version you were using and your operating system!_
- Operating system: Windows 7
- Version: 0.16.7
- Browser: Chrome
## How to reproduce
1. Start KA Lite Server and login as Admin
2. Click Manage -> Language
3. Enable the "Show beta language packs" tick box and click on the "Set language pack drop down menu".
4. Note that "Kannada" Language is not listed.
## Screenshots

![language_content_packs](https://cloud.githubusercontent.com/assets/21152041/17835896/e94e167e-679d-11e6-89ee-f69bcccd569b.jpg)

**Comment by benjaoming** [comment]
It's the ka.zip package listed here:

http://pantry.learningequality.org/downloads/ka-lite/0.16/content/contentpacks/

@aronasorman it has this entry in all_metadata.json:

```

   {

      "subtitle_count":595,

      "percent_translated":21.0138248848,

      "topic_tree_translated":45.4692330448,

      "software_version":"0.16",

      "beta":false,

      "name":"Georgian",

      "code":"ka",

      "zip_size":30984243,

      "language_pack_version":229,

      "video_count":219,

      "native_name":"\u10e5\u10d0\u10e0\u10d7\u10e3\u10da\u10d8"

   },
```

Any reason it wouldn't be mentioned?

**Comment by benjaoming** [comment]
Ping @aronasorman

**Comment by yogeshmr** [comment]
@benjaoming 
I could not figure out how to ping @aronasorman!

The metadata.json for code "ka" given above is for Georgian. The code for "Kannada" is kn and its metadata.json is as below:

 {"language_pack_version":1,"name":"Kannada","topic_tree_translated":99.7159305334,"software_version":"0.16","native_name":"\u0c95\u0ca8\u0ccd\u0ca8\u0ca1","percent_translated":50.5069124424,"beta":true,"video_count":0,"code":"kn","subtitle_count":0}

I can find the "kn.zip" language pack available for download in below path:
http://pantry.learningequality.org/downloads/ka-lite/0.16/content/contentpacks/

Is there someway I can install this language pack to my KA Lite installation?

**Comment by benjaoming** [comment]
@yogeshmr on right, was a bit too fast there :)

The kn.zip is unfortunately a zero-data package.

But it is supposed to have data, right? What I mean is that `kn.khanacademy.org` actually does not exist... but I'm guessing that it did at some point?

**Comment by yogeshmr** [comment]
@benjaoming 

Ok. Then we have to find where is the data package....hmm...

**Comment by yogeshmr** [comment]
@benjaoming 

I found the below status on Crowdin for Kannada translation.

![crowdin_kannada_status](https://cloud.githubusercontent.com/assets/21152041/18417782/1f9b6398-7857-11e6-8fbb-2c6c376218e6.png)

Could you please let me know, on which of the translations I should be working on: 0.16-django.po or 0.16-djangojs.po?

Is it possible to install the existing quantity of translations for time being?

**Comment by benjaoming** [comment]
@yogeshmr ah yes, this is the translation of the KA Lite interface. But it doesn't pertain videos or exercises.

If you do translations for 0.16, that would be great... we don't plan changing the interface for 0.17. It's both the django.po and djangojs.po that are for translating.

@aronasorman - is it fine to translate for Kannada, interface only? Or would that be wasteful?

**Comment by yogeshmr** [comment]
@benjaoming @aronasorman 

That's gr8. I think that the translations for the exercises is crucial and easier. Could you please indicate how/ where to perform translations for exercises?

**Comment by benjaoming** [comment]
@yogeshmr I haven't tried translating so I'm no expert, but I think you might find it here:

https://crowdin.com/project/khanacademy/kn

@cpauya could you advice if this is the correct procedure?

**Comment by benjaoming** [comment]
Someone has already done a few videos, perhaps it's worth getting in touch with those people:

https://www.youtube.com/user/KhanAcademyKannada/videos

There's also [the translation portal](https://www.khanacademy.org/translations), but it seems to freeze when clicking Kannada, so perhaps it's best to contact Khan Academy directly regarding this issue: i18n_support@khanacademy.org

**Comment by yogeshmr** [comment]
@benjaoming Thank you very much for giving the leads!!!

**Comment by benjaoming** [comment]
There are still almost no translations of `kn` on Crowdin or on the Khan Academy translation platform: https://www.khanacademy.org/translations/kn

I'm closing this as it can only be solved by firstly going through the KA.org channels.
