### ISSUE TITLE
Downgrading requests causes issues with old versions of pip

### ISSUE THREAD

**Issue by mrpau-eduard** [learningequality/ka-lite#5264]
## Summary

Edit: @benjaoming

The downgrading of `requests` causes issues with pip both system-wide and inside virtualenvs (in which, however, pip isn't needed unless user installs additional pkgs from PyPi)

This is known to affect older versions of pip, 1.5.6 especially

The fix will arrive in 0.17.

---

The original issue here is we downgrade requests to fix the [Unclean shutdown](https://github.com/learningequality/ka-lite/issues/5211#event-747204501) on `OS X`.
Spawn issue after the downgrade [Ka-lite installed with PIP break the latter](https://github.com/learningequality/ka-lite/issues/5257).

## System information

 - Operating system: `OS X`, `Debian Jessie`
 - Version: 0.16.

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

* [Ka-lite installed with PIP break the latter](https://github.com/learningequality/ka-lite/issues/5257)
* [Unclean shutdown in OS X installer ](https://github.com/learningequality/ka-lite/issues/5211#event-747204501)

**Comment by mrpau-eduard** [comment]
We need to replace `Pyrun` by [PEX](https://github.com/pantsbuild/pex) base on the spawning issue. `PEX` will isolate the virtual environment for ka-lite to prevent some issue like this. Then we need upgrade the `requests` to `requests==2.10.0`

**Comment by benjaoming** [comment]
@mrpau-eduard - it's unclear to me what the issue on Debian Jessie is?

But I agree, we need to get requests upgraded ASAP because of the pip breakage.

**Comment by benjaoming** [comment]
Fixed in #5285

`requests` is now in version 2.11.1 in `develop`, will be released in 0.17 - prereleased in 0.17b1 on PyPi
