### ISSUE TITLE
Auto-syncing bug reporting tool for distributed servers

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#527]
How do you report a bug when you're offline in the Sahara desert, learning how to multiply fractions?  You click the "report a bug" button, fill out the form, and let it sit on your local machine until the next time you connect to the internet--when it gets pushed up to your software provider automatically.

Sound too good to be true?  Then you haven't been paying attention! :)  This is an important part of what KA Lite does!

In fact, creating an auto-syncing bug reporting tool is really easy with Django + KA Lite's auto-syncing back-end:
1. Create a new app (bug-reporting)
2. Add a models.py file for the bug report info needed.  Make it extend securesync.models.SyncedModel, and add it to the list of syncing models (add_syncing_models)
3. Add a forms.py file for generating the form (which can auto-generate a HTML form, and help you parse it!
4. Add a views.py file for receiving the basic form information, adding some system information to the form before it's saved.
5. .... honestly, that's pretty much it!

This would be a great project for interns--let me know if you're interested!  Glad to work together!

**Comment by aronasorman** [comment]
Once we implement https://github.com/learningequality/ka-lite/issues/3327, we can have a mechanism we automatically syncs the latest log dump when needed. To 0.14!

**Comment by rtibbles** [comment]
This is not going to happen within the scope of KA Lite.
