### ISSUE TITLE
no languages in dropdown for 0.16.9

### ISSUE THREAD

**Issue by tim-moody** [learningequality/ka-lite#5273]
after install of 0.16.9 on centos 7.2 the languages dropdown shows no languages and no language is listed as installed.

**Comment by tim-moody** [comment]
after re-running kalite manage setup, the list of languages from 0.16.8 is there and English is listed as installed, but Arabic is not in the list even when clicking show beta. (it used to me in the main list)

**Comment by tim-moody** [comment]
https://hub.learningequality.org/languages/dashboard shows Arabic as 100% translated, but after I manually downloaded ar.zip I see Chinese, Cyrillic, English, and Arabic.

**Comment by benjaoming** [comment]
Thanks for reporting this -- not sure which version you upgraded from, but the problem could be due to an old language pack version that wasn't active after the upgrade?

Hope it's okay to continue this in your other issue? #5266
