### ISSUE TITLE
Using built PEX file in KA Lite installers.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/ka-lite#5274]
### List of issues that will be fix using built KA Lite PEX file.
1. [Kill existing pyrun activity when resetting the kalite-monitor app](https://github.com/learningequality/installers/issues/125#issuecomment-246227013)
1. [Drop Pyrun on OS X Installer and replace it with virtualenv.](https://github.com/learningequality/installers/issues/98)

### KA Lite issue.

1. [Downgrading requests causes issues with old versions of pip](https://github.com/learningequality/ka-lite/issues/5264)

**Comment by mrpau-richard** [comment]
Hi @benjaoming can you also add an open `pypy` issue related on pex?

**Comment by benjaoming** [comment]
@mrpau-richard - this looks like an issue you should open up in the installers repo:

https://github.com/learningequality/installers/issues

> Hi @benjaoming can you also add an open pypy issue related on PEX? Because I can't find those issues.

You want me to compile a list of all issues related to pypy? You can search for "pypy" in the issues open in ka-lite and installers, that will give you a result that's better than asking me :)

**Comment by mrpau-richard** [comment]
@benjaoming Ok, I will close this issue and transfer it to [installers](https://github.com/learningequality/installers/issues)
