### ISSUE TITLE
Videos player doest not show control bar and play button

### ISSUE THREAD

**Issue by fheslouin** [learningequality/ka-lite#5289]
## Summary

Videos does not show play button or show status bar on Android, Firefox (v. 48).
Videos works correctly on Android, Chrome (v. 43)
Videos works correctly on Laptop Linux, Firefox (v. 48)
## System information

_Please specify the KA Lite version you were using and your operating system!_
### Server side
- Operating system: Linux Debian Jessie
- Version: 0.16.8
## How to reproduce
1. Use Firefox 48 on Android
2. Navigate to a video
3. Try to play the video
## Workaround

Long push on a video show a menu, you can press "play" or "show control bar"

**Comment by benjaoming** [comment]
You mean this? It's showing here on 0.16.9.

![screenshot from 2016-09-21 18-27-54](https://cloud.githubusercontent.com/assets/374612/18719789/233f5d54-8029-11e6-929c-8377da16f91d.png)

**Comment by fheslouin** [comment]
I upgrade to 0.16.9, It works on Android Chrome, but not Firefox. 

On Firefox it seems that the old control bar is still appearing, then I long press then "play", It is loading then the new control bar is appearing...
I cleared completely Firefox cache and tried on two devices, same issue.

**Comment by benjaoming** [comment]
@fheslouin after updating, have you run `kalite manage setup` - running this command will perform some of the routine Django stuff like `migrate` and `collectstatic`.

**Comment by fheslouin** [comment]
I have done `kalite manage setup` but no improvement. The video can't be shown automatically on Android Firefox. 

Does it work for you ?

**Comment by benjaoming** [comment]
@fheslouin I don't have access to Android Firefox - are you able to debug this, for instance dump any javascript errors that may occur in the browser?

**Comment by benjaoming** [comment]
@fheslouin video.js (the video player) is updated in 0.17, you can try installing a prerelease with `pip install ka-lite --pre` (needs pip 8 series, doesn't work yet in pip 9)

**Comment by benjaoming** [comment]
Closing this, it would have to be investigated again in 0.17, but for now, video-js is updated to the latest version, hopefully this also solves issues with new browsers.
