### ISSUE TITLE
New ContentPack(bn)

### ISSUE THREAD

**Issue by rifatbd** [learningequality/ka-lite#5295]
## Its been a while Since any bangla(bn) contentpack is released for KALite. Recently the [Khan Academy Bangla](https://bn.khanacademy.org/) site have unlocked some new sections. It would be great if a new contentpack is available with all the new contents.
# System information
# Traceback or relevant snippet from server.log
# How to reproduce
## Screenshots

![Current Content in KALite](https://cloud.githubusercontent.com/assets/18570759/18808174/c19c83fa-827c-11e6-9a59-6d60d61443ce.PNG)

![Current Content in KhanAcademy](https://cloud.githubusercontent.com/assets/18570759/18808183/089c2b8e-827d-11e6-90a8-5275079f299f.PNG)
## Real-life consequences

Well it is very important for us to use it in schools.

**Comment by mrpau-eduard** [comment]
Hi @rifatbd thanks for reporting.
We will take a look on this issue and update the contentpacks soon.

**Comment by benjaoming** [comment]
@mrpau-eduard is it possible to build this for 0.17 with data straight just from content-pack-maker? 

What I mean is that there possibly won't be enough time to act before releasing 0.17.0, but we can still build the content pack, and then CrowdIn data can be added later..

**Comment by mrpau-eduard** [comment]
Yeah it is possible, If you mean the data from khan page. 
If it has an English version and we need a translation of the titles and description we can create an alternative instead of waiting to khan api to have the translation to be included.

Doable for dubbed videos. I didn't try yet the exercise, but I think is possible as long I have the source which I can scrape the data. 
Like this https://ar.khanacademy.org it has the titles and YouTube video equivalent.

**Comment by benjaoming** [comment]
@mrpau-eduard - is the `https://bn.khanacademy.org/` site adequate?

**Comment by mrpau-eduard** [comment]
Nope. We can still scrape the titles and description aslong as the youtube_ids of `bn` has an english youtube_ids. I can match the youtube ids to indentify the matching titles then replace the untranslated nodes with the scraped data from https://bn.khanacademy.org/math for example.

**Comment by rifatbd** [comment]
@mrpau-eduard so if i provide you a excel sheet with the Title and YouTube link for all the dubbed videos.... would it be of any help?..... and for exercise(if you tried anything meanwhile) what is needed ? May be i can provide with some info i guess...

**Comment by mrpau-eduard** [comment]
Thanks for the suggestion as of now I am working with a script which collect the new video mappings on the `khan api internal`. 
This script work's only the dubbed videos, you can check the video mappings here: http://learningequality.org/r/translationmapping

**Comment by benjaoming** [comment]
@rifatbd could you test the new content pack available in 0.17.0b5 - instructions are in #5390

**Comment by rifatbd** [comment]
@benjaoming ..... will do and let you know :)

**Comment by radinamatic** [comment]
While I cannot, of course, vouch for the accuracy of the content, the language installs OK and displays in the latest OSX installer:


![virtualbox_sierra_24_01_2017_14_50_45](https://cloud.githubusercontent.com/assets/1457929/22250144/29ac1edc-e246-11e6-8a41-99058518324b.png)

  
![virtualbox_sierra_24_01_2017_14_53_00](https://cloud.githubusercontent.com/assets/1457929/22250145/29ae7286-e246-11e6-8c87-cde4b98daa5b.png)


![virtualbox_sierra_24_01_2017_15_00_10](https://cloud.githubusercontent.com/assets/1457929/22250141/29a931ea-e246-11e6-8954-1d58e304b072.png)


![virtualbox_sierra_24_01_2017_14_54_02](https://cloud.githubusercontent.com/assets/1457929/22250142/29ab1c3a-e246-11e6-881d-3fd2c8c2086d.png)


![virtualbox_sierra_24_01_2017_14_59_39](https://cloud.githubusercontent.com/assets/1457929/22250143/29ab4c46-e246-11e6-841b-b76e6ccd8209.png)

**Comment by benjaoming** [comment]
@radinamatic 's tests look really promising - @rifatbd I hope your deployment will be successful from here on :) Please let us know if there are any further issues! And in case there are, feel welcome to report them!
