### ISSUE TITLE
Some videos that are in the French packs are in English

### ISSUE THREAD

**Issue by mrpau-eduard** [learningequality/ka-lite#5328]
## Summary

Playing some of the videos using the French language are in English.
## System information
- Version: 0.16.x
## How to reproduce
1. Download the  French content pack [fr.zip](http://dungeon.learningequality.org:8085/artifact/CP-KL/shared/build-254/English-content-pack/langpacks/fr.zip)
2. Then run command `kalite manage retrievecontentpack local fr <download/path/>/fr.zip`
3. Switch your language to French. 
4. Download the `fr` videos via [torrent](http://pantry.learningequality.org/downloads/ka-lite/0.16/content/ka-lite-0.16-resized-videos-french.torrent).
5. After your done downloading the videos move/copy the videos from your `./ka-lite/content/` directory then in your browser navigate to the management tab. Go to the download page click `Scan content for videos`. 
6. You may also download the videos via UI navigate to the download videos in your management tab then select the videos corresponding in the list of urls below. 
7.  Clink the selected links below and it will redirect you to the English videos.
## List of urls/titles where videos that are in the French packs are in English
- [Examen BC d'analyse AP: 2008 1 b&c](http://127.0.0.1:8008/learn/khan/math/calculus-home/ap-calc-topic/ap-calculus-bc-questions/ap-calculus-bc-exams-2008-1-b-c/)
- [Analyse BC 2008 2 b &c](http://127.0.0.1:8008/learn/khan/math/calculus-home/ap-calc-topic/ap-calculus-bc-questions/calculus-bc-2008-2-b-c/)
- [Ptolemaic: Rosetta Stone](http://127.0.0.1:8008/learn/khan/computing/computer-science/informationtheory/info-theory/rosetta-stone-196-b-c-e/)
- [Réponse #6c au sujet d'Analyse AB de 2011](http://127.0.0.1:8008/learn/khan/math/calculus-home/ap-calc-topic/ap-calculus-ab-questions/2011-calculus-ab-free-response-6c/)
- [Subtracting in your head (no regrouping)](http://127.0.0.1:8008/learn/khan/math/fr-cycle-3/fr-addition-et-soustraction-de-nombres-entiers/fr-soustraction-avec-retenue-jusqu-a-1000/mental-technique-for-subtraction-without-regrouping/)
- [Production of sound](http://127.0.0.1:8008/learn/khan/science/physics/mechanical-waves-and-sound/sound-topic/production-of-sound/)
- [Virus](http://127.0.0.1:8008/learn/khan/science/biology/biology-of-viruses/virus-biology/viruses/)
- [Trous noirs](http://127.0.0.1:8008/learn/khan/science/cosmology-and-astronomy/stellar-life-topic/stellar-life-death-tutorial/black-holes/)
- [Introduction to limits (old)](http://127.0.0.1:8008/learn/khan/math/differential-calculus/limit-basics-dc/limits-introduction-dc/introduction-to-limits/)
- [Introduction à l'hérédité](http://127.0.0.1:8008/learn/khan/science/biology/classical-genetics/mendelian--genetics/introduction-to-heredity/)
- [Scale of the large](http://127.0.0.1:8008/learn/khan/science/cosmology-and-astronomy/universe-scale-topic/scale-earth-galaxy-tutorial/scale-of-the-large/)
- [Electrochemical gradients and secondary active transport](http://127.0.0.1:8008/learn/khan/science/biology/membranes-and-transport/active-transport/electrochemical-gradient-and-secondary-active-transport/)
- [Multiplying with area model: 6 x 7981 ](http://127.0.0.1:8008/learn/khan/math/arithmetic/arith-review-multiply-divide/arith-review-place-value-area-models/4-by-1-multiplication-with-grid/)
- [Les fractions égales](http://127.0.0.1:8008/learn/khan/math/arithmetic/fraction-arithmetic/arith-review-visualizing-equiv-frac/more-equivalent-fractions/)
- [Preuve du théorème de la divergence (seconde partie)](http://127.0.0.1:8008/learn/khan/math/multivariable-calculus/greens-theorem-and-stokes-theorem/divergence-theorem-proof/divergence-theorem-proof-part-2/)
## Youtube ID's  that are in the French packs are in English.
- [xPb6HLM3xEQ, S4oOSgTj9C8, OFXY9-pec1I, ucghWyc2_qs, iivtjjdSu9I, nGKffdaI4Pg, 0h5Jd7sgQWY, JoL2pO3O0rg, W0VWO4asgmk, eEUvRrhmcxM, 5FEjrStgcF8, wbWL2wfvsM8, UvAOynxGfIU, yZqVJtDO7gc, ZZ6h7ugR0xc]

**Comment by mrpau-eduard** [comment]
Notice that `description` and `title` for - [Examen BC d'analyse AP: 2008 1 b&c](http://127.0.0.1:8008/learn/khan/math/calculus-home/ap-calc-topic/ap-calculus-bc-questions/ap-calculus-bc-exams-2008-1-b-c/) are translated to French however the `youtubeId` and `translatedYoutubeLang` is `en`.
```
{
  "description": "Réponses au problème 1, parties b et c",
  "downloadSize": 7026793.0,
  "duration": 574,
  "id": "24256",
  "imageUrl": "https://cdn.kastatic.org/googleusercontent/GcOt-PK7p3F0Z_42X_SzHjVc34bnT84lPK26WDsUTIJS-SCtvXYImIYIJoX_PSif2XKZKr89Y_AL5krddMI0Bis",
  "keywords": "calculus, BC, exam",
  "kind": "Video",
  "licenseName": "CC BY-NC-SA (KA default)",
  "readableId": "ap-calculus-bc-exams-2008-1-b-c",
  "relatedExerciseUrl": null,
  "relativeUrl": "/video/ap-calculus-bc-exams-2008-1-b-c",
  "sha": "e35b63e33c64fc0fa674e2d74690eedffd03b101",
  "slug": "ap-calculus-bc-exams-2008-1-b-c",
  "title": "Examen BC d'analyse AP: 2008 1 b&c",
  "translatedYoutubeLang": "en",
  "youtubeId": "xPb6HLM3xEQ"
},
```

**Comment by jamalex** [comment]
Ok, that makes sense then. Presumably if `translatedYoutubeLang` is "en", we should not use that `youtubeId`, other than to look it up in the spreadsheet. If it's not in the spreadsheet (and `xPb6HLM3xEQ` isn't), then we should exclude it.

Is that not what we're doing now?

**Comment by mrpau-eduard** [comment]
Hi @jamalex , 
We are currently working on it. If the  if `translatedYoutubeLang` is "en" we lookup on the spreadsheet then exclude the `youtubeId` which is english.
We incorporate this fix in this pull request https://github.com/fle-internal/content-pack-maker/pull/39

@mrpau-dev able to exclude the English youtube id's. See attachment below.
 [Examen BC d'analyse AP: 2008 1 b&c](http://127.0.0.1:8008/learn/khan/math/calculus-home/ap-calc-topic/ap-calculus-bc-questions/ap-calculus-bc-exams-2008-1-b-c/)
![screen shot 2016-10-14 at 4 20 43 pm](https://cloud.githubusercontent.com/assets/20859877/19380527/324ab2ea-922a-11e6-90ce-09e65e47d875.png)

When we implement the fix there are some issue we encounter in the video topics which we are currently fixing it.
![screen shot 2016-10-14 at 4 16 06 pm](https://cloud.githubusercontent.com/assets/20859877/19380371/96382162-9229-11e6-8525-755612a96148.png)

**Comment by mrpau-eduard** [comment]
Hi @jamalex we manage to fix the issue on the video topics.
The next things @mrpau-dev will do is to test the fix with different language packs.

**Comment by benjaoming** [comment]
@mrpau-eduard @radinamatic - was looking around, seems there are still a lot of topics in English in the French content pack.

What can we do about it? Should we add it as a "known issue"?

**Comment by benjaoming** [comment]
![screenshot from 2017-01-24 22-41-56](https://cloud.githubusercontent.com/assets/374612/22268108/7ebeb64c-e286-11e6-82a0-a77be5c29977.png)
![screenshot from 2017-01-24 22-42-49](https://cloud.githubusercontent.com/assets/374612/22268109/7ed59312-e286-11e6-99c6-a8c9328202f8.png)

**Comment by radinamatic** [comment]
@benjaoming Those topic titles are displayed in English even on KA site in French, so I'm unsure if there's something we can actually do:

![virtualbox_ubuntu 16 10_25_01_2017_15_17_41](https://cloud.githubusercontent.com/assets/1457929/22294423/96ca434a-e313-11e6-8e0a-d68ebeb98815.png)

![virtualbox_ubuntu 16 10_25_01_2017_15_24_20](https://cloud.githubusercontent.com/assets/1457929/22294430/a3818a9e-e313-11e6-8b21-a75d98152225.png)


Once the video is downloaded in KA Lite, it is the dubbed French version, so there's that at least...

**Comment by radinamatic** [comment]
As of the `Grade X (NCERT)` topics, those are not present on  KA math page in French (it ends with `Terminale S` topic), so maybe we could exclude them, but I don't think it warrants the mention in the `Known issues`.

![virtualbox_ubuntu 16 10_25_01_2017_15_35_46](https://cloud.githubusercontent.com/assets/1457929/22294608/2c7ebec0-e314-11e6-91f6-4945437ca70b.png)

**Comment by benjaoming** [comment]
@radinamatic thanks for checking it out!

I think we can close it then... since remaining English meta data basically just reflects upstream data.
