### ISSUE TITLE
Windows 8 installer: Sever is not running and has been grayed out

### ISSUE THREAD

**Issue by BabluKumar17** [learningequality/ka-lite#5334]
## Summary

I successfully downloaded KA Lite first time in Windows and then when I ran it as an administrator it asked for a password and I typed in my password in cmd.  But I noticed in the nofication, the **Start Server** has been grayed out.

## System information

*Please specify the KA Lite version you were using and your operating system!*

 - Operating system: ? Windows 8.1, 64 bit
 - Version: 0.16.? Yes!
 - Browser: ? Chrome

## Screenshots
![06-11-2016-08-54-39](https://cloud.githubusercontent.com/assets/14871809/20035197/46e56e1a-a400-11e6-9fab-ad0ae33db752.png)

**Comment by radinamatic** [comment]
Hi @BabluKumar17!

Please confirm that you installed the latest release 0.16.9 of KA Lite!

Did you see a Windows Firewall notification about giving permission for a Python process when you tried to run KA Lite the first time after the installation? If the `python.exe` process is not permitted to run, KA Lite server will not start. 

Do you see any `python.exe` process running? Right click the task bar and select **Task Manager** from the contextual menu, and check the  **Processes** tab?

**Comment by BabluKumar17** [comment]
Thanks for your @radinamatic:
I tried your approach too. But, unfortunately nothing worked.  I have also turned off my firewall but I do not see any **python.exe** file running in **Task Manager**.

**Comment by benjaoming** [comment]
This issue was moved to learningequality/installers#428
