### ISSUE TITLE
Subtitles do not load in 0.17b2 and `no element found` error

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#5337]
## Summary

Two things might be unrelated, but it's the only error I see in the console.

## System information

*Please specify the KA Lite version you were using and your operating system!*

 - Operating system: Ubuntu 16.10
 - Version: 0.17b2
 - Browser: Firefox

## Browser console

```
no element found
```

## How to reproduce

1. Install 0.17b2
1. Download a contentpack (Spanish in my case, but happens on English too) & videos.
1. Try playing videos.

## Screenshots

![no_element_found](https://cloud.githubusercontent.com/assets/1457929/20316897/1ddf9778-ab64-11e6-95a2-fb1af33617af.png)

**Comment by benjaoming** [comment]
I've copied in the newest 0.16 content packs, should give you this:

![screenshot from 2016-11-28 17-26-17](https://cloud.githubusercontent.com/assets/374612/20676371/d2d2125c-b58f-11e6-98a0-a604c90365bd.png)

**Comment by benjaoming** [comment]
Hmmm, well, trying the latest `en` contentpack built for 0.16 gives me: `uncaught exception: undefined` when enabling subtitles.

**Comment by benjaoming** [comment]
It correctly requests and receives the .vtt file, so I think we can assume it's a JavaScript issue, will investigate.

**Comment by benjaoming** [comment]
@radinamatic - seems like another issue is that the current `develop` branch doesn't even have a "CC" button in the videojs player. Wondering a bit what we've changed in this regard. 0.17b2 works, but even after rebuilding JS assets in current `develop`, I still don't see it :/

**Comment by radinamatic** [comment]
@benjaoming I was under the impression that it was the default behaviour of `videojs` not to display the CC button if there are no captions for the currently playing video.

**Comment by benjaoming** [comment]
@radinamatic - it is the correct behaviour, however there *is* a caption for "Counting with small numbers" in English.

```
➜  ~ find .kalite -name '*y2-uaPiyoxc*'
.kalite/httpsrv/static/srt/en/subtitles/y2-uaPiyoxc.vtt
.kalite/content/y2-uaPiyoxc.mp4
.kalite/content/y2-uaPiyoxc.png
```

**Comment by benjaoming** [comment]
It seems my issue is that after switching from 0.17b2 to 0.17 in `develop`, the database was wrongly annotated:

When from this:

     "subtitle_urls": [{"url": "/static/srt/en/subtitles/y2-uaPiyoxc.vtt", "code": "en", "name": "English"}]

**Comment by benjaoming** [comment]
To be investigated in #5318

**Comment by radinamatic** [comment]
I don't see the `y2-uaPiyoxc.vtt` loaded in my screenshot above, so it must be lost in translation... :stuck_out_tongue:

**Comment by radinamatic** [comment]
If I fire up the same VM with 0.17b2 will it be able to grab the new contentpacks you talk about above?
@benjaoming

**Comment by benjaoming** [comment]
Yes, they are live now. Sorry that I derailed the original issue slightly -- if you could investigate if the problem w/ Spanish subtitles persists, that'd be great!!!

**Comment by radinamatic** [comment]
Roger, will test as soon I manage to clone that VM on my new system (hoping SSD will make the VBox run faster than before :wink: )!

**Comment by radinamatic** [comment]
`no element found` error vanished with 0.17 contentpacks and the recent subtitles fixes by @benjaoming, so I'm closing this.
