### ISSUE TITLE
Exercises in Firefox - uncaught exception: out of memory

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#5339]
## Summary

Cannot load exercises in Firefox, `uncaught exception: out of memory` error in the console. Happened first on `pt-BR` contentpack, but the same problem repeats when I switch to English, or when I install Spanish.

It is as if when it arrives to `bundle_exercise.js` file, it tries to load but eventually fails and reports the error...

## System information

*Please specify the KA Lite version you were using and your operating system!*

 - Operating system: Windows 7
 - Version: `KALiteSetup-0.17.0.dev0.exe` compiled today
 - Browser: Firefox, Chrome seems not to have this issue

## Traceback or relevant snippet from server.log

```
uncaught exception: out of memory
```

## How to reproduce

1. Install `pt-BR` or `es-ES` contentpack.
1. Try any exercise.

## Screenshots

![virtualbox_windows 7_21_11_2016_12_23_42](https://cloud.githubusercontent.com/assets/1457929/20482301/47e4a432-afec-11e6-947f-0c3f378a816b.png)

![virtualbox_windows 7_21_11_2016_13_19_17](https://cloud.githubusercontent.com/assets/1457929/20482485/2fda4cce-afed-11e6-9728-3b9c6799b4b0.png)

**Comment by benjaoming** [comment]
@radinamatic 

Does this happen consistently?
Does it happen on all or specific exercises?

**Comment by radinamatic** [comment]
Still trying to figure out how to consistently replicate this... 🤔 

I just installed on Windows 8:
1. Tried several random exercises in English - no problems.
2. Downloaded Spanish, tried again several random exercises - still no problems.
2. Downloaded `pt-BR`, tried the first exercise - 💥 `uncaught exception: out of memory` again!

😿

**Comment by radinamatic** [comment]
And it still happens only on Firefox...

**Comment by benjaoming** [comment]
What if you only have PT-br installed?

**Comment by radinamatic** [comment]
That was the first case on W7, and it happened with only pt-BR. 
Later I downloaded es-ES to see if it happens there too, and it did...

**Comment by benjaoming** [comment]
Tried to profile this in Firefox 50 on Ubuntu.

The count exercise with images of foxes is ~20,000 milliseconds to load on pt-BR and ~14,000 ms in English w/o pt-BR installed. Load times vary on my system, and I find it a bit unclear if things really do load slower with pt-BR installed or not, I also had an incident where it didn't - this was when reloading the same exercise.

The total memory footprint is 18 MB in English w/o the pt-BR, which suddenly increases to 27 MB with pt-BR installed but still in English. This happened right after installing a new content pack.

I can, however, reload the page and the total footprint is back to 18 MB.

I'm not sure what kind of caching is at stake, but certainly the memory consumption of the exercise seems to be related to whether it's a fresh display or a page reload.

**Comment by benjaoming** [comment]
Btw. the pt-BR content packs do not contain static files, hence it doesn't change how javascript behaves.

It's true that `/static/js/distributed/bundles/bundle_exercise.js` takes up a lot, 17% of memory. But there's also some `js::Shape` object that's 24% that I'm not sure what is.. could be some kind of vector rendering.

What I'm seeing performance-wise on Ubuntu could be different on Windows because of the host system.

It's hard to rule out a memory error because of these very memory-intensive operations - I get a feeling that it's inherent from the way these exercises are built upstream, and not something we can optimize.

**Comment by benjaoming** [comment]
I found that it's only the counting exercise in `/learn/khan/math/early-math/cc-early-math-counting-topic/cc-early-math-counting/counting-out-1-20-objects/` that's super slow.

Btw the exercise is as slow on 0.16.9 - please try that, too @radinamatic :)

You could even go as far as to try the exercise on KA.org:

https://pt.khanacademy.org/math/early-math/cc-early-math-counting-topic/cc-early-math-counting/e/counting-out-1-20-objects

In case you can confirm that the issue is also happening on 0.16, I think we should close this issue.

**Comment by radinamatic** [comment]
One thing is sure: no sign of this error in Firefox 50 on Ubuntu 16.04 - I went through all the exercises in topic `Counting` and they all work fine... :thinking: 

The exercise you mention above is noticeably slower then the rest, but it still does not throw the error as on Windows.

I'll try 0.16 next!

**Comment by benjaoming** [comment]
@radinamatic pretty sure the "out of memory" will only happen when something hits an upper limit, and not because of a consistent programmatic pattern... but the upper memory limit is not a universal limit, it could be that it will only reproduce on Windows. Exact memory consumption is also unique according to whatever host system, browser etc. Just theory-guessing :)

**Comment by radinamatic** [comment]
Installed the 0.16.9 on a new snapshot of the same W7 virtual machine as above (same version of FF and RAM amount), and all `Counting > Early math` exercises load in flying, even the `/cc-early-math-counting-topic/cc-early-math-counting/counting-out-1-20-objects/`...

**Comment by radinamatic** [comment]
![virtualbox_windows 7_30_11_2016_13_20_27](https://cloud.githubusercontent.com/assets/1457929/20752107/d2529a10-b6ff-11e6-8e72-0f3bb19301e4.png)


However, clearing the cache and reloading brings the beast back:

![virtualbox_windows 7_30_11_2016_13_27_23](https://cloud.githubusercontent.com/assets/1457929/20752298/db694ea4-b700-11e6-9141-67d264e873d9.png)

Not very familiar with these profiling tools, what should I look for...?

**Comment by radinamatic** [comment]
No sign of error on the newest OSX installer by @mrpau-richard either:

![virtualbox_sierra_30_11_2016_14_34_50](https://cloud.githubusercontent.com/assets/1457929/20754240/519f93e0-b70a-11e6-821b-df35541173d3.png)

**Comment by benjaoming** [comment]
In order to identify whether it's something we can do anything about: In case you reproduce the slowness / memory error, try loading the same exercise on khanacademy.org.

In case it's also slow on their site, I would recommend we stop throwing resources at this bug, it doesn't seem likely it's something related to KA Lite...

**Comment by radinamatic** [comment]
Re-testing this with the latest installer by @mrpau-richard ( #5364 ), I think the issue might have something to do with reloading... If I select the exercise from the the root of the sidebar, it loads correctly, but if I simply reload that exercise page, the `uncaught exception: out of memory
` appears again:

![virtualbox_windows 7_16_12_2016_14_41_34](https://cloud.githubusercontent.com/assets/1457929/21264998/84af029c-c39f-11e6-9058-fde5d71405c3.png)

**Comment by radinamatic** [comment]
Hmmm, I just updated Firefox to version 50 on this Windows 7 machine, and I can't reproduce the error anymore, not even by reloading...

I'll play with this a bit more, see if it's really gone!

**Comment by radinamatic** [comment]
Firefox 49 in Windows 8, first exercise load is correct, but as soon as I reload the page, error is there again:

![virtualbox_ie11 - win8 1_16_12_2016_15_31_28](https://cloud.githubusercontent.com/assets/1457929/21266219/588d4434-c3a5-11e6-9633-b5781599ffe8.png)

And not just the `Counting` ones, pick another randomly, first load OK:

![virtualbox_ie11 - win8 1_16_12_2016_15_34_25](https://cloud.githubusercontent.com/assets/1457929/21266231/6e71dd14-c3a5-11e6-868a-44c769731e28.png)

 Simply reload the same page, error is there:

![virtualbox_ie11 - win8 1_16_12_2016_15_37_06](https://cloud.githubusercontent.com/assets/1457929/21266276/acb818ea-c3a5-11e6-9790-ad52cbc5e5bb.png)
 

Going to update FF to version 50 now, to see if the error disappears as in Windows 7...

**Comment by radinamatic** [comment]
Whatever glitch caused this, seems to have gone bye-bye with updating to Firefox 50... 😈 

I'm going to close this!

**Comment by benjaoming** [comment]
In my experience on both FF and Chrome, the exercise "Counting with small numbers" is still super-slow.

**Comment by radinamatic** [comment]
Firefox on Windows 7 VM with 4Gb RAM it's not noticeably slow, I'll reduce the RAM and see if something changes.

**Comment by scriptrobin** [comment]
Hi, @radinamatic i faced the out of memory issue in firefox version 68.0. am not familiar with this issue, kindly write a solution if you have an idea. Thanks in advance

**Comment by radinamatic** [comment]
@robinProject, thank you for reaching out.

For the last 3 years we have been concentrating our efforts on the development of our second generation platform called [Kolibri](https://learningequality.org/kolibri/), with many more features and content sources available compared to KA Lite. It is doubtful that we will have resources to dedicate to managing issues on this older platform.

Kolibri is free to [download](https://learningequality.org/download/) directly from our website and we've also created a [do-it-yourself Toolkit](https://learningequality.org/documentation/) that has a range of training materials, documentation, and guidance on how to effectively integrate Kolibri into your context. I'd also recommend taking a look at our [user guide](https://kolibri.readthedocs.io/en/latest/) to learn more about installation and using Kolibri.

I invite you to take a look at our [Kolibri demo site](http://learningequality.org/download) to get a sense of how Kolibri can be used (you can explore with provided credentials for all user types), and access the tutorial videos in the "How to get started with Kolibri" channel.

Let me know if you have any questions!
