### ISSUE TITLE
Subtitles broken on Firefox 50

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#5347]
## Summary

Subtitle support has broken since at least the latest Firefox 50 release.

Identical setups work on Chromium and Firefox 49.

The bug is in the polyfill for WebVTT, vtt.js - For the record videojs-vtt and vtt.js are the same packages!

## System information

*Please specify the KA Lite version you were using and your operating system!*

 - Operating system: Ubuntu 16.04
 - Version: develop
 - Browser: Firefox 50

## Traceback or relevant snippet from server.log

```
TypeError: Member of DoubleOrAutoKeyword 'undefined' is not a valid value for enumeration AutoKeyword.  bundle_video.js:19:1509
	l http://localhost:8008/static/js/distributed/bundles/bundle_video.js:19:1509
	o http://localhost:8008/static/js/distributed/bundles/bundle_video.js:19:1926
	require<[590]</</p.Parser.prototype.parse http://localhost:8008/static/js/distributed/bundles/bundle_video.js:19:23332
	require<[588]</</</<[127]</x http://localhost:8008/static/js/distributed/bundles/bundle_video.js:28:6684
	require<[588]</</</<[127]</O/< http://localhost:8008/static/js/distributed/bundles/bundle_video.js:28:6941
	require<[588]</</</<[133]</r/r http://localhost:8008/static/js/distributed/bundles/bundle_video.js:28:18305
	o/< http://localhost:8008/static/js/distributed/bundles/bundle_video.js:22:24327
	i http://localhost:8008/static/js/distributed/bundles/bundle_video.js:22:22283
	e http://localhost:8008/static/js/distributed/bundles/bundle_video.js:22:21680
```

## How to reproduce

1. Load a video with a sub title, e.g.: http://localhost:8008/learn/khan/math/early-math/cc-early-math-counting-topic/cc-early-math-counting/counting-with-small-numbers/

**Comment by benjaoming** [comment]
`p.Parser.prototype.parse` is part of [videojs-vtt](https://www.npmjs.com/package/videojs-vtt.js) which hasn't been updated for 12 months and seems to have very few users.

Suggesting to update.

**Comment by benjaoming** [comment]
Confirmed that our subtitles are rendered with videojs-vtt in Firefox 49.

**Comment by benjaoming** [comment]
Using latest upstream master for vtt.js yields something similar to the old error:

```
TypeError: Argument 1 of TextDecoder.decode could not be converted to any of: ArrayBufferView, ArrayBuffer.[Learn More]  bundle_video.js:1961:24
	require<[756]</</WebVTT.Parser.prototype.parse http://127.0.0.1:8000/static/js/distributed/bundles/bundle_video.js:1961:24
	parseCues http://127.0.0.1:8000/static/js/distributed/bundles/bundle_video.js:11121:3
	loadTrack/< http://127.0.0.1:8000/static/js/distributed/bundles/bundle_video.js:11177:7
	ret http://127.0.0.1:8000/static/js/distributed/bundles/bundle_video.js:21958:12
	once/< http://127.0.0.1:8000/static/js/distributed/bundles/bundle_video.js:11681:12
	loadFunc http://127.0.0.1:8000/static/js/distributed/bundles/bundle_video.js:11555:9
	readystatechange http://127.0.0.1:8000/static/js/distributed/bundles/bundle_video.js:11485:13
```

**Comment by benjaoming** [comment]
I'm hoping some of the nice Mozilla people can give us more insight, otherwise we have to add a "know issue" on Firefox 50 not having subtitle support.

https://github.com/mozilla/vtt.js/issues/354

**Comment by bzbarsky** [comment]
@benjaoming Can you breakpoint in Parser.prototype.parse and see what object is being passed in as "data" from parseCues?

Where is parseCues coming from?  It doesn't look to be part of either this repo or vtt.js.

**Comment by bzbarsky** [comment]
Oh, and I would try with the "how to reproduce" from the original issue, but I can't find any clear directions on what to actually run to get the server up.

**Comment by benjaoming** [comment]
@bzbarsky Thanks! I guess our project is a it tedious to get running with a video + subtitles because we rely on a bit of data to be build...

But I've tried outlining the steps for debugging this particular error, this should be the simplest way to get started without reading too much of our dev guide :)

1. check out my PR branch: `git clone https://github.com/benjaoming/ka-lite.git` + `cd ka-lite` + `git fetch` + `git checkout origin/videojs-upgrade`
1. Create a virtual python env, `virtualenv venv`
1. Activate virtualenv, `venv/bin/activate`
1. Install dependencies, `pip install -r requirements_dev.txt`
1. Install NPM stuff, `npm install`
1. Create local database, `bin/kalite manage setup`
1. Retrieve English video data, `bin/kalite manage retrievecontentpack download en`
1. Run development server (this invokes `node build.js`) `bin/kalite manage runserver --settings=kalite.project.settings.dev`

When the server is running, create an admin user, go to the Manage -> Videos tab and fetch the "left-most" node in the tree: `Math -> Early Math -> Counting -> Counting Small Numbers -> Counting With Small Numbers`.

Then finally, go to the video that should have subtitles: http://127.0.0.1:8000/learn/khan/math/early-math/cc-early-math-counting-topic/cc-early-math-counting/counting-with-small-numbers/

**Comment by bzbarsky** [comment]
> Activate virtualenv, venv/bin/activate

I assume you mean `source venv/bin/activate`.

> Create local database, bin/kalite manage setup

For future reference, this produces:

    (venv)bash-3.2$ bin/kalite manage setup
    Traceback (most recent call last):
      File "bin/kalite", line 120, in <module>
        from kalite import cli
    ImportError: No module named kalite

Setting $PYTHONPATH to include `.` seems to help...

> create an admin user, go to the Manage -> Videos tab

I created an admin user during the "manage setup" bit.  But I see no "Manage" anywhere in the web UI.  There's a message saying to log in with the admin account, but no way I see to log in.

**Comment by bzbarsky** [comment]
Ah, I found it.  Have to click on "Learn", then make all the stuff that pops out go away, _then_ I get a login button.

**Comment by benjaoming** [comment]
@bzbarsky - oh, yes, sorry, I tried deviating a bit from the usual [dev guide](http://ka-lite.readthedocs.io/en/develop/developer_docs/environment.html), glad you figured it out, thanks for the patience :)

**Comment by bzbarsky** [comment]
OK.  So I'm seeing `WebVTT.Parser.prototype.parse` called with `data` set to a string.  That string is:

> WEBVTT
>
>NOTE Paragraph
>
>00:00:00.193 --> 00:00:03.311
>Put seven squirrels in the box.
>
>00:00:03.311 --> 00:00:04.505
>Alright

etc.  This string is then passed to `TextDecoder.decode`, which does in fact throw, per spec.

I tried Chrome dev  on the same page.  It throws the exact same exception from `TextDecoder.decode`, for the same reason.  Then I tried Firefox 49, and not surprisingly it throws the same exception for the same reason.  None of these seem to show subtitles on this video at first glance.

Looks like loadTrack is doing an XHR and then passing the responseBody to parseCues, which just passes it through.  And it's coming back as a string, not an arraybuffer.  This bit:

    var loadTrack = function loadTrack(src, track) {
      var opts = {
        uri: src
      };

      var crossOrigin = _utilsUrlJs.isCrossOrigin(src);
      if (crossOrigin) {
        opts.cors = crossOrigin;
      }

      _xhr2['default'](opts, Fn.bind(this, function (err, response, responseBody) {

Presumably something in there should set the responseType on the XHR to "arraybuffer"?

**Comment by bzbarsky** [comment]
So add `responseType: "arraybuffer"` to `opts`.

**Comment by benjaoming** [comment]
@bzbarsky - thanks!!

Firefox 49 and Chromium are working with the 0.12.1 version of vtt.js, so no alarm if they're producing the same errors now, I didn't investigate that part. Sounds good with the consistency :) Trying your suggestion pronto....

The `loadTrack` function is [part of video-js](https://github.com/gkatsev/video.js/blob/master/src/js/tracks/text-track.js#L62) btw.

**Comment by benjaoming** [comment]
Injecting `responsetype: "arraybuffer"` into the video-js code produces a new error:

```
TypeError: Member of DoubleOrAutoKeyword 'undefined' is not a valid value for enumeration AutoKeyword.  bundle_video.js:1124:22
	consumeCueSettings http://127.0.0.1:8008/static/js/distributed/bundles/bundle_video.js:1124:22
	parseCue http://127.0.0.1:8008/static/js/distributed/bundles/bundle_video.js:1159:5
	require<[756]</</WebVTT.Parser.prototype.parse http://127.0.0.1:8008/static/js/distributed/bundles/bundle_video.js:2124:15
	parseCues http://127.0.0.1:8008/static/js/distributed/bundles/bundle_video.js:11121:3
	loadTrack/< http://127.0.0.1:8008/static/js/distributed/bundles/bundle_video.js:11178:7
	ret http://127.0.0.1:8008/static/js/distributed/bundles/bundle_video.js:21959:12
	once/< http://127.0.0.1:8008/static/js/distributed/bundles/bundle_video.js:11682:12
	loadFunc http://127.0.0.1:8008/static/js/distributed/bundles/bundle_video.js:11556:9
	readystatechange http://127.0.0.1:8008/static/js/distributed/bundles/bundle_video.js:11486:13
```

...but this is the exact same error as was already defined in https://github.com/mozilla/vtt.js/issues/354

Which makes me wonder if somehow video-js manages to mix in its own 0.12.1 copy which it's apparently depending on, but I don't know quite how these JS libs are linked together, all I can see is that videojs depends on videojs-vtt.js and fetches this during `npm install`.

**Comment by bzbarsky** [comment]
> ...but this is the exact same error as was already defined in mozilla/vtt.js#354

Yep, that's what I got locally when I added the responseType too...

I certainly see two copies of vtt.js in bundle_video.js.  More generally, I see a copy in `ka-lite/node_modules/vtt.js/lib/vtt.js` and another copy in `ka-lite/node_modules/video.js/node_modules/videojs-vtt.js/lib/vtt.js` (and another in `ka-lite/node_modules/video.js/node_modules/videojs-vtt.js/dist/vtt.js` but I expect it's the same thing.

That said, at least in my checkout all the various copies of vtt.js involved are the old one, with cue.position being set to an object...

**Comment by benjaoming** [comment]
@bzbarsky yeah, there's a lot of stuff flying around... everything in `node_modules` is "intermediate" code used to bundle together things. Magic happens with `node build.js`, then afterwards special directories `kalite/<app-name>/static/` are served by the development HTTP server. I have no clue which vtt.js is used where :)

Trying to work on a separate copy of video.js to see if I can force the latest vtt.js master branch to be used.

**Comment by benjaoming** [comment]
From testing manually, issue seems fully fixed with #5349

**Comment by radinamatic** [comment]
Seeing the subtitles in 0.17b3, yey!!! :+1: 

One detail, though, they seem somewhat weirdly aligned:

![ubuntu15 10 pip install static 0 17b3 running - oracle vm virtualbox_076](https://cloud.githubusercontent.com/assets/1457929/20990024/4756bf8a-bcd7-11e6-9798-d31ba2dbe7d3.png)

**Comment by benjaoming** [comment]
Oh dear :( I haven't changed anything in that regard :( Is your screenshot perhaps warped because you created the webdev sidebar AFTER the script had aligned the subtitles?

...They were showing up fine on my FF 50.

**Comment by radinamatic** [comment]
Nope, it happens even without the sidebar:

![selection_077](https://cloud.githubusercontent.com/assets/1457929/21010453/67d76d98-bd4c-11e6-9036-c5ea6f54589f.png)

**Comment by benjaoming** [comment]
Working fine here on Ubuntu with the latest FF

![screenshot from 2016-12-17 01-17-23](https://cloud.githubusercontent.com/assets/374612/21282591/05f8eb7c-c3f7-11e6-86c8-e8d354055e01.png)

What are you using and can you describe any circumstances that you would suspect to cause this?

**Comment by benjaoming** [comment]
@radinamatic - I'm closing this, could you re-open another issue describing how you reproduce the misplaced subtitles and on which browsers?
