### ISSUE TITLE
Device registration: User message in case of connection failure

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#5348]
## Suggested change

Old:

``` 
 <p>{% trans "The device needs to have internet access when first being registered. Please ensure it is connected to the internet, and then" %} <a href="." class="refresh-link">{% trans "refresh this page" %}</a>.</p>
``` 

New:

``` 
<p>{% trans "The device needs internet access in order to be registered. Please ensure you are connected to the internet, and then" %} <a href="." class="refresh-link">{% trans "refresh this page" %}</a>. If you are still getting this message, it might indicate a temporary problem with the central server. Please wait a few minutes and try again later.</p>
``` 

...in `python-packages/securesync/templates/securesync/register_public_key_client.html`

## Summary

~KA Lite seems unable to connect to register the device in order to download the videos & languages. Refreshing the page has no effect, and the machine is correctly connected to Internet (see the loaded elpais.com in the other window).~

~Is `staging.learningequality.org` where the device register happens? It seems to be running OK, so the culprit might be other.~

## Screenshots

![virtualbox_windows 7_30_11_2016_13_46_49](https://cloud.githubusercontent.com/assets/1457929/20752815/9486453e-b703-11e6-90f5-01631c996870.png)

**Comment by benjaoming** [comment]
Just experienced exactly the same on FF, Ubuntu 0.16.9 installation.

@radinamatic are you able to reproduce this for 0.16.9 in all cases? It might be a server-side issue..

**Comment by benjaoming** [comment]
Also, try running the server with `kalite start --foreground` in order to get more logging and see what it says at the exact moments of registration.

**Comment by radinamatic** [comment]
Apparently, one-click registration on WXP is working today:

![virtualbox_wxp_14_12_2016_14_47_52](https://cloud.githubusercontent.com/assets/1457929/21184398/9b790480-c20c-11e6-8e44-d70819a63efe.png)


![virtualbox_wxp_14_12_2016_14_49_17](https://cloud.githubusercontent.com/assets/1457929/21184404/a136de74-c20c-11e6-816c-739c1f256849.png)

**Comment by radinamatic** [comment]
Works on Ubuntu too, fresh 0.16.9 install:

![virtualbox_gubuntu_14_12_2016_15_04_36](https://cloud.githubusercontent.com/assets/1457929/21184915/d5877f56-c20e-11e6-9c99-993c9484e8dd.png)

Seems it's most likely the temporary problem with our server, so I suggest changing [this line](https://github.com/learningequality/ka-lite/blob/84ac76a71177ad2e656728b103e781b9cf3ad820/python-packages/securesync/templates/securesync/register_public_key_client.html#L48) into:

`<p>{% trans "The device needs internet access in order to be registered. Please ensure you are connected to the internet, and then" %} <a href="." class="refresh-link">{% trans "refresh this page" %}</a>. If you are still getting this message, it might indicate a temporary problem with the central server. Please wait a few minutes and try again later.</p>
`

**Comment by benjaoming** [comment]
@radinamatic okay the string freeze is up, but I think you are hinting at two issues:

1. a possible issue with network connectivity during registration, could be related to other DNS issues we've discussed
1. a user message change.

I'm altering the issue to be about the latter, if you have more information to provide on the first subject, please open a new issue.

**Comment by benjaoming** [comment]
Changed description.

**Comment by radinamatic** [comment]
@benjaoming User message change is generic enough in order to cover multiple connection issues. If the string freeze is up, does that mean it will not make it for the 0.17?

**Comment by benjaoming** [comment]
@radinamatic - that would have been the standard policy, however I don't see a problem adding an error message in this case and it gets released untranslated, it's an error message after all.

**Comment by benjaoming** [comment]
It's freezing up again in 0.16.9. The same in 0.17.0. Still not seeing any useful log messages: No JS error, no server-side error, no connection error from the browser. Everything is stuck at this picture:

![screenshot from 2017-01-31 17-56-53](https://cloud.githubusercontent.com/assets/374612/22475330/e6f03094-e7de-11e6-8ac3-f829a93d2eaa.png)

**Comment by benjaoming** [comment]
I have Wiresharked myself during this error message. No network activity at all during the error message.

**Comment by benjaoming** [comment]
Maybe relevant: https://github.com/learningequality/ka-lite-content-packs/issues/58#issuecomment-276950139

**Comment by benjaoming** [comment]
Connection failures seem to be reproducing across the spectre. Downloading `all_metadata.json` is also failing. Suspecting new CSP / CORS stuff to be the cause.

**Comment by benjaoming** [comment]
I'll try this: https://github.com/ottoyiu/django-cors-headers/

**Comment by rtibbles** [comment]
Adding dataType to `jsonp` might be sufficient to fix this: https://github.com/learningequality/ka-lite/blob/master/kalite/updates/static/js/updates/bundle_modules/update_languages.js#L35

So this options object becomes:
```
{
    cache: false,
    dataType: "jsonp"
}
```

**Comment by benjaoming** [comment]
Hmm, I tried to update django-cors-headers to work with Django 1.5.. which was a rabbit hole.

Trying @rtibbles 's suggestion to change to `jsonp`..

**Comment by benjaoming** [comment]
@rtibbles oh yes, I tried that yesterday, we need to list out the json fields, too, but seems plausible. Will PR soon..

**Comment by benjaoming** [comment]
Changed to `jsonp` but the request is still never received by Pantry, and XHR `.fail` is still called straight-away.

**Comment by benjaoming** [comment]
Thanks Chromium, this error message helps a lot :)

> XMLHttpRequest cannot load http://pantry.learningequality.org/downloads/ka-lite/0.17/content/contentpa…ata.json?callback=jQuery21407293127653173606_1486484313736&_=1486484313737. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8000' is therefore not allowed access. The response had HTTP status code 405.

**Comment by benjaoming** [comment]
Some gateway in front of the Pantry server seems to be giving a 405 when the browser tries to retrieve CORS policies:

```
jquery.js:8630 OPTIONS http://pantry.learningequality.org/downloads/ka-lite/0.17/content/contentpa…ta.json?callback=jQuery214017264082951495596_1486485490415&_=1486485490416 405 (Not Allowed)
```

Can someone please tell me why we even have a gateway in front of Pantry and if we can lower the complexity level a bit here? :)

**Comment by radinamatic** [comment]
Pinging @aronasorman :sos:

**Comment by benjaoming** [comment]
Okay, we got through the diversion - actually the problem was a misconfiguration of pantry.learningequality.org and that's been fixed.

We can concentrate on the original issue about the user message.

**Comment by radinamatic** [comment]
[Latest screencast is here](https://github.com/learningequality/ka-lite/issues/5401#issuecomment-278636528).

**Comment by mrpau-eugene** [comment]
Has anyone filed a PR on updating the user message in case the internet is unavailable or gets disconnected?

**Comment by benjaoming** [comment]
@mrpau-eugene no, this issue is still unsolved and relevant, PR is welcome!
