### ISSUE TITLE
Can't install ka-lite with setuptools >= 30.0.0

### ISSUE THREAD

**Issue by bochecha** [learningequality/ka-lite#5352]
## Summary

setuptools 30.0.0 (and above) refuses to install a module which specifies full paths for its data files, which ka-lite does.

## System information

This fails with all releases of ka-lite uploaded to Pypi.

I reproduced it on Debian Jessie and Fedora 24, but that doesn't matter.

The problem is with setuptools >= 30.0.0

## How to reproduce

In a virtual environment:

```
$ pip install --upgrade setuptools
$ pip install ka-lite
[... snip ...]
    writing manifest file 'ka_lite.egg-info/SOURCES.txt'
    error: Error: setup script specifies an absolute path:
    
        /tmp/pip-build-ISZyAg/ka-lite/kalitectl.py
    
    setup() arguments must *always* be /-separated paths relative to the
    setup.py directory, *never* absolute paths.
```
## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

This makes it impossible to install ka-lite in an environment with a recent setuptools.

For example, just creating a virtual environment with a recent `virtualenv` command will install the latest setuptools.

**Comment by benjaoming** [comment]
Well, I feel sort of proud that I already anticipated this development :)

The reason is that the concept of `data_files` has been somewhat disputed, and in `wheels`, it was basically abolished, although some Frankenstein still remains.

In 0.17, we don't use them anymore.

So you *could* run the new beta:  `pip install --pre`

Other than that, this is fixed in #5285

**Comment by benjaoming** [comment]
Also, thanks for reporting! I didn't know that it has been abolished even in setuptools.

I'm trying to get 0.17 out as quickly as possible.

**Comment by bochecha** [comment]
> So you could run the new beta: pip install --pre

Which fails to install as well, albeit for different reasons. (but I guess I should create a different ticket for that?)

**Comment by benjaoming** [comment]
@bochecha yes please feel absolutely welcome to create a ticket for any issues with 0.17, they will be highly prioritized, and we appreciate all the testing we can get of the next release.

**Comment by benjaoming** [comment]
Added a release note about the issue, but since it's already fixed, I can't really do more, will just have to wait for 0.17 to be out and meanwhile use prereleases.

Thanks for reporting @bochecha
