### ISSUE TITLE
KA Lite Admin - Topic Tree not Loading

### ISSUE THREAD

**Issue by rjoommen** [learningequality/ka-lite#5370]
## Summary

I'm new to KA Lite and an ADMIN.  I have installed the latest version of KA Lite twice now and when I sign in and go to the manage videos tab, I get a message:  "Loading topic tree... Please wait!"  (where the tree view of courses should appear) - see screencapture file attached.

Has anyone seen this before? and any ideas on what I need to try.  I am not a technical admin.

Thanks very much in advance for any help anyone can provided.

RJ

![capture](https://cloud.githubusercontent.com/assets/24686503/21370962/8ad42ba8-c6dc-11e6-8d7b-2a51eaa5cf1c.PNG)

## System information

*Please specify the KA Lite version you were using and your operating system!*

 - Operating system: ? Windows 8.1
 - Version: 0.16.? IE 11
 - Browser: ? IE 11 (same result in Chrome Version 55.0.2883.87 m)
 

## Traceback or relevant snippet from server.log

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

1. Steps
1. To
1. Reproduce

## Screenshots

*If applicable*

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

*If applicable*

**Comment by benjaoming** [comment]
@rjoommen - How much time do you wait? Also, can you see any Javascript errors?

Help regarding opening the debugging panel in IE11: https://msdn.microsoft.com/en-us/library/dn255006(v=vs.85).aspx

**Comment by benjaoming** [comment]
Also no, this is not an issue we've been seeing. KA Lite 0.16.x has been out for a long time :)

How did you install?

**Comment by rjoommen** [comment]
HI Benjamin,
It seems to hang for hours...never loads.  No javascript errors that I can see...although it certainly appears to be a browser issue.  In any case, I did do a re-install on a different computer and was successful.   
Thank you very much for your response and willingness to assist!!
Merry Christmas and Happy Holidays!
RJ
