### ISSUE TITLE
KHAN Lite not working...macOS Sierra ver. 10.12.2 Error: kalite_startup.lock

### ISSUE THREAD

**Issue by whatabearthinks** [learningequality/ka-lite#5374]
## Summary

*Briefly describe what this is about*

## System information

*Please specify the KA Lite version you were using and your operating system!*

 - Operating system: ?
 - Version: 0.16.?
 - Browser: ?

## Traceback or relevant snippet from server.log

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

1. Steps
1. To
1. Reproduce

## Screenshots

*If applicable*

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

*If applicable*

**Comment by whatabearthinks** [comment]
Not sure how GitHub works, so please excuse me if this is the wrong the way to address my problem...

**Comment by mrpau-richard** [comment]
Hi @whatabearthinks, this issue It's already been reported by @radinamatic at [Issue #5333](https://github.com/learningequality/ka-lite/issues/5333).

**Comment by whatabearthinks** [comment]
Thanks @mrpau-richard! I'll look there. Sincerely appreciate it.
