### ISSUE TITLE
Ka-lite 16.9 not starting on boot

### ISSUE THREAD

**Issue by case485** [learningequality/ka-lite#5382]
## Summary

Ka-lite not starting on boot - 

ON CLIENT BROWSER: 
"KA-Lite might be busy - wait a few moments and then reload this page 
If KA-Lite is still busy, get help from the system administrator
Error code: nginx 502 Bad Gateway (maybe the KA-Lite webserver is not working correctly)

ON KALITE Pi Server: 
I can kill nginx processes running on port 8008 then restart kalite : kalite start and it loads just fine. 
## System information
Kalite 16.9
Raspberry Pi
Install method:
		apt-get install python-m2crypto
		apt-get install python-pkg-resources	
		apt-get install nginx
		apt-get install python-psutil		
		wget https://learningequality.org/r/deb-pi-installer-0-16 --no-check-certificate 
                --content-disposition
		dpkg -i ka-lite-raspberry-pi*.deb

KA Lite diagnostics

KA LITE VERSION:      0.16.9
PYTHON:                   2.7.9 (default, Sep 17 2016, 20:26:04) 
[GCC 4.9.2]
PLATFORM:             Linux-4.4.38-v7+-armv7l-with-debian-8.0
SERVER PROXY:         http://172.24.1.1:8008/
SERVER PROXY:         http://192.168.10.102:8008/
SERVER PROXY:         http://127.0.0.1:8008/
SERVER STATUS:        Unclean shutdown
INSTALLED IN:         /usr/lib/python2.7/dist-packages/kalite
CONTENT ROOT:         /home/pi/.kalite/content
CONTENT SIZE:         0 octet
USER DATABASE:        /home/pi/.kalite/database/data.sqlite
DEVICE NAME:          raspberrypi
DEVICE ID:            5ec5873b8e76571c942bb8f530e3c981
DEVICE REGISTERED:    False
SYNCED:               Never
SYNC RESULT:          -
ZONE ID:              Unset

## Traceback or relevant snippet from server.log

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

1. Steps
1. To
1. Reproduce

## Screenshots

*If applicable*

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

*If applicable*

**Comment by benjaoming** [comment]
Hi @case485

You should start KA Lite as a system service.

```
kalite stop  # In order to stop it if it's already running
/etc/init.d/ka-lite start
```

The reason is that ka-lite should run on port 7007, this happens when you invoke the system service.

Please let me know if the suggestion works.

**Comment by case485** [comment]
Thanks for the reply. Unfortunatly this did not work, I did mutilple installs using the following process : 

I tried both a dpkg process and the ppa : 

		apt-get update && apt-get upgrade
		apt-get install python-m2crypto
		apt-get install python-pkg-resources	
		apt-get install nginx
		apt-get install python-psutil		
		if [ "$1" == "dpkg" ]; then
			echo "In the Update KA LITE Funcion ; DPKG Option"

			wget https://learningequality.org/r/deb-pi-installer-0-16 --no-check-certificate --content-disposition
			dpkg -i ka-lite-raspberry-pi*.deb
			test_outcome "Starting updateKalite Function "
			#/usr/bin/sudo /bin/su pi -c '/usr/bin/kalite manage retrievecontentpack download fr'
			#echo -e "\nLANGUAGE_CODE = \"fr\" \n" >> /home/pi/.kalite/settings.py
			test_outcome "Exiting updateKalite Function "
		elif [ "$1" == "ppa" ]; then 
			echo "In the Update KA LITE Funcion ; PPA Option"
			apt-get install -y software-properties-common python-software-properties
			echo "deb http://ppa.launchpad.net/learningequality/ka-lite/ubuntu trusty main" >> /etc/apt/sources.list.d/learningequality-ka-lite-trusty.list
			sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 74F88ADB3194DD81
			add-apt-repository ppa:learningequality/ka-lite
			apt-get -y install ka-lite
			test_outcome "Installing Ka-Lite"
		fi

Durring the Kalite setup process I always choose YES to run as a service. 
ON reboot i connect from a client machine to the Pi on port 8008 and get  : 

KA-Lite might be busy - wait a few moments and then reload this page 
If KA-Lite is still busy, get help from the system administrator
Error code: nginx 502 Bad Gateway (maybe the KA-Lite webserver is not working correctly)

When I check on the PI with :
$ kalite status
Stopped(1)

$kalite start
Port 8008 occupied....

Then i can kill -9 all nginx processes and restart kalite
$ sudo killall -9 nginx
$ kalite start 
.... http:192.168.10.105:8008
..... Going into daemon mode 

All good. 

From the client browser I now get the kalite "Create admin account box" as expected. 

There seems to be some issue with the startup script or the version of nginx

**Comment by benjaoming** [comment]
@case485 in your examples, you haven't invoked the system process.

Running KA Lite by simply issuing `kalite start` will run it on port 8008, i.e. the port that Nginx is occupying. That's how it's supposed to be. Running `sudo service kalite start` will run KA Lite on port 7007 which is the port that Nginx proxies to... if nothing is running on 7007, Nginx will issue "Bad Gateway".

**Comment by case485** [comment]
That works and thank you very much for your patience. My question is that I have been running Ka-lite for several years now and have never had to do that before, when the install process asks me if i want to startup kalite as a sytem process on boot i always select yes there and have never had to do anything else until now. 

To ensure that kalite starts at boot, do i need to add the "service ka-lite start" to the rc.local file?

Thanks again.

Chad

**Comment by benjaoming** [comment]
Hi @case485 !

You can register it as a script to be started with default settings like so:

    sudo update-rc.d ka-lite defaults

Adding it to `rc.local` is also an option, but you might as well start the system service in the conventional way :)

There might, however, be reasons as to why it isn't running. You can troubleshoot with:

    journalctl -u ka-lite
    # or sudo less /var/log/syslog

**Comment by benjaoming** [comment]
I'm closing this since it seems things are working, otherwise issues are with ka-lite-raspberry-pi, but all the debian installers have had their system service script changed because of systemd compatibility. So should expect different behavior in 0.17.
