### ISSUE TITLE
206 server response for mp4 files on Ubuntu

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#5384]
## Summary

I've been concentrating on subtitles lately, that I just now realized that videos are not actually playing neither in FF nor in Chromium on Ubuntu. They apparently load and one can advance by clicking on the progress slide-bar, but video does not reproduce.

## System information

 - Operating system: Ubuntu 16.10
 - Version: 0.17b4
 - Browser: both Firefox & Chromium
 - Ubuntu restricted extras installed, both browsers have no extensions/addons

## Traceback or relevant snippet from server.log

Only one warn in the console, but I can't see the relevance:

```
VIDEOJS: WARN: Calling addRemoteTextTrack without explicitly setting the "manualCleanup" parameter to `true` is deprecated and default to `false` in future version of video.js
```
Servers response is 206 `partial content`, might be the reason?

## How to reproduce

1. Install 0.17b4
1. Download some videos

## Screenshots

FF:
![virtualbox_ubuntu 16 10_17_01_2017_14_23_43](https://cloud.githubusercontent.com/assets/1457929/22022058/9ad0fb36-dcc0-11e6-8727-3d60e79d3a0d.png)

Chromium:
![virtualbox_ubuntu 16 10_17_01_2017_14_22_23](https://cloud.githubusercontent.com/assets/1457929/22022065/a9f28378-dcc0-11e6-92c2-2ba7bffae0c2.png)

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

Troubling, to say the least... 🤔 
@benjaoming I'm tagging this `release-blocker` until further notice! I'll try to replicate in other Linux VMs asap.

**Comment by radinamatic** [comment]
VM Gnome Ubuntu 16.10, same issue:

FF:
![virtualbox_gubuntu_17_01_2017_14_52_28](https://cloud.githubusercontent.com/assets/1457929/22023012/b95fae36-dcc4-11e6-84f0-7223a2014304.png)

Chrome:
![virtualbox_gubuntu_17_01_2017_14_50_35](https://cloud.githubusercontent.com/assets/1457929/22023033/d130a100-dcc4-11e6-8dff-5d52e249b13c.png)

**Comment by benjaoming** [comment]
@radinamatic and you've installed the mp4 video codecs?

http://ka-lite.readthedocs.io/en/develop/installguide/system_requirements.html#video-playback

**Comment by benjaoming** [comment]
Unable to reproduce both with Cherrypy and Django development server.

**Comment by radinamatic** [comment]
Weird, I just opened an older VM with Ubuntu 15.10 where I had 0.17.b4 installed 2 weeks ago, but was having the left-aligned subs in Firefox 47 - subs are still on left, but the video is playing:

![virtualbox_ubuntu15 10-0 17b4](https://cloud.githubusercontent.com/assets/1457929/22030700/c03b4a2a-dcde-11e6-9b93-3f49f519b506.png)

I'm going to upgrade FF to 50 and see what happens...

**Comment by radinamatic** [comment]
@benjaoming Yes, as noted above, `Ubuntu restricted extras` are installed, but that was never required in Chrome for correct video playback.

**Comment by benjaoming** [comment]
@radinamatic does installing it change, though? Chrome might have switched to using native system libraries?

**Comment by radinamatic** [comment]
AFAIK `Ubuntu restricted extras` have always been required only by FF, because of some licensing issues that Chrome does not have. And those codecs were installed prior to KA Lite on this VM.

Anyway, upgrading FF to 50 did not bring the issue here, so I'm unable to repro what I reported initially on this third VM - `206` response is present, but videos play OK:

![virtualbox_ubuntu15 10-0 17b4-2](https://cloud.githubusercontent.com/assets/1457929/22032120/65f655f0-dce3-11e6-8f77-7878977f2c53.png)

**Comment by radinamatic** [comment]
I've installed a completely new Ubuntu 15.10 VM on the same OSX host as the original issue, and the problem persists. Since I'm unable to reproduce it on my home MiniMac as a host (post above), leads me to believe this might have something to do with the host itself. 🤔 

I'll make one more run at it with Ubuntu host just to cover all basis, and we'll take it from there...

**Comment by benjaoming** [comment]
Thanks @radinamatic - will keep fingers crossed that it's your host :) Try ensuring that video drivers for the VM are installed?

**Comment by radinamatic** [comment]
Closing this as it seems to be limited to guest VMs on only one of three host machines where I've tested it.
