### ISSUE TITLE
unexpected error - no such table

### ISSUE THREAD

**Issue by nakam28** [learningequality/ka-lite#5388]
## Summary
I installed KA Lite version 2016.20 on an RACHEL-Plus (Intel CAP) when I open KA Lite I get the error message as shown in the screen shot below.

*Briefly describe what this is about*
When I click on any item in KA Lite I get an error message " [unexpected error - no such table]"

## System information

Hardware	        i686

RACHEL Installer	1-2-16_9.1.1 *
Kiwix	                0.9 *
Content Shell	      v2.2.2

*Please specify the KA Lite version you were using and your operating system!*
                    
 - Operating system:  Ubuntu precise (12.04.3 LTS)
 - Version:  KA Lite	                0.16.9-0ubuntu3 *
 - Browser: Chrome Version 55.0.2883.87 (64-bit)

## Traceback or relevant snippet from server.log

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

1. Steps
1. Install KA Lite module (en-kalite) via RACHEL-Plus from http://dev.worldpossible.org/cgi/rachelmods.pl
1. Reproduce
When file download is comple click any item on KA Lite page
## Screenshots

![unexpected error - no such table](https://cloud.githubusercontent.com/assets/24987742/22068186/24447296-dd8c-11e6-981c-af7d328a9592.jpg)

![rachel version info](https://cloud.githubusercontent.com/assets/24987742/22068216/3b409b1e-dd8c-11e6-9b5b-e724225c5b1a.png)
![modules_installed](https://cloud.githubusercontent.com/assets/24987742/22069031/f283d65e-dd8e-11e6-86b0-16098a9eaf64.png)

*If applicable*

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)
Unable to access KA Lite
*If applicable*

**Comment by benjaoming** [comment]
@nakam28 RACHEL runs KA Lite as the `root` user IIRC.

You may have data from RACHEL's installation that's in use and then installed a newer KA Lite on top of it?

In that case, try running (as the correct user, probably, `root`):

    kalite manage setup

**Comment by nakam28** [comment]
@benjaoming - Many thanks for yor response.
KA Lite is running on the RACHEL-Plus server - it uses the Intel Content Access Point CAP). 
Can you please explain to me how to run the command "kalite manage setup" as a root on the RACHEL_Plus server?
Many Thanks

**Comment by nakam28** [comment]
@benjaoming - I have just run the command "kalite manage setup" on the CAP. 
And get the following "**Warning message**":
_**[WARNING] [2017-01-19 11:48:39,241] root: It's recommended that you install Python version 2.7.6. Your version is: 2.7.3**_
Do I have to install Python version 2.7.6 as suggested? If yes how?
![manage_kalite_setup](https://cloud.githubusercontent.com/assets/24987742/22106094/fbc575c8-de3e-11e6-9627-aedd02bda0ef.png)

**Comment by benjaoming** [comment]
@nakam28 - the warning regarding Python version... I cannot remember exactly why we did this, I have tried searching a bit around. Anyways, you can probably use KA Lite with Python 2.7.3.

> Can you please explain to me how to run the command "kalite manage setup" as a root on the RACHEL_Plus server?

It looks from your screenshots as if you are confusing your laptop and the server?

It seems like you are logging into the server on `192.168.88.1` and then running `kalite manage setup` correctly. You should presse `[enter]` to continue as the text suggests.

**Comment by benjaoming** [comment]
I'm not sure what to do about this issue, but RACHEL has AFAIK already updated to the latest KA Lite, and it's difficult for us to troubleshoot why the above error has occurred. Somehow, the database didn't get properly created during the setup - and the fix is to run `kalite manage setup` to create it.

Thanks for the report @nakam28 - hope you'll get your deployment working nicely! Please ask away in our Community Forum if you have any further questions - http://community.learningequality.org/
