### ISSUE TITLE
Online registration confirmation email undelivered

### ISSUE THREAD

**Issue by Faustusone** [learningequality/ka-lite#5392]
## Summary

I am not receiving the verification email when registering my account.

## System information

*Please specify the KA Lite version you were using and your operating system!*

 - Win 7
 - Version: Latest windows version.
 - Chrome
- I use gmail

## N/A

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

1. Start server
2. login with account
3. Register account
4. Nothing

## Screenshots

*If applicable*

## Real-life consequences (anything community should be aware, for instance how it affects your deployment) 

*If applicable*

**Comment by benjaoming** [comment]
@Faustusone where do you register your account? On http://hub.learningequality.org/ ?

**Comment by Faustusone** [comment]
I registered with KA lite through 127.0.0.1:8008.  It allows me to register
my initial account but when I register my device I enter all the necessary
information name, surname, email address, password etc. I get the message
that I will receive an email to verify my account. Yet I haven't received
an email yet.

Thanks for your time.

**Comment by benjaoming** [comment]
Thanks for reporting and explaining, I understand now. Checked it, too.. it seems after 30 minutes of waiting that it indeed doesn't work.

**Comment by Faustusone** [comment]
It's a pleasure.

**Comment by Faustusone** [comment]
Could you please message me when it's up again. Thanks.

**Comment by benjaoming** [comment]
@Faustusone sorry that this is taking so long, I'm handling it as soon as I've been transfered credentials to the server that sends out our emails so I can diagnose this.

**Comment by Faustusone** [comment]
No problem. Thanks for the assistance.

**Comment by benjaoming** [comment]
Sorry that this is taking a long time @Faustusone 

We were out of credits with out email provider! *blushes*

It's all fixed now, but the confirmation email from 6 days ago has unfortunately been removed from the queue, meaning you would have to request a new account.

THANKS for reporting this!!

**Comment by benjaoming** [comment]
Actually, I *have* received my confirmation email from 5 days ago, so you might have, too :)

**Comment by Faustusone** [comment]
Thanks for the help, Yip I got my email I'm busy downloading the videos now.
