### ISSUE TITLE
Register Device failed in 0.17.0

### ISSUE THREAD

**Issue by shuaiye1999** [learningequality/ka-lite#5413]
## Summary

After I install 0.17.0, and start the service. I goto manage tab, and click "Register Divece",
and choose the left one to register. then I get:
"
Error
Sorry, but there was an error while trying to load the page.

(TypeError: __init__() takes exactly 3 arguments (1 given))

"

## System information

 - Operating system: OSX 10.9.5
 - Version: 0.17.0
 - Browser: Chrome and Safari

## Traceback or relevant snippet from server.log
2017-02-18 09:17:22 Stopped (1)

2017-02-18 09:17:23 Running 'kalite start' as daemon (system service)

Stand by while the server loads its data...

2017-02-18 09:17:23 Going to daemon mode, logging to /Users/shuaiye1999/.kalite/server.log

2017-02-18 09:17:24 Not responding (5)

2017-02-18 09:17:25 COMMAND    PID        USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Google     205 shuaiye1999  139u  IPv4 0xbf0ddc3d0c27b5f7      0t0  TCP localhost:52791->localhost:http-alt (CLOSE_WAIT)
Google     205 shuaiye1999  165u  IPv4 0xbf0ddc3d0c23ae0f      0t0  TCP localhost:52792->localhost:http-alt (CLOSE_WAIT)
Google     205 shuaiye1999  167u  IPv4 0xbf0ddc3d0c2695f7      0t0  TCP localhost:52793->localhost:http-alt (CLOSE_WAIT)
Google     205 shuaiye1999  172u  IPv4 0xbf0ddc3d089405f7      0t0  TCP localhost:52794->localhost:http-alt (CLOSE_WAIT)
Google     205 shuaiye1999  176u  IPv4 0xbf0ddc3d0c29d5f7      0t0  TCP localhost:52795->localhost:http-alt (CLOSE_WAIT)
Google     205 shuaiye1999  177u  IPv4 0xbf0ddc3d0c1e35f7      0t0  TCP localhost:52796->localhost:http-alt (CLOSE_WAIT)
Python    3515 shuaiye1999    3u  IPv4 0xbf0ddc3d0c4b9e0f      0t0  TCP localhost:54083->localhost:http-alt (CLOSED)
Python    3515 shuaiye1999    8u  IPv4 0xbf0ddc3d0c216e0f      0t0  TCP *:http-alt (LISTEN)

2017-02-18 09:17:26 OK, running (0)
KA Lite running on:

	http://127.0.0.1:8008/
	http://192.168.3.2:8008/

2017-02-18 09:17:27 Running 'kalite start' as daemon (system service)

Stand by while the server loads its data...

2017-02-18 09:17:27 Refusing to start: Already running
Use 'kalite stop' to stop the instance.

2017-02-18 09:17:28 OK, running (0)
KA Lite running on:

	http://127.0.0.1:8008/
	http://192.168.3.2:8008/

2017-02-18 09:17:30 OK, running (0)
KA Lite running on:

	http://127.0.0.1:8008/
	http://192.168.3.2:8008/

## How to reproduce

1. Start server
2. open in browser
3. select "manage" tab
4. click "register device"

## Screenshots

*If applicable*
![image](https://cloud.githubusercontent.com/assets/25855988/23088888/7444f976-f5bc-11e6-8ab9-2561474bafc2.png)

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

*If applicable*

**Comment by shuaiye1999** [comment]
and python version is the version in README:

shuaiye1999deMacBook:~ shuaiye1999$ python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 26 2016, 12:10:39) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by benjaoming** [comment]
Thanks for reporting this @shuaiye1999 - it seems that the Mac installer built yesterday has been based off out-of-date source code. We need to rebuild it.

Meanwhile, the 0.16.9 installer is reported to work fine for registration: http://pantry.learningequality.org/downloads/ka-lite/0.16/installers/mac/KA-Lite-0.16.9.pkg

After registering your device using 0.16.9, you can upgrade to 0.17.0.

**Comment by mrpau-richard** [comment]
Hi @benjaoming your right the latest KA Lite OS X installer is built in out-of-date source code. Here’s the newly built and signed [KA Lite OS X installer](https://drive.google.com/open?id=0B5Tyi-tRKOFMX2dTZ3ZfQWR5c2M). I also tested it with no issue on device registration.

**Comment by shuaiye1999** [comment]
thanks you guys。@benjaoming @mrpau-richard
so when it will be available officially?
I cannot access the folder @mrpau-richard  mentioned.

**Comment by mrpau-richard** [comment]
Hi @shuaiye1999 the linked I posted is not an official KA Lite OS X installer for the public user. We will inform you when @radinamatic , @benjaoming & @arnoan verify and  upload it in the  [pantry](http://pantry.learningequality.org/downloads/ka-lite/0.17/installers/).

**Comment by mrpau-richard** [comment]
@shuaiye1999 KA Lite OS X installer 0.17 released has been updated at [panty](http://pantry.learningequality.org/downloads/ka-lite/0.17/installers/mac/KA-Lite-0.17.0.dmg)

**Comment by benjaoming** [comment]
Closing this, please feel welcome to report any further issues @shuaiye1999 and thanks for creating this one!
