### ISSUE TITLE
Unable to Install French Contentpack...help!

### ISSUE THREAD

**Issue by Burkina-Faso** [learningequality/ka-lite#5414]
I am a Peace Corps Volunteer living in a small village in Burkina Faso, West Africa.  We have a computer lab with ten computers at our one Lycée.  I have successfully downloaded KA Lite in English (Windows) and installed it one of our computers as a test run.  

However, I also need to import the French version of KA Lite.  I have downloaded the fr.zip contentpack but I cannot figure out how to import that contentpack into the existing English version of KA Lite.  Once, I've logged into KA Lite I see that it is possible to download the French contentpack but that also doesn't work.

I would greatly appreciate some guidance as to how I can successfully install without an internet connection an English/French version of KA Lite onto our ten computers.  Our 600 some students would definitely appreciate it as well!

**Comment by benjaoming** [comment]
Hello @Burkina-Faso 

I see what you mean, and it's true that there is only a graphical user interface for downloading the content packs. We have only put an effort into create a command line for this use case.

On Windows, open up a command line `WIN+R`, then type `cmd`.

Navigate to where the `kalite` command is available and press ENTER.

    cd C:\Python27\Scripts

The run the command, giving it the correct path to your content pack.

    kalite manage retrievecontentpack local fr C:\Path\To\File

If you have further questions, please ask away in the support community forums :)

http://community.learningequality.org/

**Comment by Burkina-Faso** [comment]
You are amazing, Benjamin!

Thank you!!
