### ISSUE TITLE
Not able to register device after upgrade

### ISSUE THREAD

**Issue by kurund** [learningequality/ka-lite#5418]
## Summary

Initial setup was of Kalite 0.16.5 installed using pip install. I tried upgrading it to 0.17 version using dpkg method. It didn't work. Hence after Jamie's suggestion on #kalite I uninstalled it using pip uninstall. Then did a fresh install of 0.17 with existing backup. Installation was using dpkg method. After that I did "kalite manage setup" and then "kalite manage contentpackchecker all --update"
Everything went smoothly without any issues.

However now when I am trying to register the device it just keeps reloading.http://localhost:8008/?login=true&next=/securesync/register/

There are no errors in chrome console and in .kalite/server.log

## System information
Upgraded 0.16.5 to 0.17 on Ubuntu

 - Operating system: Ubuntu
 - Version: 0.16.5
 - Browser: Chrome

## Traceback or relevant snippet from server.log

```
There are no errors in chrome console and in .kalite/server.log
```

## How to reproduce
Follow the steps in summary

**Comment by mrpau-eduard** [comment]
Can you give us a screen shoot that you are using the 0.17 release. The registration issue is already fixed on the latest release. Can you post also the `server. log` so we can help you debug the issue.

**Comment by mrpau-eduard** [comment]
This issue is fixed https://groups.google.com/a/learningequality.org/forum/#!topic/dev/V2iWK1Ycos4
