### ISSUE TITLE
Question: are symlinks discovered

### ISSUE THREAD

**Issue by tim-moody** [learningequality/ka-lite#5428]
If I create a separate videos directory with all downloaded videos and create a symlink to each of them in content will the menu item Scan content folder for videos find them or does it check for an actual file?

**Comment by benjaoming** [comment]
@tim-moody

Why not symlink the whole `content` directory?

I've tested symlinking a video, and it works fine for me. Remember to take thumbnails into consideration, too, for what you're working on. But I can't honestly - from intuition - see that creating thousands of symlinks sounds like the right path ;)

Please in the future, use our [community support forum](http://community.learningequality.org/) for simple questions.
