### ISSUE TITLE
Not seeing Pictures display in 0.17.0 (multiple browsers) similar to: picture not displaying #5140

### ISSUE THREAD

**Issue by case485** [learningequality/ka-lite#5430]
KaLite version 0.17.0
Host Raspberry Pi Jessie 4.4 
Multiple browsers from windows client not displaying pictures of course content not displaying. Similar to #5140 

I tried in both content packs i have loaded (french and English) and with 3 different browsers on my windows 10 client (Mozilla, IE and Chrome) 

![pic1](https://cloud.githubusercontent.com/assets/17994779/24664958/8f9d136a-1921-11e7-8cef-f924a4c4eca1.PNG)
![pic1_ie](https://cloud.githubusercontent.com/assets/17994779/24664957/8f9d13e2-1921-11e7-9dee-338a0ca68c8c.PNG)
![pic2_chrome](https://cloud.githubusercontent.com/assets/17994779/24664959/8f9ff2d8-1921-11e7-8e3f-ad6cc8d842b4.PNG)

**Comment by benjaoming** [comment]
Hi @case485 

This is not a browser issue, but the media from your Content Pack that's not showing up.

It would be nice if you could use the original issue template and answer questions like how you installed KA Lite - was it with the debian installer, and wsa it the `ka-lite-raspberry-pi` installer?

Try running:

    kalite manage collectstatic

**Comment by case485** [comment]
Here is how i installed the distribution : 
			apt-get -y install software-properties-common python-software-properties
			echo "deb http://ppa.launchpad.net/learningequality/ka-lite/ubuntu xenial main" > /etc/apt/sources.list.d/ka-lite.list
			apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 74F88ADB3194DD81
			apt-get -y update
			apt-get install -y ka-lite-raspberry-pi

**Comment by benjaoming** [comment]
Thanks for getting back, I can confirm this now!

**Comment by benjaoming** [comment]
I can also confirm that I've found the fix.

**Comment by benjaoming** [comment]
The following lines are in your `/etc/nginx/sites-available/kalite.conf` by mistake and should be deleted:

```
    location /content/assessment/khan {
        alias   /usr/share/kalite/assessment/khan/;
    }
```

I'm creating an update now. In case you delete the lines manually, just beware that when you upgrade the ka-lite-raspberry-pi package, you will probably get a warning where you should accept the "package maintainers version".

Within a few hours, a fix will be out (takes a while to build and upload)...

**Comment by case485** [comment]
Amazing - thanks for all the hard work.

**Comment by benjaoming** [comment]
A fix is now in https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed/

**Comment by benjaoming** [comment]
The fix is now in the stable `ka-lite` repo and the learningequality.org server is also serving an updated `ka-lite-raspberry-pi_0.17.0-0ubuntu3_all.deb`.

http://pantry.learningequality.org/downloads/ka-lite/0.17/installers/debian/ka-lite-raspberry-pi_0.17.0-0ubuntu3_all.deb

Thanks for finding this @case485 and sorry about the delayed investigation from my side.
