### ISSUE TITLE
KA-lite for mac uninstall and now not allowing clean install

### ISSUE THREAD

**Issue by kevhyde** [learningequality/ka-lite#5434]
## Summary

*I am not experienced in programming. I installed KA lite on my mac today and got it working as far as the questions and user accounts etc. I could not show ka lite where my compressed downloaded videos were by scanning. Nothing was being found. I could not see the .kalite folder and tried to show a new data file location in preferences so I could link to torrented video. This stopped my ka lite working. I then deleted the KA-lite folder and contents from applications. Then I found a github page here that gave terminal commands to remove invisible .kalite folders from the system. I've done this. When I try to install the KA-lite again, it goes through the motions of installing but then at summary stage advised that installation failed*

## System information

KA-lite version 0.17

mac OS yosemite 10.10.5
 - Version: 0.17
 - safari

Thanks very much for any suggestions, Kevin

**Comment by benjaoming** [comment]
This issue was moved to learningequality/ka-lite-installers#446
