### ISSUE TITLE
KA-Lite Starting at Startup Minit Linux

### ISSUE THREAD

**Issue by trexken** [learningequality/ka-lite#5437]
## Summary

*Briefly describe what this is about*

How to have KALITE start at bootup.

*Please specify the KA Lite version you were using and your operating system!*

 -Mint 18.1
 - KALITE 0.17.0
 - Browser: ?

## Traceback or relevant snippet from server.log

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

1. Steps
1. To
1. Reproduce

## Screenshots

*If applicable*

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

*If applicable*

**Comment by benjaoming** [comment]
Hi @trexken 

Thanks - this doesn't sound like a tech issue, though.

Please ask in the community forums: http://community.learningequality.org/

( hint: you might want to share how you've installed KA Lite since we have a number of different installation methods )
