### ISSUE TITLE
Debian has removed "ifconfig" command - need to update ifcfg

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#5455]
## Summary

Background: https://linuxconfig.org/how-to-install-missing-ifconfig-command-on-debian-linux

We need to revisit and release an update of python-ifcfg once this issue is fixed and released: https://github.com/learningequality/python-ifcfg/issues/3

## System information

This applies to all KA Lite versions released.

**Comment by radinamatic** [comment]
Is this something we may need to document? Actually I'm thinking more of Kolibri then KA Lite...

**Comment by radinamatic** [comment]
Nwm me, brain fused by too much documentation... 📜 🤕 

I just remembered I mentioned the `ifconfig` somewhere in Kolibri docs, and wondered if I need to update it 😒

**Comment by benjaoming** [comment]
@radinamatic yeah, it's not to be taken for granted anymore... pretty annoying. Some legacy should not be cleaned up :)

**Comment by benjaoming** [comment]
Fixed in #5463
