### ISSUE TITLE
Points keep increasing even when the user is just replaying the video.

### ISSUE THREAD

**Issue by mrpau-eugene** [learningequality/ka-lite#5458]
## Summary

I was watching some videos because I was trying to reproduce this issue #4302.
I thought each video is allocated with an equivalent number of points. So when I am halfway through finishing the video, I tried to replay it. And I have observed that the points keep increasing.

## System information

 - Operating system: Mac OS
 - Version: 0.17.0
 - Browser: Chrome

## How to reproduce

1. Login as User
1. Watch a Video
1. Look at how the points are increasing
1. Repeat the video from the start

## Screenshots
![may-05-2017 11-39-11](https://cloud.githubusercontent.com/assets/27984604/25733013/d736f7f8-3187-11e7-8f56-cca973390e02.gif)

**Expected Behavior**: The points should reset to 0 or to the equivalent seconds where the video was replayed.
**Actual Behavior**: The points keep on increasing.

Update:
The points that are increasing does not reflect to the total points accumulated by the learner. My bad. I'll just close this issue.

**Comment by jamalex** [comment]
Thanks for the report! This is actually the expected behavior, even if it seems less than ideal. Keeping track of exactly which time ranges have been viewed and trying to make sure we only allocate points for new sections of the video would be too burdensome. All we store in the DB is how many total seconds (in "video time") each video was watched for.

**Comment by mrpau-eugene** [comment]
thanks for the clarification @jamalex

**Comment by benjaoming** [comment]
Yup, it's not optimal, but not something that's really causing any breakage.. essentially students can access videos, solve exercises, and teachers can monitor student progress... despite this strange behaviour :)

But great issue report @mrpau-eugene - really good start - you've reported and solved an issue in almost no time :+1: :laughing:
