### ISSUE TITLE
Shorten TOC on installation guide

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#5459]
## Summary

[Website](https://learningequality.org/ka-lite/) points directly to this page for "Installation Guide" item:

http://ka-lite.readthedocs.io/en/latest/installguide/install_main.html

But it's a mess because the TOC shows too many levels:

![screenshot from 2017-05-05 20-44-06](https://cloud.githubusercontent.com/assets/374612/25759664/bf576202-31d3-11e7-8460-8bf5e8978ea7.png)

**Comment by morrme** [comment]
Looks like the `max depth` attribute needs to be set.  Whoever changes it may need admin access.

**Comment by benjaoming** [comment]
You're right @morrme - Once merged into the right branch ( develop / master / 0.17.x ), RTD will build it automatically

**Comment by radinamatic** [comment]
Seems a good suggestion to set:
```
.. toctree::
    :maxdepth: 2
```
:+1:

**Comment by benjaoming** [comment]
Fixed in #5460
