### ISSUE TITLE
Captions on by default

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#5464]
## Summary

Learners can have difficulties understanding the voice of Sal Khan, especially in countries where English is pronounced substantially different from Khan's North American.

Also, headphones may be low quality, speakers broken, noisy environments, or no sound at all.

In conclusion and by recommendation, we should therefore switch on captions by default when they're available.

## System information

 - Operating system: Any
 - Version: 0.17.x
 - Browser: Any

**Comment by mrpau-eugene** [comment]
Hi @benjaoming. Will it not affect this current issue **Dubbed videos should not include subtitles of other languages #5359**  if we enable subtitles by default?

**Comment by mrpau-eugene** [comment]
@benjaoming how should be the behavior when we enable captions by default?

If the default language is set to _Spanish_ **es**, should it automatically enable the Spanish captions?

Or

Regardless of the default language, we always set the enabled captions to english?

**Comment by benjaoming** [comment]
@mrpau-eugene 

>  Will it not affect this current issue Dubbed videos should not include subtitles of other languages #5359 if we enable subtitles/captions by default?

Great question! The other issue seems to concern specific languages in which the subtitles are substantially different from the dubbed language.

Perhaps the best solution is to make the behaviour configurable through introducing a setting?

```python
from django.conf import settings

AUTO_ENABLED_CAPTIONS = getattr(settings, 'KALITE_AUTO_ENABLED_CAPTIONS', ['en'])
```

I don't know which module is most suitable to have the setting, but we could certainly introduce it and add a line about it in the documentation.

And because we're only informed that it's relevant to English, we can switch it on only for English by default...

**Comment by benjaoming** [comment]
Pending a test, @radinamatic would you be able to test the current `0.17.x` branch to see if captions display as supposed to?

**Comment by benjaoming** [comment]
Confirmed to be working: https://github.com/learningequality/ka-lite/pull/5467#issuecomment-308133172
