### ISSUE TITLE
KA Lite doesn't show server logs in windows

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/ka-lite#5471]
## Summary

After running `kalite start` command at first time and start the KA Lite server again, it will clean the server.log contents and it's doesn't show any KA Lite logs anymore.

## System information

 - Operating system: Windows 10, Windows 7
 - Version: 0.17.1

## How to reproduce

1. Install KA Lite 0.17.1 in windows.
1. Start and stop the KA Lite server and repeat it twice.
1. Then the KA Lite sever.log will be empty.

**Comment by benjaoming** [comment]
This is the intended behaviour and is consistent on all platforms. It's because we didn't have log rotation.

See:

http://ka-lite.readthedocs.io/en/0.17.x/installguide/release_notes.html#id3

**Comment by benjaoming** [comment]
See also #4890
