### ISSUE TITLE
0.17.0 - some assessments not showing images

### ISSUE THREAD

**Issue by moyere** [learningequality/ka-lite#5478]
## Summary

 I have deployed a server with windows 10. I installed KA light via the windows installer and downloaded all of the French videos.    This is deployed in the small village in Haiti to help educate the population. 

*Briefly describe what this is about*

 We have about 10 other computers some with XP some with Windows 7 some with windows 10 accessing the data on the server. On all of those computers several assessments do not display images properly.    All of the videos work properly and most of the assessments did as well. Just a few had issues. 
## System information

*Please specify the KA Lite version you were using and your operating system!*

 - Operating system: ? Win 10
 - Version: 0.17.0
 - Browser: chrome 

## Traceback or relevant snippet from server.log

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

1. Steps
1. To
1. Reproduce

## Screenshots

*If applicable*

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

*If applicable*

**Comment by radinamatic** [comment]
@moyere Thank you for the report! :+1: 

Could you copy & paste the URLs of the exercises where assessment items and images do not load correctly?
Are you using Chrome browser on client computers too?

**Comment by moyere** [comment]
Thank you so much for your reply....
One of then is...

http://192.168.0.100:8008/learn/khan/math/early-math/cc-early-math-counting-topic/cc-early-math-counting/counting-out-1-20-objects/

**Comment by moyere** [comment]
Children are using it on chrome browsers on computers and iPads as well as explorer browser...all have the same issue.

Could it have something to do with them being in the French?

**Comment by benjaoming** [comment]
@moyere it's a prerequisite for all of the content packs (the exercises and topic tree data that's released for each language) to have the English content pack installed - and for the same version. In other words... those images that you are missing actually belong to the English content pack!

Do you have enought bandwidth (~859 MB) to try downloading and reinstalling the English content pack?

You can install it from command line with `kalite manage retrievecontentpack download en`

I have tried to recreate the issue, but the assessment items are showing up correctly for the exercise which you mentioned:

![screenshot from 2017-07-04 16-00-08](https://user-images.githubusercontent.com/374612/27833211-10571580-60d2-11e7-957c-fcf01cf3fb95.png)

**Comment by moyere** [comment]
Thank you so much for the information. I'm very new to this and not sure how to do that. I left the server in Haiti but I did download the English server pack. It is on the computer but how do you install it? The laptop has windows 10 on it.

Keep in mind there are two nuns I have to give these instructions to. :) 

••••••••••••••
Thank You,  
Eric

**Comment by benjaoming** [comment]
Hi @moyere 

Given that you have the content pack as a file (that's great btw!), it can be installed from command line only. Btw it's a good idea to verify its size. You can see the content packs and their sizes [here](http://pantry.learningequality.org/downloads/ka-lite/0.17/content/contentpacks/)

It might get difficult for the nuns, but there are good chances that they can figure it out given that they tinker around.

1. With File Manager, navigate to `C:\Python27\Scripts`
2. Get command prompt (shift-right-click open area; select "Open command window here")
3. In the command line, type `kalite manage retrievecontentpack local X:\path\to\content\pack\en.zip` followed by `ENTER`.
4. Reboot (the shorter instruction, alternative would be to restart KA Lite only)

Remember that you have to explain them somehow where the `en.zip` file is and how they can see its full path.

Remember also that you should explain that if they succeed in opening up the command line and type in a command followed by `ENTER`, they will either get an error message (if something is wrong, but this is harmless), and once they are successful and the file installs, it will take up to several minutes for it to complete!

**Comment by benjaoming** [comment]
Also, before sending over the instructions, make sure to try them out locally :)

**Comment by jinchuika** [comment]
I'm running the same problem in windows 10. When I install the content pack, it removes the language pack and then, I can't see a lot of exercises. Did reinstalling the English pack solved your problem?

**Comment by moyere** [comment]
I have not gotten around to it yet

••••••••••••••
Thank You,  
Eric
