### ISSUE TITLE
Some video's resolution are too low

### ISSUE THREAD

**Issue by jiangjianshan** [learningequality/ka-lite#5482]
Hello, 

     My KA Lite version is 0.17.1. I have found some video's resolution are too slow, e.g. 
(1) http://127.0.0.1:8008/learn/khan/math/arithmetic-home/addition-subtraction/basic-add-subtract/basic-addition/ 
(2) http://127.0.0.1:8008/learn/khan/math/arithmetic-home/addition-subtraction/basic-add-subtract/basic-subtraction/ 

     Maybe there are some other video has the same issue but I have go through all of them for this moment. Could you update the video those have lower resolution?

**Comment by mrpau-eugene** [comment]
Hi @jiangjianshan unfortunately, those videos have low resolutions by default. I checked the video on youtube https://www.youtube.com/watch?v=AuX7nPBqDts to see if we can download a higher resolution but sadly, the original video doesn't have other resolutions higher than `240p`.
