### ISSUE TITLE
"setup script specifies an absolute path". Install failure on Arch Linux

### ISSUE THREAD

**Issue by nobicycle** [learningequality/ka-lite#5483]
## Summary

Install failure on Arch Linux

## System information

*Please specify the KA Lite version you were using and your operating system!*

 - Operating system: ?
Linux tower 4.9.33-1-MANJARO #1 SMP PREEMPT Sat Jun 17 14:07:44 UTC 2017 x86_64 GNU/Linux
$ python2 -V
Python 2.7.13

## Traceback or relevant snippet from server.log

```
$ sudo  python2 ./setup.py install
Already blocking...
Already blocking...
running install
running bdist_egg
running egg_info
writing requirements to ka_lite.egg-info/requires.txt
writing ka_lite.egg-info/PKG-INFO
writing top-level names to ka_lite.egg-info/top_level.txt
writing dependency_links to ka_lite.egg-info/dependency_links.txt
reading manifest file 'ka_lite.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*' found under directory 'kalite/static'
warning: no previously-included files matching '*' found under directory 'data/khan'
warning: no previously-included files matching '*pyc' found under directory 'python-packages'
warning: no files found matching '*' under directory 'dist-packages'
writing manifest file 'ka_lite.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
error: Error: setup script specifies an absolute path:

    /srv/kalite/kalitectl.py

setup() arguments must *always* be /-separated paths relative to the
setup.py directory, *never* absolute paths.
```

## How to reproduce

1. Extract kalite git master version
2. sudo  python2 ./setup.py install

**Comment by benjaoming** [comment]
Oh nice, I like Arch if that's their policy.. but just to check, could you state which version of pip and setuptools you're running?

```
$ pip --version
pip 9.0.1 from /blah/blah/site-packages (python 2.7)
̈́
AND:


$ pip show setuptools

Name: setuptools
Version: 36.0.1
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /blah/blah/site-packages
Requires: 

```

**Comment by nobicycle** [comment]
]$ pip2 --version
pip 9.0.1 from /usr/lib/python2.7/site-packages (python 2.7)

pip2 show setuptools
Name: setuptools
Version: 36.0.1
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /usr/lib/python2.7/site-packages
Requires:

**Comment by benjaoming** [comment]
Hi @nobicycle 

You stated

> Extract kalite git master version

...however reading the output:

```
error: Error: setup script specifies an absolute path:

    /srv/kalite/kalitectl.py
```

...suggests a file `kalitectl.py` is in play. We removed that file since 0.17.0 was released, so are you sure that you are installing a recent version?

**Comment by nobicycle** [comment]
Right! Somehow I was running 16.8 from github.
Thanks very nuch
