### ISSUE TITLE
Videos shown on demo server are different on the KA Lite 0.17.1 videos

### ISSUE THREAD

**Issue by mrpau-eugene** [learningequality/ka-lite#5490]
## Summary

Here is the link for the discussion: https://community.learningequality.org/t/the-videos-shown-on-the-demo-are-different-from-what-is-available-on-my-instillation/269

It seems that when we were rebuilding the 0.17.1 content packs, KA's API was doing some sort of stuffs that changes the location of the videos.

## System information

 - Operating system: All
 - Version: 0.17.1
 - Browser: Any browser

## How to reproduce

1. Login
1. In the `Manage` tab, click `Videos`
1. Look on how `Mathematics > Algebra II` (for example) is different from the demo site.

### Demo Server:
![image](https://user-images.githubusercontent.com/27984604/28562372-84586960-7154-11e7-81ab-edd554306d85.png)

### KA Lite 0.17.1

![image](https://user-images.githubusercontent.com/27984604/28562353-76582968-7154-11e7-849e-bdd485d0f6ec.png)

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

Might confuse the users since we weren't aware that topics were restructured and we haven't included anything in the release notes.

**Comment by mrpau-eugene** [comment]
But this shouldn't be an issue anymore. After rebuilding the content packs, I've re-checked the videos and their structure seems to be the same with the official Khan Academy website including new topics.

@radinamatic @benjaoming

**Comment by benjaoming** [comment]
Ah yes, true @mrpau-eugene - thanks for investigating and finding the cause!
