### ISSUE TITLE
Resource titles displaying in English instead of the chosen locale in the Teach tab 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#5494]
## Summary

If Spanish is selected by default, the resource titles are still displaying in English instead of Spanish inside the search dropdown and  tabular report in the `Teach` tab. 

This does not seem to be a contentpack issue as those items are present and localized in the Spanish topic tree, they are just not displaying here in the appropriate language, whether Spanish or French.

## System information

 - Operating system: Ubuntu 17.04
 - Version: 0.17.2rc2-2
 - Browser: FF & Chrome

## How to reproduce

1. Log-in as one or more users, view some videos, or do some exercises 
1. Login as Admin or Coach
1. Change the locale.
1. Go to Teach tab and observe the tabular report at the bottom.

### Spanish
![virtualbox_ubuntu17 04_28_07_2017_19_06_18-titles](https://user-images.githubusercontent.com/1457929/28740797-cc321a3a-7409-11e7-8e37-00e3d4ba2ecc.png)

### French
![virtualbox_ubuntu17 04_29_07_2017_04_03_35](https://user-images.githubusercontent.com/1457929/28741349-9af03a0a-7414-11e7-8843-646016309aa7.png)

## Real-life consequences

Coaches cannot interpret the results - let's fix it with the rest of the content in Spanish that we already managed to correct!

**Comment by mrpau-eugene** [comment]
Hmmm. I think I see the problem here. I've added `_` to the untranslated strings for this page but it still wasn't translating. The `_` function gets the translations from `djangojs.mo` so we need to do something about whether having maybe a single `django.mo` file and fetch the strings there or have the `_` fetch strings from both files.

Also, maybe @benjaoming has any suggestions?

**Comment by benjaoming** [comment]
> Btw, this issue is also existing in the demo server.

The demo server is running 0.16.9 which probably have similar issues.

> I tried adding _ in some variables in the tabular-view.handlebars but it still doesn't seem to get translated.

These titles are from the content database, so isn't the problem that it uses the English contents regardless of the active user language?

**Comment by benjaoming** [comment]
Also, @mrpau-eugene - some of the missing msgids are added in #5496

**Comment by mrpau-eugene** [comment]
> These titles are from the content database, so isn't the problem that it uses the English contents regardless of the active user language?

Yes, that's most likely it.

> Also, @mrpau-eugene - some of the missing msgids are added in #5496

Great! Will see if I can also find some missing msgids :)

**Comment by radinamatic** [comment]
@mrpau-eugene 

> so isn't the problem that it uses the English contents regardless of the active user language?
> > Yes, that's most likely it.

I hope I'm understanding correctly: what you want to say is that it isn't going to be a (big) problem to fix, right?

Because it is definitely a problem for the users to have them in English instead of the active user language... :stuck_out_tongue:

**Comment by mrpau-eugene** [comment]
@radinamatic Yeah. Seems like it won't take too long. I'll fix this as soon as possible.

**Comment by mrpau-eugene** [comment]
@radinamatic @benjaoming where should we target a PR for this? Should it be in the `0.17.3`?

**Comment by radinamatic** [comment]
Is there a reason why it should not be included into the `0.17.2`? 
Partners in LatAm are expecting it... :confused:

**Comment by mrpau-eugene** [comment]
@radinamatic no reason in particular.. I'm just making sure 😄

**Comment by benjaoming** [comment]
I'm happy to add this in 0.17.2 since the fix is very clean. Will verify the CI build and merge soon.
