### ISSUE TITLE
Reset User Name and Password.

### ISSUE THREAD

**Issue by fhenson1** [learningequality/ka-lite#5501]
I need to reset the user name and password on a computer that already has Kalite  installed.

 - Operating system:  Windows 10
 - Version: 0.17.1
 - Browser: Google

I found the following:

If you have forgotten the username/password combination, simply run kalite manage createsuperuser in your Terminal.

I do not know what is meant by terminal.

Below is the link to the manual.

http://ka-lite.readthedocs.io/en/latest/usermanual/userman_admin.html

**Comment by mrpau-eugene** [comment]
Hi @fhenson1 

On a windows machine, simply press the `Windows` key and search for `cmd`.

A command prompt should appear, then you can type the command `kalite manage createsuperuser`

**Comment by benjaoming** [comment]
@fhenson1 when you have the command line (AKA terminal), you need to "change directory" firstly to where the `kalite` script is located:

```
cd C:\Python27\Scripts
kalite manage createsuperuser
```

To change password for an existing user:

```
cd C:\Python27\Scripts
kalite manage changepassword <username>
```

To see other available commands:

```
cd C:\Python27\Scripts
kalite manage help
```

Please refer to our community forums for further support: http://community.learningequality.org/

**Comment by fhenson1** [comment]
Benjamin

 

Thank you so much.  The is exactly what I needed.

 

I am using Kalite in India and Kenya at slum schools.  I am 77 so not very tech savvy but can follow the excellent instructions you provided.

 

Very grateful in Houston today,

 

Forrest
