### ISSUE TITLE
Unify color legends on the Teach page

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#5510]
## Summary

There are [two, almost identical](https://github.com/learningequality/ka-lite/pull/5496#discussion_r134044543) "keys/color legends" displayed when the report table is opened.
Let's try to add the `Not attempted` item in the first one to account for that state in the table report, and remove the second one.

## Screenshots

![bye-bye-color-legend](https://user-images.githubusercontent.com/1457929/29852371-0ed501ce-8d3a-11e7-8da9-427bee9f3d96.png)

**Comment by benjaoming** [comment]
Fixed in #5511
