### ISSUE TITLE
Missing translations on Manage Languages

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#5514]
## Summary

Still missing some translations on Manage Languages page.

## System information

 - Operating system: Windows 7 & Ubuntu 16.10
 - Version: 0.17.3
 - Browser: all

## Screenshots

![ubuntu3 start running - oracle vm virtualbox_588](https://user-images.githubusercontent.com/1457929/29988961-6aa5de8c-8f70-11e7-9073-3f370a2ee6ed.png)

![w7 start running - oracle vm virtualbox_585](https://user-images.githubusercontent.com/1457929/29988968-73a3bab8-8f70-11e7-9c4e-c33308773d68.png)

![w7 start running - oracle vm virtualbox_586](https://user-images.githubusercontent.com/1457929/29988970-82cd6f5c-8f70-11e7-95ab-abf2b4079463.png)

**Comment by benjaoming** [comment]
Fixed in #5517 - and new msgids

This has added 40 new strings and removed 3. So it will be substantial IMO. @radinamatic could you give an overview of the most important places that were untranslated?

**Comment by benjaoming** [comment]
@radinamatic @mrpau-eugene I would like to close this issue with a final verdict about how serious the issue is, for instance an idea of where the missing translations mainly feature, like are they important pages that are hard to understand for the intended user?

Also, have they been translated now for the major languages? I can see that Spanish is completed..

**Comment by radinamatic** [comment]
@benjaoming All the strings from #5517 have been translated on Crowdin, but some of them did not make it into 0.17.3. Not a major tragedy, and this can be closed!

![w7 0 17 3 running - oracle vm virtualbox_629](https://user-images.githubusercontent.com/1457929/30695445-86270326-9ed8-11e7-81e1-ff3312809e4e.png)

**Comment by benjaoming** [comment]
@radinamatic - per #5518 which will be released in 0.17.4, we'll move the translations into the release itself (see the issue), so I was just wondering how much this glitch pushes our priorities.. but I think for now, we'll just see how quickly we can get it resolved and release 0.17.4 - seems there's no panic.

**Comment by radinamatic** [comment]
Agreed, @benjaoming, since this is on Admin side, no panic involved! :+1:
