### ISSUE TITLE
New npm version asks not to "cache clean"

### ISSUE THREAD

**Issue by alherrera42** [learningequality/ka-lite#5519]
## Summary

Attempting to install this package with node 5.x will not work since it has a new self-checking mechanism (see npm output below)

## System information

 - Operating system: Ubuntu Xenial
 - Version: 0.17.x
- npm: 5.4.1
 - Browser: - Not applicable

## Output
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
npm ERR! 
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.

## How to reproduce

On regular install
sudo make install

## Solution proposed
As npm itself recommends, use the command "npm cache verify" in the Makefile. Using "npm cache clean --force" is not recommended and throws the proper warning to the CLI. I did it and package works just fine. 

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

Regular installing will throw an error and stop

**Comment by benjaoming** [comment]
Thanks for looking into this.

We upgraded to use Node 6 at the 0.17.2 release: http://ka-lite.readthedocs.io/en/0.17.x/installguide/release_notes.html#id2

I haven't seen this error show up, but I also use npm 3.x - will try to run `sudo npm install npm -g`, guessing that it's the way to upgrade.

@rtibbles FYI

**Comment by benjaoming** [comment]
Fixed in #5520 - I think we are safe here:

Build environments use clean systems when building release installers or have NPM>=5 - make note @mrpau-richard in case you have to change anything.

Thanks for reporting @alherrera42
