### ISSUE TITLE
Configurable welcome message for superusers

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#5522]
## Summary

When starting KA Lite for the first time, a user has to

1) Create a new superuser
2) Login
3) [this is where we want the welcome message]

Upon first login, we could have a message that greeted admins. It should be configurable for special deployments like RACHEL.

The message should be a configurable Django template string, like:

```
KALITE_WELCOME_MESSAGE = """
<h2>KA Lite for RACHEL</h2>
<p>You are running an instance of KA Lite shipped with a RACHEL Pi. You can get online support for the device itself or KA Lite depending on the nature of your problem:</p>
<ul>
  <li><a href="http://community.learningequality.org/" target="_blank">KA Lite community</a></li>
  <li><a href="http://community.rachelfriends.org/" target="_blank">RACHEL community</a></li>
</ul>
"""
```

Of course, the message should only be shown once. So a flag has to be set once it has been shown and dismissed.

FYI @j-schwartz - would anyone from the RACHEL team be able to work on this?

Any suggestions for the default text? @radinamatic

**Comment by mrpau-eugene** [comment]
@benjaoming would it be better to redirect the superusers to a welcome page and display the message there or should it just display the welcome message like here:

![image](https://user-images.githubusercontent.com/27984604/31425995-2119b296-ae94-11e7-9044-f6386d192a7e.png)
