### ISSUE TITLE
Simplified login does not work if there are more than 1,000 users

### ISSUE THREAD

**Issue by mrpau-eugene** [learningequality/ka-lite#5523]
## Summary

It was originally a report from Edulution's feedback:

> We noticed that this is due to the API request (securesync/api/user/facility<facility_id>&is_teacher=false) only returning 1000 objects from the students table at the login screen. To overcome this, we simply deleted inactive student accounts at each facility until they were less than 1000. However, this is only a temporary solution. A more permanent fix to enable >1000 learners to login via simplified login even would be appreciated

## System information

*Please specify the KA Lite version you were using and your operating system!*

 - Operating system: ?
 - Version: 0.16.?
 - Browser: ?

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

We don't want users to only login when it's less than a thousand users registered.

**Comment by benjaoming** [comment]
FYI @Aypak :)
