### ISSUE TITLE
Should all KA Lite videos be downloaded first before watching them all? 

### ISSUE THREAD

**Issue by Elga07** [learningequality/ka-lite#5531]
Should all KA Lite videos be downloaded first before watching them all? 

I typed the title of the video I want to watch from the KA Lite Software and it appeared, but my question is: does it need to be downloaded before I can access it? Tell me about videos of KA Lite especially your experience.

**Comment by mrpau-eugene** [comment]
Hi @Elga07

> does it need to be downloaded before I can access it?

Yes. You need to download the videos first by accessing the `Manage` page, then click the `Videos` to show the list of downloadable videos 😄

**Comment by Elga07** [comment]
I have done it already, Mr. Oliveros. However, thanks!
