### ISSUE TITLE
Install ka-lite over apache?

### ISSUE THREAD

**Issue by dkirmis** [learningequality/ka-lite#5534]
## Summary

We are running a system on the raspberry Pi 3 that is already configured to use apache. We would like to add ka-lite to our content. Is there a way to install over apache? Any instructions for doing so?

## System information

*Please specify the KA Lite version you were using and your operating system!*

 - Operating system: Raspbian Jessie 8
 - Version: 0.16.?
 - Browser: any

**Comment by benjaoming** [comment]
Hi @dkirmis 

Yes you can run KA Lite with Apache :)

If you install the package `ka-lite-raspberry-pi`, you will have KA Lite installed and configured to run through Nginx on port 8008, but you can switch it to run from port 80 or setup Apache to behave the same way.

You can get `ka-lite-raspberry-pi` from here or on the [Download page](http://ka-lite.readthedocs.io/en/latest/installguide/install_all.html#raspberry-pi): https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite

You can run KA Lite through Apache either through a Proxy (as with the Nginx setup) or mod_wsgi, a module for Apache that runs Python WSGI applications. Please refer to the docs: http://ka-lite.readthedocs.io/en/latest/installguide/advanced.html?highlight=wsgi#nginx-apache-setup

Please refer to our community forums if you have further questions: http://community.learningequality.org/
