### ISSUE TITLE
PEX test file build script + buildkite integration

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#5544]
## Summary

To speed up testing a bit, an automated PEX build via Buildkite will be a good starting point:

 * [ ] A make target for a `.buildkite/pex.sh` script creating `dist/ka-lite-static<version-info>.pex`
 * [ ] Activate script on Buildkite
 * [ ] Get PR status feedback through bot

Versions:

I think you can stick output of `git describe` in the file name. We don't have the same clever automatic dev versioning in KA Lite as Kolibri, but at least having a unique file name would be nice.

## System information

*Please specify the KA Lite version you were using and your operating system!*

 - Operating system: ?
 - Version: current 0.17.x branch
 - Browser: ?

**Comment by mrpau-eugene** [comment]
@benjaoming I was wondering, would it be okay to use `git describe`?

I'm on the `0.17.x` branch and executed `git describe` and then it gave me this `v0.17.3-30-g86e1ea6e2`.

Doesn't it make confusion since the KA-Lite Version is `0.17.4`, but we will get something like `ka-lite-static-v0.17.3-30-g86e1ea6e2.pex`?

**Comment by benjaoming** [comment]
@mrpau-eugene garh, you are right, it's because we aren't tagging pre-releases

let's change the work flow, so pre-releases get merged into `0.17.x` and only `master` serves as the "current stable". That way, we can tag and track our pre-releases in a linear way.

**Comment by benjaoming** [comment]
I can start doing tags for pre-releases once #5545 is finalized and a new pre-prelease is out..

**Comment by benjaoming** [comment]
@mrpau-eugene 0.17.x is now tagged, so if you apply `git describe`, you should get meaningful output now :)

**Comment by mrpau-eugene** [comment]
@benjaoming thanks!

**Comment by benjaoming** [comment]
Yay! Fixed in #5551 :) ( which was merged in #5552 )
