### ISSUE TITLE
ka-lite failed to install on win 10, raised Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by engrsmukhtar** [learningequality/ka-lite#5573]
## Summary
I ran `pip install ka-lite` on windows 10 and it returned a 

> ModuleNotFoundError: No module named 'version'

## System information

HP 6.00 GB Ram | 64-bit Operating System, x64-based processor
Microsoft Windows [Version 10.0.16299.371]
(c) 2017 Microsoft Corporation.

*Please specify the KA Lite version you were using and your operating system!*
         ka-lite-0.17.4.tar.gz
 - Operating system: Windows 10
 - Version: 0.16299.371
 - Python: Version 3.6.5

## Traceback or relevant snippet from server.log

`
Collecting ka-lite
  Downloading https://files.pythonhosted.org/packages/ae/13/e98aa7284b9e409a451e3d96a72f0d6ef7635f063e2983deb56ada733d99/ka-lite-0.17.4.tar.gz (29.4MB)
    100% |████████████████████████████████| 29.5MB 289kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\MyName\AppData\Local\Temp\pip-install-ujpfskc_\ka-lite\setup.py", line 17, in <module>
        import kalite
      File "C:\Users\MyName\AppData\Local\Temp\pip-install-ujpfskc_\ka-lite\kalite\__init__.py", line 4, in <module>
        from version import *
    ModuleNotFoundError: No module named 'version'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\MyName\AppData\Local\Temp\pip-install-ujpfskc_\ka-lite\
`
## Real-life consequences (anything community should be aware, for instance how it affects your deployment)
Initially, the Windows installer didn't install with Python 3.6.5. I googled but the only related thing was a yaml library dependency breaks the installer #3633

Thanks for your help on how to go about this.

**Comment by mrpau-richard** [comment]
@engrsmukhtar I recommend you use the [KA Lite Windows installer](https://ka-lite.readthedocs.io/en/latest/installguide/install_all.html#installation) when installing KA Lite at Windows.

**Comment by benjaoming** [comment]
Hi @engrsmukhtar 

KA Lite isn't compatible with Python 3. You need to use Python 2.7 to install it from `pip`.
