### ISSUE TITLE
Missing videos in Health and medicine - Advanced nervous system physiology section

### ISSUE THREAD

**Issue by mewmew** [learningequality/ka-lite#5574]
## Summary

Missing videos in Health and medicine - Advanced nervous system physiology section

## System information

*Please specify the KA Lite version you were using and your operating system!*

 - Operating system: Arch Linux
 - Version: 0.17.4
 - Browser: Chromium and Firefox

## How to reproduce

Compare khanacademy version https://www.khanacademy.org/science/health-and-medicine/nervous-system-and-sensory-infor with ka lite version http://192.168.1.2:8008/learn/khan/science/health-and-medicine/nervous-system-and-sensory-infor/

## Screenshots

Khan Academy:
![2018-05-27-233021_960x1176_scrot](https://user-images.githubusercontent.com/1414531/40590858-dcc5e67e-6206-11e8-8b00-01539ad5dfe1.png)

KA Lite:
![2018-05-27-232932_1163x1175_scrot](https://user-images.githubusercontent.com/1414531/40590857-da18313e-6206-11e8-8cca-f42c6b883976.png)

**Comment by mrpau-richard** [comment]
@mewmew thanks for reporting this. I think the `KA Lite content pack` is outdated. I recommend you try [Kolibri](https://learningequality.org/download/) the upgraded version of `KA Lite`  It has an updated `Khan Academy` contents.

**Comment by mewmew** [comment]
Thanks @mrpau-richard! I'll give Kolibri a try.

Leaving this issue open for now, as it still affects ka-lite users. If ka-lite is determined no longer to receive updates, then feel free to close this issue.

Cheers,
/u

**Comment by benjaoming** [comment]
Hi @mewmew -- thanks for a good issue description. We did do an updated content pack, but we are unsure if it will work, and testing 25k exercises and 8k videos can be a hassle :)

You can find the new content pack here: https://github.com/learningequality/ka-lite-content-packs/pull/78#issuecomment-357616993

(just beware of the problems listing videos, they should be harmless, though, if you are just downloading everything in a topic and ignore the wrong figures being displayed)

Whether KA Lite 0.18 will land remains to be seen, currently Learning Equality (the organization creating and maintaining) is putting almost all efforts into Kolibri. However, all community efforts are most welcome.
