### ISSUE TITLE
Ka Lite French not working on Rachel server

### ISSUE THREAD

**Issue by kevinkchoi** [learningequality/ka-lite#5589]
## Summary

Dear expert, I managed to install Ka Lite on Rachel server. Install is correct but it shows "Unavailable Contents". it's for both English & French version
French install: rsync -Pavz rsync://dev.worldpossible.org/rachelmods/fr-kalite ./
English install: rsync -Pavz rsync://dev.worldpossible.org/rachelmods/en-kalite-ess ./

Can someone help me please?

## System information

*Please specify the KA Lite version you were using and your operating system!*

OS: Linux rachel 4.14.79-v7*  installed from Strech version
And I'm accessing from a windows PC with chrome.

## Traceback or relevant snippet from server.log

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

1. Steps
1. To
1. Reproduce

## Screenshots

*If applicable*

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

*If applicable*

**Comment by kevinkchoi** [comment]
Hi all,
I have resolved it by modifying the finish_install.sh file, which was indicating wrong directories.

Nevertheless, I still wonder if someone can help me to unite both English & French version of Khan Academy into the single database (although both are separately installed in 2 different locations)?

My installation is under;
- /var/www/modules/en-kalite-ess
- / var/www/modules/fr-kalite

And when I run one of the two system finish_install.sh, I will have no longer access to the other installation.

Thanks in advance

**Comment by benjaoming** [comment]
Hi @kevinkchoi 

Thanks for posting. We are not actively developing anything considerable on KA Lite anymore, almost all efforts are in developing [Kolibri](https://learningequality.org/kolibri/).

I think this issue sounds mostly like it has to do with the way that Rachel works. On a regular KA Lite installation, languages are added through the user interface (in the browser) while logged in on an administrator account.

![image](https://user-images.githubusercontent.com/374612/64528276-57568d80-d308-11e9-9f21-ddfe4ef55002.png)


Best,
Ben
