### ISSUE TITLE
Python often cannot be found on Windows, when we don't install 

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#585]
Scenarios:
* Install only for local user (need to use HKEY_CURRENT_USER; http://msdn.microsoft.com/en-us/library/windows/desktop/ee872121(v=vs.85).aspx#app_exe)
* On Windows 8, the App Path is not set for Python (or maybe that was due to the install options I chose when I installed Python?)

**Comment by aronasorman** [comment]
Fixed in the latest installer -- we now require superuser access for installing Python.
