### ISSUE TITLE
Scripts for detecting "bad clients"

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#604]
We can make very simple central server scripts for detecting bad clients, and alerting us for further investigation (via email).

For example, here's a list of failed session counts (per device, failed # > 1) who, this month, have been getting errors while trying to sync:
```
Failed session count:  2
Failed session count:  7
Failed session count:  21
Failed session count:  112
Failed session count:  694
```

We should detect these things and try to understand our product better / reduce server workload from receiving 3 - 20 failed "pings" per day.

**Comment by aronasorman** [comment]
Not a priority.
