### ISSUE TITLE
Using colored output in installation script

### ISSUE THREAD

**Issue by mrshu** [learningequality/ka-lite#62]
I've just had a look at the tutorial video for KA-Lite. It looks very nice but when I someone not very familiar with the command line starting at the Terminal I could quite easily see they'd get lost very soon.

So how about making sure that everything that should catch attention (I mean the echoed texts, not command outputs) is colored in some way (I don't know, blue or something)?

Also, in true command line fashion, we could add an ASCII FLE logo on the beginning of the install script.

**Comment by aronasorman** [comment]
Not a priority; reopen when needed.
