### ISSUE TITLE
Use an app-specific directory for temp files and temp directories

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#620]
Some of our tasks use tempfiles heavily (installation, caching, etc).  We (correctly) use the tempfile module to create those files and directories.

However, it's quite challenging to ever have a process that goes and deletes them later--if they're not deleted by our app immediately (and sometimes they can't be), they're just left there until the OS cleans up.

It would be nice to have our own module that wraps tempfile, and puts everything into an app-specific temp directory.

**Comment by aronasorman** [comment]
Not a priority; reopen if it's a big issue.
