### ISSUE TITLE
Create generic SD card image

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#635]
It should be simple.  We create SD card images for all platforms (windows, linux, osx), such that:
* When you start the server the first time, a key / device / zone is created (solves uniqueness issue); password uniqueness may need to be solved in an automated way too.
* Simple way to add facility information

The process for deploying these should be this simple:
* Clone the image to the SD card
* Start the server
* Enter the facility information

And the outcome should be:
* A fully installed system (including a facility, and videos)
* That install data is synced to our central server (including the facility, for future tracking).

Installation / start should take < 5 mins of manual work (not including wait time)

**Comment by aronasorman** [comment]
Superseded by https://github.com/learningequality/installers. Let's revisit this once we're ready to create KA Lite images.
