### ISSUE TITLE
KA Lite shutdown option

### ISSUE THREAD

**Issue by gimick** [learningequality/ka-lite#660]
In some cases, KA Lite will be the only application using the Raspberry Pi, and in many cases the RPi could be switched-on for class, and then switched-off again at the end of the lesson.

Just now, there is no capability for a teacher to shut the hardware down gracefully - everytime they will power off at the mains.

To minimise issues with data loss/corruption or even hardware component failure, it would be better to have a system shutdown option available from the KA Lite application - perhaps as a menu item available only to admins and teachers?

**Comment by benjaoming** [comment]
I don't think it's very awesome to put functionality into KA Lite that's tied up to the host system. We tried and failed with setting the host system clock, a feature which was removed. Let's not go there again, even with Kolibri IMO.
