### ISSUE TITLE
Points total displays incorrectly when multiple tabs open

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#670]
Background:
I want to watch videos in one tab (listening in, watching, pausing), while doing exercises in the other.

Expectation:
Things that are static get out of sync (fine), but things that show updates are updated similarly between windows.

Current behavior:
Points (top right corner) are updated, but never retrieved from the server.

Suggested fix:
Query, and return, the current total points, and update from there.  Can do a local update, and then refresh with true points from the server, if the request returns successfully.

**Comment by rtibbles** [comment]
Won't fix.
