### ISSUE TITLE
Proposal to support alternative databases

### ISSUE THREAD

**Issue by gimick** [learningequality/ka-lite#677]
This ticket will track progress, feel free to contribute

Outline plan:
* benchmark postgresql/mysql/sqlite (including Raspberry Pi)
* benchmark large database performance on the different db's (including sqlite)
* identify and fix issues with KA Lite code
* Agree which db's will be supported by KA Lite
* modify installer functions
* automate/document any admin tasks for KA Lite or the database

Branch gimick/db_1 will hold any changes/additions.

**Comment by aronasorman** [comment]
Let's open issues for individual DBs.
