### ISSUE TITLE
Topic links greyed out, even with exercise progress.

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#679]
Our topic links are greyed out based on video downloads.  However, this can lead to confusion: if a student has done exercises at sub-topics with no videos (this is common), and especially if videos exists for other topics that the student hasn't done exercises for:

For example, here "Multi-digit multiplication" looks inviting, but there's no progress there.  In fact, there's progress under the greyed "One digit division".
![image](https://f.cloud.github.com/assets/4072455/1107844/fd861644-1964-11e3-8a55-d58f9315ca0c.png)

![image](https://f.cloud.github.com/assets/4072455/1107852/2a0ccadc-1965-11e3-827d-c617435548df.png)

**Comment by rtibbles** [comment]
No longer relevant.
