### ISSUE TITLE
Record all usage data, even if no user is logged in / facility is created.

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#706]
In order to understand KA Lite usage worldwide, we need as much usage data as possible.  However, when no users exist or are created, we simply do not save any usage data.

We can record all *Log data, as usual, when no user is logged in, or when Django users are logged in.

Possible designs:
* Have a default facility (hidden from all reports) and facility user (hidden from all reports) that is used
* Allow facility/facility user to be None for *Log objects.  When syncing, explicitly upload such data, but never download it.  However, there must be a way to distinguish across device, as you don't want records to collide cross-device (as we do with actual users).
* Store this data in separate tables, and sync separately.

**Comment by aronasorman** [comment]
I'm not up to date on where we are with regards to our data collection system. @rtibbles how close are we to implementing this in the current develop?

**Comment by rtibbles** [comment]
Way off.

**Comment by rtibbles** [comment]
Not going to happen within the scope of KA Lite.
