### ISSUE TITLE
Device Registration page navigation bar 

### ISSUE THREAD

**Issue by wangguan59** [learningequality/ka-lite#713]
![screen shot 2013-09-16 at 4 38 54 pm](https://f.cloud.github.com/assets/1319955/1153701/319dc0e8-1f29-11e3-933a-ad8fcf5ca791.png)

To make it less distraction and let the user focus on the device registration process. the navigation bar can be remove, or only keep few items, or use different nav(device registration steps navigation).

Once the user click out of device registration page, it is hard to find it back, and we don't want to them to do anything else besides finishing this registration. (If user don't have a zone created yet, do we want them to go to admin page and create a zone, or just stick with this process in this page?)

Side notes:
This technique is often used by many E-commerce sites. During the checkout process, they removed their standard navigation bar to make the user focus on checkout process.

**Comment by aronasorman** [comment]
not a priority; let's open another issue if this is a big UX problem.
