### ISSUE TITLE
HTH: Zero-config USB stick package

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#732]
Requested as part of the High Tech High deployment.

In order to deploy to students homes, where we:
* Cannot have an expert help install
* Need kids to be able to manage things
* Need a portable solution
* Don't necessarily have admin rights
* May be working on any platform, with any OS state
* Need to have data on a specific sharing network

a viable solution is to provide all of the following on a USB stick:
* All platforms of Python
* All platforms of a compatible browser
* KA Lite on a "sharing network", synced to appropriate facilities

**Comment by rtibbles** [comment]
Superseded by cross platform installers approach.
