### ISSUE TITLE
KA Lite website: Improve Navigation by adding Dropdown for Content Pages

### ISSUE THREAD

**Issue by dylanjbarth** [learningequality/ka-lite#735]
We have the following pages:
- About the Organization
- What is KA Lite?
- Our Mission
- User Manual
- Our Users

5 of which are not accessible from the nav bar. I think a dropdown would be a nice solution. I tried implementing it myself, but the CSS rules we currently have look optimized for mobile and don't follow the bootstrap paradigm for nav bars, so I wanted  to post here and get feedback before continuing. Good idea? Bad idea?

**Comment by rtibbles** [comment]
No longer relevant.
