### ISSUE TITLE
Central Server control panel UI enhancement thinking 

### ISSUE THREAD

**Issue by wangguan59** [learningequality/ka-lite#744]
![screen shot 2013-09-19 at 7 19 04 pm](https://f.cloud.github.com/assets/1319955/1178082/4232d422-219d-11e3-9827-0fb9d237fc88.png)
Above is our current Central Server control panel UI.
I have few suggestion:
1) Make zone name as a link to replace "Manage"
It would simplified the page, and make it more direct and intuitive for the action. Also, it not all about managing the zone. it can be simply for checking the data. 

2) Adding "last sync time" info next to the zone. 
I was thinking what makes the user to click into the zone. Users want to find out the latest report about the zone. If the data is never updated, user wouldn't be necessary to click the link, because there is no new activity data for the user to see. "Last sync time" is an important point to trigger the user to decide whether they need to open the zone link.  When an organization have multiple zones, it would be clearly to see each zone's activity by looking at the control panel page. Currently, we have this data, but it would show after the user click "manage"

3) Move "delete" function inside of zone. 
I was thinking how the user determine to delete a zone. Will they delete the zone by just looking at the zone name? I happened to create few empty zones for function testing, but I also had few zones that had synced data. I want to delete those useless zones, so I went through click manage for each zone, browse the data, and determine whether it is a zone I would like to delete. If it is empty, I will go back and delete the zone. I think the user will always need to take a look at the zone and decide to delete or not. Then move the "delete" option from the control panel page into the zone info page makes more sense based on such behavior context.

This is my thought process to approach this user experience thinking.  We don't have clear evidence about it yet, it is more based on my experience of using the system. What do you guys think?

**Comment by aronasorman** [comment]
Thread conversation is stale; reopen if it's a big UX issue in the central server repo: https://github.com/fle-internal/ka-lite-central
