### ISSUE TITLE
Link to meaningful coach reports, provide meaningful blurbs

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#754]
Right now, coach reports are too flexible, and not informative about how they should be interpreted.

Add direct links to particular reports from the coachreprots landing page.  For each linked report, have a report description on the page, to help users with interpretation.  Perhaps using the "glossary" abilities from the central server to get optional help interpreting would be good too.

**Comment by rtibbles** [comment]
Superseded by #1871
