### ISSUE TITLE
Multiplatform installer for KA Lite

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#762]
Requirements:
* Had a GUI
* Installed Python (and any other dependencies)
* Installed KA Lite
* Is rebuildable efficiently / on the fly (so we can dynamically insert zone information, custom local_settings, etc)

@ruimalheiro this is something you've begun.  Can you talk a bit about the current direction, and how well it addresses each of the above?

**Comment by aronasorman** [comment]
In progress in the learningequality/installers repo.
