### ISSUE TITLE
HTH: restrict install to sync a single user's data

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#763]
This will be a preliminary / demo version necessary for android device installation, needed for HTH deployment on Thursday.

Issues:
* When students bring installations home, they have full control of the data.  For this reason, we must restrict the data put on such devices to that single user.

Approach:
* As a first pass, it's easiest to restrict student usage to a single, pre-defined user.
    * Syncing will only occur for that user's data
* We want the user experience to be as streamlined as possible.
    * Disable the "sign up" button
    * Use this username at login

Notes:
* There will be nothing stopping this user from removing this setting, or changing it to another user.  (among other things), Future iterations should find a way to deal with this.

@jamalex any input on the (demo) design is appreciated, or if a longer-term design could easily be done, some suggestions for that@
@rtibbles any ideas from you would be welcome as well, of course!

**Comment by aronasorman** [comment]
Fixed in the latest develop, with the `UserRestricted` config package.
