### ISSUE TITLE
HTH: webpage for creating single-user package for USB installation

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#764]
We want to allow students to have their own KA Lite installation that they can carry via USB and bring home.

Having a webpage where we can select the user and a USB location, then click a button and have the necessary software installed, is very helpful for this.

@arnaudbenard This is just the kind of thing we'd work on together in the past!  Do I have to do this myself now?  Not appealing at all... would like to focus on the back-end work.

@dylanjbarth any interest in stepping in to help?

**Comment by aronasorman** [comment]
Superseded by https://github.com/learningequality/installers.
