### ISSUE TITLE
Distributed server Sign-in page. 

### ISSUE THREAD

**Issue by wangguan59** [learningequality/ka-lite#772]
Issue:  Users don't know or forget about their account info on login page 

Solution: To provide a link under sign-in form that would  pop over a help page to guid   different users for account info.
This link would also provide some usability data whether they had issue about knowing/remembering their account.
 
I had so many CSS and JS conflicts issues, so I put a simple example in jsfiddle
http://jsfiddle.net/wangguan59/WqNgn/

With the same code in KA Lite, shows
![screen shot 2013-09-28 at 12 04 55 pm](https://f.cloud.github.com/assets/1319955/1231890/25bc817a-2879-11e3-8e49-f589131a1745.png)

My repo: https://github.com/wangguan59/ka-lite/tree/sign_in_page

**Comment by rtibbles** [comment]
Superseded by #2035
