### ISSUE TITLE
GUI for server control

### ISSUE THREAD

**Issue by ruimalheiro** [learningequality/ka-lite#784]
In the moment we have a GUI to control the server that only runs on Windows.

- We want to build a multiplatform GUI for the same purpose (and maybe others).
- We want to move from (C/C++ - Win32) to python, so we can increase flexibility and support.

- Suggestion:
Write GUI in python using Tkinter.

**Comment by aronasorman** [comment]
Supplanted by https://github.com/learningequality/installers/issues/6.
