### ISSUE TITLE
Better indication that a page is being loaded after a link has been touched (for tablets)

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#788]
In the Nalanda deployment, students are using Ubislate tablets to access content from a Pi. Feedback came in as follows:
> Progress bar: Students tend to re-click on links very often as the current progress bar (when a link is opening) is not very visible.  Request to make the progress bar more visible.

We currently have no control over the progress bar (it's a feature of the browser, not KA Lite), but we can look into adding an additional indicator (and perhaps disabling the links) when a link has been clicked.

**Comment by 66eli77** [comment]
in 0.13, we don't have many reload pages for student, other issues mentioned in this thread will be or has already been addressed by optimization.
