### ISSUE TITLE
HTH: Permissions for MVP P2P syncing

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#803]
Background:
* We want to "spawn" limited installs (containing user-specific data only) for taking home KA Lite on a USB key or Android tablet.
* How to best do this, minimizing confusing code and the chances for a limited device gaining access to all data?

Issues:
* If we put the "limited" device on the zone, then we have to lock down syncing for old devices (so that the limited device couldn't lie about its version to get the data).
* If we don't put the "limited" device on the zone, then we'll have zone data both on and off the zone.. what if the "limited" device tries to register. 
    * Some lockdown of the device is possible to make this harder, but ... not THAT hard.

Current thoughts:
* Create a SyncPermissions model that *must* be carried by a device wishing to sync with any other device (central or otherwise).
* The SyncPermissions model is signed by a device on the zone.
* The SyncPermissions model must be verified by a device (or overridden manually) before syncing occurs.  However, no syncing of devicemodels is done to try and verify the SyncPermissions setting.

What this does:
* 

Other possible designs:
* Mark something on the ZoneInvitation object
    * Issue: what to do for devices without this field set (lockdown?)
    * Issue: how to make this extensible?
* Mark something on the DeviceZone object
    * Issue: this can be self-created/self-signed now.  How would we avoid lying?

@jamalex @aronasorman glad to hear your thoughts!

**Comment by aronasorman** [comment]
No longer relevant, with the new flexmodels syncing in the pipeline.
