### ISSUE TITLE
Nalanda: Documenting our point system / mastery

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#811]
Need documents about point system, what mastery is, how to use

**Comment by aronasorman** [comment]
Oooh, yes we certainly need documentation for this. Let's move this for 0.14 and make it a release-blocker.

**Comment by aronasorman** [comment]
We've rewritten the coachreports system, and we are expecting documentation regarding that.

We also document how our points system works, although it's a bit outdated now( see https://github.com/learningequality/ka-lite/issues/3665). I think we can close this.
