### ISSUE TITLE
django_sessions table updates are slow on RPi

### ISSUE THREAD

**Issue by gimick** [learningequality/ka-lite#816]
Updates to the django_sessions table are normally using the key-field session_key.

Just now the only index on the table is expiration_date.

The slowness is presumably due to sequential searching through all sessions.

The django_sessions table is upstream, and NOT ka-lite code.

Not a show-stopper just now.

**Comment by aronasorman** [comment]
Closing this; will revisit once we have a benchmarking suite in place.
