### ISSUE TITLE
Store language pack zip files, rather than unzipping and discarding them

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#872]
Currently, language pack zip files are downloaded and unzipped from a memory buffer, which is then discarded:
https://github.com/learningequality/ka-lite/pull/864/files#r7079056

It would be good to download the zip file, then unpack the zip, and keep it around, in order to facilitate a) being able to pass this zip file onwards to other devices once we have P2P content sync, and b) being able to load a language pack zip file from disk, for installation on completely offline servers.

**Comment by aronasorman** [comment]
Wontfix, due to the impending refactoring of language packs into channels + the new syncing mechanism in the works.
