### ISSUE TITLE
Sync errors details not available 

### ISSUE THREAD

**Issue by gimick** [learningequality/ka-lite#920]
Branch release 0.11
**CENTRAL SERVER**
The device syncing history is showing errors for every sync event.
There is no option to drill-down and discover what those errors are.
ALSO, the corresponding jobs on the distributed server's django admin intrerface are not reporting any errors at all.

**Comment by benjaoming** [comment]
Happens now to a certain extend.

![screenshot from 2016-06-13 16 06 37](https://cloud.githubusercontent.com/assets/374612/16010296/d8d581d6-3180-11e6-92e2-494d39f9b6b8.png)
