### ISSUE TITLE
Student's account management page layout and wording 

### ISSUE THREAD

**Issue by wangguan59** [learningequality/ka-lite#930]
![screen shot 2013-11-03 at 7 08 44 pm](https://f.cloud.github.com/assets/1319955/1462569/84cbad0c-44fe-11e3-88f0-bb115a95ad67.png)
I would suggest to change the wording to "My report" to replace "Account management page for..."
"Change password" button has too much visual weight. I think change it to "Update account " with simpler button might be better. 
and assigned to myself

**Comment by rtibbles** [comment]
No longer relevant.
