### ISSUE TITLE
KA Lite fails to launch install script (by default) on Mac; need to register for Developer ID

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#937]
http://support.apple.com/kb/ht5290
https://developer.apple.com/developer-id/

There are ways to [work around this](http://osxdaily.com/2012/07/27/app-cant-be-opened-because-it-is-from-an-unidentified-developer/), but this default behavior can be confusing.

![image](https://f.cloud.github.com/assets/4072455/1485260/6be6bf64-4712-11e3-8b59-dd67791ca109.png)

**Comment by aronasorman** [comment]
Solved on the latest learningequality/installers master branch.
