### ISSUE TITLE
Prompt admins to select a default facility, as quickly as possible

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#946]
Admins aren't requested to select a default facility unless they do some action requiring a facility to be selected.  However, users need to know their facility before logging in, and so it's helpful to select one essentially immediately.

Find ways to prompt admins (upon login?  upon facility creation?) to select a default facility.

**Comment by aronasorman** [comment]
Not a priority; let's open another issue if this is a big UX problem.
