### ISSUE TITLE
No way to access 3rd party exercise logs in tabular view coach report

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#950]
This is more Phase 2-ish, but brings together other issues.

Because the tabular view is using queries based on the knowledge map, it can ignore changes to the topic tree that aren't reflected in the knowledge map JSON files.

We should:
* Eliminate those knowledge map JSON files, and include them in our topics.json
* (same as above, but more explicit) Mark (with metadata) the nodes that do appear on the knowledge map, within topics.json

**Comment by rtibbles** [comment]
Now possible.
