### ISSUE TITLE
Exercise logs for exercises eliminated from the topic tree are unqueryable.

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#951]
We can add a node onto the topic tree for coach reports, that represents all uncategorized / unrecognized exercise logs.  Otherwise, that data is invisible.

This is true similarly for student's own report--they've done work that they no longer have access to view their progress on, if the topic tree eliminates exercises--yet that data still lives in the database.

**Comment by aronasorman** [comment]
Not a priority; let's reopen if people want to requery old exercises.
