### ISSUE TITLE
Review EVERY DB query made

### ISSUE THREAD

**Issue by bcipolli** [learningequality/ka-lite#953]
`git grep \\.filter | grep \\.py | grep -v static/`
`git grep get_object_or_`
`git grep .objects.get | grep -v test`

Worst case performance scenario: queries inside loops, or querysets handed off to templates directly (without conversion to list first).

It's not enough to view the grep output--each must be investigated individually.

We've got release-0.11 pretty blazing fast already, but there's still plenty of query optimization remaining.  Remember: queries are fast in the single user scenario, but blocking in the multi-user SQLite scenario, and should be avoided as much as possible.

**Comment by aronasorman** [comment]
Issue is vague; let's open issues with more specific problems.
